- match2/commons/brkts_wiki_specific_base.lua
- match2/commons/match.lua
- match2/commons/match_group.lua
- match2/commons/match_group_base.lua
- match2/commons/match_group_display.lua
- match2/commons/match_group_display_bracket.lua
- match2/commons/match_group_display_helper.lua
- match2/commons/match_group_display_matchlist.lua
- match2/commons/match_subobjects.lua
- match2/commons/match_summary_base.lua
- match2/commons/opponent_display.lua
- match2/wikis/rocketleague/brkts_wiki_specific.lua
- match2/wikis/rocketleague/match_group.lua
- match2/wikis/rocketleague/opponent_display.lua
- match2/wikis/valorant/big_match.lua
- match2/wikis/valorant/brkts_wiki_specific.lua
- match2/wikis/valorant/match_group.lua
- match2/wikis/valorant/match_summary.lua
Push already existing code from modules, including RL and Valorant specific modules
> Initial setup

- match2/wikis/starcraft/brkts_wiki_specific.lua
- match2/wikis/starcraft/match_group_legacy.lua
- match2/wikis/starcraft/match_group_legacy_default.lua
- match2/wikis/starcraft/match_legacy.lua
- match2/wikis/starcraft2/match_group_legacy.lua
Add the BW specific Modules that are located on the BW wiki.
https://liquipedia.net/starcraft/Module:Brkts/WikiSpecific
https://liquipedia.net/starcraft/Module:Match/Legacy (SMW part is still WiP)
https://liquipedia.net/starcraft/Module:MatchGroup/Legacy/Default
https://liquipedia.net/starcraft/Module:MatchGroup/Legacy
> Add BW based match2 Modules

- match2/wikis/valorant/match_summary.lua
missing changes in match2/wikis/valorant/match_summary.lua
> Sync from live modules for valorant

- match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Add additional fallback Variables in the Date processing
> Adjust Date Processing (stacked, first)

- match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Adjust TeamIcon/TeamPage retrieval
> Adjust Icon/TeamPage retrieval (stacked)

- match2/commons/starcraft_starcraft2/match_group_input_starcraft_ffa.lua
Add pbg/bg processing in FFA Input processing
> Add pbg/bg processing in FFA Input processing

- match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Remove some redundant stuff and add a default "tbd" for team template storage
> Remove redundant (stacked)

- match2/commons/starcraft_starcraft2/match_group_input_starcraft_ffa.lua
Fix allowed colors.
The color "mid" should be an alias for "stay" there is no "bg-mid" class
> Fix allowed colors

- match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
* Switch to the new `varDefaultMulti` instead of using nested `varDefault` calls
> Switch to the new `varDefaultMulti` (stacked)

- match2/wikis/starcraft2/match_group_legacy.lua
* Add option to disable storage for Legacy brackets
> Add option to disable storage for Legacy brackets (stacked)

- match2/commons/match_group_base.lua
> Add null handling for next match

- match2/wikis/starcraft2/match_group_legacy.lua
Add option to disable duplicate Check by passing `noDuplicateCheck` to the luaBracket.
> Add option to disable duplicate Check (stacked)

- match2/commons/match_group_display_matchlist.lua
> adhere-comments-of-PR-#65

- match2/commons/match_group_base.lua
> Invert logic

- match2/wikis/starcraft2/match_group_legacy_default.lua
Move the map adding stuff into an extra function.
This way that function can be accessed by the Custom mappings.
> Move map stuff into extra function

- match2/wikis/starcraft2/match_group_legacy.lua
Change double to single quotes
to resolve comment of #83
> Change double to single quotes (stacked, resolves comment of #83 )

- match2/wikis/starcraft2/match_legacy.lua
Switch double to single quotes
> Switch double to single quotes (stacked)

- match2/wikis/rocketleague/brkts_wiki_specific.lua
- match2/wikis/rocketleague/match_group_legacy_default.lua
* Add Function in `Module:Brkts/WikiSpecific` to allow legacy conversion for solo (type) brackets
* Add file https://liquipedia.net/rocketleague/Module:MatchGroup/Legacy/Default
> Add & Adjust RL Legacy Conversion

- match2/wikis/rocketleague/match_group_legacy_default.lua
Forgot to change it back for the PR (set it to 1 so that the logs were not long af)
> Adjust number

- match2/wikis/rocketleague/match_group_legacy_default.lua
* Add functions that make creating custom mappings way easier (imo) -- similar to the sc2 functions
> Add functions for custom mappings (stacked)

- match2/wikis/rocketleague/match_group_legacy_default.lua
code style (just a different PR to increase readability of the PRs)
> code style (stacked)

- match2/wikis/rocketleague/opponent_display.lua
Copy opponent_display.lua from commons so we have a basis for the changes i propose in #106
> Copy from Commons to RL (stacked, first, just basis for real changes)

- match2/wikis/rocketleague/match_summary.lua
Add optional gameHeader display
> Add optional gameHeader display

- match2/wikis/rocketleague/brkts_wiki_specific.lua
Fix LP tier and tiertype in combination with the change to `Template:Infobox league`
> Fix LP tier and tiertype

- match2/commons/match_group_legacy.lua
Add Workaround for empty opponents with filled in macth summary
> Add Workaround for empty opponents

- match2/commons/match_group_legacy.lua
kick `RxMBR` match if score2 is empty
> kick `RxMBR` match if score2 is empty

- match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Add Safety regarding date format for the team template historical resolve
> Add Safety regarding date format

- match2/commons/match_group_legacy.lua
Disable 3rd place match if opponent1 is empty
> Disable 3rd place match if opponent1 is empty (stacked, first)

- match2/wikis/rocketleague/match_group_legacy_default.lua
*Enable Lower header handling
* some `'` vs `"` stuff
* "outsource" the map adding into the existing function
(mostly copied from SC2)
needs to be in combination with #125
> Enable Lower header handling

- match2/commons/match_group_legacy.lua
*Option to disable duplicate check
*Option to disable Storage, also triggered by "disable_SMW_storage wiki var
> Add Option to disable storage and duplicate check (stacked)

- match2/wikis/rocketleague/match_legacy.lua
Add mode to smw storage, so it can be used in some swm queries
(we probably should replace those once everything is converted ...)
> Add mode to smw storage

- match2/commons/match_group_legacy.lua
* Enable Lower header handling
* Switch from double to single quote
* Switch from `p` as package to `Legacy`
(mostly copied from SC2)
> Enable Lower header handling (stacked)

- match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- match2/wikis/rocketleague/brkts_wiki_specific.lua
* remove bad string.gsub in both RL and SC/SC2 input processing
* change some variable names in the sc2 version too (better code style)
> Fix hjps stupid mistakes

- match2/wikis/rocketleague/get_match_group_copy_paste_wiki.lua
> fix maps copy paste

- match2/commons/get_match_group_copy_paste_wiki_base.lua
> fix map copy paste

- match2/wikis/rocketleague/brkts_wiki_specific.lua
> avoid indexing nil

- match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
resolve redirect for vetoed maps
> resolve redirect for vetoed maps

- match2/commons/match_group_base.lua
Add Parent parameter to match for storage in lpdb once set up in lpdb
> Add Parent parameter to match

- match2/commons/match_group_base.lua
> unify Quotes (MatchGroup/Base)

- match2/commons/template_match.lua
> unify Quotes (TemplateMatch)

- match2/commons/template_match.lua
fix `bracketsection`
(single vs double quotes solved in next PR)
> fix `bracketsection`

- match2/wikis/rocketleague/brkts_wiki_specific.lua
- match2/wikis/rocketleague/match_group_legacy_default.lua
Enable custom links for solo opponents in LegacyBrackets
> Enable custom links for solo opp. in LegacyBrkts

- match2/wikis/rocketleague/brkts_wiki_specific.lua
resolve redirect for `opponent.name`
> resolve redirect for `opponent.name` (stacked, first)

- match2/wikis/rocketleague/brkts_wiki_specific.lua
- match2/wikis/rocketleague/match_legacy.lua
> Add walkover handling (stacked)

- match2/wikis/rocketleague/legacy_match_list.lua
allow date to be header if it header isn't set
> allow date to be header if header isn't set

- match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- match2/wikis/rocketleague/brkts_wiki_specific.lua
fix due to rename in extension
> Fix due to rename in extension

- match2/wikis/starcraft2/legacy_player_cross_table.lua
add option to display it as matchList
> add option to display it as matchList

- match2/wikis/rainbow_six/brkts_wiki_specific.lua
- match2/wikis/rainbow_six/match_legacy.lua
- match2/wikis/rainbow_six/match_summary.lua
atm still wip, hence the draft status
(Rathoz wanted a first feedback)
> Add some R6 modules

- match2/commons/match_group_display_helper.lua
> change date format

- match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
> store patch in match2game

- .luacheckrc
> add select as allowed global

- standard/links.lua
* add more links
* add customization option for links that get used differently by different infoboxes
> add more links & customization option

- components/infobox/commons/infobox.lua
- components/infobox/commons/infobox_series.lua
- components/infobox/commons/infobox_team.lua
* Flags: use the Flags module instead of the safeExpand
* Links pass the type of infobox along where needed
> adjust Flags and Links

- components/match2/wikis/rainbow_six/brkts_wiki_specific.lua
- components/match2/wikis/rainbow_six/match_summary.lua
* Store Epoch=0 when there's no date/datetime added to a match
* Only display countdown for datetime (dateIsExact)
* If there's a date (but no time), display only the date (no countdown)
> R6 - Improvements in the Datetime and Date displaying

- components/infobox/commons/infobox_team.lua
either this (maybe with a different function name) or we have the links at the bottom for infobox team (and player) on sc2:
> add addCustomContent option (stacked)

- components/match2/wikis/rainbow_six/match_summary.lua
Span caused issues with long comments.
> R6 - Removed span from comment.

- components/infobox/wikis/starcraft2/infobox_series_custom.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
adjust to changes on the commons modules
* rename function
> adjust to changes on the commons modules

- components/match2/wikis/brawlstars/brkts_wiki_specific.lua
Add brkts/wikispecific module for brawlstars
* mostly a copy of the RL module
> Add brkts/wikispecific module for brawlstars

- components/infobox/wikis/starcraft2/infobox_series_custom.lua
> fix bug for custom vars

- standard/localisation.lua
use option `frameOnly`
together with the cleanup for module usage i did yesterday on all wikis we now should be able to use it without the fallbacks
> use option `frameOnly`

- components/infobox/commons/infobox_team.lua
kick sponsor display as per https://discord.com/channels/321003439431745537/321641940879802368/877119378947190794
> kick sponsor

- components/infobox/commons/infobox.lua
The chronology row loop was missing an increment, causing an infinite loop
> Actually increment the chronology index

- components/infobox/commons/infobox_league.lua
Stacks on #186 
Set shared variables across all wikis, and provide a way of setting wiki-specific variables
> Set infobox league vars

- components/infobox/commons/infobox.lua
> Adjust chronology display

- components/match2/wikis/rocketleague/brkts_wiki_specific.lua
add support for draws
before:
after:
> add support for draws

- components/infobox/commons/infobox_league.lua
- components/infobox/wikis/rocketleague/infobox_league_custom.lua
> Reformat infobox league

- components/infobox/commons/infobox_league.lua
- components/infobox/wikis/rocketleague/infobox_league_custom.lua
Convert the infobox to use #217
> Convert Infobox/League to use Infobox/Basic

- components/infobox/wikis/rocketleague/infobox_league_custom.lua
> Create league liquipediatier

- components/infobox/commons/infobox.lua
> fix chronology

- components/infobox/wikis/rocketleague/infobox_league_custom.lua
> Add mode cell to RL league infobox

- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/match_group_display_matchlist.lua
These styles were added before the current round of css cleanup. The changes have already been applied to pages.
> [css1] Lua changes relating to style cleanup

- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/match_group_util.lua
This change reworks displaying of headers so that they can appear in more places than previously.
Examples (from bracket designer)
Old
New
Example of actual tournament exhibiting this type of header: https://liquipedia.net/starcraft2/IEM_Season_XII_-_PyeongChang
Old
New
Old
New
Notes
- For it to work the header arg must be set in the bracket template. This can be done by regenerating the bracket template from the bracket designer.
- 
Changes
- Headers can now appear in more places than before
- The header computation is moved to a separate stage before render, similar to layout computation
- Added depth and round number calculation. This will be moved to lpdb at a later stage.
- Rooted trees in the bracket were right aligned as a workaround because the round number wasn't available. Now …
> [css4] Rework header display

- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/match_group_util.lua
- Rename headMatchIds -> rootMatchIds
- Include the third place match in rootMatchIds. Layout wise it remains alongside the finals match, and not as a separate root
- Add `bracket.bracketDatasById` as a shortcut to `bracket.matchesById[matchId].bracketData`, since it's used very frequently
> [css5] rootMatchIds improvements

- components/infobox/commons/infobox_patch.lua
- components/infobox/wikis/starcraft2/infobox_patch_custom.lua
used on Patch pages on several wikis
example: https://liquipedia.net/starcraft2/Patch_1.1.0
> add infobox patch implementation

- components/infobox/commons/infobox_show.lua
- components/infobox/wikis/starcraft2/infobox_show_custom.lua
used on show pages
example: https://liquipedia.net/starcraft2/Day9_Daily
> add infobox show

- components/infobox/wikis/rocketleague/infobox_league_custom.lua
Add Rocket League specific LPDB data
> Add RL league LPDB data

- components/infobox/commons/infobox_league.lua
Make sure to convert extradata to JSON
> Convert League LPDB extradata to JSON

- components/infobox/commons/infobox_team.lua
- components/infobox/wikis/rocketleague/infobox_team_custom.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
convert infobox team to use infobox basic
> convert infobox team to use infobox basic

- components/infobox/commons/infobox_cell.lua
Make sure to reset class variables in Infobox/Cell, so that they don't have effect in the next iteration
> Reset class vars in cell

- components/infobox/commons/infobox_scene.lua
convert infobox scene to use `Module:Infobox/Basic`
> convert infobox scene to use `Module:Infobox/Basic`

- components/infobox/commons/infobox_series.lua
- components/infobox/wikis/rocketleague/infobox_series_custom.lua
- components/infobox/wikis/starcraft2/infobox_series_custom.lua
convert infobox series to use `Module:Infobox/Basic`
> convert infobox series to use `Module:Infobox/Basic`

- components/infobox/commons/infobox_company_custom.lua
- components/infobox/commons/infobox_league.lua
- components/infobox/commons/infobox_map.lua
- components/infobox/commons/infobox_patch.lua
- components/infobox/commons/infobox_show.lua
- components/infobox/commons/infobox_strategy.lua
- components/infobox/wikis/rocketleague/infobox_company_custom.lua
- components/infobox/wikis/rocketleague/infobox_league_custom.lua
- components/infobox/wikis/rocketleague/infobox_team_custom.lua
- components/infobox/wikis/starcraft2/infobox_map_custom.lua
- components/infobox/wikis/starcraft2/infobox_patch_custom.lua
- components/infobox/wikis/starcraft2/infobox_show_custom.lua
- components/infobox/wikis/starcraft2/infobox_strategy_custom.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
switch to lowercase & use self
> switch to lowercase & use self

- components/infobox/commons/infobox_series.lua
- standard/localisation.lua
* switch to use localization module instead of template
* fix some `self.frame` to `self.infobox.frame`
* allow a simple "error" as return instead of the normal error message in `Module:Localisation`
> Switch to use localization module

- components/infobox/commons/infobox_basic.lua
> Add a catch for nil

- components/infobox/wikis/rocketleague/infobox_league_custom.lua
Adds the game cell to the Rocket League Infobox/League
> Add Game cell for Rocket League

- components/infobox/commons/infobox_league.lua
- components/infobox/wikis/rocketleague/infobox_league_custom.lua
Adds support for multiple locations, as well as TBD locations
> Complete the Infobox/League location implementation

- standard/links.lua
add function `makeFullLinksForTableItems` a table version of `makeFullLink`
> add function `makeFullLinksForTableItems`

- components/infobox/commons/infobox_game.lua
add `Module:Infobox/Game` (used on pages of game descriptions)
example: https://liquipedia.net/starcraft2/Heart_of_the_Swarm
> add `Module:Infobox/Game`

- components/infobox/commons/infobox_game.lua
doing this one extra since this module was merged into main after the pr for the headers was started
> Add header for `module:Infobox/Game`

- components/match2/wikis/rainbow_six/match_legacy.lua
- components/match2/wikis/rainbow_six/match_summary.lua
* Convert extradata.matchsection in match2->match1 mapping
* Fixed that the css class weren't applied correctly for maps that ended with a draw (incorrect if statement)
> R6 - Extradata.matchsection in legacy mapping, fix css class for map draws

- components/infobox/commons/infobox.lua
Our links are currently not sorted nicely. This PR sorts them alphabetically
> Iterate through links alphabetically

- components/infobox/wikis/starcraft2/infobox_series_custom.lua
> Adjust custom variables

- components/match2/commons/bracket_alias.lua
- components/match2/commons/brkts_wiki_specific_base.lua
- components/match2/commons/display_util.lua
- components/match2/commons/get_match_group_copy_paste.lua
- components/match2/commons/get_match_group_copy_paste_wiki.lua
- components/match2/commons/get_match_group_copy_paste_wiki_base.lua
- components/match2/commons/match.lua
- components/match2/commons/match_group.lua
- components/match2/commons/match_group_base.lua
- components/match2/commons/match_group_display.lua
- components/match2/commons/match_group_display_bracket_template.lua
- components/match2/commons/match_group_legacy.lua
- components/match2/commons/match_group_util.lua
- components/match2/commons/match_subobjects.lua
- components/match2/commons/match_summary_base.lua
- components/match2/commons/template_match.lua
looks like yesterday evening wasn't my best ...
> fix header

- components/match2/wikis/rocketleague/brkts_wiki_specific.lua
Update tournament vars for Rocket League
> Use `tournament_enddate` instead of `tournament_date`

- components/infobox/commons/infobox_patch.lua
- components/infobox/wikis/starcraft2/infobox_patch_custom.lua
> Add LPDB storage

- components/infobox/commons/infobox_league.lua
Use function `makeFullLinksForTableItems` from `Module:Links` to allow more links for LPDB storage
stacks on #277
> Use a function from `Module:Links` (stacked)

- components/match2/commons/match_group_display_helper.lua
Adjust date display so that it does not display the time and countdown in case it is not an exact date
> Adjust date display

- components/match2/wikis/starcraft2/get_match_group_copy_paste_wiki.lua
> Fix a concat boolean bug

- standard/page.lua
Add `Module:Page` as suggested in #286 
* function that can check for the existence of a page
* function that can make internal links (with the option to let it check for the existence first)
* function that can make external links
> Add `Module:Page`

- components/infobox/commons/infobox_league.lua
as discussed in #287 
* adjust series storage to resolve redirec
* add abbreviation as fallback for shortname
* lower case game string for the storage
additional:
* switch `League:_exists` to use `Module:Page` instead
> Adjust Vars & LPDB and page exist calls

- components/infobox/commons/infobox_widget_cell.lua
See #304 for overview of this project.
Creates the Cell widget, representing a single property in the infobox
> Create Cell widget

- components/infobox/commons/dev_infobox.lua
- components/infobox/commons/infobox_widget_cell.lua
> Finish support for Customizable in Infobox

- components/infobox/commons/infobox_widget_links.lua
See #304 for overview.
Creates the Link widget, which shows icons for links in an infobox.
> Create Links widget

- components/infobox/commons/infobox_widgets.lua
Provide all Widgets as a library, from just one file.
> Provide all widgets from one export file

- components/infobox/commons/infobox_widget_injector.lua
- components/infobox/wikis/pubg/infobox_company_custom.lua
Add `Module:Infobox/Company/Custom`
> Add `Module:Infobox/Company/Custom`

- components/infobox/commons/infobox_widget_center.lua
> Remove empty centered cells

- components/infobox/commons/infobox_basic.lua
- components/infobox/commons/infobox_company.lua
- components/infobox/commons/infobox_company_custom.lua
- components/infobox/commons/infobox_widget_injector.lua
- components/infobox/commons/infobox_widgets.lua
- components/infobox/wikis/pubg/infobox_company_custom.lua
- components/infobox/wikis/rocketleague/infobox_company_custom.lua
Migrates Infobox/Company over to table based layout, see #304. Merges into #321 
Cannot be merged until Module:Infobox has been switched over. It is currently fully functional using /dev modules though.
> Migrate infobox company

- components/infobox/commons/infobox.lua
- components/infobox/commons/infobox_basic.lua
- components/infobox/commons/infobox_team.lua
- components/infobox/wikis/rocketleague/infobox_team_custom.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Migrates Infobox/Team over to table based layout, see #304. Merges into #321
> Migrate Infobox Team

- components/match2/wikis/rainbow_six/match_legacy.lua
Added storage of winner to smw in legacy mapping
> (R6) Added storage of winner to smw in legacy

- components/infobox/commons/infobox_skill.lua
- components/infobox/wikis/starcraft2/infobox_skill_ability.lua
- components/infobox/wikis/starcraft2/infobox_skill_spell.lua
Migrates Infobox/Skill over to table based layout, see #304 . Merges into #321
Custom Modules:
> Migrate Infobox Skill

- components/infobox/commons/infobox_series.lua
- components/infobox/commons/infobox_widget_injector.lua
- components/infobox/wikis/fortnite/infobox_series_custom.lua
- components/infobox/wikis/rocketleague/infobox_series_custom.lua
- components/infobox/wikis/starcraft2/infobox_series_custom.lua
Migrates Infobox/Series over to table based layout, see #304. Merges into #321
> Migrate Infobox Series

- components/infobox/commons/infobox_map.lua
- components/infobox/wikis/starcraft2/infobox_map_custom.lua
> Migrate Infobox map

- components/infobox/commons/infobox_widget_breakdown.lua
Needed for sc, sc2, warcraft in infoboxes league and team
> Add Breakdown Widget

- standard/links.lua
* allow to also make links for entries that appended a number
* examples:
* * esl2, twitch2, bracket2, .....
> Improve `makeFullLinksForTableItems`

- components/infobox/commons/infobox_game.lua
- components/infobox/commons/infobox_game_custom.lua
Migrates Infobox/Game over to table based layout, see #304. Merges into #321 
* migrate commons module
* add base version of custom module on commons
> Migrate Infobox game

- components/infobox/commons/infobox_show.lua
- components/infobox/commons/infobox_show_custom.lua
- components/infobox/wikis/starcraft2/infobox_show_custom.lua
Migrates Infobox/Show over to table based layout, see #304. Merges into #321 
* migrate commons module
* migrate sc2 custom module
* add base version of custom module on commons
> Migrate Infobox show

- components/infobox/commons/infobox_league.lua
- components/infobox/commons/infobox_map.lua
- components/infobox/commons/infobox_widget_chronology.lua
- components/infobox/wikis/counterstrike/infobox_league_custom.lua
- components/infobox/wikis/rocketleague/infobox_league_custom.lua
Migrates Infobox/League over to table based layout, see #304. Merges into #321
> Migrate Infobox League

- components/infobox/commons/infobox_team.lua
* indents (tabs vs space)
* `args.history` --> `args.created`
> Fix some stuff in infobox team

- components/infobox/wikis/starcraft2/infobox_series_custom.lua
> Bug fix infobox series sc2

- components/infobox/wikis/starcraft2/infobox_skill_spell.lua
> Fix Race Category handling

- components/infobox/wikis/starcraft2/infobox_skill_ability.lua
Fix Race Category handling (ability)
> Fix Race Category handling (ability)

- components/infobox/commons/infobox_basic.lua
Adjust `isEmpty` check for `getAllArgsForBase`
> Adjust `isEmpty` check for `getAllArgsForBase`

- components/infobox/wikis/starcraft2/infobox_series_custom.lua
fix tier issue for sc2 custom infobox series
> Fix tier issue

- components/infobox/commons/infobox_league.lua
- components/infobox/wikis/starcraft2/infobox_league_custom.lua
custom part of infobox league for SC2
(image is zoomed 75%)
redo of #287 (rebase issues there)
> Add `Module:Infobox/League/Custom`

- components/infobox/commons/infobox_team.lua
- components/infobox/wikis/rocketleague/infobox_team_custom.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Add LPDB storage to infobox team (redo of #339 after rebase issues and so we can split some of it up)
* add LPDB base support in the commons module
> Add LPDB storage to infobox team

- components/infobox/commons/infobox.lua
Only display adbox if this is the first infobox on the page
> Only display ad box for first infobox

- components/infobox/wikis/pubg/infobox_company_custom.lua
Fix bug on pubg infobox company
> Fix bug on pubg infobox company

- components/infobox/commons/infobox_widget_center.lua
Fix bug for centered cells
* avoid nil
> Fix bug for centered cells

- components/infobox/wikis/starcraft2/infobox_strategy_custom.lua
> Make `popularized` a link

- components/infobox/commons/infobox_campaign.lua
- components/infobox/commons/infobox_unofficial_world_champion_custom.lua
* commons version of `Module:Infobox/UnofficialWorldChampion/Custom`
* `Module:Infobox/Campaign` (this one is just rofl ...)
> Add some tiny infobox modules

- components/infobox/commons/infobox_strategy.lua
- components/infobox/wikis/starcraft2/infobox_strategy_custom.lua
Adjust `Module:Infobox/Strategy` + Custom version to allow it to also be used for `Template:Infobox technique`
> Merge Infobox technique into infobox strategy

- components/match2/wikis/rainbow_six/brkts_wiki_specific.lua
* Added facebook stream to brkts
* Removed unneeded pair of ()
> Add Facebook stream to R6 matches

- components/infobox/commons/infobox_website.lua
- components/infobox/commons/infobox_website_custom.lua
* `Module:Infobox/Website`
* `Module:Infobox/Website/Custom` (Commons)
> Add `Infobox website`

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
> Add missing space

- components/infobox/commons/infobox_campaign_mission.lua
- components/infobox/commons/infobox_widget_header.lua
- components/infobox/wikis/starcraft2/infobox_campaign_mission_custom.lua
* Add `Module:Infobox/CampaignMission`
* Add `Module:Infobox/CampaignMission/Custom` (SC2)
* Adjust `Module:Infobox/Widget/Header` (needed for this infobox ;;; alternatively we could add `Module:Infobox/Widget/Image`)
This infobox is (atm) only used on SC2
> Add `Infobox campaign mission`

- components/infobox/commons/infobox_widget_header.lua
re-add subHeader without error
stacked on #387
> Re-add subHeader without error

- components/infobox/wikis/ageofempires/infobox_league_custom.lua
> Add `Module:Infobox/League/Custom` for ageofempires

- components/match2/commons/starcraft_starcraft2/match_group_display_bracket_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/commons/starcraft_starcraft2/opponent_display_starcraft.lua
> Allow race & flag for literals

- components/hidden_data_box/commons/hidden_data_box.lua
Improve code for HiddenDataBox a bit
thx @Rathoz ^^
> Improve code for HiddenDataBox

- components/match2/commons/match_group_base.lua
- components/match2/commons/match_group_legacy.lua
- components/match2/wikis/rocketleague/legacy_match_list.lua
- components/match2/wikis/starcraft2/legacy_player_cross_table.lua
- components/match2/wikis/starcraft2/match_group_legacy.lua
* Display Warnings above each Legacy Bracket/Matchlist
* Display Warnings above each Bracket/Matchlist with duplicate id
* only do that when logged in
> Add legacy warnings

- components/infobox/wikis/starcraft2/infobox_strategy_custom.lua
> Handle empty string

- components/infobox/commons/infobox_widget_links.lua
- standard/links.lua
Add `faceit-c` to Links, which requires us to add a suffix dict
> Add `faceit-c`

- components/match2/commons/match_group.lua
- components/match2/commons/match_group_base.lua
- components/match2/commons/match_group_display.lua
There's a lot of entry points for brackets and matchlists. Added a bit of documentation, in preparation of consolidating them in the future.
> Document match group entry points

- components/infobox/extensions/commons/age.lua
Add header so this file gets pushed to commons
`Module:Age` exists, so using a different name here
> Add header

- components/infobox/commons/infobox_person.lua
- components/infobox/wikis/starcraft2/infobox_person_player.lua
WAITING FOR #421 
rewrite (table version)
* `Module:Infobox/Person`
* `Module:Infobox/Person/Player`
Warning: STILL MISSING THE AGE STUFF!!!
> Rewrite infobox person

- components/infobox/commons/infobox_person.lua
- components/infobox/wikis/starcraft2/infobox_person_map maker.lua
stacked on #386 
may need some changing depending on decisions of #386 
`Infobox mapmaker` (SC2) implementation, based on `Infobox/Person`
(birthdate display missing as it is not implemented in the base `Infobox/Person`)
> Add Infobox mapmaker

- components/infobox/commons/infobox_person.lua
- components/infobox/wikis/starcraft2/infobox_person_commentator.lua
stacked on #386 
may need some changing depending on decisions of #386 
`Infobox commentator` (SC2) implementation, based on `Infobox/Person`
(birthdate display missing as it is not implemented in the base `Infobox/Person`)
> Add Infobox commentator

- components/infobox/commons/infobox_person.lua
- components/infobox/commons/infobox_person_user.lua
- components/infobox/wikis/starcraft2/infobox_person_user.lua
stacked on #386 
uses `Infobox/Person` as a basis
* Commons base version that should serve most wikis directly
* SC2 override due to race stuff
(age stuff missing due to it not being added to Infobox/Person)
> Add Infobox User

- components/infobox/wikis/halo/infobox_team_custom.lua
> Add infobox team custom

- components/match2/wikis/halo/brkts_wiki_specific.lua
- components/match2/wikis/halo/match_summary.lua
* `Module:Brkts/WikiSpecific`
* `Module:MatchSummary`
* FFA Support not yet added
> Add halo match2 implementation

- components/match2/commons/match_summary_ffa.lua
- components/match2/commons/starcraft_starcraft2/README.txt
- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft_ffa.lua
- components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_summary_ffa_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
- components/match2/wikis/starcraft/brkts_wiki_specific.lua
- components/match2/wikis/starcraft2/brkts_wiki_specific.lua
Using `Starcraft` over `StarCraft` since it's one word (even though Blizzard uses StarCraft for branding)
> Capitalization: FFA -> Ffa, StarCraft -> Starcraft

- components/match2/wikis/halo/bracket_alias.lua
- components/match2/wikis/halo/get_match_group_copy_paste_wiki.lua
stacked on #425 
Add match2 copy paste generators to halo wiki
usage via
* https://liquipedia.net/halo/Special:RunQuery/BracketCopyPaste
* https://liquipedia.net/halo/Special:RunQuery/MatchListCopyPaste
> Add match2 copy paste generators to halo wiki

- components/infobox/wikis/halo/infobox_league_custom.lua
> Add infobox league custom

- components/match2/wikis/halo/match_summary.lua
> Add match vod display

- standard/league_icon.lua
* Remove outer span
* add wiki params for copy paste code
> Fix Display Bug

- components/infobox/wikis/halo/infobox_league_custom.lua
* remove unused function
* adjust map display to include the modes
* add storage for maps (incl. their modes) into lpdb
* fix a typo
> Adjust map stuff in infobox league custom

- components/infobox/extensions/commons/age.lua
> Avoid concating nil

- components/infobox/wikis/halo/infobox_league_custom.lua
stacked on #435 
Set `tournament_mode` as `solo` if `args.player_number` is set
> Set `tournament_mode`

- components/match2/wikis/halo/brkts_wiki_specific.lua
Resolve Redirect of opponent name in Match Input processing
> Resolve Redirect of opponent name

- components/infobox/commons/infobox_person.lua
add Default image for infobox person
> Add Default image for infobox person

- components/match2/commons/match_group.lua
- components/match2/commons/match_group_base.lua
- components/match2/wikis/valorant/match_group.lua
Expand the number of modules with dev variants slightly
> [mg1] Enable dev on MatchGroup/Base and MatchGroup/Display

- components/infobox/wikis/halo/infobox_league_custom.lua
> Adjust LPDB custom storage

- components/infobox/wikis/halo/infobox_league_custom.lua
stacked on #446
* set `tournament_currency_rate` var for usage inside prize pools
> Adjust prize pool function

- components/infobox/wikis/halo/infobox_league_custom.lua
stacked on #448 
* Add tier highlighting for `|hcs-sponsored=true`
* store `args['hcs-sponsored']` into `publishertier`
> Add tier highlighting for `|hcs-sponsored=true`

- components/infobox/wikis/halo/infobox_person_player.lua
stacked on #443 & waiting for #444 
* kick region display but store it in lpdb
as per https://discord.com/channels/93055209017729024/882959691523690536/891626728684929034
> Remove region display

- components/infobox/wikis/halo/infobox_league_custom.lua
stacked on #449 
* store game in a standardized way
> Adjust game storage in infobox league

- components/infobox/wikis/halo/infobox_league_custom.lua
Add var `tournament_publishertier` in halo custom infobox league implementation
> Add var `tournament_publishertier`

- components/infobox/extensions/commons/age.lua
Fix age display bug
* if empty death/birth date is entered the death/birth field is displayed with empty value
> Fix age display bug

- components/match2/wikis/halo/brkts_wiki_specific.lua
Add `publishertier` storage in halo matches
> Add `publishertier` storage in matches

- components/match2/commons/match_group_base.lua
- components/match2/commons/match_group_display.lua
- components/match2/commons/match_group_input.lua
Move code that reads matches from input args from MatchGroup/Base to MatchGroup/Input
> [mg6] Move match group input processing to dedicated module

- components/infobox/commons/infobox_league.lua
- standard/league_icon.lua
* adjust `LeagueIcon.getIconFromTemplate` call from `Module:Infobox/League`
* add icon as default fall back for iconDark
> Fix Icon bug

- components/infobox/wikis/starcraft2/infobox_person_commentator.lua
- components/infobox/wikis/starcraft2/infobox_person_map maker.lua
- components/infobox/wikis/starcraft2/infobox_person_player.lua
- components/infobox/wikis/starcraft2/infobox_person_user.lua
Kick region display for sc2 person infoboxes
* Commentator
* User
* Player
* MapMaker
> Kick region display for sc2 person infoboxes

- components/match2/commons/match_group_display.lua
- components/match2/commons/starcraft_starcraft2/match_group_display_bracket_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_group_display_matchlist_starcraft.lua
Few fixes to the previous merges
+ enables separate /dev module for StarcraftMatchSummary
> Few fixes + Add /dev to StarcraftMatchSummary

- standard/links.lua
* currently links with variant are not processed properly (the id is not added), this should fix it
> Fix bug for links

- components/infobox/wikis/starcraft2/infobox_building_custom.lua
> Avoid nil concat

- components/match2/commons/match_group_display.lua
- components/match2/commons/match_group_input.lua
- components/match2/commons/match_group_util.lua
Simplifies the code in Module:MatchGroup/Input
- Moved some match id manip code to individual functions in MatchGroup/Util
- Brackets now just warn if not all match args are filled out. Previously it would error out.
> [mg8] Clean up Module:MatchGroup/Input

- components/match2/commons/match_group_display.lua
Revert for a number of changes in #457.
> Revert changes to MatchGroup/Display in #457

- .luacheckrc
- standard/class.lua
* Copy `Module:Class` from commons
--
* add `setmetatable` to allowed globals in the git
> Add `Module:Class`

- components/hidden_data_box/wikis/starcraft2/hidden_data_box_custom.lua
Add `featured` var to HDB
it just sets an additional var ...
> Add `featured` var to SC2 HDB

- standard/region.lua
- standard/region_data.lua
Add region module + its data module
the `Module:Region/CountryData` is wikispecific and optional
Documentation: https://liquipedia.net/commons/Module:Region/doc
> Add region module

- standard/fn_util.lua
* copy `Module:FnUtil` from commons
> Add `Module:FnUtil`

- standard/reference_cleaner.lua
* copy `Module:ReferenceCleaner` from commons
> Add `Module:ReferenceCleaner`

- standard/namespace.lua
* copy `Module:Namespace` from commons
> Add `Module:Namespace`

- standard/tree_util.lua
* copy `Module:TreeUtil` from commons
> Add `Module:TreeUtil`

- components/infobox/wikis/halo/infobox_team_custom.lua
* make region use region module and hence display it standardized
* store location standardized
* enable region to be set from the location value
basically just do it like it was before #493
> Use module for region

- components/infobox/commons/infobox_unit.lua
- components/infobox/wikis/starcraft2/infobox_unit_custom.lua
* Add standardized module implementation for infobox unit
* * Commons part
* * SC2 custom part
* commons module --> https://liquipedia.net/starcraft2/Module:Hjpalpha/sandbox17
* SC2 module --> https://liquipedia.net/starcraft2/Module:Hjpalpha/sandbox13
Checked if it works on some pages using the current infobox
> Add infobox unit implementation

- standard/variables.lua
* copy `Module:Variables` from commons
> Add `Module:Variables`

- standard/template.lua
* copy `Module:Template` from commons
> Add `Module:Template`

- standard/type_util.lua
* copy `Module:TypeUtil` from commons
> Add `Module:TypeUtil`

- .luacheckrc
- standard/type_util.lua
The version currently on the git is broken, and causes errors. This is caused by #486. This copies over the live version and then addresses its errors, which include variable shadowing and usage of undefined global `arg`. It also simplifies the `getTypeErrors` function.
I used the testcases for Module:TypeUtil, which are all passing https://liquipedia.net/commons/Module_talk:TypeUtil/dev/testcases
> Fix bugs in TypeUtil

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
* move the draw calculation and everything that follows afterwards into a separate for loop so the opponent scores are actually calculated at the time they are checked against each other
via dev module
> Fix draw issues

- components/infobox/wikis/starcraft2/infobox_unit_custom.lua
* change attack display slightly
* add fallback entry options for supply
pushed it to live (module not used yet and tested it via preview
> Adjust custom infobox unit

- standard/hotkey.lua
* copy `Module:Hotkey` from commons
> Add `Module:Hotkey`

- components/match2/commons/match_group_input.lua
When a bracket template is missing, it's likely because the template needs to be purged. Show a warning box with a link to the template when that happens.
Enable `feature_prompt_purge_bracket_template` and use starcraft tournament test suite
> Use warning box to prompt template purge

- standard/result_or_error.lua
ResultOrError is a structurally typed, immutable class that represents either a result or an
error. It is used for representing the outcome of a function that can throw. It provides a way to write code using the try-catch-finally pattern.
Module same as live code
> Add Module:ResultOrError

- standard/logic.lua
* copy `Module:Logic` from commons
> Add `Module:Logic`

- standard/table.lua
* copy `Module:Table` from commons
> Add `Module:Table`

- standard/flags.lua
- standard/flags_master_data.lua
* Rewrite of `Module:Flags`
* temporary solution (for a few days) until switching to use `Module:Class`
* * needed to be able to switch the usage everywhere so we do not get problems
via testing it in user space and via module sandboxes
> Add `Module:Flags`

- standard/string_utils.lua
* copy `Module:StringUtils` from commons
> Add `Module:StringUtils`

- components/match2/commons/match_group_display.lua
add missing changes need by #496
starcraft2 tournament test pages
https://liquipedia.net/starcraft2/Liquipedia:BracketUpdate/Tests/Wide_Load
https://liquipedia.net/starcraft2/Liquipedia:BracketUpdate/Tests/WTL_6
> Re-add changes from #457

- standard/array.lua
* copy `Module:Array` from commons
> Add `Module:Array`

- standard/math_util.lua
Module:MathUtil contains just the stuff from Module:Math that I added
```
math.partialSums({3, 5, 4})
-- Returns {0, 3, 8, 12}
```
> Add Module:MathUtil

- standard/json.lua
* copy `Module:Json` from commons
> Add `Module:Json`

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
Add Casters Display (and storage) for SC2 matches
> Add Casters Display (and storage) for SC2 matches

- components/infobox/wikis/dota2/infobox_person_user.lua
Add dota2 version of infobox user
Difference to commons version:
added lines
* 57
* 70-81
> Add dota2 version of infobox user

- components/match2/commons/match_group_input.lua
- standard/array.lua
Rename of functions in `Module:Array`
Starcraft 2 tournament test suite
> Array.fromTableKeys -> Array.extractKeys, Array.fromTableValues ->Array.extractValues

- standard/namespace.lua
Add Namespace.idFromName
Usage
```
Namespace.idFromName('Liquipedia')
-- Returns 4
```
```
Namespace.idFromName('Liquipedia')
-- Returns 4
```
> Add Namespace.idFromName

- standard/json_ext.lua
Add JsonExt.parseIfTable
```
Attempts to parse a JSON encoded table. Returns nil if unsuccessful.
Example:
JsonExt.parseIfTable('{"a" = 3}')
-- Returns {a = 3}
```
```
JsonExt.parseIfTable('{"a" = 3}')
-- Returns {a = 3}
```
> Add JsonExt.parseIfTable

- standard/array_ext.lua
- standard/logic.lua
- standard/table.lua
Usage
```
Array.groupAdjacentBy({2, 3, 5, 7, 14, 16}, function(x) return x % 2 end)
-- returns {{2}, {3, 5, 7}, {14, 16}}
Logic.deepEquals({a = {b = 3}}, {a = {b = 3}})
-- Returns true
```
```
Array.groupAdjacentBy({2, 3, 5, 7, 14, 16}, function(x) return x % 2 end)
-- returns {{2}, {3, 5, 7}, {14, 16}}
Logic.deepEquals({a = {b = 3}}, {a = {b = 3}})
-- Returns true
```
> Add ArrayExt.groupAdjacentBy, Logic.deepEquals

- standard/array_ext.lua
Usage
```
Array.findIndexOf({3, 5, 4, 6, 7}, function(x) return x % 2 == 0 end)
-- returns 3
```
```
Array.findIndexOf({3, 5, 4, 6, 7}, function(x) return x % 2 == 0 end)
-- returns 3
```
> Add ArrayExt.findIndex

- standard/array.lua
- standard/fn_util.lua
Add Array.minBy, Array.maxBy, Array.reduce
Usage
```
local function pow(x, y) return x ^ y end
Array.reduce({2, 3, 5}, pow)
-- Returns 32768
local function pow(x, y) return x ^ y end
Array.reduceRight({2, 3, 5}, pow)
-- Returns 15625
Array.max({3, 2, 5, 2, 4})
-- Returns 5
Array.min({3, 2, 5, 2, 4})
-- Returns 2
```
```
local function pow(x, y) return x ^ y end
Array.reduce({2, 3, 5}, pow)
-- Returns 32768
local function pow(x, y) return x ^ y end
Array.reduceRight({2, 3, 5}, pow)
-- Returns 15625
Array.max({3, 2, 5, 2, 4})
-- Returns 5
Array.min({3, 2, 5, 2, 4})
-- Returns 2
```
> Add Array.minBy, Array.maxBy, Array.reduce

- components/match2/commons/match_group_util.lua
Split MatchGroupUtil.makeMatchGroup into separate function
used by starcraft's prize pool
> [pl1] Split MatchGroupUtil.makeMatchGroup into separate function

- components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua
- components/match2/commons/starcraft_starcraft2/player_display_starcraft.lua
- components/match2/commons/starcraft_starcraft2/player_util_starcraft.lua
Depends on #648 #607 
Sync code from starcraft's `/downstream` modules
> [pl2] Sync starcraft player code with live

- components/infobox/wikis/starcraft2/infobox_person_commentator.lua
- components/infobox/wikis/starcraft2/infobox_person_player.lua
Round `currentYearEarnings` display
pushed to live
> Round `currentYearEarnings` display

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
> Use capital letter

- standard/links.lua
Set `challonge` prefix for players
tested via sandbox, worked -> pushed to live
> Set `challonge` prefix for players

- components/infobox/wikis/wildrift/infobox_item_custom.lua
Adjust param name as wished by hesketh
pushed to live (modulized template not used yet) and works as intended
> Adjust param name

- components/infobox/wikis/starcraft2/infobox_person_commentator.lua
- components/infobox/wikis/starcraft2/infobox_person_player.lua
Catch empty opponents
pushed live
> Catch empty opponents

- standard/array_ext.lua
- standard/logic.lua
- standard/table.lua
Usage
```
Array.uniqueElement({4, 4, 4})
-- Returns 4
```
```
Array.uniqueElement({4, 4, 4})
-- Returns 4
```
> Add ArrayExt.uniqueElement

- components/infobox/wikis/wildrift/infobox_unit_champion.lua
Implement Infobox champion on Wildrift
using `{{infobox champion/test`
first check (left new one, right old one):
> Implement Infobox champion

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Adds a missing metadata tag to counterstrike
Pushed to live, will ask iMarbot to verify it works. ✔️
> Add metadata to counterstrike

- standard/math_util.lua
Returns the dot product of two vectors.
Example:
```
MathUtil.dotProduct({3, 2, 4}, {5, 6, 7})
-- Returns 55
```
```
MathUtil.dotProduct({3, 2, 4}, {5, 6, 7})
-- Returns 55
```
> Add MathUtil.dotProduct

- components/match2/commons/match_group_display_helper.lua
TZ required after the Countdown JS was rewritten
Tested live
> Add TimeZone (UTC) to the call to Module:Countdown

- components/match2/commons/starcraft_starcraft2/player_util_starcraft.lua
Allow boolean true for racehistorical
using this change in several sc2 modules already
> Allow boolean true for racehistorical

- components/infobox/commons/infobox_person.lua
Adjust `localizedname` storage as per the discussion in the discord.
> Adjust `localizedname` storage

- components/infobox/extensions/commons/metadata_generator.lua
refers to https://github.com/Liquipedia/Lua-Modules/pull/683#discussion_r746448067
-
> Implement proper A vs AN

- standard/string_utils.lua
Adds ability to do [string interpolation](https://en.wikipedia.org/wiki/String_interpolation)
> Create string interpolation function

- components/infobox/commons/infobox_person.lua
Make nationality display in infobox person customizable so that RL can overwrite it
if not overwritten no changes happen due to this
> Make nationality display customizable

- components/infobox/wikis/apexlegends/infobox_league_custom.lua
Remove legacy (tier --> tier + tiertype) switch helper stuff
temporarily pushed to live and checked several pages
basically same code as on halo and sc2
> Remove legacy (tier --> tier + tiertype) stuff

- components/match2/wikis/wildrift/brkts_wiki_specific.lua
- components/match2/wikis/wildrift/match_group_input_custom.lua
Add Wildrift match Input processing
* test page: https://liquipedia.net/wildrift/User:Hjpalpha
* lpdb match2 data looks good (legacy stuff follows later)
* display and automated calculations seem to work properly (matchsummary display follows later)
> Add Wildrift match Input processing

- standard/league_icon.lua
Use filler icon if no icon is found
adjusted it in a sandbox and checked the display with invokes of that sandbox
> Use filler icon if no icon is found

- components/squad/squad.lua
- components/squad/squad_custom.lua
- components/squad/squad_person.lua
- components/squad/squad_row.lua
This PR creates the basic structure for a module that would replace the `ActiveSquad`, `SquadPlayer`, etc templates. The idea of this implementation is that a wiki specific module creates the Squad object. If needed, it can extend the class and provide its own header. The module can then pass SquadRow objects to Squad, objects which also can be extended. This makes for a relatively generic framework which should allow for quite a bit of freedom for the wikis while allowing us to maintain standards over things we want to be standard, such as LPDB implementation.
```
{{#invoke:VoganRL/Squad/Custom|run 
|p1={{VoganRL/Squad person |flag=dk|id=Ronaky|name=Aldin Hodzic|joindate=2020-11-11<ref name="Ronaky"/>}}
|p2={{VoganRL/Squad person |flag=pt|id=AcroniK|name=Bruno …
```
> Create basic Squad structure

- components/infobox/wikis/rocketleague/infobox_person_player.lua
Implement Infobox player on RL
* several RL contributors tested it for display and plain errors using `{{Infobox player/test`
* compared LPDB and smw data of new and old implementation on 5 pages plus (some with birth dates, some without, some with localizedname, some without, ...)
new:
old:
> Implement Infobox player

- components/infobox/commons/infobox_team.lua
- components/infobox/wikis/halo/infobox_team_custom.lua
> [SUGGESTION] for #708

- components/match2/wikis/splitgate/brkts_wiki_specific.lua
https://liquipedia.net/splitgate/User:Fenrir.SPAZ/NewBrackets
> Create Brkts/WikiSpecific for Splitgate

- components/match2/wikis/wildrift/match_legacy.lua
Add wildrift match2 legacy storage
wrote myself a tiny module that queries the data from the according lpdb tables and compared them:
https://liquipedia.net/wildrift/User:Hesketh2/sandbox
did the same via smw ask
> Add wildrift legacy storage

- standard/logic.lua
Fix short circuiting in Logic.nilOr
```
Logic.nilOr(function() return false end, 3)
-- Returns 3
```
> Fix short circuiting in Logic.nilOr

- components/match2/commons/match_summary_base.lua
- components/match2/wikis/rainbow_six/match_summary.lua
* Provide Mvp class via `MatchSummary/Base`
* Adjust Custom modules accordingly
temp pushed to live on wildrift (they do not yet use the match2 system)
> Provide Mvp class via `MatchSummary/Base`

- components/match2/wikis/wildrift/get_match_group_copy_paste_wiki.lua
Add match2 copy paste generator for wildrift
pushed live (match2 system not yet in use on the wiki), created the forms and generated copy paste code with them
> Add match2 copy paste generator for wildrift

- components/match2/wikis/wildrift/brkts_wiki_specific.lua
Adjust trigger function for MatchSummary popup
pushed to live (System not in use on wildrift atm)
> Adjust trigger function for MatchSummary popup

- components/match2/wikis/wildrift/match_summary.lua
Add wildrift match summary implementation
* test page: https://liquipedia.net/wildrift/User:Hjpalpha (refresh css for proper display)
* pushed modules to live since new system not yet in use
* legacy stuff follows later
> Add wildrift matchsummary

- components/earnings/wikis/halo/earnings.lua
- components/earnings/wikis/rocketleague/earnings.lua
- components/earnings/wikis/valorant/earnings.lua
Fix function name
(fix for #735)
via a /dev version on RL
> Fix function name

- components/match2/wikis/halo/match_group_input_custom.lua
Store mapHeader for halo.
pushed live
> Store mapHeader for halo

- components/match2/commons/match_group_display_bracket.lua
Moves the line connectors in bracket display into their own display component (`BracketDisplay.ConnectorStub` and `BracketDisplay.NodeConnector`). This allows features to be added to them without duplicating it everywhere.
Use https://liquipedia.net/starcraft2/Liquipedia:BracketUpdate/Tests/Bracket_Layout
> [coords2] Move bracket connectors into separate component

- standard/variables.lua
Add function `varDefineEcho`
only adds a new function
tested it via a sandbox
> Add function `varDefineEcho`

- components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
- components/match2/commons/starcraft_starcraft2/opponent_display_starcraft.lua
Remove custom css that is set via css sheet since by now the cache for the old sheet should have refreshed
N/A
> Remove custom css

- components/notability/commons/notability_checker.lua
- components/notability/wikis/rocketleague/notability_checker_config.lua
I added detection for the bizarre legacy RL `liquipediatiertype` system so it just uses the standard system if not detected. Also added support for 1v1
Sandbox
> Add AoE support

- components/squad/squad_custom.lua
- components/squad/squad_row.lua
Adds LPDB saving to Module:Squad. Stacks on #767
> Add LPDB to Squad

- components/match2/commons/opponent.lua
Forgot to actually add the opponent constants `Opponent.team` etc
https://liquipedia.net/starcraft2/Liquipedia:Gallery/OpponentList
https://liquipedia.net/starcraft2/Liquipedia:Gallery/SwissTableLeague
> Add opponent constants

- components/squad/squad_row.lua
When you forget the pipes in the squad wikicode, you get a bit of a confusing error. This makes it easier.
It's live.
> Add friendlier error to squad

- components/squad/squad_row.lua
> Fix Squad typo

- components/squad/wikis/mobilelegends/squad_custom.lua
Add Squad to mobilelegends
It's live.
> Add Squad to mobilelegends

- components/squad/wikis/starcraft2/squad_custom.lua
stacked on #787
Adds the SC2 version of Squads custom module
not yet usable on sc2 due to us having to adjust additional modules
test (except race display): https://liquipedia.net/rocketleague/User:Hjpalpha/Squad
> Add SC2 custom for Squad modules

- components/match2/commons/match_group_util.lua
Update type declarations in MatchGroupUtil to those at the end of coords5g.
Tested as a part of #753 .
> [coords5a] Update type declarations in MatchGroupUtil

- components/squad/wikis/starcraft2/squad_custom.lua
* Fix modules that get required
* adjust id handling
(temp) pushed to live
_____
please ping me on discord when this is merged so i can start the conversion bot run on sc2
(already prepared all sc2 modules and templates for it)
> Fix bugs with sc2 squads

- components/squad/squad_row.lua
Add a (non breaking) space between id and icon display
Before:
After:
> Add Space between id and icon

- components/match2/wikis/splitgate/match_group_input_custom.lua
Adds the MatchGroup/Input/Custom to Splitgate wiki
Changes were tested on https://liquipedia.net/splitgate/User:Fenrir.SPAZ/NewBrackets
> Create MatchGroup/Input/Custom for Splitgate wiki

- components/match2/commons/starcraft_starcraft2/match_external_links_starcraft.lua
Add css class starcraft-match-external-links
used on live
> Add css class starcraft-match-external-links

- components/match2/commons/match_group_util.lua
Split makeMatchGroup into bracket and matchlist specific functions. headMatchIds is no longer used so it is removed.
Tested as a part of #753
> [coords5b] Split makeMatchGroup into bracket and matchlist specific functions

- components/match2/wikis/halo/match_summary.lua
- components/match2/wikis/rainbow_six/match_summary.lua
- components/match2/wikis/rocketleague/match_summary.lua
- standard/vod_link.lua
stacked on #804 
Adjust Modules to use the `VodLink` module instead of the template
via /dev modules and preview on pages (with enabled dev feature)
> Adjust Modules to use the `VodLink` module

- components/match2/wikis/valorant/big_match.lua
- components/match2/wikis/valorant/match_group_input_custom.lua
- components/match2/wikis/valorant/match_legacy.lua
Add Match/Legacy (Match2 -> Match1 mapping) for Valorant.
https://liquipedia.net/valorant/Special:LiquipediaDB/VoganRL/Matches
Still works need to be done when it comes to merging the Info from BigMatch and Bracket/MatchList, hence doesn't look complete.
> Add Match/Legacy for Valorant

- components/match2/wikis/valorant/match_group_input_custom.lua
Copy more data from the Big Match into the Tournament Page match, so we get one complete record
https://liquipedia.net/valorant/Special:LiquipediaDB/VoganRL/Matches
> Improve Population of Tournament Match from Big Match

- components/match2/wikis/rainbow_six/match_group_input_custom.lua
- components/match2/wikis/rainbow_six/match_summary.lua
Adds ChallengerMode as a icon to the new brackets
Tested live: https://liquipedia.net/rainbowsix/Six_Invitational/2022/Europe/Open_Qualifier_1
> Add ChallengerMode to Rainbow Six Match2

- components/match2/wikis/splitgate/match_summary.lua
https://liquipedia.net/splitgate/User:Fenrir.SPAZ/NewBrackets
> Create MatchSummary for Splitgate

- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/match_group_display_matchlist.lua
- components/match2/commons/match_group_display_singlematch.lua
- components/match2/commons/match_summary_ffa.lua
- components/match2/commons/opponent_display.lua
- components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
- components/match2/wikis/halo/match_summary.lua
- components/match2/wikis/rainbow_six/match_legacy.lua
- components/match2/wikis/rainbow_six/match_summary.lua
- components/match2/wikis/rocketleague/match_summary.lua
- components/match2/wikis/rocketleague/opponent_display_custom.lua
- components/match2/wikis/valorant/match_legacy.lua
- components/match2/wikis/valorant/match_summary.lua
- components/match2/wikis/wildrift/match_summary.lua
Use the /dev module of Display Helper if dev mode is activated.
> Use /dev of MatchGroup/Display/Helper if in dev mode

- components/match2/commons/match_group_util.lua
Read lowerMatchIds and lowerEdges from lpdb if available. Otherwise compute it assuming that it is a standard bracket.
Tested as a part of #753
> [coords5e] Read lowerMatchIds and lowerEdges from lpdb

- components/match2/commons/match_group_util.lua
Read bracketData.advance spots from lpdb if it is populated. Otherwise compute it assuming that it is a standard bracket.
Tested as a part of #753
> [coords5f] Read advance spots from lpdb

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
stacked on #838
Adjust type handling in sc2 infobox league
pushed to live (module not yet in usage)
> Adjust type handling

- components/match2/wikis/rainbow_six/get_match_group_copy_paste_wiki.lua
Was never put on github for some reason. Better late than never...
Been live quite a while
> Add CopyPaste for R6

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
Fix some bugs in sc2 infobox league
* Server(s) handling
* chronology
* catch nil localcurrency
* also remove localcurrency text from prizevalues
pushed to live (module not yet in usage, still in test phase)
> Fix some bugs in sc2 infobox league

- standard/reference_cleaner.lua
- standard/test/reference_cleaner_test.lua
same issue as with #848
not tested, but the same change was tested in a different module for #848
> Fix Reference Cleaner

- standard/hidden_sort.lua
Add HiddenSort implementation as a module so we can eliminate lots of template expands later on
sandboxes
> Add HiddenSort implementation as a module

- components/infobox/commons/infobox_person.lua
- components/infobox/wikis/starcraft2/infobox_person_commentator.lua
- components/infobox/wikis/starcraft2/infobox_person_player.lua
Adjust earnings display for persons
N/A (only chnages displayed text, no actual changes to functionality)
> Adjust earnings display for persons

- standard/flags.lua
- standard/flags_master_data.lua
> enable iso stuff for language flags + add option to store the special language flags we have as iso

- components/match2/commons/get_match_group_copy_paste.lua
Depends on #522 #560 , and requires that all bracket templates have been purged
Reorders the matches in the generated copy+paste bracket template. The upper/lower bracket matches are now appear together, so it's easier for editors to specify which players advance without having to scroll down a lot. The order is closer to that of pre-match2 brackets.
Example output
```
{{Bracket|Bracket/16U8L4DSL2DSL1D|id=PfWhJ8DO9z
|R1M1=
|R1M2=
|R1M3=
|R1M4=
|R1M5=
|R1M6=
|R1M7=
|R1M8=
|R2M1=
|R2M2=
|R2M3=
|R2M4=
|R4M1=
|R4M2=
|R6M1=
|R1M9=
|R1M10=
|R1M11=
|R1M12=
|R2M5=
|R2M6=
|R2M7=
|R2M8=
|R3M1=
|R3M2=
|R4M3=
|R4M4=
|R5M1=
|R6M2=
|R7M1=
|RxMBRheader=
|RxMBR=
}}
```
https://liquipedia.net/starcraft2/Special:RunQuery/BracketCopyPaste?title=Special%3ARunQuery%2FBracketCopyPaste&pfRunQueryFormName=Bracket …
> Reorder match entries in bracket copy+paste template

- components/infobox/wikis/halo/infobox_map_custom.lua
Creates a custom Map Infobox for the Halo wiki
Tested off a contributors userspace page for the maps: https://liquipedia.net/halo/User:0238/Bazaar
> Create custom Map Infobox for Halo

- standard/region/commons/region_data.lua
Adds a new way of setting the North American region
It's live
> Add "United States" to Region data

- components/infobox/commons/infobox_person.lua
fix a typo
pushed live
deathdate now set in lpdb as intended
> Fix typo in infobox person

- components/match2/wikis/splitgate/get_match_group_copy_paste_wiki.lua
Copy and Paste module for the Match2 brackets on Splitgate
Tested live
> Add CopyPaste Generator for Splitgate 

- components/match2/commons/starcraft_starcraft2/matches_table_starcraft.lua
Add missing "Module:"
pushed live
> Add missing "Module:"

- components/notability/wikis/ageofempires/notability_checker_config.lua
AoE wiki adopted the notability checker and integrated it into the notability guidelines.
N/A
> Add configuration for notability checker on AoE

- components/infobox/wikis/starcraft2/infobox_person_custom_shared.lua
Add Module with shared functions for sc2 person infoboxes.
Needed as a basis for #873 and #874
sandboxes
> Add Module with shared functions for sc2 person infoboxes

- components/match2/commons/match_group_input.lua
Adds a `matchIndex` property to matchlist match2bracketdata, to allow sorting matches if the order is lost.
Tested it here: https://liquipedia.net/rocketleague/Liquipedia:BracketUpdate/Tests/RLCS_5 using the dev module
> Add `matchIndex` to MatchList `match2bracketdata`

- components/match2/wikis/sideswipe/brkts_wiki_specific.lua
Create the wiki specific brackets for Sideswipe wiki
Currently live
> Create Brkts wiki specific Sideswipe

- components/match2/commons/match_group.lua
- components/match2/commons/match_group_base.lua
- components/match2/wikis/rainbow_six/legacy/match_maps_legacy_store.lua
Refactor the name of the MatchList and Bracket components in MatchGroup to simplify the code.
[Testing suite](https://liquipedia.net/rocketleague/Rocket_League_Championship_Series/Season_7)
> Rename MatchGroup components

- components/infobox/commons/infobox_league.lua
If `|abbreviation=` is not set, but `|series=` is set then query for the abbreviation from LPDB series.
/dev module
> Retrieve Abbreviation from LPDB series if unset

- .github/workflows/deploy_dev.yml
- deploy_dev.sh
modified scripts to auto-deploy modules to dev wiki as well
> Dev wiki deploy branch

- standard/lpdb/condition.lua
- standard/lpdb/condition_test.lua
This PR creates structured LPDB conditions, thereby mandating a structure and thus minimizing mistakes as well as improving readability. See the test for usage.
See test included in this PR.
> Create structured LPDB conditions

- components/group_table_league/commons/group_table_league_util.lua
Add the Utility module required by the match2 based GroupTableLeague
live
> Add utility module for GroupTableLeague

- components/match2/wikis/arenaofvalor/match_summary.lua
Adding MatchSummary module for Arena of Valor, part of the Match2 implementation
_The 1st commit is a direct copy with no changes from Mobile Legends, using the latest version which already incorporate changes from #881_ 
already Pushed Live
> Add MatchSummary for Arena of Valor

- components/standings/standings_storage.lua
First draft for LPDB standing storage.
> Create storage for standing

- components/match2/wikis/arenaofvalor/matchgroup_input_custom.lua
Adding MatchGroup/Input/Custom module for Arena of Valor, part of the Match2 implementation
_The 1st commit is a direct copy with no changes from Mobile Legends, using the latest version which already incorporate changes from #927_ 
already Pushed Live
> Add MatchGroup Input for Arena of Valor

- components/notability/wikis/halo/notability_checker_config.lua
Adding Misc, Charity, and Show Match to the config to allow for auto notability points
Currently live
> Adding new TierTypes

- components/match2/commons/match.lua
Implements the newly added LPDB property `section`
Match2 test pages
> Add `section` to matches

- components/match2/wikis/overwatch/match_summary.lua
Adding the Match Summary module for the Overwatch wiki using match2. Display is incredibly similar to Halo 
All changes tested here: https://liquipedia.net/overwatch/User:Fenrir.SPAZ/Sandbox
> Create MatchSummary for Overwatch

- components/infobox/wikis/brawlstars/infobox_league_custom.lua
Add infobox_league for Brawl STars
Standirazing the Infobox League
Tested the module on World Finals 2021 
It doesn't breaks LPDB vars
> Add Infobox League for Brawl Stars

- components/infobox/commons/infobox_widget_links.lua
- components/infobox/wikis/dota2/infobox_person_player_custom.lua
Kickstart the Dota migration effort by creating a first draft for Infobox/Player for Dota. Left is old, right is new. Clearly not quite there yet, but with this part done adding the rest should be relatively easy.
Use `{{Infobox_player/dev`
> Create Infobox/Player for Dota

- components/match2/wikis/wildrift/match_group_input_custom.lua
Port, same thing as #991 (ML), but for Wild Rift
https://liquipedia.net/wildrift/User:Hesketh2/sandbox
> Adjusting for WR MatchGroup Input

- components/infobox/wikis/dota2/infobox_person_player_custom.lua
Fixes a null error for dota players without `playerid`
live
> Fix null error on Dota

- components/match2/wikis/halo/match_group_input_custom.lua
- components/match2/wikis/halo/match_summary.lua
PR removes a series of unused code from the Match2 stuff. 
Removing Siege Links
Removing Map Veto code
Tested here https://liquipedia.net/halo/User:Fenrir.SPAZ/sandbox to ensure code didn't break
> Removing unused code from Halo Match2

- standard/logic.lua
This change adds 'yes' to truthy logic values and 'no' to falsy logic values
Deployed in [/Dev](https://liquipedia.net/commons/Module:Logic/Dev) and works as intended
> Add `yes` and `no` to logic values

- components/infobox/commons/infobox_weapon.lua
> Fix deploy header

- components/infobox/commons/infobox_weapon_custom.lua
Base Custom module used in [PR 1024](https://github.com/Liquipedia/Lua-Modules/pull/1024)
Tested live with PR 1024
> Create Infobox Weapon Custom

- components/infobox/commons/infobox_widget_links.lua
- standard/links/commons/links.lua
Add VLR Link Spupport to new infoboxes (for Ricci).
not yet
> Add VLR support to Links

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/wikis/arenaofvalor/matchgroup_input_custom.lua
- components/match2/wikis/brawlstars/match_group_input_custom.lua
- components/match2/wikis/halo/match_group_input_custom.lua
- components/match2/wikis/mobilelegends/matchgroup_input_custom.lua
- components/match2/wikis/rainbow_six/match_group_input_custom.lua
- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/splitgate/match_group_input_custom.lua
- components/match2/wikis/valorant/match_group_input_custom.lua
- components/match2/wikis/wildrift/match_group_input_custom.lua
- standard/stream_links.lua
Reverts Liquipedia/Lua-Modules#1032
> Revert "Adjust Stream handling in match2 input processing"

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/wikis/arenaofvalor/matchgroup_input_custom.lua
- components/match2/wikis/brawlstars/match_group_input_custom.lua
- components/match2/wikis/halo/match_group_input_custom.lua
- components/match2/wikis/mobilelegends/matchgroup_input_custom.lua
- components/match2/wikis/rainbow_six/match_group_input_custom.lua
- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/splitgate/match_group_input_custom.lua
- components/match2/wikis/valorant/match_group_input_custom.lua
- components/match2/wikis/wildrift/match_group_input_custom.lua
- standard/stream_links.lua
Undoes the revert in Liquipedia/Lua-Modules#1038
See explanation in #1032
> Adjust Stream handling in match2 input processing

- components/infobox/commons/infobox_widget_links.lua
- standard/links/commons/links.lua
Add vidio as supported link in infoboxes
sandbox on sc2
> Add vidio as supported link in infoboxes

- components/standings/standings_storage.lua
Adds support for the LPDB `section` property
Live
> Add `section` to LPDB `standing`

- components/match2/commons/starcraft_starcraft2/player_ext_starcraft.lua
> Fix SC2 historical race fetching from player pages

- components/infobox/wikis/dota2/infobox_person_player_custom.lua
Add namespace check for role, i.e. only set it on mainspace
Live
> Add namespace check for player role

- components/infobox/wikis/overwatch/infobox_map_custom.lua
Adds a new Infobox Map for Overwatch
https://liquipedia.net/overwatch/User:Fenrir.SPAZ/Sandbox
> Create Overwatch Infobox Map

- components/standings/standings_storage.lua
Use the new `roundindex` property in LPDB
Live
> Add `roundindex` to standings storage

- components/match2/wikis/brawlstars/get_match_group_copy_paste.lua
Add Copy Paste generators for brawlstars
live
> Add Copy Paste generators for brawlstars

- components/match2/wikis/brawlstars/match_summary.lua
Add MatchSummary for BrawlStars
live (system not yet in use on the wiki)
> Add MatchSummary for BrawlStars

- components/match2/wikis/brawlstars/get_match_group_copy_paste.lua
Update brawlstars match2 copy-paste generator due to some param changes in match2 input processing and the new optioon for players per map.
live
> Update brawlstars match2 copy-paste generator

- components/match2/wikis/brawlstars/match_legacy.lua
Add match2 legacy storage module for brawlstars
live (match2 system not yet in use there)
> Add match2 legacy storage module

- components/match2/commons/match.lua
- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/wikis/arenaofvalor/matchgroup_input_custom.lua
- components/match2/wikis/brawlstars/match_group_input_custom.lua
- components/match2/wikis/dota2/matchgroup_input_custom.lua
- components/match2/wikis/halo/match_group_input_custom.lua
- components/match2/wikis/mobilelegends/matchgroup_input_custom.lua
- components/match2/wikis/rainbow_six/match_group_input_custom.lua
- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/splitgate/match_group_input_custom.lua
- components/match2/wikis/wildrift/match_group_input_custom.lua
Store dark mode icon for team opponents in match2
—> needs lpdb field too for it to take effect
dev modules
> Store dark mode icon for team opponents in match2

- components/match2/wikis/dota2/get_match_group_copy_paste_wiki.lua
Copy-Paste for dota2, based on Wild Rift with bunch of changes & cleanup.
Live on wiki, as match2 is not live.
> Copy-Paste for dota2

- components/match2/wikis/dota2/match_legacy.lua
Based on Wild Rift with a dozen or so changes
Not live yet, userspace only
https://liquipedia.net/dota2/User:Lenya_01/15
> Add initial match2 to match1 handling

- components/match2/wikis/dota2/match_summary.lua
MatchSummary for dota2
Mostly done by @leonidkim01 with some changes at the end by me.
Live on userspace only
https://liquipedia.net/dota2/User:Lenya_01/15
> Add initial match summary for dota2

- components/match2/wikis/dota2/matchgroup_input_custom.lua
The current implementation will always trigger. It's code seems based on R6, which has map, and it would only count once a mapname has been enter to any game.
However dota2 doesn't have maps, and have a default map name as input from the Template. This caused it to always trigger the automatic scoring, displaying `0 : 0` for upcoming, not started, games.
With the new logic automatic match scoring is only used when there either 1) A map winner of any map or 2) the Match has started according to the `|date=` parameter (only if it's an exact time).
Tested live
> Automatic match scoring on match start time instead of map

- components/match2/wikis/dota2/matchgroup_input_custom.lua
This just fixes a small issue.
Live.
> Add missing return to function

- components/match2/wikis/rainbowsix/get_match_group_copy_paste_wiki.lua
Adjusts the copy and past generator to account for a nine map competitive map pool
Change was tested live before automatic bot deploy overwrote the changes
> Updating Rainbow Six to 9 Map Map Pool

- components/match2/wikis/dota2/get_match_group_copy_paste_wiki.lua
Dota editors voted in Discord for the version without indents.
Live.
> Remove indents from copy-paste generator

- standard/links/commons/links.lua
Support aligulac2 in infobox icon-links
N/A
> Support aligulac2 in infobox links

- components/match2/wikis/brawlstars/match_group_input_custom.lua
Allowing to use in match2 system the option to add maps not played in a series
> Add support for maps not played in a series

- components/infobox/commons/infobox_widget_links.lua
- standard/links/commons/links.lua
Add trackmania-io infobox icon
> Add trackmania-io infobox icon

- components/infobox/wikis/rainbowsix/infobox_patch_custom.lua
Creates a new Infobox Patch for the Rainbow Six wiki
Changes were tested in a Sandbox [Module](https://liquipedia.net/rainbowsix/Module:Fenrir/sandbox2) and tested on a sandbox [page](https://liquipedia.net/rainbowsix/User:Fenrir.SPAZ/wip4)
> Create Siege infobox/Patch

- components/infobox/wikis/dota2/infobox_team_custom.lua
Infobox Team implementation for dota2
Preview (`{{Infobox team/dev}}`)
> Create Infobox Team for dota2

- components/infobox/wikis/rainbowsix/infobox_patch_custom.lua
This PR fixes the broken links that exist in the Infobox Patch chronology. The fix was not anticipated in the initial update. 
[Testing module](https://liquipedia.net/rainbowsix/Module:Fenrir/sandbox2)
[Testing page](https://liquipedia.net/rainbowsix/User:Fenrir.SPAZ/wip4)
> Hotfix to correct errors on R6 Patch infobox

- components/match2/wikis/leagueoflegends/brkts_wikispecific.lua
Ad Brkts WikiSpec for League
Userspace
> Add Brkts WikiSpec for League

- components/infobox/wikis/brawlhalla/infobox_league_custom.lua
> Add Infobox League for Brawlhalla

- components/match2/wikis/leagueoflegends/match_legacy.lua
Add Match2 to Match1 Conversion for League.
~~There's a TODO regarding MVPs' Team~~
~~Userspace~~Live pilot tournament
> Add Match2-to-Match1 for League

- components/match2/wikis/leagueoflegends/get_match_group_copy_paste_wiki.lua
Add the CopyPaste generator for League of Legends
Live test
> Add Match2 CopyPasta for League

- components/match2/wikis/leagueoflegends/match_summary.lua
Add MatchSummary for League of Legends
~~Userspace~~ Live
> Add MatchSummary for League

- components/match2/commons/match_summary_base.lua
Improve Score Display for Bracket Reset similöarly to #1186
still to be tested
> Improve Score Display for Bracket Reset

- components/infobox/commons/infobox_person.lua
Store person earnings (total and per year) in wiki vars for storage in smw via the template
/dev module
> Store person earnings in wiki vars for smw

- components/match2/wikis/arenaofvalor/match_summary.lua
- components/match2/wikis/dota2/match_summary.lua
- components/match2/wikis/mobilelegends/match_summary.lua
- components/match2/wikis/wildrift/match_summary.lua
Fix game.length display as requested
not tested, change identical to leagueoflegends version (https://github.com/Liquipedia/Lua-Modules/pull/1174/commits/92abea3a10c575de200817614dc5d7a611420df9)
> Fix game.length display

- components/match2/wikis/leagueoflegends/matchgroup_input_custom.lua
Match2 input code for League of Legends
~~Userspace~~ Live
> Add League's Match2 Input

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft_ffa.lua
not time sensitive
early enough if you review it when you get paid for it ;)
(more clean up to come (especially for the "normal" sc2 input processing))
General CleanUp of the SC/SC2 match2 input processing.
- clean up code for better readability
- remove unused stuff (attemt to add some functions for bracket contests which never went anywhere)
/dev modules
> [SC match2 clean up 1] Clean up for FFA specific input

- components/infobox/wikis/brawlhalla/infobox_team_custom.lua
Add Infobox Team for Brawlhalla
live for > 1 month
> Add Infobox Team for Brawlhalla

- components/infobox/wikis/overwatch/infobox_league_custom.lua
Creates a new Infobox League module on the Overwatch wiki
Testing [module](https://liquipedia.net/overwatch/Module:Infobox/League/Custom), testing [page](https://liquipedia.net/overwatch/User:Fenrir.SPAZ/Sandbox_4)
> Create Overwatch Infobox League

- components/match2/wikis/leagueoflegends/matchgroup_input_custom.lua
> Fix finished bug for League

- components/infobox/commons/infobox_person.lua
Make earnings values available to /Custom modules
tested on
* brawlhalla
* sc2
* dota2
* rocketleague
> Make earnings values available to /Custom modules

- components/infobox/wikis/brawlhalla/infobox_person_player_custom.lua
depends on #1200
Add Infobox Player for Brawlhalla.
/dev module
> Add Infobox Player for Brawlhalla

- components/match2/wikis/leagueoflegends/match_legacy.lua
Correctly handle ties when converting a match2 data to League's match1 data format.
Live
> Correct match1 data for ties

- components/match2/wikis/brawlstars/match_group_input_custom.lua
> Avoid nil as index

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
- components/infobox/wikis/starcraft2/infobox_league_hidden.lua
- components/infobox/wikis/starcraft2/infobox_series_custom.lua
Update Module:tier and modules that depend on it (only on sc2)
* Infobox league
* Infobox series
* infobox league/hidden
/dev modules
> Update Module:tier and modules that depend on it

- components/infobox/commons/infobox_series.lua
Allow Warnings in infobox series
/dev modules
> Allow Warnings in infobox series

- components/match2/commons/starcraft_starcraft2/match_group_display_singlematch_starcraft.lua
Adjust SC/SC2 FFA SingleMatch display
* set the additional class needed for sc/sc2 ffa display
/dev module
https://liquipedia.net/commons/index.php?title=MediaWiki%3ACommon.css%2FBrackets.css&type=revision&diff=420791&oldid=419501
> Adjust SC/SC2 FFA SingleMatch display

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
- Tier function
- GameVersion dispaly
- kick `type` overwrite (botted them away)
/dev module
> CleanUp SC2 `Infobox/League/Custom`

- components/hidden_data_box/wikis/starcraft2/hidden_data_box_custom.lua
Remove 2 BS lines from sc2 HDB Custom
/dev module
> Remove unused wikivariables

- components/infobox/wikis/rainbowsix/infobox_person_player_custom.lua
Infobox Player for R6
Sample testing on Main Space, no issues detected
> Create Infobox Player for R6

- standard/locale_data_countries.lua
Add non-representing localisation
> Add non-representing localisation

- standard/table.lua
> Fix typos in a comment

- components/squad/wikis/dota2/squad_custom.lua
Create Squad Custom for dota2.
Will require botting after merge to use.
Initial testing has been done. Awaiting some UAT.
UAT found some issue which have been resolved.
> Create Squad for dota2

- standard/info/wikis/fortnite/info.lua
> Add fortnite Info module

- components/infobox/wikis/fortnite/infobox_person_player_custom.lua
Add fortnite infobox player
new module, not yet in use
test pages + a few selected main space pages to test it on
Remark: Kano wrote it, i just fixed a bit of stuff
> Add fortnite infobox player

- components/infobox/wikis/dota2/infobox_league_custom.lua
Create an Infobox League Custom for dota2
Tested in preview. LPDB test still isn't done
> Create Infobox League for dota2

- components/infobox/wikis/apexlegends/infobox_league_custom.lua
* Adjust LP tier handling to use commons.
* `not String.isEmpty` --> `String.isNotEmpty`
/dev module
> Adjust tier + cleanup

- components/infobox/wikis/pubg/infobox_league_custom.lua
- components/infobox/wikis/pubgmobile/infobox_league_custom.lua
Adjust tier handling to use commons
/dev module
> Adjust tier handling to use commons

- components/infobox/wikis/rocketleague/infobox_league_custom.lua
Overwrite createLiquipediaTierDisplay directly instead of just overwriting the widget
/Dev module
> Overwrite createLiquipediaTierDisplay directly

- components/infobox/commons/infobox_league.lua
- components/infobox/wikis/ageofempires/infobox_league_custom.lua
- components/infobox/wikis/apexlegends/infobox_league_custom.lua
- components/infobox/wikis/counterstrike/infobox_league_custom.lua
- components/infobox/wikis/dota2/infobox_league_custom.lua
- components/infobox/wikis/overwatch/infobox_league_custom.lua
- components/infobox/wikis/rainbowsix/infobox_league_custom.lua
- components/infobox/wikis/starcraft2/infobox_league_custom.lua
Move 'Individual Tournaments' category to be set via commons
/dev modules across several wikis (+commons)
> Move 'Individual Tournaments' category to commons

- components/infobox/commons/infobox_widget_links.lua
- standard/links/commons/links.lua
Add support for second rulebook.
N/A
> Add support for 2nd rulebook

- components/infobox/commons/infobox_widget_links.lua
Fix playlist icons in infobox links
live
> Fix playlist icons in infobox links

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
not time sensitive
General CleanUp of the SC/SC2 match2 input processing.
* clean up code for better readability
* remove unused stuff (attemt to add some functions for bracket contests which never went anywhere)
/dev module
> [SC match2 clean up 2] Clean up for non-ffa input

- components/match2/wikis/valorant/get_match_group_copy_paste_wiki.lua
Match2 Copy-Paste for Valorant
UAT
> Create Match2 Copy-Paste for Valorant

- components/match2/wikis/valorant/match_group_input_custom.lua
- components/match2/wikis/valorant/match_legacy.lua
* Add missing tiertype storage
* Store the correct mode
* Fix typo in an iterator
* Correctly handle participants in match1 convert
> 4 bug fixes for Valorant

- components/match2/wikis/valorant/match_group_input_custom.lua
Add automatic bestOf calculations
> Add automatic bestOf for Valorant

- components/match2/wikis/valorant/match_group_input_custom.lua
- components/match2/wikis/valorant/match_legacy.lua
- components/match2/wikis/valorant/match_summary.lua
* Change the round storage in extradata from individual fields into json based
* Add initial support for overtime
> Rework storage for round scores

- components/match2/wikis/valorant/match_group_input_custom.lua
- components/match2/wikis/valorant/match_summary.lua
* Remove unnecessary extra way of imputing game vods
* Remove unnecessary extradata storage
* Renmamed a parameter in a function to be more descriptive
* Change a Template call to the Module equivalent
* Change some image string to consts.
> Valorant Match2 Cleanup

- components/match2/wikis/valorant/match_legacy.lua
- components/match2/wikis/valorant/match_summary.lua
* Add display support for Overtime
* Match1 backwards compatibility handling support for Overtime 
Will be properly tested with the full feature
> Overtime functionlity for Valorant

- components/infobox/wikis/valorant/infobox_league_custom.lua
LPDB Diff looks fine. I took the opportunity to remove some unused extradata keys.
Old:
New:
Tested live on sample page
> Create Infobox League for Valorant

- components/match2/wikis/dota2/match_summary.lua
As discussed on discord #template-discussion 2022-03-20. https://discord.com/channels/93055209017729024/874304000718172200/955052104962146314
Change to a base 4 system to improve cleaner look.
Tested using dev modules
> Change dota2 css styles

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
Adjust sc2 tiertype handling (cleanup)
also catch lower case stuff due to that
/dev module
> Adjust sc2 tiertype handling (cleanup)

- components/infobox/wikis/valorant/infobox_league_custom.lua
* ~~fix tier bug~~
* move patch cell into gamesettings customizable
severe because it breaks tier display and storage on lots of pages
~~tier fix live, move patch via /dev~~
/dev module
> Move patch cell into gamesettings customizable

- components/match2/wikis/brawlstars/match_legacy.lua
Fix literal opponent handling in Match/Legacy
live
> Fix literal opponent handling in /Legacy

- components/match2/wikis/brawlstars/get_match_group_copy_paste.lua
adjust the start of the runindex for maps (from 1 to 2)
live
> Fix brawlstars copy paste

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
* Add Years Active for casters/casted events
* Adjust Years Active display as requested by contributors.
* Sort module requires
/dev module
> Adjust Years Active display

- standard/info/wikis/starcraft/info.lua
Add maximumNumberOfPlayersInPlacements to bw info module
N/A
#1316 and #1291 will depend on this
> Add maximumNumberOfPlayersInPlacements to bw info module

- components/infobox/wikis/fortnite/infobox_team_custom.lua
Add fortnite infobox team
new module, so live, but not ye used except on a few selected pages for testing
> Add fortnite infobox team

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
Cleanup SC2 infobox league custom module with the codereview from the broodwar infobox league
/dev module
> Cleanup SC2 infobox league

- components/infobox/wikis/fortnite/infobox_team_custom.lua
> Fix Earnings bug

- components/infobox/wikis/starcraft2/infobox_team_custom.lua
stacked on #1355
same as #1356
same fix also applied in #1291
/dev
> Fix earnings bug for teams (sc2)

- components/infobox/wikis/starcraft2/infobox_series_custom.lua
Cleanup SC2 infobox series /custom a bit
/dev
> Cleanup SC2 infobox series

- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Ceanup SC2 infobox team  with the codereview from the broodwar infobox team
Also kick builder usage and replace it with the usual table isnters isntead
/dev module
> Ceanup SC2 infobox team

- components/match2/wikis/overwatch/match_legacy.lua
Creates a Match/Legacy module for Overwatch
[Module](https://liquipedia.net/overwatch/Module:Match/Legacy)
> Overwatch Match/Legacy

- components/match2/wikis/overwatch/match_summary.lua
Adds map modes to the map row
Testing [page](https://liquipedia.net/overwatch/User:Fenrir.SPAZ/Sandbox_3)
> Adding MapMode icons to OW

- components/match2/wikis/overwatch/match_summary.lua
Adding the missing icons for 3rd party links
> OW Adding 3rd party icons

- components/infobox/wikis/starcraft/infobox_person_player_custom.lua
Make numbered string a number
live
> Cast numeric string to number

- components/match2/wikis/overwatch/match_summary.lua
Adding NVP display to the MatchSummary on OW
Tested live
> OW MVP Match Summary

- components/infobox/wikis/overwatch/infobox_unofficial_world_champion_custom.lua
Add OW unoff. world champ infobox
live module but not in use yet
> Add OW unoff. world champ infobox

- components/infobox/wikis/overwatch/infobox_team_custom.lua
Creates a new Infobox Team for Overwatch
Tested via this [page](https://liquipedia.net/overwatch/User:Fenrir.SPAZ/Sandbox)
> Overwatch Infobox Team

- components/infobox/wikis/halo/infobox_patch_custom.lua
Creates a new custom Infobox for patches on Halo
Tested Live via pages in new [patch portal ](https://liquipedia.net/halo/Portal:Patches)
> Halo Patch infobox

- components/match2/wikis/halo/get_match_group_copy_paste_wiki.lua
Removes the multi line indent on the Halo copy paste generator.
Tested live
> Halo copy/paste line height adjustment

- components/infobox/wikis/leagueoflegends/infobox_team_custom.lua
Creates a new Team Infobox for League of Legends
[Testing page](https://liquipedia.net/leagueoflegends/User:Fenrir.SPAZ/Team_Infobox)
> LoL Infobox Team

- standard/array_ext.lua
Add `ArrayExt.distinct`, a function that returns distinct elements of an array.
dhe added it via `Module:Array/Ext/downstream` so it factually is in use for several months now
but it is a function we need in a few modules so i think porting it over to the one in the git repo is a good idea ...
(renamed variables to be more up to git standards)
> Add ArrayExt.distinct

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/wikis/rainbowsix/prize_pool_custom.lua
Create the basic structure of the PrizePool table and parse the input 
Background can be found in the the PrizePool rework RFC https://docs.google.com/document/d/1ZbDpksMmI_wlRXdYA9_xggOPhSI_eyE3-WBt_Z-XSAY/edit#
```
{{#invoke:PrizePool/Custom|run|localcurrency=eur|points=si|qualifies=Six Major/2022/Stage 1|type={{TeamOpponent}}|prizesummary=no
|{{Slot|localprize=15,000|points=225 |qualified=yes |{{Opponent|Heroic |wdl=8/0/0/1|qualified=yes}}}}
|{{Slot|localprize=10,000|points=225 |qualified=yes |{{Opponent|BDS |wdl=5/1/1/2}}}}
|{{Slot|localprize=7,500 |points=225 |qualified=yes |{{Opponent|Looking For Org (ex-Vitality)|wdl=4/1/2/2}}}}
|{{Slot|localprize=6,000 |points=225 |qualified=yes |{{Opponent|G2 |wdl=5/0/1/3}}}}
|{{Slot|localprize=4,000 |points=225 |{{Opponent|mnm gaming …
```
> Prize Pools: structure and input

- components/prize_pool/commons/prize_pool.lua
Current implementation will have the prizes in a randomized order. Sort them based on the order that they should be presented in. Made the order
1) Dollar Money
2) Local Money
3) Qualifies To ("Seed")
4) Points
5) Other (freetext prizes)
Which matches the current setup the most.
**Before** sorting:
```
table#1 {
table#2 {
["data"] = table#3 {
metatable = table#4
["icon"] = "Rainbow Six Invitational Icon.png",
["iconDark"] = "",
["link"] = "Six_Invitational/2023/Global_Standings",
["title"] = "SI",
["titleLong"] = "Six Invitational Global Points",
},
["id"] = "POINTS1",
["index"] = 1,
["type"] = "POINTS",
},
table#5 {
["data"] = table#6 {
["currency"] = "EUR",
["currencyText"] = "€&nbsp;<abbr title=\"Euro\">EUR</abbr>",
["symbol"] = "€",
["symbolFirst"] = true,
},
["id"] = …
```
> Sort Prizes in order to display in an organized order

- components/prize_pool/commons/prize_pool.lua
Fix typo introduced in while cleanup up the code in #1374. Specifically this commit and line https://github.com/Liquipedia/Lua-Modules/pull/1374/commits/58546ae3192a6e80548b344ddd7ed12476d2003e#diff-e5d78c15af71464fe7cb67b275e37c46ec13ca13658398086304aca07af6bd6fR357 
The bug is causing the count not to increase properly (increases by 1 less than expected).
(Check the `placeStart` and `placeEnd`.
Full lists omitted to keep it short.
Before:
```
["placements"] = table#5 {
table#6 {
metatable = table#7
["args"] = table#8 {
"{\"qualified\":\"yes\",\"wdl\":\"8/0/0/1\",\"1\":\"Heroic\"}",
["localprize"] = "15,000",
["localprize1"] = "15,000",
["points"] = "225",
["points1"] = "225",
["qualified"] = "yes",
["qualified1"] = "yes",
},
["date"] = "2022-06-20",
["hasUSD"] = false,
["opponents"] = …
```
> Fix typo introduced in previous refactoring

- components/prize_pool/commons/prize_pool.lua
Add default display functions to prize types
Dependent on #1400
> Add default display functions to prize types

- components/match2/commons/opponent.lua
Adjust `Opponent.readOpponentArgs` and `Opponent.resolve`
* also pass playerTeams along (and resolve it)
* `i` --> `playerIndex` (more descriptive variable name)
/dev module
> Adjust `Opponent.readOpponentArgs` and `Opponent.resolve`

- standard/info/wikis/sideswipe/info.lua
Creates a new Info module for Sideswipe
Currently live
> Sideswipe Info

- standard/info/wikis/naraka/info.lua
Creates a new Info Module for Naraka
Currently live
> Naraka Info

- components/prize_pool/commons/prize_pool.lua
Follow up to #1405.
Use rowspans when a column in two (or more) rows consecutively  has the same content. Must be within a single `placement`.
> Prizepool rowspan when content is the same

- components/automatic-points-table/commons/automatic-points-table.lua
I realized that we need to (if we will) resolve redirects before querying lpdb for the points, since the redirects will also take place in the tournament pages, hence it will affect the lpdb objects stored in these tournament pages.
[Deployed in Sandbox](https://liquipedia.net/rocketleague/Module:Sandbox/AutoPointsTable/Rewrite/GH/11)
> Move resolve redirects to an earlier stage

- components/match2/wikis/brawlstars/get_match_group_copy_paste.lua
Set 3 instead of 2 bans in brawlstars copy paste
live
> Set 3 instead of 2 bans in brawlstars copy paste

- components/notability/wikis/rocketleague/notability_checker_config.lua
Updates Rocket League notability values.
Live
> Update Rocket League notability config

- components/hidden_data_box/wikis/wildrift/hidden_data_box_custom.lua
Fix wiki definition in header
N/A
> Fix wiki definition in header

- components/match2/wikis/leagueoflegends/get_match_group_copy_paste_wiki.lua
* Kick `finished` parameter.
* Add spaces between parameters in the same line.
was temp. live
> Adjust LOL match2 copy paste generator

- components/prize_pool/commons/prize_pool.lua
Fix `Array.foreach` --> `Array.forEach` in prize pool
just changing function name to the one that exists^^
> Fix `Array.foreach` --> `Array.forEach` in prize pool

- standard/tournaments_summary_table/wikis/starcraft2/tournaments_summary_table_custom.lua
> Fix git header

- components/prize_pool/commons/prize_pool.lua
Introduced in #1408. 
Missing return in one function.
If statement should have been reversed in refactor of function, but wasn't.
> Fix missing return and reversed if statement

- components/infobox/wikis/mobilelegends/infobox_league_custom.lua
Same implementation as previous ones #1444 
Briefly updated on the live module (before bot reverted) and functional well
> Add Official Device for ML Infobox League

- components/infobox/wikis/arenaofvalor/infobox_league_custom.lua
Same implementation as previous ones #1444 
Briefly updated on the live module (before bot reverted) and functional well
If you were noticed of the closed one, I had the typo the pull request name (accidentally type ML for AOV).
> Add Official Device for AOV Infobox League

- components/prize_pool/commons/prize_pool.lua
Very important for mobile users is the ability to scroll the table horizontally.
/dev module on my mobile
> Make prize pool's responsive (horizontal scroll)

- components/prize_pool/commons/prize_pool.lua
> Merge multiple occurrences of the same prize type into one column, for some types

- components/infobox/wikis/overwatch/infobox_person_player_custom.lua
Removes Team History Auto from player pages as the wikis transfer standards are far to poor to support this without breaking everything
Done live
> Removing THA from OW

- components/prize_pool/wikis/rainbowsix/prize_pool_custom.lua
* Set Wiki variable for points, as its required by the teamcard module.
* Add handling and saving of SI Points into a DataPoint
Dev Module on both test page & live pilot page (as test page doesn't have TeamCards).
>  Add R6 Custom Points handling

- components/prize_pool/commons/prize_pool.lua
Add currency exchange information when automatic currency exchange has been used, matching the style of old.
/dev modules
> Add currency exchange information

- components/prize_pool/commons/prize_pool.lua
Add special status to Prize Pool Tables, such as DQ (disqualified) & DNP (did not participate).
Dev module
> Add special status to Prize Pool Tables

- components/prize_pool/commons/prize_pool.lua
Currently, for any prize that is not the first of that type; all previous prizes must be explicitly defined in the slot. For instance here, `qualified1=no` is required for `qualified2=yes` to be parsed.
This PR aims to rework the parsing so this is no longer required. It does so by parsing the slots (and opponents) based on the rewards defined in the header. Since USD is not defined in the header, it has a special case here to parse specifically the USD reward.
Dev module
> Rework rewards parsing

- components/prize_pool/commons/prize_pool.lua
Allow custom opponentDisplay library in PP
I think we already had it but it got lost in some merge (conflict) handling
/dev module
> Allow custom opponentDisplay library in PP

- components/standings/standings_storage.lua
Handle so that the old module call still works until migration been completed.
Tested live.
> Handle legacy Module call

- components/standings/standings_storage.lua
Fixed typo that was introduced in #1487 
Live
> Fix typo in #1487

- components/match2/wikis/starcraft2/match_legacy.lua
SC2 part for #1502
/dev module
> Have match2-to-match1 respect store flags (SC2)

- components/match2/wikis/starcraft/match_legacy.lua
broodwar part for #1502
/dev module
> Have match2-to-match1 respect store flags (broodwar)

- components/prize_pool/wikis/rocketleague/prize_pool_custom.lua
Create Prize Pool Custom for Rocket League wiki
https://liquipedia.net/rocketleague/User:Rathoz/PPT
> Add PrizePool Custom for Rocket League

- .github/workflows/luacheck.yml
> Update leafo/gh-actions-lua for stylechecker to v9

- components/prize_pool/wikis/valorant/prize_pool_custom.lua
Migration over from their old PPTs. Removed some functionality that was unused (status, custom name)
> Create PPT Custom for Valorant

- components/prize_pool/wikis/dota2/prize_pool_custom.lua
Create a Custom PPT for dota2, handling their specific needs.
Tested in preview only so far.
> Create PPT Custom for dota2

- components/infobox/wikis/apexlegends/infobox_person_player_custom.lua
Adding a module for the infobox for apex.
Tested on:
(https://liquipedia.net/apexlegends/Hardecki)
Page works, earnings are a little off, but that probably requires an update in the prizepool section.
> Creating infobox person for Apex Legends

- components/infobox/wikis/apexlegends/infobox_team_custom.lua
Currently tested on:
https://liquipedia.net/apexlegends/Gambit_Esports
Added the Custom Infobox team module to apex legends
The changes were tested on:
https://liquipedia.net/apexlegends/Gambit_Esports
> Create Custom infobox team for Apex Legends

- components/prize_pool/wikis/apexlegends/earnings.lua
Needed to correctly calculate the earnings per player.
Currently tested on player pages and seems correct.
https://liquipedia.net/apexlegends/Hardecki
https://liquipedia.net/apexlegends/Zer0
Earnings are (close) to their original state with this fix.
> Set up Module:Earnings for Apex

- components/prize_pool/wikis/apexlegends/prize_pool_custom.lua
https://liquipedia.net/apexlegends/Douyu/2022/Defender_Cup/Season_2
https://liquipedia.net/apexlegends/Apex_Legends_Global_Series/2022/Championship
Standardizing the PPT for the wiki.
Currently already active and working across the wiki:
https://liquipedia.net/apexlegends/Douyu/2022/Defender_Cup/Season_2
https://liquipedia.net/apexlegends/Apex_Legends_Global_Series/2022/Championship 
Tested across various tournament pages. Also purged these, and checked all player/team results/achievements tables and earnings. Nothing broken so far.
> Add Custom Prizepool handler to Apex

- components/squad/wikis/apexlegends/squad_custom.lua
Standardizing the Squad sections.
All roles featuring legends have already been botted out and roles such as |Substitute, Stand-in etc have been fixed. 
Tested on the following page:
https://liquipedia.net/apexlegends/Team_Burger
> Create Squad Custom for Apex

- components/infobox/commons/infobox_series.lua
Rearranged Sponsors and Tier to match that of Infobox League.
Added Venue and Type. 
Is this OK?
> Made Series match League in formatting slightly more

- components/infobox/wikis/counterstrike/infobox_series_custom.lua
Create an Infobox Series for CS.
Before:
After:
LPDB Before:
LPDB After:
> Create Infobox Series for Counterstrike

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Significantly rework most parts of the Counterstrike Infobox League. May be easier to review it as an entirely new infobox rather than just the diff.
Current live (ie Template not git stored module)
With Module:
LPDB Live (template based):
With Module:
Dev module
> Cleanup, fix and improve CS Infobox League

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Based on feedback from CS Staff
> Remove team list from Infobox League on CS

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Did a typo in the string concat in #1564
Dev Module
> Fix string concat typo

- components/squad/wikis/counterstrike/squad_custom.lua
Create Custom Squad for CS wiki.
Based on Valorant.
> Create Squad Custom for Counterstrike

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
Make SC2 player (and caster) infoboxes faster by ~45%
/dev module, display looks the same as before
left: current; right: proposed
> Make SC2 player (and caster) infoboxes faster

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
stacked on #1577
Kick several "globals" in sc2 infobox player
/dev module
> Remove several "globals" in sc2 infobox player

- standard/links/commons/links.lua
Add a player/user link for ESEA website
Live
> Add player link for ESEA

- components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua
Creates a new Player infobox for League of Legends
[testing page](https://liquipedia.net/leagueoflegends/User:Fenrir.SPAZ/NewPlayers)
> LoL Player Infobox

- components/match2/commons/match_group_display_helper.lua
- standard/date_ext.lua
(only affects users with JS turned off or auto time tz convert setting turned off)
> Add a space between time and timezone

- components/infobox/wikis/starcraft2/infobox_person_map_maker.lua
Add to instead of overwrite extradata in sc2 mapmaker infobox
live
> Add to instead of overwrite extradata

- components/infobox/wikis/counterstrike/infobox_person_player_custom.lua
Create a Infobox Player for the Counter Strike wiki. 
Template Based:
Module Based:
Simple preview testing done.
LPDB tests done.
UAT done (#1606 for adjustments)
LPDB Old:
LPDB New:
> Create Player Infobox for CS

- components/prize_pool/commons/prize_pool.lua
Fix PP participantflag storage
dev module (see comment below)
> Fix PP participantflag storage

- components/squad/wikis/leagueoflegends/squad_custom.lua
This is actually the final version of what was tested in #1614. I forgot to push it to git.
Tested when doing #1614
> Forgot to push these minor fixes onto #1614

- components/match2/wikis/counterstrike/get_match_group_copy_paste_wiki.lua
Counterstrike match2 Copy/Paste.
-https://liquipedia.net/counterstrike/Special:RunQuery/BracketCopyPaste
-https://liquipedia.net/counterstrike/Special:RunQuery/MatchListCopyPaste
-https://liquipedia.net/counterstrike/Special:RunQuery/SingleMatchCopyPaste
Waiting #1616 to be merged.
Tested on:
-https://liquipedia.net/counterstrike/Special:RunQuery/MatchListCopyPaste/dev
> Counterstrike match2 Copy/Paste 

- components/hidden_data_box/wikis/rainbowsix/hidden_data_box_custom.lua
Create HDB for R6
Tested on https://liquipedia.net/rainbowsix/6_French_League/Season_4/Group_Stage with dev template.
> Create HiddenDataBox for R6

- components/match2/commons/starcraft_starcraft2/opponent_display_starcraft.lua
analogous to #1514 just for sc/sc2
/dev module
> Default TBD's to hide link in sc/sc2 opponents

- components/squad/commons/squad.lua
- components/squad/commons/squad_row.lua
Only merge after the css changes are in the cache.
https://liquipedia.net/commons/index.php?title=MediaWiki%3ACommon.css%2FMiscellaneous.css&type=revision&diff=440348&oldid=440035
https://discord.com/channels/93055209017729024/1002203659884576788/1002904911140376677
(from a thread in the #dark-theme channel on lp discord)
Replace hardcoded colors with css classes.
#773
to be done
> Replace hardcoded colors with css classes

- components/infobox/commons/infobox_person.lua
Store `firstname` and `lastname` into wiki variables
/dev module
> Store `firstname` and `lastname` into wiki variables

- components/match2/commons/match_group_input.lua
- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/wikis/arenaofvalor/match_group_input_custom.lua
- components/match2/wikis/brawlstars/match_group_input_custom.lua
- components/match2/wikis/dota2/match_group_input_custom.lua
- components/match2/wikis/halo/match_group_input_custom.lua
- components/match2/wikis/leagueoflegends/match_group_input_custom.lua
- components/match2/wikis/mobilelegends/match_group_input_custom.lua
- components/match2/wikis/overwatch/match_group_input_custom.lua
- components/match2/wikis/pokemon/match_group_input_custom.lua
- components/match2/wikis/rainbowsix/match_group_input_custom.lua
- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/sideswipe/match_group_input_custom.lua
- components/match2/wikis/splitgate/match_group_input_custom.lua
- components/match2/wikis/valorant/match_group_input_custom.lua
- components/match2/wikis/wildrift/match_group_input_custom.lua
Move common tournament Variable retrieval to commons
/dev modules
> Move common tournament Variable retrieval to commons

- components/hidden_data_box/wikis/dota2/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/rainbowsix/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/rocketleague/hidden_data_box_custom.lua
Incorrect function header causing parameters to be incorrect.
Only matter on the dota2 implementation, the other two don't use the paramters
Live on dota2
> Bug fixed on Custom HDBs

- components/match2/commons/starcraft_starcraft2/opponent_starcraft.lua
Add `Module:Opponent/Starcraft`
/dev module
except for the Table.deepCopy stuff it is in use like this since months
> Add `Module:Opponent/Starcraft`

- components/match2/wikis/pokemon/match_summary.lua
Module:MatchSummary, couple changes comparing to the conventional MOBAS is this game uses Purple/Orange as side colors, The score on the middle replaces length because the match timer is a countdown.
LIVE
This was a long not yet-PR stuff since February, maybe a lot behind it in terms of updates.
> Match Summary for Pokemon

- components/match2/wikis/ageofempires/opponent_custom.lua
- components/match2/wikis/ageofempires/player_ext_custom.lua
- components/prize_pool/wikis/ageofempires/prize_pool_custom.lua
Add standardized prize pool for AoE
- Implements custom `Opponent:resolve` to fetch teams
- Currently not working: walkover input, depending on #1544 
[Sandbox](https://liquipedia.net/ageofempires/User:SyntacticSalt/Sandbox/1)
> Implement `PrizePool` for Age of Empires

- components/match2/wikis/pokemon/brkts_wikispecific.lua
Brkts/WikiSpecific for Pokemon, This one is a direct identical port of Mobile Legends (and so does other Mobile MOBA wikis) with only default file changes.
LIVE
> Brackets WikiSpecific for Pokemon

- components/infobox/commons/infobox_league.lua
depends on #1638
* Use new infobox prize pool module
/dev
> Use new infobox prize pool module

- components/infobox/wikis/apexlegends/infobox_person_player_custom.lua
Add data of **retired date** to LPDB.
/dev
> Add retired date to lpdb in apex

- components/prize_pool/commons/prize_pool.lua
depends on #1638 
Use currency_rate variables in PrizePool
/dev
> Use currency rate variables in PrizePool

- components/prize_pool/wikis/leagueoflegends/prize_pool_custom.lua
- components/prize_pool/wikis/leagueoflegends/prize_pool_legacy_custom.lua
Create Prize Pool Table and it's Legacy mapper for League of Legends.
> Create PPT for League of Legends

- components/match2/commons/starcraft_starcraft2/opponent_starcraft.lua
Use the module that actually has that function
live
> Use the module that actually has that function

- components/infobox/commons/infobox_person.lua
Support additional "status" parameters in infobox/person
- inactive
- banned
/dev
> Support additional "status" parameters in infobox/person

- standard/variables.lua
Add intellisense annotations to Module:Variables.
> Add intellisense annotations to Module:Variables

- components/prize_pool/wikis/counterstrike/prize_pool_custom.lua
- components/prize_pool/wikis/counterstrike/prize_pool_legacy_custom.lua
Create the PPT customs for the CS wiki.
> Implement PPT Custom for Counterstrike

- components/prize_pool/commons/prize_pool.lua
Allow negative scores in PP
/dev module
> Allow negative scores in PP

- components/infobox/commons/infobox_person.lua
Catch empty strings in some ifs in infobox/person
/dev module
> Catch empty strings in some ifs

- standard/currency/currency.lua
> Catch empty strings

- components/match2/wikis/starcraft/legacy/match_group_legacy.lua
- components/match2/wikis/starcraft/legacy/match_group_legacy_default.lua
copy over sc2, to fix a few bugs that were fixed on commons and sc2 in the last months
+ use single quote instead of double quote (due to copy-paste))
live (1-1 copy, with no changes except for the `wiki=starcraft` in the git header)
> Update broodwar MatchGroup/Legacy

- components/prize_pool/wikis/valorant/prize_pool_custom.lua
Save `qualified` flag for Valorant's tournament list
/dev Module
> Save Qualified LPDB field on VAL

- components/match2/commons/match_summary_base.lua
* Add `Footer:addLink` function to MatchSummary/Base
* use it in side `Footer:addLinks`
/dev
> Add `Footer:addLink` function to MatchSummary/Base

- components/hidden_data_box/wikis/overwatch/hidden_data_box_custom.lua
Creates a custom HDB for Overwatch
Tested live [page](https://liquipedia.net/overwatch/Best_Hero/Code_A/Group_Stage) with testing module
> OW HDB Custom

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
- components/infobox/wikis/starcraft2/infobox_league_hidden.lua
- components/infobox/wikis/starcraft2/infobox_patch_custom.lua
- components/infobox/wikis/starcraft2/infobox_person_custom_shared.lua
- components/infobox/wikis/starcraft2/infobox_person_map_maker.lua
- components/infobox/wikis/starcraft2/infobox_person_user.lua
- components/infobox/wikis/starcraft2/infobox_series_custom.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/wikis/starcraft2/legacy/legacy_player_cross_table.lua
- components/match2/wikis/starcraft2/legacy/match_group_legacy.lua
- components/match2/wikis/starcraft2/legacy/match_maps_legacy.lua
Kick Smw param usage on sc2
/dev where applicable
needs prep bot run on 1k pages
> Kick Smw param usage on sc2

- components/standings/standings_storage.lua
Remove the storage of legacy lpdb standings table
Tested on R6 using dev module
> LPA-6348: Remove legacy lpdb storage of standings

- components/match2/commons/starcraft_starcraft2/match_group_display_singlematch_starcraft.lua
Allow noScore for ffa singleMatch display
/dev
> Allow noScore for ffa singleMatch display

- components/match2/wikis/starcraft/legacy/match_maps_legacy.lua
Add Broodwar MatchMaps/Legacy module
live
> Add Broodwar MatchMaps/Legacy module

- components/infobox/wikis/ageofempires/infobox_league_custom.lua
A Suggestion for #1730 / an alternative way of handling the maps stuff
imo this is a bit cleaner
just an idea, would have to be tested if wanted
> Suggestion for #1730

- components/match2/commons/match_group_util.lua
- components/match2/wikis/counterstrike/match_legacy.lua
- components/match2/wikis/dota2/match_legacy.lua
- components/match2/wikis/leagueoflegends/match_legacy.lua
- components/match2/wikis/mobilelegends/match_legacy.lua
- components/match2/wikis/overwatch/match_legacy.lua
- components/match2/wikis/rainbowsix/match_legacy.lua
- components/match2/wikis/rocketleague/match_summary.lua
- components/match2/wikis/starcraft/match_legacy.lua
- components/match2/wikis/starcraft2/match_legacy.lua
- components/match2/wikis/valorant/match_legacy.lua
Change match2.bestof to an integer. This is preparation work for doing the same in the DB Column. These were the only places on git I could find that needed change. @hjpalpha is there some SC/SC2 stuff querying match2.bestof that are not on git?
Tested on R6
> Change match2.bestof to an integer from string

- components/prize_pool/commons/prize_pool_legacy.lua
Catch special cases in PPT Legacy merge option
/dev module
> Catch special cases in PPT Legacy merge option

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_legacy.lua
Add support for w, d, l as specialStatuses
/dev modules (under way)
"normal usage"
"usage in legacy" (note the additional medal is unrelated to this PR)
> Add support for w, d, l specialStatuses

- components/infobox/wikis/apexlegends/infobox_character_custom.lua
Created infobox/character/custom for Apex wiki to replace old template version.
https://liquipedia.net/apexlegends/Dark_meluca/WattsonTest
Test page can be found here. Moved to mainspace to check whether LPDB data was being stored.
Infobox can be seen displayed also.
PS, sorry hjp
> Add Infobox Character for Apex Legends

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_legacy.lua
Suppress 0 display for freetext in PPT
/dev
current:
proposed:
> Suppress 0 display in PPT

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_legacy.lua
stacked on #1712
change stuff from smwPrefix to lpdbPrefix
targets https://github.com/Liquipedia/Lua-Modules/pull/1712#issuecomment-1217170254
/dev
> Change stuff from smwPrefix to lpdbPrefix

- components/infobox/wikis/apexlegends/infobox_weapon_custom.lua
Created infobox/weapon/custom for Apex wiki to replace old template version.
https://liquipedia.net/apexlegends/Dark_meluca/HavocTest
Test page can be found here. Moved to mainspace to check whether LPDB data was being stored. 
Infobox can be seen displayed also.
> Add Infobox Weapon for Apex Legends

- components/prize_pool/wikis/counterstrike/prize_pool_legacy_custom.lua
Remove stuff from cs custom that commons does now #1701 
/dev module
> Remove check in CS custom that commons does

- standard/flags.lua
- standard/localisation.lua
Add function to Flags module, that retrieves localisation values from the master data
Needs the data added by #1057
/dev modules
> Combine Localisation and Flags data

- components/hidden_data_box/wikis/brawlstars/hidden_data_box_custom.lua
Add brawlstars HDB
live module (new) + dev template
pushed live after tests to fix bugs with the old smw based template version
> Add brawlstars HDB

- standard/links/commons/links.lua
Apex Legends Status Public website that tracks accounts on Apex Legends. (Showing match histories, ranked leaderboards, character statistics)
> Add Apex Legend Status support

- components/prize_pool/commons/prize_pool.lua
Make `storeSmw`, `storeLpdb` and `resolveRedirect` actually an option
/dev
> Make `storeSmw`, `storeLpdb` and `resolveRedirect` actually an option

- components/match2/wikis/rocketleague/match_summary.lua
Was broken in #1811. Each side needs to be wrapped in a div
Live
> Fix Match Summary for Rocket League

- components/prize_pool/commons/prize_pool.lua
Fix bug from #1815 - entries are not updated with tournament data
/Dev module
> Fix bug from #1815 - entries are not updated with tournament data

- components/match2/commons/opponent.lua
Fixes #1792 (CS part)
via /dev
- Tested with SoloPrizepool on AoE and SC2
> Treat player displayName `tbd` as isTbd

- components/prize_pool/commons/prize_pool.lua
Make assert error message more precise in the opponent number per placement assert in PPT
/dev
> Make assert error message more precise

- standard/timezone.lua
I missed to push a commit to #1829. This function is expected to be live by #1833 (and is required). 
Live
> Add timezone offset in second function

- components/squad/wikis/overwatch/squad_custom.lua
Creates a new Squad Custom
[Testing page](https://liquipedia.net/overwatch/User:Fenrir.SPAZ/Sandbox_3)
> Create Overwatch Custom Squad Implementation

- components/match2/wikis/counterstrike/get_match_group_copy_paste_wiki.lua
Map.vod should be enough in copy paste.
`dev`module.
> Remove redundant vod parameter Copy/Paste

- components/hidden_data_box/commons/hidden_data_box.lua
The way the code was written, a lot of lines would be trying to index a table variable `queryResult` which is initialized as `nil` and not always set later to an empty table instead. This PR addresses that by initializing directly as an empty table and modifying further logic down the line to support the change.
https://github.com/Liquipedia/Lua-Modules/blob/09642751b8d10801d9e9f14d013783129a71eabe/components/hidden_data_box/commons/hidden_data_box.lua#L45
https://github.com/Liquipedia/Lua-Modules/blob/09642751b8d10801d9e9f14d013783129a71eabe/components/hidden_data_box/commons/hidden_data_box.lua#L73
Tested on `/dev` on commons using pages on CS wiki.
* https://liquipedia.net/counterstrike/index.php?title=User:Optimush-2/TDJ/Supercopa_de_America/2022/Contenders_Stage&oldid=2344048 …
> Fix potential nil indexing in HDB

- components/squad/wikis/overwatch/squad_custom.lua
Not sure when or why this was removed, probably a mistake, as it was there during testing. CC: @FenrirWulf 
Live
> Fix broken OW Squad Custom for Manual tables

- components/match2/commons/starcraft_starcraft2/opponent_starcraft.lua
Catch nil in StarcraftOpponent.readOpponentArgs
/dev
> Catch nil in StarcraftOpponent.readOpponentArgs

- components/prize_pool/wikis/prize_pool_legacy_custom.lua
Legacy Prize Module, 
**EDIT: It was closed once but Brought back to get usdprize1 and usdprize2 working, the added section are ported from counterstrike**
This include removing all other parts that was noted unused (and would work fine without it), but re-added the prize stuff
**LIVE**
https://liquipedia.net/mobilelegends/MPL/Philippines/Season_9
> Add PPT (Legacy) for Mobile Legends

- components/infobox/wikis/apexlegends/infobox_weapon_custom.lua
After implementing the standardised infobox live, it was realised there may be some extra fields needed.
Tested with `dev` module call
> Adding additional fields to Infobox Weapon

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_placement.lua
Add option to not fill placeRanges with TBD opponents
/dev
> Add option to not fill placeRanges with TBD opponents

- components/match2/wikis/player_ext_custom.lua
To introduce, Fortnite is a Battle Royale wiki and has no submatches. 
just in case if these poses future usage because its already existed in the wiki
Ported from AoE
> Add Player Ext Custom for Fortnite

- components/prize_pool/wikis/overwatch/prize_pool_custom.lua
Creates a custom prize pool for Overwatch
[Testing page](https://liquipedia.net/overwatch/User:Fenrir.SPAZ/newPrizePool)
> OW Custom PrizePool

- standard/logic.lua
Adjust Logic.readBool and Logic.readBoolOrNil so we can deprecate https://liquipedia.net/commons/Module:Yesno
only difference now is lowercaseing in Module:Yesno
/dev
> Adjust Logic.readBool and Logic.readBoolOrNil

- components/squad/wikis/arenaofvalor/squad_custom.lua
Updating it to matched Mobile Legends
quick test by saving into the main module (before reverted) works good on both normal squad input and auto input
> Update AoV Squad Module

- components/squad/wikis/trackmania/squad_custom.lua
Creating Lua Module for Squad/Custom at Trackmania wiki
Creating Module for Squad/Custom at Trackmania wiki
Tested it at my Userspace: https://liquipedia.net/trackmania/User:Heinzchen/Sandbox1
I created the module at this page: https://liquipedia.net/trackmania/Module:Heinzchen/Squad/Custom
Don't really know if this is the right way to test modules. Please let me know if there is a better way.
> Create Trackmania Custom Squad implementation

- components/match2/commons/match_group_util.lua
Pass along map/game dates to matchsummary
/dev
> Fetch date for Games from LPDB

- components/mvp_table/commons/mvp_table_custom.lua
Fixes broken magic comment
N/A
> Fix magic comment

- components/infobox/commons/custom/infobox_series_custom.lua
Live and active on commons for forever, but never uploaded to git
Live
> Add missing Series Custom from Commons

- components/infobox/wikis/ageofempires/infobox_league_custom.lua
Prepare AoE Infobox to use dev feature flag.
Quick test on dev module
> AoE: Cleanup Imports, enable dev if dev-flag is on

- components/infobox/commons/custom/infobox_character_custom.lua
- components/infobox/commons/custom/infobox_company_custom.lua
- components/infobox/commons/custom/infobox_game_custom.lua
- components/infobox/commons/custom/infobox_league_custom.lua
- components/infobox/commons/custom/infobox_patch_custom.lua
- components/infobox/commons/custom/infobox_person_user_custom.lua
- components/infobox/commons/custom/infobox_show_custom.lua
- components/infobox/commons/custom/infobox_strategy_custom.lua
- components/infobox/commons/custom/infobox_unofficial_world_champion_custom.lua
- components/infobox/commons/custom/infobox_weapon_custom.lua
- components/infobox/commons/custom/infobox_website_custom.lua
In order to facilitate the efficient testing of new functionality in the Infobox, adding support for the Dev feature flag.
This PR only enables it on the Customs that exist on Commons.
Sample testing
> Infobox Common's Customs: Require dev if FF turn on

- components/infobox/wikis/rainbowsix/infobox_league_custom.lua
- components/infobox/wikis/rainbowsix/infobox_patch_custom.lua
- components/infobox/wikis/rainbowsix/infobox_person_player_custom.lua
- components/infobox/wikis/rainbowsix/infobox_team_custom.lua
Setup R6 Infoboxes to use dev feature flag.
Sample testing
> R6: Cleanup imports, enable dev if dev-flag is on

- components/infobox/wikis/arenaofvalor/infobox_league_custom.lua
Setup AoV Infoboxes to use dev feature flag.
> AoV: Cleanup imports, enable dev if dev-flag is on

- components/infobox/wikis/brawlhalla/infobox_league_custom.lua
- components/infobox/wikis/brawlhalla/infobox_person_player_custom.lua
- components/infobox/wikis/brawlhalla/infobox_team_custom.lua
Setup Brawlhalla Infoboxes to use dev feature flag.
> Brawlhalla: Cleanup imports, enable dev if dev-flag is on

- components/infobox/wikis/leagueoflegends/infobox_league_custom.lua
- components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua
- components/infobox/wikis/leagueoflegends/infobox_team_custom.lua
Setup League of Legends Infoboxes to use dev feature flag.
> League: Cleanup imports, enable dev if dev-flag is on

- components/infobox/wikis/dota2/infobox_league_custom.lua
- components/infobox/wikis/dota2/infobox_person_player_custom.lua
- components/infobox/wikis/dota2/infobox_person_user_custom.lua
- components/infobox/wikis/dota2/infobox_series_custom.lua
- components/infobox/wikis/dota2/infobox_team_custom.lua
Setup dota2 Infoboxes to use dev feature flag.
> dota2: Cleanup imports, enable dev if dev-flag is on

- components/infobox/wikis/valorant/infobox_league_custom.lua
- components/infobox/wikis/valorant/infobox_person_player_custom.lua
- components/infobox/wikis/valorant/infobox_series_custom.lua
- components/infobox/wikis/valorant/infobox_team_custom.lua
Setup Valorant Infoboxes to use dev feature flag.
> Valorant: Clean imports, enbale dev if dev-flag is on

- components/infobox/wikis/rocketleague/infobox_company_custom.lua
- components/infobox/wikis/rocketleague/infobox_league_custom.lua
- components/infobox/wikis/rocketleague/infobox_person_player_custom.lua
- components/infobox/wikis/rocketleague/infobox_series_custom.lua
- components/infobox/wikis/rocketleague/infobox_team_custom.lua
- components/infobox/wikis/rocketleague/infobox_unit_car.lua
Setup RL Infoboxes to use dev feature flag.
> RL: Cleanup imports, enable dev if dev-flag is on

- components/infobox/wikis/rocketleague/infobox_company_custom.lua
> Fix wrong import (League instead of Company)

- components/infobox/wikis/apexlegends/infobox_character_custom.lua
- components/infobox/wikis/apexlegends/infobox_league_custom.lua
- components/infobox/wikis/apexlegends/infobox_map_custom.lua
- components/infobox/wikis/apexlegends/infobox_person_player_custom.lua
- components/infobox/wikis/apexlegends/infobox_team_custom.lua
- components/infobox/wikis/apexlegends/infobox_weapon_custom.lua
Setup Apex Infoboxes to use dev feature flag.
> Apex: Cleanup Imports, enable dev if dev-flag is on

- components/infobox/wikis/crossfire/infobox_league_custom.lua
Setup Crossfire Infoboxes to use dev feature flag.
> Crossfire: Cleanup imports, require dev if dev-flag is on

- components/infobox/wikis/freefire/infobox_person_player_custom.lua
Setup FreeFire Infoboxes to use dev feature flag.
> FF: Enable dev if dev-flag is on

- components/infobox/wikis/halo/infobox_league_custom.lua
- components/infobox/wikis/halo/infobox_map_custom.lua
- components/infobox/wikis/halo/infobox_patch_custom.lua
- components/infobox/wikis/halo/infobox_person_player_custom.lua
- components/infobox/wikis/halo/infobox_team_custom.lua
Setup Halo Infoboxes to use dev feature flag.
> Halo: Cleanup imports, enable dev if dev-flag is on

- components/infobox/wikis/naraka/infobox_league_custom.lua
- components/infobox/wikis/naraka/infobox_person_player_custom.lua
Setup Naraka Infoboxes to use dev feature flag.
> Naraka: Enable dev if dev-flag is on

- components/infobox/wikis/overwatch/infobox_league_custom.lua
- components/infobox/wikis/overwatch/infobox_map_custom.lua
- components/infobox/wikis/overwatch/infobox_person_player_custom.lua
- components/infobox/wikis/overwatch/infobox_person_user_custom.lua
- components/infobox/wikis/overwatch/infobox_team_custom.lua
- components/infobox/wikis/overwatch/infobox_unofficial_world_champion_custom.lua
Setup OW Infoboxes to use dev feature flag.
> Overwatch: Cleanup imports, enable  dev if dev-flag is on

- components/infobox/wikis/pokemon/infobox_league_custom.lua
- components/infobox/wikis/pokemon/infobox_person_player_custom.lua
Setup Pokemon Infoboxes to use dev feature flag.
> Pokemon: Cleanup Imports, enable dev if dev-flag is on

- components/infobox/wikis/wildrift/infobox_item_custom.lua
- components/infobox/wikis/wildrift/infobox_league_custom.lua
- components/infobox/wikis/wildrift/infobox_person_player_custom.lua
- components/infobox/wikis/wildrift/infobox_unit_champion.lua
Setup Wild Rift Infoboxes to use dev feature flag.
> WR: Cleanup Imports, enable dev if dev-flag is on

- components/infobox/wikis/pubg/infobox_company_custom.lua
- components/infobox/wikis/pubg/infobox_league_custom.lua
- components/infobox/wikis/pubg/infobox_weapon_custom.lua
Setup PUBG Infoboxes to use dev feature flag.
> PUBG: Cleanup import, require dev if dev-flag is on

- components/infobox/wikis/pubgmobile/infobox_league_custom.lua
- components/infobox/wikis/pubgmobile/infobox_person_player_custom.lua
Setup PUBGM Infoboxes to use dev feature flag.
> PUBGM: Cleanup imports, enable dev if dev-flag is on

- components/infobox/wikis/mobilelegends/infobox_hero_custom.lua
- components/infobox/wikis/mobilelegends/infobox_item_custom.lua
- components/infobox/wikis/mobilelegends/infobox_league_custom.lua
- components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua
Setup MLBB Infoboxes to use dev feature flag.
> MLBB: Cleanup imports, enable dev if dev-flag is on

- components/infobox/wikis/starcraft2/infobox_building_custom.lua
- components/infobox/wikis/starcraft2/infobox_campaign_mission_custom.lua
- components/infobox/wikis/starcraft2/infobox_league_custom.lua
- components/infobox/wikis/starcraft2/infobox_map_custom.lua
- components/infobox/wikis/starcraft2/infobox_patch_custom.lua
- components/infobox/wikis/starcraft2/infobox_person_custom_shared.lua
- components/infobox/wikis/starcraft2/infobox_person_map_maker.lua
- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
- components/infobox/wikis/starcraft2/infobox_person_user.lua
- components/infobox/wikis/starcraft2/infobox_series_custom.lua
- components/infobox/wikis/starcraft2/infobox_show_custom.lua
- components/infobox/wikis/starcraft2/infobox_skill_ability.lua
- components/infobox/wikis/starcraft2/infobox_skill_spell.lua
- components/infobox/wikis/starcraft2/infobox_strategy_custom.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
- components/infobox/wikis/starcraft2/infobox_unit_custom.lua
- components/infobox/wikis/starcraft2/infobox_unofficial_world_champion_custom.lua
Setup SC2 Infoboxes to use dev feature flag.
> SC2: Cleanup imports, enable dev if dev-flag is on

- components/infobox/wikis/starcraft/infobox_league_custom.lua
- components/infobox/wikis/starcraft/infobox_person_player_custom.lua
- components/infobox/wikis/starcraft/infobox_series_custom.lua
- components/infobox/wikis/starcraft/infobox_team_custom.lua
Setup SC Infoboxes to use dev feature flag.
> SC: Enable dev if dev-flag is on

- components/hidden_data_box/commons/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/ageofempires/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/brawlstars/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/counterstrike/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/dota2/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/leagueoflegends/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/mobilelegends/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/overwatch/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/rainbowsix/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/rocketleague/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/starcraft2/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/valorant/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/wildrift/hidden_data_box_custom.lua
Add require dev if enabled to all Hidden Databox Customs. This will simplify testing in the future. 
Will also add it to the Template calls.
Sample tested
> HDB Customs: RequireDevIfEnabled

- .gitignore
Sometimes I use JetBrains IDEs so yeah, just easier if we can ignore those files too please :D
Well... I gave the IDE a banana and it didn't throw it back at me, so I think it works 😆
> Add `./idea` directory to gitignore since we have vscode there too

- standard/table.lua
Start of annotations for the Table Library.
Tested the annotations in VSCode. Found a few things that didn't work as expected, but are planned to be fixed in the next maintaince release (3.6.0) of sumneko.
> Partial annotation of Table library

- deploy.sh
> deploy: add dev wiki skip logging

- components/infobox/wikis/rainbowsix/infobox_weapon_custom.lua
Creates a new Siege Infobox Weapon for Rainbow Six
Tested on test [page](https://liquipedia.net/rainbowsix/User:Fenrir.SPAZ/Sandbox)
> Creating Siege Infobox Weapon

- components/infobox/wikis/freefire/infobox_person_player_custom.lua
added some roles to use the same module in infobox commentator
/dev module
> adding more roles to ff infobox player

- components/match2/commons/match_group_display_helper.lua
- components/match2/commons/opponent_display.lua
- components/match2/wikis/rocketleague/opponent_display_custom.lua
Remove deprecated function. One unused already, one replaced all current usages with the new function.
Tested with dev modules
> Update match2 to not use deprecated function

- components/standings/commons/standings_storage.lua
Add `finished` to standingstable extradata
/dev
> Add `finished` to standingstable extradata

- components/prize_pool/commons/prize_pool_import.lua
> Fix typo in PPT import

- components/team_card/team_card_storage.lua
Basically the teamCard equiv to #1965
/dev
> Set standardized lpdb_placement fields in teamCard storage

- components/prize_pool/commons/prize_pool_import.lua
Only apply gtl for finished gtls in ppt import
dev
> Only apply gtl for finished gtls in ppt import

- components/standings/commons/standings_storage.lua
Add enddate to standingstable extradata
dev
> Add enddate to standingstable extradata

- components/team_card/team_card_storage.lua
Add TBD Opponent as fallback if no opponent is entered in TeamCard standardized storage
(before it would error due to Opponent.resolöve not getting an opponent)
dev
> Add TBD Opponent as fallback if no opponent is entered in TeamCard standardized storage

- components/prize_pool/commons/prize_pool_import.lua
Do not overwrite date while merging in PPT import if present from the import data
dev
> Do not overwrite date while merging in PPT import

- components/match2/wikis/valorant/big_match.lua
Some minor cleanup in the Code of Big Match in Valorant.
It's currently unused in Production.
Module likely needs a complete code refactor down the line however.
> Minor code cleanup in Valorant Big Match

- components/match2/wikis/halo/match_legacy.lua
Adding the MatchLegacy module. 
Live
> MatchLegacy for Halo

- components/match2/wikis/sideswipe/match_legacy.lua
Create Match/Legacy for SideSwipe. Cleaned up version of what's been live for 6+ months.
Live
> Create Match Legacy for Side Swipe

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
Only format series number if it is numeric (instead of if it is not empty).
This catches some bs input in userspace (eliminating scirpt errors in userspace)
dev into live
> Only format seriesNumber if it is numeric

- components/prize_pool/commons/starcraft_starcraft2/prize_pool_starcraft.lua
Change nil check to isNotEmpty check to catch empty string cases
dev into live
> Change nil check to isNotEmpty check

- components/match2/wikis/counterstrike/match_group_input_custom.lua
There are some cases where the score for a match or map are unknown, so a manual winner needs to be set. The old version was working incorrectly setting default when no scores were set or if there was a draw, the manual `winner` input was ignored.
`/dev`
```
{{Match
|opponent1={{TeamOpponent|saw}}|opponent2={{TeamOpponent|ftw}}
|winner=1
|finished=true}}
```
- Old LPDB data:
- New LPDB data:
> Allow manual match/map winner

- standard/test/date_ext_test.lua
Create Unit Tests for Module:Date/Ext
https://liquipedia.net/commons/Module_talk:Date/Ext/testcases
> Create unit tests for Date/Ext

- standard/test/abbreviation_test.lua
Create unit test for Module:Abbreviation. Found an issue in the output of the Module thanks to it, see #2034.
https://liquipedia.net/commons/Module_talk:Abbreviation/testcases
> Create unit tests for Module:Abbreviation

- standard/test/flags_test.lua
Create Unit Tests for Module:Flags.
https://liquipedia.net/commons/Module_talk:Flags/testcases
> Create unit tests for Module:Flags

- standard/test/locale_test.lua
Create Unit Tests for Module:Locale
https://liquipedia.net/commons/Module_talk:Locale/testcases
> Create unit test for Module:Locale

- standard/test/page_test.lua
Create Unit Tests for Module:Page
https://liquipedia.net/commons/Module_talk:Page/testcases
> Create unit tests for Module:Page

- standard/test/math_util_test.lua
Create Unit Tests for MathUtil's functions
https://liquipedia.net/commons/Module_talk:MathUtil/testcases
> Create Unit Tests for MathUtil

- standard/test/placement.lua
Create Unit Tests for `Module:Placement`.
https://liquipedia.net/commons/Module_talk:Placement/testcases
> Create Unit Tests for Module:Placement

- components/match2/wikis/splatoon/match_legacy.lua
**Splatoon 3 Match2**
The Legacy module already has SMW usage cleaned out
**LIVE**
> Match Legacy for Splatoon

- standard/test/json_test.lua
Create Unit Tests for `Module:Json`
https://liquipedia.net/commons/Module_talk:Json/testcases
> Create tests for Module:Json

- plugins/sumneko_plugin.lua
The plugin is currently using the wrong indentation (4 spaces). This PR changes it to 1 tab indentation.
N/A
> Convert indentation to tabs in Plugin

- standard/string_utils.lua
Add intellisense annotations to Module:StringUtils.
> Add annotations to Module:StringUtils

- standard/test/string_utils_test.lua
Create Unit Tests for Module:StringUtils.
https://liquipedia.net/commons/Module:StringUtils/testcases
> Create unit tests for Module:StringUtils

- standard/test/text_sanitizer.lua
Create Unit Test for Module:TextSanitizer
https://liquipedia.net/commons/Module_talk:TextSanitizer/testcases
> Create unit test for Module:TextSanitizer

- standard/test/timezone_test.lua
Create Unit Tests for Module:Timezone
https://liquipedia.net/commons/Module_talk:Timezone/testcases
> Create Unit Tests for Module:Timezone

- standard/test/currency_test.lua
Create Unit Tests for Module:Currency
https://liquipedia.net/commons/Module_talk:Currency/testcases
> Create Unit Tests for Module:Currency

- standard/test/variables_test.lua
Create Unit Tests for Module:Variables
https://liquipedia.net/commons/Module_talk:Variables/testcases
> Create Unit Tests for Module:Variables

- standard/test/region_test.lua
Create Unit Test for Module:Region
https://liquipedia.net/commons/Module_talk:Region/testcases
> Create Unit Test for Module:Region

- standard/test/ordinal_test.lua
Create Unit Tests for Module:Ordinal
https://liquipedia.net/commons/Module_talk:Ordinal/testcases
> Create unit tests for Module:Ordinal

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
- components/infobox/wikis/starcraft2/infobox_league_hidden.lua
Adjust placement query in infobox league and infobox league hidden to use the new standardized fields.
dev into live
> Use standardized fields in sc2 infobox league placement queries

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
Adjust sc2 infobox player to use new standardized fields when querying placements
/dev
> Adjust sc2 infobox player to use new standardized fields when querying placements

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
stacked on #2080
Slightly change code style in sc2 infobox player
- removing underscores in front of (uppercase) global vars
/dev
> Slightly change code style in sc2 infobox player

- components/earnings/wikis/splatoon/earnings.lua
Earnings for Splatoon - Halo Port
**LIVE** 
e.g. https://liquipedia.net/splatoon/Chara (has only 1 earnings, numbers are /4)
Are this module required due to Splatoon is a Team of 4?.
> Earnings Module for Splatoon

- components/prize_pool/wikis/arenaofvalor/prize_pool_custom.lua
New Prize Pool for Arena of Valor
these are also clean ports of Mobile Legends PPT
LIVE, There hasnt been any concluded events tested under **TeamPrizePool** template input yet. As of now theres only one but its still an ongoing 
https://liquipedia.net/arenaofvalor/Arena_of_Glory/2022/Winter#Prize_Pool
> Add PPT for Arena of Valor

- components/infobox/wikis/arenaofvalor/infobox_team_custom.lua
Towards app readiness ported from WR
LIVE 
https://liquipedia.net/arenaofvalor/Isurus
There is this section that is SMW asks, is it possible if we can make it calls LPDB infos instead (or just any form of make it not using smw)?
> Infobox Team for AoV

- components/prize_pool/commons/starcraft_starcraft2/prize_pool_starcraft.lua
Calculate individualprizemoney  for non team opponents
dev into live
> Calculate individualprizemoney  for non team opponents

- components/infobox/commons/infobox_league.lua
> Prevent series icon links when the page does not exist

- components/infobox/wikis/warcraft/infobox_series_custom.lua
Creates a custom Infobox Series for Warcraft
Tested live
> Warcraft Infobox Series Custom

- standard/mock/mock_lpdb.lua
Expand the Lpdb Mocking with Storage. The Storage mock type checks the data.
Together with #2104
> Create Lpdb Storage mocking with value checking

- components/infobox/wikis/warcraft/infobox_series_custom.lua
Fixes an earnings error in the Infobox Series on Warcraft
Tested live
> Fixing error on WC Series

- components/prize_pool/commons/prize_pool_import.lua
Fix lastvsscore for gsl/swiss style groups in import.
Fix date being actually queried from the match.
dev into live
> Fix additional data for gsl/swiss style groups in import

- components/prize_pool/commons/prize_pool_import.lua
Fix index where to insert overtime.l
dev into live
> Fix index where to insert overtime.l

- components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua
Adding a third role to the infobox, for players that played multiple roles over their career
quickly tested this on the live module
> Add support for a third role in the player infobox

- standard/tournaments_summary_table/wikis/trackmania/tournaments_summary_table_custom.lua
Configuration for the standardized TournamentsSummaryTable/TournamentsMenu
new module, so live
> Add TournamentsSummaryTable/Custom for trackmania

- components/match2/wikis/rocketleague/match_group_input_custom.lua
Fix an issue introduced in #2131, related to Octane and Ballchasing being nil.
/dev
> Fix empty Octane and Ballchasing error

- components/prize_pool/wikis/counterstrike/prize_pool_custom.lua
Applying #2123 to CS custom.
`/dev` on cs wiki.
> Apply #2123 to CS Prizepools

- components/standings/commons/standings_storage.lua
- components/standings/commons/starcraft_starcraft2/standings_storage_starcraft_legacy.lua
requires #2153 to be merged first
Apply #2145 for standings storage
dev modules
> Apply #2145 to Standings Storage

- components/prize_pool/test/prize_pool_test.lua
This PR creates unit tests for the headers in the Prize Pool Table.
https://liquipedia.net/commons/Module_talk:PrizePool/testcases
> Create initial unit tests for Prize Pool Table

- components/group_table_league/commons/group_table_league_util.lua
- components/match2/commons/match_group_workaround.lua
- components/prize_pool/commons/prize_pool_import.lua
- standard/error_ext.lua
Remove usages of Deprecated `flatMap` in git modules
Tested some using /dev module
> Remove usages of `flatMap`
