Liquipedia/Lua-Modules

- components/prize_pool/commons/prize_pool_legacy.lua
If there's a legacy prizepool with the entry `''[[Link|Text]]''` then the outputted link would become `''Link`. This PR solves this by removing data outside the actual link. 
Before:
/dev module:
> Remove info around links in PPT Legacy

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
* use `participantlink` as an additional query condition (or) so for solo opponents in placements it doesn't have to check the json
--> this speeds up infobox player by ~4%
* cleanup: remove redundant brackets in the ConditionTree building
/dev, but pushed live now
> Make sc2 infobox player a bit faster

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Resolve Redirect the extradata field `series2`, just like `series` is done in the commons league, on Counter Strike.
/dev module
> Add Resolve Redirect on CS `series2`

- components/infobox/commons/infobox_league.lua
Sanitize tournaments name, tickername and shortname before saving them into LPDB and Wiki-Variables.
Before:
After:
/dev module
> LPA-6211: Sanitize tournament names before inserting into LPDB or Wiki-Variables

- components/match2/wikis/arenaofvalor/match_legacy.lua
- components/match2/wikis/dota2/match_legacy.lua
- components/match2/wikis/leagueoflegends/match_legacy.lua
- components/match2/wikis/mobilelegends/match_legacy.lua
- components/match2/wikis/wildrift/match_legacy.lua
These five MOBAs prefix their match1 static id's with `Legacy_`.
None of the other wikis does this it and there seems to be no reason for it. Additionally it causes issues when trying to work with a combination of match1 and match2 (as we have to do for now), as the direct link is broken.
Tested live on dota2
> Update StaticID on mobas to match other wikis

- components/prize_pool/wikis/counterstrike/prize_pool_legacy_custom.lua
Forward the points link override that CS had in their legacy setup to the new PPT. The field was previously called `|points-link`. Only works for valid points setup in `Points/data`.
/dev module
> Handling points-link in CS Legacy PPT

- components/prize_pool/wikis/counterstrike/prize_pool_legacy_custom.lua
Forward this parameter, used by the CS Custom to set a field into the tournament extradata.
> Forward `|qualifier=` in PPT Legacy for CS

- components/hidden_data_box/commons/hidden_data_box.lua
* Add option to disable query and hence suppress the warning that the parent is invalid in HDB.
Use Case: SC2 Series subpages (12)
e.g. https://liquipedia.net/starcraft2/Alpha_Pro_Series_Showmatches/2018
the Parent is a Series page (hence lpdb_series is set but not lpdb_league), but still several variables need to get set.
Infobox League/hidden isn't an option as it creates a lpdb_tournament entry that is not wanted.
* Add the warning for invalid parent only in main space, so Pages that got moved to user space do not clutter the category
/dev
> Add option to disable query in HDB

- components/infobox/wikis/leagueoflegends/infobox_league_custom.lua
> Fix typo'd wiki name in Module

- standard/flags.lua
- standard/flags_master_data.lua
For areas that are allowed to be entered as countries (per LP Country Policy) whilst not having an ISO-3166-1 code, map their alpha2 codes to the parent 3166-1 alpha2.
For example, this will make `wales` alpha2 `gb` instead of not existing at all.
/dev modules
> LPA-5995: Add mapping for 3166-2 to parent 3166-1 alpha2

- components/match2/commons/opponent_display.lua
Introduced in #1739.
Custom OpponentEntry was the reason of this bug.
Live
> Ensure non-nil in BracketOpponentEntry

- components/match2/wikis/counterstrike/match_legacy.lua
In counterstrike `|walkover=true` was set if a match was a forfeit, setting this prevented pages like https://liquipedia.net/counterstrike/Category:Pages_lacking_HLTV_stats from being populated. So this fix was created to avoid having match.walkover set with a random value, as this was causing a mess with [Module:CrossTableLeague ](https://liquipedia.net/counterstrike/Module:CrossTableLeague).
Live.
* https://liquipedia.net/counterstrike/ESL/Challenger_League/Season_42/Asia-Pacific
* https://liquipedia.net/counterstrike/ESL/Challenger_League/Season_42/Asia-Pacific/Weeks_1_to_4
*edit (CrossTableLeague not GroupTableLeague)
> Fix Bug caused by setting match.walkover in counterstrike

- components/infobox/commons/infobox_league.lua
- components/infobox/commons/infobox_series.lua
- standard/locale.lua
Add support for `|venuelink=` in addition to `|venue=`.
Split the external link from the display one in current method if in `|venue=` as a first step before doing bot runs that can be done later.
Old:
New:
/dev module
> LPA-6245 Split venue/venue-link in LPDB

- components/match2/commons/get_match_group_copy_paste.lua
- components/match2/wikis/counterstrike/get_match_group_copy_paste_wiki.lua
Add option to push header params up top in match2 copy paste
as requested by CS (Zaykor)
--> https://discord.com/channels/93055209017729024/874304000718172200/1009206326628454521
/dev
> Add option to push header params up top in match2 copy paste

- components/match2/commons/player_ext.lua
- components/match2/commons/starcraft_starcraft2/player_ext_starcraft.lua
Kick TournamentUtil  usage from Player/Ext and Player/Ext/Starcraft.
Reason: Need to use Opponent Module in TournamentUtil so it would create a require loop and since this is a tiny function it is way easier to do it this way instead of writing a new module that merges both.
/dev then pushed live to see if require loop is solved
> Kick TournamentUtil  usage from Player/Ext and Player/Ext/Starcraft

- components/infobox/wikis/rainbowsix/infobox_league_custom.lua
To allow for a clean moving over to `-1` as storage value for Misc, will do this in wiki customs at first, one by one. 
Module:Tier and other Modules using this info has been updated
https://liquipedia.net/rainbowsix/index.php?title=Module%3ATier&type=revision&diff=483234&oldid=448331
Live
> LPA-5998: Have `Misc` as an alias for Tier `-1` on R6

- components/match2/commons/match_group_coordinates.lua
Add
* `MatchGroupCoordinates.computeBracketOpponentCounts`
* * Computes the number of opponents from each round onward in a bracket.
* MatchGroupCoordinates.computeRawCounts
* * Computes the number of opponents from each round onward for each section in a bracket.
will be needed for prize pool automation
basically live since months via dhe's `Module:MatchGroup/Coordinates/Ext` which only holds those 2 functions
> Add 2 functions to `Module:MatchGroup/Coordinates`

- components/standings/commons/standings_storage.lua
Adjust standings storage in preparation for sc/sc2 for usage in deprecated group table slots
* allow direct opponent struct passing (sc/sc2 needs a wrapper for the opponent handling anyways (e.g. for archon, duo, ...))
* ~~do not store overtime in scoreboard if not set (—> discussion)~~
* move the file to match the directory structure of other components (and so the sc/sc2 wrapper can be added accordingly)
/dev module
> Adjust standings storage in preparation for sc/sc2

- standard/locale.lua
Fixes #1753. Due to incorrect logic in `getLocationData` , the index would be applies twice, eg. `country1` would become `country11` and `country2` would become `country22`. The issue didn't affect `getLocationDataIndexless`, so `country` would become `country1` as intended. 
This PR fixes the return values of `getLocationData` and renames parameters in `getLocationDataIndexless` for commonality. 
/dev module
```
mw.logObject(Locale.formatLocations{country='Sweden', country2='Norway'})
table#1 {
["country1"] = "se",
["country2"] = "no",
}
mw.logObject(Locale.formatLocations{country1='Sweden', country2='Norway'})
table#1 {
["country1"] = "se",
["country2"] = "no",
}
mw.logObject(Locale.formatLocations{country='Sweden', country2='Norway', country3='Finland'})
table#1 {
["country1"] = "se", …
```
> Fix issue with index being applied twice in `locaitons`

- components/prize_pool/commons/prize_pool.lua
Resolves #1718
The participant structure (ie non-opponent structure) expects `participantteam` in the extradata. This is used by `earnings` for instance. This PR adds the saving of this extradata field.
> Store `participantteam` in extradata in PPT

- components/match2/commons/match_summary_base.lua
Add option for adjusted reset match display in matchSummary.
As an example (with screenshot) see #1749
/dev modules
`brkts-popup-header-reset` class is new so for it to work ... cache ...
> Add option for adjusted reset match display in matchSummary

- components/standings/commons/standings_storage.lua
If either of the standard variables to indicate non storage are set (`disable_SMW_storage` & `disable_LPDB_storage`) or if the page is outside of main space, don't store the standings into LPDB.
hjp tested it for me <3
> Don't store standings into LPDB if disable storage is set

- components/infobox/extensions/commons/metadata_generator.lua
There was an issue when all three were missing the text generated would end abruptly.
Tested using `/dev`
> Fix metadesc generator for no date, teams, and prizepool

- standard/placement.lua
Previously using `display:none` spans was potentially causing issues with how the javascript was sorting the tables. This is now switched to using the intended sorting value way that's described on the MediaWiki wiki.
Tested live on CS wiki since `/dev` module was already in use for refactor and CS wiki uses `Module:Placement/Custom`
* https://liquipedia.net/counterstrike/User:IMarbot/placement_test
* https://liquipedia.net/counterstrike/Module:Placement
> Fix mediawiki sorting for placements

- components/match2/wikis/counterstrike/match_group_input_custom.lua
- components/match2/wikis/counterstrike/match_summary.lua
Avoid showing match countdown if a match is postponed or cancelled, and also don't set it as finished in these cases.
* `/dev` modules.
* [VANYLO x SCL Summer Cup 2022](https://liquipedia.net/counterstrike/VANYLO_x_SCL_Cup/2022/Summer)
> Improve counterstrike handling of match status (postponed/canceled)

- components/hidden_data_box/wikis/counterstrike/hidden_data_box_custom.lua
Fix if the template is called without any args.
Code for fix was copied from commons module. Tested on `/dev`.
> fix HDB nil error with no args present on cs

- components/hidden_data_box/commons/hidden_data_box.lua
Currently HDB sets the `tourtnament_parent` variable as `args.parent` if entered. This can cause the variable having spaces instead of underscores.
The local `parent` alsready has that cleaned up so just usse it instead
/dev modules
> Fix inconsistency in parent storage

- components/infobox/commons/infobox_league.lua
- standard/text_sanitizer.lua
Move the sanitization code out of the infobox module for consistent use across other modules. Also fix objectname not being sanitizied. Allows for work on #1735.
> Move tournament name sanitization

- standard/placement.lua
Basically, the code did nothing before because the css class `placement-text` already applied that identical CSS shadow stuff. Now it uses the boolean to determine whether to add the class or not, which achieves the wanted behaviour. Also, less hardcoded CSS, more darkmode fun, and less includes size memes.
Live on CS wiki.
> Placement: Fix skipShadowCell and remove unnecessary CSS

- components/prize_pool/commons/prize_pool_legacy.lua
Add option to merge slots with same place in legacy PPT
Why only as an option:
for wikis like CS that use `|points2=` to indicate that opponent 2 in this slot got those points the merge functionality doesn't work
but for wikis that do not have those the merge functionality ensures that legacy ppts look as intended
/dev module
without merging (looks the same as pre PR):
with merging:
> Add option to merge slots with same place in legacy PPT

- components/team_card/team_card_storage.lua
Further to the discussion in #templates-help on August 27th between myself and hjpalpha, It was said that this change would allow for /dev modules of TeamCard/Custom to be used when testing modules. 
An example of such can be found here, where I was attempting to pass some extradata fields from tournament -> placement for use in querying in another module. The page calls the /dev module initially using the "vardefine" set on the page, but calls the non dev version when storing lpdb data. 
https://liquipedia.net/apexlegends/Dark_meluca/PointsPrizePoolTest
> Allow for "TeamCard/Custom/dev" lpdb storage

- components/match2/wikis/leagueoflegends/match_summary.lua
Padding is inconsistent between game rows and ban rows. Changes match PR #1208.
Live:
With PR:
Dev module
> LPA-5874: Update paddings on LOL's match summary

- components/prize_pool/wikis/apexlegends/prize_pool_custom.lua
Added extradata fields passed from lpdb.tournament to lpdb.placement for use in other modules. 
Tested here using dev module:
https://liquipedia.net/apexlegends/Dark_meluca/PointsPrizePoolTest
> PrizePool: Add extradata fields to lpdb.placement storage

- components/prize_pool/commons/prize_pool_legacy.lua
Allow for space in the `<br>` or `<hr>` on either side of a potential `/`.
Tested with /dev module
> Allow for space on either side of the `/` in br/hr in Legacy PPT

- standard/placement.lua
Moving all the hardcoded inline colors to their CSS alternatives. This will de-clog a lot of hardcoded colors for darkmode. **Need to wait a few days for CSS to fully propagate before merging otherwise some colors will be missing**.
Tested live on CS wiki.
> Move placement colors to CSS

- standard/placement.lua
Add `w`, `d`, `l`, `dq` classes to Placement.placementClasses`
Idea is to adjust `Placement:getBackground()` to be able to read them from there
https://github.com/Liquipedia/Lua-Modules/blob/fde50c2ae82a4b92b76f6fb3adb4d0615f8e575b/components/prize_pool/commons/prize_pool.lua#L1163
maybe something like the following (only idea)
```lua
function Placement:getBackground()
for statusName, status in pairs(Placement.specialStatuses) do
if status.active(self.args) and PlacementInfo.getBgClass(statusName:lower())  then
return PlacementInfo.getBgClass(statusName:lower())
end
end
return PlacementInfo.getBgClass(self.placeStart)
end
```
this way we maybe could solve #1675 (together with adding w,d,l as special statuses)
N/A
> Add `w`, `d`, `l`, `dq` classes to `Placement.placementClasses` for later usage in PPT

- components/match2/wikis/splitgate/match_summary.lua
depends on #1748
Use new reset display in splitgate matchsummary.
/dev modules
> Use new reset display in splitgate matchsummary

- components/infobox/commons/infobox_league.lua
- components/infobox/commons/infobox_series.lua
Add support in infobox league and series to display multiple `venue`s with separate wikicode input. This would replace the freetext `|venue=` overtime. 
Wikicode would be:
* `|venueX=` (just `|venue=` would be an alias for `|venue1=`)
* `|venueXlink=` (internal or external link to a page)
* ~~`|venueXdesc=` (description to append at the end of the venue)~~
Gives
/dev module
> Support multiple `venue` with similiar wikicode format to `organizer`

- components/infobox/wikis/crossfire/infobox_league_custom.lua
Infobox League for CrossFire, loosely based from Arena of Valor ( #1000 ). Since CrossFire does contain multiple game versions for the wiki. The rest are some touchups for the wiki (e.g. highlighted tiers)
LIVE:
Some of the pages
https://liquipedia.net/crossfire/Special:LiquipediaDB/CrossFire_Pro_League/Season_20
https://liquipedia.net/crossfire/Special:LiquipediaDB/CrossFire_Stars_Summer_Championship/2022/Vietnam
##Side Note
- Should this be merged before  1774 (venueX) so that this one gets updated later on? 
(Crossfire has a good range of multiple venue cases.)
- CF will only have Player and League in Github aside from Match2
(Teams, Squad, Series works fine through the /base aka commons)
> Infobox League for CrossFire

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_legacy.lua
stacked on #1778
refers to https://github.com/Liquipedia/Lua-Modules/pull/1778#discussion_r958212605
Do not have 1/2/3/4 bg color for special statuses
/dev module
> Do not have 1/2/3/4 bg color for special statuses

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_legacy.lua
- components/team_card/team_card_storage.lua
* Improve ~~smw~~lpdb_prefix support (+ rename stuff from smwPrefix to lpdbPrefix)
* Fix bug where smw prefix caused teamCard and prize pool object names not to match if smw/lpdb prefix was set
* Enable dev stuff for `team_card_storage.lua`
/dev
> Improve lpdb_prefix support

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_legacy.lua
Add support for `|place=Q`, used on a few places on CS. If possible, we should look in the future at removing this if can be replaced with something better.
Resolves #1781
/dev module
> Add support for `|place=Q`

- components/prize_pool/wikis/counterstrike/prize_pool_custom.lua
- components/prize_pool/wikis/counterstrike/prize_pool_legacy_custom.lua
Resolves #1783
CS uses the LPDB field `qualified` for their tournament lists. Due to its complicated usage, the automatic handling frequently fails and need manual input. This PR adds support in the new prizepool for `|forceQualified=` for a slot and adds support for the legacy methods of `|qual=true`, `|qual=false` & `|noqual=true`.
/dev module
> PPT CS: Option to force LPDB field `qualified` and add legacy support

- components/prize_pool/commons/prize_pool_legacy.lua
- components/prize_pool/wikis/counterstrike/prize_pool_legacy_custom.lua
Resolves #1782
CounterStrike used `points2` to indicate points for the second opponent instead of a second column of points. The current implementation in legacy handles for all cases expect Qualifiers (Seed). This PR adds support for Qualifiers as well.
Before:
After:
Dev modules
> Add support for points1/2/... for Qualifiers on CS Legacy

- components/match2/wikis/dota2/match_summary.lua
- components/match2/wikis/leagueoflegends/match_summary.lua
Remove CSS overflow changes in dota2/lol as improvements with overflow has been put in the CSS by Ely.
Dev module
> Remove inline css overflow in matchsummary root

- components/prize_pool/commons/prize_pool_legacy.lua
- components/prize_pool/wikis/counterstrike/prize_pool_legacy_custom.lua
Resolves #1784 
Sort the Qualifiers IDs (1, 2, 3 etc) based on the following logic:
* Lowest number of Slots qualifying to this position (@iMarbot should this be changed to Lowest number of Opponents instead?)
* If tied, fall back to the one that was spotted first (ie first occurrence further up in the table)
Before:
After:
/dev module
> Sort Legacy Qualifiers 

- components/match2/wikis/rainbowsix/match_summary.lua
Issue: Operator Icons are cut off at the popup's edge.
Solved this by removing `overflow: hidden` from brkts-popup-body-game.
I also wrapped the hover styling in a `@media (hover: hover)`media feature (https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover) on https://liquipedia.net/commons/MediaWiki:Common.css/Brackets.css
> LPA-5869 Update operator icons on Rainbow 6

- components/notability/wikis/rainbowsix/notability_checker_config.lua
The notability config needs to be updated to handle `tier = -1` and removal of type = misc.
Live
> Update R6's notability config to reflect #1738

- components/infobox/wikis/apexlegends/infobox_league_custom.lua
- components/prize_pool/wikis/apexlegends/prize_pool_custom.lua
Storage of location data from `lpdb.tournament` into `lpdb.placement.extradata` with addtional formatting to store either the region or default to args.country. The formatted data is first stored as a custom variable in infobox league, and then is used in the prizepool module to assign it to the extradata of `lpdb.placement`.
Tested here using dev module:
https://liquipedia.net/apexlegends/Dark_meluca/PointsPrizePoolTest
> Additional Formatting of tournament region data

- components/prize_pool/commons/prize_pool.lua
- if the first slot doesn't have an opponent nor a place set the 2nd place is declared as 1st place too
- fix the "Too many opponents" assert the logic was wrong (it checked if there were at least as many opponents as max possible)
/dev
> Fix 2 bugs in PPT

- standard/placement.lua
As discussed with hjpa on discord, we felt that this module could benefit from a complete rewrite. Complete refactor of `Module:Placement`. Also adds support for CS `/Custom` needs. Essentially closes #1535.
Also makes a little progress towards addressing #1781.
* Unsure where/if `Placement.RangeLabel()` is used. I had thought it was used in prize pools but it's not. If it's not needed we can drop it.
* Which placement starts to use `placement-darkgrey` after top 32 may need discussion. CS never really used it for anything before, for example.
* Was unsure of correct way to do documentation for functions, I did what I saw in other module replacing what was currently in used in this one. If this incorrect, then will adjust accordingly or restore old comments.
* Function names and variable …
> Complete rewrite of placements (fix #1535)

- components/infobox/commons/infobox_league.lua
Add support to display description with the venue.
Wikicode:
Display:
LPDB:
/dev module
> Add support for venue description in Infobox

- components/match2/commons/starcraft_starcraft2/opponent_starcraft.lua
Remove redundant param
N/A the target function only eats 1 param anayways
> Remove redundant param

- components/match2/commons/starcraft_starcraft2/opponent_display_starcraft.lua
Fix bugs in `Module:OpponentDisplay/Starcraft`
- pass along team for players
- catch nil extradata
/dev
> Fix bugs in `Module:OpponentDisplay/Starcraft`

- components/infobox/commons/infobox_widget_links.lua
Apex Legends Status Public website that tracks accounts on Apex Legends. (Showing match histories, ranked leaderboards, character statistics)
> Add Apex Legend Status support to Widget Links

- components/prize_pool/commons/prize_pool.lua
Allow overwrite of lpdbTournamentData in prizePools.
SC/SC2 need it for ovwerwriting `mode` and `tournament`
/dev
> Allow overwrite of lpdbTournamentData in prizePools

- components/match2/commons/match_summary_base.lua
- components/match2/commons/match_summary_ffa.lua
- components/match2/commons/starcraft_starcraft2/match_summary_ffa_starcraft.lua
- components/match2/wikis/halo/match_summary.lua
- components/match2/wikis/rocketleague/match_summary.lua
Use Bracket Name instead of Short Name in Match Summary.
Changed the overflow to ellipsis since wrap looks quite bad. 
Fixed CSS to allow overflow to work at all (https://liquipedia.net/commons/index.php?title=MediaWiki:Common.css/Brackets.css&diff=prev&oldid=447943) 
> LPA-2465: Use Bracket Name in Match Summaries

- components/match2/wikis/arenaofvalor/match_group_input_custom.lua
- components/match2/wikis/dota2/match_group_input_custom.lua
- components/match2/wikis/leagueoflegends/match_group_input_custom.lua
- components/match2/wikis/mobilelegends/match_group_input_custom.lua
- components/match2/wikis/pokemon/match_group_input_custom.lua
- components/match2/wikis/wildrift/match_group_input_custom.lua
Match2 wiki input customs, that resolve redirect of Player Pages must ensure that underscore instead of space is used.
Related to #1802, this one fixes Players in Teams in match2 only.
Tested with dev on dota2
> LPA-6543: Customs that do resolve redirect on Player Pages must set underscore

- components/squad/wikis/mobilelegends/squad_custom.lua
Towards app readiness (as **newStorageDisplay** isnt compatible with the old module):
This one is just a clean port of LoL's squad for now (adjustments if needed) 
and at the same time I wanted to adjust the **Position** text to be just non-italic and without brackets (in which LoL fits the description), so all these are happening on one go
/dev calls on test pages - https://liquipedia.net/mobilelegends/User:Hesketh2/Test
Old Version (Already merged in the github)
Ported Version
The **Position** header is absent and empty, any possible way we could bring it back? (unless it is supposed to be that way)
> Updating Mobile Legends Squad modules

- components/prize_pool/commons/prize_pool.lua
Make objectName available in lpdb/smw injector processing and smwData processing
as a side effect it can be used to overwrite objectName
/dev
> Make objectName available in lpdb/smw injector processing and smwData processing

- components/prize_pool/commons/prize_pool.lua
- standard/smw_injector.lua
Stash instead of store smw (incl. injector)
* add `smw_injector.lua` (basically a copy of `lpdb_injector.lua`)
* set the smw data via the ppt module into a table and allow adjusting in /Custom via an injector
* then stash it into wiki vars so they can easily be stored into smw via a template (the template gets called in the prize pool templates, but OUTSIDE lua code, i.e. reduce lua run time significantly)
Advantages:
* easier adjusting of smw data, especially for non default opponents
* better performance
/dev module (smw inj. module is new, so live for that one)
> Stash instead of store in lua of smw data (incl. injector)

- components/infobox/wikis/ageofempires/infobox_league_custom.lua
Many maps have specific links entered in the infobox map list, as well as later in the brackets.
This is expected to rise even more once map pages are standardized (will likely always be append with the game, e.g. `Arabia (AoE4)`.
This change stores the entered map links (or the name, if no link is input) in variables, so it can be retriefed by MatchSummaries.
This will allow editors to just enter the map name (without the additional link) in a bracket, while the link will still be correct.
[/dev](https://liquipedia.net/ageofempires/Module:Infobox/League/Custom/dev)
> Store maplinks entered in the infobox in variables

- components/infobox/wikis/pokemon/infobox_person_player_custom.lua
Infobox Player  for Pokemon, different from the MOBA ones that uses commons, this one is local for the wiki due to the need of "Game Appearances" display, so these are largely based on the Halo Infobox Player
LIVE
Some of the pages:
https://liquipedia.net/pokemon/Wolfey / https://liquipedia.net/pokemon/Special:LiquipediaDB/Wolfey
https://liquipedia.net/pokemon/Tord_Reklev / https://liquipedia.net/pokemon/Special:LiquipediaDB/Tord_Reklev
Another wiki - Crossfire, will also share this same infobox as well once this is revised (if needed) and merged (since they need the game appearances as well)
> Infobox Player for Pokemon

- .github/workflows/luacheck.yml
- components/earnings/wikis/rocketleague/earnings.lua
With the latest release of https://github.com/mikepenz/action-junit-report `annotate_notice` must be set to `false` to only show warnings and errors.
I tested it locally on a PC
> Only display errors in luacheck junit CI run

- standard/timezone.lua
- standard/timezone_data.lua
Create a Timezone Library and associative data package. 
The data is based on https://liquipedia.net/commons/Special:PrefixIndex?prefix=Abbr%2F&namespace=10
The TZ Library currently only builds the String of above templates. 
```lua
mw.log(p.getTimezoneString('IST'))
--<abbr data-tz="+05:30" title="Indian Standard Time (UTC+5:30)">IST</abbr>
mw.log(p.getTimezoneString('CEST'))
--<abbr data-tz="+02:00" title="Central European Summer Time (UTC+2)">CEST</abbr>
mw.logObject(p.getTimezoneString('BAN'))
--nil
```
> Create Timezone library

- components/match2/commons/match_group_display_helper.lua
Resolve #1750. Requires #1829.
User who have turned off TZ adjustment should be shown the match in the matches timezone instead of UTC.
With TZ adjustment turned off:
Before:
After:
Dev module
> Use match timezone instead of UTC

- components/prize_pool/wikis/counterstrike/prize_pool_custom.lua
The LPDB Field is called `groupscore`, not `wdl`. This PR corrects it
> Fix WDL/Groupscore in CS Custom for PPT

- components/prize_pool/commons/prize_pool.lua
#stacked on #1836 due to altering stuff that gets changed there
Move `placement:_displayPlace()` call to the display part so it can be used on importet placements that had no manual input
/dev
> Move `placement:_displayPlace()` call to the display part

- components/match2/commons/player_ext.lua
Catch some edge cases for `pageVarEntry` in `PlayerExt.syncTeam`
where pageVarEntry.team (unresolved team template or lowercased underscore replaced pagename of the team) is set while pageVarEntry.template is not set
/dev
> Catch case in `PlayerExt.syncTeam` with `pageVarEntry` has no `template` property

- standard/timezone_data.lua
ADT uses UTC -3 as opposed to 4.
Source:
https://www.timeanddate.com/time/zones/adt
> Change Atlantic Daylight Time (ADT) to -3 instead of 4

- components/prize_pool/commons/prize_pool_legacy.lua
For walkover in legacy PPT, the `lastvs` field wasn't set rather the walkover to/from contained the opponent. This PR ensure that the opponent information is properly maintained into the normal PPT.
Tested with /dev
> Set `lastvs` on walkover to/from in PPT Legacy

- components/match2/commons/starcraft_starcraft2/opponent_starcraft.lua
Sync playerTeam if syncing player in StarcraftOpponent.resolve.
Intended so i can kick the _populatePlayerTeams function from the PrizePool/Import/Custom (the placement calls inside /Import will already do it)
/dev
> Sync playerTeam if syncing player in StarcraftOpponent.resolve

- components/hidden_data_box/commons/hidden_data_box.lua
Fix Typo in `.setWikiVariableForParticipantKey` function.
THe wiki-var names for resolved and unresolved have a different format.
/dev
> Fix Typo in Wiki-Variable name

- components/match2/commons/match.lua
- components/match2/commons/match_group_input.lua
- components/match2/commons/match_group_util.lua
- standard/date_ext.lua
Add support for unix timestamp in match2.
This PR adds support in parsing (`MatchGroupInput.readDate`), saving into LPDB (`Match._addCommonMatchExtradata`) & re-reading from LPDB (`MatchGroupUtil.matchFromRecord`).
/dev module
> Have support for (unix) timestamp in match2

- components/match2/wikis/rainbowsix/brkts_wiki_specific.lua
- components/match2/wikis/rainbowsix/match_group_input_custom.lua
- components/match2/wikis/rainbowsix/match_summary.lua
Use the support added in #1858 to use timestamp instead of the date strings.
/dev
> R6: Use timestamps instead of date strings

- components/infobox/wikis/apexlegends/infobox_weapon_custom.lua
Removal of old infobox/grenade and incorporated relevant fields into infobox/weapon/custom. 
Added two extra fields relevant to grenade information, alongside adding a check for `ammotype` to avoid concat error when calling the module for a grenade (as there is no ammo type)
Tested with `/dev`
> Merge Grenade infobox into Weapon

- components/match2/wikis/counterstrike/match_group_input_custom.lua
- Setting `|score2`in map wouldn't work as expected.
- Avoid the calculation of a draw when there are less than 2 opponents.
- Only calculate the winner when scores are set for both opponents.
`dev`module.
> Handle score2 in map and draw

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
Do not overwrite with nil.
Due to the call `player.yearsActive = CustomPlayer._getMatchupData(_PAGENAME)` overwriting `player.yearsActive` while the function does not return basically the calculated string gets overwritten with nil.
Change it so that the string is actually returned.
live (bug fix)
> Do not overwrite with nil

- components/prize_pool/commons/prize_pool.lua
Prevents setting the SMW properties for scores in case of Special Scores (non-numeric), since those properties are expected to be Numbers.
Sets walkover properties if necessary.
Will work for Legacy PPT once #1838 is merged.
TBD (changes only done in Github Web)
> SMW: Do not set score and opponent score in case of special scores

- components/prize_pool/wikis/apexlegends/prize_pool_legacy_custom.lua
Currently a lot of prizepools which call the legacy modules which have many teams in 1 place slot. This allows the PrizePool module to autoassign any slot with the correct sequential order
Tested with/dev here
https://liquipedia.net/apexlegends/User:Dark_meluca/PrizePoolMappingTest
> Allow places to autofill from PrizePool

- components/match2/commons/starcraft_starcraft2/opponent_starcraft.lua
In function `StarcraftOpponent.resolve` if syncing player do not return defaultRace if it wasn't manually entered
and replace string 'u' with `StarcraftRace.defaultRace`
/dev
> Do not return defaultRace if it wasn't manually entered

- components/prize_pool/commons/prize_pool_legacy.lua
depends on #1867
Set default for `fillPlaceRange` in Legacy PPT
Since apparently most wikis have cases where placeranges were not filled we imo should set it like this as default for Legacy PPTs.
For new PPTs we should not set `false` as the default since for automation (which i assume most wikis will like) needs the filled place ranges for the merging process.
(For SC/SC2 (who already have automation with the old PPT) the Legacy (#1828) is different anyways so not affected by this PR)
/dev
> Set default for `fillPlaceRange` in Legacy PPT

- components/match2/commons/match_group_input.lua
- components/match2/commons/match_summary_base.lua
- components/match2/wikis/leagueoflegends/match_group_input_custom.lua
- components/match2/wikis/leagueoflegends/match_legacy.lua
Should be manually deployed before merge due to it depending on each other and hence breaking stuff until merge bot run has updated all the modules
Adjust mvp storage + dependencies on lol.
Testcase for doing it on all wikis that have mvp stuff with the same input as lol has (e.g. R6)
* move mvp read function to commons and adjust it to retrieve more data from match2players
* adjust matchsummary base to be able to handle both formats (temp until we have everything switched)
* adjust match/legacy on lol to fit the new mvp player format
* cleanup " vs ' in lol matchsummary
/dev
> Adjust mvp storage + dependencies

- components/match2/wikis/counterstrike/match_legacy.lua
Match1 stores a draw as `draw`instead of `0`. Also, the resulttype is only set if a `opponent.score` is contained in `{'FF', 'DQ', 'L'}` or if the match is overturned, the resulttype its equal to `ff`.
Live.
- Before
- After:
Undo [Recent games/row](https://liquipedia.net/counterstrike/index.php?title=Template%3ARecent_games%2Frow&type=revision&diff=2345127&oldid=2338932)
> Handle winner and resulttype in match legacy

- components/match2/wikis/fortnite/opponent_display_custom.lua
To introduce, Fortnite is a Battle Royale wiki and has no submatches. 
These related module (3 that will be put on PR) are currently served for only one purpose and that is **to make the **TournamentPortalList** that was used on Starcraft2 to be functional on Fortnite** (as they allowed duos and trios result display)
But also just in case if these poses future usage for BR Match2 (whenever it happens) as well
https://liquipedia.net/fortnite/index.php?title=Template:TournamentPortalList&action=edit
https://liquipedia.net/commons/index.php?title=Module:Tournament/PortalList/Fortnite&action=edit
https://liquipedia.net/fortnite/B-Tier_Tournaments
(Goal is only to get this portal displayed, and both solo/team/duos/trios winners-runnerups are shown)
> Add Opponent Display for Fortnite

- components/match2/wikis/opponent_custom.lua
To introduce, Fortnite is a Battle Royale wiki and has no submatches. 
These related module (3 that will be put on PR) are currently served for only one purpose and that is **to make the **TournamentPortalList** that was used on Starcraft2 to be functional on Fortnite** (as they allowed duos and trios result display)
But also just in case if these poses future usage for BR Match2 (whenever it happens) as well
https://liquipedia.net/fortnite/index.php?title=Template:TournamentPortalList&action=edit
https://liquipedia.net/commons/index.php?title=Module:Tournament/PortalList/Fortnite&action=edit
https://liquipedia.net/fortnite/B-Tier_Tournaments
(Goal is only to get this portal displayed, and both solo/team/duos/trios winners-runnerups are shown)
**While the rest based on SC2 with …
> Add Opponent Custom for Fortnite

- standard/region/commons/region_data.lua
In Region/Data, there are several countries listed as regions, or aliases to regions. For the latter case they should be set up in the wiki-specific `Module:Region/CountryData`. The former case should be avoided as it's redundant data (query country=XX instead).
N/A
Possible that there are regression on some wiki related to `player`'s region storage.
> Remove Countries as Regions

- components/match2/commons/match_summary_base.lua
- components/match2/wikis/arenaofvalor/match_summary.lua
- components/match2/wikis/dota2/match_summary.lua
- components/match2/wikis/halo/match_summary.lua
- components/match2/wikis/leagueoflegends/match_summary.lua
- components/match2/wikis/mobilelegends/match_summary.lua
- components/match2/wikis/pokemon/match_summary.lua
- components/match2/wikis/rocketleague/match_summary.lua
- components/match2/wikis/valorant/match_summary.lua
- components/match2/wikis/wildrift/match_summary.lua
In match summary:
* Add option to override display style
* Set default style to `short`
* Set wikis with match summary widths >= 400px to `bracket`
Recommend to start the review with `match_summary_base.lua`.
dev module
Counterstrike (width = 330px, using default)
dota2 (width = 400px, using override)
> Update handling of Team Nane in Match Summary

- components/infobox/commons/infobox_person.lua
For player with lowercase teams the `teampagename` field can contain a lowercase first letter. Let's do a resolve redirect so to ensure that the pagename is correctly capitalized. 
/dev module
> LPA-6819: Resolve Redirect teampagename for LPDB Player

- components/earnings/commons/earnings_base.lua
As a stop-gap solution to distinguish award placements from normal placement, all award places will have their `mode` set to either `award_individual` or `award_team`. 
This PR make sure we treat `award_individual` in Earnings the same way as `individual`.
N/A
> Treat `award_individual` as `individual` when it comes to earnings

- standard/placement.lua
Due to oversight on my part, `args.text` was being ignored in refactored code. This PR addresses that.
`/dev` on commons.
Before:
After:
> Fix placement args.text being ingored

- components/squad/commons/squad_row.lua
Lightmode logos are almost invisible in darkmode.
Untested, I was unsure of how to test a commons change in userspace.
> Squad Tables: use darkmode icons

- standard/ordinal/ordinal.lua
`_ordinal()` previously returned the input + suffix, not just suffix. However, #1883 changed it to just suffix which broke reliance on the module.
The code here could also be changed as different way to fix this but all other uses of `_ordinal()` need to be modified too.
https://github.com/Liquipedia/Lua-Modules/blob/63fde24455eb9c0d04451b9a7e9eb20471c21ef0/components/prize_pool/commons/prize_pool_placement.lua#L413-L416
**Edit:** 2nd and 3rd not showing up as such is also fixed now.
**Edit 2:** Added some error prevention.
**Edit 3:** Refactored `ordinal()` to just call `_ordinal()` instead.
Live on commons due to being applied as emergency fix.
> Multiple fixes for `Module:Ordinal` plus error prevention in #1883

- components/match2/commons/opponent.lua
- components/match2/commons/starcraft_starcraft2/opponent_starcraft.lua
Do not save player pageVars for TBD in Opponent.resolve when syncing
can cause issues on pages due to flags and races wrongly being assigned to TBD stuff
also causes issues in prize pool when setting manual flag/race data for a player that data gets used for tbd opponents further down in the prize pool
/dev
> Do not save player pageVars for TBD in Opponent.resolve

- components/infobox/commons/infobox_team.lua
Currently, if `|disbanded=<date>` contains any none-date characters, such as `??` (which is quite common), the entire date will be stored as Epoch 0 in the Database.
This PR resolves that issue by running the Cleaner on it. The cleaner will convert `??` into `01`, which is the most accurate we can be. This fixes issues with using LPDB for Portal Teams to determine if a team is disbanded or not.
Not doing this for `created`, as it often contains two dates, one for org-create and one for org joining the game.
/dev module
> Convert `??` to valid date character for team's disband date

- components/prize_pool/wikis/ageofempires/prize_pool_custom.lua
Old prize pool used to set `LPDB.Placement.qualified` to 1 in case someone qualified.
This adds the same functionality to the new PPT.
Via /dev
> Set `LPDB.Placement.qualified` to 1 if there is a qualified prize

- components/standings/commons/starcraft_starcraft2/standings_storage_starcraft_legacy.lua
Add SC2/SC Legacy Wrapper for Standings Storage
* supports parsing opponents as input into `args[1]`
* determines opponentType (if supported) automatically
* supports team, solo, duo, trio, quad opponents
* due to targeting sc/sc2 specific classes for the player split this is only applicable for sc/sc2
* archon gets ignored (for reason see comment in the code)
live (new module)
> Add SC2/SC Legacy Wrapper for Standings Storage

- components/standings/commons/standings_storage.lua
Add `hasdraw` and `hasovertime` params as standard extradata for standings storage
/dev together with https://liquipedia.net/rainbowsix/Module:GroupTableLeague/sandbox and https://liquipedia.net/commons/Module:GroupTableLeague/next/downstream
> Add `hasdraw` and `hasovertime` params as standard extradata for standings storage

- components/standings/commons/starcraft_starcraft2/standings_storage_starcraft_legacy.lua
`Table.map` returns a table, so no fnUtil needed (in fact it causes issues on some pages).
live
> Fix TYPE_FROM_NUMBER

- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/opponent_display.lua
I wasn't a fan of how teams were being displayed in the new brackets. i.e., two team templates depending on screen width. Also, they weren't responsive in regards to opponent height differences across wikis. Also, was really not a fan of the up-to-the-edge'ness of wide logos. And finally, in narrow mode, some logos just turned into unidentifiable blobs.
So, I refactored `OpponentDisplay.BlockTeam()` to have a new style named `hybrid` which is similar to what `Module:Team` has for GTL for example. On wide views, the bracket name is displayed, and on narrow views, the short name is displayed.
The following CSS was also added/modified to allow for these changes:
```css
@media (max-width: 767px) {
.brkts-bracket {
--brkts-team-icon-width: 30px;
}
}
.brkts-opponent-entry …
```
> Responsive display for teams in new brackets

- components/infobox/wikis/fortnite/infobox_person_player_custom.lua
- components/infobox/wikis/fortnite/infobox_series_custom.lua
- components/infobox/wikis/fortnite/infobox_team_custom.lua
Setup Fortnite Infoboxes to use dev feature flag.
> Fortnite: Cleanup imports, require dev if dev-flag is on

- components/infobox/wikis/pubg/infobox_league_custom.lua
**Variables.varDefine('tournament_ticker_name', _args.tickername or '')** to allow match ticker to retrieved Tickername again
https://liquipedia.net/pubg/index.php?title=Module%3AInfobox%2FLeague%2FCustom&type=revision&diff=435115&oldid=435114 (before bot revert, after clearing cache, this works)
> Add missing Tickername Variables for PUBG

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Needed for tournament table lists, as with `series2`.
Tested on `dev` on CS wiki.
> Infobox League: store `shortname2` in CS custom

- components/infobox/commons/infobox.lua
- components/infobox/commons/infobox_basic.lua
- components/infobox/commons/infobox_widget.lua
- components/infobox/commons/infobox_widget_breakdown.lua
- components/infobox/commons/infobox_widget_builder.lua
- components/infobox/commons/infobox_widget_cell.lua
- components/infobox/commons/infobox_widget_center.lua
- components/infobox/commons/infobox_widget_chronology.lua
- components/infobox/commons/infobox_widget_customizable.lua
- components/infobox/commons/infobox_widget_error.lua
- components/infobox/commons/infobox_widget_factory.lua
- components/infobox/commons/infobox_widget_header.lua
- components/infobox/commons/infobox_widget_highlights.lua
- components/infobox/commons/infobox_widget_links.lua
- components/infobox/commons/infobox_widget_title.lua
- components/infobox/commons/infobox_widgets.lua
In order to facilitate the efficient testing of new functionality in the Infobox, adding support for the Dev feature flag.
This PR only enables it on the shared infobox components, ie widgets and Infobox + Infobox Basic.
Sample testing
> Infobox Core: Require dev if feature flag is enable

- components/infobox/wikis/wildrift/infobox_team_custom.lua
Part towards app readiness
_Clean Port of LoL team infobox_ so the coach and manager stuff  remains intact
LIVE
https://liquipedia.net/wildrift/Nova_Esports_(Chinese_Team)
https://liquipedia.net/wildrift/Rex_Regum_Qeon
Prize Pool supposed to be first to get PR, however after testing with a /dev template called, the old infobox team loses recognition of earnings, but that was a non-module Team Infobox anyway.
(theres Teams, HDB, Prize and Squad left since standings gonna be using /dota2 anyway)
> Add Infobox Team for Wild Rift

- standard/placement.lua
- standard/variables.lua
In placement:
* Fixed two parameter names being incorrect
* Changed two `table` to `number[]` 
In variables:
* Changed from `string` to `any?` for the varDefine methods, as it will accept anything that has a tostring,
Just Annotations
> Fix incorrect annotations in Variables and Placement

- components/match2/wikis/halo/match_summary.lua
Currently the team's in Halo's match summary are significantly misaligned.
This PR resolves this issue.
Any potential issue with Solo's are Out of Scope for this PR.
Live
> Fix Halo's MatchSummary for Teams

- components/match2/wikis/wildrift/match_group_input_custom.lua
- components/match2/wikis/wildrift/match_legacy.lua
- components/match2/wikis/wildrift/match_summary.lua
This is to allow new Match2 MVP Table to be working (it does not before)
/dev https://liquipedia.net/wildrift/User:Hesketh2/MVP
Tournament with Dev enabled https://liquipedia.net/wildrift/Icons_Global_Championship/2022/Knockout_Stage
summary and matchgroup will be include in same PR
> Adjust mvp storage + dependencies for Wild Rift

- components/match2/wikis/counterstrike/match_group_input_custom.lua
- components/match2/wikis/counterstrike/match_summary.lua
Sometimes a vod doesn't contain the full match/map video, so a parameter to insert a second vod (part 2) is required.
`dev`module and [Sandbox](https://liquipedia.net/counterstrike/User:LuckeLucky/Sandbox/2).
VodLink module should allow to set a custom title even if `gamenum` is numeric, or support some `part` parameter, with the objective to produce a title like `Watch VOD (part X)` or `Watch Game Y (part X)`.
> Add support for a second vod in map or match

- deploy.sh
After the change in #1945, if there are no changes to any dev wikis committed to main, the dev job will error (https://github.com/Liquipedia/Lua-Modules/actions/runs/3135441022/jobs/5091113088#step:4:15 ) on the `rm cookie_*` due to no cookies have been created. Providing `-f` should silence any such error.
```
-f          Attempt to remove the files without prompting for confirma-
tion, regardless of the file's permissions.  If the file does
not exist, do not display a diagnostic message or modify the
exit status to reflect an error.  The -f option overrides any
previous -i options.
```
Tested by Martin https://github.com/iMarbot/Lua-Modules/actions/runs/3135538041/jobs/5091332865
> Silence the `rm` error in deploy

- components/prize_pool/wikis/wildrift/prize_pool_custom.lua
Towards app readiness, port of LoL
For /Legacy calls the old templates already switched to it , general checking all things are in good state
For New Template inputs only tests are done  at past events so far
USD with wdl: https://liquipedia.net/wildrift/Wild_Circuit/2022/Asia_Invitational
Local: https://liquipedia.net/wildrift/ROG_Phone_Invitational_Series/2022
Local with qualifies and dq and wdl: https://liquipedia.net/wildrift/Origin_Series/2021/Finals
Achievements, Earnings remain unaffected by the new input.
> Add PPT for Wild Rift

- standard/table.lua
- standard/test/table_test.lua
Improve the logic of `Table.isEmpty(tbl)` so we no longer need the luacheck ignore.
Test cases:
https://liquipedia.net/commons/Module_talk:Table/testcases
> Table.isEmpty() refactor

- components/prize_pool/wikis/overwatch/prize_pool_custom.lua
`Overwatch` should be lowercase `overwatch` :p 
I didn't but surely it will be fine.
> Fix OW prize pool deploy

- standard/placement.lua
This function should accept both integers and strings. Since integers are not in native lua until 5.3 (and we're using modified 5.1), let's do number instead.
In VSCode
> Fix another `placement.lua` annotation issue

- standard/links/commons/links.lua
- standard/lua.lua
- standard/region/commons/region.lua
For both `requireIfExists` and `loadDataIfExists`, the behavior behind the parameter `default` can be handled with a `or` instead, which is exactly what's done in the clear majority places using this function. 
This PR removes the `default` parameter from both function.
In addition this PR changes the logic of the `requireIfEixsts` from using `require` to `Lua.invoke`. This allows for combination of `requireIfExists` and `requireDevIfEnabled`. To allow for this, Lua.requireIfExists accepts an optional options table.
**Modules needing updating to use `or`:**
* https://liquipedia.net/commons/Module:LuaUtils (done)
* https://liquipedia.net/commons/Module:Head_to_head_match_stages (done)
* https://liquipedia.net/commons/Module:ResultTable/next (done)
* …
> Update parameters for `requireIfExists` and `loadDataIfExists`

- standard/lua.lua
This PR changes automatic pass-through of the `|dev=true` flag through template to modules called by directly or indirectly from that Template.
This allows for replacing
```
{{#vardefine:feature_dev|1}}
{{SomeTemplate|...}}
{{#vardefine:feature_dev|}}
```
with
`{{SomeTemplate|dev=true|...}}`
and achieve the same effect.
> Check for dev in parent frames

- standard/table.lua
- standard/test/table_test.lua
#1959 is failing when a table has been loaded with `mw.loadData()`. Revert the change to Module:Table and add an additional testcase to ensure the issue doesn't appear in the future.
Live
> Revert #1959 and add a test for the issue

- components/prize_pool/commons/prize_pool_import.lua
- components/prize_pool/commons/prize_pool_legacy.lua
depends on #1851
Add Import Module for PPT
new module, tested together with /dev of the prize pool module and a test /Custom of the prize pool module on sc2
sc2 testing page (new pp not live, PrizePool/Custom not really set up):
https://liquipedia.net/starcraft2/User:Hjpalpha/PPT
for other wikis see screenshots below
If the placements in prize pool don't technically match what is in the swiss table, i.e. swiss might have all placements as 1 to 16 (1, 2, 3, etc, rather than 1-2, 3-5, etc.) but prize pools still has 1-2, 3-5, etc. regardless.
Issue with this is that the standings table doesn't hold that data, so the import module can not know that those are to be pushed into the same placement.
Possibly at a later date we can come up with a solution for this via storing additional data in …
> Add Import Module for PPT

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_placement.lua
stacked on #1850 due to that PR adding the Module that gets adjusted here
Add option in PrizePool/Placement to not call `readOpponentArgs`.
This is needed for the automation/import stuff since the opponents coming from there are already in the format we need and do not possess the args that would be needed by `readOpponentArgs`
live (new module not yet in use as of the start of this PR
> Add option in PrizePool/Placement to not call `readOpponentArgs`

- standard/lua.lua
#1943 had the wrong return value in the inner function `devEnabled`. It should return `nil`, not `false` if the parameter is not found.
Test case should be created for to avoid it appending again. 
dev module by hjp
> Lua.lua: Fix return value of `devEnabled`. It should have been `nil` not `false` as default

- components/prize_pool/commons/prize_pool_import.lua
Do not set lastVs if no lastVs is retrieved.
If we give the empty table in lastvs to `placement:_parseOpponents` it will think it is an tbd opponent
To avoid that add an IsEmpty check on the lastVs table and set lastvs as nil if lastVs is empty
live (module not in use yet)
> Do not set lastVs if no lastVs is retrieved

- components/squad/wikis/wildrift/squad_custom.lua
Towards app readiness, port from ML
All related auto modules (Active/Former OrgnizationAuto, Inactive/Active/Former SquadAuto) has also been ported from ML (which contains **newStorageDisplay** calls)
**Automated** https://liquipedia.net/wildrift/Nova_Esports_(Chinese_Team) 
**Mixed (Manual Timeline but Auto Roster)** https://liquipedia.net/wildrift/Rex_Regum_Qeon
**Manual**: https://liquipedia.net/wildrift/User:Hesketh2/test2
> Squad Module for WR

- components/infobox/commons/infobox_league.lua
- components/infobox/commons/infobox_person.lua
- components/infobox/commons/infobox_scene.lua
- components/infobox/commons/infobox_series.lua
- components/infobox/commons/infobox_team.lua
- components/infobox/extensions/commons/metadata_generator.lua
- components/infobox/extensions/test/metadata_generator_test.lua
- components/infobox/wikis/dota2/infobox_person_player_custom.lua
- components/infobox/wikis/rocketleague/infobox_person_player_custom.lua
- components/infobox/wikis/starcraft2/infobox_league_hidden.lua
Localisation.getLocalisation was deprecated in favor of Flags.getLocalisation in #1058.
This PR removes all uses of `Localisation.getLocalisation` in favor of `Flags.getLocalisation`. Since the parameters and return values are slightly different, some logic around has been changed (eg ` or ''` where necessary).
None-git modules have already been changed.
Dev modules.
Metadata generator tested here https://liquipedia.net/commons/Module_talk:MetadataGenerator/testcases
Rest of random pages that use it
> Migrate uses of deprecated `Localisation.getLocalisation`

- standard/localisation.lua
Once #1968 is merged, this function will be unused.
Checked twice with Wiki-wide search & github search that this function is unused (After merge of #1968)
> Remove unused & deprecated `Localisation.getLocalisation`

- components/prize_pool/commons/prize_pool_placement.lua
Store the opponent structure (`opponentname`, `opponenttemplate`, `opponenttype` and `opponentplayers`) into Placements.
dev module
> Store Opponent Structure in PrizePool

- components/infobox/wikis/rocketleague/infobox_league_custom.lua
Removing the custom Prize Pool handler on Rocket League Infobox League, in order to have them use the commons which have automatic currency conversion from local -> main currency.
> Remove Custom PrizePool on RL Infobox League

- components/infobox/commons/infobox_league.lua
- standard/localisation.lua
Deprecated `Localisation.getCountryName` and remove github uses of it. It's still widely used on none-git modules.
Dev module
> Deprecated `Localisation.getCountryName`

- components/infobox/extensions/commons/infobox_extensions_prize_pool.lua
If both `|prizepool=` (+ `|currency=`) and `|prizepoolusd=` is set, don't auto convert from local currency to USD, use the manual input.
dev module
> Use prizepoolusd if set

- components/match2/commons/starcraft_starcraft2/player_ext_starcraft.lua
Do not set player wiki var for default race
/dev
> Do not set wiki-var when a player race is unknown

- components/match2/wikis/counterstrike/match_external_links.lua
Updating the link so it's one less redirect
Went to the HLTV website and saw it redirected me
> hltv is always at www.hltv.org

- components/match2/wikis/counterstrike/match_group_input_custom.lua
match.liquipediatier is a number and was being compared agains string tier.
Earnings year also adjusted to retrieve earning from 2 years.
Live
> Adjust Featured match

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/commons/starcraft_starcraft2/opponent_display_starcraft.lua
Allow penalty as param in sc/sc2 opponents in match2.
Used for cases where opponents are awarded penalty maps (i.e. start with a negative score)
/dev
> Allow penalty as param in sc/sc2 opponents in match2

- components/prize_pool/commons/prize_pool_import.lua
Change default group score delimiter in PPT import
Investigation https://github.com/Liquipedia/Lua-Modules/pull/1983#issuecomment-1264253532 showed that `/` is the commonly used delimiter
/dev
> Change default group score delimiter in PPT import

- components/infobox/wikis/valorant/infobox_team_custom.lua
Valorant requested `IGL` to be shown together with the other roles.
> Move `IGL` in Valorant's Infobox Team

- components/prize_pool/commons/prize_pool_placement.lua
Allow partial input for non literal/team Opponents.
E.g. if the nationality (or race/faction) of the first/... is already known
required for sc/sc2 legacy handling
/dev
> Allow partial input for non literal/team Opponents

- components/prize_pool/wikis/leagueoflegends/prize_pool_custom.lua
- components/prize_pool/wikis/rainbowsix/prize_pool_custom.lua
- components/prize_pool/wikis/rocketleague/prize_pool_custom.lua
As per the discord conversation on september 3rd R6 uses WDL for GSL style groups:
https://discord.com/channels/93055209017729024/315607343331278848/1015435649710559373
As per the discord conversation on september 3rd RL uses WDL for GSL style groups:
https://discord.com/channels/93055209017729024/202524980146208768/1015435677531373578
As per the discord conversation on september 3rd lol uses WDL for GSL style groups:
https://discord.com/channels/93055209017729024/276340346831765504/1015435528797171792
N/A
> Set `allGroupsUseWdl` as `true` for R6, RL and lol

- standard/test/reference_cleaner_test.lua
Per documentation, the first parameter is expected, while the second is actual. (https://liquipedia.net/commons/Module:ScribuntoUnit#assertEquals) 
Update the code the reflect that.
N/A
> Fix `expected` vs `actual` in Reference Cleaner Tests

- standard/links/commons/links.lua
FACEIT "championship" links now work with just a `/`. Also, hub links need a `/` at the end to function
- https://www.faceit.com/en/championship/8ef9edaf-5e83-4cd6-9c01-fda8c948fafb/ works
- https://www.faceit.com/en/hub/fcd8dabb-31e2-4447-87df-3bfb79dc9546/ works
- https://www.faceit.com/en/hub/fcd8dabb-31e2-4447-87df-3bfb79dc9546 doesn't work
> FACEIT link suffix update

- components/standings/commons/starcraft_starcraft2/standings_storage_starcraft_legacy.lua
By default do not store Standings from old manual group table templates from non main space.
The data causes issues on some old user space pages with the ppt import.
dev into live
> Do not store legacy standings from non main space

- components/prize_pool/commons/starcraft_starcraft2/prize_pool_legacy_starcraft.lua
When using import do not fill up opponents until slot size while reading a slot. Instead first merge slots with the same place and fill them up afterwards. For filling up the last slot/opponent (without the opponent data (race, flag, link, displayname, wdl, lastvs, score)) is basically copied.
This is needed so when merging slots while import is enabled, we do not get too many opponents in a slot from reading the args.
basically it is for stuff like this:
```
{{prize pool slot|place=13-16|usdprize=1900|points=90}}
{{prize pool slot|place=13-16|usdprize=1775|points=90}}
{{prize pool slot|place=13-16|usdprize=1900|points=90|count=2}}
```
before it got 16 opponents now 4
but at the same time we also have such cases:
```
{{prize pool slot|place=13-16|usdprize=1900|points=90}}
```
here we need …
> Adjust filling up slots handling in SC/SC2 PPT Legacy

- components/prize_pool/commons/starcraft_starcraft2/prize_pool_legacy_starcraft.lua
please merge #2018 first
The `local args = Template.retrieveReturnValues('PrizePool')` (line 36) empties the wiki vars, hence the old prize pool can not retrieve them anymore.
Changed the old prize pool to accept passed args, this way we can now pass the retrieved args to the old module
live
> Adjust old prize pool call in case of awards

- components/match2/commons/match_group_legacy.lua
In #1510, one function call to `luaGetMap` was not updated. This PR updates said function call.
It was missed due to only used in match1->match2 conversion on RL and R6. We should look at adding better tests for match2.
Live
> One function call was not updated in #1510

- components/match2/wikis/splatoon/brkts_wiki_specific.lua
**Splatoon Match2** (Explanation were done in the match modules already)
LIVE
https://liquipedia.net/splatoon/Splatoon_2_World_Championship/2019#Results
I thought adding BrktsSpecific up just for now, since it has the UNIX TIME changes that were related.
Legacy werent really related to the UNIX changes so I can wait until merge then PR that one later
> BrktsSpecific for Splatoon

- components/prize_pool/commons/starcraft_starcraft2/prize_pool_starcraft.lua
Fix var name when getting opponenttype for legacy mode
/dev into live
> Check opponenttype in the correct table when determining mode

- components/prize_pool/commons/starcraft_starcraft2/prize_pool_legacy_starcraft.lua
Catch Seeds that are plain text.
SC2/SC has several old PrizePools that have plain text in columns that have the header Seed (be it from localcurrency or points).
Currently those are discarded due to them not having a link and hence `LegacyPrizePool.parseWikiLink` returning an empty table.
This PR catches those cases and converts them to `freetext` so they still get displayed.
/dev into live
example: https://liquipedia.net/starcraft2/index.php?title=Gold_Series_International_2016/Qualifiers/Europe&action=edit&section=3
(the `Paid Trip` in seed column)
> Catch Seeds that are plain text in Legacy

- components/prize_pool/commons/starcraft_starcraft2/prize_pool_legacy_starcraft.lua
Fix slotSize for 2v2, Archon, ...
Currently when converting 2v2/... Prize pools it thinks that there are twice as many opponents as entered due to 1 opponent having 2 unnamed args
/dev into live
> Fix slotSize calculations for Non-Team/Solo opponent in SC2 Legacy

- components/prize_pool/commons/prize_pool_placement.lua
Fill up placement with first opponent if no first opponent is present
This is so that empty slots are accepted by the Prize pool.
While at it extract the if conditions into a function for better readability + better comments.
/dev
> Fill up placement with first opponent if no first opponent is present

- components/match2/wikis/counterstrike/match_group_input_custom.lua
Related to (#2027). Using `scoreinfo.status == 'S'` guarantees that score is both set and numeric. This needs to be done to avoid weird scores inputs messing things up.
/dev
> Use `scoreinfo.status` to check for score set

- components/match2/wikis/counterstrike/match_external_links.lua
Both `hltv` and `hltvlegacy` can have `stats`and `legacystats` as map stats.
Live.
- (OLD) `hltv` and `legacystats`
- (NEW) `hltv` and `legacystats`
> Both `hltv` and `hltvlegacy` can have `stats`and `legacystats` as map stats

- standard/test/reference_cleaner_test copy.lua
Use LuaImport and RequireDevIfEnabled, to allow for [Template:RunTests](https://liquipedia.net/commons/Template:RunTests) to work.
Live
https://liquipedia.net/commons/Module_talk:ReferenceCleaner/testcases
> RequireDevIfEnavbled for ReferenceCleaner Testcases

- components/match2/wikis/splatoon/match_summary.lua
**Splatoon Match2**
Splatoon is a multi map + multi mode like Overwatch
However the editors were asking a **weapon input** that allows each map to show the weapon picked by each player (as **weapon** in Splatoon are treated like **hero** in LoL: cannot be changed/replaced  and always same during a full map)
Originally I planned to port Brawl Stars but because the weapon input, Hjp has suggested the idea and went on to help rebuild this with LoL as the baseline instead. So the end result is a hybrid of Objective-based Match2 and MOBA Match2
**WeaponIcon** module has major rework to allow image called based on what **game** is stored in LPDB instead of Date (as they are visually different)
Other stuff such as MVP and Map Vetoes are also provided (not tournament standard, but some event has …
> MatchSummary for Splatoon

- standard/abbreviation.lua
While doing #2035 I noticed that the Abbreviation Module is missing a `"` in its return. Mediawiki parser seems to currently automatically correct it, but we should return correct html.
> Add missing `"` in Abbreviation Module

- components/infobox/commons/infobox_team.lua
In infobox team move earnings variables from globals into self,
This is so that wikis can pass the self calculated values to lpdb storage without having to shadow e.g. the loop that stores the earnings per year.
/dev
> Move earnings variables into self

- components/infobox/wikis/starcraft2/infobox_team_custom.lua
- use new (standardized) keys from lpdb_placement
- store teamearnings per year into extradata (making use of #2045)
- store playerEarnings per year into extradata
- store playerearnings total into extradata
- norm those stored values to round with precision 0
- use module Opponent when checking on opponent types
/dev
> Rework earnings for sc2 infobox team

- plugins/sumneko_plugin.lua
When using LF lua files in combination with our Sumneko Lua plugin, the line break would be removed. This is because there's an off by one error in the code.  (See examples, https://github.com/sumneko/lua-language-server/wiki/Plugins & https://github.com/sumneko/sample-plugin/blob/master/.vscode/plugin.lua#L7).
The reason is worked on CRLF is that the CR would be removed, which had no impact on the Language Server. Howevewr on LF, the LF would be removed, causing multiple lines be merged (and effectively commented out).
Chcked the `diffed` files in my VSCode (CRLF) and Martins VSCode (LF).
> Fix issue when using LF with our Plugin

- components/infobox/wikis/starcraft2/infobox_person_custom_shared.lua
Fix capitalisation typo in mapmaker category check
live
> Fix capitalisation typo in mapmaker category check

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Catch unset winner for finished matches in sc/sc2 match2 input.
- add business logic to determine the winner of a finished match where neither bestof nor winner are set
- change `true` string to bool when setting `match.finished`
/dev
> Catch unset winner for finished matches

- components/infobox/wikis/splatoon/infobox_person_player_custom.lua
Infobox Player, this one is port of Mobile Legends (which was the same as AoV/WR anyway) and edited to worked with the Weapon Input to display Signature Weapon for each player (as Weapon are treated as Characters in Splatoon)
LIVE
https://liquipedia.net/splatoon/Chara
**Module:WeaponIconPlayer** is Intentional, due to **Module:WeaponIcon** for Match2 ties to the game input it wouldnt work on player infoboxes 
so I had a separate one both **Module:WeaponIconPlayer** and /Data just for Player Infobox in which this one is the normal one we've done on MOBA Wikis (date switches, instead of game switches)
https://liquipedia.net/splatoon/index.php?search=Module%3AWeaponIconPlayer
https://liquipedia.net/splatoon/index.php?search=Module%3AWeaponIconPlayer%2Fdata
Team Infobox uses /Base so there …
> Infobox Player for Splatoon

- components/infobox/wikis/fortnite/infobox_series_custom.lua
Currently on Fortnite, the Infobox Series has a error for the Prize pool implementation (seen below)
The current module queries for the ``series.name`` however this is nil. When logging ``series`` (as passed in by the function), the only parameter in the series is the data as saved in LPDB under the "name" field, thus making ``series`` the correct call here
Tested with a /dev modul and results are shown here
> Correcting error in Fortnite Infobox/Series

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
Adjust achievements processing in sc2 infobox player
- kick log (added with #2080 by accident)
- adjust sort order in the lpdb call (weight before placement)
- change order of `Array.sub` and `Array.extendWith` calls to be a tiny bit more efficient and not loose order
--> (i do not get why but when doing it the other way around it doesn't take the first objects from the 2nd table but random ones although `Array.extendWith` uses ipairs afaik)
--> this only affects player pages who have < 10 real achievements
/dev
> Adjust achievements processing in sc2 infobox player

- components/team_card/test/team_card_storage_test.lua
Depends on #2082
Create unit tests for the two helper functions in `TeamCard/Storage`. Currently there's no good way to verify the LPDB storage.
https://liquipedia.net/commons/Module_talk:TeamCard/Storage/testcases
> Create unit tests for TeamCard/Storage

- components/infobox/wikis/splatoon/infobox_league_custom.lua
Infobox League, this is ported from Arena of Valor due to the need of **Game Version** inputs which ties into the Match2 structure
LIVE 
Some of the pages
https://liquipedia.net/splatoon/The_Big_House/10
https://liquipedia.net/splatoon/Splatoon_2_World_Championship/2019
https://liquipedia.net/splatoon/GENESIS/7
> Infobox League for Splatoon

- components/infobox/wikis/starcraft/infobox_league_custom.lua
Use standardized placement keys in bw infobox league query
/dev
> Use standardized placement key in bw infobox league query

- standard/namespace.lua
Our unit tests runs on namespace `Module Talk` (id: 829), so it's important to treat it the same as Mainspace when it comes the logic. 
Hence adding it to `isMainspace()` function.
/dev module
> Treat namespace `Module Talk` as Mainspace

- components/infobox/wikis/starcraft/infobox_person_player_custom.lua
- Use standardized lpdb_placement keys in BW infobox player earnings queries
- Condition on player name with and without underscore
- change the conditions slightly to drop the query runtime a bit
/dev into live (basically the same change already done on sc2 some days/weeks ago)
> Use standardized lpdb_placement keys in BW infobox player earnings queries

- components/infobox/wikis/starcraft/infobox_team_custom.lua
1. Store the same (extra)data on BW team pages as on sc2
- playerearningsinXXXX
- playerearnings
- earningsinXXXX (via passing to commons)
2. Switch to using standardized keys in placement query and data processing
3. Replace some hardcoded `'solo'`/`'team'` to using `Opponent.solo`/`Opponent.team`
/dev into live (99% copy paste from sc2)
> Store the same data on BW team pages as on sc2

- components/prize_pool/commons/prize_pool_import.lua
Ignore `BYE` opponents during import
Limitations:
- matches have to be finished and the BYE Opponent has to be the loser
--> should not be a real limitation as matches with set winner should be finished anyways (unless overwritten and overwrite option available)
/dev module + a few tests on sc, sc2, cs and r6
> Ignore `BYE` opponents during import

- components/prize_pool/commons/prize_pool_import.lua
Currently Reset matches are ignored by PPT import (as one of the limitations of the MVP for it).
This PR makes the import use the reset match if present to determine the 1st/2nd place (instead of using the grandfinal match)
/dev
how should we handle scores in this case?
should we use the scores of the reset match or are there other suggestions?
> Handle reset matches in PPT import

- components/match2/wikis/counterstrike/match_summary.lua
Sometimes a vod is only set on the game, so for a best of 1, the title would be `Watch Game 1` instead of `Watch VOD`. The icon was also adjusted for a best of 1.
`/dev`
> Change vod link title and icon for a bestof 1

- components/match2/wikis/counterstrike/match_summary.lua
When only the first half of overtime was input, the half score for the team on the right would appear shifted by one column. With this fix, the ways scores and half scores are being added to display are simplified, only needing to add the direction, `rtl`, to the right div.
/dev
> *Overtime 1st half
> Fix right team first half overtime score display

- components/prize_pool/commons/prize_pool.lua
The `)` was outside of the italics when the `(` was inside. So, I moved the `)` to be inside too, otherwise it looked bad.
`/dev`
**before**
**after**
> fix ppt exchange info italics

- components/infobox/wikis/ageofempires/infobox_league_custom.lua
In AoE, series pages are often redirects, e.g. for multiple seasons of one big series.
Due to the infobox previously resolving redirects before storage, it wasn't possible to query for these different seasons using LPDB.
This prevents resolving of redirects for args.series, while still resolving redirects before storing seriespage.
via /dev
> Prevent resolving of redirects for arg.series

- components/hidden_data_box/wikis/arenaofvalor/hidden_data_box_custom.lua
Towards app readiness, ported from ML
Key parts of this are the **aovpremier** publisher tier line, as I need this to trigger the highlights for the Match Tickers, and actually the field name for this is originally **garena-sponsored** but i'm going to change it to **aovpremier** to be more standard 
(as there was prev. case with HoK Contributors wrongly assumed that theres another param for Honor of Kings, the other game we cover on this same wiki. This **aovpremier** should help as aov is refer to just the wiki. Better field name anyways)
LIVE
Infobox League will have a PR to changed **garena-sponsored** to **aovpremier**
https://github.com/Liquipedia/Lua-Modules/pull/2097
> HDB for AoV

- standard/mock/mock_lpdb.lua
The current regex doesn't allow for special characters. Setup with a lazy any character instead of the current char-set.
dev module
> Make all characters acceptable in LPDB Mock for values

- components/prize_pool/wikis/apexlegends/prize_pool_legacy_custom.lua
https://github.com/Liquipedia/Lua-Modules/pull/1857
Reversion of commit made in the pull request above to hotfix prizepool errors with too many teams in the one slot. Have manually changed all pages so the previous commit can be reverted, as per Rathoz' comment
> Revert of prizepool autofill slots

- components/infobox/wikis/dota2/infobox_team_custom.lua
Template `Team achievements` needs team name.
/dev
> Fix achievements in Infobox/Team for Dota 2

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_import.lua
Adjust parent handling in PPT import
- pass self from `Module:PrizePool` instead of placements and args
- use the so passed parent (above passed self) in the `_emptyPlacement` fucntion
Advantages:
- can call prizepool now without initial slot (very rare as it automatically means no prizes specified)
- prep for #2003
/dev
> Adjust parent handling in PPT import

- standard/mock/mock_lpdb.lua
- standard/type_util.lua
Add the custom type `pagename` to our Type Checking. 
`pagename` is a `string` with two additional criteria, first letter must be uppercase and it may not contain any spaces. 
Also update Lpdb specification to use this field where applicable, instead of the non-existing type `page`.
> Add `pagename` as a custom type

- components/prize_pool/wikis/pubgmobile/prize_pool_custom.lua
Ported from Apex Legends.
Auto LocalCurrency stuff from #2137 applied here as well
LIVE 
Only few under the new **TeamPrizePool** input , these are one of it
https://liquipedia.net/pubgmobile/PUBG_Mobile_Pro_League/Southeast_Asia/Championship/2022/Fall
At the time of this PR going up I havent started on **SoloPrizePool** conversion, although quick copy from any **SoloPrizePool** input from Solo Apex Legends tournaments does work fine.
> PPT (New) for PUBG Mobile

- components/standings/commons/standings_storage.lua
Throw intentional error in case of missing standings index.
Currently if standingsIndex is not set in several instances on the same page we get several standings on the same page with the same index, i.e. we get bad data and hence also possible issues for the app.
/dev
> Error for missing standingsIndex

- components/match2/commons/match_group_input.lua
- components/match2/commons/match_summary_base.lua
- components/match2/wikis/leagueoflegends/match_summary.lua
Allow comments per mvp player in mvp display in matchSummary
/dev
> Allow comments per mvp player in mvp display in matchSummary

- components/squad/test/squad_test.lua
- standard/mock/mock_lpdb.lua
Create unit tests for Squads.
Add LPDB storage mocking for SquadPlayer.
https://liquipedia.net/commons/Module_talk:Squad/testcases
> Add unit tests for Squads

- standard/tournaments_summary_table/wikis/trackmania/tournaments_summary_table_custom.lua
Removes the additional `Custom` in the magic comment.
Correct URL is https://liquipedia.net/trackmania/Module:TournamentsSummaryTable/Custom
N/A
> Fix wrong name in magic comment

- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/rocketleague/match_summary.lua
Ballchasing is a website that hosts replays for Rocket League, all of the RLCS replays are hosted there. Liquipedia always has the link to the Ballchasing tournament page on the wiki tournament page, but with this pull-request it will be possible per match, so the user does not have to relocate the match they want to find the replays for.
/dev module
> Add Ballchasing link to RL's match summary. Fix link storage on RL

- standard/info/wikis/ageofempires/info.lua
- standard/info/wikis/fortnite/info.lua
- standard/info/wikis/rocketleague/info.lua
- standard/info/wikis/starcraft/info.lua
- standard/info/wikis/starcraft2/info.lua
Add Custom opponent Libs to info modules
Will allow to require the correct opponent libs via
```lua
local Info = require('Module:Info')
local Lua = require('Module:Lua')
local Opponent = Lua.import('Module:'.. Info.opponentLibrary or 'Opponent', {requireDevIfEnabled = true})
local OpponentDisplay = Lua.import('Module:'.. Info.opponentDisplayLibrary or 'OpponentDisplay', {requireDevIfEnabled = true})
```
N/A, just adding data to info modules
> Add Custom opponent Libs to info modules

- standard/lua.lua
Add proper annotations to Lua.import. Mainly to get the options table in intellisense.
> Add annotation to Lua.import

- components/opponent/commons/opponent_libraries.lua
Add `Module:OpponentLibraries` for easily fetching the wanted opponent library and opponent display library
created the module and tested it with the Results table i am currently building in my sandboxes (simulate the case of non sc2 with temp removing the opponent libs from module:Info)
<https://liquipedia.net/starcraft2/index.php?title=Module%3AHjpalpha%2Fsandbox30&type=revision&diff=2297928&oldid=2297924>
> Add `Module:OpponentLibraries`

- components/match2/wikis/rocketleague/match_summary.lua
Spotted error on an old Rocket League bracket
`Module:MatchSummary:386: bad argument #1 to 'cssText' (string, number or nil expected, got boolean)`
https://liquipedia.net/rocketleague/Rocket_League_Championship_Series/Season_1/North_America/Qualifier_2#Playoffs
This PR fixes this issue by ensure a boolean is never returned by the ternary. 
Dev module
> Fix issue on Rocket League match2 with Goal displays

- standard/info/commons/info.lua
Add `Module:Info` on commons for it to not be missing when requiring it
N/A
> Add `Module:Info` on commons

- components/prize_pool/commons/prize_pool.lua
Allow to modify default for a wiki while still allowing users to change the value with args. Before it was like
```lua
-- Turn off automations
args.prizesummary = false
args.autousd = false
args.exchangeInfo = false
```
This meant you couldn't use the args in wikicode to change the values. Could have added like args handling in custom but this felt better.
`/dev`
```lua
-- Turn off automations
prizePool:changeConfigDefault('prizeSummary', false)
prizePool:changeConfigDefault('autoUSD', false)
prizePool:changeConfigDefault('exchangeInfo', false)
```
<https://liquipedia.net/counterstrike/index.php?title=Module%3APrizePool%2FCustom%2Fdev&type=revision&diff=2391352&oldid=2344059>
(Will submit as PR if/when this get's merged)
Live here for testing: …
> PPT: Add method to modify config defaults from custom

- components/opponent/commons/opponent_libraries.lua
When requiring a module only the first return value is returned, hence the OpponentDisplay library is currently never returned.
This PR changes the return value to be a table (with named keys) of the libraries, hence returning bot libraries.
This allows to require as follows:
```lua
local OpponentLibraries = require('Module:OpponentLibraries')
local Opponent = OpponentLibraries.Opponent
local OpponentDisplay = OpponentLibraries.OpponentDisplay
```
The bug was introduced via #2145
The module is not yet in use anywhere.
dev modules
> Fix OpponentLibraries module

- components/match2/wikis/brawlstars/match_legacy.lua
- components/match2/wikis/dota2/match_legacy.lua
- components/match2/wikis/leagueoflegends/match_legacy.lua
- components/match2/wikis/rainbowsix/match_legacy.lua
- components/match2/wikis/valorant/match_legacy.lua
Since inherited header was introduced in #1159, the complicated logic using Wiki Variables can be simplified. This was first done for OW in #1318
Apply the simplified logic to all wikis using the old logic.
Verified on R6 as sample
> Simplify match2 to match1 logic for `Header` field

- components/match2/commons/match_group_input.lua
Add fallback for missing match2players in reading mvp
Fixes preview "bug" where in section preview it would error due to the playerdata from TC/HDB not being present
"Bug" was introduced via #1862
"Bug" only shows on pages with bad data input or in preview
/dev
> Add fallback for missing match2players in reading mvp

- components/hidden_data_box/wikis/rocketleague/hidden_data_box_custom.lua
- components/infobox/wikis/rocketleague/infobox_league_custom.lua
- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/rocketleague/match_summary.lua
Adds a button to match summaries in order to make the head-to-head pages more quickly and easily accessible for upcoming and past matchups.
The button only appears for matchups in which both teams have pages, since they are more likely to have a history.
I was unsure whether this logic should be in the summary, or the input.
/dev module
> Add head-to-head to RL's match summary

- components/infobox/commons/infobox_league.lua
Change so commons Infobox League defines an empty extradata table. This is a step to unify is distinct patterns being used when it comes to LPDB extradata from commons. Other infoboxes using this pattern includes Infobox Team and Infobox Person.
The wikis are updated in #2163, but that's not a requirement for this PR, rather that PR changes the pattern to on the Custom side.
Tested by hjp
> Have infobox league define LPDB `extradata`

- components/infobox/commons/infobox_league.lua
stacked on #2162 
Store series2 in lpdb_tournament_extradata via commons
/dev
> Store series2 in lpdb_tournament_extradata

- standard/table.lua
sumneko-lua 3.6.0 was just released which apparently improved/fixed their lambda function annotations to be checked.
This PR corrects incorrect annotations, making sure parameters are optional for lambdas and adding missing return values.
Checked in VSCode
> Fix annotation issues on lambda functions

- components/infobox/wikis/ageofempires/infobox_league_custom.lua
- components/infobox/wikis/apexlegends/infobox_league_custom.lua
- components/infobox/wikis/arenaofvalor/infobox_league_custom.lua
- components/infobox/wikis/brawlhalla/infobox_league_custom.lua
- components/infobox/wikis/counterstrike/infobox_league_custom.lua
- components/infobox/wikis/crossfire/infobox_league_custom.lua
- components/infobox/wikis/dota2/infobox_league_custom.lua
- components/infobox/wikis/halo/infobox_league_custom.lua
- components/infobox/wikis/leagueoflegends/infobox_league_custom.lua
- components/infobox/wikis/naraka/infobox_league_custom.lua
- components/infobox/wikis/overwatch/infobox_league_custom.lua
- components/infobox/wikis/pokemon/infobox_league_custom.lua
- components/infobox/wikis/pubg/infobox_league_custom.lua
- components/infobox/wikis/pubgmobile/infobox_league_custom.lua
- components/infobox/wikis/rainbowsix/infobox_league_custom.lua
- components/infobox/wikis/rocketleague/infobox_league_custom.lua
- components/infobox/wikis/splatoon/infobox_league_custom.lua
- components/infobox/wikis/valorant/infobox_league_custom.lua
With the introduction of #2162 and #2174, there's now extradata field provided with information from commons. This PR changes the wiki custom build upon this table instead of creating a new one.
Sample testing (tested CS and dota2)
> Wiki InfoboxLeague customs should not overwrite extradata

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
- components/infobox/wikis/starcraft2/infobox_league_hidden.lua
depends on #2162
Prepare sc2 infobox league (+ hidden) for placement cleanup
- the stuff set into extradata is currently set into extradata via the prize poools when they add the top4
- featured is not applicable for hidden infobox league, so skipped there
Currently it has no real effect, but after the sc/sc2 placement cleanup it will be needed.
/dev
> Prepare sc2 infobox league (+ hidden) for placement cleanup

- components/match2/commons/match_group_input.lua
- standard/string_utils.lua
`StringUtils.explode(..., ..., X)` works the same way as `mw.text.split(..., ...)[X+1]`, ie unnecessary.
The following non-git modules needs updating:
Tested using /dev module
> Remove StringUtils.explode

- components/match2/wikis/counterstrike/match_group_input_custom.lua
The easiest way to check if a match should be included in live or upcoming matches, `dateexact` is currently used. In order to not build additional complexities for around postponed and cancelled matches and tournaments, setting `dateexact` to `false` would be an easy and simple solution, which is technically correct as well (as the match will no longer take place at said time).
> LPA-6895: Set dateexact to false for cancelled or postponed games

- components/infobox/commons/infobox_team.lua
Step in the solution of #1337 
#1337 allows us to unify the storage across the wikis in the short-term (see #2158), and making sure that that the version with text is available. Currently what's stored in `logo`:
* half the wikis don't store the text based logo at all, making it unavailable for consumers of LPDB, if there's a textless version
* The other half always store the text-version
The field `textlesslogo` should be seen as deprecated, and the purpose of it's introduction is standardized and enriched the `logo` field.
Once team templates have been switched away from `std`'s, `textlesslogo` can be removed all together.
Tested with /dev module
> Store `textlesslogo` from infobox team

- components/infobox/commons/infobox_map.lua
- components/infobox/wikis/starcraft2/infobox_map_custom.lua
- Allow wiki spec. categories in infobox map
- set wiki specific categories based on max number of players on the map for sc2
/dev
> Allow wiki spec. categories in infobox map

- components/infobox/wikis/halo/infobox_person_player_custom.lua
Added sypport for the PlayerTeamAuto Module on Halo's infobox.
Tested with a dev module on two player pages:
https://liquipedia.net/halo/Module:Infobox/Person/Player/Custom/Dev
https://liquipedia.net/halo/Kamado
https://liquipedia.net/halo/Penguin
Do note that playerintroduction was already broken before this
> Force PlayerTeamAuto on Halo in Player Infobox

- components/opponent/commons/opponent_display.lua
Add 'icon' as valid TeamStyle in OpponentDisplay
No need for any changes in the display as the display will add the icon and after that the name display based on the TeamStyle.
So since 'Icon' is not checked in the if cases no name display will get added.
/dev
> Add 'icon' as valid TeamStyle in OpponentDisplay

- components/results_table/commons/results_table.lua
stacked on #2120
relies a tiny bit on #2184 (only for the TypeUtil check if it gets enabled)
Add base display functions to base module for standardized Results table
together with additional sandboxes, that will be added via sep. PRs after #2120
for screenshots see #2120
> Add base display functions to base module for standardized Results table

- components/infobox/wikis/brawlstars/infobox_person_player_custom.lua
Move autoPlayerIntro from bottom content to after the infobox
/dev
before:
after:
> Move autoPlayerIntro from bottom content to after the infobox

- standard/table.lua
- standard/test/table_test.lua
Use pairs over ipairs in Table.includes
/dev module in combination with a few modules
\+ checking the code all (non dev/sanbox) modules that use it if there are cases where it depends on ipairs
> Use pairs over ipairs in Table.includes

- components/squad/wikis/ageofempires/squad_custom.lua
This enables the combination of SquadAuto and Squad already in use on R6.
Therefore data on rosters will be stored in LPDB SquadPlayer instead of datapoints, enabling the future use of `Module:NavboxGenerator`.
Tested by enabling the flag on some team pages and verifying the display works and data can be pulled correctly on player's pages.
> Add Squad/Custom with SquadAuto support for ageofempires

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
Automatically remove $ sign from prize pool inputs
/dev into live
> Remove $ sign from prize pool inputs

- components/results_table/commons/results_table_award.lua
Add Awards Table module (header and row display)
sandboxes together with #2120 and additional /Custom
> Add Awards Table module (header and row display)

- components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
Add `advantage` comment in matchsummary
On mobile the Abbr in the score display can not be hoovered and hence the user can not access that information.
This PR adds the information also to the matchSummary display. 
/dev
> Add `advantage` comment in matchsummary

- components/squad/wikis/arenaofvalor/squad_custom.lua
- components/squad/wikis/leagueoflegends/squad_custom.lua
- components/squad/wikis/mobilelegends/squad_custom.lua
- components/squad/wikis/overwatch/squad_custom.lua
- components/squad/wikis/wildrift/squad_custom.lua
`Transfer` & `SquadAuto` had a data structure change, where there can be more than one position per transfer. This is to allow position transfers (in addition to role transfer). As a result of this the old field `player.position` no longer exists, rather there is now `player.oldTeam.position`,  `player.newTeam.position` and `player.thisTeam.position`. 
This PR adjust the Squad Custom for the wiki using Position combined with SquadAuto.
LIVE
> Update field used for Position in `RunAuto` in Squads

- scripts/deploy.sh
Instead of using the latest git commit message on the automated weekly re-sync deploy, it will now use _(Git: Automated Weekly Re-Sync)_.
Tested on dev wiki using my fork of the repo. Both normal deploy and re-sync work as before, except with new message for re-sync.
> Update edit summary for weekly auto re-deploy

- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/rocketleague/match_summary.lua
Grand finals that have bracket resets are made up of two series, meaning 2 Octane and 2 Ballchasing links are needed.
Match summary supposedly once supported multiple Octane links, or at least they are written in multiple pages.
/dev module
The `links.octane` and `links.ballchasing` are now tables in LPDB, but nothing is affected by this as nothing uses them.
> Add support for multiple links to RL's match summary

- components/match2/wikis/valorant/match_group_input_custom.lua
Valorant's match2 is not storing DisplayNames for players in lpdb. The PR fixes this issue.
Dev module
> Store Player Displaynames on Valorant match2

- components/prize_pool/wikis/ageofempires/prize_pool_custom.lua
Current TeamCard overrides a placement's date with the default tournament enddate.
This change sets the wikivar to pass specific dates on to the TeamCard for each participant.
via /dev
> Set variable for specific enddates entered in PPT

- components/match2/wikis/callofduty/brkts_wiki_specific.lua
**Match2 for Call of Duty**
This was ported from Splatoon instead since there's different in that the old WIP one on COD uses EPOCH TIME but the Splatoon assuming newer has moved to DateExt so I'm trying with that if it's the better go-to vs EPOCH
LIVE
e.g. 
https://liquipedia.net/callofduty/Call_of_Duty_League/Season_4/Stage_1 (Matchlist)
https://liquipedia.net/callofduty/Fall_Invitational/2022/Knockout_Stage (Bracket)
> Create BrktsWikiSpecific for COD

- components/infobox/wikis/mobilelegends/infobox_hero_custom.lua
The editors wanted to listed the voice actors for heroes on their respective page through Hero Infoboxes (as it appears such info were provided in the game)
Right now the input is like the old venue/sponsors so 
```|parameter=X  <br> Y <br> Z```
I wanted to switch to be similar as the current venue input but I have no idea how. Hence why this revision is just a custom cells since it's the only method I know
Goal is like this if  based on the example pic
```|voice1=NO1 |voice1flag=jp```
```|voice2=NO2 |voice2flag=uk```
```|voice3=NO3 |voice3flag=id```
DEV - https://liquipedia.net/mobilelegends/User:Hesketh2/Test2
https://liquipedia.net/mobilelegends/Module:Infobox/Unit/Hero/dev
> Add input for Voice Actors in MLBB Hero Infobox

- components/infobox/wikis/pokemon/infobox_league_custom.lua
It wasnt there originally in LPDB Data, this is to allow new prize pool and results table to work properly with it, Specifically Individual events
DEV - https://liquipedia.net/pokemon/index.php?title=Module:Infobox/League/Custom/dev&action=edit
Page tested - https://liquipedia.net/pokemon/Pokemon_Championships/Regional/Baltimore/2023/TCG
> Stored modes in Pokemon Infobox League

- components/infobox/commons/infobox_team.lua
Adds an explanation about team earnings containing individual earnings.
via /dev
Checked that any custom implementations of Module:Earnings do not interfere (or the cell is also being overriden in a custom infobox)
> Add abbreviation explaining team earnings

- components/match2/wikis/rocketleague/match_legacy.lua
RocketLeague's match1 compatibility is not setting the `walkover` field according the the logic that RL-Match1 was using. See for instance https://liquipedia.net/rocketleague/index.php?title=Template:MatchMaps&action=edit#mw-ce-l158
This caused issues with using some commons functionality, most notably `played matches`.
test with /dev
> Set the match1 `walkover` field correctly

- components/match2/commons/match_group_input.lua
To be able to use a dev version of `Module:Brkts/WikiSpecific`, that modules has to imported properly.
This PR adjusts the import into `Module:MatchGroup/Input` accordingly.
via /dev, enabling the flag on various wikis using match2.
> Require Dev version of Brkts/WikiSpecific if enabled

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Adjust match.placement handling for even bestofs so that they are not considered won if one opponent reaches bestof/2
/dev
> Adjust match.placement handling for even bestofs

- components/match2/commons/starcraft_starcraft2/match_external_links_starcraft.lua
Adjust interview icon for sc/sc2 match2 external links
Advantages:
- use standard icon other wikis use also
- since it is black only it can be adjusted via css for darkmode and we do not need an additional icon
N/A
just icon file change
> Adjust interview icon for sc/sc2 match2 external links

- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/match_group_display_matchlist.lua
- components/match2/commons/match_summary_base.lua
Adjust 
Module:MatchGroup/Display/Bracket 
Module:MatchGroup/Display/Matchlist 
Module:MatchSummary/Base
to use **OpponentLibraries** on OpponentDisplay local calls
/Dev
all file changes in this PR
> Use OpponentLibraries in some match2 modules

- components/opponent/wikis/rocketleague/opponent_display_custom.lua
deepCopy base opponent module into custom instead of just holding the adjusted/added functions without the stuff from the base module
intoduced with #2247
https://discord.com/channels/93055209017729024/372075546231832576/1055811882683998229
dev into live since bug fix
> DeepCopy base opponent module into custom

- components/notability/wikis/ageofempires/notability_checker_config.lua
The previous implementation would always evaluate to true and half the calculated score therefore.
It was also based on by now unused values of the mode field.
This fixes it by using a valid condition and the correct field value, `team`.
Discovered in #2250.
Calculate scores with updated config to verify 1v1 results are now doubled compared to the old results.
> Fix broken condition when adjusting score

- components/prize_pool/wikis/ageofempires/prize_pool_custom.lua
Since on AoE no match2 is available right now, the prize pool errors when trying to use the import functionality.
It technically would work with group tables, but since it won't pick up brackets afterwards it still errors.
via /dev
> Disable PPT import for AoE

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_import.lua
- components/prize_pool/commons/prize_pool_legacy.lua
- components/prize_pool/commons/prize_pool_placement.lua
- components/prize_pool/commons/starcraft_starcraft2/prize_pool_legacy_starcraft.lua
- components/prize_pool/commons/starcraft_starcraft2/prize_pool_starcraft.lua
- components/prize_pool/wikis/ageofempires/prize_pool_custom.lua
Use `Module:OpponentLibraries` in various ppt modules
- `Module:PrizePool`
- `Module:PrizePool/Placement`
- `Module:PrizePool/Import`
- `Module:PrizePool/Legacy`
- `Module:PrizePool/Starcraft`
- `Module:PrizePool/Legacy/Starcraft`
- `Module:PrizePool/Custom` on aoe (the only such module (except sc/sc2) that set a different opponent library)
this has the advantage that in the future we do not need to add the custom opponent libs in the `Module:PrizePool/Custom`s on the wikis if there are such custom opponent libs
(e.g. ClashRoyale and trackmania are in the process of getting stuff set up and both need custom opp libs)
/dev (together with changes of PR 2218)
> Use `Module:OpponentLibraries` in various ppt modules

- components/squad/commons/squad_row.lua
Add option to disable storage for Squad Rows via
- manual input
- set wiki var
requested by trev: https://discord.com/channels/93055209017729024/874304000718172200/1058083187277971496
/dev of the module on commons + /dev of Squad/Custom on LOL with some requiredev adjusts so that the Squad/Row/dev would actually be called
> Add option to disable storage for Squad Rows

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_placement.lua
Set lastvsdata in lpdbentries
The lpdb field does not yet exist but once it does this will make it so that it gets filled up
/dev (together with the changes of PR 2218)
since the lpdb field does not exist yet checked via previews and logs of the lpdb data right before storage
> Store lpdb field lastvsdata in PPT

- components/prize_pool/commons/prize_pool_placement.lua
- components/prize_pool/commons/starcraft_starcraft2/prize_pool_starcraft.lua
Currently the commons module only supports `individualprizemoney` for solo opponents.
This PR adds via a small tweak support for any opponentType except team opponents (i.e. for solo, duo, trio, quad).
(for team the `individualprizemoney` is intended to be handled via teamCards)
Since a few more wikis that have duo opponents want to switch to the standardized prize pool imo it is good to add support for it via commons, especially as the change makes it imo even better to read and more logical^^
/dev (together with changes of PR 2218)
> Support individualprizemoney for all party opponents

- components/match2/wikis/halo/match_summary.lua
Wanted to add a Head2Head link in the Match Summary for every match as Halo Data Hive had to pause their product due to costs. It is set to always be on, as there is no other statistics site to provide this sort of information, and I believe should be easy to access from any match.
/dev in Userspace
[https://liquipedia.net/halo/User:OxWeaselDee/BracketTest#Results](https://liquipedia.net/halo/User:OxWeaselDee/BracketTest#Results)
> Halo: Add Head2Head link to Match Summary 

- components/infobox/wikis/starcraft/infobox_league_custom.lua
If `|female=` is set to true (readBool) then add
- indicator into lpdb_tournament_extradata
- according category
fwiw #2277 is needed for this to have any effect on the extradeata storage as currently the ppt overwrites it again
/dev
> Add `|female=` BW infobox league

- components/infobox/wikis/starcraft/infobox_league_custom.lua
- Kick Legacy Category --> usages have been adjusted
- minor adjust in lpdb storage: unset female instead of storing `false` so that extradata is kept smaller
/dev
> Update `|female=` handling on BW

- components/match2/wikis/clashroyale/brkts_wiki_specific.lua
Part of Match2 Implementation, largely based from Starcraft with large changes due to CR's niche game structure.
The game involves usage of both 1v1, 2v2 and Teams events
Alongside "Sets" (where a team match consists an array of 1v1 and 2v2 sets/subgroups) and the need of Card inputs (which is same manner as Characters in MOBA match2s)
/Dev and Test Pages (https://liquipedia.net/clashroyale/User:Hesketh2/Mockup)
> Add `BrktsWikiSpecific` for Clash Royale

- standard/flags_master_data.lua
NE Asia is a region used for Apex, the flag is supported from a previous template, but in the effort to update modules to use the Module:Flags, we require this flag to be added to the flagdata
> Added correct link for NE Asia region flag

- components/match2/wikis/mobilelegends/match_group_input_custom.lua
- components/match2/wikis/mobilelegends/match_summary.lua
**|caster1=|caster2=** which was ported from Rainbow Six's match2 
DEV - https://liquipedia.net/mobilelegends/User:Hesketh2/test
**This revision will include MatchSummary as well, so two files**
~~It doesnt seem to retrieved flag for caster with existing pages, I know **casterXflag** existed but it was for non-page casters, That's one thing I'm not able to find a fix~~
> Add input for Casters in MLBB Match2

- components/match2/commons/player_display.lua
Avoids showing `[[|]]` when no player is specified in `PlayerDisplay`
| Before:                                                                                                          | After:                                                                                                          |
|------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| ![Before](https://user-images.githubusercontent.com/42142350/209376984-bac81663-f4cf-491f-be42-00ffb2da1286.png) | ![After](https://user-images.githubusercontent.com/42142350/209377086-83a0e3d4-3598-461c-ac65-7f70ab581ce1.png) |
/dev module
> Avoid showing empty player syntax in PlayerDisplay

- components/match2/wikis/rainbowsix/brkts_wiki_specific.lua
Comparing a string with a timestamp not correct.
This PR fixes this logic issue so it's comparing timestamp to timestamp,
dev modules
Before:
After:
> Fix logic issue in R6's hasDetails determination

- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/match_group_display_matchlist.lua
- components/match2/commons/match_group_legacy.lua
- components/match2/commons/match_subobjects.lua
- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Most, but not all, uses of `Brkts/WikiSpecific` is imported with requireDev, but not all. This PR makes the remaining uses import with requireDev.
Tested with dev modules
> Have Imports of `Brkts/WikiSpec` use DevFlag if Enabled

- standard/namespace.lua
- standard/test/namespace_test.lua
Add 2 functions to module:Namespace
- `nameFromId` a function to retrieve NameSpace name from id
- `prefixFromId` a function to retrieve the NameSpace Prefix from id (usefull when building links)
/dev
> Add funcationity to get the `DisplayName` of a NameSpaceId

- components/squad/wikis/rocketleague/squad_custom.lua
Rocket League lists and stores previous Squads into LPDB. Earlier tables on the page contain full or partial information, which is stored. For entries that only have partial info, it's important that the entries are merged when more information comes further down on the page. This is currently not working for players had changed their `id` between the tables.
This PR sets objectname based on `link` instead of `id`. This allows merging of players with pages at least.
Tested with dev module. LPDB Entries now merge as expected
> RL Squads: Set objectname based on `link`

- components/notability/wikis/ageofempires/notability_checker_config.lua
With the bugfix from #2258, most notability scores increased (pre-fix, the score for every result was halfed instead of only team results).
After discussion with other editors, this adjust the thresholds used to determine notability accordingly.
N/A
> Update notability thresholds for AoE

- components/opponent/commons/opponent_display.lua
- standard/test/opponent_display_test.lua
Props `showFlag` and `showLink` are allowed values in the props, but are not passed on to `PlayerDisplay.InlineOpponent`.
via [Testsuite](https://liquipedia.net/commons/Module:OpponentDisplay/testcases)
> Match prop definition and usage for OpponentDisplay.InlineOpponent

- components/infobox/wikis/apexlegends/infobox_league_custom.lua
Tested on dev, defaults to pc (i.e. mixed) like the display function does
> Store platform into Apex's lpdb tournament 

- components/match2/commons/brkts_wiki_specific.lua
- components/match2/commons/match_group_display_helper.lua
As discussed yesterday in our module talk the idea behind this PR is to add functionality to remove several `Brkts/WikiSpecific` modules because the commons one already exists.
- Add commons Version of `Module:Brkts/WikiSpecific` that only "redirects" to `Module:Brkts/WikiSpecific/Base`
- Adjust `defaultMatchHasDetails` in `Module:MatchGroup/Display/Helper` to check for `match.timestamp ~= DateExt.epochZero` IF `match.timestamp` exists
The second point mirrors what most wikis already do without hurting the wikis that
- overwrite the `matchHasDetails` function or
- used the current default (as for them match.timestamp is not set)
/dev (via R6 & SC2 & RL)
> Adjust default `MatchHasDetails` behavior

- standard/array.lua
- standard/test/array_test.lua
This PR created a function that checks if an input is an array (ie table with all keys in ascending, consecutive order). Because the `#` only works on arrays, comparing the return value of that compared to the number of elements, is a clean and simple way to check (but not most performative, as the array is iterated twice).
Attached testcases
https://liquipedia.net/commons/Module_talk:Array/testcases
> Create isArray standard function

- standard/template_engine.lua
- standard/test/template_engine_test.lua
This PR aims to create a Template Engine for our Lua environment.
The syntax follows [{{mustache}}](https://mustache.github.io/mustache.5.html). Most functionality in {{mustache}} is supported.
What is **not** supported is:
* `{{{variable}}}` (use `{{&variable}}` instead for unescape functionality). _Code complexity for no new functionality gain._
* [Partials](http://mustache.github.io/mustache.5.html#Partials). _Not useful yet, would be easy implementation_
* Sections within section and inverted section within sections. _This requires proper tokenization instead of just string manipulation_
* Delimiter setting. _Unlikely to be implemented in the future_
Attached testcase
> Create a Template Engine

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_legacy.lua
- components/prize_pool/commons/prize_pool_placement.lua
- components/prize_pool/commons/starcraft_starcraft2/prize_pool_legacy_starcraft.lua
- components/prize_pool/test/prize_pool_test.lua
- components/prize_pool/wikis/counterstrike/prize_pool_custom.lua
- components/prize_pool/wikis/counterstrike/prize_pool_legacy_custom.lua
- components/prize_pool/wikis/mobilelegends/prize_pool_legacy_custom.lua
There was conflicting use of `USD` and `BASE_CURRENCY` across the PPT modules. This PR addressed that by renaming everything to `BASE_CURRENCY`.
Tested using `/dev` modules on commons, and with CS and ML wikis.
> Refactor `USD` to `BASE_CURRENCY` in PrizePool

- standard/mock/mock_lpdb.lua
Adding this functionality would allow tests to check and verify the exact data stored into LPDB. 
It is optional for a test to use it.
/dev module and added little thing to a dev testcase `LpdbMock.setUp(function(...) mw.logObject(Table.pack(...)) end)` 
```
table#1 {
"standingstable",
"standingsTable_0",
table#2 {
["extradata"] = table#3 {
},
["matches"] = table#4 {
},
["parent"] = "Module_talk:Standings/Storage/testcases",
["section"] = "",
["standingsindex"] = 0,
["title"] = "",
["tournament"] = "Test Tournament",
["type"] = "league",
},
["n"] = 3,
}
```
> Add data callback functionality to LPDB Mock

- components/opponent/wikis/trackmania/opponent_display_custom.lua
I want to make the migration to match2 for Trackmania wiki. OpponentDisplay has to be custom because we need 2v2 opponent, and we also needs score2 and score3, because TM Esports now have several games to be played in the official leagues of the game. This PR is a split of an initial PR that added every modules. I will add every modules with new PRs in the next days.
Lots of my changes are tested on [User:Sigeth/BracketsShenanigans](https://liquipedia.net/trackmania/User:Sigeth/BracketsShenanigans) and, for 2v2, on [User:Sigeth/....../Regional_1](https://liquipedia.net/trackmania/User:Sigeth/Trackmania_World_Tour/2023/Stage_1/Regionals/Europe/Regional_1).
> Add `OpponentDisplay/Custom` for trackmania

- standard/info/wikis/trackmania/info.lua
As for PrizePool/Custom (that will be a PR later on) uses these libraries, we specify it in the Info module. This PR should be merged just after #2262 (OpponentDisplay custom module).
as I tested OpponentDisplay/Custom, there should not be a problem
> Change `Info` module to use good Opponent and OpponentDisplay libraries

- components/prize_pool/wikis/trackmania/prize_pool_custom.lua
As we want to use the match2 PrizePool template, we need PrizePool/Custom. Everything seems to work now and stores the same values in LPDB and SMW Properties as the previous prize pool templates.
Changes have been tested by using two pages in my userspace.
* Old (previous prize pool templates)
* * [Page](https://liquipedia.net/trackmania/User:Sigeth/Trackmania_World_Tour/2023/Stage_1/Grand_League)
* * [SMW Properties](https://liquipedia.net/trackmania/Special:Browse/:User:Sigeth-2FTrackmania-5FWorld-5FTour-2F2023-2FStage-5F1-2FGrand-5FLeague)
* * [SMW Properties for a ranked team](https://liquipedia.net/trackmania/Special:Browse/:User:Sigeth-2FTrackmania-20World-20Tour-2F2023-2FStage-201-2FGrand-20League-23ranking-5Fsolary)
* * [LPDB …
> Add `PrizePool/Custom` for trackmania

- components/match2/wikis/counterstrike/match_summary.lua
- components/match2/wikis/dota2/match_summary.lua
- components/match2/wikis/leagueoflegends/match_summary.lua
- components/match2/wikis/rainbowsix/match_summary.lua
Removes an unneeded inline CSS, as it was added to the CSS class, set by MatchSummary class to the same element, a long time ago.
Dev module on R6
> Remove unneeded CSS inline

- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Remove extra datapoint storage in sc2 infobox team
- it is stored in lpdb_team_extradata
- all team pages have been purged
- all consumers have been updated
/dev
> Remove redundant lpdb_datapoint storage in SC2 team infobox

- standard/links/commons/links.lua
CS requests an addtional steam input (`|steam2=`)
Side Note: In the future should rewrite the Links.transform to make use of pairsByPrefix so we can have an arbitrary amount of each
N/A data
> Add support for steam2

- components/infobox/commons/infobox_widget_builder.lua
Any type of widget that requires its `Context` set to work (currently only `Customizable` Widget) will fail inside a `Builder` Widget, because it doesn't set the context to it's children.
Dev module
> Fix: Customizable inside Builder failing

- components/infobox/commons/infobox_team.lua
Have the built cell in Earnings be customizable. This allows a wiki to make use of its calculated values, whilst customizing parts.
Dev module
> Make the cell inside `earnings` customizable

- components/infobox/wikis/counterstrike/infobox_team_custom.lua
Resolves #2241.
CS doesn't wish the abbr to be displayed in the Team Infobox Earnings cell. This PR remove it.
Dev module with #2306 (required bug fix) and #2307 (allows the customization)
> Update the Earning's Cell Title on CS

- components/prize_pool/commons/prize_pool_import.lua
Fix qualLose (loser also qualfies) handling for non single elim brackets
In the PPT Import currently the qualLose of a non lower bracket match (in non single elim) gets ignored from the ppt import.
This PR fixes that issue (#2313).
/dev module and then preview test (with dev enabled) on 20 (random) pages that do not have qualLose (but use import) and 2 pages that have qualLose
Cynical also checked a few pages with preview tests
> Fix handling of double qualified in UB Finals(PPT Import)

- components/infobox/commons/infobox_person.lua
Expose player's additional teams in extradata.
Fix mistake in which `teamlinkX` was being used in one part of the code instead of `teamXlink`, `teamlinkX` is not used on any wiki.
/dev module
> Store player's additional teams in extradata

- components/prize_pool/commons/prize_pool.lua
The header row needs a background color according to the design. By adding a class to this specific row I can set it with css.
I tested it on my own wikidev environment to see if that class is being added, and that is the case:
> Add CSS Class to header row of PPT

- standard/tournaments_summary_table/wikis/starcraft2/tournaments_summary_table_custom.lua
Adjust sc2 conditions in tournaments summary table due to ppt not storing into tournament_extradata anymore (missed that when updating all consumers)
dev into live
> Update query conditions for SC's tournaments summary table

- components/infobox/wikis/counterstrike/infobox_company_custom.lua
Removed 1 field that is in use, `events`. Checked with Zaykor who was fine with it, since it's out of date on most and there are dynamic event lists in the content of the page. The input `|series=` has been added as an optional field.
Few fields have changed location. For instance `Location` is now next to `HQ` instead of on the top. `Industry` is renamed `Focus` is now directly after Parent/Sister/Subsisdiary instead of just before. `People` has been renamed `Key People`.
Before:
After:
"Live" Module (in preview)
> Create Custom Company Infobox for CS

- components/prize_pool/commons/prize_pool.lua
Uses this functionality instead
https://github.com/Liquipedia/Lua-Modules/blob/db0ae9f05a2c63d10d841276d7113ea188e81040/components/widget/widget_table_row.lua#L17
I didn't test it due to only doing this really quickly at 2am. I can test later if needed before merge.
> Use init statement in PPT header to add TableRow class instead

- components/infobox/commons/infobox_game.lua
As per discussion in discord yesterday, I have added support for social links at the bottom of Infobox/Game.
Tested here: - https://liquipedia.net/pubgmobile/User:Dark_meluca/GameTest
with /dev here : - https://liquipedia.net/commons/Module:Infobox/Game/dev
the /dev version differs slightly in that it uses 
"local Links = require('Module:Links')"
instead of 
"Lua.import('Module:Links', {requireDevIfEnabled = true}"
for testing purposes. However the commit pushed here uses Lua.import
> Added link support for Infobox/Game

- components/match2/wikis/trackmania/match_summary.lua
This PR is the last mandatory module to be added for match2 implementation on Trackmania wiki. MatchSummary is displaying BOs (like BO5 or BO7 for a match) and should display correctly any informations related to the match.
This module has been tested mainly on [User:Sigeth/BracketsShenanigans](https://liquipedia.net/trackmania/User:Sigeth/BracketsShenanigans) and on [User:Sigeth/......./Regional_1](https://liquipedia.net/trackmania/User:Sigeth/Trackmania_World_Tour/2023/Stage_1/Regionals/Europe/Regional_1)
> Add `MatchSummary` for trackmania

- components/match2/wikis/trackmania/match_group_input_custom.lua
Before this fix, nil values of opponent.template will cause to crash the module, notably when Opponent was not filled (empty field).
This change was tested on Brackets of [this page](https://liquipedia.net/trackmania/User:Sigeth/Trackmania_World_Tour/2023/Stage_1/Regionals/Europe/Regional_1)
> Fix MatchGroup Input Custom crashing if opponent.template does not exist

- components/prize_pool/test/prize_pool_test.lua
Apparently the test case was not adjusted with several PRs
- adding the additional header class
- currency handling reword in ppt (`currencyText`, `symbol` and `symbolFirst` got canned)
This PR adjusts the test case accordingly, so that tests pass again
"live"
> Fix ppt header test

- components/prize_pool/commons/prize_pool.lua
- components/widget/widget_table.lua
* Move row creation from Opponent to Placement. This allows for css such as nth-child, allowing for odd/even coloring.
* Bunch of code cleanup that could be done as a result of it.
* Manually set the column count instead of taking the row with most cells.
Dev module
> Clean up Prize Pool Rows

- components/prize_pool/commons/prize_pool.lua
- standard/array.lua
In #2340, there was a critical issue, where `return nil` within an `Array.map` was changed to just `return`. This caused the table.insert to critically fail, due to expectation of two parameters.
As a short term solution, I've added Annotation to `Array.map()`. This will in the IDE catch a this issue before it arises.
`return` 
`return nil`
Live
> Fix PrizePool Table Crash

- standard/links/commons/links.lua
stacked on #2334
Adjust `Links.transform` to use an iterator for the transform instead of a hardcoded table
Gives better support for keys that are incremented with index (e.g. `twitch`, `twitch2`, `twitch3`, ...)
Needed for using it in other places from Infoboxes (e.g. `Module:Streams`)
/dev
(Added additional reviewers since big chuncks of it are rath's suggestion already)
> Adjust Links.transform

- standard/table.lua
- standard/test/table_test.lua
Adjust `Table.mapArguments`
- add option to not use interleave stuff
- add annotations
intentional usecase is for adjusting PPT Import to:
- be able to have a importLimit per stage in addition to the overall importLimit
- be able to have a switch for a stages last match importing winner too (currently it only does so for the last stage, with the planned adjusts it could do so for earlier stages too if the according switch is set to true for that stage
see #2352
for both the interleave fillup would make this function not (easily) usable
/dev + test suite
> Adjust `Table.mapArguments`

- components/match2/wikis/trackmania/match_group_input_custom.lua
Match2 threw an error when `player.name` was nil.
This adds a default value of `''` to prevent a hard error.
In addition, it seems like the loop should be broken once no valid player can be found from match or the variables, to prevent listing empty players in LPDB data.
cc @Sigeth 
Bugfix, so live
> Fix match2 error when player.name is nil

- components/infobox/commons/infobox_team.lua
`coach` is already a valid input to the Cells, but not to LPDB. This PR allows for for `coach` to be valid for LPDB in addition to `coaches`.
> Add `coach` as valid input to lpdb in Team Infobox

- components/results_table/commons/results_table.lua
Missing information in the annotation that this call is inheriting from another.
Warnings went away
> Fix annotation in Results Table

- standard/flags_master_data.lua
The demonym for Trinidad and Tobago is current plural, leading to [this](https://liquipedia.net/overwatch/Avani).
> Fix plural demonym in `Flags/MasterData`

- components/infobox/wikis/rocketleague/infobox_league_custom.lua
Remove the Psyonix Logo from Infobox League for Psyonix sponsored and organized events. 
Based on request from RL Admins.
Before:
After:
Dev module
> Remove Psyonix logo from RL League Infobox

- components/results_table/commons/results_table_base.lua
Currently the ResultsTable also retrieves lpdb_placement data from placements that have no place set.
This PR changes that for the non awards queries.
live (module not really in use yet)
> Adjust placement condition in ResultsTable

- components/prize_pool/commons/prize_pool_placement.lua
Add `|count=` support in slots
`count` gives the size/width of the slot, i.e. the number of participants expec ted in the slot
requested by @iMarbot 
dev + preview pages (both pages using import and pages not using import)
> Add `|count=` support in slots

- components/match2/wikis/counterstrike/match_legacy.lua
Fix issue with missing TTs and match1 mapping from match2
`/dev` on CS wiki.
https://liquipedia.net/counterstrike/GDK/Season/8
> Fix CS match1 opponent names when missing TT

- components/prize_pool/wikis/counterstrike/prize_pool_custom.lua
Before moving to new PPT, the calculation was slightly different. If prize money was 0, then the weight was not divided by placement. This addresses that difference by bringing back the old way.
`/dev` module on CS wiki.
**Before dev changes**
**After dev changes**
> Fix CS' PPT weight calculations

- standard/table.lua
The current annotation says that the Keys of the return table must be the same as the Keys of the input table. While this is correct for `Table.mapValues()`, it is not correct for `Table.map`. This PR fixes it.
Ensured incorrect warnings are gone
> Fix return value in the Annotation of `Table.map`

- components/infobox/commons/infobox_league.lua
Make dates display customizable in infobox league
Warcraft will need it.
They display a countdown with date/startDate if a starttime is given:
```wiki
-->{{#if:{{{date|}}}|<div><div class="infobox-cell-2 infobox-description">Date:</div><div class="infobox-cell-2">{{#if:{{{starttime|}}}|{{countdown|date={{#time:M j, Y - H:i|{{#var:start_time}}{{#var:tournament_timezone}}}}{{abbr/UTC}}|finished={{#var:tournament_finished}}}}|{{{date}}}}}</div></div>}}{{#if:{{{sdate|}}}|<div><div class="infobox-cell-2 infobox-description">Start Date:</div><div class="infobox-cell-2">{{#if:{{{starttime|}}}|{{countdown|date={{#time:M j, Y - H:i|{{#var:start_time}}{{#var:tournament_timezone}}}}{{abbr/UTC}}|finished={{#ifexpr: {{#time:U|-4 hours}} < {{#time:U|{{#var:start_time}}{{#var:tournament_timezone}}}}|fals …
```
> Make dates display customizable in infobox league

- components/infobox/commons/infobox_league.lua
HtmlStrip the `format` field before inserting it into lpdb_tournament
Dev module
**Before:** 
**After:**
> Strip the `format` field of HTML in lpdb_tournament

- components/prize_pool/commons/prize_pool_legacy.lua
In case of `points=seed`, a category was added for missing links, which also happened when there was a slot without any indication that there is actually a missing link.
It would be possible to add `and input` to the condition to catch pages where there is input but no link can be parsed, e.g. there is only html that gets cleaned or something.
via /dev
> Remove aggressive category setting

- standard/links/wikis/warcraft/links_custom_data.lua
Warcraft has a wiki specific prefix for esl/eslgaming links, this PR adds the customData to reflect that
dev into live (new module)
> Add warcraft link overwrite data

- components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua
change TeamHistoryAuto to use the proper default parameters as used in the main template (https://liquipedia.net/leagueoflegends/Template:TeamHistoryAuto)
> Fix default history behaviour

- components/match2/wikis/counterstrike/match_legacy.lua
Previously literal opponents on CS were stored as TBD always. Now, if the team name doesn't contain HTML (i.e., `<sup></sup>` for placeholder names in brackets), it will use the literal name for match1 opponent names.
`/dev` module on CS wiki.
https://liquipedia.net/counterstrike/International_Gaming_League/2016/Summer/Qualifier#Group_A
And `TBD` still kept here: https://liquipedia.net/counterstrike/Special:LiquipediaDB/User:IMarbot/IEM#match
> Temporary literal opponent handling as team for match1

- standard/currency/currency_data.lua
Added support for Bhutanese ngultrum to currency/data module. 
A tournament on pubgmobile required it for prize pool.
Information on symbol taken from wikipedia.
> Add BTN to Currency Data

- components/squad/wikis/ageofempires/squad_custom.lua
- components/squad/wikis/apexlegends/squad_custom.lua
- components/squad/wikis/arenaofvalor/squad_custom.lua
- components/squad/wikis/counterstrike/squad_custom.lua
- components/squad/wikis/dota2/squad_custom.lua
- components/squad/wikis/leagueoflegends/squad_custom.lua
- components/squad/wikis/mobilelegends/squad_custom.lua
- components/squad/wikis/overwatch/squad_custom.lua
- components/squad/wikis/pubg/squad_custom.lua
- components/squad/wikis/rainbowsix/squad_custom.lua
- components/squad/wikis/rocketleague/squad_custom.lua
- components/squad/wikis/starcraft2/squad_custom.lua
- components/squad/wikis/trackmania/squad_custom.lua
- components/squad/wikis/valorant/squad_custom.lua
- components/squad/wikis/wildrift/squad_custom.lua
Resolves #2314
Eg. Incase a person joins both the active squad and as a streamer, add role suffix to the objectname.
Dev module on LoL
> Add `role` as part of the SquadPlayer objectname

- components/infobox/wikis/ageofempires/infobox_team_custom.lua
Automatically determine games for teams based on placements. Use latest placement date per game to determine inactivity.
Uses both team as well as player's placements.
via /dev on various team pages
> Automate game display for teams

- components/squad/commons/squad_row.lua
Use Opponent/OpponentDisplay to render the Player Id in Squad Tables, instead of the super deprecated `Module:Player`.
Added side bonus is that `flag` input is now automatically retrieved, if not provided, from the player's page.
Before:
After:
Dev module
> Use OpponentDisplay for rending squad tables

- components/squad/commons/squad_row.lua
- components/squad/wikis/leagueoflegends/squad_custom.lua
Resolves #2315
Create function to set extradata, and have LoL store `status` (TableType) into there.
dev module
> feat: add extradata storage for LoL squads

- components/infobox/wikis/warcraft/infobox_league_custom.lua
Add infobox league for warcraft
new module, not yet used on live
preview tests and lpdb &smw data comparisons
https://liquipedia.net/warcraft/Category:Pages_where_abbreviation_can_be_removed
https://liquipedia.net/warcraft/Category:Pages_with_abbreviation_but_no_series
https://liquipedia.net/warcraft/Category:Pages_with_missing_series_lis
https://liquipedia.net/warcraft/Category:Pages_with_series_and_abbreviation_lis_not_matching
> Add infobox league for warcraft

- components/squad/commons/squad_row.lua
The Coach and Sub logos put on a new line instead of the same line due to using `BlockOpponent` instead of `InlineOpponent`.
Introduced in #2412
**Block:**
**Inline:**
dev module
> Fix inline issue with Squad Table Display

- components/squad/commons/squad_row.lua
In #2411 the newTeamRole brackets were incorrectly removed. This PR re-adds them
Before:
After:
dev module
> Re-add missing bracket around newteamrole

- components/squad/commons/squad_row.lua
- components/squad/wikis/ageofempires/squad_custom.lua
- components/squad/wikis/apexlegends/squad_custom.lua
- components/squad/wikis/arenaofvalor/squad_custom.lua
- components/squad/wikis/counterstrike/squad_custom.lua
- components/squad/wikis/dota2/squad_custom.lua
- components/squad/wikis/leagueoflegends/squad_custom.lua
- components/squad/wikis/mobilelegends/squad_custom.lua
- components/squad/wikis/overwatch/squad_custom.lua
- components/squad/wikis/pubg/squad_custom.lua
- components/squad/wikis/rainbowsix/squad_custom.lua
- components/squad/wikis/rocketleague/squad_custom.lua
- components/squad/wikis/starcraft2/squad_custom.lua
- components/squad/wikis/trackmania/squad_custom.lua
- components/squad/wikis/valorant/squad_custom.lua
- components/squad/wikis/wildrift/squad_custom.lua
SquadRow constuctor expects `frame` and `role` inputs. Frame is enough unused, and `role` handling should be in the `:role(...)` method.
Dev module with RL
Before:
After:
> refactor: remove redundant parameters of the SquadRow Constructor

- components/match2/wikis/rocketleague/match_group_input_custom.lua
- standard/links/commons/links.lua
Followup to #2245, now that all `octane` params have been changed to `shift` instead.
Dev module
> Remove Octane

- components/match2/wikis/trackmania/match_group_input_custom.lua
- components/match2/wikis/trackmania/match_summary.lua
There are two changes in this PR :
* Map names no longer redirects to a link, because of how map system is in Trackmania, we can't make a page for every single one of them
* Green checks when a map score is added now appears automatically, comparing the two scores entered and applying the green check to the highest score. It also takes into an account if a map has no scores (you'll see in examples that I did not catch a result in Upper Bracket Finals, and it does not brake)
All of my changes have been tested on [this page](https://liquipedia.net/trackmania/User:Sigeth/RegionalsTest)
You can see the differences with the [page with current MatchSummary](https://liquipedia.net/trackmania/Trackmania_World_Tour/2023/Stage_1/Regionals/Middle-East_%26_Africa/Regional_1).
You will see these …
> Improvements for MatchSummary in Trackmania

- standard/links/commons/links.lua
Inputs `website` and `website2` are already mapped to `home`, which is the functional icon.
`lp-website` is not an icon
via /dev 
Wrong:
Fixed:
> Remove prefix website

- components/infobox/wikis/starcraft2/infobox_person_user_custom.lua
Move `Infobox/Person/User` to `Infobox/Person/User/Custom`
N/A
please move the according module on the sc2 wiki before merging, so that we do not duplicate it
also adjust the invoke in the according template on sc2 so it will not error^^
> Move `Infobox/Person/User` to `Infobox/Person/User/Custom`

- components/prize_pool/commons/prize_pool_legacy.lua
Allow lastvsXlink/lastvspageX in Legacy PPT
This is needed in case of solo prize pools and the lastvs having a link that differs from the displayname
dev
> Allow lastvsXlink/lastvspageX in Legacy PPT

- components/opponent/commons/starcraft_starcraft2/opponent_display_starcraft.lua
- components/opponent/commons/starcraft_starcraft2/opponent_starcraft.lua
depends on #2392 and #2394
Make use of #2392 and #2394 in the sc/sc2 opponent modules
(20 more git modules and a several non git modules to follow in the upcoming days/weeks)
dev together with #2392 and #2394
> Make use of #2392 and #2394 in the sc/sc2 opponent modules

- components/prize_pool/wikis/trackmania/prize_pool_custom.lua
With the current Trackmania World Tour, we need automated counter for the Global Points Ranking, on which the competition and World Cup are based on.
It begins with PrizePool storing in LPDB those World Tour points. This is what this PR is about
I've tested this change on [this page](https://liquipedia.net/trackmania/User:Sigeth/RegionalsTest).
You can see that LPDB has been changed [here](https://liquipedia.net/trackmania/Special:LiquipediaDB/User:Sigeth/RegionalsTest#datapoint)
> Add WT Points integration in prize pools

- components/infobox/commons/infobox_game.lua
Added support in the same fashion as "Developer", so that multiple publishers can be added if needed.
https://liquipedia.net/pubgmobile/PUBG_Mobile
Tested using dev version
> Support "Publisher" in Infobox/Game

- standard/links/commons/links.lua
Kick redundant `rules2`, `rulebook` and `rulebook2` in Links module
N/A
> Remove redundant `rules2`, `rulebook` and `rulebook2`

- components/infobox/wikis/warcraft/infobox_league_custom.lua
Adjust participants number handling in WC infobox league
- Warcraft wants to be able to enter stuff like `|player_number=8+`, i.e. a `'+'` suffix
- It is to be stored without the suffix
- It is to be displayed as `<small>more than </small> .. cleanedNumber`
dev
> Adjust participants number handling in WC infobox league

- components/faction/commons/faction.lua
Add Faction.readMultiFaction
Needed for reading input of multiple factions in the same string.
optionally with sep. otherwise going char by char
usecase will be person infoboxes on sc, sc2 (and at a later date warcraft)
example (used in testing the function on sc2):
```lua
Faction.readMultiFaction{input = 'ptz'} = {'p', 't', 'z'}
Faction.readMultiFaction{input = 'protoss'} = {'p'}
Faction.readMultiFaction{input = 'p'} = {'p'}
Faction.readMultiFaction{input = 'protoss,zerg', sep = ','} = {'p', 'z'}
Faction.readMultiFaction{input = 'pghjn'} —> intentional error
```
note that adding testcases on commons could not be evaluated on commons as the data is not available on commons
/dev
> Add Faction.readMultiFaction

- components/infobox/wikis/pubgmobile/infobox_team_custom.lua
Moved bottom content out of template call and into custom and fixed the display of those sections. 
Added an extra page variable to be set
https://liquipedia.net/pubgmobile/User:Dark_meluca/TeamTest
https://liquipedia.net/pubgmobile/Module:Infobox/Team/Custom/dev
current custom uses /dev versions of bottom content templates, so as not to disturb the current display of infoboxes
> pubgmobile: create infobox team custom

- components/infobox/wikis/pubgmobile/infobox_map_custom.lua
colon notation wasn't supposed to be there originally, updating to correct bug.
> pubgmobile: Fix incorrect function definition

- components/prize_pool/wikis/pubgmobile/prize_pool_custom.lua
both prizepoints and status are defined to be stored in lpdb placement extradata
Tested alongside teamcard/custom/dev here:
https://liquipedia.net/pubgmobile/User:Dark_meluca/PrizePoolTest
> pubgmobile: add wikivars for extradata

- components/infobox/wikis/warcraft/infobox_league_custom.lua
Fix timezone var in WC infobox league
- escape the `-` (i.e. use `%-` over `-`)
- match non greedy (i.e. use `-` over `*`)
dev into live
> Fix timezone var in WC infobox league

- components/prize_pool/commons/prize_pool_import.lua
Add more options to PPT Import, namely:
* (optional) `importLimit` per stage.
---
* (optional) `importWinners` per stage to override importing of non-eliminated opponents in a stage (by default only in the last stage the non-eliminated opponents are also imported. This change gives the option to do it in earlier stages or disable it entirely for a stage.
---
* (optional) `groupElimStatuses` per stage. Defaults to global `groupElimStatuses` then to `DEFAULT_ELIMINATION_STATUS`.
With above two images, can see that `seedup` is ignored as not present in stage's `groupElimStatuses`.
---
example usage for those changes: https://liquipedia.net/counterstrike/User:IMarbot/BLAST and https://liquipedia.net/counterstrike/User:IMarbot/temp
`/dev` testing on CS wiki.
> Add stage `importLimits`, `importWinners`, & `groupElimStatuses` to PPT Import

- components/opponent/commons/opponent_libraries.lua
Allows to use a /dev version of Module:Info, to be able to adjust the opponent libraries during development.
As an alternative, i could also add a OpponentDisplay/Custom shim on the wiki, and change the Info module directly. (Since i then can work in OpponentDisplay/Custom/dev)
Tested via dev:
Info/dev:
> Import `Module:Info` via Lua.import in OpponentLibraries

- components/match2/wikis/counterstrike/match_legacy.lua
`TBD` handling was broken by #2374 and/or #2377 . This addresses that issue.
Tested on `/dev`
> Fix TBD handling for CS match1

- components/infobox/wikis/ageofempires/infobox_team_custom.lua
Previously, the functionality used a single lpdb query to fetch games a team competed in as well as the date of these placements.
Since `order` only applies after a `groupby`, this worked for some, but not all teams, as sometimes old placements and therefore dates would be returned.
In addition, fetching of games is decoupled from any manual input, and it uses `args.name` to query placements before it defaults to pagename.
via /dev
> Fix inactivity fetching in AoE Infobox team

- components/prize_pool/wikis/ageofempires/prize_pool_custom.lua
With mergeSlots enabled, points aren't not in the placement, but in the opponent instead.
Points are also stored in variables to be retrieved by teamcards.
via /dev
> Fix storage of points with mergeSlots enabled

- components/prize_pool/commons/prize_pool_legacy.lua
Catch empty lastvs table to avoid storing tbd opponents in lastvsdata
reported by @DMeluca : https://discord.com/channels/93055209017729024/268719633366777856/1070327549609123891
/dev
> Catch empty lastvs table to avoid storing tbd opponents in lastvsdata

- components/infobox/wikis/pubgmobile/infobox_league_custom.lua
Removed function definitions that passed self as an argument unnecessarily.
Tested with /dev. Both display and lpdb storage were fine.
> pubgm league infobox: Changed function operator syntax

- components/infobox/wikis/pubgmobile/infobox_person_player_custom.lua
Removed the template call in the infobox template and pushed it to the custom module method.
/dev
> pubgmobile: Call bottom content method for player infobox

- components/infobox/commons/infobox_basic.lua
Now with `Module:Info` up on 50/52 wikis, we can add a fallback for the Infoboxes to get the `|wiki=` param from that, if not provided in the call. 
This allows us to move basic Template's for infoboxes to commons (eg. Template:Infobox league) with most wikis not having a need to have them once SMW storage has been removed.
Tested on WC3 (wiki that uses `|wiki=` and on Tetris (after removing `|wiki=` from their template). Both set the expected values (`tft` and `tetris` respectively).
> refactor: `|wiki=` fallbacks to info.wikiname in infobox

- standard/game.lua
* Fix annotation for the tbl input top most functions. It is optional and not required
* Fix typo in annotation `isValid`
* Simplify the `_createIcon` function so it only accepts `icon` as icon input, and not both `icon` and `logoData`
Annotation: In IDE
`_createIcon`: dev + https://liquipedia.net/commons/Module_talk:Game/testcases
> `Module:Game`: fix annotation and simplify

- components/team_card/team_card_storage.lua
The only place across the Wiki farm that sets `tournament_publisher_tier` wiki variable is https://liquipedia.net/commons/index.php?title=Template:TournamentVariables&action=edit#mw-ce-l23. This one also sets `tournament_publishertier`. The standard infobox league sets `tournament_publishertier`, so format should follow it.
dev module
> fix: incorrect wiki-var used in TC Storage for PublisherTier

- components/standings/commons/standings_storage.lua
- standard/mock/mock_lpdb.lua
LPDB field `config` was recently added to the StandingsTable.
As a first step in migrating away from the config values stored in extradata, store them into the new field.
Dev module
> Store standings config values

- standard/links/commons/links.lua
`|site=` is setup as a both an alias to `|home=` and it's own. This PR solve this by removing as it's own and only having it as an alias.
Live
> Correctly handle link `|site=`

- standard/test/game_test.lua
The plugin doesn't handle imports correctly when not directly assigned to a variable.
This PR fixes this by moving the import to its own variable.
Testcase:
https://liquipedia.net/commons/Module_talk:Game/testcases
IDE Before:
IDE After:
> refactor: fix incorrect IDE warnings in test for game

- components/infobox/commons/infobox_team.lua
- components/infobox/wikis/warcraft/infobox_team_custom.lua
Create Team Infobox for Warcraft. Also fixes issue where achievements were broken due to incorrect SMW query since a few weeks back (now uses LPDB).
Before:
After: 
Preview testing on WC. LPDB Testing (via dev) on other wiki to check the refactor.
> feat: Create infobox team for Warcraft

- components/team_card/team_card_storage.lua
Due to #2485, some issues arose where merging of TBD from PrizePool and TBD from TeamCard was leading to uncorrelated data being merged into a single object (i.e., placement (PPT) and qualifier (TC) fields). This addresses the issue by creating separate objects for the two different types of TBD.
Another potential issue caused by the change too: https://discord.com/channels/93055209017729024/874304000718172200/1070814796104093806
Before:
Tested using `/dev`.
After:
Now there are `ranking` TBD placements and `participant` TBD placements.
When the participant is no longer TBD, the TeamCard reverts to storing as `ranking`. Example:
> Fix TBD teamcard storage

- standard/links/commons/links.lua
https://github.com/Liquipedia/Lua-Modules/pull/2334/files#diff-3b3ed830e3f8f975bc4df4542d6a3610a3a6f786902ab7bfebb4efd3935c792cL268
The input was `|siegegg=`, whilst after the PR #2334 it become `|siege-gg=`. This PR changes it back to `|siegegg=`.
> Fix Siege.gg infobox links

- components/infobox/extensions/commons/infobox_extensions_prize_pool.lua
Allow local value and usd value to calculate the currencyRate if it can not be determined via exchange.
Background: Currently on Warcraft several pages error for the infobox prizepool due to not retrieving a currencyRate while they have both (local) prizepool value and prizepoolusd value set.
dev
> Adjust Infobox League prize pool extension

- components/prize_pool/wikis/warcraft/prize_pool_custom.lua
The commons component does not set lpdbData.players for non solo/team opponents, hence we have to copy it over to lpdbData.players in that case.
Since for other cases (non duo) the additional data is no issue we can just copy it for all kinds of opponents.
The already deprecated lpdb_tournament.players field is currently still needed for earnings calculations.
dev into live
> Fix WC PPT players data for duos

- components/infobox/wikis/warcraft/infobox_league_custom.lua
Allow manual `|finished=false` input in WC infobox league to allow them to set an even as not finished if no match data is present due to their old matches not storing into LPDB
dev into live
> Workaround: Allow manual `|finished=false` input in WC infobox league

- components/infobox/commons/infobox.lua
Change infobox's standard way of setting categories from adding it in the wikitext `[[Category:FooBar]]` to using the dedicated lua function.
Dev module, tested on R6 Infobox league, SC2 Infobox team and SC2 infobox player
> refactor: set categories with `add_category` instead of wikicode

- components/results_table/wikis/starcraft2/results_table_custom.lua
- kick legacy lastvs since PPTs store into the new field (purge run done)
- rename main function from `run` to `results` to match commons
- correctly use frame over args in awards table
Live, module not yet in use
> Adjust sc2 results table custom

- standard/game.lua
Catch cases in Game.toIdentifier where identifier is not a name or abbreviation
live, module not in use except for test pages
> Catch cases where identifier is not a name or abbreviation

- components/infobox/wikis/tetris/infobox_league_custom.lua
League Infobox for Tetris, while Tetris is mainly 1v1, **team_number=** still relevant due to some team events that will likely be covered in near future
LIVE - https://liquipedia.net/tetris/CTWC/2022
How do I edit the Infobox to instead of calling games from **Module:GameVersion** to called **Module:Info** instead with the Module:Game thingy?
I am going to assume its needed to be done anyway. So I will cut to the chase
> Add Infobox League for Tetris

- components/results_table/wikis/fortnite/results_table_custom.lua
Add fortnite results table custom
Please note:
- Although Fortnite is not yet on the new prize pool they use the (deprecated) base of what we used for the sc2 prize pools. Hence they store opponentData already correctly.
- They do not store lastvs data though (since it is a battle royale)
dev
> Add fortnite results table custom

- components/infobox/commons/infobox_league.lua
Introduced in #2525, where only the happy path was tested. Due to missing table, the field will never be shown.
Live
> Fix typo regarding `location` in League Infobox

- components/infobox/commons/infobox_widget_header.lua
If a wiki doesn't have an Infobox Template, rather using one from commons, the following happens today
With this change it will correctly work
dev module. Verified on Valorant that having a template on the wiki still has the expected behavior.
> Fix `[h]` link when template only exists on commons

- components/results_table/wikis/fortnite/results_table_custom.lua
lower case tier input since they still use tiertype values in tier
live, bug fix
> Fix: TierDisplay in Fortnite results table

- components/notability/commons/notability_checker.lua
The old condition failed when calculated weight was exactly on the MIN_THRESHOLD:
This removes some duplicate code and reorders the condition to work again.
It also changes the thresholds to be inclusive, so a weight of exactly NOTABILITY_THRESHOLD_NOTABLE is treated as notable (same for NOTABILITY_THRESHOLD_MIN)
via /dev
> Fix condition when deciding notability

- components/squad/commons/squad_row.lua
Currently, if a Squad entry is missing a date, the display get messed up on mobile.
With this change missing a date will instead look like
dev module
> Improve Squad Table display on mobile

- components/infobox/commons/infobox.lua
I want to remove the class wiki-bordercolor-light because I added the border color to the selector itself and it's overwriting with the wrong color for skin LakesideView. I added fallback colors for skin Bruinen.
https://liquipedia.net/commons/index.php?title=MediaWiki:Common.css/Infobox.css&action=edit#mw-ce-l18
https://liquipedia.net/commons/index.php?title=MediaWiki:Common.css/Infobox.css&action=edit#mw-ce-l33
https://liquipedia.net/commons/index.php?title=MediaWiki:Common.css/Infobox.css&action=edit#mw-ce-l34
Removing the class with devtools.
> Remove class from infobox

- components/results_table/wikis/starcraft2/results_table_custom.lua
Remove (additional) sectionHeader from sc2 resultstable
Decided to display it a bit different, hence not needed anymore
dev to live
> Remove (additional) sectionHeader from sc2 resultstable

- components/infobox/wikis/zula/infobox_person_player_custom.lua
Zula is a CS:GO type of game. 
Outside of Info Player the rest is a port of either CS or VAL
But the Infobox Player has Tetris base to include the role changes (moved to run function). However I've added the feature to have Team History and Player's current team **(|team=)** to be automated like how LoL and APEX has this feature
LIVE, Because this is the only player page on wiki : https://liquipedia.net/zula/Doxiu
> Add Infobox Player for Zula

- standard/info/wikis/smash/info.lua
Incorrect game names. Wii U should not link to the Ultimate tournament portal.
Matches existing usage.
> Update info.lua for smash

- components/earnings/wikis/warcraft/earnings.lua
For correct player prize calculations for warcraft, have them use `individualprizemoney`.
Live
> Have WC use `individualprizemoney` for Player Earnings

- components/match2/wikis/leagueoflegends/match_summary.lua
Moving the css class from children to parent reduced the Post-expand include size by about 3.5%. 
Tested on results section of https://liquipedia.net/leagueoflegends/Liga_Master/2022/Closing/Group_Stage
> Reduce include size

- components/infobox/wikis/trackmania/infobox_person_player_custom.lua
Set alias in trackmania infobox player so that trackmania.io links work as intended
dev into live
> Use `trackmania_id` for `trackmania.io` in Infobox player

- components/infobox/wikis/warcraft/infobox_team_custom.lua
Add additional extradata storage to warcraft infobox team
- indicator if it is a national team
- indicator if it is a "race team"
Needed to condition on in some queries so we can replace some old smw shit
dev
> Add additional extradata storage to warcraft infobox team

- components/faction/wikis/warcraft/faction_data.lua
Add Alias `night elf` in wc faction data
Sometimes it is written with, sometimes without space to account for that add the alias to be able to read both
live, just an alias
> Add Alias `night elf` in wc faction data

- standard/info/wikis/ageofempires/info.lua
All current modules expect variables/storage of games to be `Age of Empires I`, as specified in [Module:Games](https://liquipedia.net/ageofempires/Module:Games).
Therefore this should be also the name that's used here.
n/a
> Change name of aoe1 to include roman number

- components/infobox/commons/infobox_widget_cell.lua
Add support in the Widget Cell for multiple columns. This is primarily to make the descrption a smaller part as the implement here makes the description always use 1 column, and the content use the remaining columns
See Achievements here:
dev module
> Allow specifying column count for CellWidget

- components/earnings/wikis/trackmania/earnings.lua
Default earnings was dividing earnings by 5.
This now uses individualprizemoney to leave the division to teamcards.
Could be removed with #2476 ?
New module, so live
> TM: Use individualprizemoney for earnings calculation

- components/infobox/wikis/ageofempires/infobox_person_player_custom.lua
Groups the rating config based on game, and displays the game when showing ratings.
[Sandbox](https://liquipedia.net/ageofempires/User:SyntacticSalt/Sandbox/1)
> AoE: Restructure player ratings

- components/infobox/wikis/fighters/infobox_person_player_custom.lua
Years Active was missed in the transition from legacy infobox to module based infobox for Fighters.
Was put live
> Add Years Active to Fighters

- components/infobox/wikis/ageofempires/infobox_person_player_custom.lua
Fetches the games a person is active in from placement and broadcasts, merged together with manual input.
Determines inactivity for these games based on thresholds for latest placement/broadcast, or manual input.
new module, live, [Sandbox](https://liquipedia.net/ageofempires/User:SyntacticSalt/Sandbox/1)
> AoE: Automate game display for players

- components/infobox/wikis/smash/infobox_person_player_custom.lua
Based on feedback from Smash community.
Now looks like
Live
> Fix ordering of games in Smash

- standard/placement.lua
Requested by design: To cut back on the many class variants and colors, the draw class can be removed/replaced for 3rd place.
I tested the edited code on my local wiki.
> Remove special bg for `3rd-4th` placement in results

- components/infobox/wikis/wildrift/infobox_person_player_custom.lua
originally **|role=Content Creator** dont displayed on WR Infobox player because the infobox didnt use Module:Role and instead set roles inside the infobox module
The PR is to add that, per this request
on LIVE briefly before bot rolls this back
> Add Content Creator Role for WR Player Infobox

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
Fix a rare bug with awards in sc2 infobox player counting as a result if they are not an achievement.
Spotted so far on 1 page
This PR escapes that via an early return in case of a non achieve award
dev into live
> Fix a bug with awards in sc2 infobox player

- components/infobox/wikis/ageofempires/infobox_person_player_custom.lua
Without resolved ID, querying would fail for lowercased IDs.
Removing the pagename as that doesn't work in userspace and ID is mandatory anyways.
Added optional query for pagenames with underscores instead of spaces.
Also changed the array merge to do one after another (otherwise, games might be added multiple times)
/dev
> AoE: Infobox player bugfixes

- standard/league_icon.lua
Add option to link to LIS template on the wikis in LIS generators
After merge the forms need adjusting by undoing:
- https://liquipedia.net/commons/index.php?title=Form%3ALeagueIconSmall&type=revision&diff=475604&oldid=475603
- https://liquipedia.net/commons/index.php?title=Form%3AHistoricalLeagueIconSmall&type=revision&diff=475620&oldid=475611
requested by @Hesketh2 
https://discord.com/channels/93055209017729024/874304000718172200/1071746318411772007
dev
> Add option to link to LIS template on the wikis in LIS generators

- components/opponent/wikis/pubg/opponent_display_custom.lua
- standard/info/wikis/pubg/info.lua
While this one does get used on Prize Pool, main goal is to allow results for tournaments under 2v2 prize pool worked and not return error through Module:ResultsTable/Custom (Results Table)
The module is a clean port of #2251 from Clash Royale with no edits on it yet
LIVE
> Support Duos on PUBG (PC)

- components/match2/commons/starcraft_starcraft2/player_ext_starcraft.lua
Use `Faction.defaultFaction` instead of `'u'`
dev to live
> Use `Faction.defaultFaction` instead of `'u'`

- components/infobox/commons/infobox_team.lua
Automate the showing of `|image=` and `|darkimage=` from Team Template in Infobox Team when applicable. This is already being done for the LPDB storage, but now also for display.
Dev module on RL.
> Automate Infobox Team's image showing when applicable

- components/prize_pool/wikis/overwatch/prize_pool_custom.lua
To allow for teams to appear in [Template:Tournaments list](https://liquipedia.net/overwatch/Qualifier_Tournaments/2023).
[Here](https://liquipedia.net/overwatch/Special:LiquipediaDB/User:Moonshot/sandbox2#placement).
> Add `qualified` to Overwatch PPT

- components/prize_pool/wikis/pubg/prize_pool_custom.lua
This is the port of the #2138 (/Custom PPT from PUBG Mobile) (includes any subsequent changes that is done after this, because I paste from the pubgm wiki just today)
since {{TeamPrizePool}} hasnt been used in past events before this, I converted it on past events
https://liquipedia.net/pubg/PUBG_Global_Championship/2022#Prize_Pool
> Add PPT for PUBG (PC Wiki)

- components/match2/commons/match_group_coordinates.lua
Fix `MatchGroupCoordinates.computeRawCounts` for double qual
This is mainly used by the PPT import
fixes import at https://liquipedia.net/counterstrike/BLAST/Major/2023/Paris/Europe/Qualifier/Open/1
dev
> Fix `MatchGroupCoordinates.computeRawCounts` for double qual

- components/match2/wikis/counterstrike/match_external_links.lua
Old URLs are now 404, they moved them all to this new URL.
Just data. Also, live on wiki.
> CS Match2: Fix 5E Arena link to new URL

- standard/info/wikis/simracing/info.lua
Add all missing games based on https://liquipedia.net/simracing/index.php?title=Template:Infobox_league&action=edit&oldid=29649 plus including any missing games (due to I've stopped editing simracing in 2020 or something, a dozen was missing from that revision)
> Add all missing games in the Simracing Info

- standard/links/commons/links.lua
Fixes the prefix used for variant player for aoezone links
dev
> Fix player prefix for aoezone links

- components/squad/wikis/dota2/squad_custom.lua
Change the primary key to use link instead of id
dev
> Squad's dota2: Use link for objectname

- standard/info/wikis/splatoon/info.lua
Missing Games for Splatoon Info, which basically just two games. The original **splatoon** default entry actually works as the entry for the first game
in wikis the **game=** input only existed as **splatoon** / **2** / **3**
> Add missing games for Splatoon Info

- standard/links/commons/links.lua
Missing link entries for lolchess and cntft
/dev
cntft (last)
lolchess (last)
> Add cntft and lolchess to Module:Links

- standard/info/wikis/fighters/info.lua
Title.  Total of 123 Games including the default Fighters entry 
This include at least every entry in the old infobox league plus many new addition being a game with **Template:Game/** that doesnt had in the list and some of the newer games.
The file name inconsistency is due to 
1. The Logo.png or such is files that already existed, I had no plans to moved file names yet
2. all/dark/lightmodes are newly uploaded
At this time of PR around 1.5 dozen of logos not yet uploaded
^^^ This is done.
> Add all missing games in Fighters Info

- components/infobox/wikis/fighters/infobox_league_custom.lua
Missing wiki-variable during the migration.
Live
> Add another wiki-variable for Fighters' league

- standard/info/wikis/counterstrike/info.lua
Was incorrect data input for `csgo`.
Just data.
> Fix data error in CS Info

- components/infobox/wikis/heroes/infobox_league_custom.lua
Adds a non-breaking space between flag and country name for server input to achieve the same display as for location.
/dev
> Add space between flag and country name

- components/infobox/wikis/ageofempires/infobox_person_player_custom.lua
In case of name clashes, IDs don't match page names, so querying by ID does not work. This fixes the problem by using the pagename if in mainspace.
/dev
> Fix query to use pagename if in mainspace

- standard/info/wikis/smash/info.lua
String expected for index, not number
It's live. Numbers break existing implementations expecting strings.
> Change Smash 64 to string key instead of number

- components/infobox/wikis/smash/infobox_person_player_custom.lua
String expected for index, not number
It's live. GAME_ORDER is used to iterate through indices, which are expected to be strings.
> Update Infobox Player to match #2643

- components/infobox/commons/infobox_league.lua
Allow cancelled tournament (via Template:Cancelled Tournament) to be set both before and after Infobox instead of just after
dev
> Allow cancelled tournament to be set before Infobox

- components/hidden_data_box/wikis/ageofempires/hidden_data_box_custom.lua
- components/infobox/wikis/ageofempires/infobox_league_custom.lua
Stores map info entered in Infobox league as stringified JSON instead of CSV.
Allows fetch of structured information, including link and image overrides, in consumer modules (HDB, Maplist, Map occurences, Matches)
via /dev
Consumers of LPDB field maps have been updated to try to parse JSON and default to old CSV if parsing fails.
> Store map info as Json in Infobox league

- components/broadcaster_card/commons/broadcaster_card.lua
Catch empty names
Currently it still displays brackets if the name is empty
reported by krola
https://discord.com/channels/93055209017729024/268719633366777856/1080173339802353704
introduced via #2646
dev
> Catch empty names in BroadcasterCard

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_import.lua
- components/prize_pool/commons/prize_pool_placement.lua
- components/prize_pool/commons/prize_pool_placement_base.lua
Prepare PrizePool/Placement for standardized Awards Prize Pools with a refactor
-> split functions shareable between both normal and awards prize pool placements into a base module that gets used to init the placment class that then gets extended in `Module:PrizePool/Placement`
dev
1. Prepare PrizePool/Placement (split into base and specifics for non awards)
2. Prepare PrizePool (split into base and specifics for non awards)
- https://liquipedia.net/commons/Module:PrizePool/refactor (replaces the current one)
- https://liquipedia.net/commons/Module:PrizePool/Base (as base)
- to avoid merge conflicts and rebases open PR after merge of this one
3. Build PrizePool/Awards and PrizePool/Award/Placement (sep. PRs)
- https://liquipedia.net/commons/Module:PrizePool/Award
- …
> [1/?] Prepare PrizePool/Placement for standardized Awards Prize Pools

- components/infobox/wikis/heroes/infobox_league_custom.lua
Adds support for team count via request by Rennalla in the Discord chat. Having confirmed with Rennalla, there are no individual events that need accounting for
Currently live on this [page](https://liquipedia.net/heroes/META_Madness/7). LPBD saving was also enabled and saving correctly.
> Adding team count support in Heroes League infobox

- components/notability/wikis/pubgmobile/notability_checker_config.lua
Requested by the pubgm admin (Thangcoi) to make the monthly events value being 0, previously the value matches standard general/indiv value (which I believe its an unintended value)
> Change the Monthly Tier Value in PUBGM Notability Checker to 0

- components/infobox/commons/infobox_league.lua
- components/infobox/wikis/brawlstars/infobox_league_custom.lua
Add organizer specific icons in BS infobox league
- make organizers customizable in commons infobox league
- adjust the /Custom to adjust organizers display as wanted
requested by m4d0o3e
dev
> Add organizer specific icons in BS infobox league

- components/infobox/wikis/brawlstars/infobox_league_custom.lua
Add a nil check in BS infobox league for organizers.
From #2475
dev into live since bug fix
> Add a nil check in BS infobox league for organizers

- components/infobox/wikis/tft/infobox_league_custom.lua
I want to start adding some standardized templates to the tft wiki, I have started with the infobox league because it seemed the least complicated one
I have tested the changes on https://liquipedia.net/tft/Allie_Coin_Pro-Am/2021 and I have verified that the achievements do not disappear on the players page, for this I used the https://liquipedia.net/tft/Module:Infobox/League/Custom/dev and https://liquipedia.net/tft/Template:Infobox_league/dev
> Create Infobox League for Teamfight Tactics

- components/match2/wikis/rocketleague/match_summary.lua
Introduced in #2408:
Keys don't match when a input was previously shifted manually, but now uses `requireIndex=false`
Hotfix, live
> Fix missing `requireIndex=false`

- components/infobox/wikis/counterstrike/infobox_person_player_custom.lua
Players get tagged as `Player` but that leaves coaches and talent in weird limbo. Can't easily query just coaches cos they get stored as `Staff` and talent don't get anything. This addresses that issue.
`/dev` on cs wiki.
> Refine `getPersonType()` for Coaches and Talent

- components/infobox/wikis/smash/infobox_person_player_custom.lua
Add localid to extradata to aid querying of players with foreign tags
Tested in dev
> Add localid to Player extradata in smash

- components/match2/wikis/counterstrike/match_legacy.lua
When there is a literal opponent and they're a BYE, catch that and store the match as `resulttype` to be `l`. Needed for certain modules that depend on displaying results differently for non-standard results.
Live on CS wiki.
> Catch BYE matches as `resulttype = l` for match1

- components/notability/commons/notability_checker.lua
Add a nil check in notability checker
needed due to misc now being -1 across the board and some wikis not wanting misc/-1 to count
the nil check takes place after the array.find and hence if a wiki has data set for -1 it will still work there while it catches the case where a wiki has not set config weight data for -1
live, bug fix, only nil check
> Add a nil check in notability checker

- components/team_card/team_card_storage.lua
* Refactor objectname in TC to work the same way as in PPT (removed unused specific custom function, instead have it updatable by the normal function)
* Have it available for use by TC Customs (needed by AOE)
Dev
> Expose ObjectName to TeamCard Storage Customs

- components/prize_pool/wikis/simracing/prize_pool_custom.lua
Adding standardized prizepool to simracing wiki, as seen on page: https://liquipedia.net/simracing/ESL_R1/2023/Spring/Round_2 Works correctly both visually and when writing data (as seen on https://liquipedia.net/simracing/Special:LiquipediaDB/ESL_R1/2023/Spring/Round_2)
The wiki is currently still using SMW for prize pools so in an effort to standardise the wiki I've started with the prizepools.
Initially tested in userspace, later tested for data on page: https://liquipedia.net/simracing/ESL_R1/2023/Spring/Round_2 - Works correctly as data is written to LPDB and there are no visual issues showing up.
> Create simracing PPT Custom

- standard/flags_master_data.lua
According to the [Prespa Agreement](https://en.wikipedia.org/wiki/Prespa_Agreement) the official demonym for North Macedonia is Macedonian, not North Macedonian.
> Changing "North Macedonian" to "Macedonian"

- components/match2/wikis/counterstrike/match_legacy.lua
Fix storage of placeholder names which often container winner or loser as string.
`/dev` followed by live on wiki due to important to fix matchticker bug.
> Add catch for winner or loser in match1 TBD filter

- components/prize_pool/wikis/fifa/prize_pool_custom.lua
new Standard Prize Pool for FIFA Wiki, this is based on the merged prize pool from Tetris
and add calls to use **Opponent/Custom** ( related to #2625 ) to Sync teams in addition to the already existing SyncPlayers by default
For old prize pool with template start/end those have been moved over to used the Commons PrizePool/Legacy/Custom already, currently I have no plans to make a local Legacy Custom because it doesnt seem to need a local one and works all good
LIVE - https://liquipedia.net/fifa/FIFA_23/Global_Series/North_Asia/2
This page includes utilizing a /dev Match2 for Import, and also the syncteam stuff (this is why I wanted, if possible to have match2 merged like soon as possible)
> Add Prize Pool for FIFA

- standard/tier/commons/tier_utils.lua
Allow shortnames as input in `Tier.toNumber`
Needed on some wikis when they use `Tier.toNumber`
/dev
> Allow shortnames as input in `Tier.toNumber`

- standard/info/wikis/simracing/info.lua
- Start Year being 2019 cause transfers before that to not worked until sdate is set in TimelineSquadAuto
- 2019 doesnt feel fitting anyway, since most of games in the list came out before so I've switched the startdate to 1998 which is few years before the oldest game in the list (GP3 - 2000)
> Adjust Start Year in Simracing Info

- standard/tier/wikis/rocketleague/tier_data.lua
Remove misc as tiertype for RL
forgot to remove it when i set up the data module
N/A
> Remove misc as tiertype for RL

- standard/string_utils.lua
Refactor StringUtils.trim to use mw.text.trim. Also add `&nbsp` to the charset.
[Testcases](https://liquipedia.net/commons/Module_talk:StringUtils/testcases)
> Improve StringUtils.trim

- components/prize_pool/commons/prize_pool_import.lua
Refine sort order in the lastVs retrieval for group stages in PPT Import.
Currently it only checks by date but if match data sets (for whatever reason) the same date for matches this could cause the wrong match being used.
This PR refines the sort order so that the likelihood of the wrong match getting chosen gets reduced.
dev
> Refine sort order

- components/match2/wikis/mobilelegends/match_group_input_custom.lua
> Bo2 have a bug when the 1st game result inputted the system acknowledge that the Match is done.
i suspect that because the system use formula of n/2 where n is Bo(n). this will make the match end when the first game result inputed.
https://discord.com/channels/93055209017729024/1084072695253176330/1084072695253176330
dev
> Fix bug for ML matches with even Bestof

- standard/tier/commons/tier_utils.lua
The current implementation would error with "trying to index a function value".
via /dev
> Tier: Call memoized functions before indexing

- components/infobox/wikis/tft/infobox_person_player_custom.lua
Added two roles to TFT infobox player:
1. Organizer: People who organize TFT Tournament
2. Content Creators: People who are important in TFT that make interview videos, tutorial videos and etc.
Additionally made category values singular to not have double `s` at the end when the category is set
only data change
> Adjust role data in tft infobox player

- components/match2/wikis/halo/match_group_input_custom.lua
- components/match2/wikis/mobilelegends/match_group_input_custom.lua
- components/match2/wikis/rainbowsix/match_group_input_custom.lua
- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/trackmania/match_group_input_custom.lua
With the updated broadcaster card #2646, broadcaster pages are stored with underscores not spaces.
This adjusts the query to match the change.
/dev, then live to fix
> Query broadcaster pages with underscores not spaces

- components/infobox/wikis/tetris/infobox_person_player_custom.lua
3 Main issue happens with Tetris Player Infobox
- In the Portal Players module, every player gets counted under Staff & Talent accidentally
- Role inside the infobox, even if matched Module:Role/Data it did not get linkede (but was made to be linked to a category from the data module)
- |role2= while being stored, never gets to displayed
- make isPlayer stored and properly
/Dev - https://liquipedia.net/tetris/Marq_Maier (isPlayer true and has category as player because no role is added in the page, intended) & https://liquipedia.net/tetris/Marq_Maier (Roles being blue-linked, isPlayer counted as False as intended)
> Fix Role issue for Tetris

- standard/info/wikis/counterstrike/info.lua
Adjust cs module:Info to have the same formatting as all other wikis (remove the wrong alias that nil-ed one of the wanted values)
live
> Fix CS Info Module

- components/infobox/wikis/fighters/infobox_league_custom.lua
Rounding of prize pools in the infobox is affecting calculated payout values in the prize pool table. The summation of all prize values in the prize pool table no longer matches the actual value of the prize pool due to this.
Code is largely copied from the sc2 infobox. Retained implicit prizepool code. Removed redundant handling of prizepool vs prizepoolusd with no localcurrency specified.
Tested in dev
> Prevent rounding of prize pools in Infobox League for fighters

- components/prize_pool/commons/prize_pool_legacy.lua
Fix default opponent type for awards legacy conversion
dev into live
> Fix default opponent type for awards legacy conversion

- standard/info/wikis/arenafps/info.lua
changed xon to xo for Xonotic.
Results for players show "?" for the Xonotic game.
> Adjust a game key in arenafps module info

- components/results_table/commons/results_table.lua
Game icons were put into a `<th>` resulting in weird styles and bugged header.
/dev
> Use td instead of th for game icons

- standard/tier/commons/tier_utils.lua
- standard/tier/wikis/starcraft2/tier_custom.lua
- standard/tier/wikis/warcraft/tier_custom.lua
- escape `false` in tier library in link option parsing
- escape default tierType when parsing from query
dev
> Add some escapes in tier library

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Add entry restrictions for teams/players to infobox and LPDB.
---
`|restrictions=female`
---
`|restrictions=female,academy`
---
`/dev` on CS wiki.
> Add restrictions to CS League infobox

- standard/info/wikis/overwatch/info.lua
Incorrect game name is causing TeamCard errors like [these](https://liquipedia.net/overwatch/ZOTAC_Cup/2023/Asia/11#Top_16_Participants).
Previously worked when I [changed it manually](https://liquipedia.net/overwatch/index.php?title=Module:Info&oldid=731961) (didn't realize it needed a PR)
> Fix game name in overwatch `info.lua`

- standard/currency/currency_data.lua
Just looks silly to use the current rendering. Better to be like on 1st place row. Can move to unicode `⃀` when it is finally added to most OS default fonts.
Seems to work fine on dev module.
> Update KGS symbol to use HTML underline

- components/standings/commons/standings_storage.lua
* Move player check before team check. This allows for both player and team parameters for players (support for team of player). 
* Made the `|` in the participant regex of player optional. Adds support for `[[Foo]]` in addition to `[[Foo|Foo]]`
* Add fallbacks on link and name
These changes together allows support for Smash, Brawlhalla and Fighters GroupTableSlots.
Dev module on Smash (new), Overwatch (Team Based) and ArenaFPS (Solo Based)
> Improve solo handling in super legacy (template) standings

- components/infobox/wikis/fighters/infobox_league_custom.lua
Parse circuit input to resolve link, abbreviation, and icon from the circuit page.
If no series icon exists, save circuit icon in lpdb
Remove "Tier" suffix from circuit tier
Tested in dev on https://liquipedia.net/fighters/Canada_Cup/2019/SFV
> Implement circuit handling in Infobox League for Fighters

- components/infobox/commons/infobox_league.lua
- components/infobox/extensions/commons/infobox_extensions_prize_pool.lua
Want to enable automatic USD conversion for CS wiki, however, also don't like the current 0 precision rounding that's baked in. This allows for that to be modified by args input and by wiki customs. Will follow up with a CS PR to change it there. Also, probably can use this as a cleaner solution for #2699.
`/dev` on commons and CS. 
Not enabled: 
Enabled and set to 2:
Also tested on R6 (works fine) and Fighters (no effect due to custom overrides).
> Make USD prizepool rounding customizable

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Kill custom `CustomLeague:_createPrizepool()` to enable auto USD from commons. Also, enable the use of #2758 to set display precision to 2dp.
dev as part of #2758
> CS Infobox: Enable auto USD conversion with precision 2

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
depends on #2758
- make usage of `Module:Infobox/Extensions/PrizePool` instead of lots of custom stuff
- change display to `≥` before the prize pool instead of `+` behind each value
dev
> Adjust sc2 infobox league prize pool handling

- standard/flags_master_data.lua
Noticed a few wikis uses "arab states" as a language entry when recording different language streams:
https://liquipedia.net/commons/Special:GlobalWhatLinksHere?wpPageTitle=Template%3AFlagNoLink%2Farab_states&wpNamespace=-1337420&wpFormIdentifier=gwlh-form
No data in the MasterData module throws an "Unknown Flag" error, so have added the data structure.
Using a local version of Flags/MasterData
https://liquipedia.net/apexlegends/User:Dark_meluca/Test/FlagUnknown
> Add arab speaking language flag data

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Restore generation of `prizepoollocal` var which regressed in #2759.
dev disabled
dev enabled
> Restore `prizepoollocal` var in CS infobox

- components/prize_pool/commons/prize_pool_award.lua
Append award name to team award object names too
requested by Okidokie98
https://discord.com/channels/93055209017729024/268719633366777856/1087878626856402995
dev
> Append award name to team award object names too

- components/notability/commons/notability_checker.lua
Gsub returns two values, the substituted string, and number of occurances. 
In a `{}`, it will insert both values into the table.
This caused an extra unintended loop to be executed. In certain scenarios, this could attribute placements to where it shouldn't been. (Eg. on Rocket League, a player name with 2 spaces would match against the participant `2` who had a 5th place in a C-Tier tournament, awarding them an extra 35 points.
Live
> Fix condition in Notability Checker

- components/match2/wikis/overwatch/match_summary.lua
Updating to 2023 OWL logo and better Contenders icon
[first match here](https://liquipedia.net/overwatch/User:Moonshot/sandbox2#Results)
> Update Overwatch League/Contenders icons

- components/external_media_links/external_media_link.lua
Currently some unexplained call is being made to `Module:Page` to make an external link of a text title (not even a link). So it causes it to double up like a `[https://google.com test link]` expected result.
Tested with overwriting module on CS wiki. will delete when merged
> Fix double `trans_title` in ExternalMediaLink

- components/prize_pool/wikis/counterstrike/prize_pool_custom.lua
- components/prize_pool/wikis/counterstrike/prize_pool_legacy_custom.lua
Custom group score result names were being lost due to removal of var `custom result name` definition when moved to github version of PPT.
`/dev` on CS wiki.
https://liquipedia.net/counterstrike/index.php?title=Module:TeamCard/Custom&diff=2493866&oldid=2320290
Ideally maybe we can move this to `lastvsdata` instead like `lastvsdata.groupscorename` for example? So, that way it won't need to be re-defined in TeamCard extradata. Just an idea.
> Fix CS PPT `resultName` not being stored

- components/squad/wikis/starcraft/squad_custom.lua
Custom Squad display for Brood Wars.
Supports two types of Inputs. Manual tables and tables via TLPB. This is because the wiki uses a mix.
Live
> Custom Squad for BW

- components/results_table/commons/results_table.lua
- components/results_table/commons/results_table_award.lua
depends on #2800
Adjust prize money display in results and awards tables to use forced round precision
dev
> Results table format money adjust

- components/results_table/commons/results_table_award.lua
Currently the awards table flips the order of flag and player name and right aligns them, which is done when displaying last result in the results table. However its not needed in the awards table, so have reverted to standard display.
Tested alongside #2812 using /dev
> Awards Table: Undo Flip for non team opponents

- components/infobox/wikis/counterstrike/infobox_person_player_custom.lua
Creating region data module started adding regions to player infoboxes. This was unintended as we only wanted regions for tournament LPDB data (at least for now). Killed the region cell by overwriting it as blank as a quick fix.
If there is a better solution, please let me know or directly change it. Thanks.
dev to live
> Remove region from CS player infobox

- standard/info/wikis/apexlegends/info.lua
- standard/info/wikis/brawlstars/info.lua
- standard/info/wikis/callofduty/info.lua
- standard/info/wikis/crossfire/info.lua
- standard/info/wikis/dota2/info.lua
- standard/info/wikis/fifa/info.lua
- standard/info/wikis/freefire/info.lua
- standard/info/wikis/heroes/info.lua
- standard/info/wikis/leagueoflegends/info.lua
- standard/info/wikis/pubg/info.lua
- standard/info/wikis/pubgmobile/info.lua
- standard/info/wikis/rainbowsix/info.lua
- standard/info/wikis/rocketleague/info.lua
- standard/info/wikis/splitgate/info.lua
- standard/info/wikis/tft/info.lua
Add defaultRoundPrecision data to info modules for wikis that want to use `0` instead of the global default of `2`
N/A, just data
spreadsheet: https://docs.google.com/spreadsheets/d/1jRN10vwuVo2S28o4YOls1U9CzWCd49QA09_GhmydZSc/edit#gid=0
> Add defaultRoundPrecision data to info modules

- components/prize_pool/commons/prize_pool_base.lua
- components/team_card/team_card_storage.lua
Remove usage of legacy wiki variables, now that all(*) wikis have stanardized league infobox
\* not smash
Tested with dev
> Remove legacy wiki variables

- components/match2/wikis/counterstrike/match_summary.lua
Currently can only add part 1 and part 2 links of a vod for a match or a game. This is aimed at adding support for unlimited number of extra parts (for example, 4 parts).
`/dev` on CS wiki. Still works with just 2 parts and no commas too.
A better solution would to be support multiple VoDs per game2 and match2 in LPDB and commons match modules. But that's out of my scope right now for this "quick" fix. If someone has a good way of doing it, please feel free to suggest or open an issue about it.
> Add CSV input to vod2 for links for 3+ vod parts

- components/hidden_data_box/wikis/counterstrike/hidden_data_box_custom.lua
Moved wikicode logic from the Template into the Module for Counterstrike's HDB.
https://liquipedia.net/counterstrike/index.php?title=Template:HiddenDataBox&action=edit
> CS HDB: Move logic from Template to Module

- components/infobox/wikis/fifa/infobox_league_custom.lua
Due to one of events that was missed out being covered on wiki https://liquipedia.net/fifa/FIFA_Interactive_World_Cup/2004 has a platform that isnt in the infobox right now. That being the original XBOX (2001)
> Add 1 missing platform in FIFA Infobox League

- components/squad/wikis/smash/squad_custom.lua
Add status to extradata, similar to commons version
Tested live, impacts lpdb only.
> Add status to Squad extradata for smash

- components/infobox/commons/infobox_widget_links.lua
- standard/links/commons/links.lua
Add support for niconico in infobox links
Infobox icon already exists:
https://liquipedia.net/commons/Infobox_Icons#Niconico
dev
> Add niconico to Links

- components/infobox/wikis/fighters/infobox_league_custom.lua
Links are retrieved via Module:Game/Module:Info(link)
Suggested change to connect existing Game title pages better into the wiki infrastructure by linking them via Infobox league.
Test via local dev module. Tested for cases: page exists; page doesn't exist; no game input; nonsense game input.
> Add Link to Game cell if there's an existing page

- components/infobox/wikis/ageofempires/infobox_series_custom.lua
AoE series don't currently have the game put in and therefore don't work with the default tier display function.
In addition, series tier links do not make sense on AoE, as they'd link to tournament lists, not series lists.
bugfix, live
> AoE: Do not link tiers in infobox series

- standard/date_ext.lua
- standard/test/date_ext_test.lua
- move date functions from TournamentUtil to DateExt
- convert comments to annotations
dev
> Move date functions from TournamentUtil to DateExt

- components/infobox/wikis/apexlegends/infobox_league_custom.lua
Currently, apex queried extradata for this information, however it makes sense to standardise it in publishertier field with the introduction of the standardised results tables and other modules.
with /dev
https://liquipedia.net/apexlegends/Dark_meluca/Test/InfoboxLeague
> Apex: Standardise highlight conditions into publishertier field

- components/prize_pool/wikis/apexlegends/prize_pool_custom.lua
To be pushed after #2841 to standardise storage into prizepools
Also tested with /dev
https://liquipedia.net/apexlegends/Dark_meluca/Test/InfoboxLeague
> Apex: Update publishertier storage in prizepool

- components/squad/commons/squad_row.lua
Resolves #2854
If the real name is set through `:id` instead of `:name`, the LPDB data isn't being stored at the moment. 
This PR fixes this issue
Dev module
> Add realname storage with `:id` in addition to `:name`

- components/results_table/commons/results_table.lua
Make Results column in results tables unsortable as per martins suggestion.
Sorting there makes little sense
dev
> Make Results column in results tables unsortable

- components/results_table/commons/results_table.lua
- components/results_table/commons/results_table_award.lua
since we centered the prize display (as per vote on discord) this makes way less sense since it doesn't fix the right align anymore
dev
> Remove force rounding in results and awards tables

- components/results_table/commons/results_table.lua
- components/results_table/commons/results_table_base.lua
- by now all wikis should use the new ppts and got purged, so the lastvsdata field should be filled (except for smash-like wikis which do not use this anyways), hence kick `processLegacyVsData`
- adjust group abbr display, add left padding to align it with team icons as per martins suggestion
dev
> Adjust group abbr display

- standard/currency/currency.lua
- standard/test/currency_test.lua
Adjust display in `formatMoney` for zero and non numeric values to dash with the option to disable it
dev + test suite
> Adjust display in `formatMoney` for zero and non numeric values to dash

- standard/table.lua
- standard/test/table_test.lua
Add alias support for `Table.iter.pairsByPrefix`
dev + testcase
> Add alias support for `Table.iter.pairsByPrefix`

- components/results_table/commons/results_table_base.lua
Avoid indexing nil in results table
live, hotfix
> Avoid indexing nil

- standard/currency/currency.lua
- standard/test/currency_test.lua
Catch '0' (string) case for dash if zero in formatMoney.
And add testcase for it
testsuite
> Catch '0' (string) case for dash if zero in formatMoney

- standard/tournaments_summary_table/commons/tournaments_summary_table.lua
Issue reported here: https://discord.com/channels/93055209017729024/268719633366777856/1096449675428646943
When using `Liquipedia:Tournaments` with `<tournaments />`, omitting the enddate for one-day tournaments will improve the display.
via /dev on heroes
Now: 
Before:
> Omit enddate for 1-day tournaments

- components/match2/commons/match.lua
Resolves #2882
Adjust objectname in `lpdb_match2player` to fix a bug where the players are attached in wrong order if 10+ players in an opponent.
While attaching it seems to sort by objectname, hence adjusting the objectname to be sortable correctly seems to fix the lpdb bug.
dev
> Fix attach order bug for players in lpdb match2

- standard/league_icon.lua
Add missing `tostring` in LeagueIcon if icon == iconDark
introduced in #2871
done by rath on live
> Add missing `tostring`

- components/infobox/wikis/overwatch/infobox_team_custom.lua
Changes the handling of which leagues team compete in to fall more in line with League of Legends. 
Currently OWL teams have a parameter called ``|owl=franchise name`` that is saved as a boolean in LPDB. Instead, this is changing that parameter to ``|league=league name`` and allowing that to be saved in LPDB as ``competes_in``
dev module tested live
> Changing OW handling of leagues on team pages

- components/prize_pool/commons/prize_pool_base.lua
In case a qualified-to page did not exist, there is no pagename and therefore the gsub errored.
Example: https://liquipedia.net/ageofempires/Civilization_War/1/Qualifier
via /dev to live
> PPT: Fallback to link

- components/external_media_links/external_media_list.lua
The new Module:ExternalMediaLink stores the displayname for authors, but it wasn't displayed when fetching them.
via /dev:
Previously:
> ExternalMediaList: Use displayname for authors

- standard/template_engine.lua
Solves 3 issues:
* Follow standard when variable is missing (empty string instead of variable name)
* If a table on the way doesn't exist (eg `{{foo.bar.lorum}}` and `bar` doesn't exist in `foo`, then it currently gives an exception, now it will just empty string it as intended)
* If the value is a stringable object that's not a string (yet), eg a `mw.html` object, currently it will throw an exception, now it will tostring the obj first (and work). 
Testcases
> TemplateEngine: Improve non-happy path

- components/opponent/commons/opponent.lua
Use custom player in Opponent when available, rather than the commons base
/dev
> Use custom player in Opponent

- standard/operator.lua
- standard/test/operator_test.lua
Allows for code simplifications (less boilerplate) when it comes to functional style functions such as `map` and `reduce`.
Given the following table
```lua
local foo = {
{ a = 3, b = 'abc'},
{ a = 5, b = 'cedf'},
{ a = 4, b = 'sfd'},
}
```
To sort it (in place) by `a`
```lua
-- Current
Array.sortInPlaceBy(foo, function(struct) return struct.a end)
-- With this PR
Array.sortInPlaceBy(foo, Operator.property('a'))
```
To fetch items
```lua
-- Current
Array.map(foo, function(struct) return struct.b end)
-- With this PR
Array.map(foo, Operator.property('b'))
```
To sum all elements in an array
```lua
-- Current
Array.reduce(arr, function(a, b) return a + b end)
-- With this PR
Array.reduce(arr, Operator.add)
```
[Tests](https://liquipedia.net/commons/Module_talk:Operator/testcases)
> Create Operator standard lib

- components/match2/wikis/leagueoflegends/big_match.lua
Rename the input arg to lol's match2 from `key` to `matchid`.
dev
> League BM: Rename input arg from `key` to `matchid`

- components/match2/wikis/leagueoflegends/big_match.lua
- components/match2/wikis/leagueoflegends/big_match_template.lua
Fix two issues with big match:
* Empty opponent would cause errors due to incorrect team template
* In-optimal display for Empty Opponents
Dev
> League BM: Fix issues around Empty Opponents

- components/match2/wikis/leagueoflegends/big_match.lua
- components/match2/wikis/leagueoflegends/brkts_wiki_specific.lua
- components/match2/wikis/leagueoflegends/match_summary.lua
Extract logic for Match Page link from MatchSummary to BigMatch.
All matches that should get a Match Page link will now also have the popup available.
Having a no-date will also count as after May 1st (still requires S-Tier).
dev
> League BM: Tweak logic for popup and match showing

- components/match2/wikis/leagueoflegends/big_match.lua
Format the minutes output to always have 2 characters (`0X` or `XX`).
dev
> League BM: Format minutes

- components/match2/wikis/leagueoflegends/big_match.lua
For Epoch = 0 dates (ie missing), do not display the date (as it will show 1970)
dev
> League BM: Only display dates for proper dates

- components/squad/commons/squad_row.lua
Add `passed away` as special team in squads
Note the according template exists on commons (with overwrite for a link on cs)
N/A, only adding a special team exception
> Add `passed away` as special team in squads

- components/prize_pool/commons/prize_pool_import.lua
Currently ppt import pushes the matchdate/groupenddate to the prize pool even if it is epoch zero.
This causes ppt to not fetch the fallback dates (edate of the tournament) and instead uses the (from import returned) epoch 0 date.
This PR adjusts the import to remove epoch 0 dates.
dev
> Remove epoch zero dates during ppt import

- components/standings/commons/standings_storage.lua
Fallback `currentstatus` to `definitestatus` in standings storage.
Some consumers need the `currentstatus` set to work properly (e.g. prizepool import).
Logically it also makes sense that if definite status is known and current status is unset to assume that current status = definite status.
dev
> Fallback `currentstatus` to `definitestatus` in standings storage

- standard/currency/currency.lua
Disable dashIfZero in calling `.formatMoney` from `.display`
Reasoning:
dashIfZero is already evalutated at lines 52-54, so in line 91 it needs to be disabled to not get wrong dashes instead of zeros
dev
> Disable dashIfZero in calling `.formatMoney` from `.display`

- components/infobox/wikis/callofduty/infobox_person_player_custom.lua
- components/infobox/wikis/crossfire/infobox_person_player_custom.lua
- components/infobox/wikis/fortnite/infobox_person_player_custom.lua
- components/infobox/wikis/freefire/infobox_person_player_custom.lua
- components/infobox/wikis/halo/infobox_person_player_custom.lua
- components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua
- components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua
- components/infobox/wikis/naraka/infobox_person_player_custom.lua
- components/infobox/wikis/pokemon/infobox_person_player_custom.lua
- components/infobox/wikis/pubgmobile/infobox_person_player_custom.lua
- components/infobox/wikis/rainbowsix/infobox_person_player_custom.lua
- components/infobox/wikis/splatoon/infobox_person_player_custom.lua
- components/infobox/wikis/valorant/infobox_person_player_custom.lua
- components/infobox/wikis/wildrift/infobox_person_player_custom.lua
- components/infobox/wikis/zula/infobox_person_player_custom.lua
Use `returnEmptyIfNoResults` param in THA where applicable.
With that simplify the usage.
After this PR is merged THA can be adjusted to use this param by default and after that can open another PR to kick the param everywhere again but leave the simplifications in play.
- case1: wikis calling THA inside the module and checking against empty ones and merging them with the manual ones
- /dev on cod wiki + preview tests on several player pages, some which have THA results and some which do not.
- case2: wikis calling THA inside the module inside the history args
- /dev on R6 wiki + preview tests on several player pages, some which have THA results and some which do not.
- note that here we have a tiny (imo desireable) change: if an empty THA is returned now the history section vanishes as …
> Use `returnEmptyIfNoResults` param in THA where applicable

- components/match2/wikis/leagueoflegends/big_match.lua
Fix three issues, 
* API returning bad player data 
* Init the reduce with `0` so that sum function will always return a number (previous would return nil if there were no player)
* If the champion property of a table was nil, then the table was picked as the string name of the champion.
Live
> Various fixes for League BM

- components/infobox/wikis/callofduty/infobox_person_player_custom.lua
- components/infobox/wikis/crossfire/infobox_person_player_custom.lua
- components/infobox/wikis/fortnite/infobox_person_player_custom.lua
- components/infobox/wikis/freefire/infobox_person_player_custom.lua
- components/infobox/wikis/halo/infobox_person_player_custom.lua
- components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua
- components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua
- components/infobox/wikis/naraka/infobox_person_player_custom.lua
- components/infobox/wikis/pokemon/infobox_person_player_custom.lua
- components/infobox/wikis/pubgmobile/infobox_person_player_custom.lua
- components/infobox/wikis/rainbowsix/infobox_person_player_custom.lua
- components/infobox/wikis/splatoon/infobox_person_player_custom.lua
- components/infobox/wikis/valorant/infobox_person_player_custom.lua
- components/infobox/wikis/wildrift/infobox_person_player_custom.lua
- components/infobox/wikis/zula/infobox_person_player_custom.lua
Remove `returnEmptyIfNoResults` params in THA calls due to them now being redundant.
(Were only needed to move the stuff over to this functionality to not break existing usage.)
dev on 3 wikis (representitive)
> Remove `returnEmptyIfNoResults` params in THA calls

- components/broadcast_talent_table/commons/broadcast_talent_table.lua
Catch nil in `BroadcastTalentTable`.
In non main space `BroadcastTalentTable` errors if no broadcaster is specified. This change catches the nil that is causing an error in `mw.ext.TeamLiquidIntegration.resolve_redirect`
live since easy bug fix
> Catch nil in `BroadcastTalentTable`

- standard/links/commons/links.lua
The site changed something and now it needs suffix to work 🫠
I didn't but it's just adding a suffix, surely it's fine :D
> Fix Esportal tournament links

- components/prize_pool/commons/prize_pool_import.lua
Cache lastVs data for groups during ppt import to speed up ppt import for big groups significantly
dev
initial tests on https://liquipedia.net/valorant/The_Goose_House/2023/Beacon/Split_1
--> disable `allGroupsUseWdl` to get the runtimes in question
--> it is importing data from a 63 team swiss group
Before: runtime error (i.e. >3s)
With this change: <0.4s
Memory usage goes from ~4.5 MB to 5.4MB
after that tested 20 pages across several wikis if it breaks something
> Cache lastVs data for groups during ppt import

- components/match2/wikis/leagueoflegends/match_summary.lua
Add a temporary highlight to the match page link
Live
> Add temporary highlighting to matchpage link

- components/match2/wikis/leagueoflegends/big_match.lua
- components/match2/wikis/leagueoflegends/big_match_template.lua
- components/match2/wikis/leagueoflegends/match_group_input_custom.lua
Requirement that picks should be sorted on Role. This forces the picks to be gathered from player section isntead of vetos.
Also clean up the code.
Dev module in preview
> LOL Big Match: Sort picks based on role

- components/infobox/commons/infobox_widget_links.lua
- standard/links/commons/links.lua
Add support for Tonamel links
Infobox icon already exists:
https://liquipedia.net/commons/Infobox_Icons#Tonamel
Tested in dev
> Add Tonamel to links

- components/broadcast_talent_table/commons/broadcast_talent_table.lua
Old commons module previously used full name by default. Restores that while allowing wikis to override to still use tickername if they wish (e.g., SC2).
`/dev`
If there is a desire for tickername to remain default by more than just SC2, then maybe we can change it. Feel free to comment your opinions.
> Switch from tickername to name in Broadcasts Table by default

- components/match2/wikis/leagueoflegends/big_match.lua
Updated the availability for BigMatch to extend to B tiered tournaments, as well as from 1st of May, 2021 onwards.
> Add B Tier to BigMatch and change startdate to 2021 May

- standard/info/wikis/fighters/info.lua
Add [Idol Showdown](https://twitter.com/IdolShowdown)
Tested on User Page
> Add `Idol Showdown` to the Fighters

- standard/table.lua
Fixed in LuaLS version [3.6.0](https://github.com/LuaLS/lua-language-server/blob/master/changelog.md#360)
Verified in IDE that it's actually fixed, which it is
> Remove outdated comment

- components/squad/wikis/apexlegends/squad_custom.lua
- components/squad/wikis/arenaofvalor/squad_custom.lua
- components/squad/wikis/counterstrike/squad_custom.lua
- components/squad/wikis/dota2/squad_custom.lua
- components/squad/wikis/halo/squad_custom.lua
- components/squad/wikis/leagueoflegends/squad_custom.lua
- components/squad/wikis/mobilelegends/squad_custom.lua
- components/squad/wikis/overwatch/squad_custom.lua
- components/squad/wikis/rainbowsix/squad_custom.lua
- components/squad/wikis/rocketleague/squad_custom.lua
- components/squad/wikis/smash/squad_custom.lua
- components/squad/wikis/starcraft/squad_custom.lua
- components/squad/wikis/starcraft2/squad_custom.lua
- components/squad/wikis/valorant/squad_custom.lua
- components/squad/wikis/warcraft/squad_custom.lua
- components/squad/wikis/wildrift/squad_custom.lua
Add SquadType as part of the Objectname, to ensure entries of different types are not merged.
Dev on Rocket League
> Add SquadType to SquadPlayer ObjectNames

- components/results_table/wikis/starcraft2/results_table_custom.lua
stacked on #2942
Default sc2 resultstable to use indiv prize money
N/A
> Default sc2 resultstable to use indiv prize money

- components/results_table/commons/results_table.lua
- components/results_table/commons/results_table_base.lua
- components/results_table/wikis/starcraft2/results_table_custom.lua
List full prizemoney by default instead of individual prize money, with the option to use individual prize money.
Dev
Before:
After:
> Use `prizemoney` in results tables as default

- components/squad/commons/squad_row.lua
This parameter is unused and wasn't supposed to been added, it was part of development but scrapped. Causes the real option param to be ignored.
Live
> Remove param that wasn't supposed to been added

- components/infobox/commons/infobox_team.lua
Store `active` and `disbanded` status in the new LPDB `status` field for teams. This allows Portal:Team and similar to actually function properly.
dev
> Store team status in LPDB

- components/notability/wikis/brawlstars/notability_checker_config.lua
As requested in discord, brawlstars would like weekly tournaments to count towards notability points
With /dev
https://liquipedia.net/brawlstars/User:Dark_meluca/NotabilityTest
> Brawlstars: Include Weekly as Notable

- components/tournaments_listing/commons/tournaments_listing_card_list.lua
- components/tournaments_listing/wikis/starcraft2/tournaments_listing_card_list_custom.lua
- Adjust sc2 custom to be able to call by year from template
- adjust default limit for query from 20 to 5000
live
> Fetch more tournaments by default; sc2 can use callByYear

- components/tournaments_listing/commons/tournaments_listing_card_list.lua
Add missing `Opponent.fromLpdbStruct` map for qualified data
dev
> Add missing `Opponent.fromLpdbStruct` map for qualified data

- standard/array.lua
- standard/test/array_test.lua
Adjust `Array.extractValues` and `Array.extractKeys` to allow sorting via provided iterators
with /dev, using Array/testcases
> Adjust `Array.extractValues` and `Array.extractKeys` to allow sorting via provided iterators

- components/tournaments_listing/commons/tournaments_listing_conditions.lua
Multiple wikis store `series2` into extradata (in case a tournament is part of multiple series).
This allows the `series` condition to take that into account
dev
> Add support for series2 in TournamentsList

- standard/tournaments_summary_table/commons/tournaments_summary_table.lua
Automatically switch to desc ordering for recent type in tournamentsSummary table
dev
> Automatically switch to desc ordering for recent

- components/infobox/commons/infobox_widget_links.lua
- standard/links/commons/links.lua
Add support for Smashboards links
Infobox icon already exists:
https://liquipedia.net/commons/Infobox_Icons#Smashboards
Tested in dev
> Add Smashboards to links

- standard/info/wikis/arenaofvalor/info.lua
The merged Asian Games version of Arena of Valor/Honor of Kings (which consider a separate game) was never added to the module before.
> Add new game to Arena of Valor Info module

- components/match2/commons/match_group_input.lua
Currently only 20 (LPDB default limit) big-matches will be pulled from LPDB for a bracket, as such gives unexpected results for brackets/matchlists with more than 20.
Dev into live
> Fix brackets with more than 20 big-matches

- standard/tournaments_summary_table/commons/tournaments_summary_table.lua
stacked on #2973 since it needs the annotation definition of `ConditionTree` class from there
Add annotations to tournaments_summary_table.lua
N/A
> Add annotations to `tournaments_summary_table.lua`

- standard/links_stream.lua
- standard/ordinal/ordinal.lua
Silence some annoying annotatrion warnings about missing annos
- add `---@param _ nil`
- `---@diagnostic disable-next-line: incomplete-signature-doc` for a case where the other params are caught by overload
N/A
> Silence some annoying annotatrion warnings about missing annos

- components/infobox/commons/infobox.lua
- components/infobox/commons/infobox_basic.lua
- components/infobox/commons/infobox_map.lua
- components/infobox/commons/infobox_widget.lua
- components/infobox/commons/infobox_widget_injector.lua
stacked on #2990 because i fucked up and am lazy
- Add informationType overwrite option for infobox map
- Add annotations in files so the warnings shut up in `infobox_map.lua`
/dev for kicking the redundant function --> preview tests on several pages on several wikis for team, league and player infoboxes
rest N/A
> Add informationType overwrite option for infobox map

- standard/flags_master_data.lua
`ccc` -> `gcc`
Live since broke wiki :(
> Fix typo of filename in flag data

- components/results_table/commons/results_table.lua
Similar to #2813 , the solo opponent display for results table has the name then flag layour the opponent, as intended when the lastOpponent is also displayed, - however for achievements tables with playerResultsOfTeam = true, this will undo the flip in that case and left align the name with flag first
https://liquipedia.net/apexlegends/User:Dark_meluca/Test/ResultsTableNew/TeamAchievements
Was testing above with /dev, but another change to a dev module in the module sequence is currently causing what I think is an unrelated error,
Opening the pull request as a draft in the mean time, so as not to forget about it
> Do not flip opponent display for `hideResult == true`

- components/tournaments_listing/commons/tournaments_listing_conditions.lua
Adds arguments  `exludeTiertypeX` to the conditions.
While in theory most usages can already be achieved with `tiertypeX=!tiertype`, this won't work to list only tournaments with a  set tiertype, unless you list all possible tiertypes.
via /dev
> Add excludeTiertype to conditions of `TournamentsListing`

- components/results_table/commons/results_table.lua
- components/results_table/commons/results_table_award.lua
- components/results_table/commons/results_table_base.lua
- Add option to show `type` in Resultstables
- Fix team display in `displayDefaultLogoAsIs` case
dev + preview
> Add option to show `type` in Resultstables

- standard/string_utils.lua
- standard/test/string_utils_test.lua
Add `upperCaseFirst` function to StringUtils.
Uses `mw.getContentLanguage():ucfirst`, but unlike that one this function can be used directly in `Array.map` etc.
dev + testcases
> Create `upperCaseFirst` in StringUtils

- standard/region/commons/region.lua
- Remove the deprecated run function
- Rename the `.runNew` function to `.run`
N/A
> Replace deprecated function with new one

- components/squad/commons/squad_custom.lua
- components/squad/wikis/leagueoflegends/squad_custom.lua
- components/squad/wikis/smash/squad_custom.lua
With storage now being available in a core field as of #2938, this no longer need to be stored in extradata
> Remove unneeded extradata storage

- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Count qualifier earnings in sc2 team infoboxes
- Kick the no qualifier condition (they are already excluded for the medals stuff etc.)
dev
> Count qualifier earnings in sc2 team infoboxes

- components/earnings/commons/earnings_base.lua
depends on #3030
- UperCase first some team names in Earnings conditions, to fix an issue with TTs holding lowercased page names
- FYI: if this is not wanted: could just make the TT have UC first in the pagename field ...
- Use Array.map instead of doing it via a for loop
/dev
> UpperCase first some team names in Earnings conditions

- components/match2/commons/match_group.lua
- components/match2/commons/match_group_shorten_bracket.lua
Alternative solution to #2780
Add functionality to `ShowBracket` to skip X rounds in display
- query the match data for a given matchGroup id
- assert it is a valid id and the retrieved data is a bracket
- remove the first X rounds and adjust the remaining matches so they can be used for showBracket display
requested by @DMeluca on discord
main goal is to have the option to have an overview page that has reduced include size
live for new module + dev versions of the modules that get adjusted
example page: https://liquipedia.net/starcraft2/Liquipedia:BracketUpdate/Test
> Add functionality to match2 to skip X rounds in display

- components/tournaments_listing/commons/tournaments_listing_card_list.lua
Allow `additionalPlaceConditions` in `Module:TournamentsListing/CardList`
dev
> Allow `additionalPlaceConditions` in `Module:TournamentsListing/CardList`

- components/broadcast_talent_table/commons/broadcast_talent_table.lua
Broadcast talent for on-page showmatches like these (https://liquipedia.net/counterstrike/BLAST/Major/2023/Paris#Showmatch) have been broken since the start it seems? They just get doubled up in terms of the same role:
Just adding some change to not do the role-merging stuff on showmatches isn't enough either since the display doesn't match the rest of the tiers.
Switched to using tier and tiertype from broadcaster extradata and falling back to `Showmatch` tiertype if nothing is set in that regard.
(Will update the fix to sorting in #3009 after this is merged since it's easier that way)
`/dev` on cs and rl wikis.
> Fix showmatches in `BroadcastTalentTable`

- components/broadcast_talent_table/commons/broadcast_talent_table.lua
HotFix Broadcaster talent table: escape nil
Introduced via #3014
Fixes the most common error caused by recent changes
the tier sort also breaks some pages on sc2 but not as many
live
> HotFix Broadcaster talent table: escape nil

- components/broadcast_talent_table/commons/broadcast_talent_table.lua
On sc2 sometimes there are broadcaster cards on series pages for those the additional tournament data is stored in extradata including tier and tier type
Before #3009 this resultet in no tier shown.
After #3009 it now throws errors due to the tier.sort function expecting a valid tier.
This PR adjusts the tier parsing in the BroadCasterTealentTable so that as a fallback it looks into extradata to parse the tier.
It also improves the error message in case of invalid/unset tiers.
dev
> Account for sc2 special case in BroadCasterTealentTable

- standard/info/wikis/ageofempires/info.lua
Module:Info was still using the old naming scheme, whereas team template default settings is using the new one. Once merged, I'll request a TT DB change from old to new.
N/A
> Adjust naming scheme of default team logo

- components/infobox/wikis/callofduty/infobox_league_custom.lua
CoD Infobox league custom is overwriting the extradata instead of extending it, causing series2 to be lost.
Live as series2 was needed now
> Extend, not overwrite extradata in CoD Infobox League

- components/infobox/wikis/worldofwarcraft/infobox_person_player_custom.lua
Player Achivement Template on WoW doesn't work, and from what I can tell probably hasn't ever worked, so removing the call.
Live
> Remove Player Achivement Template on WoW

- standard/operator.lua
- standard/test/operator_test.lua
Create `Operator.eq` and `Operator.neq`. 
Some boy scouting with changing `math.pow(a, b)` to `a ^ b` to make it be usable on anything with the correct metamethod implemented.
https://liquipedia.net/commons/Module_talk:Operator/testcases
> Create `eq` and `neq` operator functions

- standard/fn_util.lua
- standard/test/fn_util_test.lua
Create a standard curry function to preforming [currying](https://en.wikipedia.org/wiki/Currying).
https://liquipedia.net/commons/Module_talk:FnUtil/testcases
> Create the curry function

- standard/links/commons/links.lua
Adding support for CoreStrike links (Omega Strikers Stats site)
Example URL: https://corestrike.gg/lookup/PuffyFPS
> Add support for CoreStrike link

- components/match2/commons/match_group_coordinates.lua
`Module:Iterator` is on the git and identical to `Module:IteratorUtil`
Note: This is the last consumer of the duplicate module so we can kill https://liquipedia.net/commons/Module:IteratorUtil after merge
N/A
> Use `Module:Iterator` instead of `Module:IteratorUtil`

- components/infobox/extensions/commons/player_introduction.lua
Fixes:
- catch players without transfer history in 
reported by Omarion: https://discord.com/channels/93055209017729024/372075546231832576/1116762129089970276
- catch players with team in infobox but no transfer history
reported by @DMeluca https://discord.com/channels/93055209017729024/372075546231832576/1117521149794992169 ff
- missing spaces in some cases
reported by Gravy: https://discord.com/channels/93055209017729024/268719633366777856/1117428095285219378
dev to live since bug
> Fix some issues in `PlayerIntroduction`

- standard/tier/wikis/smash/tier_custom.lua
Add `Tier.toIdentifier` overwrite for smash.
Due to their non standard setup we need to allow empty string as valid identifier.
live as hot fix since broadcast talent table was broken on smash on some pages
> Add `Tier.toIdentifier` overwrite for smash

- components/infobox/wikis/smash/infobox_series_custom.lua
Tier display in series infobox is unwanted
https://liquipedia.net/smash/index.php?title=Module%3AInfobox%2FSeries%2FCustom%2Fdev&type=revision&diff=423686&oldid=423661
> Remove tier display from series infobox for smash

- standard/error_display.lua
- standard/error_ext.lua
Add stash/retrieve options to `Module:Error/Display` and `Module:Error/Ext`
With this change we can dissolve seversal /downstream (and a few non git) modules.
via /downstream
> Add stash/retrieve options to `Module:Error/Display` and `Module:Error/Ext`

- components/infobox/wikis/fifa/infobox_league_custom.lua
Targeting this on {{TournamentsList}} portal
Briefly edited into LIVE infobox, no side errors
> Add highlights for FIFA League Infobox

- components/infobox/wikis/tft/infobox_person_player_custom.lua
Requested by Taner (One of TFT's main contributors) to be added to player infoboxes.
With /dev and preview loading player pages in mainspace. Also saved and checked Team is correctly stored in lpdb
> TFT: Add PlayerTeamAuto detection for player infobox

- components/infobox/wikis/ageofempires/infobox_person_player_custom.lua
With more and more transfer data actually being stored as transfers, this makes PlayerTeamAuto and TeamHistoryAuto the default if there is no manual override input.
For the history (inspired by SC2, where it was bot-added), there is a display of both for logged-in users to help migrating.
It might be advisable to restrict this even further, maybe editor+? I'm not aware of the appropriate class tho.
via dev on various pages (even logged out)
> AoE: Automate team and history in Infobox player

- components/prize_pool/wikis/brawlstars/prize_pool_custom.lua
Since the commons TeamCard/Custom uses mw.ustring already, variable names didn't match in case of captial unicode letters.
dev to live
> Use mw.ustring.lower over string.lower

- standard/flags.lua
- standard/test/flags_test.lua
Add `Flags.isValidFlagInput` function and according testcases.
Intended usage is in some sc2 modules where we would like to filter provided args keys for valid flags.
`local someVar = Table.filterByKey(args, Flags.isValidFlagInput)`
dev
> Add `Flags.isValidFlagInput` function

- components/infobox/wikis/ageofempires/infobox_person_player_custom.lua
PlayerIntroduction expects a pagename passed as player, which sometimes mismatches the ID (e.g. lowercase IDs)
dev
> AoE: Fix mismatch between id and pagename for PlayerIntroduction

- components/infobox/wikis/overwatch/infobox_person_player_custom.lua
Adding Streamer as a supported role
[Tested here.](https://liquipedia.net/overwatch/User:Moonshot/sandbox4) via /dev
> Add `streamer` as role to Overwatch Infobox player

- components/infobox/wikis/brawlstars/infobox_person_player_custom.lua
Pass along romanized name over localized name to player intor in brawlstars infobox player
live, bug fix
> Pass along romanized name over localized name in brawlstars infobox player

- components/infobox/wikis/ageofempires/infobox_league_custom.lua
When a map name is a redirect, the expected display is the unresolved name. Therefore, the display name needs to be set, but can be dropped to reduce JSON length if resolved and unresolved name match.
via dev
> AoE: Use unresolved map name in case of redirects

- components/opponent/commons/player_ext.lua
date was used for comparison with leavedate (iso string) from player history
via /dev by hjp
> Parse unix timestamp to ISO for comparison

- components/match2/wikis/pokemon/match_group_input_custom.lua
**Make it so when inputting SoloOpponents in Match2 Bracket, you dont need to add flag all the time**
- If {{OpponentList}} is present above and with all flag inputs inside that, It takes from there
- If a player has page, It takes from their page right away
- When input flag on their first match, every subsequent match doesnt need to as flags being kept onto it
Generally made it easier for contributor, this was made possible after #3100 (since pre-3100 fix theres errorcodes)
**/dev** on two live pages
**Mostly with player who has pages**
https://liquipedia.net/pokemon/index.php?title=Pokemon_Championships%2FInternational%2FNorth_America%2F2023%2FVGC&type=revision&diff=185663&oldid=185631
**All no-page players, utilizes the first match input then not input flag anymore after first round** …
> Adjust Pokemon Match2 to take flags input automatically

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
- components/prize_pool/wikis/counterstrike/prize_pool_custom.lua
Allow prize pool to not need to be updated every time something in infobox changes.
Tested on `/dev` on cs wiki.
> Switch CS infobox league to store extradata in single var

- components/prize_pool/commons/prize_pool_import.lua
Currently PPT imports `qualLose` even when winner import is disabled for the stage.
This PR changes it so that if winner import is disabled for a stage `qualLose` in that stage will not be imported.
`qualLose` indicates a Loser of a match still advancing to the next stage, so from a logical point of view it makes sense to only import them if winner import is enabled
/dev
> Do not import QualLose when winners are not imported

- components/opponent/commons/player_ext.lua
Catch empty string potentially causing some errors.
Currently if `options.date` is empty string `DateExt.toYmdInUtc` would error.
To circumvent this use `Logic.emptyOr` instead of plain `or`
dev
> Catch empty string potentially causing some errors

- components/tournaments_listing/commons/tournaments_listing_card_list.lua
This logic was wrong on the CS module that pre-dates this one and is possibly where this has been "copied" from. Anyway, this fixes the following display issue when both prize pool and participants number are missing:
Tested on `/dev` and then also pushed live.
Also ensured it still works properly when tiers are shown:
> TournamentsListing: fix inverted logic causing mobile display issues

- components/prize_pool/wikis/counterstrike/prize_pool_custom.lua
- components/prize_pool/wikis/counterstrike/prize_pool_legacy_custom.lua
The `tournament name` field was not being mapped to a header argument in legacy. Added that and also renamed some of the others to have less better names in the non-legacy module.
Tested `/dev`.
> Fix CS PPT legacy tournament name

- components/infobox/wikis/starcraft2/infobox_person_custom_shared.lua
Remove `'not player'` storage in status field for sc2 infobox player/commentator since it causes an issue in playerintroduction and is not needed anymore
dev
> Remove `'not player'` storage in status field

- standard/links/commons/links.lua
Adding support for Omega Strikers new stats website:
Example URL
https://strikr.gg/pilot/PuffyFPS
Icon:
https://liquipedia.net/commons/File:InfoboxIcon_Strikr.png
> Add support for Strikr within Links

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
Convert string to number and fallback to 0.
SC2 Infobox player broke on some pages due to indiv. prize money suddenly being a string instead of a number.
This PR catches those strings and converts them to numbers and falls back to 0 if the given value is not numeric.
Needed for summing up and fo comparing with another number.
live, hotfix
> Convert `individualprizemoney` from string to number to avoid comparing string with number

- components/match2/commons/match_summary_base.lua
- standard/vod_link.lua
Should be 16px not 15px, and also that part is done via CSS class `vodlinks` (so we can 32px instead for higher PPI devices).
Blurry before change:
Tested with dev. CSS class has existed for ages already so won't need any delay to being pushed.
After change not blurry:
> Use 32px icons for match links and vods

- standard/timezone_data.lua
Adding Venezuelan Standard Time (VET) as UTC-4
Just some data :D
> Add Venezuelan Standard Time

- components/notability/wikis/ageofempires/notability_checker_config.lua
With `Module:Tier/Data` in place, the notability config needed some adjustments.
All changes in calculation are result of a discussion among editors.
In theory the listing of tier -1 could be omitted, it is just added to be explicit.
Live
> AoE: Adjust notability config to new tier/tiertypes

- components/statistics/count.lua
Was doing some checks on the coverage table and there were cases where it was including cancelled tournaments that did not have proper date information.
Added a parameter to check select whether to filter them out or not
> Add filter to remove cancelled/postponed tournaments

- components/match2/wikis/rocketleague/match_group_input_custom.lua
As title says, needed for rating to properly filter tiertypes from valid matches.
Tested with /dev
> Store `liquipediatiertype2` on RL Match2 extradata

- components/statistics/count.lua
args are technically optional, the function can be called without any arguments to set lpdb conditions and by default query all entries of that lpdb data type
> Change annotations to account for default tables

- components/match2/wikis/rainbowsix/match_summary.lua
Update opl icon in R6 matchSummary as per request by Okidokie98
https://discord.com/channels/93055209017729024/874304000718172200/1132754514156458085
/dev by Okidokie98
> Update opl icon in R6 matchSummary

- components/infobox/extensions/wikis/rocketleague/team_ranking.lua
- components/infobox/wikis/rocketleague/infobox_team_custom.lua
- components/ratings/ratings.lua
- components/ratings/ratings_display.lua
- standard/date_ext.lua
- standard/test/date_ext_test.lua
Create Team ELO Rating component.
Currently hardcoded settings, only works on Rocket League (which is the only thing that in scope for now)
Semi-live 
https://liquipedia.net/rocketleague/Liquipedia:RatingV2
Infobox
with /dev
> Create Team ELO Ratings

- components/ratings/ratings.lua
- components/ratings/ratings_display.lua
Add missing `/` in the module name for Date/Ext
Live
> Fix import of DateExt in Ratings

- components/match2/wikis/rocketleague/legacy/match_group_legacy_default.lua
RL had RxDydisplay input to specify a custom displayname.
The currently used legacy conversion doesn't work, this PR fixes that.
Note: link being a duplicate of name and p1 being the (optional) displayname makes sense due to:
In opponent module reading opp args for solo opponents gets the link from the link value while the display name is determined via `args[1] or args.p1 or args.name`, so
- if p1 (optional display input) is set it is used as displayName
- if p1 is not set it falls back to name, the page name
dev
> Fix RL solo opponent parsing in legacy brackets

- standard/logic.lua
depends on #3063 
Add `wrapTryOrLog` and `tryOrElseLog` to `Module:Logic`
With this we can kill `Module:Logic/downstream` and i think those 2 functions are a nice and useful addition.
(All other usages of `Module:Logic/downstream` have been eliminated in non dev/archived modules.)
Factually already in use in several non git modules via downstream
> Add `wrapTryOrLog` and `tryOrElseLog` to `Module:Logic`

- components/infobox/extensions/wikis/starcraft2/infobox_extension_cost_display.lua
- components/infobox/wikis/starcraft2/infobox_building_custom.lua
- components/infobox/wikis/starcraft2/infobox_unit_custom.lua
Some units/buildings in sc2 have total costs (e.g. `Lurker` which is morphed from `Hydralisk`, so the total cost of a Lurker is the costs of the Hydralisk + the costs for the morph)
This PR adds the option for total cost input (incl. display and storage). It also adds storage for supply in infobox unit so that the LPDB data is better.^^
dev into live (very low risk, could already let the one that requested it update the pages)
> Enhance sc2 costdisplay in infobox unit and building

- components/mvp_table/commons/mvp_table.lua
- Add legacy match1 query support to MvpTable
- In case the match2 mvp data is in old format this is also caught (via `Logic.tryCatch` since old format in match2 would else result in an error) and uses match1 legacy query instead in that case.
- compared to the old match1 based mvp table this one catches some edge cases (redirects, players with underscores) too
this should allow rolling it out on all wikis, even ones that are not on match2 yet
and it should sllow to easily use it on wikis that have some match2 pages but still have pages where brackets/matchlists are not converted yet
dev
> Add legacy match1 query support to MvpTable

- components/match2/wikis/arenaofvalor/match_group_input_custom.lua
- components/match2/wikis/arenaofvalor/match_legacy.lua
Store mvp data on aov in a sane way
N/A, copied 1-1 from lol
match1 storage (old stuff) adjusted and purge for those initiated
needs purge run for match2 matches after this pr is merged too
> Store mvp data on aov in a sane way

- standard/game.lua
Due to an oversight in design (by me), game icons with darkmode versions cause two spans to appear, but since the hiding is done via class on the image rather than span, it leaves a span there and shifts the icons over.
This PR makes it so it's just one span with multiple images inside which fixes the issues.
> Fix double span in darkmode game icons
