Liquipedia/Lua-Modules

components/match2/wikis/rainbowsix/match_group_input_custom.lua
Saves the caster data into extra data which will actually show them on the match summary. Seems I forgot to include this line in the first PR
Tested live
=> Fixing match2 bug on Siege

components/infobox/wikis/apexlegends/infobox_person_player_custom.lua
Make `|input=` values case-insensitive in player infobox 
Tested with dev module in preview
=> Make `|input=` values case-insensitive in player infobox

components/results_table/commons/results_table.lua
stacked on #2120
Add init + functions it calls to results table
alone not functional, will be properly tested once every thing comes together in #2120
ignore the lua check error
it is irrelevant as the never accessed var `OpponentDisplay` will be used later on via stuff that gets added via additional prs into the base pr
=> Add init + functions it calls to results table

standard/info/wikis/battlerite/info.lua
Create Battlerite Infobox Module
N/A
=> Set up Battlerite Info Module

standard/info/wikis/autochess/info.lua
Create Battlerite Infobox Module
N/A
=> Set up Auto Chess Info Module

standard/info/wikis/underlords/info.lua
Create Underloards Infobox Module
N/A
=> Set up Underlords Info Module

standard/info/wikis/runeterra/info.lua
Create Runeterra Infobox Module
N/A
=> Set up Runeterra Info Module

standard/info/wikis/hearthstone/info.lua
Create Hearthstone Infobox Module
N/A
=> Set up Hearthstone Info Module

standard/info/wikis/simracing/info.lua
Create Sim Racing Infobox Module
N/A
=> Set up Sim Racing Info Module

standard/info/wikis/splatoon/info.lua
Create Splatoon Infobox Module
N/A
=> Set up Splatoon Info Module

standard/info/wikis/artifact/info.lua
Create Artifact Infobox Module
N/A
=> Set up Artifact Info Module

standard/info/wikis/magic/info.lua
=> Setup Magic info Module

components/infobox/wikis/brawlstars/infobox_person_player_custom.lua
Add brawlstars infobox player
/dev
=> Add brawlstars infobox player

components/results_table/commons/results_table.lua
stacked on #2120
Add create + functions it calls to base results table
- build query conditions
- query data
- process data (sort, categorise)
alone not functional, will be properly tested once every thing comes together in #2120
=> Add :create() + functions it calls to base results table

components/match2/wikis/halo/match_summary.lua
Complete rewrite of Halos Match Summary to base the module off the base Commons version
/dev and [testing page](https://liquipedia.net/halo/User:Fenrir.SPAZ/sandbox)
=> Halo Match2 rewrite to base (Match Summary)

components/squad/wikis/valorant/squad_custom.lua
Resolves #2188. Adds support in Valorant's Squad Module for `SquadAuto`. Valorant is current running `SquadAuto` on some pages using non-Squad display & storage. This PR allows them to be switched over to using Squad.
For review help:
Line 76 to 106 of old is the new function `_playerRow()`.
Tested with dev & preview
=> Add runAuto to Valorant's Squad

components/infobox/wikis/starcraft2/infobox_league_custom.lua
Store the same value in lpdb_tournament that gets set into the wiki var and hence stored into stuff further down on the page
Also makes it so that the same value is also set on subpages
FYI: Currently that value is not queried anywhere
/dev
=> Store game standardized in sc2 infobox league

components/results_table/commons/results_table_base.lua
Add lastvs processing to base of results table
"live" (modules exist, but not in use except for testing)
=> Add lastvs processing to base of results table

components/infobox/extensions/commons/years_active_base.lua
Years in the future should show as present activity.
In userspace.
=> Handle future tournaments in Years Active 

standard/timezone_data.lua
Adding https://liquipedia.net/commons/Template:Abbr/WITA
None, just data.
=> add WITA timezone

components/notability/commons/notability_checker.lua
Fix notability for players with spaces in pagename.
Tested with own copy of code with patch applied.
=> Fix notability for players with spaces in pagename

components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua
Add support for positional icons based on transfers
Live on THA templates on wikis like LoL/Arena of Valor/Wildrift
=> Add support for Position icon

components/match2/wikis/callofduty/match_legacy.lua
**Match2 for Call of Duty**
**_Ported from Overwatch_**, there were some small changes to it
COD shares similarities to Overwatch so multiple modes and multiple maps, things like Bracket Reset also existed here as well. 
LIVE
e.g. 
https://liquipedia.net/callofduty/Call_of_Duty_League/Season_4/Stage_1 (Matchlist)
https://liquipedia.net/callofduty/Fall_Invitational/2022/Knockout_Stage (Bracket)
=> Create Match Legacy for COD

components/match2/wikis/pokemon/match_legacy.lua
These are direct port of Mobile Legends (Which has #1502 merged last month)
LIVE
Should the properties be changed due to for a Pokemon wiki, both teams and indivs are used (compared to ML that is almost entirely team only)
=> Create Match Legacy for Pokemon

components/match2/wikis/callofduty/match_summary.lua
**Match2 for Call of Duty**
**_Ported from Overwatch_**, there were some small changes to it
COD shares similarities to Overwatch so multiple modes and multiple maps, things like Bracket Reset also existed here as well. 
LIVE
e.g. 
https://liquipedia.net/callofduty/Call_of_Duty_League/Season_4/Stage_1 (Matchlist)
https://liquipedia.net/callofduty/Fall_Invitational/2022/Knockout_Stage (Bracket)
=> Create MatchSummary for COD

components/match2/wikis/callofduty/match_group_input_custom.lua
**Match2 for Call of Duty**
**_Ported from Overwatch_**, there were some small changes to it
COD shares similarities to Overwatch so multiple modes and multiple maps, things like Bracket Reset also existed here as well. 
LIVE
e.g. 
https://liquipedia.net/callofduty/Call_of_Duty_League/Season_4/Stage_1 (Matchlist)
https://liquipedia.net/callofduty/Fall_Invitational/2022/Knockout_Stage (Bracket)
=> Create MatchGroupInput/Custom for COD

components/prize_pool/commons/prize_pool_legacy.lua
Fix lastvs handling for solo opponents
/dev
no visual change, no data change for team opponents (tested on cs)
properly parses the solo lastvs now
=> Fix lastvs handling for solo opponents

components/match2/wikis/arenaofvalor/match_group_input_custom.lua, components/match2/wikis/mobilelegends/match_group_input_custom.lua, components/match2/wikis/pokemon/match_group_input_custom.lua, components/match2/wikis/wildrift/match_group_input_custom.lua
These 4 wikis shares same base, they missing **return opponents** within the Walkover function, and also suffer an issue that was solved by #1114, which wasnt present in these 4 games
/dev modules
PR will start with pokemon first, then the other three gets added later here
=> Add #1114 and Walkover fix to Pokemon, WR, ML, AOV

components/prize_pool/commons/prize_pool.lua
Requested by the team working on the new wiki theme.
dev module
=> Add CSS-class to the place cell in PrizePoolTable

components/results_table/commons/results_table_custom.lua
Add commons csutom for results/awards table
live (not in use)
(only calls the according function in the necessary modules)
=> Add commons custom for results/awards table

components/infobox/wikis/rainbowsix/infobox_league_custom.lua
Add 'Console' as platform in R6 infobox league
as per request by Okidokie
N/A, just table entry added
=> Add 'Console' as platform in R6 infobox league

components/prize_pool/commons/prize_pool_placement.lua
Fix typo in PPT that was introduced via #2267
live (hot fix)
=> Fix typo in Prize Pool Table

components/infobox/wikis/ageofempires/infobox_series_custom.lua
Adds an implementation of Infobox series that displays the total awarded prize money.
via /dev
=> Add `Infobox/Series/Custom` for ageofempires

components/infobox/wikis/trackmania/infobox_league_custom.lua
Port of previous `Template:Infobox_league`.
New module, so live with invokes on various pages
=> Add infobox league to trackmania

components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua
not considered players anymore
=> Add Streamer role

components/match2/wikis/clashroyale/brkts_wiki_specific.lua
Incorrect header on a file
N/A
=> Fix Incorrect Magic Header for Brkts ClashRoyale

components/hidden_data_box/wikis/halo/hidden_data_box_custom.lua
Creates a new HiddenDataBox for Halo 
Currently being tested live on this [page](https://liquipedia.net/halo/Halo_Championship_Series/2021-22/Orlando/Open_Bracket) with proper results showing on [BesT MaN's page](https://liquipedia.net/halo/BesT_MaN#Achievements) (tier was originally undefined for the above event
=> Create HDB for Halo

components/match2/wikis/overwatch/match_group_input_custom.lua
For some reason, overwatch doesn't have a few improvements to the match2 system, missing for instance darkmode icons and simplified stream handling. This PR bring OW up to date.
dev module
=> Apply #763 and #1032 to OW

components/prize_pool/wikis/overwatch/prize_pool_custom.lua
Adding prizepoints and minimumsecured to extradata to allow for RankingsTable support
Successfully stored [here](https://liquipedia.net/overwatch/User:Moonshot/sandbox).
=> Add prizepoints and minimumsecured to OW

components/infobox/commons/infobox_company.lua
Made more cell customizable in Infobox Company. 
Allowed alias for Founded and Defunct
Dev module with #2298
=> Make Infobox Company more customizable

components/infobox/wikis/starcraft/infobox_series_custom.lua, components/infobox/wikis/starcraft2/infobox_series_custom.lua
Prep infobox series to kick wikicode vardefines in templates
/dev
=> Update Series Infobox to allow for removal of wikicode in templates

components/opponent/wikis/clashroyale/opponent_custom.lua, standard/info/wikis/clashroyale/info.lua
Add CR `Module:Opponent/Custom`
- Adjusts `Opponent.resolve` for retrieving player teams
live ((should) not yet used on live)
=> Create Custom Opponent module for CR

components/infobox/wikis/warcraft/infobox_company_custom.lua
Create a Custom Company Infobox for Warcraft wiki. 
Preview
=> Create Company Infobox for WC

components/infobox/wikis/worldofwarcraft/infobox_company_custom.lua
Create Custom Infobox Company for World of Warcraft
Preview testing
=> Create Company Infobox for WoW

components/infobox/wikis/fifa/infobox_company_custom.lua
Create custom Company infobox for FIFA
Preview
=> Create Company Infobox for FIFA

components/infobox/wikis/hearthstone/infobox_company_custom.lua
Create company infobox for Hearthstone
Preview
=> Create Company Infobox for HS

components/infobox/wikis/teamfortress/infobox_company_custom.lua
Infobox Company for Team Fortress
Preview
=> Create Company Infobox for teamfortress

components/infobox/wikis/dota2/infobox_company_custom.lua
Create Infobox Company for dota2
=> Create Company Infobox for dota2

components/opponent/commons/opponent_display.lua, components/opponent/wikis/rocketleague/opponent_display_custom.lua
Adjust showLink default for BracketOpponentEntry:createPlayer
/dev
=> Have showLink default off for Bracket Players

components/results_table/wikis/starcraft2/results_table_custom.lua
Add sc2 custom for results table
"live" (new module without use currently) in user space
=> Create sc2 custom for results table

components/prize_pool/commons/starcraft_starcraft2/prize_pool_legacy_starcraft.lua
Catch some edge cases ion sc/sc2 ppt legacy and fix a typo for 2v2/archon stuff
/dev into live
=> Catch Edge Case player input in sc/sc2 legacy ppt

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Replace featured storage with publishertier storage
dev into live so i can start bot runs
=> SC: Replace featured storage with publishertier storage

components/hidden_data_box/wikis/starcraft2/hidden_data_box_custom.lua
Remove usage of extradata.featured in SC2 HDB
/dev
=> Remove usage of extradata.featured in SC2 HDB

components/match2/wikis/clashroyale/match_group_input_custom.lua
stacked on #2322 for easier review
Add non team stuff to cr match input custom
tested together with team stuff on live
without team stuff: https://liquipedia.net/clashroyale/Module:MatchGroup/Input/Custom/dev
=> Add non team stuff to cr match input custom

components/prize_pool/wikis/brawlstars/prize_pool_legacy_custom.lua
Add BS PPT Legacy Custom temporarily
only needed for cleanup, to be removed after cleanup
live (not in use as of now)
=> Add BS PPT Legacy Custom

standard/table.lua, standard/test/table_test.lua
Add `Table.filterByKey`
/dev + test suite
=> Add `Table.filterByKey`

components/infobox/wikis/teamfortress/infobox_team_custom.lua
Create Team Infobox for Team Fortress
Put it live
=> Create Infobox Team for Team Fortress

components/prize_pool/wikis/halo/prize_pool_custom.lua
Creates a new Prize Pool Custom originally created by @Kanopedia 
[Kanos testing page](https://liquipedia.net/halo/User:Kanoodles/PPT)
=> Halo PrizePool Custom

components/prize_pool/wikis/brawlstars/prize_pool_custom.lua
Add BS PPT Custom
"live" without usage except for test page
=> Add BS PPT Custom

components/prize_pool/wikis/halo/prize_pool_custom.lua
Fixes a bug where the Custom does not check for blank input
Currently live
=> Bug fix for Halo Prize Pool

components/prize_pool/wikis/brawlstars/prize_pool_custom.lua
Fix bs ppt to error due to missing key/index
introduced via #2343
live, hotfix (starting to roll it out atm)
=> Fix bs ppt to error due to missing key

components/prize_pool/wikis/brawlstars/prize_pool_custom.lua
Catch some edge cases where tournament_type is unset and hence the weight function errors.
live
=> Catch nil in BS PPT Custom

components/infobox/wikis/heroes/infobox_team_custom.lua
Create Team Infobox for Heroes
Live
=> Create Team Infobox for Heroes

components/hidden_data_box/commons/hidden_data_box.lua, components/infobox/commons/infobox_league.lua, standard/test/text_sanitizer_test.lua, standard/text_sanitizer.lua
Rename `TextSanitizer.tournamentName()` to `TextSanitizer.stripHTML()`.
Untested :(
=> Rename TextSanitizer function to `stripHTML()`

components/match2/wikis/rocketleague/match_group_input_custom.lua
Add ~~"hasstream" and~~ "hasopponents" to match extradata for ease of calling LPDB for ~~sorting and~~ condition purposes
/dev module
=> RL: Add "hasopponents" to RL match extradata

components/infobox/wikis/ageofempires/infobox_team_custom.lua
Create Team Infobox for AoE
Also did quick scan of LPDB and SMW
=> Create Team Infobox for Age of Empires

components/match2/wikis/counterstrike/get_match_group_copy_paste_wiki.lua
Just some minor changes to the output of the generator module for better wikicode layout.
Live on wiki.
=> Move around some of the CS `{{Match}}` params

components/infobox/commons/infobox_widget_cell.lua
Remove unused field in Widget Cell
dev
=> Remove unused field in Infobox Cell Widget

components/match2/wikis/rainbowsix/match_group_input_custom.lua
R6 was one of the first wikis to have match2 implemented. The code quality and style is not up to par with what's expected of it these days.
Added to dev and had a few editors look for bugs
=> General refactor of R6's M2 Input Parsing

components/squad/wikis/ageofempires/squad_custom.lua, components/squad/wikis/apexlegends/squad_custom.lua, components/squad/wikis/arenaofvalor/squad_custom.lua, components/squad/wikis/counterstrike/squad_custom.lua, components/squad/wikis/dota2/squad_custom.lua, components/squad/wikis/leagueoflegends/squad_custom.lua, components/squad/wikis/mobilelegends/squad_custom.lua, components/squad/wikis/overwatch/squad_custom.lua, components/squad/wikis/pubg/squad_custom.lua, components/squad/wikis/rainbowsix/squad_custom.lua, components/squad/wikis/rocketleague/squad_custom.lua, components/squad/wikis/starcraft2/squad_custom.lua, components/squad/wikis/trackmania/squad_custom.lua, components/squad/wikis/valorant/squad_custom.lua, components/squad/wikis/wildrift/squad_custom.lua
Use Lua.import's `requireDevIfEnabled` instead of a normal require on the Squad & Squad Row modules imported from Squad/Custom's.
dev module
=> `requireDevIfEnabled` for Squad Modules

components/infobox/wikis/starcraft2/infobox_league_custom.lua
Fix autopatch dates in sc2 infobox league
dev into live
=> Fix autopatch dates in sc2 infobox league

components/infobox/wikis/pubgmobile/infobox_map_custom.lua
New map infobox to replace old templaet version
Tested here with /dev
https://liquipedia.net/pubgmobile/User:Dark_meluca/MapTest
Displays correct and also stores to lpdb
=> PUBGMobile: Create Infobox/Map/Custom

standard/info/wikis/callofduty/info.lua
stacked on #2197
Update info.lua of cod
so far only a conversion from input to data table
-
=> Update cod Module:Info

components/match2/commons/match.lua, components/match2/commons/match_group_input.lua, standard/links_stream.lua
Cleanup of released feature flags.
Dev module
=> Remove merged featureflags

standard/info/wikis/arenafps/info.lua
stacked on #2197
Update info.lua of arenafps
so far only a conversion from input to data table
-
=> Update arenafps Module:Info

components/prize_pool/commons/prize_pool_legacy.lua
Add more customization options in PPT Legacy
needed for warcraft
- allow to overwrite LegacyPrizePool.mapOpponents entirely
- add function to determine `opponentsInSlot` and make it customizable
dev
=> Add more customization options in PPT Legacy

standard/tournaments_summary_table/wikis/warcraft/tournaments_summary_table_custom.lua
Add TournamentsSummaryTable for warcraft
live (new)
=> Add TournamentsSummaryTable for warcraft

components/match2/wikis/clashroyale/player_ext_custom.lua
Add CR `Module:Player/Ext/Custom`
live
=> Add CR `Module:Player/Ext/Custom`

standard/links/wikis/warcraft/links_custom_data.lua
Overwrite challonge link prefix on WC
live
=> Overwrite challonge link prefix on WC

components/results_table/commons/results_table_base.lua
Return self instead of nil in Resultstable base
dev into live, bug fix
=> Return self instead of nil in Resultstable base

components/infobox/wikis/warcraft/infobox_league_custom.lua
Add nil check in WC infobox league
live, bug fix
=> Add nil check in WC infobox league

components/notability/wikis/pubgmobile/notability_checker_config.lua
Tested here. The invoke is for the "NotabilityChecker/dev" module as a local "NotabilityChecker" exists , however the /dev on commons is up to date with the git version. 
https://liquipedia.net/pubgmobile/User:Dark_meluca/NotabilityTest
=> pubgmobile: create notability checker config file

components/squad/wikis/halo/squad_custom.lua
Creates a new Squad module for Halo
[testing page](https://liquipedia.net/halo/User:Fenrir.SPAZ/SquadTest)
The following images are from testing pages (OpTic Gamings mainspace page)
Top squad is the testing version while the bottom is the current ``{{ActiveSquadAuto}}`` being used on the wiki
Additionally the code is visible here with the testing template
=> Halo Squad Custom

components/infobox/wikis/starcraft/infobox_league_custom.lua, components/infobox/wikis/starcraft/infobox_team_custom.lua, components/infobox/wikis/starcraft2/infobox_building_custom.lua, components/infobox/wikis/starcraft2/infobox_league_custom.lua, components/infobox/wikis/starcraft2/infobox_skill_ability.lua, components/infobox/wikis/starcraft2/infobox_skill_spell.lua, components/infobox/wikis/starcraft2/infobox_strategy_custom.lua, components/infobox/wikis/starcraft2/infobox_team_custom.lua, components/infobox/wikis/starcraft2/infobox_unit_custom.lua, components/infobox/wikis/starcraft2/infobox_unofficial_world_champion_custom.lua
Clean up race stuff in infoboxes [part 1]
Part 2 will be the more complicated person modules
/dev or live (if usage on 1 page)
=> Refactor race/faction in infoboxes [part 1]

components/faction/commons/faction.lua
Add missing brackets around the singleFaction
live (unused function + bug fix for testing my infobox changes)
=> Faction: Fix return value in edge case

components/squad/wikis/starcraft2/squad_custom.lua
only merge after #2454
Clean up race stuff in sc2 squad custom
kicking "all" in fav of tpz/pzt/... is intended
dev
=> Refactor Race/Faction in sc2 squads

components/match2/commons/starcraft_starcraft2/match_group_display_bracket_starcraft.lua, components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua, components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua, components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua, components/match2/commons/starcraft_starcraft2/player_display_starcraft.lua, components/match2/commons/starcraft_starcraft2/player_ext_starcraft.lua, components/opponent/commons/starcraft_starcraft2/opponent_display_starcraft.lua
Use Module:Faction in sc/sc2 match2 modules
dev
=> Refactor sc/sc2 match2 Race/Faction handling

components/faction/commons/faction.lua
Fix anotation typo in Faction module
N/A
=> Fix anotation typo in Faction module

components/infobox/wikis/pubgmobile/infobox_team_custom.lua
addtolpdb not used in custom, so removed the extra definition and call
=> pubgmobile: removed redundant function override

components/infobox/wikis/pubgmobile/infobox_team_custom.lua
Removed the or statement for passing team parameters to placement summary module and used only args.teampage
=> use team pagename to query team placement summary

components/match2/wikis/warcraft/player_ext_custom.lua
depends on #2392 and #2394
Add WC Player/Ext/Custom
Needed due to race stuff
live module together with other prs in prize pool
=> Add WC Player/Ext/Custom

components/match2/wikis/warcraft/match_group_util_custom.lua
depends on #2392 and #2394
Add Warcraft MatchGroup/Util/Custom
Needed due to race stuff
live module together with other prs in prize pool
=> Add Warcraft MatchGroup/Util/Custom

components/match2/wikis/warcraft/player_display_custom.lua
depends on #2392, #2394, #2397 and #2396
Add WC Player/Display/Custom
Needed due to race stuff
live (new module not in use except on test page)
=> Add WC Player/Display/Custom

components/prize_pool/commons/prize_pool_placement.lua
Add placement storage for all TBD entries via adding a tbd index to the objectName
dev
=> Add placement storage for all TBD entries

components/prize_pool/wikis/warcraft/prize_pool_legacy_custom.lua
Fix slot calculation for Special places in WC PPT Legacy
dev into live (bug fix)
=> Fix slot calculation for Special places in WC PPT Legacy

components/prize_pool/wikis/warcraft/prize_pool_custom.lua
Allow auto currency exchange on WC PPT
live
=> Allow auto currency exchange on WC PPT

components/infobox/commons/infobox_team.lua
Improve the code in the Team Infobox
dev module
=> refactor: minor cleanup of team infobox

components/hidden_data_box/wikis/warcraft/hidden_data_box_custom.lua
Add WC HDB Custom
live (HDB has usage on a total of 1 page on WC so far and there it works)
=> Add WC HDB Custom

components/infobox/commons/infobox_widget_links.lua, standard/links/commons/links.lua
Add Links support for NWC3L 
this is for the Warcraft Wiki as requested
=> Add NWC3L Links support

components/match2/wikis/rainbowsix/match_group_input_custom.lua, components/match2/wikis/rainbowsix/match_summary.lua
R6 adjust match links as requested by Okidokie98
https://discord.com/channels/93055209017729024/874304000718172200/1072153653856702476
provided in dev and tested by Okidokie98
=> R6 adjust match links

components/infobox/commons/infobox_league.lua
Make the location cell customizable.
dev module
=> Make `location` customizable in Infobox League

components/prize_pool/wikis/tetris/prize_pool_custom.lua
PrizePool/Custom for Tetris
_Plain port of Pokemon PPT, because they are similar in how PPT should work_
LIVE - https://liquipedia.net/tetris/CTWC/2022
=> Add PPT for Tetris

components/squad/wikis/brawlstars/squad_custom.lua
Squad Module for Brawl Stars
LIVE for Some Page under the test of both Squad and Org Auto
https://liquipedia.net/brawlstars/Revenant_Esports
Kano is the one who setup the module so I'm not sure about the baseline (where it was ported from if it is)
I just take it to PR.
EDIT: Replaced with VALORANT Port (so it works for New squad but not Auto)
=> Add Squad for Brawl Stars

components/infobox/wikis/tetris/infobox_person_player_custom.lua
Player Infobox for Tetris
LIVE - https://liquipedia.net/tetris/Jonas_Neubauer
If I recall this is a port of a WIP version from Clash Royale (which is set to go PR originally but then you know, things happened.), Whenever this merged. Clash Royale can use the same one as Tetris as well as a quick port
=> Add Infobox Player for Tetris

standard/info/wikis/zula/info.lua
Creates a new Info module for Zula
=> Create Zula Info

components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua
Adding support for PlayerTeamAuto on the MLBB wiki per request from the contributors.
Tested here:
https://liquipedia.net/mobilelegends/Module:Infobox/Person/Player/Custom/dev 
Needed to add playerintroduction to the wiki as well
=> Update Player Infobox to add support for PlayerTeamAuto

components/earnings/wikis/worldofwarcraft/earnings.lua, components/infobox/wikis/worldofwarcraft/infobox_person_player_custom.lua
Needs birthdates swapped from Template to ISO at go live
=> Create Player Infobox for WoW

components/infobox/wikis/teamfortress/infobox_person_player_custom.lua
Create Player Infobox for Team Fortress.
Live
=> Create Player Infobox for Team Fortress

components/infobox/wikis/crossfire/infobox_person_player_custom.lua
Cleaned up and simplified version of what's been live for 6+ month on the wiki (without being on git).
Live
=> Create Infobox Player for Crossfire

components/earnings/wikis/arenafps/earnings.lua, components/infobox/wikis/arenafps/infobox_person_player_custom.lua, standard/info/wikis/arenafps/info.lua
Create Player Infobox for ArenaFPS
Requires swapping births to ISO from Template at go live
=> Create Infobox Player for ArenaFPS

components/infobox/commons/infobox.lua
Fix infobox categories sortKey being index of Array.forEach
dev
=> Fix infobox categories sortKey being index of Array.forEach

components/infobox/wikis/warcraft/infobox_person_player_custom.lua
Create an Infobox Player for WC.
Requires swapping the Birth Date to iso rather than Template call at golive.
Edit: Race location is now out date in images below, it's further up.
=> Create infobox player for Warcraft

components/infobox/wikis/heroes/infobox_person_player_custom.lua
Create Infobox Player on HotS 
Put live
=> Create Infobox Player on HotS

components/infobox/wikis/pubg/infobox_person_player_custom.lua
Create an infobox player for PUBG.
Needs birthday botting when going live.
=> Create Player infobox for PUBG

components/infobox/wikis/fifa/infobox_person_player_custom.lua
=> Create infobox player for FIFA

components/infobox/wikis/simracing/infobox_person_player_custom.lua
Infobox Player for Simracing
Using Template:Game/... since the wiki does not have a complete Module:Info yet.
Live
=> Create Player Infobox for Simracing

components/infobox/wikis/trackmania/infobox_person_player_custom.lua
Player Infobox for Trackmania
Live
=> Create Infobox Player for Trackmania

components/infobox/wikis/callofduty/infobox_person_player_custom.lua
Create Player Infobox for CoD. It's a cleaned up version of what's been live for 5 months without being on git.
Live.
=> Create Infobox Player for CoD

components/infobox/wikis/hearthstone/infobox_person_player_custom.lua
Create Player Infobox for Hearthstone
Live
=> Create Infobox Player for Hearthstone

components/infobox/wikis/clashroyale/infobox_person_player_custom.lua
Cleaned up version of what's been lived for 2 months without being pushed to git.
Live
=> Create CR Infobox Player

components/infobox/wikis/warcraft/infobox_person_player_custom.lua
Adjust WC player infobox to show race in header instead of team
dev
=> Adjust WC player infobox to show race in header instead of team

standard/timezone_data.lua
Needed due to usage on CS wiki now.
Just data so I didn't.
=> Add Alaskan Timezones to data

components/earnings/wikis/smash/earnings.lua, components/infobox/wikis/smash/infobox_person_player_custom.lua, standard/links/commons/links.lua
Create infobox player for Smash
Current:
New:
Preview testing and verified LPDB storage
=> Create Infobox Player for Smash

components/infobox/wikis/ageofempires/infobox_person_player_custom.lua
Create Infobox Player for Age of Empries.
Mostly preview testing and some LPDB checking
=> Infobox player for AoE

components/infobox/wikis/callofduty/infobox_league.lua
Infobox league for CoD. It's a cleaned up and significantly simplified version of what's been live for 6+ months.
Live
=> Create Infobox League for CoD

components/infobox/wikis/starcraft/infobox_person_player_custom.lua
only merge after #2454
Clean up BW infobox player race stuff
dev
=> Clean up BW infobox player race stuff

components/infobox/wikis/clashroyale/infobox_league_custom.lua
Cleaned up version what's been live on Clash Royale for a few months
Live
=> Create Clash Royale League Infobox

components/infobox/wikis/freefire/infobox_league_custom.lua
League Infobox fore FreeFire
Preview
=> Create Infobox League for FreeFire

components/infobox/wikis/fortnite/infobox_league_custom.lua
Create Infobox League for Fortnite. Cleaned up version what's currently live.
Live
=> Create League Infobox for Fortnite

components/infobox/wikis/simracing/infobox_league_custom.lua
Create League Infobox for Simracing
Live
=> Create Infobox League for Simracing

components/infobox/wikis/fifa/infobox_league_custom.lua
Create League Infobox for FIFA
Pushed live
=> Create League Infobox for FIFA

components/infobox/wikis/criticalops/infobox_league_custom.lua
Cleaned up version of what was live.
Live
=> Infobox League Critical Ops

components/infobox/wikis/squadrons/infobox_league_custom.lua
Infobox League for Squadrons
Put live
=> Create Infobox League for Squadrons

components/infobox/wikis/arenafps/infobox_league_custom.lua, standard/links/commons/links.lua
Create League Infobox for ArenaFPS
Preview testing
=> Create League Infobox for ArenaFPS

components/infobox/wikis/magic/infobox_league_custom.lua, standard/info/wikis/magic/info.lua
Create Infobox League for MTG
Pushed Live
=> Infobox Leauge for Magic

components/infobox/wikis/hearthstone/infobox_league_custom.lua
Create League Infobox for Hearthstone
Pushed Live
=> Create Infobox League for HS

components/infobox/wikis/heroes/infobox_league_custom.lua
HotS wanted a few custom things. `bgX` which is basically `mapX` seen on many other wikis. Also they want automatically retrieve Logo and Displayname for Server Input
Live
=> Custom handling for HotS's Infobox League

standard/info/wikis/brawlhalla/info.lua, standard/info/wikis/crossfire/info.lua, standard/info/wikis/fighters/info.lua, standard/info/wikis/hearthstone/info.lua, standard/info/wikis/simracing/info.lua, standard/info/wikis/splatoon/info.lua, standard/info/wikis/teamfortress/info.lua
Add remaining Module:Info game data
N/A copy from the wikis (there uopdated by community team)
=> Add more Module:Info game data

standard/info/wikis/mobilelegends/info.lua
=> Hot fix ML info module

components/opponent/wikis/trackmania/opponent_display_custom.lua
Fix TM OpponentDisplay with calling a Class.new on BracketOpponentEntry before adjusting it
live, hotfix
=> Fix TM OpponentDisplay

components/infobox/wikis/starcraft/infobox_person_player_custom.lua, components/infobox/wikis/starcraft2/infobox_person_player_custom.lua, components/match2/commons/match_ticker/match_ticker_query.lua, components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Store pagenames with underscores in sc/sc2 match2
dev
=> Store pagenames with underscores in sc/sc2 match2

standard/info/wikis/fifa/info.lua
All missing games based on deprecated Module:Games
included the '24 Game (with supposing name) just in case
=> Add all missing games for FIFA Info

components/prize_pool/commons/prize_pool_import.lua, components/prize_pool/commons/prize_pool_placement.lua
Adjust count handling
- calculate count and placeStart/end independently if both is supplied so that slot size (count) can differ from the displayed range
if i understood you correctly that is what you wanted, right? @iMarbot 
dev (incl. storage tests)
=> Adjust count handling

components/infobox/wikis/starcraft2/infobox_league_custom.lua, components/results_table/wikis/starcraft2/results_table_custom.lua
Adjust CSS Class to standard in 2 SC2 modules
live
=> Adjust CSS Class to standard in 2 SC2 modules

components/infobox/wikis/fighters/infobox_league_custom.lua
Create Infobox League for Fighters.
The game field won't work until #2459 is finished for Fighters.
Preview testing
=> Infobox league for fighters

components/match2/wikis/halo/match_summary.lua
Comparison at https://discord.com/channels/93055209017729024/882959691523690536/1077749685491609670  screen capped from https://liquipedia.net/commons/User:OxWeaselDee/IconTest with manual CSS changes in browser's inspect to show darkmode.
=> Change icon for Halo's H2H

components/match2/wikis/halo/match_summary.lua
forgot "File:" in pr #2637
https://liquipedia.net/halo/index.php?title=Module%3AMatchSummary&type=revision&diff=30767&oldid=30746
=> Fix missing File-Prefix in halo matchsummary

components/match2/commons/match_ticker/match_ticker_query.lua
Add more query options to matchTicker Query
dev
=> Add more query options to matchTicker Query

components/infobox/wikis/ageofempires/infobox_league_custom.lua
=> Chore: change table access to dot instead of brackets

standard/lpdb/condition.lua, standard/lpdb/condition_test.lua
Allow passing nil in `:add` in condition building
dev
=> Support `nil` input as a `noop` in Condition Builder

components/broadcaster_card/commons/broadcaster_card.lua
Reduce necessary usage of `title` parameter for types of positions
Tested on copy of module
=> Pluralise multiple broadcaster positions

standard/info/wikis/apexlegends/info.lua
Resolves #2497
@hjpalpha I didn't open a pull request because I was unsure which file to use, but this is a high res image of the icon
https://liquipedia.net/commons/File:Apex-legends-icon.png
=> Module:Info - Fix Low Res image Apex Legends

components/results_table/commons/results_table.lua, components/results_table/commons/results_table_base.lua
Add alias support to ResultsTable
Needed e.g. on Simracing.
Where they have the same "Team" competing several times in the same event with different TTs.
Requested by @Hesketh2 
dev
=> Add alias support to ResultsTable

components/prize_pool/commons/prize_pool_base.lua
Fix typos in abstract functions
n/a
=> Fix typos in abstract functions

components/notability/wikis/brawlstars/notability_checker_config.lua
Helped fix issues with the old checker a while back for brawlstars, the standardised version has been up and running for a while now.
Committing now that the contributors I've spoken to seem happy with the implementation.
=> Brawlstars: Create config for Notability Checker

components/prize_pool/prize_pool_award_placement.lua
Add PPT Award placement module
new module
tested via direct invoke on some pages on 3 different wikis
=> Add PPT Award Placement module

components/infobox/wikis/counterstrike/infobox_league_custom.lua, components/infobox/wikis/starcraft/infobox_league_custom.lua, components/infobox/wikis/starcraft/infobox_series_custom.lua, components/infobox/wikis/starcraft/infobox_team_custom.lua, components/match2/commons/match_group_legacy.lua, components/match2/wikis/rainbowsix/legacy/match_maps_legacy_store.lua, components/match2/wikis/starcraft/legacy/match_group_legacy.lua, components/match2/wikis/starcraft/legacy/match_maps_legacy.lua, components/prize_pool/wikis/counterstrike/prize_pool_custom.lua, components/standings/commons/standings_storage.lua
Update disable storage wiki var according to bot runs
N/A
=> Remove deprecated `disable_SMW_storage`

components/infobox/wikis/dota2/infobox_league_custom.lua, components/infobox/wikis/dota2/infobox_team_custom.lua, components/match2/wikis/dota2/match_summary.lua, standard/links/commons/links.lua
player and match links to stratz.com were outdated (though redirects on stratz.com are maintained); links to league and team pages were missing.
i did not test this change, i didn't find any documents that describe how to view/test changes.
=> update stratz links

standard/tier/commons/tier_utils.lua
Improve `Tier.toNumber`
- remove spaces to catch more cases
- return input if input is already numeric
dev
=> Improve `Tier.toNumber`

components/notability/wikis/brawlstars/notability_checker_config.lua
I changed the values for testing purposes and forgot to return them to the correct values.
=> Correcting Player Limits for Brawlstars Notability

components/prize_pool/prize_pool_award.lua, components/prize_pool/prize_pool_award_placement.lua
Add PPT Award module
new module
tested via direct invoke on some pages on 3 different wikis
=> Create Awards component

components/prize_pool/commons/prize_pool_custom.lua
Create a Basic Custom PPT for Commons
Live on all Dormant Wikis (Paladins, Artifact etc)
=> Create Default PPT Custom

standard/tier/wikis/starcraft2/tier_custom.lua, standard/tier/wikis/starcraft2/tier_data.lua
Add sc2 tier data and custom
with not yet used modules that are currently still in building
=> Add sc2 tier data and custom

standard/tier/wikis/warcraft/tier_custom.lua
Add warcraft `Module:Tier/Custom`
together with dev of #2680 - #2683
=> Add warcraft `Module:Tier/Custom`

standard/tier/wikis/rocketleague/tier_custom.lua
Add RL tier custom
new module, together with infobox league devs
=> Add RL tier custom

components/infobox/wikis/fighters/infobox_league_custom.lua
Save abbreviated name in lpdb. Use normalized name for categories and display.
Set type to offline if not defined.
Correct custom var "tournament_circuit" to "circuit".
Tested in dev
=> Update Infobox League for fighters

standard/info/wikis/tetris/info.lua
Requested by the editors, all games have icons uploaded already.
- Blockbox
- Tetris Friends
- Tetris Online Japan
- NullpoMino
- Cultris 2
- TetriNET2
- Tetris Online Poland
=> Add new Games to Tetris Info

components/prize_pool/commons/prize_pool_base.lua, components/prize_pool/test/prize_pool_test.lua, standard/mock/mock_lpdb.lua
Resolves #2641
/dev on a [test page](https://liquipedia.net/ageofempires/User:SyntacticSalt/PrizePool) and using testcases
=> Follow value of `disable_LPDB_storage` in prize pool

components/squad/commons/squad_row.lua
Let's keep only extradata customizable (which it is through another function)
Dev module
=> Remove unused/unneeded function in SquadRow

standard/info/wikis/fighters/info.lua
Changed capitalization of titles
No effect. Game links match page names.
=> Correct game names in info.lua for fighters

standard/info/wikis/tft/info.lua
Updated logos
1. LOGO: both lightmode and darkmode
2. Double Up: both lightmode and darkmode
=> Update logos for TFT

components/prize_pool/commons/prize_pool_award_custom.lua, components/prize_pool/commons/starcraft_starcraft2/prize_pool_award_starcraft.lua, components/prize_pool/wikis/ageofempires/prize_pool_award_custom.lua, components/prize_pool/wikis/counterstrike/prize_pool_award_custom.lua, components/prize_pool/wikis/dota2/prize_pool_award_custom.lua, components/prize_pool/wikis/pubg/prize_pool_award_custom.lua, components/prize_pool/wikis/pubgmobile/prize_pool_award_custom.lua, components/prize_pool/wikis/starcraft/prize_pool_award_custom.lua, components/prize_pool/wikis/starcraft2/prize_pool_award_custom.lua
Add Award PPT Customs
- sc/bw redirects
- sc/bw custom on commons
- default custom on commons
new modules so live together with preview and storage tests on existing (smaller) tournament pages
=> Create Award PPT Customs

components/infobox/wikis/valorant/infobox_person_player_custom.lua
Added support for PlayerTeamAuto, additionally changed the storing to be lowercase alongside updating the PlayerIntroduction modules/tempaltes
https://liquipedia.net/valorant/Module:Infobox/Person/Player/Custom/dev
https://liquipedia.net/valorant/Carlee
=> Add support for PlayerTeamAuto to VALORANT

components/prize_pool/commons/prize_pool_legacy.lua, components/prize_pool/commons/starcraft_starcraft2/prize_pool_legacy_starcraft.lua
depends on #2692
Adjust PPT Legacy modules on commons
- `Module:PrizePool/Legacy`: Adjust for accepting award instead of place
- `Module:PrizePool/Legacy/Starcraft`: Adjust for accepting award instead of place
Note that no customs for PPT Award Legacy conversion are needed since except sc/sc2 no variations are necessary for any wiki.
For sc/sc2 those are already caught via the sc/sc2 legacy for "normal" PPTs
dev
=> Adjust PPT Legacy modules on commons

components/prize_pool/wikis/fortnite/prize_pool_legacy_custom.lua
Add fortnite PPT Legacy Custom
needed due to legacy duo, trio, quad prize pools
dev
=> Add fortnite PPT Legacy Custom

standard/tier/wikis/counterstrike/tier_custom.lua, standard/tier/wikis/counterstrike/tier_data.lua
Adjust CS Tier display in case of both tiers present
- add "prio" values to tierTypes in data
- add custom to adjust the tier display
dev
=> Adjust CS Tier display in case of both tiers present

components/infobox/wikis/warcraft/infobox_league_custom.lua
Fix typo in wc3 infobox league
live
=> Fix spelling in wc3 infobox league

components/prize_pool/commons/prize_pool_award_custom.lua, components/prize_pool/commons/starcraft_starcraft2/prize_pool_award_starcraft.lua
Pass `true` in `:build` for awards ppt so that the first column has `Award` as header instead of `Place`
live
=> Pass `true` in `:build` for awards ppt

components/prize_pool/wikis/fortnite/prize_pool_legacy_custom.lua
Sync players for fortnite legacy sicne their old ppt could do it
live
=> Sync players for fortnite legacy

components/infobox/commons/infobox_basic.lua, components/infobox/commons/infobox_league.lua, components/infobox/commons/infobox_series.lua, components/infobox/commons/infobox_unofficial_world_champion.lua, components/infobox/wikis/halo/infobox_league_custom.lua
Generic refactoring, mostly where `while` loops can be replaced with better methods (getForBase or pairByPrefix).
Remove organizer-ref field because it was unused.
dev module
=> Refactoring loops in Infobox

standard/info/wikis/zula/info.lua
=> Fix startYear typo on Zula

standard/info/wikis/fighters/info.lua
Fixed capitalization of game name
Fixed broken logo link
=> Update Guilty Gear Xrd REV 2 name & logo

components/prize_pool/wikis/ageofempires/prize_pool_award_custom.lua, components/prize_pool/wikis/counterstrike/prize_pool_award_custom.lua, components/prize_pool/wikis/dota2/prize_pool_award_custom.lua, components/prize_pool/wikis/fortnite/prize_pool_award_custom.lua, components/prize_pool/wikis/fortnite/prize_pool_custom.lua, components/prize_pool/wikis/pubg/prize_pool_award_custom.lua, components/prize_pool/wikis/pubgmobile/prize_pool_award_custom.lua
Fix some award ppt customs and add fortnite customs
N/A, bug fixes
- for the custom adjusts the samne as #2723
- for the fortnite ones: copy pase from commons with the addition of adding the currency fallback
=> Fix some award ppt customs and add fortnite customs

components/prize_pool/wikis/fortnite/prize_pool_legacy_custom.lua
Also retrieve currency from var in legacy conversion on fortnite
dev to live
=> Also retrieve currency from var in legacy conversion on fortnite

standard/tier/wikis/ageofempires/tier_custom.lua, standard/tier/wikis/ageofempires/tier_data.lua
Adds AoE custom tier modules including game links
tested with dev versions of ResultsTable, Infobox league
=> Add AoE Tier data, custom

components/prize_pool/commons/prize_pool_award.lua
Add the award (name) to objectname in PPT Award
/dev
=> Add the award (name) to objectname in PPT Award

components/earnings/wikis/fortnite/earnings.lua
Add fortnite earnings custom
needed since currently the earnings on player pages are plain wrong
live
=> Add fortnite earnings custom

components/infobox/wikis/tft/infobox_league_custom.lua
Add default mode in tft infobox league
as per request https://discord.com/channels/93055209017729024/1086210455829237760/1086210455829237760
dev
=> Add default mode in tft infobox league

standard/info/wikis/apexlegends/info.lua
=> Fixing the dark/lightmode image files

components/broadcaster_card/commons/broadcaster_card.lua
Adjust sorting option in BroadcasterCard
dev
=> Adjust sorting option in BroadcasterCard

components/hidden_data_box/commons/hidden_data_box.lua, components/hidden_data_box/wikis/ageofempires/hidden_data_box_custom.lua, components/hidden_data_box/wikis/counterstrike/hidden_data_box_custom.lua, components/hidden_data_box/wikis/valorant/hidden_data_box_custom.lua
Use Tier library in HDB
dev, to be done
=> Use Tier library in HiddenDataBox

standard/tier/wikis/starcraft/tier_data.lua, standard/tier/wikis/starcraft2/tier_data.lua
Fix typos in sc/sc2 tier data
live
=> Fix typos in sc/sc2 tier data

components/results_table/commons/results_table_award.lua
Use correct var name in building the heaader of Awards tables
dev to live
=> Fix Header in Awards Table

standard/info/wikis/artifact/info.lua
Typo in Module Info for Artifact
Live
=> Fix Artifact's Info data

components/squad/commons/squad_custom.lua
Create a Custom on Commons that can be used by most wikis.
It Supports both manual and automatic tables
Live on Zula (previously using a non-git commited custom)
=> Create basic Commons Custom for Squad

standard/info/wikis/battalion/info.lua
Typo in Battalion's info module
Live
=> Fix Battalion's Info Module

components/infobox/wikis/brawlstars/infobox_league_custom.lua
- add support for ESL and FACEIT
- make it indifferent to casing
- add darkmode support for supercell icon
- outsource it to function instead of calling the table directly
dev
=> Adjust Brawlstars organizer icon handling

components/squad/wikis/warcraft/squad_custom.lua
Create Squad Custom for Warcraft, in order to have support for Faction Icon
=> Create Squad Custom for Warcraft

components/infobox/wikis/brawlstars/infobox_league_custom.lua
fix typo `.png.png` —> `.png`
live
=> Fix wrong file names in brawlstars infobox league

components/squad/commons/squad_row.lua, components/squad/wikis/smash/squad_custom.lua
Adds new way to display real name
Preview
=> Create Squad Custom for Smash

components/results_table/commons/results_table_base.lua
Do not use alias check for lastVs in Results tables
dev
=> Do not use alias check for lastVs in Results tables

components/misc/want_to_help_list.lua
Create a unified, standard version of Want to Help List
Live on wikis using Module:WantToHelpList
=> Create Standardized Want to Help List

components/infobox/wikis/warcraft/infobox_league_custom.lua
Adjust participantsnumber handling in wc infobox league
as per requests by wc contrib.
dev
=> Adjust participantsnumber handling in wc infobox league

components/hidden_data_box/wikis/splatoon/hidden_data_box_custom.lua
Slimmed down version of what's been 
Live
=> Create HDB for Splatoon

components/hidden_data_box/wikis/pokemon/hidden_data_box_custom.lua
Slimmed down version of what's been live long
Live
=> Create HDB for Pokemon

components/hidden_data_box/wikis/teamfortress/hidden_data_box_custom.lua
Created a HDB for Team Fortress
Live
=> Create HDB for TF

components/hidden_data_box/wikis/hearthstone/hidden_data_box_custom.lua
Create HiddenDataBox for Hearthstone
Put live
=> Create HDB for Hearthstone

components/hidden_data_box/wikis/squadrons/hidden_data_box_custom.lua
Create HiddenDataBox for Hearthstone
Put live
=> Create HDB custom for Squadrons

components/hidden_data_box/wikis/simracing/hidden_data_box_custom.lua
Create HiddenDataBox for Simracing
Put live
=> Create HDB for Simracing

components/hidden_data_box/wikis/freefire/hidden_data_box_custom.lua
Create HiddenDataBox for Freefire
Put live
=> Create HDB for Freefire

components/hidden_data_box/wikis/pubg/hidden_data_box_custom.lua, components/infobox/wikis/pubg/infobox_league_custom.lua
Create HiddenDataBox for PUBG. Removed a now unused legacy wiki variable from the Infobox Leageu
Put live
=> Create HDB for PUBG

components/infobox/commons/infobox_league.lua
Fix venue display for (wikipedia) interwiki links
dev
=> Fix venue display for (wikipedia) interwiki links

components/results_table/commons/results_table_award.lua, components/results_table/commons/results_table_base.lua
- Make use of `Module:HighlightConditions` in results tables
- also highlight in awards tables
dev
=> Adjust highlighting in results and awards tables

components/external_media_links/external_media_link.lua
Fix `by_linkX` in display in externalmedialink
dev to live since bug fix
=> Fix `by_linkX` in display in externalmedialink

components/infobox/wikis/starcraft2/infobox_building_custom.lua
Fix filenames in sc2 infobox building
live
=> Fix filenames in sc2 infobox building

components/infobox/wikis/warcraft/infobox_league_custom.lua
Fix warcraft infobox league mode category handling
live, hotfix
=> Fix warcraft infobox league mode category handling

standard/info/wikis/tetris/info.lua
=> Name adjustments in Tetris Info Module

components/prize_pool/commons/prize_pool_base.lua, components/team_card/team_card_storage.lua
Stores a placement's date in a variable and retrieves it in the teamcard.
via /dev
=> Save placement date to variable to be retrieved in TeamCards

components/prize_pool/commons/prize_pool_base.lua, components/prize_pool/commons/starcraft_starcraft2/prize_pool_award_starcraft.lua, components/prize_pool/commons/starcraft_starcraft2/prize_pool_starcraft.lua, components/prize_pool/wikis/apexlegends/prize_pool_custom.lua, components/prize_pool/wikis/mobilelegends/prize_pool_custom.lua, components/prize_pool/wikis/pokemon/prize_pool_custom.lua
Add `publishertier` default storage on prize pools
dev
=> Add `publishertier` default storage on prize pools

components/results_table/commons/results_table_base.lua
Apply sortbottom to tr instead of th so it actually works
dev
=> Fix sortbottom in resultstables

components/infobox/commons/infobox_league.lua, components/infobox/commons/infobox_person.lua, components/infobox/commons/infobox_series.lua, components/infobox/commons/infobox_team.lua
resolves #2774 
Respect `disable_LPDB_storage` wiki var in core infoboxes
dev
=> Respect `disable_LPDB_storage` wiki var in core infoboxes

standard/info/wikis/fighters/info.lua
Adjust SF6 icon in info module
N/A, just data change
=> Adjust SF6 icon in info module

standard/info/wikis/fighters/info.lua
Adjust various logos/icons in fighters info module
N/A only data adjust
=> Updated various logos/icons within Info

standard/league_icon.lua
Improve include size in LeagueIcon if icon == iconDark
dev
=> Improve include size in LeagueIcon

components/results_table/commons/results_table.lua, components/results_table/commons/results_table_award.lua
depends on #2879 
Adjust currency display in results/awards table from `'$' .. Currency.formatMoney` to `Currency.display`
dev
=> Adjust currency display in results/awards table

components/results_table/wikis/counterstrike/results_table_custom.lua
Needed to change how Tiers are rendered.
`/dev` on cs wiki.
=> Add initial custom for CS Results Table

standard/tournaments_summary_table/wikis/heroes/tournaments_summary_table_custom.lua
Replaces old SMW template
live
=> Add TournamentsSummaryTable/Custom for heroes

components/prize_pool/commons/prize_pool_base.lua
resolves #2821 
Adjust name display for qualifier fields in ppt
dev (preview tests)
=> Adjust name display for qualifier fields in ppt

components/infobox/wikis/overwatch/infobox_person_player_custom.lua
Adds support for manual entry for National Team participation above a new forced addition of Team History Auto 
currently live via dev module
=> Add National Teams to players for OW

components/prize_pool/wikis/overwatch/prize_pool_custom.lua
Adjust OW PPT Weight function as per request by editors.
Multiply Qualifiers with `0.001`
dev
=> Adjust OW PPT Weight function

components/match2/wikis/leagueoflegends/big_match_template.lua
Missed a **commit** to fix the display for the second team in addition to the first team.
Live
=> Forgot to update team2 in #2899

components/match2/wikis/leagueoflegends/match_links.lua
Update the copytext for reddit
Dev
=> League M2: Update Copytext for Reddit

components/infobox/commons/infobox_league.lua
Add tracking category for locationless tournaments
Commons alternative for #2888 
/dev
=> Add tracking category for locationless tournaments

components/infobox/wikis/leagueoflegends/infobox_league_custom.lua
Adds what patch the League was played on in the League of Legends Infobox 
Currently testing live via dev module [here](https://liquipedia.net/leagueoflegends/Keysie_Streamers_Invitational/2)
=> Adding Patches to League League

components/match2/wikis/leagueoflegends/big_match.lua
Updated to PM's request
Put it live and checked the affected tournaments, Popup showed correctly
=> League BM: Update values for enablement

components/earnings/commons/earnings_legacy.lua, standard/date_ext.lua, standard/table.lua
Fix a few annotation warnings i got in VSCode
N/A
=> Fix a few annotation warnings

components/match2/wikis/leagueoflegends/match_summary.lua
Pass along date to game rows in lol MS
=> Pass along date to game rows in lol MS

components/match2/wikis/leagueoflegends/big_match.lua
Set wiki variables that are expected by match2 on a BigMatch page
Dev module
=> Invoke HDB from LOL BM

components/squad/wikis/apexlegends/squad_custom.lua, components/squad/wikis/counterstrike/squad_custom.lua, components/squad/wikis/dota2/squad_custom.lua, components/squad/wikis/rocketleague/squad_custom.lua, components/squad/wikis/valorant/squad_custom.lua
This wiki variable is never set on any wiki. Remove it as it's completely unneeded.
Tested on Rocket League
=> Remove unused wiki variable

components/squad/commons/squad_row.lua, components/squad/wikis/apexlegends/squad_custom.lua, components/squad/wikis/arenaofvalor/squad_custom.lua, components/squad/wikis/counterstrike/squad_custom.lua, components/squad/wikis/dota2/squad_custom.lua, components/squad/wikis/halo/squad_custom.lua, components/squad/wikis/leagueoflegends/squad_custom.lua, components/squad/wikis/mobilelegends/squad_custom.lua, components/squad/wikis/overwatch/squad_custom.lua, components/squad/wikis/rainbowsix/squad_custom.lua, components/squad/wikis/rocketleague/squad_custom.lua, components/squad/wikis/smash/squad_custom.lua, components/squad/wikis/starcraft/squad_custom.lua, components/squad/wikis/starcraft2/squad_custom.lua, components/squad/wikis/valorant/squad_custom.lua, components/squad/wikis/warcraft/squad_custom.lua, components/squad/wikis/wildrift/squad_custom.lua
`status` was just added as a field in LPDB. Store the status into this field. 
For reviewing: start with commons before checking wiki customs.
Tested on Rocket League
=> Store SquadPlayer Status in LPDB

components/match2/wikis/starcraft2/legacy/match_maps_legacy.lua
Adjust handling of empty/unset maps to be consistent with non legacy version
dev to live
=> Adjust sc2 matchMaps/Legacy

components/broadcast_talent_table/commons/broadcast_talent_table.lua, definitions/mw.lua
Fix some annotations to shut up vsCode
N/A
=> Fix some annotations

components/squad/commons/squad_custom.lua
In #2938, Commons Custom was missed.
Live
=> Add status storage to commons custom

standard/highlight_conditions/wikis/dota2/highlight_conditions.lua
Adjust dota2 highlights conditions
live
=> Adjust dota2 highlights conditions

components/tournaments_listing/commons/tournaments_listing_conditions.lua
=> Add missing ipairs

components/earnings/commons/earnings_base.lua, components/earnings/wikis/halo/earnings.lua, components/earnings/wikis/rocketleague/earnings.lua, components/earnings/wikis/valorant/earnings.lua, components/squad/commons/squad.lua, components/squad/commons/squad_custom.lua, components/squad/commons/squad_row.lua, components/squad/test/squad_test.lua, components/squad/wikis/apexlegends/squad_custom.lua, components/squad/wikis/arenaofvalor/squad_custom.lua, components/squad/wikis/counterstrike/squad_custom.lua, components/squad/wikis/dota2/squad_custom.lua, components/squad/wikis/mobilelegends/squad_custom.lua, components/squad/wikis/overwatch/squad_custom.lua, components/squad/wikis/rocketleague/squad_custom.lua, components/squad/wikis/smash/squad_custom.lua, components/squad/wikis/starcraft/squad_custom.lua, components/squad/wikis/starcraft2/squad_custom.lua, components/squad/wikis/valorant/squad_custom.lua, components/squad/wikis/warcraft/squad_custom.lua, components/squad/wikis/wildrift/squad_custom.lua, standard/info/wikis/counterstrike/info.lua, standard/info/wikis/pokemon/info.lua, standard/info/wikis/tetris/info.lua
Various code style fixes in Earnings, Squad and Info components.
N/A white space changes only
=> Fix code style in Earnings, Squad and Info

components/infobox/wikis/ageofempires/infobox_person_player_custom.lua, components/infobox/wikis/ageofempires/infobox_team_custom.lua, components/match2/wikis/leagueoflegends/match_group_input_custom.lua, components/match2/wikis/mobilelegends/match_group_input_custom.lua, components/match2/wikis/rainbowsix/match_group_input_custom.lua, components/match2/wikis/rocketleague/match_group_input_custom.lua, components/match2/wikis/wildrift/match_group_input_custom.lua, components/prize_pool/wikis/warcraft/prize_pool_legacy_custom.lua
stacked on #2956
Fix some more annotation warnings
for the `Module:MatchGroup/Input/Custom` cases in dev, rest N/A
=> Fix some more annotation warnings

components/infobox/commons/infobox_widget_links.lua, standard/links/commons/links.lua
Move some functionality from `Module:Infobox/Widget/Links` to `Module:Links` so that it can be used in other modules.
dev
=> Move some functionality from `Module:Infobox/Widget/Links` to `Module:Links`

components/hidden_data_box/commons/hidden_data_box.lua, components/hidden_data_box/commons/hidden_data_box_custom.lua, components/hidden_data_box/wikis/ageofempires/hidden_data_box_custom.lua, components/hidden_data_box/wikis/apexlegends/hidden_data_box_custom.lua, components/hidden_data_box/wikis/arenaofvalor/hidden_data_box_custom.lua, components/hidden_data_box/wikis/brawlstars/hidden_data_box_custom.lua, components/hidden_data_box/wikis/counterstrike/hidden_data_box_custom.lua, components/hidden_data_box/wikis/dota2/hidden_data_box_custom.lua, components/hidden_data_box/wikis/freefire/hidden_data_box_custom.lua, components/hidden_data_box/wikis/halo/hidden_data_box_custom.lua, components/hidden_data_box/wikis/hearthstone/hidden_data_box_custom.lua, components/hidden_data_box/wikis/leagueoflegends/hidden_data_box_custom.lua, components/hidden_data_box/wikis/mobilelegends/hidden_data_box_custom.lua, components/hidden_data_box/wikis/overwatch/hidden_data_box_custom.lua, components/hidden_data_box/wikis/pokemon/hidden_data_box_custom.lua, components/hidden_data_box/wikis/pubg/hidden_data_box_custom.lua, components/hidden_data_box/wikis/pubgmobile/hidden_data_box_custom.lua, components/hidden_data_box/wikis/rainbowsix/hidden_data_box_custom.lua, components/hidden_data_box/wikis/rocketleague/hidden_data_box_custom.lua, components/hidden_data_box/wikis/simracing/hidden_data_box_custom.lua, components/hidden_data_box/wikis/splatoon/hidden_data_box_custom.lua, components/hidden_data_box/wikis/squadrons/hidden_data_box_custom.lua, components/hidden_data_box/wikis/starcraft/hidden_data_box_custom.lua, components/hidden_data_box/wikis/starcraft2/hidden_data_box_custom.lua, components/hidden_data_box/wikis/teamfortress/hidden_data_box_custom.lua, components/hidden_data_box/wikis/trackmania/hidden_data_box_custom.lua, components/hidden_data_box/wikis/valorant/hidden_data_box_custom.lua, components/hidden_data_box/wikis/warcraft/hidden_data_box_custom.lua, components/hidden_data_box/wikis/wildrift/hidden_data_box_custom.lua
Add annotations for HiddenDataBox
N/A
=> Add annotations for HiddenDataBox

components/mvp_table/commons/mvp_table.lua
Add annotations for `Module:MvpTable`
N/A
=> Add annotations for `Module:MvpTable`

components/external_media_links/external_media_link.lua, components/external_media_links/external_media_list.lua
Add annotations for `components/external_media_links/*`
N/A
=> Add annotations for `components/external_media_links/*`

components/broadcast_talent_table/commons/broadcast_talent_table.lua, components/broadcaster_card/commons/broadcaster_card.lua
Add annotations to broadcaster stuff
N/A
=> Add annotations to broadcaster stuff

standard/locale.lua, standard/reference_cleaner.lua
Add annotations for locale.lua and reference_cleaner.lua
N/A
=> Add annotations for `locale.lua` and `reference_cleaner.lua`

standard/logic.lua
Add annotations to logic.lua
N/A
=> Add annotations to `logic.lua`

standard/timezone.lua
Add annotations for timezone.lua
N/A
=> Add annotations for `timezone.lua`

standard/vod_link.lua, standard/warning_box.lua
Add annotations for vodLink and warningBox
N/A
=> Add annotations for `vod_link.lua` and `warning_box.lua`

components/infobox/wikis/dota2/infobox_league_custom.lua, definitions/mw.lua, standard/template.lua
Add annotations for template.lua
And fix anno warnings in files using this file
N/A
=> Add annotations for `template.lua`

standard/links/commons/links.lua
Add annotations to links modules
N/A
=> Add annotations to `links.lua`

standard/region/commons/region.lua, standard/region/extensions/ept.lua
Add annotations for region.lua and ept.lua
N/A
=> Add annotations for `region.lua` and `ept.lua`

standard/league_icon.lua
Add annotations to league_icon.lua
N/A
=> Add annotations to `league_icon.lua`

components/team_card/team_card_storage.lua
Add annotations for `Module:TeamCard/Storage`
N/A
=> Add annotations for `Module:TeamCard/Storage`

components/infobox/wikis/ageofempires/infobox_series_custom.lua, components/infobox/wikis/fortnite/infobox_series_custom.lua, components/infobox/wikis/rocketleague/infobox_series_custom.lua, components/infobox/wikis/warcraft/infobox_series_custom.lua, components/match2/wikis/starcraft/legacy/match_group_legacy_default.lua, standard/lua.lua
Add annotations for lua.lua
And resolve any remaining annotation warnings in files that use `Module:Lua`
N/A
=> Add annotations for `lua.lua`

components/standings/commons/starcraft_starcraft2/standings_storage_starcraft_legacy.lua, components/team_card/team_card_storage.lua
Add annotations to `Module:Standings/Storage/StarcraftLegacy`
N/A
=> Add annotations to `Module:Standings/Storage/StarcraftLegacy`

standard/links_stream.lua
Add annotations to links_stream.lua
N/A
=> Add annotations to `links_stream.lua`

components/tournaments_listing/commons/tournaments_listing_card_list.lua, components/tournaments_listing/commons/tournaments_listing_card_list_custom.lua, components/tournaments_listing/commons/tournaments_listing_conditions.lua, components/tournaments_listing/wikis/starcraft2/tournaments_listing_card_list_custom.lua
Add annotations to `components/tournaments_listing/*`
N/A
=> Add annotations to `components/tournaments_listing/*`

standard/lpdb/condition.lua
Add annotations for conditions module
N/A
=> Add annotations for `conditions.lua`

components/infobox/wikis/fighters/infobox_league_custom.lua, standard/abbreviation.lua, standard/array_ext.lua, standard/error.lua, standard/error_display.lua, standard/error_ext.lua, standard/feature_flag.lua, standard/flags.lua, standard/format_table.lua, standard/hidden_sort.lua, standard/hotkey.lua, standard/json.lua, standard/tournament_structure.lua
Some more annotations and fixes for anno warnings
N/A so far
=> Annotatate various libraries

plugins/sumneko_plugin.lua
Silence some annotation warnings in the plugin file
Annotations from https://github.com/LuaLS/lua-language-server/wiki/Plugins#functions
N/A
=> Silence some annotation warnings in the plugin file

components/infobox/commons/infobox_widget.lua, components/widget/widget_table.lua, components/widget/widget_table_cell.lua, components/widget/widget_table_row.lua
Add annotations for `components/widget/*`
N/A
=> Add annotations for `components/widget/*`

standard/array.lua
Fix some array annotations
N/A
=> Fix some array annotations

components/external_media_links/external_media_list.lua, standard/logic.lua, standard/lpdb/condition.lua
=> Fix a few annotations

components/portal_players/commons/portal_players.lua, components/portal_players/wikis/fifa/portal_players_custom.lua, components/portal_players/wikis/smash/portal_players_custom.lua
Fix portal player customs
Apparently forgot to adjust them when reworking some stuff in the commons one.
live since bug fix before role out
=> Fix portal player customs

components/infobox/commons/infobox_person.lua, components/infobox/wikis/ageofempires/infobox_person_player_custom.lua, components/infobox/wikis/fortnite/infobox_person_player_custom.lua, components/infobox/wikis/halo/infobox_person_player_custom.lua, components/infobox/wikis/halo/infobox_team_custom.lua, components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua, components/infobox/wikis/pokemon/infobox_person_player_custom.lua, components/infobox/wikis/splatoon/infobox_person_player_custom.lua, components/tournaments_listing/commons/tournaments_listing_card_list.lua, standard/locale.lua, standard/region/commons/region.lua, standard/test/region_test.lua
Rework `module:Region` and adjust all git consumers.
dev
=> Rework `module:Region`

components/match2/commons/display_util.lua, components/match2/commons/match_group_util.lua, components/opponent/commons/opponent.lua, components/opponent/commons/opponent_display.lua, components/opponent/commons/starcraft_starcraft2/opponent_display_starcraft.lua, components/opponent/commons/starcraft_starcraft2/opponent_starcraft.lua, components/opponent/wikis/fortnite/opponent_display_custom.lua, components/opponent/wikis/rocketleague/opponent_display_custom.lua, components/opponent/wikis/trackmania/opponent_display_custom.lua, components/opponent/wikis/warcraft/opponent_custom.lua, components/opponent/wikis/warcraft/opponent_display_custom.lua
Add annotations to opponent modules
N/A
=> Add annotations to opponent modules

standard/test/tier_test.lua, standard/tier/commons/tier_utils.lua, standard/tier/wikis/ageofempires/tier_custom.lua, standard/tier/wikis/apexlegends/tier_custom.lua, standard/tier/wikis/counterstrike/tier_custom.lua, standard/tier/wikis/rocketleague/tier_custom.lua, standard/tier/wikis/smash/tier_custom.lua, standard/tier/wikis/starcraft/tier_custom.lua, standard/tier/wikis/starcraft2/tier_custom.lua, standard/tier/wikis/warcraft/tier_custom.lua
Change `Tier._raw` to `Tier.raw` (i.e. make it non private)
dev on commons + testcases
=> Change `Tier._raw` to `Tier.raw` (i.e. make it non private)

components/portal_players/commons/portal_players.lua
Pass width along correctly in portal players
dev
=> Pass width along correctly in portal players

standard/fn_util.lua
=> Create annotations for FnUtils

components/opponent/commons/opponent.lua
Fix annotations for Opponent 
* Input is optional to certain parameters.
* Correctly handle party size
=> Fix Opponent Annotation

components/prize_pool/wikis/rainbowsix/prize_pool_custom.lua, components/prize_pool/wikis/trackmania/prize_pool_custom.lua
`Array.filter` expects true/false return (nil not OK). Fix these two lambda. Better code style also...
=> Fix Lambda returns in PPT Customs

standard/logic.lua
Fix/improve annotation of some Logic Annotations
=> Fix Logic Annotations

standard/date_ext.lua
Fix annotations in `date_ext.lua`
N/A
=> Fix annotations in `date_ext.lua`

standard/flags_master_data.lua
Adding new region to better subdivide the African continent.
=> Adding Sub-Saharan Africa to Flags Master data

components/portal_players/commons/portal_players.lua
In Portal Player, create support for status filtering. Needed by trackmania and possibility others.
Dev module
=> Create status filter for Portal Players

components/broadcast_talent_table/commons/broadcast_talent_table.lua
As discussed, swap around to do the logic not in display from #3043.
@hjpalpha Can you suggest a page for testing? :p
=> Different solution for extradata tiers in #3043

components/infobox/wikis/ageofempires/infobox_person_player_custom.lua
The parameter `playerInfo = 'direct'` caused issues with the new module, so removing this (and also migrate to new call style)
Hotfix, dev to live
=> AoE: Adjust call to PlayerIntroduction

components/infobox/wikis/wildrift/infobox_unit_champion.lua
Improve the LPDB Data stored for WR Champion Infobox
dev
=> Improve LPDB Data for Wild Rift Infobox Champion 

standard/info/wikis/clashofclans/info.lua
Info module for newest installed wiki CoC
=> Info Module for Clash of Clans

components/tournaments_listing/commons/tournaments_listing_conditions.lua
Check in 3rd organizer when conditioning on organizer in TournamentslistCard
Needed for some stuff in RL
N/A
=> Check in 3rd organizer when conditioning on organizer

components/infobox/wikis/wildrift/infobox_item_custom.lua
Add LPDB Storage to Wild Rift Items
dev
=> Add LPDB storage to Wild Rift Items

components/portal_players/commons/portal_players.lua
Add option for extra condition input in portal players.
With it i can kick broodwar smw player portal.
/dev
=> Add option for extra condition input in portal players

standard/links/commons/links.lua
Added |vod= support for infobox icon button.
=> Add `vod` support to `Module:Links`

components/infobox/wikis/valorant/infobox_league_custom.lua
Sort maps alphab in Valorant infobox league
dev
=> Sort maps alphab in Valorant infobox league

standard/tier/commons/tier_utils.lua
Fix anno warning in `Module:Tier/Utils`
/dev
=> Fix anno warning in `Module:Tier/Utils`

standard/game.lua, standard/test/game_test.lua
Adds text function to be used to create links
Tested on `/dev` in console and also in upcoming infobox module edits for CS wiki.
=> Add `text()` and `listGames()` to `Module:Game`

components/opponent/commons/opponent_display.lua, standard/class.lua, standard/error_ext.lua, standard/lpdb/condition.lua
Fix annotation warnings with the latest version of sumneko
In IDE
=> Fix some annotation

standard/game.lua
As the title says. An on mobile but pushed live to fix bug.
=> Fix game icon being not string

components/ratings/ratings_display.lua
* Extracted large parts to functions
* Split graph and list making into seperate entry points
* Made the code clearer (at a slight cost of runtime)
* Minor tweaks to the graph
Live as the system is not yet live
=> Improve ratings display

components/match2/wikis/brawlstars/match_legacy.lua, components/match2/wikis/splatoon/match_legacy.lua
Fix Match/Legacy on brawlstars
Bug introduced with #3139
live, hot fix
=> Fix Match/Legacy on brawlstars and splatoon

.github/PULL_REQUEST_TEMPLATE.md, components/infobox/wikis/starcraft2/infobox_league_custom.lua, components/match2/wikis/starcraft2/match_legacy.lua, components/prize_pool/commons/starcraft_starcraft2/prize_pool_legacy_starcraft.lua, components/prize_pool/commons/starcraft_starcraft2/prize_pool_starcraft.lua
Remove SMW Storage on sc2
- match legacy storage
- variables in infobox league only needed for smw storage
- ppt adjusts for smw storage
N/A
For on monday
=> Remove SMW Storage on sc2

components/match2/commons/match.lua, components/match2/commons/match_group_base.lua, components/match2/wikis/arenaofvalor/match_legacy.lua, components/match2/wikis/brawlstars/match_legacy.lua, components/match2/wikis/callofduty/match_legacy.lua, components/match2/wikis/counterstrike/match_legacy.lua, components/match2/wikis/dota2/match_legacy.lua, components/match2/wikis/leagueoflegends/big_match.lua, components/match2/wikis/leagueoflegends/match_legacy.lua, components/match2/wikis/mobilelegends/match_legacy.lua, components/match2/wikis/overwatch/match_legacy.lua, components/match2/wikis/pokemon/match_legacy.lua, components/match2/wikis/rainbowsix/legacy/match_maps_legacy.lua, components/match2/wikis/rainbowsix/match_legacy.lua, components/match2/wikis/rocketleague/match_legacy.lua, components/match2/wikis/starcraft/match_legacy.lua, components/match2/wikis/valorant/big_match.lua, components/match2/wikis/valorant/match_legacy.lua, components/match2/wikis/wildrift/match_legacy.lua
=> Remove smw from match2

components/prize_pool/wikis/brawlstars/prize_pool_custom.lua, components/prize_pool/wikis/counterstrike/prize_pool_award_custom.lua, components/prize_pool/wikis/counterstrike/prize_pool_custom.lua, components/prize_pool/wikis/warcraft/prize_pool_custom.lua
Remove SMW in PPT Customs
Need to first remove it in PPT Customs before being able to touch commons to not break stuff
N/A
=> Remove SMW in PPT Customs

components/infobox/commons/infobox_person.lua, components/infobox/commons/infobox_team.lua, components/infobox/wikis/apexlegends/infobox_person_player_custom.lua, components/infobox/wikis/arenafps/infobox_person_player_custom.lua, components/infobox/wikis/brawlstars/infobox_person_player_custom.lua, components/infobox/wikis/counterstrike/infobox_person_player_custom.lua, components/infobox/wikis/dota2/infobox_person_player_custom.lua, components/infobox/wikis/freefire/infobox_person_player_custom.lua, components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua, components/infobox/wikis/naraka/infobox_person_player_custom.lua, components/infobox/wikis/overwatch/infobox_person_player_custom.lua, components/infobox/wikis/pubg/infobox_person_player_custom.lua, components/infobox/wikis/pubgmobile/infobox_person_player_custom.lua, components/infobox/wikis/rainbowsix/infobox_person_player_custom.lua, components/infobox/wikis/rocketleague/infobox_person_player_custom.lua, components/infobox/wikis/valorant/infobox_person_player_custom.lua, components/infobox/wikis/warcraft/infobox_league_custom.lua, components/infobox/wikis/warcraft/infobox_team_custom.lua, components/infobox/wikis/wildrift/infobox_person_player_custom.lua, components/infobox/wikis/worldofwarcraft/infobox_person_player_custom.lua
Remove SMW stuff from infoboxes
=> Remove SMW stuff from infoboxes

components/prize_pool/commons/prize_pool_placement.lua
Remove unused variable which pipeline complains about
N/A
=> Fix pipeline

standard/info/wikis/fighters/info.lua
Update info for Bloody Roar to match current usage
Already live
=> Update Info for Fighters

components/match2/wikis/leagueoflegends/match_links.lua
Add darkmode icon for factor in lol match links
live by katanamvp (module wasn't locked)
=> Add darkmode icon for factor in lol match links

components/infobox/wikis/ageofempires/infobox_person_player_custom.lua, components/infobox/wikis/ageofempires/infobox_team_custom.lua
=> Use Infobox/Extension/Achievements instead of old module

components/match2/wikis/brawlstars/match_group_input_custom.lua, components/match2/wikis/brawlstars/match_summary.lua
Resolves #3174
Add support to indicate which opponent started pick process
dev
=> Add support to indicate which opponent started pick process

components/infobox/wikis/naraka/infobox_league_custom.lua
=> Fix typo in import

components/infobox/extensions/commons/infobox_extension_achievements.lua
Return nil for achievements infobox extension outside of main space
dev
=> Return nil for achievements infobox extension outside of main space

components/infobox/extensions/commons/infobox_placement_stats.lua
Avoid nil return and add some missing annotations
N/A
=> Avoid nil return and add some missing annotations

components/standings/commons/standings_storage.lua, components/standings/commons/starcraft_starcraft2/standings_storage_starcraft_legacy.lua
resolves #3203 
Adjust the regexes according to the change done to flags
live since bug fix and no negative impact since it can only affect the already broken flag parsing
=> Fix flag parsing in manual group tables

components/match2/commons/match_summary_base.lua, components/match2/wikis/halo/match_summary.lua, components/match2/wikis/mobilelegends/match_summary.lua, components/match2/wikis/rainbowsix/match_summary.lua, components/match2/wikis/rocketleague/match_summary.lua, components/match2/wikis/trackmania/match_summary.lua
Move Casters Class from Custom MatchSummaries to commons
via dev together with #3197
=> Move Casters Class from Custom MatchSummaries to commons

components/infobox/wikis/starcraft/infobox_building_custom.lua
Add BW Infobox building
"live" since new module that is not used anywhere yet
=> Add BW Infobox building

standard/test/array_test.lua
Fix Typo in (test) function name
N/A
=> Fix Typo in (test) function name

components/infobox/commons/custom/infobox_tool_custom.lua, components/infobox/commons/infobox_tool.lua
Add Infobox tool
usage on broodwar and warcraft, both identical with the exception of default game
"live", since new module
=> Add Infobox tool

components/infobox/wikis/starcraft/infobox_skill_custom.lua
Add bw infobox spell (via commons infobox skill)
=> Add bw infobox spell (via commons infobox skill)

.github/workflows/deploy.yml, .github/workflows/scheduled.yml, scripts/deploy.sh
Update deploy scripts to run towards both dev environments
Also remove Team Fortress as a dev wiki as its bonked
Not at all
=> Update deploy scripts to reflect the dev environment

components/infobox/wikis/starcraft/infobox_map_custom.lua
Add bw infobox map
"live", new module with no usage
=> Add bw infobox map

components/infobox/wikis/starcraft/infobox_person_player_custom.lua
Integrate Infobox bot into infobox player
/dev
=> Integrate Infobox bot into infobox player

components/infobox/commons/infobox_league.lua, components/infobox/commons/infobox_series.lua, components/infobox/wikis/starcraft/infobox_building_custom.lua
=> Fix incorrect function headers and annotations

components/infobox/commons/custom/infobox_patch_custom.lua, components/infobox/commons/infobox_patch.lua, components/infobox/wikis/halo/infobox_patch_custom.lua, components/infobox/wikis/rainbowsix/infobox_patch_custom.lua, components/infobox/wikis/starcraft2/infobox_patch_custom.lua
Add annos for infobox patch
N/A
=> Add annos for infobox patch

components/infobox/commons/custom/infobox_show_custom.lua, components/infobox/commons/infobox_show.lua, components/infobox/wikis/starcraft2/infobox_show_custom.lua
Add annotations for infobox show
N/A
=> Add annotations for infobox show

components/infobox/commons/infobox_campaign_mission.lua, components/infobox/extensions/commons/infobox_extension_achievements.lua, components/infobox/wikis/starcraft2/infobox_campaign_mission_custom.lua
- Add annos for infobox campaign mission
- make use of module game in sc2 custom (cleanup)
dev (for sc2 custom)// N/A
=> Add annos for infobox campaign mission

components/infobox/commons/infobox_building.lua, components/infobox/wikis/starcraft/infobox_building_custom.lua, components/infobox/wikis/starcraft2/infobox_building_custom.lua
- Add annotations to building infoboxes
- Minor clean up in the sc2 customs
N/A; for sc2 dev
=> Add annos for building infoboxes

components/infobox/wikis/fighters/infobox_league_custom.lua
Allow setting of series icon manually
dev
=> Allow manual icons for Infobox League for Fighters

components/infobox/wikis/starcraft/infobox_strategy_custom.lua
Add BW Infobox/Strategy/Custom module
used on bw for
- infobox strategy
- infobox technique
- infobox counter
"live", since new module
=> Add BW Infobox/Strategy/Custom module

components/infobox/wikis/warcraft/infobox_map_custom.lua
=> Add Warcraft infobox map

components/infobox/wikis/warcraft/infobox_strategy_custom.lua
Add WC `Infobox/Strategy/Custom` module
used on warcraft for
- infobox strategy
- infobox technique
"live", since new module
=> Add WC `Module:Infobox/Strategy/Custom`

components/infobox/wikis/warcraft/infobox_item_custom.lua
depends on #3225 for pushing live (merge independent)
Add warcraft infobox item
=> Add warcraft infobox item

components/infobox/wikis/warcraft/infobox_character_custom.lua, standard/abbreviation.lua
depends on #3229
Add warcraft `Module:Infobox/Character/Custom` for usage in `Template:Infobox heroauto`
"live", since new module
=> Add warcraft `Module:Infobox/Character/Custom`

components/infobox/commons/custom/infobox_game_custom.lua, components/infobox/commons/custom/infobox_website_custom.lua, components/infobox/commons/infobox_campaign.lua, components/infobox/commons/infobox_game.lua, components/infobox/commons/infobox_scene.lua, components/infobox/commons/infobox_website.lua
Add annos to infoboxes that do not have (wiki) customs
N/A
=> Add annos to infoboxes that do not have (wiki) customs

components/infobox/commons/custom/infobox_character_custom.lua, components/infobox/commons/infobox_character.lua, components/infobox/wikis/apexlegends/infobox_character_custom.lua, components/infobox/wikis/omegastrikers/infobox_character_custom.lua
Add annos for infobox character
N/A
=> Add annos for infobox character

components/infobox/commons/custom/infobox_unofficial_world_champion_custom.lua, components/infobox/commons/infobox_unofficial_world_champion.lua, components/infobox/wikis/overwatch/infobox_unofficial_world_champion_custom.lua, components/infobox/wikis/starcraft2/infobox_unofficial_world_champion_custom.lua
Add annos for `Module:Infobox/UnofficialWorldChampion`
N/A
=> Add annos for `Module:Infobox/UnofficialWorldChampion`

components/infobox/commons/custom/infobox_strategy_custom.lua, components/infobox/commons/infobox_strategy.lua, components/infobox/wikis/apexlegends/infobox_map_custom.lua, components/infobox/wikis/halo/infobox_map_custom.lua, components/infobox/wikis/overwatch/infobox_map_custom.lua, components/infobox/wikis/pubgmobile/infobox_map_custom.lua, components/infobox/wikis/starcraft/infobox_map_custom.lua, components/infobox/wikis/starcraft2/infobox_map_custom.lua, components/infobox/wikis/starcraft2/infobox_strategy_custom.lua
Add annos for infobox map and infobox strategy
N/A
=> Add annos for infobox map and infobox strategy

components/infobox/commons/custom/infobox_series_custom.lua, components/infobox/commons/infobox_series.lua, components/infobox/wikis/ageofempires/infobox_series_custom.lua, components/infobox/wikis/counterstrike/infobox_series_custom.lua, components/infobox/wikis/dota2/infobox_series_custom.lua, components/infobox/wikis/fortnite/infobox_series_custom.lua, components/infobox/wikis/rocketleague/infobox_series_custom.lua, components/infobox/wikis/smash/infobox_series_custom.lua, components/infobox/wikis/starcraft/infobox_series_custom.lua, components/infobox/wikis/starcraft2/infobox_series_custom.lua, components/infobox/wikis/valorant/infobox_series_custom.lua, components/infobox/wikis/warcraft/infobox_series_custom.lua
Add annos for infobox series
N/A
=> Add annos for infobox series

components/infobox/commons/infobox_item.lua, components/infobox/wikis/mobilelegends/infobox_item_custom.lua, components/infobox/wikis/wildrift/infobox_item_custom.lua
=> Add infobox item annos

components/infobox/commons/custom/infobox_weapon_custom.lua, components/infobox/commons/infobox_weapon.lua, components/infobox/wikis/apexlegends/infobox_weapon_custom.lua, components/infobox/wikis/pubg/infobox_weapon_custom.lua, components/infobox/wikis/rainbowsix/infobox_weapon_custom.lua
Add annos for infobox weapon
N/A
=> Add annos for infobox weapon

components/infobox/extensions/commons/infobox_extensions_prize_pool.lua
Add annos for `Module:Infobox/Extensions/PrizePool`
N/A
=> Add annos for `Module:Infobox/Extensions/PrizePool`

components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua
Remove signature champion display in lol infobox player as per request by izanagi
https://discord.com/channels/93055209017729024/268719633366777856/1147954293916315738
/dev
=> Remove signature champion display in lol infobox player

components/infobox/commons/infobox_league.lua
Add annos to commons infobox league
N/A
=> Add annos to commons infobox league

components/infobox/wikis/starcraft/infobox_map_custom.lua
Fix size field in broodwar infobox map
live
=> Fix size field in broodwar infobox map

components/infobox/commons/infobox_widget_breakdown.lua, components/infobox/commons/infobox_widget_builder.lua, components/infobox/commons/infobox_widget_cell.lua, components/infobox/commons/infobox_widget_center.lua, components/infobox/commons/infobox_widget_chronology.lua, components/infobox/commons/infobox_widget_customizable.lua, components/infobox/commons/infobox_widget_factory.lua, components/infobox/commons/infobox_widget_header.lua, components/infobox/commons/infobox_widget_highlights.lua, components/infobox/commons/infobox_widget_links.lua, components/infobox/commons/infobox_widget_title.lua, components/widget/widget_table.lua
- Add annotations for infobox widgets
- Fix Table Widget anno as per #3239
N/A
=> Add annotations for infobox widgets

components/opponent/commons/opponent.lua
split out of #3258 
Add `.isBye` function to `Module:Opponent`
N/A
=> Add `.isBye` function to `Module:Opponent`

components/infobox/extensions/wikis/warcraft/infobox_extension_building_unit_shared.lua
This module holds shared functions between those 2 infoboxes to de-duplicate lots of code.
"live", sicne new
together with #3273 and #3274
=> Add infobox extension for warcraft infoboxes unit and building

components/infobox/wikis/warcraft/infobox_building_custom.lua
depends on #3272
Remark: Deploying to template (not merge) earliest on 2023-09-12 since i will not be around friday-monday
Remark2: `onYourOwn` set up the first version of this, i "only" cleaned it up, fixed some stuff and de-duplicated with infobox unit in mind
Add warcraft infobox building
"live", sicne new and not yet in use
=> Add warcraft infobox building

components/infobox/wikis/warcraft/infobox_unit_custom.lua
depends on #3272
Remark: Deploying to template (not merge) earliest on 2023-09-12 since i will not be around friday-monday
Add warcraft infobox unit
"live", sicne new and not yet in use
=> Add warcraft infobox unit

standard/logic.lua
Add `Logic.isDeepEmpty` function.
Like `Logic.isEmpty` function just also recursively checks if a table only consists of empty items.
/dev (no test cases since those do not exist for any logic function yet)
=> Add `Logic.isDeepEmpty` function

components/match2/commons/match_group.lua
Add option to forceDisplay a Bracket as a matchList
/dev
=> Add option to force display of a Bracket as a matchList

standard/test/logic_test.lua
Add testcases for `Module:Logic`
N/A
=> Add testcases for `Module:Logic`

standard/info/wikis/fighters/info.lua
added mortal kombat 1 to the list
=> Add Mortal Kombat 1 to Fighters

components/match2/wikis/brawlstars/match_summary.lua
depends on #3312 
Rework brawlstars MatchSummary to use the new base module and hence simplify stuff and improve reset match display
dev
=> Rework brawlstars MatchSummary

components/faction/wikis/warcraft/faction_data.lua
Add css classes to warcraft Faction data
N/A
=> Add css classes to warcraft Faction data

components/matches_schedule_display/commons/matches_schedule_display.lua
Fix condition building in matches_schedule_display.lua
live since bug fix
=> Fix condition building in matches_schedule_display.lua

components/infobox/wikis/warcraft/infobox_building_custom.lua, components/infobox/wikis/warcraft/infobox_unit_custom.lua
Fix some small bugs in warcraft infobox building and infobox unit
dev to live
=> Fix some small bugs in warcraft infobox building and infobox unit

components/infobox/wikis/warcraft/infobox_building_custom.lua, components/infobox/wikis/warcraft/infobox_unit_custom.lua
Fix 2 typos in warcraft infoboxes
live
=> Fix 2 typos in warcraft infoboxes

standard/flags_master_data.lua
Adding Levant & North Africa flags to database.
Just data update.
=> Add Levant & North Africa flag files

components/match2/commons/match_summary_base_temp.lua
Force disable merging reset into normal match
live
=> Force disable merging reset into normal match

components/match2/wikis/rainbowsix/match_summary.lua
Update R6 MatchSummary to use `Module:MatchSummary/Base/temp`
dev
=> Update R6 MatchSummary to use new Match Summary

components/match2/wikis/arenaofvalor/match_summary.lua, components/match2/wikis/brawlstars/match_summary.lua, components/match2/wikis/callofduty/match_summary.lua, components/match2/wikis/halo/match_summary.lua
if you want less anno warnings during review: wait for #3322 and rebase the branch then^^
- Update aov, cod and halo MS to use `Module:MatchSummary/Base/temp`
- refine annos for brawlstars MS
dev
=> Update aov, cod and halo MS

components/match2/wikis/valorant/match_summary.lua
Update Valorant MatchSummary to use `Module:MatchSummary/Base/temp`
dev
=> Update valorant MatchSummary

components/match2/wikis/mobilelegends/match_summary.lua, components/match2/wikis/overwatch/match_summary.lua, components/match2/wikis/pokemon/match_summary.lua, components/match2/wikis/splitgate/match_summary.lua, components/match2/wikis/wildrift/match_summary.lua
Update WR, Splitgate, Pokemon, OW and ML MatchSummary Modules to use `Module:MatchSummary/Base/temp`
dev
=> Update WR, Splitgate, Pokemon, OW and ML MatchSummary Modules

components/infobox/wikis/ageofempires/infobox_map_custom.lua
Direct replacement of template implementation
via /dev
=> AoE: Add infobox map

components/infobox/wikis/ageofempires/infobox_map_custom.lua
Fixes two bugs encountered when adjusting the template to use the module;
one was missed due to testing with complete input only, the other was missed due to only using preview before.
live (new module) and tested with multiple pages
=> Fix bugs in AoE Infobox Map

components/match2/commons/match_group_util.lua, components/match2/commons/match_summary_base.lua, components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
Simplify `MatchGroupUtil.fetchMatchForBracketDisplay`
dev
=> Simplify `MatchGroupUtil.fetchMatchForBracketDisplay`

components/opponent/wikis/warcraft/player_ext_custom.lua
Fix warcraft `CustomPlayerExt.fetchPlayer`
dev
=> Fix warcraft `CustomPlayerExt.fetchPlayer`

components/hidden_data_box/commons/hidden_data_box.lua, components/hidden_data_box/wikis/starcraft/hidden_data_box_custom.lua, components/hidden_data_box/wikis/starcraft2/hidden_data_box_custom.lua
Add support for non team opponents in HiddenDataBox participantGrabber
dev
=> Add support for non team opponents in HDB participantGrabber

components/opponent/commons/opponent_display.lua
Add `dq` option to `OpponentDisplay.BlockTeam`
dev
=> Add `dq` option to `OpponentDisplay.BlockTeam`

components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
Fix sc/sc2 h2h link in MatchSummary
dev to live since bug fix
=> Fix sc/sc2 h2h link in MatchSummary

components/prize_pool/commons/prize_pool_base.lua
Fix ppt percentage for unset localcurrency
/dev
=> Fix ppt percentage for unset localcurrency

standard/links/commons/links.lua
Add `haojiao` link support as per request in templates-help discord channel
dev
=> Add `haojiao` link support

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- adjust var name for display name to be more in line with commons (new SC/SC2 TC sets it)
- add a vardefine for easier input
- simplify the function a bit
dev
=> Adjust sc/sc2 parsing of team player variables

standard/links/commons/links.lua
Adjust haojiao link data as per info from discord
N/A
=> Adjust haojiao link data

components/matches_schedule_display/commons/matches_schedule_display.lua
Add matchpage support for the Match Schedule
It's hidden behind a param-toggle
dev
=> Add matchpage support for the Match Schedule

standard/region/commons/region_data.lua
=> Fix LATAM alias typo

components/match2/wikis/warcraft/get_match_group_copy_paste_wiki.lua
Add warcraft match2 copy pasta generator
"live" since not yet in use
=> Add warcraft match2 copy pasta generator

components/match2/wikis/heroes/match_group_input_custom.lua
**Match2 for Heroes of the Storm**
Game Summary: Its just a MOBA with multiple maps
Key Info
- Base is Mobile Legends
- (This Module) Added the ability to do **Map Veto** as requested by the Wiki Editors 
- The rest is untouched from the port
https://liquipedia.net/heroes/User:Hesketh2
(the hero icon and map names in Veto are placeholder name and icons from other wikis to test only)
=> Add MatchGroup/Input/Custom for Heroes

components/match2/wikis/warcraft/match_legacy.lua
Add Warcraft match legacy storage
"live" since match2 not in use except for testing
=> Add Warcraft match legacy storage

components/match2/wikis/tetris/match_legacy.lua
**Part of Match2 Implementation**
Based on the merged PR of Clash Royale with Adjustments
LIVE
(e.g. https://liquipedia.net/tetris/CTWC/2022)
=> Match/Legacy for Tetris

components/opponent/wikis/warcraft/player_ext_custom.lua
Fix contextualDateOrNow call in warcraft PlayerExt
live since bug fix
=> Fix contextualDateOrNow call in warcraft PlayerExt

components/opponent/wikis/trackmania/opponent_display_custom.lua
Fix trackmania score display.
Currently it displays -1 over the status.
Additionally the old code is redundant in some places.
This PR fixes the wrong display and cleans up the functions code style.
dev
=> Fix trackmania score display

components/match2/wikis/heroes/match_legacy.lua
**Match2 for Heroes of the Storm** 
Legacy Module, direct port of Mobile Legends version with no changes
LIVE
=> Add Match Legacy for Heroes

components/participant_table/commons/starcraft_starcraft2/participant_table_starcraft.lua
Catch some legacy input variation in sc2 participantTable
dev to live
=> Catch some legacy input variation in sc2 participantTable

components/opponent/commons/starcraft_starcraft2/opponent_starcraft.lua, components/opponent/wikis/warcraft/opponent_custom.lua
Pass along date in sc2/warcraft opponent.resolve to sync player so it is available during race sync
dev
=> Pass along date in sc2/warcraft opponent.resolve to sync player

components/match2/wikis/trackmania/match_legacy.lua
Been live on the wiki for almost a year. I did some cleanup compared to the live version.
@Sigeth did initial version, with some later changes by @mbergen  and @hjpalpha .
Live
=> feat: match legacy for trackmania

components/infobox/wikis/starcraft2/infobox_person_player_custom.lua, components/infobox/wikis/starcraft2/infobox_team_custom.lua
Use new matchticker in sc2 infoboxes
dev
=> Use new matchticker in sc2 infoboxes

components/participant_table/commons/participant_table_base.lua
Keep the order of the input when alphabetical order is disabled, like the previous table handled it.
Reported on [Discord](https://discord.com/channels/93055209017729024/268719633366777856/1163487709856272536).
Fix originally written by @hjpalpha 
dev
=> Keep order of input in ParticipantTable

components/participant_table/commons/participant_table_base.lua, components/participant_table/commons/starcraft_starcraft2/participant_table_starcraft.lua
Fix some display issues in participant table
- suppress duplicate titles between the table itself and the sections
- fix bad row breaks on zoom
dev to live
=> Fix some display issues in participant table

components/match2/wikis/zula/match_summary.lua
Wrong annotation names in zula's match summary
vscode
=> fix: zula annotations

standard/wikis/worldoftanks/info
Basic setup of the Info module for World of Tanks.
Initial default logo is already added
=> Setup Module info for World of Tanks wiki

standard/links/commons/links.lua, standard/links/commons/links_priority_groups.lua
Add rgl link support
N/A, just data
resolves #3425
=> Add rgl link support

standard/links/commons/links.lua, standard/links/commons/links_priority_groups.lua
=> Add `etf2l` link

components/match2/commons/match_group_legacy.lua
Catch winner in legacy processing
dev
=> Catch winner in legacy processing

components/opponent/wikis/warcraft/opponent_display_custom.lua
Call correct opponentDisplay in warcraft BracketOpponentEntry.
dev to live
=> Call correct opponentDisplay in warcraft BracketOpponentEntry

components/match2/wikis/warcraft/legacy/legacy_match_maps.lua, standard/page_variable_namespace.lua
Add warcraft wrapper for legacy match lists
"live" since new
=> Add warcraft wrapper for legacy match lists

components/infobox/commons/infobox_patch.lua, components/infobox/wikis/dota2/infobox_patch_custom.lua
Implements the legacy infobox patch and infobox version of dota2 into the new infobox system
preview
=> feat: infobox patch and infobox version for dota2

standard/links/commons/links.lua
Add tftv link as per request by contributor
just data
=> Add tftv link

components/prize_pool/commons/starcraft_starcraft2/prize_pool_starcraft.lua
Respect `disable_LPDB_storage` var in sc/sc2 ppt
dev to live
=> Respect `disable_LPDB_storage` var in sc/sc2 ppt

components/participant_table/commons/participant_table_base.lua
Fix participanttable objectname
dev to live
=> Fix participanttable objectname

standard/info/wikis/arenaofvalor/info.lua
Add new game info for the combined game version used for the upcoming Honor of Kings International Championship (to distinguish it from other HoK versions).
=> Add new KIC game info

components/infobox/wikis/clashroyale/infobox_patch_custom.lua
Implements the legacy infobox version of Clash Royale into the new infobox system
Live
=> feat: infobox patch for clash royale

components/infobox/wikis/fortnite/infobox_patch_custom.lua
Implements the legacy infobox version of Fortnite into the new infobox system
Live
=> feat: infobox patch for fortnite

standard/tier/commons/tier_utils.lua, standard/tier/wikis/ageofempires/tier_custom.lua, standard/tier/wikis/apexlegends/tier_custom.lua, standard/tier/wikis/counterstrike/tier_custom.lua, standard/tier/wikis/rocketleague/tier_custom.lua, standard/tier/wikis/smash/tier_custom.lua, standard/tier/wikis/starcraft/tier_custom.lua, standard/tier/wikis/starcraft2/tier_custom.lua, standard/tier/wikis/warcraft/tier_custom.lua
=> Fix annos in tier modules

components/infobox/commons/infobox_patch.lua, components/infobox/wikis/valorant/infobox_patch_custom.lua
Implements the legacy infobox patch of valorant into the new infobox system
Tested on page
=> feat: infobox patch for valorant

standard/page_variable_namespace.lua
Add annos to PageVariableNamespace
N/A
=> Add annos to PageVariableNamespace

components/infobox/wikis/fighters/infobox_league_custom.lua
Rudimentary support to display number of teams for team tournaments
Tested in dev
=> Add team number cell in fighters infobox league

components/match2/commons/match_group.lua, components/match2/commons/match_group_shorten_bracket.lua, components/match2/commons/starcraft_starcraft2/match_group_display_bracket_starcraft.lua, components/match2/commons/starcraft_starcraft2/match_group_display_matchlist_starcraft.lua, components/match2/wikis/starcraft/brkts_wiki_specific.lua, components/match2/wikis/starcraft2/brkts_wiki_specific.lua
Add option to suppress details display in show bracket
dev
resolves #3460
=> Add option to suppress details display in show bracket

standard/json.lua
Json.stringify's annotation does not match it's code.
Correct it
IDE
=> fix: json.stringify annotations

standard/links/commons/links.lua, standard/links/commons/links_priority_groups.lua
Added links for the osu infobox icon
=> added links for osu infobox icon

standard/result_or_error.lua
As spotted by hesketh2 on discord: https://discord.com/channels/93055209017729024/874304000718172200/1171087927984521308
=> Fix require typo in #3413

components/infobox/wikis/ageofempires/infobox_person_player_custom.lua, components/infobox/wikis/ageofempires/infobox_team_custom.lua, components/match2/wikis/arenaofvalor/match_group_input_custom.lua, components/match2/wikis/brawlstars/match_group_input_custom.lua, components/match2/wikis/callofduty/match_group_input_custom.lua, components/match2/wikis/counterstrike/match_group_input_custom.lua, components/match2/wikis/dota2/match_group_input_custom.lua, components/match2/wikis/halo/match_group_input_custom.lua, components/match2/wikis/heroes/match_group_input_custom.lua, components/match2/wikis/leagueoflegends/match_group_input_custom.lua, components/match2/wikis/mobilelegends/match_group_input_custom.lua, components/match2/wikis/overwatch/match_group_input_custom.lua, components/match2/wikis/pokemon/match_group_input_custom.lua, components/match2/wikis/rainbowsix/match_group_input_custom.lua, components/match2/wikis/rocketleague/match_group_input_custom.lua, components/match2/wikis/sideswipe/match_group_input_custom.lua, components/match2/wikis/splatoon/match_group_input_custom.lua, components/match2/wikis/splitgate/match_group_input_custom.lua, components/match2/wikis/trackmania/match_group_input_custom.lua, components/match2/wikis/valorant/match_group_input_custom.lua, components/match2/wikis/wildrift/match_group_input_custom.lua, components/ratings/ratings.lua
The Param is now called `osdateparam` instead
=> fix: `osdate` -> `osdateparam`

components/squad/commons/squad_row.lua
Parenthesis was in the wrong place
=> fix: squadrow sync

components/infobox/commons/infobox_person.lua, components/infobox/wikis/starcraft2/infobox_person_custom.lua
Fix anno warning in SC2 person
=> fix: annotation warnings in infobox sc2 person

components/infobox/commons/infobox_widget.lua, components/infobox/commons/infobox_widget_factory.lua, standard/class.lua
Fix some annotation and useless code (`return error()` > `error()`) that confused the intellisense
=> fix: annotations in widget and widget factory

components/infobox/wikis/warcraft/infobox_league_custom.lua
Add server2 and patch2 support to warcraft infobox league
Also add annos to the file
dev
=> Add server2 and patch2 support to warcraft infobox league

standard/info/wikis/fortnite/info.lua
Missed to change Module:Info in #3501 
Live
=> fix: forgot in #3501 to defaeult fortnite's opponent display info

components/portal_players/wikis/formula1/portal_players_custom.lua
Add f1 custom portal players
Written by `I am entry` who apparently doesn't have github.
https://discord.com/channels/93055209017729024/874304000718172200/1170421565867954258
by `I am entry` via dev
=> Add f1 custom portal players

components/match2/wikis/leagueoflegends/match_links.lua, standard/links/commons/links.lua, standard/links/commons/links_priority_groups.lua
Resolves #3461. Factor as a site has shutdown, and is no longer active. 
Just data
=> Removing Factor link from Infoboxes

components/match2/wikis/warcraft/legacy/match_group_legacy_convert_map_data.lua, components/match2/wikis/warcraft/legacy/match_group_legacy_default.lua
Pass along walkover handling in legacy wrapper. (Yet another edge case)
dev
=> Pass along submatch/map walkover handling in legacy wrapper

components/statistics/portal_statistics.lua
As reported by kano in discord
live
=> Statistics: Fix opponentplayers sometimes being nil

components/match2/commons/brkts_wiki_specific_base.lua, components/match2/commons/match_group_display_singlematch.lua, components/match2/commons/starcraft_starcraft2/match_group_display_singlematch_starcraft.lua, components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua, components/match2/wikis/starcraft/brkts_wiki_specific.lua, components/match2/wikis/starcraft2/brkts_wiki_specific.lua, components/match2/wikis/starcraft2/legacy/match_maps_legacy.lua, components/match2/wikis/warcraft/brkts_wiki_specific.lua, components/match2/wikis/warcraft/get_match_group_copy_paste_wiki.lua, components/matches_schedule_display/commons/matches_schedule_display.lua, components/participant_table/commons/participant_table_base.lua, components/participant_table/commons/participant_table_import.lua, components/participant_table/commons/starcraft_starcraft2/participant_table_starcraft.lua, components/participant_table/wikis/warcraft/participant_table_custom.lua, components/portal_players/commons/portal_players.lua, components/portal_players/wikis/fifa/portal_players_custom.lua, components/results_table/commons/results_table_base.lua, components/results_table/wikis/starcraft2/results_table_custom.lua, components/tournaments_listing/commons/tournaments_listing_card_list.lua, spec/abbreviation_spec.lua, standard/table.lua
Fix some more annotations
VSCode
=> Fix some more annotations

components/match2/wikis/warcraft/legacy/legacy_match_maps.lua, components/match2/wikis/warcraft/match_group_util_custom.lua
Add a nil catch to wc legacy match maps team template input
dev to live
=> Add a nil catch to wc legacy match maps team template input

scripts/deploy_css.sh
Correct target file (Foo.js instead of ./stylesheet/Bar/Foo.js)
=> fix: css deploy script

components/infobox/extensions/commons/player_introduction.lua
=> fix: anno typo

components/match_ticker/commons/match_ticker_display_components.lua
=> Add a nil check with log

components/infobox/wikis/formula1/infobox_league_custom.lua
Uploading existing live module f1 infobox league
Live :/
=> feat: Create F1 infobox league

components/infobox/wikis/formula1/infobox_map_custom.lua
Adding live f1 module infobox map
Live :/
=> feat: Create F1 infobox map

components/infobox/wikis/formula1/infobox_person_player_custom.lua
Add F1 infobox player
It has been live since february ...
module exists live without being on the git ...
changes via this PR compared to the live module via dev
=> Add F1 infobox player

components/infobox/wikis/warcraft/infobox_league_custom.lua
Adjust map processing in warcraft infobox league
- resolve aliases like in matches
- sort alphabetically
requested by warcraft reviewer Stowka
dev
=> Adjust map processing in warcraft infobox league

components/match2/wikis/warcraft/match_group_input_custom.lua
Add a nil catch in an edge case in warcraft match input processing.
dev to live
=> Add a nil catch

.eslintrc.json, .github/workflows/deploy.yml, .gitignore, .vscode/extensions.json, Gruntfile.js, javascript/README.md, javascript/commons/Bracket.js, javascript/commons/Calendar.js, javascript/commons/Collapse.js, javascript/commons/Commons_mainpage.js, javascript/commons/Commons_tools.js, javascript/commons/CopyToClipboard.js, javascript/commons/Countdown.js, javascript/commons/Crosstable.js, javascript/commons/FilterButtons.js, javascript/commons/Liquipedia_links.js, javascript/commons/Mainpage.js, javascript/commons/Miscellaneous.js, javascript/commons/Prizepooltable.js, javascript/commons/Selectall.js, javascript/commons/SiteNotice.js, javascript/commons/Tabs.js, package.json, scripts/deploy_res.sh
Add js and its pipeline to the repository as well
=> feat: add js to the repo

standard/array.lua, standard/mock/mock_lpdb.lua, standard/template.lua, standard/test/template_test.lua
=> fix: improve/fix some annotations

components/infobox/wikis/warcraft/infobox_item_custom.lua
Improve `extradata_purchasedfromgoblinshop` storage in warcraft infobox item
dev
=> Improve `extradata_purchasedfromgoblinshop` storage in warcraft infobox item

components/infobox/wikis/clashofclans/infobox_building_custom.lua, components/infobox/wikis/starcraft2/infobox_building_custom.lua
Fix some small anno issues
vscode
=> Fix some small anno issues

components/hidden_data_box/commons/hidden_data_box.lua
Catch a nil in HDB
live as super easy bug fix
=> Catch a nil in HDB

components/infobox/extensions/wikis/warcraft/infobox_extension_building_unit_shared.lua
Adjust some calculatriuon for units/buildings in warcraft infoboxes as per request by contributors
dev
=> Adjust some calculation for units/buildings in warcraft infoboxes

components/participant_table/wikis/stormgate/participant_table_custom.lua
Uses the Starcraft Participants table
=> Add Participant Table for Stormgate

components/match2/wikis/warcraft/match_group_input_custom.lua, components/match2/wikis/warcraft/match_group_util_custom.lua, components/match2/wikis/warcraft/match_summary.lua
Always show h2h link for standard warcraft matches.
dev
=> Always show h2h link for standard warcraft matches

standard/info/wikis/stormgate/info.lua
Info module for Stormgate 
I put start year as 2023 (while the game actually is 2024, we had some stuff going on in this year at least)
=> Add info module for Stormgate

standard/currency_data.lua
Adds BHD to currency data (added to dev by Tanmay)
via /dev
=> Add bahraini dinar to currency data

components/match2/commons/match_group_legacy.lua
- minor cleanup (remove underscores, fix some import code styles)
- add annos
- make `MatchGroup/Legacy/Default` import dav-able
dev
=> Cleanup `Module:MatchGroup/Legacy` a bit

components/infobox/wikis/starcraft/infobox_building_custom.lua
=> Fix an anno warning

.eslintrc.json, javascript/commons/Bracket.js, javascript/commons/Collapse.js, javascript/commons/Commons_mainpage.js, javascript/commons/Commons_tools.js, javascript/commons/CopyToClipboard.js, javascript/commons/Countdown.js, javascript/commons/Crosstable.js, javascript/commons/FilterButtons.js, javascript/commons/Liquipedia_links.js, javascript/commons/Mainpage.js, javascript/commons/Miscellaneous.js, javascript/commons/Prizepooltable.js, javascript/commons/Selectall.js, javascript/commons/SiteNotice.js, javascript/commons/Tabs.js
Change the code to es5 instead of es2017 until https://gitlab.com/teamliquid-dev/liquipedia/web/issue-bucket/-/issues/9 is done
=> fix: change from es2017 to es5

components/infobox/wikis/formula1/infobox_person_player_custom.lua
- add getPersonType overwrite
- fix typo in anno
- clean up role usage according to the changes done in module:Role
dev
=> Fix type storage in f1 infobox player

components/hidden_data_box/wikis/stormgate/hidden_data_box_custom.lua
Add stormgate hdb
live, new wiki
=> Add stormgate hdb

components/prize_pool/wikis/stormgate/prize_pool_award_custom.lua, components/prize_pool/wikis/stormgate/prize_pool_custom.lua
Both Award and Custom Prize will use the Starcraft one on Commons.
Has both in this PR
=> Add prize pool for Stormgate

components/match2/wikis/brawlstars/match_group_input_custom.lua
Currently draws are not processed correctly
- wrong winner is assigned (first opponent)
- placements are wrong
This PR fixes those issues
dev
=> Fix brawlstars winner processing

components/faction/wikis/stormgate/faction_data.lua, components/faction/wikis/stormgate/faction_icon_data.lua, stylesheets/commons/Miscellaneous.css
Add stormgate faction stuff
N/A // live (new modules)
=> Add stormgate faction stuff

components/match_ticker/commons/match_ticker_display_components.lua
Fix ffa/br header expand in matchtickers
and shut up some anno warnings in the same module
dev
=> Fix ffa/br header expand in matchtickers

components/match2/commons/match.lua
Related to require + other stuff on name code-line
Intellisense in VSCode
=> fix: anno warning

components/infobox/wikis/osu/infobox_league_custom.lua
Func has no parameters but annos says it has
=> fix(anno): typo in osu's infobox league

components/infobox/wikis/worldoftanks/infobox_map_custom.lua
Creates a new Map Infobox for World of Tanks
Tested via userspace [page](https://liquipedia.net/worldoftanks/User:Fenrir.SPAZ/MapTest)
LPDB saved:
=> Create Map Infobox for WoT

components/match2/wikis/crossfire/brkts_wikispecific.lua, components/match2/wikis/crossfire/match_group_input_custom.lua, components/match2/wikis/crossfire/match_legacy.lua, components/match2/wikis/crossfire/match_summary.lua
Not done by me, just took what's live to the git
=> feat: match2 for crossfire

components/hidden_data_box/commons/hidden_data_box.lua
Spotted that HDB is using the wrong table to look up dates from parent. It's trying to get it from the `queryData` instead of `queryData[1]` (from array instead of the first obj in the array)
Cleaned up some annotations stuff while around
=> fix(hdb): date fetching from parent

components/infobox/wikis/stormgate/infobox_map_custom.lua
still todo: add icons for ressources
Add stormgate infobox map with fields as per discussion in stormgate channel on LP discord
"live" (new wiki)
=> Add stormgate infobox map

standard/json.lua
=> fix: annotations mistake in json

components/team_card/team_card_storage.lua
Fix misisng field in anno
was apparently forgotten in #3619 and anoyed me in vscode now
N/A, just to shut up the anno warning
=> fix: misisng field in anno

components/match2/wikis/wildrift/legacy/match_group_legacy_default.lua, components/match2/wikis/wildrift/legacy/match_maps_legacy.lua
Add legacy wrapper to wildrift.
Code wise very similar to leagueoflegends.
[sandbox](https://liquipedia.net/wildrift/User:LuckeLucky/sandbox/2)
=> Add legacy wrapper to wildrift

components/infobox/wikis/ageofempires/infobox_team_custom.lua
annos + 3669 + 3663
The earnings stuff could use some cleanup, but that is oos for this PR.
dev
=> Refactor aoe infobox team

components/infobox/wikis/starcraft2/infobox_building_custom.lua, components/infobox/wikis/starcraft2/infobox_campaign_mission_custom.lua, components/infobox/wikis/starcraft2/infobox_map_custom.lua, components/infobox/wikis/starcraft2/infobox_patch_custom.lua, components/infobox/wikis/starcraft2/infobox_show_custom.lua, components/infobox/wikis/starcraft2/infobox_skill_custom.lua, components/infobox/wikis/starcraft2/infobox_strategy_custom.lua, components/infobox/wikis/starcraft2/infobox_unit_custom.lua, components/infobox/wikis/starcraft2/infobox_unofficial_world_champion_custom.lua
depends on #3710
Refactor minor sc2 infoboxes
(all infoboxes, except league, series, team and person)
dev (unoff. world champ live since usage only on 1 page)
=> Refactor minor sc2 infoboxes

standard/info/wikis/battalion/info.lua
Updates the Battalion 1944 Info module to change the images used to be images that follow the File Standards Guide
Image change. Nothing to test
=> Update Battalion Info with proper images

components/infobox/wikis/warcraft/infobox_building_custom.lua, components/infobox/wikis/warcraft/infobox_character_custom.lua, components/infobox/wikis/warcraft/infobox_company_custom.lua, components/infobox/wikis/warcraft/infobox_item_custom.lua, components/infobox/wikis/warcraft/infobox_map_custom.lua, components/infobox/wikis/warcraft/infobox_patch_custom.lua, components/infobox/wikis/warcraft/infobox_skill_custom.lua, components/infobox/wikis/warcraft/infobox_strategy_custom.lua, components/infobox/wikis/warcraft/infobox_unit_custom.lua
depends on #3710
Refactor minor warcraft infoboxes
(all infoboxes, except league, series, team and person)
dev
=> Refactor minor warcraft infoboxes

components/infobox/wikis/fortnite/infobox_team_custom.lua
annos + 3669 + 3663
The earnings stuff could use some serious cleanup, but that is oos for this PR.
dev
=> Refactor fortnite infobox team

components/infobox/wikis/starcraft/infobox_team_custom.lua
annos + 3669 + 3663
The earnings stuff could use some serious cleanup, but that is oos for this PR.
dev
=> Refactor bw infobox team

components/infobox/wikis/starcraft2/infobox_team_custom.lua
annos + 3669 + 3663
The earnings stuff could use some serious cleanup, but that is oos for this PR.
dev
=> Refactor sc2 infobox team

components/infobox/wikis/starcraft2/infobox_person_map_maker_custom.lua
Refactor sc2 infobox mapmaker by using #3669 + #3663 and class inheritance
dev
=> Refactor sc2 infobox mapmaker

components/infobox/commons/infobox_person.lua, components/infobox/extensions/commons/player_introduction.lua, components/infobox/wikis/brawlhalla/infobox_person_player_custom.lua, components/infobox/wikis/brawlstars/infobox_person_player_custom.lua, components/infobox/wikis/counterstrike/infobox_person_player_custom.lua, components/infobox/wikis/dota2/infobox_person_player_custom.lua, components/infobox/wikis/rainbowsix/infobox_person_player_custom.lua, components/infobox/wikis/rocketleague/infobox_person_player_custom.lua, components/infobox/wikis/starcraft/infobox_person_player_custom.lua, components/infobox/wikis/starcraft2/infobox_person_custom.lua, components/infobox/wikis/starcraft2/infobox_person_player_custom.lua, components/portal_players/wikis/formula1/portal_players_custom.lua
Rework status in person infoboxes
dev
If there are "invalid" statuses used somewhere we might get a few (intentional) errors.
=> Rework status in person infoboxes

standard/tier/wikis/stormgate/tier_data.lua
Add stormgate tier data.
Changes to commons:
- Misc is tier (-1) not tierType
- add charity tierType
N/A just data
=> Add stormgate tier data

components/match2/commons/match_summary_base.lua, components/match2/wikis/omegastrikers/match_group_input_custom.lua, components/match2/wikis/omegastrikers/match_summary.lua
Not done by me, just took what's live to the git
Live
=> feat: match2 for omegastrikers

components/infobox/wikis/starcraft2/infobox_league_custom.lua
Fix typo in sc2 infobox league
live
=> Fix typo in sc2 infobox league

standard/info/wikis/fighters/info.lua
Add `Under Night In-Birth II` game data to `Module:Info` on fighters wiki
=> Add `Under Night In-Birth II` game data to `Module:Info`

components/infobox/commons/infobox_league_temp.lua
Fix series linking in infobox league temp
dev
=> Fix series linking in infobox league temp

standard/links/commons/links.lua, standard/links/commons/links_priority_groups.lua, stylesheets/commons/Icons.css
=> Add chzzk icon

components/infobox/wikis/starcraft2/infobox_league_custom.lua
=> fix: error when no race breakdown on sc2

components/infobox/wikis/starcraft/infobox_league_custom.lua
Refactor broodwar infobox league
- add annos where missing
- make use of #3669
- make use of #3663
- make use of #3702
- use class inheritance
dev
=> Refactor broodwar infobox league

components/infobox/wikis/apexlegends/infobox_person_player_custom.lua
kano mentioned that the display is wrong after the status adjusts we did.
This PR fixes it.
Note: Yes i know `_args` is bad. It will be killed in a later PR, so OOS for this PR.
dev
=> fix apex status display in infobox player

components/infobox/wikis/starcraft/infobox_league_custom.lua, components/infobox/wikis/starcraft2/infobox_league_custom.lua
fix typos in chronology computation on sc/sc2 infoboxes league
live on phone
=> Fix: typo in chronology computation

components/infobox/wikis/starcraft/infobox_league_custom.lua, components/infobox/wikis/starcraft2/infobox_league_custom.lua
No prio but simple fix
Fix a typo in sc(2) infobox league that causes an issue with YmapX edge cases
live
=> Fix issue with YmapX edge case in SC infoboxes

components/infobox/wikis/ageofempires/infobox_league_custom.lua
Refactor AOE infobox league
initial test okay, contributors tested more
https://discord.com/channels/93055209017729024/717412628330446929/1192478032510849055
=> Refactor AOE infobox league

standard/info/wikis/leagueoflegends/info.lua, standard/info/wikis/wildrift/info.lua
Can be done thanks to the great job @LuckeLucky in converting those wikis for match1->match2 legacy wrapper
=> feat: update match2 status of lol and wr

components/infobox/wikis/apexlegends/infobox_league_custom.lua, components/infobox/wikis/halo/infobox_league_custom.lua, components/infobox/wikis/rainbowsix/infobox_league_custom.lua, components/infobox/wikis/rocketleague/infobox_league_custom.lua
Refactor more infoboxes league (the not small but also not super big ones)
- add annos where missing
- make use of #3669
- make use of #3663
- make use of #3702
- use class inheritance
initial tests okay, letting contributors test too
=> Refactor more infoboxes league

components/infobox/wikis/warcraft/infobox_league_custom.lua
Refactor warcraft infobox league
dev
=> Refactor warcraft infobox league

components/infobox/commons/infobox_league_temp.lua, components/infobox/wikis/fighters/infobox_league_custom.lua
Refactor fighters infobox league
- initial test on 1 page okay
- additional tests via contributors due to changing quite a lot and not being familiar with the wiki
- https://discord.com/channels/93055209017729024/202549269134180352/1192418756387930173
=> Refactor fighters infobox league

components/infobox/wikis/halo/infobox_patch_custom.lua, components/infobox/wikis/rainbowsix/infobox_weapon_custom.lua, components/match2/commons/match_summary_base.lua
=> fix: various annotation typos

components/infobox/commons/infobox_skill.lua, components/infobox/wikis/starcraft/infobox_skill_custom.lua
=> Refactor infobox skill on commons and sc1

components/infobox/wikis/counterstrike/infobox_league_custom.lua
Refactor cs infobox league
- initial test okay
- more testing via contributors
=> Refactor cs infobox league

components/match2/wikis/arenafps/match_legacy.lua
Adding Match legacy for Arena FPS's match2
=> Create Match legacy for ArenaFPS

components/infobox/wikis/counterstrike/infobox_league_custom.lua
With the recent infobox PRs, the valvetier was no longer being stored into publisher tier since before it was being grabbed from the variable. fixed that and fixed a typo.
live on wiki.
=> fix(infobox): valve tier data missing from lpdb

components/widget/widget_table.lua, components/widget/widget_table_cell.lua, components/widget/widget_table_row.lua
Should have been done in #1908, but are widgets and not infoboxes related technically (should be cleaned up at some point). Caused some issues in dev mode when using both these widgets and infobox widgets
Live
=> refactor: have widget/table import dependencies with dev

components/match2/wikis/valorant/legacy/match_group_legacy_default.lua, components/match2/wikis/valorant/legacy/match_maps_legacy.lua
Add legacy wrapper to Valorant.
[sandbox](https://liquipedia.net/valorant/User:LuckeLucky/sandbox/2)
=> Add legacy wrapper to Valorant 

components/hidden_data_box/wikis/starcraft2/hidden_data_box_custom.lua, components/infobox/wikis/starcraft2/infobox_building_custom.lua, components/infobox/wikis/starcraft2/infobox_campaign_mission_custom.lua, components/infobox/wikis/starcraft2/infobox_league_custom.lua, components/infobox/wikis/starcraft2/infobox_map_custom.lua, components/infobox/wikis/starcraft2/infobox_patch_custom.lua, components/infobox/wikis/starcraft2/infobox_person_custom.lua, components/infobox/wikis/starcraft2/infobox_person_map_maker_custom.lua, components/infobox/wikis/starcraft2/infobox_series_custom.lua, components/infobox/wikis/starcraft2/infobox_show_custom.lua, components/infobox/wikis/starcraft2/infobox_skill_custom.lua, components/infobox/wikis/starcraft2/infobox_strategy_custom.lua, components/infobox/wikis/starcraft2/infobox_team_custom.lua, components/infobox/wikis/starcraft2/infobox_unit_custom.lua, components/infobox/wikis/starcraft2/infobox_unofficial_world_champion_custom.lua, components/match2/wikis/starcraft2/brkts_wiki_specific.lua, components/opponent/wikis/starcraft2/player_ext_custom.lua, components/participant_table/wikis/starcraft2/participant_table_custom.lua, components/prize_pool/wikis/starcraft2/prize_pool_award_custom.lua, components/prize_pool/wikis/starcraft2/prize_pool_custom.lua, components/results_table/wikis/starcraft2/results_table_custom.lua, components/squad/wikis/starcraft2/squad_custom.lua, components/tournaments_listing/wikis/starcraft2/tournaments_listing_card_list_custom.lua, standard/tier/wikis/starcraft2/tier_custom.lua
Remove redundant `requireDevIfEnabled` from sc2 git modules
N/A
=> Remove `requireDevIfEnabled` from sc2 git modules

components/hidden_data_box/wikis/starcraft/hidden_data_box_custom.lua, components/hidden_data_box/wikis/stormgate/hidden_data_box_custom.lua, components/infobox/wikis/starcraft/infobox_building_custom.lua, components/infobox/wikis/starcraft/infobox_league_custom.lua, components/infobox/wikis/starcraft/infobox_map_custom.lua, components/infobox/wikis/starcraft/infobox_person_player_custom.lua, components/infobox/wikis/starcraft/infobox_series_custom.lua, components/infobox/wikis/starcraft/infobox_skill_custom.lua, components/infobox/wikis/starcraft/infobox_strategy_custom.lua, components/infobox/wikis/starcraft/infobox_team_custom.lua, components/infobox/wikis/starcraft/infobox_unit_custom.lua, components/infobox/wikis/stormgate/infobox_league_custom.lua, components/infobox/wikis/stormgate/infobox_team_custom.lua, components/match2/wikis/starcraft/brkts_wiki_specific.lua, components/match2/wikis/stormgate/brkts_wiki_specific.lua, components/opponent/wikis/starcraft/player_ext_custom.lua, components/participant_table/wikis/starcraft/participant_table_custom.lua, components/participant_table/wikis/stormgate/participant_table_custom.lua, components/prize_pool/wikis/starcraft/prize_pool_award_custom.lua, components/prize_pool/wikis/starcraft/prize_pool_custom.lua, components/prize_pool/wikis/stormgate/prize_pool_award_custom.lua, components/prize_pool/wikis/stormgate/prize_pool_custom.lua, components/squad/wikis/starcraft/squad_custom.lua, standard/tier/wikis/starcraft/tier_custom.lua
Remove redundant `requireDevIfEnabled` from bw & stormgate git modules
N/A
=> Remove redundant `requireDevIfEnabled` from bw & stormgate git modules

components/hidden_data_box/wikis/warcraft/hidden_data_box_custom.lua, components/infobox/wikis/warcraft/infobox_building_custom.lua, components/infobox/wikis/warcraft/infobox_character_custom.lua, components/infobox/wikis/warcraft/infobox_company_custom.lua, components/infobox/wikis/warcraft/infobox_item_custom.lua, components/infobox/wikis/warcraft/infobox_league_custom.lua, components/infobox/wikis/warcraft/infobox_map_custom.lua, components/infobox/wikis/warcraft/infobox_patch_custom.lua, components/infobox/wikis/warcraft/infobox_skill_custom.lua, components/infobox/wikis/warcraft/infobox_strategy_custom.lua, components/infobox/wikis/warcraft/infobox_team_custom.lua, components/infobox/wikis/warcraft/infobox_unit_custom.lua, components/match2/wikis/warcraft/brkts_wiki_specific.lua, components/match2/wikis/warcraft/get_match_group_copy_paste_wiki.lua, components/match2/wikis/warcraft/match_group_input_custom.lua, components/match2/wikis/warcraft/match_group_util_custom.lua, components/match2/wikis/warcraft/match_legacy.lua, components/match2/wikis/warcraft/match_summary.lua, components/opponent/wikis/warcraft/opponent_custom.lua, components/opponent/wikis/warcraft/opponent_display_custom.lua, components/opponent/wikis/warcraft/player_display_custom.lua, components/opponent/wikis/warcraft/player_ext_custom.lua, components/participant_table/wikis/warcraft/participant_table_custom.lua, components/prize_pool/wikis/warcraft/prize_pool_custom.lua, components/prize_pool/wikis/warcraft/prize_pool_legacy_award_custom.lua, components/prize_pool/wikis/warcraft/prize_pool_legacy_custom.lua, components/squad/wikis/warcraft/squad_custom.lua, standard/tier/wikis/warcraft/tier_custom.lua
Remove redundant `requireDevIfEnabled` from warcraft git modules
N/A
=> Remove redundant `requireDevIfEnabled` from warcraft git modules

components/earnings/wikis/rocketleague/earnings.lua, components/hidden_data_box/wikis/rocketleague/hidden_data_box_custom.lua, components/infobox/extensions/wikis/rocketleague/years_active.lua, components/infobox/wikis/rocketleague/infobox_company_custom.lua, components/infobox/wikis/rocketleague/infobox_league_custom.lua, components/infobox/wikis/rocketleague/infobox_team_custom.lua, components/infobox/wikis/rocketleague/infobox_unit_car.lua, components/match2/wikis/rocketleague/brkts_wiki_specific.lua, components/match2/wikis/rocketleague/legacy/legacy_match_list.lua, components/match2/wikis/rocketleague/match_group_display_bracket_custom.lua, components/match2/wikis/rocketleague/match_group_input_custom.lua, components/match2/wikis/rocketleague/match_summary.lua, components/match2/wikis/rocketleague/player_ext_custom.lua, components/opponent/wikis/rocketleague/opponent_display_custom.lua, components/prize_pool/wikis/rocketleague/prize_pool_custom.lua, components/squad/wikis/rocketleague/squad_custom.lua, standard/tier/wikis/rocketleague/tier_custom.lua
Remove redundant `requireDevIfEnabled` from rl git modules
N/A
=> Remove redundant `requireDevIfEnabled` from rl git modules

components/hidden_data_box/wikis/leagueoflegends/hidden_data_box_custom.lua, components/infobox/wikis/leagueoflegends/infobox_league_custom.lua, components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua, components/infobox/wikis/leagueoflegends/infobox_team_custom.lua, components/infobox/wikis/leagueoflegends/infobox_unit_champion.lua, components/match2/wikis/leagueoflegends/big_match.lua, components/match2/wikis/leagueoflegends/brkts_wiki_specific.lua, components/match2/wikis/leagueoflegends/match_group_input_custom.lua, components/match2/wikis/leagueoflegends/match_legacy.lua, components/match2/wikis/leagueoflegends/match_summary.lua, components/prize_pool/wikis/leagueoflegends/prize_pool_custom.lua, components/prize_pool/wikis/leagueoflegends/prize_pool_legacy_custom.lua, components/squad/wikis/leagueoflegends/squad_custom.lua
Remove redundant `requireDevIfEnabled` from cs git modules
N/A
=> Remove redundant `requireDevIfEnabled` from lol git modules

components/hidden_data_box/wikis/dota2/hidden_data_box_custom.lua, components/infobox/wikis/dota2/infobox_company_custom.lua, components/infobox/wikis/dota2/infobox_league_custom.lua, components/infobox/wikis/dota2/infobox_patch_custom.lua, components/infobox/wikis/dota2/infobox_person_user_custom.lua, components/infobox/wikis/dota2/infobox_series_custom.lua, components/infobox/wikis/dota2/infobox_team_custom.lua, components/match2/wikis/dota2/match_group_input_custom.lua, components/match2/wikis/dota2/match_legacy.lua, components/match2/wikis/dota2/match_summary.lua, components/prize_pool/wikis/dota2/prize_pool_award_custom.lua, components/prize_pool/wikis/dota2/prize_pool_custom.lua, components/prize_pool/wikis/dota2/prize_pool_legacy_custom.lua, components/squad/wikis/dota2/squad_custom.lua
Remove redundant `requireDevIfEnabled` from dota git modules
N/A
=> Remove redundant `requireDevIfEnabled` from dota git modules

components/infobox/wikis/fighters/infobox_series_custom.lua
- it was already used without being on the git, so copied it over ....
- cleanup
- kicking totalprizepool display as per message in #templates-help channel on discord
by contributors via dev
=> Add fighters series infobox

components/match2/wikis/arenafps/get_match_group_copy_paste_wiki.lua
Setting up match 2 for Arena fps
https://liquipedia.net/arenafps/Special:RunQuery/BracketCopyPaste
https://liquipedia.net/arenafps/Special:RunQuery/MatchListCopyPaste
=> Setting up MatchGroup CopyPaste for ArenaFPS

components/match2/wikis/arenafps/get_match_group_copy_paste_wiki.lua, components/match2/wikis/arenafps/match_group_input_custom.lua, components/match2/wikis/arenafps/match_legacy.lua, components/match2/wikis/arenafps/match_summary.lua
Feature branch for the different ArenaFPS PR for match2. See those for me information
=> feat: match2 for ArenaFPS

components/faction/commons/faction.lua, components/infobox/wikis/trackmania/infobox_person_player_custom.lua, components/infobox/wikis/warcraft/infobox_person_player_custom.lua, components/infobox/wikis/worldoftanks/infobox_person_player_custom.lua, components/infobox/wikis/worldofwarcraft/infobox_person_player_custom.lua, components/infobox/wikis/zula/infobox_person_player_custom.lua
Refactor first batch (5) of infoboxes player
dev
=> Refactor first batch (5) of infoboxes player

components/infobox/wikis/apexlegends/infobox_person_player_custom.lua, components/infobox/wikis/arenafps/infobox_person_player_custom.lua, components/infobox/wikis/arenaofvalor/infobox_person_player_custom.lua, components/infobox/wikis/brawlhalla/infobox_person_player_custom.lua, components/infobox/wikis/callofduty/infobox_person_player_custom.lua
Refactor second batch (5) of infoboxes player
dev
=> Refactor second batch (5) of infoboxes player

components/infobox/wikis/clashroyale/infobox_person_player_custom.lua, components/infobox/wikis/crossfire/infobox_person_player_custom.lua, components/infobox/wikis/fifa/infobox_person_player_custom.lua, components/infobox/wikis/fighters/infobox_person_player_custom.lua, components/infobox/wikis/formula1/infobox_person_player_custom.lua, components/infobox/wikis/fortnite/infobox_person_player_custom.lua, components/infobox/wikis/freefire/infobox_person_player_custom.lua, components/infobox/wikis/halo/infobox_person_player_custom.lua, components/infobox/wikis/hearthstone/infobox_person_player_custom.lua, components/infobox/wikis/heroes/infobox_person_player_custom.lua, components/infobox/wikis/naraka/infobox_person_player_custom.lua, components/infobox/wikis/osu/infobox_person_player_custom.lua, components/infobox/wikis/pokemon/infobox_person_player_custom.lua, components/infobox/wikis/simracing/infobox_person_player_custom.lua, components/infobox/wikis/splatoon/infobox_person_player_custom.lua, components/infobox/wikis/tetris/infobox_person_player_custom.lua
Refactor third batch (16) of infoboxes player
dev
=> Refactor third batch (16) of infoboxes player

components/infobox/wikis/counterstrike/infobox_league_custom.lua
Fix some annotations in CS infobox league
VSCode
=> Fix some annotations in CS infobox league

components/hidden_data_box/commons/hidden_data_box.lua
Catch a nil in HDB and also fix an annotation warning
dev to live
=> Fix: Catch a nil in HDB

components/infobox/commons/infobox_character.lua, components/infobox/commons/infobox_manufacturer.lua, components/infobox/commons/infobox_map.lua, components/infobox/commons/infobox_weapon.lua, components/mvp_table/commons/mvp_table.lua, standard/abbreviation.lua, standard/game.lua, standard/tournament_structure.lua
=> Fix some anno warnings

components/infobox/commons/infobox_league.lua, components/infobox/wikis/ageofempires/infobox_league_custom.lua, components/infobox/wikis/apexlegends/infobox_league_custom.lua, components/infobox/wikis/arenafps/infobox_league_custom.lua, components/infobox/wikis/arenaofvalor/infobox_league_custom.lua, components/infobox/wikis/brawlhalla/infobox_league_custom.lua, components/infobox/wikis/brawlstars/infobox_league_custom.lua, components/infobox/wikis/callofduty/infobox_league_custom.lua, components/infobox/wikis/clashofclans/infobox_league_custom.lua, components/infobox/wikis/clashroyale/infobox_league_custom.lua
Rename class `InfoboxLeagueTemp` to `InfoboxLeague` - part 1
broken into several PRs to not kill the server
N/A
=> Rename class `InfoboxLeagueTemp` to `InfoboxLeague` - part 1

components/infobox/wikis/counterstrike/infobox_league_custom.lua, components/infobox/wikis/criticalops/infobox_league_custom.lua, components/infobox/wikis/crossfire/infobox_league_custom.lua, components/infobox/wikis/dota2/infobox_league_custom.lua, components/infobox/wikis/fifa/infobox_league_custom.lua, components/infobox/wikis/fighters/infobox_league_custom.lua, components/infobox/wikis/formula1/infobox_league_custom.lua, components/infobox/wikis/fortnite/infobox_league_custom.lua, components/infobox/wikis/freefire/infobox_league_custom.lua, components/infobox/wikis/halo/infobox_league_custom.lua
Rename class `InfoboxLeagueTemp` to `InfoboxLeague` - part 2
N/A
=> Rename class `InfoboxLeagueTemp` to `InfoboxLeague` - part 2

components/infobox/wikis/hearthstone/infobox_league_custom.lua, components/infobox/wikis/heroes/infobox_league_custom.lua, components/infobox/wikis/leagueoflegends/infobox_league_custom.lua, components/infobox/wikis/magic/infobox_league_custom.lua, components/infobox/wikis/mobilelegends/infobox_league_custom.lua, components/infobox/wikis/naraka/infobox_league_custom.lua, components/infobox/wikis/osu/infobox_league_custom.lua, components/infobox/wikis/overwatch/infobox_league_custom.lua, components/infobox/wikis/pokemon/infobox_league_custom.lua, components/infobox/wikis/pubg/infobox_league_custom.lua
Rename class `InfoboxLeagueTemp` to `InfoboxLeague` - part 3
N/A
=> Rename class `InfoboxLeagueTemp` to `InfoboxLeague` - part 3

components/infobox/wikis/pubgmobile/infobox_league_custom.lua, components/infobox/wikis/rainbowsix/infobox_league_custom.lua, components/infobox/wikis/rocketleague/infobox_league_custom.lua, components/infobox/wikis/sideswipe/infobox_league_custom.lua, components/infobox/wikis/simracing/infobox_league_custom.lua, components/infobox/wikis/splatoon/infobox_league_custom.lua, components/infobox/wikis/squadrons/infobox_league_custom.lua, components/infobox/wikis/starcraft/infobox_league_custom.lua, components/infobox/wikis/starcraft2/infobox_league_custom.lua
Rename class `InfoboxLeagueTemp` to `InfoboxLeague` - part 4
N/A
=> Rename class `InfoboxLeagueTemp` to `InfoboxLeague` - part 4

components/infobox/wikis/stormgate/infobox_league_custom.lua, components/infobox/wikis/teamfortress/infobox_league_custom.lua, components/infobox/wikis/tetris/infobox_league_custom.lua, components/infobox/wikis/tft/infobox_league_custom.lua, components/infobox/wikis/trackmania/infobox_league_custom.lua, components/infobox/wikis/valorant/infobox_league_custom.lua, components/infobox/wikis/warcraft/infobox_league_custom.lua, components/infobox/wikis/wildrift/infobox_league_custom.lua, components/infobox/wikis/worldoftanks/infobox_league_custom.lua
Rename class `InfoboxLeagueTemp` to `InfoboxLeague` - part 5
N/A
=> Rename class `InfoboxLeagueTemp` to `InfoboxLeague` - part 5

components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua, components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua, components/infobox/wikis/overwatch/infobox_person_player_custom.lua, components/infobox/wikis/pubg/infobox_person_player_custom.lua, components/infobox/wikis/pubgmobile/infobox_person_player_custom.lua, components/infobox/wikis/smash/infobox_person_player_custom.lua, components/infobox/wikis/teamfortress/infobox_person_player_custom.lua, components/infobox/wikis/tft/infobox_person_player_custom.lua, components/infobox/wikis/valorant/infobox_person_player_custom.lua, components/infobox/wikis/wildrift/infobox_person_player_custom.lua
Fourth batch of infobox player refactor
=> Fourth batch (10) of infobox player refactor

components/infobox/wikis/ageofempires/infobox_person_player_custom.lua, components/infobox/wikis/starcraft/infobox_person_player_custom.lua, definitions/liquipedia_db.lua
Refactor bw and aoe infobox player
=> Refactor bw and aoe infobox player

components/infobox/wikis/leagueoflegends/infobox_team_custom.lua, components/infobox/wikis/valorant/infobox_team_custom.lua
Adds an Affiliate cell to Valorants Infobox Team
=> Adding Affiliate to Team Infoboxes

standard/info/wikis/smite/info.lua
Creates the Info module for Smite. Originally created by Hesketh
=> Create Smite Info

stylesheets/commons/Miscellaneous.css
Moving tie color to variables since we have to make it work with dark mode.
Directly by changing the variable using the dev console for [this page](https://liquipedia.net/dota2/Team_Liquid/Played_Matches)
=> Improve visibility for tie matches in dark mode

components/infobox/commons/infobox_building.lua, components/infobox/wikis/clashofclans/infobox_building_custom.lua, components/infobox/wikis/starcraft/infobox_building_custom.lua
Refactor infobox building
Note: SC2 and WC were refactored already
dev
=> Refactor infobox building

standard/info/wikis/arenafps/info.lua
#3767 implemented match2 for arenafps
=> chore: update arenafps match2 status

components/infobox/commons/infobox_character.lua, components/infobox/wikis/apexlegends/infobox_character_custom.lua, components/infobox/wikis/omegastrikers/infobox_character_custom.lua
Refactor infobox character
Note: WC was refactored already
dev
=> Refactor infobox character

components/infobox/commons/infobox_strategy.lua, components/infobox/wikis/starcraft/infobox_strategy_custom.lua
Refactor infobox strategy
Note: SC2 and WC were refactored already
dev
=> Refactor infobox strategy

components/infobox/wikis/worldoftanks/infobox_league_custom.lua
Fix WoT publishertier storage in infobox league
dev
=> Fix WoT publishertier storage in infobox league

components/infobox/wikis/smite/infobox_person_player_custom.lua
Creates the Infobox Player for Smite
dev
=> Create Smite Infobox Player

components/match2/wikis/apexlegends/match_summary.lua
Clock icon was missing a class to display correctly
Tested it with adding the class in the console and it works
=> add missing class to clock icon

components/match2/wikis/apexlegends/match_summary.lua
Since all stream display is game based, populate the match streams into the game object
Live
=> fix(m2, apex): fix stream display

components/match2/wikis/apexlegends/match_summary.lua
Always show rank/placement, even on ongoing and upcoming. Defaulting to the index
Live
=> feat(m2, apex): always display rank/placement even when not finalized

components/match2/wikis/apexlegends/match_summary.lua
Fixes couple of issues primarily coming from using `{{ShowMatch}}`
Live
=> fix(m2, apex): issues with showmatch

standard/icon_data.lua
Saw that on SC2 the red-x is used as a veto icon too, so adding a separate use name here to help distinguish the use of it for the future.
=> Add veto to icon_data.lua

components/match2/commons/get_match_group_copy_paste_wiki_base.lua, components/match2/wikis/apexlegends/get_match_group_copy_paste_wiki.lua
Create Copy Pastable for Apex's match2
Live
=> feat(m2, apex): create copy pastable

components/infobox/wikis/mobilelegends/infobox_unit_hero_custom.lua
=> Refactor ml infobox hero

components/hidden_data_box/commons/hidden_data_box_custom.lua, components/hidden_data_box/test/hidden_data_box_test.lua, components/hidden_data_box/wikis/ageofempires/hidden_data_box_custom.lua, components/hidden_data_box/wikis/apexlegends/hidden_data_box_custom.lua, components/hidden_data_box/wikis/arenaofvalor/hidden_data_box_custom.lua, components/hidden_data_box/wikis/brawlstars/hidden_data_box_custom.lua, components/hidden_data_box/wikis/counterstrike/hidden_data_box_custom.lua, components/hidden_data_box/wikis/dota2/hidden_data_box_custom.lua, components/hidden_data_box/wikis/freefire/hidden_data_box_custom.lua, components/hidden_data_box/wikis/halo/hidden_data_box_custom.lua, components/hidden_data_box/wikis/hearthstone/hidden_data_box_custom.lua, components/hidden_data_box/wikis/leagueoflegends/hidden_data_box_custom.lua, components/hidden_data_box/wikis/mobilelegends/hidden_data_box_custom.lua, components/hidden_data_box/wikis/overwatch/hidden_data_box_custom.lua, components/hidden_data_box/wikis/pokemon/hidden_data_box_custom.lua, components/hidden_data_box/wikis/pubg/hidden_data_box_custom.lua, components/hidden_data_box/wikis/pubgmobile/hidden_data_box_custom.lua, components/hidden_data_box/wikis/rainbowsix/hidden_data_box_custom.lua, components/hidden_data_box/wikis/rocketleague/hidden_data_box_custom.lua, components/hidden_data_box/wikis/simracing/hidden_data_box_custom.lua, components/hidden_data_box/wikis/splatoon/hidden_data_box_custom.lua, components/hidden_data_box/wikis/squadrons/hidden_data_box_custom.lua, components/hidden_data_box/wikis/starcraft/hidden_data_box_custom.lua, components/hidden_data_box/wikis/starcraft2/hidden_data_box_custom.lua, components/hidden_data_box/wikis/stormgate/hidden_data_box_custom.lua, components/hidden_data_box/wikis/teamfortress/hidden_data_box_custom.lua, components/hidden_data_box/wikis/trackmania/hidden_data_box_custom.lua, components/hidden_data_box/wikis/valorant/hidden_data_box_custom.lua, components/hidden_data_box/wikis/warcraft/hidden_data_box_custom.lua, components/hidden_data_box/wikis/wildrift/hidden_data_box_custom.lua
note i already did the change on half the wikis so we can easily deploy this pr in one go without killing the server
Fix annos of the return from Custom HiddenDataBox
With #3876 the return was changed from string to Html.
This PR fixes the annos in the according customs.
VSCode
=> Fix: custom hdb return annos string --> Html

components/infobox/wikis/starcraft2/infobox_team_custom.lua
Fix sc2 infobox team earnings display
dev to live
=> Fix: Sc2 infobox team earnings display

components/match2/wikis/apexlegends/match_group_input_custom.lua, components/match2/wikis/apexlegends/match_summary.lua
=> feat(m2. apex): status (up, down etc) coloring

components/infobox/commons/custom/infobox_character_custom.lua, components/infobox/commons/custom/infobox_company_custom.lua, components/infobox/commons/custom/infobox_game_custom.lua, components/infobox/commons/custom/infobox_league_custom.lua, components/infobox/commons/custom/infobox_manufacturer_custom.lua, components/infobox/commons/custom/infobox_patch_custom.lua, components/infobox/commons/custom/infobox_series_custom.lua, components/infobox/commons/custom/infobox_show_custom.lua, components/infobox/commons/custom/infobox_strategy_custom.lua, components/infobox/commons/custom/infobox_unofficial_world_champion_custom.lua, components/infobox/commons/custom/infobox_weapon_custom.lua, components/infobox/commons/custom/infobox_website_custom.lua
- no functional changes, just code style
- use class inheritance
- add annotations where missing
N/A
=> Cleanup commons infobox customs

components/match2/commons/match.lua, components/match2/wikis/valorant/match_group_input_custom.lua
Inherit common match vars to map.
/dev
=> inherit match variables into game on valorant

stylesheets/commons/BattleRoyale/NavigationTabs.less, stylesheets/commons/BattleRoyale/Panel.less, stylesheets/commons/BattleRoyale/PanelTable.less
This closes ticket https://gitlab.com/teamliquid-dev/liquipedia/web/issue-bucket/-/issues/36
Discussed with Kevin what changes he wanted. There are some borders and hover colors added.
I edited on the live wiki together with Kevin.
=> BR - background color for navigation

components/infobox/wikis/formula1/infobox_person_player_custom.lua
Move params to appear under driver info box instead of stats box
dev
=> Move params on driver infobox (f1)

components/infobox/commons/infobox_company.lua, components/infobox/commons/infobox_series.lua, components/infobox/wikis/starcraft/infobox_series_custom.lua, components/infobox/wikis/starcraft2/infobox_series_custom.lua
As mentioned on discord: https://discord.com/channels/93055209017729024/874304000718172200/1202091908244176906
Fixing capitalization and also changing to a more consistent terminology.
Just display text :p
=> feat(infobox): more consistent prize pool terminology

components/match2/wikis/valorant/match_summary.lua, stylesheets/commons/Brackets.less
=> Add css classes for valorant side colors

components/match2/wikis/magic/match_group_input_custom.lua, components/match2/wikis/magic/match_legacy.lua, components/match2/wikis/magic/match_summary.lua
Not done by me, just took what's live to the git
Live?
=> feat: match2 for magic

components/match2/wikis/battlerite/match_group_input_custom.lua
=> Fix wikiname in magic comment

components/match2/wikis/battlerite/match_group_input_custom.lua
Remove all other automatic bestof handling, but missed to remove this.
=> fix: remove non-intended bestof handling in battlerite

components/faction/wikis/ageofempires/faction_data.lua, components/faction/wikis/ageofempires/faction_icon_data.lua
Completes the faction data modules for AoE.
"live" https://liquipedia.net/ageofempires/Module:Faction/Data
=> AoE: Add complete faction data

components/notability/wikis/ageofempires/notability_checker_config.lua
Adjusts the notability calculation to the changes contributors voted for [here](https://discord.com/channels/93055209017729024/1169346788201869402/1196749840047144960):
- "Remove" Open for discussion range
- Do not award points for showmatches
N/A
=> AoE: Adjust notability config for 2024

components/infobox/commons/infobox_person.lua, standard/tier/wikis/formula1/tier_data.lua
Add misc as tier for use on the F1 wiki
tested live
=> Add misc as tier (F1)

components/match2/wikis/apexlegends/get_match_group_copy_paste_wiki.lua, components/match2/wikis/arenafps/get_match_group_copy_paste_wiki.lua
=> chore: fix copy-paste annotations

components/squad/commons/squad.lua, components/squad/commons/squad_custom.lua, components/squad/commons/squad_row.lua, components/squad/wikis/apexlegends/squad_custom.lua, components/squad/wikis/arenaofvalor/squad_custom.lua, components/squad/wikis/counterstrike/squad_custom.lua, components/squad/wikis/dota2/squad_custom.lua, components/squad/wikis/halo/squad_custom.lua, components/squad/wikis/leagueoflegends/squad_custom.lua, components/squad/wikis/mobilelegends/squad_custom.lua, components/squad/wikis/overwatch/squad_custom.lua, components/squad/wikis/rainbowsix/squad_custom.lua, components/squad/wikis/rocketleague/squad_custom.lua, components/squad/wikis/smash/squad_custom.lua, components/squad/wikis/starcraft/squad_custom.lua, components/squad/wikis/starcraft2/squad_custom.lua, components/squad/wikis/valorant/squad_custom.lua, components/squad/wikis/warcraft/squad_custom.lua, components/squad/wikis/wildrift/squad_custom.lua
Add annos to Squad modules and clean them up a tiny bit
dev preview tests
=> Add annos to Squad modules

components/match2/wikis/leagueoflegends/big_match.lua
=> Inherit match variables into map on leagueoflegends BigMatch

standard/tier/wikis/formula1/tier_data.lua
Fix misc tier.
Thanks martin
Tested live
=> Fix misc tier (F1)

components/match2/wikis/arenaofvalor/match_group_input_custom.lua
=> chore: fix indentation aov

components/infobox/commons/infobox_skill.lua
Add basic lpdb storage to infobox skill
dev
=> Add basic lpdb storage to infobox skill

components/infobox/wikis/stormgate/infobox_building_custom.lua
Add stormgate infobox building
to be done
=> Add stormgate infobox building

components/match2/wikis/apexlegends/match_group_input_custom.lua
=> fix(m2, apex): map date parsing

components/infobox/commons/infobox_unit.lua, components/infobox/wikis/stormgate/infobox_unit_custom.lua
=> Add stormgate infobox unit

components/match2/wikis/apexlegends/match_summary.lua
=> feat(m2, apex): improve sorting for upcoming matches

components/match2/wikis/apexlegends/match_summary.lua
Add icons to the status column
dev module
=> feat(m2, apex): add icons to the status field

components/infobox/wikis/valorant/infobox_map_custom.lua
Creates a new standardized Map infobox for Valornat
dev
=> Create Map Infobox for Valorant

components/opponent/commons/opponent.lua
Change nil returns into error, at invalid inputs. 
Most of the time we don't catch the nil return properly and throws an error in the next step
Tested abit on dota2
=> refactor(opponent): remove nil returns

components/infobox/commons/infobox_company.lua, components/infobox/commons/infobox_person.lua, components/infobox/commons/infobox_team.lua, components/infobox/wikis/brawlhalla/infobox_person_player_custom.lua, components/infobox/wikis/dota2/infobox_league_custom.lua, components/infobox/wikis/fortnite/infobox_person_player_custom.lua, components/infobox/wikis/fortnite/infobox_team_custom.lua, components/infobox/wikis/starcraft/infobox_person_player_custom.lua, components/infobox/wikis/starcraft/infobox_team_custom.lua, components/infobox/wikis/starcraft2/infobox_person_player_custom.lua, components/infobox/wikis/starcraft2/infobox_team_custom.lua, components/infobox/wikis/stormgate/infobox_person_player_custom.lua, components/matches_schedule_display/commons/matches_schedule_display.lua, components/notability/commons/notability_checker.lua, components/tournaments_listing/commons/tournaments_listing_card_list.lua
Set the wiki up for future successes
=> refactor: use wiki lang instead of hardcoded english

components/external_media_links/external_media_link.lua, components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua, components/match2/wikis/fifa/match_group_input_custom.lua, components/match2/wikis/stormgate/match_group_input_custom.lua, components/match2/wikis/warcraft/match_group_input_custom.lua, components/ratings/ratings.lua, components/standings/commons/starcraft_starcraft2/standings_storage_starcraft_legacy.lua, standard/date_ext.lua, standard/logic.lua
=> Fix some annos

components/infobox/extensions/commons/player_introduction.lua
Changed 1971 to default
Discussed [here](https://discord.com/channels/93055209017729024/874304000718172200/1206494323365904415)
LIve ig?
=> Change 1971 to default

spec/array_spec.lua, standard/array.lua
Add `Array.readCommaSeparatedList` as per suggestion in #3956
test case
Can remove a function from some custom modules after this is merged.
=> Add `Array.readCommaSeparatedList`

components/infobox/extensions/wikis/stormgate/infobox_extension_attack.lua, components/infobox/wikis/stormgate/infobox_building_custom.lua, components/infobox/wikis/stormgate/infobox_unit_custom.lua
Make use of #3985
preview and storage tests
=> Make use of #3985

components/infobox/commons/infobox.lua, definitions/mw.lua, spec/flags_spec.lua, spec/prize_pool_spec.lua, spec/test_helper.lua
The Infobox mocking wasn't working. This PR fixes and adjusts tests to their proper states
=> test: fix infobox mock

components/squad/wikis/smite/squad_custom.lua
Squad for SMITE 
This is clean port of the current Mobile Legends revision last updated Feb 5 2024 (meant this incl. #3931), only the mobilelegends text were replaced, All stuff should match the need for the wiki afaik
currently Live
=> feat(squad): setup for smite

components/match2/wikis/dota2/legacy/match_group_legacy_default.lua, components/match2/wikis/dota2/legacy/match_maps_legacy.lua
Add Legacy wrapper to dota2
live
=> Add Dota2 legacy wrapper

components/infobox/wikis/formula1/infobox_person_player_custom.lua
Changed "Abbrevitions" to "Abbreviations"
=> fix(infobox): typo in F1's person infobox

components/infobox/wikis/stormgate/infobox_building_custom.lua, components/infobox/wikis/stormgate/infobox_unit_custom.lua
Add `upgrades_to` in stormgate infobox building as per request by contributors
dev
=> feat(stormgate infobox building/unit): Add `upgrades_to` support

standard/info/wikis/dota2/info.lua
The match1 -> match2 legacy conversion for dota2 is completed
=> feat: enable full match2 for dota2

components/notability/wikis/pubgmobile/notability_checker_config.lua
Updating PUBGM's notabilty checker config for 2024
dev config
=> Updating PUBGM's notabilty checker config for 2024

components/infobox/wikis/formula1/infobox_unit_car_custom.lua
Add cells for usage on car infobox. 
dev
=> feat: Add cells to F1 Car infobox

javascript/commons/FilterButtons.js, stylesheets/commons/FilterButtons.less
I have further work I want to do to JavaScript filter buttons, however, the old code base was all over the place and hard to work with to add new feature. I have refactored, from the ground up, the entire JS code for this module.
I went for a semi-MVC pattern here as it makes adding new features a lot easier as they can be added to either view or model code and not have to mix both like it was before. For example, the buttons and filtered items update based on their model (data) which is updated whenever the user clicks something.
The stuff I'm going to build on top of this refactor are a pre-defined curated set of filterable items (for tournaments lists) and and option to not store stuff to users' browsers (for match2 popups where there are multiple series in a single popup). Also will …
=> refactor(filterbuttons): complete JS module refactor

components/match2/wikis/stormgate/match_group_input_custom.lua, components/match2/wikis/warcraft/match_group_input_custom.lua
Fix(match2): cleanup wc and sg winner processing
- simplify `subgroup` code
- clean up map winner processing
dev
=> refactor(match2): improve WC and SG

components/match2/wikis/ageofempires/match_group_input_custom.lua
live since Bugfix
(sorry for not adding labels/having the usual structure here, doing these PRs with the GitHub app doesn't allow them)
=> AoE: fix empty map input in match2

components/infobox/wikis/overwatch/infobox_league_custom.lua
Adding the new S-Tier series to blizzardtiers for highlighting
=> feat: On overwatch, add OWCS as blizzardtier

components/prize_pool/wikis/ageofempires/prize_pool_custom.lua
=> AoE: Allow enabling PPT import

components/infobox/commons/infobox_widget_injector.lua, components/prize_pool/commons/prize_pool.lua, components/prize_pool/commons/prize_pool_award.lua, components/prize_pool/commons/prize_pool_award_custom.lua, components/prize_pool/commons/prize_pool_award_placement.lua, components/prize_pool/commons/prize_pool_base.lua, components/prize_pool/commons/prize_pool_custom.lua, components/prize_pool/commons/prize_pool_legacy.lua, components/prize_pool/commons/prize_pool_placement.lua, components/prize_pool/commons/prize_pool_placement_base.lua, standard/lpdb_injector.lua
Annotate commons ppt modules except for the import one as i want to slightly refactor that (in a sep. PR)
N/A // VSCode
=> docs(ppt): Annotate commons ppt modules

components/infobox/wikis/warcraft/infobox_league_custom.lua
Add modes to Warcraft infobox league as requested here
https://discord.com/channels/93055209017729024/161454541009715200/1213168855065698374
dev
=> feat: add additional modes to warcraft infobox league

components/squad/wikis/overwatch/squad_custom.lua
Debug logging sneaked into production
=> fix: remove unintended log

standard/lpdb.lua
Fix typo in for match2, and add placement
=> refactor: create model for `lpdb-placement`

components/squad/wikis/overwatch/squad_custom.lua
Fix error on all OW's squad tables. Had previously applied a quick fix but never pushed to git. Originally introduced in #3931
Live
=> fix: error on overwatch squad tables

standard/info/wikis/overwatch/info.lua
Update overwatch's match2 status to done
=> feat: update overwatch's m2 status

javascript/commons/Countdown.js, standard/links_stream.lua
Add's Kick to current countdown codebase. Can be superseded by #3111 if that goes ahead soon, but otherwise would like to merge this in time for the upcoming PGL CS2 Major and rebase the other PR if needed.
Untested but it's just adding some data and copy-pasting existing working code.
=> feat(coutdown): add Kick stream pages support

components/match2/commons/match_summary_base.lua
Make input anno optional since the input is optional
N/A
=> fix(annotation): make input anno optional

stylesheets/commons/BattleRoyale/PanelTable.less
For the BR table:
- Set a font size
- Reduce cell padding
Dev tools
=> add table font size and reduce cell padding

components/prize_pool/commons/prize_pool_import.lua
Fixing issue pointed out on discord: https://discord.com/channels/93055209017729024/372075546231832576/1215744516955312188
Pushed live as bug fix.
=> fix(ppt): `importWinners` should be parsed as bool, not number

components/match2/wikis/arenaofvalor/legacy/match_group_legacy_default.lua, components/match2/wikis/arenaofvalor/legacy/match_maps_legacy.lua
=> feat: Add legacy wrapper to arenaofvalor

components/match2/wikis/ageofempires/get_match_group_copy_paste_wiki.lua, components/match2/wikis/ageofempires/match_group_input_custom.lua, components/match2/wikis/ageofempires/match_legacy.lua
Bugfixes, CopyPaste changes requested by contributors
dev/live where necessary
=> fix(match2) Various fixes on AoE

standard/info/wikis/arenaofvalor/info.lua
=> feat: update arenaofvalor m2 status

components/prize_pool/wikis/ageofempires/prize_pool_award_custom.lua, components/prize_pool/wikis/ageofempires/prize_pool_custom.lua, components/prize_pool/wikis/apexlegends/prize_pool_custom.lua, components/prize_pool/wikis/apexlegends/prize_pool_legacy_custom.lua, components/prize_pool/wikis/arenaofvalor/prize_pool_custom.lua, components/prize_pool/wikis/brawlstars/prize_pool_custom.lua, components/prize_pool/wikis/counterstrike/prize_pool_award_custom.lua, components/prize_pool/wikis/counterstrike/prize_pool_custom.lua, components/prize_pool/wikis/counterstrike/prize_pool_legacy_custom.lua, components/prize_pool/wikis/dota2/prize_pool_award_custom.lua, components/prize_pool/wikis/dota2/prize_pool_custom.lua, components/prize_pool/wikis/dota2/prize_pool_legacy_custom.lua, components/prize_pool/wikis/formula1/prize_pool_custom.lua, components/prize_pool/wikis/fortnite/prize_pool_award_custom.lua, components/prize_pool/wikis/fortnite/prize_pool_custom.lua, components/prize_pool/wikis/fortnite/prize_pool_legacy_custom.lua, components/prize_pool/wikis/halo/prize_pool_custom.lua, components/prize_pool/wikis/leagueoflegends/prize_pool_custom.lua, components/prize_pool/wikis/leagueoflegends/prize_pool_legacy_custom.lua, components/prize_pool/wikis/mobilelegends/prize_pool_custom.lua, components/prize_pool/wikis/mobilelegends/prize_pool_legacy_custom.lua, components/prize_pool/wikis/overwatch/prize_pool_custom.lua
Add annos to custom ppt modules
part 2 of 2 (so we do not hammer the server too much)
VCSCode
=> doc(prize pool): annotate half of ppt customs

components/prize_pool/commons/prize_pool_placement_base.lua, components/prize_pool/commons/starcraft_starcraft2/prize_pool_award_starcraft.lua, components/prize_pool/commons/starcraft_starcraft2/prize_pool_legacy_starcraft.lua, components/prize_pool/commons/starcraft_starcraft2/prize_pool_starcraft.lua, components/prize_pool/wikis/pokemon/prize_pool_custom.lua, components/prize_pool/wikis/pubg/prize_pool_award_custom.lua, components/prize_pool/wikis/pubg/prize_pool_custom.lua, components/prize_pool/wikis/pubgmobile/prize_pool_award_custom.lua, components/prize_pool/wikis/pubgmobile/prize_pool_custom.lua, components/prize_pool/wikis/rainbowsix/prize_pool_custom.lua, components/prize_pool/wikis/rocketleague/prize_pool_custom.lua, components/prize_pool/wikis/tetris/prize_pool_custom.lua, components/prize_pool/wikis/trackmania/prize_pool_custom.lua, components/prize_pool/wikis/valorant/prize_pool_custom.lua, components/prize_pool/wikis/valorant/prize_pool_legacy_custom.lua, components/prize_pool/wikis/warcraft/prize_pool_custom.lua, components/prize_pool/wikis/warcraft/prize_pool_legacy_award_custom.lua, components/prize_pool/wikis/warcraft/prize_pool_legacy_custom.lua, components/prize_pool/wikis/wildrift/prize_pool_custom.lua
Add annos to custom ppt modules
part 1 of 2 (so we do not hammer the server too much)
VCSCode
=> doc(prize pool): Add annos to ppt custom modules - pt1/2

components/match2/wikis/worldoftanks/get_match_group_copy_paste_wiki.lua
Creates the Match2 Bracket Copy/Paste for World of Tanks
=> Create WoT Match2 Copy/Paste

components/match2/commons/get_match_group_copy_paste.lua
fix custom header in match2 copy pasta
=> fix custom header in match2 copy pasta

components/match2/wikis/brawlstars/legacy/match_group_legacy_default.lua, components/match2/wikis/brawlstars/legacy/match_maps_legacy.lua
=> feat: Add brawlstars legacy wrapper

standard/info/wikis/brawlstars/info.lua
=> feat: Update brawlstars match2 status

components/external_media_links/external_media_list.lua
fix anno warning in external media list
VSCode
=> fix anno warning in external media list

components/infobox/wikis/valorant/infobox_person_player_custom.lua
Somehow, the old [module](https://liquipedia.net/valorant/Module:PlayersSignatureAgents) using vardefine and stuff was not working as expected with infobox. Characters would appear, but then they wouldn't be saved to LPDB.
To fix it, I decided to create [Module:SignaturePlayerAgents](https://liquipedia.net/valorant/Module:SignaturePlayerAgents), that has almost the same behavior that the old module, but instead of returning the icons and setting variables in page, it returns a array with the top X played agents by a player in the past month.
/dev
=> feat: Update valorant signature agents module

components/match2/commons/bracket_template.lua, components/match2/commons/match_group.lua, components/match2/commons/match_group_coordinates.lua, components/match2/commons/match_group_display_bracket_template.lua, components/match2/commons/match_group_shorten_bracket.lua, components/match2/commons/match_group_util.lua, components/match2/commons/match_placement.lua, components/match2/commons/template_match.lua
Add annos to further match2 commons files
/dev (#4098, #4100 and #4102 together)
=> docs(match2): annotate to more match2 commons files

components/infobox/wikis/clashofclans/infobox_team_custom.lua
Created custom infobox team for clash of clans, they requested a custom param for clan tags [here](https://discord.com/channels/93055209017729024/784100703047122975/1221958934643081238), so that's why I made a custom^^
dev & vsc
=> feat: create custom infobox team for clash of clans
