components/match2/wikis/arenaofvalor/match_summary.lua
components/match2/wikis/brawlstars/match_group_input_custom.lua
components/match2/wikis/brawlstars/match_legacy.lua
components/match2/wikis/brawlstars/match_summary.lua
components/match2/wikis/callofduty/match_summary.lua
components/match2/wikis/dota2/match_group_input_custom.lua
components/match2/wikis/dota2/match_legacy.lua
components/match2/wikis/dota2/match_summary.lua
components/match2/wikis/halo/match_group_input_custom.lua
components/match2/wikis/halo/match_summary.lua
components/match2/wikis/mobilelegends/match_group_input_custom.lua
components/match2/wikis/mobilelegends/match_legacy.lua
components/match2/wikis/mobilelegends/match_summary.lua
components/match2/wikis/overwatch/match_group_input_custom.lua
components/match2/wikis/overwatch/match_legacy.lua
components/match2/wikis/overwatch/match_summary.lua
components/match2/wikis/pokemon/match_group_input_custom.lua
components/match2/wikis/pokemon/match_legacy.lua
components/match2/wikis/pokemon/match_summary.lua
components/match2/wikis/rainbowsix/match_group_input_custom.lua
components/match2/wikis/rainbowsix/match_legacy.lua
components/match2/wikis/splatoon/match_legacy.lua
components/match2/wikis/splitgate/match_group_input_custom.lua
components/match2/wikis/valorant/match_group_input_custom.lua
components/match2/wikis/wildrift/match_summary.lua
components/mvp_table/commons/mvp_table.lua

Standardize mvp data
- use via commons provided function to read/parse mvp input
- adjust matchSummary and Legacy storage accordingly
- fix some anno warning in mvp table
With the commons mvpTable now supporting both the new format as well as match1 legacy data we can easily adjust all wikis on match2 that have mvp data to store it in the same format
hard copy from lol

Standardize mvp data

---

components/match2/commons/match_group_input.lua
components/match2/wikis/brawlstars/match_group_input_custom.lua
components/match2/wikis/halo/match_group_input_custom.lua
components/match2/wikis/overwatch/match_group_input_custom.lua
components/match2/wikis/rainbowsix/match_group_input_custom.lua
components/match2/wikis/splitgate/match_group_input_custom.lua
components/match2/wikis/valorant/match_group_input_custom.lua

- Avoid nil
- Adjust player of team input processing. Directly set players into `opponent.match2players` instead of pushing them into `match['opponent' .. opponentIndex .. '_p' .. playerIndex]` which then later on gets made into what we now directly achieve.
This solves a bug with mvp stuff, where it expects the player info being inside `match2players` already for processing mvp input.
/dev

Adjust parsing of team players in matches on some wikis

---

components/match2/wikis/brawlstars/match_group_input_custom.lua

Add missing displayname reading for brawlstars
live, hotfix

Add missing `player.displayname` reading for brawlstars

---

components/squad/commons/squad_row.lua

Instead of listing various roles that contain coach, string match the word `coach` to determine whether a person is a coach.
As far as i can tell the class with plain role names aren't used anywhere, so they could be removed as well.
via /dev
new:
old:

Squad: Add roster-coach class for all roles containing coach

---

components/infobox/wikis/valorant/infobox_league_custom.lua
components/tournaments_listing/commons/tournaments_listing_card_list.lua
standard/highlight_conditions/wikis/valorant/highlight_conditions.lua

At the request of the wiki editors, the following changes are being made: https://discord.com/channels/93055209017729024/684060921898860569/1133875400217464833
- `|riot-highlighted=true` will add both highlighting and riot icon.
- `|riot-sponsored=true` will add only riot icon.
For all tournament lists, broadcast lists, etc, they should be using the highlight conditions module, so that only `riot-highlighted` (`publishertier` being `highlighted`) triggers that.
(Also added dev support for highlighting conditions module in tournament list).

Update VALORANT highlighting conditions

---

components/external_media_links/external_media_list.lua

ExternalMediaLinks store authors with resolved redirects, which also replaces underscores with whitespace and capitalizes the first character.
This change applies the same processing before querying to allow the same input to work.
via /dev

EMList: Resolve redirect for author before querying

---

components/prize_pool/commons/prize_pool_placement.lua
standard/placement.lua

F1 needs an array of additional placement, since the added ones cannot be substituted by the existing one we have (which also exists in F1 in a different context, would result in we putting the wrong classification if we had to sub in/out)
These included
**DNQ** (Participated, but failed to Qualify for the main race)
**DNPQ** (Participated, but failed to Pre-Qualify into the Main Qualify)
**DNS** (Participated, Does qualified, but failed to Start the main race)
**NC** (Ended a season with no points, in the past instead of providing a numbered placement, the official result will determine this as **Not Classified** but does complete every event, which is a different context of DQ)
Additionally DNF and DNP already existed so those are usable
/dev

Add F1-related placement

---

standard/region/commons/region_data.lua

Adding missing regions that are defined in `Module:Flags/MasterData`. Unless a wiki adds these to their `Module:Region/CountryData` or uses them like a country in a infobox then there should be no change to their stuff from this change as I haven't modified any existing regions' names or aliases.
It's just data :D

Add missing regions from Flags data

---

standard/game.lua

Fix a bug caused by positioning of code when to fallback to placeholder icon, the span code was being missed. This caused issues with placeholder icons being too large and also not having span custom span classes that might be used for other CSS stuff.
Reordered the code to fix the issue and also did some clean-up on the existing code (leftover unused options and consistent order of options).

Ensure placeholder game icons conform to span classes

---

components/prize_pool/wikis/formula1/prize_pool_custom.lua

Local PPT Custom for Formula 1 wiki, is now a Part of #3118  (this one adds the placement, 3118's placement.lua needed for colors so both will work together)
This is separated to made it easier  for code review
/dev 
I created a new label for F1 under a new color and **s:** to indicate a sport wiki

Create F1 PPT Custom

---

components/standings/commons/standings_storage.lua

Add missing data that is needed for importing into prize pools from legacy group table slots. Along with these wikicode edits:
https://liquipedia.net/commons/index.php?title=Template:StandingsData&diff=508174&oldid=484011
https://liquipedia.net/counterstrike/index.php?title=Template:GroupTableSlot&diff=2549876&oldid=2338665
`/dev` on CS wiki on https://liquipedia.net/counterstrike/ESL/Pro_League/Season_6/North_America

Add LPDB data for importing from legacy group slots

---

components/infobox/wikis/starcraft2/infobox_person_player_custom.lua

- Catch matches with literal opponents in sc2 vs stats on player pages
- use early return instead of having almost the entire function in one if
dev to live since it was causing an error on 1 page

Catch matches with literal opponents in sc2 vs stats on player pages

---

components/prize_pool/wikis/brawlstars/prize_pool_custom.lua

Brawlstars uses the AutoPointsTable from RL, so match the setting of the minimum secured points to the one from RL.
via /dev

BrawlStars: Store minimum secured points in var

---

components/standings/commons/standings_storage.lua

Add slotindex storage as it's own field. The field doesn't exist yet but is planned.
Once the field is created, consumers needs to be swapped over and then removed from extradata.

Add `slotindex` as a lpdb_standingsentry field

---

components/infobox/extensions/commons/infobox_extension_achievements.lua

use `requireIfExists` over `loadDataIfExists` since one of the options allowed to pass along is a function
live, broke sc2

Fix `Module:Infobox/Extension/Achievements`

---

components/statistics/count.lua
components/statistics/portal_statistics.lua

Fixes #3162 
The old version would result in tournaments counted multiple times into the total when displaying tiertypes in the table as well as miss tournaments.
Things to discuss:
via /dev on https://liquipedia.net/ageofempires/User:Dark_meluca/PortalStatisticsTest/CoverageTest/2019

Statistics: Adjust coverageTournamentTable

---

components/statistics/portal_statistics.lua

On some wikis (for specific years) there aren't many players with more than 1k earnings, so the table was missing many.
Make the value configurable but default to 1000.
via /dev

Stats: Make minimum earnings configurable

---

components/infobox/wikis/clashofclans/infobox_league_custom.lua

Infobox league for New Wiki CoC 
**Clean Port of Brawl Stars** 
Stuff that mentions **Supercell** would need to be stay as they are from same publisher, but please check two side notes
LIVE - https://liquipedia.net/clashofclans/Clash_of_Clans_World_Championship/2021
1. Since Brawl InfoLeague is existed for quite a while already (as early as last year) , Do I need to removed this section if it shouldnt be there for a Pre Alpha? 
2. Should I need to revise the parameter name **supercellpremier** for the highlighted tier to be **publisherpremier** parameter instead?

Create Infobox League for Clash of Clans

---

components/infobox/wikis/ageofempires/infobox_league_custom.lua

Since some mapnames are present in multiple games and there is no standard suffix currently, it can happen that maps entered on a tournament page link to the wrong page.
This introduces a small check for map data from a page, and adds a tracking category if a mismatch between games is detected.
via /dev

AoE: Check whether mappages are linked correctly

---

components/broadcaster_card/commons/broadcaster_card.lua

Avoid pulling ghost data by querying only on other pages.
Example:
| Before| After |
| --- | ----------- |
| ![image](https://github.com/Liquipedia/Lua-Modules/assets/42142350/5ae51555-b2c0-42d7-a3aa-5f3df7336f32)| ![image](https://github.com/Liquipedia/Lua-Modules/assets/42142350/3b2198df-62ed-4584-a2de-f88420baf6c0) |
/dev

Mitigate preservation of ghost broadcaster data

---

components/infobox/commons/infobox_league.lua
components/infobox/commons/infobox_series.lua
components/infobox/wikis/ageofempires/infobox_league_custom.lua
components/infobox/wikis/ageofempires/infobox_series_custom.lua
components/infobox/wikis/rocketleague/infobox_league_custom.lua
components/infobox/wikis/warcraft/infobox_league_custom.lua

To fix issue of `self.appendLiquipediatierDisplay()` vs `self:appendLiquipediatierDisplay()`:
https://discord.com/channels/93055209017729024/372075546231832576/1139472665451696208
Tested on `/dev` with LoL wiki.

Switch all `appendLiquipediatierDisplay` to object calls

---

components/infobox/wikis/apexlegends/infobox_league_custom.lua
components/infobox/wikis/mobilelegends/infobox_hero_custom.lua
components/infobox/wikis/mobilelegends/infobox_item_custom.lua
components/infobox/wikis/starcraft/infobox_team_custom.lua
components/infobox/wikis/starcraft2/infobox_campaign_mission_custom.lua
components/infobox/wikis/starcraft2/infobox_team_custom.lua
components/infobox/wikis/tft/infobox_league_custom.lua
components/infobox/wikis/wildrift/infobox_item_custom.lua
components/infobox/wikis/wildrift/infobox_unit_champion.lua

Fix incorrect function headers (`.` vs `:`) on a few wiki customs. 
Only TFT and Apex with a real effect (as they use the param)
Live on FTF

Fix Wiki Categories

---

components/infobox/wikis/valorant/infobox_person_player_custom.lua

Add `years_active_talent` param to Valorant infoboxes, it already exists in the [documentation of the template](https://liquipedia.net/valorant/Template:Infobox_player), it's just not added to the module.

Add `years_active_talent` param to Valorant infoboxes

---

standard/info/wikis/battlerite/info.lua

I have moved the original file to a new name and uploaded a allmode version for it, now some tables started to break so this change should fix those issues. (even the file redirect broke it, my bad...)
[Example of broken page right now, it breaks once I had updated the team template from the "old" legacy filename to the "new" one https://liquipedia.net/battlerite/Averse ]
Old link: https://liquipedia.net/commons/File:Battlerite_logo.png?redirect=no
New link: https://liquipedia.net/commons/File:Battlerite_default_allmode.png

Fix Battlerite `Module:Info` structure

---

standard/flags.lua

Uploaded higher resolution flags to commons (for mobile devices, etc.) similar to #3114. So need this to enforce the actual flag files served to users as with the other PR's icons.
Also amended code which parses expanded wikicode of `{{Flag}}` templates to split on Category which is a better alternative and less prone to breakage as seen earlier in discord:
https://discord.com/channels/93055209017729024/372075546231832576/1139971859350294659
Also added tracking category using lua and changed other outputs to use lua too rather than wikicode category setting.
Tested on `/dev`. Also now live as hotfix to break because of changes to `{{Flag}}` templates' code. Category stuff isn't live, however, is tested.

Set flag px size and handle missing flags better

---

components/prize_pool/commons/prize_pool_import.lua

resolves #3183
Add option for ppt import to ignore opponents that have `opponnet.status ~= 'S'`
dev

Add option for ppt import to ignore opponents that have `opponnet.status ~= 'S'`

---

components/infobox/wikis/fighters/infobox_league_custom.lua

Separate the params used to abbreviate circuits and series. The two are distinct entities, and should not be abbreviated using the same parameter.
Tested in dev

Change abbreviation parameter for circuits in Infobox League for Fighters

---

standard/flags_master_data.lua

Yugoslavia renamed to Serbia and Montenegro in 2003 and received a new ISO code (from `yu` to `cs)`. Adding the new country name and codes.
Also added a `usgb` alias for English speaking since its `us` and `gb` flag combined rather than `uk` flag.
Just some flag data :D

Add Serbia and Montenegro flag data

---

standard/flags_master_data.lua

Reported on discord, `Oceanian` is the correct demonym
N/A

Fix demonym for Oceania

---

components/infobox/commons/infobox_team.lua

Pass through `doNotIncludePlayerEarnings` in infobox team to earnings
dev

Pass through `doNotIncludePlayerEarnings` in infobox team to earnings

---

components/match2/wikis/valorant/match_group_input_custom.lua

As title says; add code to store `publishertier` in match2 on VALORANT wiki.

Store `publishertier` in match2 on VALORANT

---

components/opponent/commons/starcraft_starcraft2/player_display_starcraft.lua

- Caused an error on some broodwar pages
- function called doesn't exist
- replaced it with existing one
live, bug fix

Fix SC playerdisplay

---

components/match2/commons/match_group_input.lua
components/match2/wikis/arenaofvalor/match_group_input_custom.lua
components/match2/wikis/brawlstars/match_group_input_custom.lua
components/match2/wikis/callofduty/match_group_input_custom.lua
components/match2/wikis/counterstrike/match_group_input_custom.lua
components/match2/wikis/dota2/match_group_input_custom.lua
components/match2/wikis/halo/match_group_input_custom.lua
components/match2/wikis/leagueoflegends/match_group_input_custom.lua
components/match2/wikis/mobilelegends/match_group_input_custom.lua
components/match2/wikis/overwatch/match_group_input_custom.lua
components/match2/wikis/pokemon/match_group_input_custom.lua
components/match2/wikis/rainbowsix/match_group_input_custom.lua
components/match2/wikis/rocketleague/match_group_input_custom.lua
components/match2/wikis/sideswipe/match_group_input_custom.lua
components/match2/wikis/splatoon/match_group_input_custom.lua
components/match2/wikis/splitgate/match_group_input_custom.lua
components/match2/wikis/trackmania/match_group_input_custom.lua
components/match2/wikis/valorant/match_group_input_custom.lua
components/match2/wikis/wildrift/match_group_input_custom.lua

Unify several get players of team functions via commons
- make it so that commons function can be used by all wikis that currently have match2 with the exception of sc/sc2 (faction stuff and different processing)
via /dev, tests on a few pages on a few wikis + letting contributors help testing

Unify several get players of team functions via commons

---

standard/flags_master_data.lua

Because getCountryCode was causing `uk` to return instead of `gb`.

Move `uk` flags ISO code to aliases

---

components/broadcaster_card/commons/broadcaster_card.lua

Store `manualinput` indicator in BroadCasterCard extradata
as part of #3201

Store `manualinput` indicator in BroadCasterCard extradata

---

components/infobox/extensions/wikis/starcraft/infobox_extension_cost_display.lua

Add `Module:Infobox/Extension/CostDisplay` for broodwar
The module will be used in some infoboxes
It differs from the sc2 version in (image) file names as well as `ICONS` structure (e.g. buildTime on sc2 is race specific on bw it is not)
as part of #3210, functional part 1-1 copy from sc2, only data changes

Add `Module:Infobox/Extension/CostDisplay` for broodwar

---

components/match2/commons/match_group_coordinates.lua
components/prize_pool/commons/prize_pool_import.lua

Previously only double-elim (and single, ofc) brackets were supported for importing into prize pools. Adding functionality to support any number of elimination level brackets.
Lightly tested on CS wiki with `/dev` on SE, DE, and TE brackets.
Example of the fix working: https://liquipedia.net/counterstrike/index.php?title=ESL/Challenger_League/Season_44/North_America/Relegation&diff=2579820&oldid=2540158

Import brackets with multiple elimination levels into prize pools

---

standard/lpdb.lua

In case parameters to LPDB are wrong (e.g. unknown column), the return type will be a string with a simple error message.
Since the call will fail anyway in the next line (ipairs on string), error earlier and display the message.
via /dev
previously:
with this change:

Pass through lpdb error messages

---

components/prize_pool/commons/prize_pool_import.lua

Fix PPT Import
- simplify some logic (L319)
- make sure not to compare nil (L324) (the -1 check is not needed since `coordinates.roundIndex` is positive integer afaik)
- simplify `_findBracketFirstDropdownRounds` function (remove not needed special case; L395-397)
- adjust logic in `_findBracketFirstDropdownRounds` to match the one before #3215
dev

Fix ppt import

---

components/infobox/extensions/wikis/starcraft/infobox_extension_cost_display.lua
components/infobox/extensions/wikis/starcraft2/infobox_extension_cost_display.lua

- Add return annotation
- fix return to be `string?` instead of `string|table|nil`
N/A

Fix non args case in sc/bw infobox costdisplay extension

---

components/infobox/extensions/wikis/warcraft/infobox_extension_cost_display.lua

Add warcraft `Infobox/Extension/CostDisplay`
Differs from sc/sc2 since icons are not faction dependent and icon data is different
as part of some infoboxes currently being build

Add warcraft `Infobox/Extension/CostDisplay`

---

components/infobox/wikis/warcraft/infobox_patch_custom.lua

depends on #3238 
Add warcraft infobox patch
dev into live
`Module:Infobox/Patch/Custom` was used for a function used by the old template version which is now integrated into the new module
to not break shit due to merge i pushed the module over after testing and adjusted the template accordingly

Add warcraft infobox patch

---

components/prize_pool/commons/prize_pool_legacy.lua
components/prize_pool/wikis/warcraft/prize_pool_legacy_custom.lua

Currently for the first slot no last vs data is set in Warcrafts legacy duo prize pools.
That is due to the fact that at the point the first slot is processed the second slot isn't present yet.
Warcraft used a (pretty stupid) reference system. So to be able to add the lastVsData to the first slot the Array map for adding the last vs data has to be moved after all slots have been processed.
This PR does that.
dev

Fix WC legacy duo prize pool lastVsData for first slot

---

components/broadcaster_card/commons/broadcaster_card.lua

depends on #3202 and bot runs after it
might need resolving merge conflict after #3202
Adjust BroadcasterCard as per our latest Modules sync discussion
- do not show name if name == id (with option switch to still show it)
- store indicator if it is manual input --> in #3202 
- restrict broadcasters query to only query from "manual input"
- query for names and flags "independently"
- make sure to only return values if there aren't different possible returns
dev

Adjust BroadcasterCard

---

components/infobox/wikis/starcraft/infobox_strategy_custom.lua

Don't make `popularized` input a link in bw infobox strategy as per request by bw contributor
live

Don't make `popularized` input a link in bw infobox strategy

---

components/match2/commons/match.lua

Adjust objectnames of match2 subobjects so that when > 9 games/opponents are returned they are still in correct order
Currently matches shown via e.g. showBracket with >= 10 maps bug:
source:
from query
presumably the same would happen with >9 opponents in a match (i.e. in BattleRoyale stuff)
it is the same fix we applied for match2players already
dev

Adjust objectnames of match2 subobjects

---

components/match2/wikis/arenaofvalor/match_group_input_custom.lua

We had around half dozen ish of Solo events and exactly 1 2V2 tournaments  for AOV wiki
originally the **(opponent)** within typeIsParty were written in a way its unable to make {{Solo or 2v2Opponent}} worked.
Display needs no change
https://liquipedia.net/arenaofvalor/User:Hesketh2/indiv 
Additionally I added the **syncPlayers** as well for Auto Flags.

Make {{Solo/DuoOpponent}} worked on AoV match2

---

components/infobox/wikis/brawlstars/infobox_map_custom.lua

Add brawlstars infobox map
When comparingh to the template version you will notice that this module has several fields less. That is due to those not being used at all. (Added tracking categories and touched the 60 pages the infobox is used on.)
Need to do a bot run with rolling it out (adjusting the template to call the module) to adjust the mode input since that get (imo) imporved.
Additionally clean up aka stuff to be now part of infobox.

Add brawlstars infobox map

---

components/infobox/wikis/starcraft2/infobox_unit_custom.lua

Add some storage flags in sc2 infobox unit.
They are intended to sort units better in some table we want to automate
dev

Storage some more data in sc2 infobox unit

---

components/infobox/wikis/starcraft2/infobox_league_custom.lua

Use commons default for participantsnumber on sc2.
Due to recent changes in the sc2 infobox league (namely adding and using racebreakdown extension) it now can use the commons part instead of having to overwrite it
dev

Use commons default for participantsnumber on sc2

---

components/squad/commons/squad_custom.lua
components/squad/commons/squad_row.lua
components/squad/wikis/apexlegends/squad_custom.lua
components/squad/wikis/arenaofvalor/squad_custom.lua
components/squad/wikis/counterstrike/squad_custom.lua
components/squad/wikis/dota2/squad_custom.lua
components/squad/wikis/halo/squad_custom.lua
components/squad/wikis/leagueoflegends/squad_custom.lua
components/squad/wikis/mobilelegends/squad_custom.lua
components/squad/wikis/overwatch/squad_custom.lua
components/squad/wikis/rainbowsix/squad_custom.lua
components/squad/wikis/rocketleague/squad_custom.lua
components/squad/wikis/smash/squad_custom.lua
components/squad/wikis/starcraft/squad_custom.lua
components/squad/wikis/starcraft2/squad_custom.lua
components/squad/wikis/valorant/squad_custom.lua
components/squad/wikis/warcraft/squad_custom.lua
components/squad/wikis/wildrift/squad_custom.lua

Presently, the teamicon is called without a date and can cause wrong historical data to be used. Added change to ensure that the latest date for that player is applied to that teamicon.

Apply date to `team` in SquadRow

---

standard/info/wikis/tft/info.lua

There's a china-only version of the game that's separate, since the wiki covers those event as well + Editors wants ability to show **game version** on infobox, I added an entry for the separate game 
Infobox League coming in another PR.

Add new game for TFT Info

---

components/infobox/wikis/tft/infobox_league_custom.lua

Editors want ability to show which game version (two that the wiki covers) is being played on that tournament
I decide to bring how Tetris implements with the Module:Game calls and an **addtolpdb** entry that relates to it
|dev=1 on few pages
Right now the **game** won't stored If theres no **|game=X** entry being input, I want to adjust in a way that if **|game=X** doesnt exist in the code input it always stores the default entry per Module:Info into **game**
Currently it does display already, but its not stored somehow
The differences 
|game=tft added https://liquipedia.net/tft/Special:LiquipediaDB/TFT_Vegas_Open
|game=tft not added https://liquipedia.net/tft/Special:LiquipediaDB/Runeterra_Reforged/Championship
**both pages with |dev=1**

Add Game version for TFT Infobox League

---

components/infobox/wikis/pubg/infobox_league_custom.lua

Ability to display patch numbers for PUBG (PC), was something that editors actually covered in the form of Text under format for a while. 
The code were brought from how Mobile Legends implement the Patch on infobox module
|dev=1
https://liquipedia.net/pubg/PUBG_Nations_Cup/2023
only these two lines that I didnt copy over, is it needed? (since the value is already stored under LPDB data for both patch and epatch fields already)

Add Patch support for PUBG (PC)

---

components/match2/commons/match_group_base.lua

Currently the `disable_LPDB_storage` wiki var doesn't get respected in match2.
For LegacyWrapper it is respected but not for new input.
Suggestion is to also respect it for new input.
/dev

Respect storageDisableVar in match2

---

components/opponent/commons/opponent.lua

depends on #3285
Add `isEmpty` function to `Module:Opponent`
Idea is to have an easy function for checking against this case sicne we might find it useful in several modules
not tested, new functions so can not break stuff and logic is pretty simple
did not set up testcases for opponent module since it would have to (imo) include lots more test cases and i would rather add that via a sep pr at a later time

Add `isEmpty` function to `Module:Opponent`

---

components/infobox/commons/infobox_league.lua

Add info text options for Infobox League
- re-use the text we generate for seo
- store it in lpdb and wiki var
- add option to directly display it from the infobox via a switch param
/dev

Add info text (summary) options for Infobox League

---

components/infobox/wikis/rocketleague/infobox_person_player_custom.lua

Change to create two new history in the player section corresponding to nationals league (Italian Rocket Championship and Elite Series). Since they are yearly leagues, it makes more sense to create a different team history showcasing the teams the player played under in this particular league.
https://liquipedia.net/rocketleague/User:Dark_meluca/infoboxTest
https://liquipedia.net/rocketleague/Module:Infobox/Person/Player/Custom/dev

Add elite series and italian rocket championship history fields in infobox player

---

components/faction/commons/faction.lua

Make faction module usable from invoke.
This is to fix some darkmode issues caused by using an outdated module in some pages. Switching over to new one is only possible if it can work properly from invoke
dev
- After merge adjust Templates `p`, `t`, `z` both on bw and sc2

Make faction module usable from invoke

---

components/infobox/wikis/clashofclans/infobox_building_custom.lua

Clash of Clans is Base-Building game, editors want to make a page covering the available Buildings in the game
I had no experience tackle Module:Infobox/Building before, so I decide to start it from Module:Infobox/Unit/Hero (from Mobile Legends, since I had familiarity with it) then change calls from anything **Hero** to use **Building** instead (as well as calling Infobox/Building instead of Unit), hence the code will look a bit weird
https://liquipedia.net/clashofclans/User:Hesketh2/Cannon

Add Infobox Building for Clash of Clans

---

components/infobox/wikis/heroes/infobox_person_player_custom.lua

Add `Retired` display in heroes infobox person as [per request by the wikis contributors](https://discord.com/channels/93055209017729024/268719633366777856/1153644417673072733)
dev

Add `Retired` display in heroes infobox person

---

components/prize_pool/commons/prize_pool_base.lua
components/results_table/commons/results_table.lua
components/results_table/commons/results_table_award.lua
components/statistics/portal_statistics.lua
components/tournaments_listing/commons/tournaments_listing_card_list.lua
standard/currency/currency.lua
standard/test/currency_test.lua

As part of wanting to fix an issue with `Module:MetadataGenerator`, I needed some more configurability of the display from this module. I changed the name of two existing options to be a bit better (imo) and added a new option too.
- `symbol` -> `displaySymbol` (functionality 1:1)
- `abbreviation` -> `displayCurrencyCode` (functionality 1:1 if not changing `useHtmlStyling`)
- `useHtmlStyling` is new and stops `&nbsp;` and `<abbr>` from being used.
`/dev` ofc :D 
The following non-git modules have been pre-prepared for the merge to not break them. Just need to remove `abbreviation` after that.

Minor rework of Currency display options

---

components/infobox/extensions/commons/metadata_generator.lua

Due to the old way that MetadataGenerator was creating the currency string, it didn't know about edge cases like CHF which don't have a symbol at all and hence a double CHF was present. This PR fixes that by using the updated Currency module display instead.
Original report: https://discord.com/channels/93055209017729024/372075546231832576/1153776473325453362
---
With post-#3298 currency module
Dropped the HTML stuff because it's probably not needed and might cause issues with some places even that display the string in a non HTML-parsed domain.
---
Also removed a duplicate import and ordered the imports alphabetically.
Should we always display USD prize pool if present or only manually input? Currently it is the latter of those two which does lead to some inconsistency with old …

Fix duplicate currency code issue in `MetadataGenerator`

---

standard/info/wikis/callofduty/info.lua

- Adjusted various file name to matched the lightmode version (these files were already existed or moved to a proper name)
- Add logos for Warzone Games
- Add entry for the MWIII (2023) Game
- Add entry for COD: Online, which exist but hasnt been added yet

Update Game Info for CoD wiki

---

components/infobox/extensions/commons/years_active_base.lua
components/infobox/extensions/wikis/rocketleague/years_active.lua
components/infobox/wikis/rocketleague/infobox_person_player_custom.lua

Rocket League currently uses the automatically calculated years-active for players, I extended this to coaches, talents, ~~and observers~~.
- Manual activity for coaches was not used on any page, neither were talents.
- ~~Observers previously did not have years-active, I thought this would be useful since there are observers with pages.~~
- Removed the completely-unused organisation years active, as well as analyst. It didn't seem fitting to keep them as it stands, as they can't automatically be updated (perhaps this could be done using `squadplayers`?).
- Added functionality to hide years active, example: `|years_active_talent=hide`. I think this could be useful for if a player was to cast or coach for a one-off event.
- Hid the `Player has no results.` text, since this text generally …

RL:  Add years-active to more roles

---

components/match2/commons/match_group_util.lua
components/match2/commons/match_summary_base.lua
components/match2/commons/match_summary_base_temp.lua
components/match2/wikis/brawlstars/match_summary.lua

Add reworked MatchSummary as temp module
Also Adjust MatchGroup/Util accordingly.
The temp module is done so we can switch wiki after wiki over instead of having to do all at the same time.
After all wikis are switched over we can kick the old one and move the temp one in its place (together with adjusting all customs to then again point towards the notmal base)
Also can simplify the fetchMatchForBracketDisplay function in MatchGroupUtil after all wikis have been switched
as dev of the normal one, see #3295

Add reworked MatchSummary as temp module

---

components/match2/wikis/dota2/match_summary.lua
components/match2/wikis/leagueoflegends/match_summary.lua
components/match2/wikis/splatoon/match_summary.lua

After the latest Safari update our match2 bracket popups have been semi-broken. This had first been reported via email and posted on our discord server here: https://discord.com/channels/93055209017729024/372075546231832576/1153996916808503360. I have reproduced the issue as shown in this screenshot:
The fix here is to avoid floats in flex items and instead add another inline-flex inside the area. I have already added classes that do this here: https://liquipedia.net/commons/index.php?title=MediaWiki%3ACommon.css%2FBrackets.css&type=revision&diff=524335&oldid=522838
Removing the floats is just cleanup since they don't do anything inside a flexbox container.
I tested this by adding the relevant class via dev tools on all three relevant wikis.
Whilst I did not test this on an actual iPhone, …

fix match2 bracket popups in safari on iOS17

---

components/prize_pool/commons/prize_pool_import.lua

Catch a nil in ppt import
dev to live

Catch a nil in ppt import

---

components/infobox/wikis/starcraft2/infobox_building_custom.lua

Remove duplicate field in sc2 infobox building
noticed by onYourOwn
live by onYourOwn

Remove duplicate field in sc2 infobox building

---

standard/lua.lua

Sets `Pages using dev modules` category on any pages using (or trying to use) dev modules via Lua invoke or Lua import. Seems to be something we want as seen on discord (https://discord.com/channels/93055209017729024/874304000718172200/1157311906042875984), so added it with help of hjpa. Only applies to namespaces that are considered "main" by the namespace module.
Tested on `/dev` module using temporary Lua/dev invoke template in userspace and mainspace.

Set page category when requiring dev modules

---

standard/class.lua

Allow Class to inherit init over >=2 levels
via Darkrais dev wiki http://darkrai.wiki.tldev.eu/commons/index.php?title=Module%3AClass&type=revision&diff=513764&oldid=511922
(can not test this change via /dev since we would have to use CLass/dev in all modules then since it depends on it being used everywhere instead of only in 1 module if modules call eachother)

Allow Class to inherit init over >=2 levels

---

components/infobox/wikis/ageofempires/infobox_person_player_custom.lua

Previously, players with multiple games would have a comma-separated string of their games in extradata.
This adds additional keys`gameX` to extradata, which allows to query for specific games.
The old list is still available for consumer compatibility.
In addition, input of aoeXnet_id is stored in extradata to allow API consumers to match on them.
via /dev

AoE: Adjust storage of game data for players

---

components/match2/commons/match_summary_base_temp.lua
components/match2/wikis/counterstrike/match_summary.lua

Update CS MatchSummary

---

components/match2/commons/match_group_input.lua
components/match2/wikis/counterstrike/match_group_input_custom.lua

Fixes behaviour where games would not correctly inherit tournament vars from their match parent in cases where the parent had had them overwritten by manual input. Only changed on CS custom but can do to others if desired.
| Match | Game |
| ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/9e249d29-1a30-466a-8f4c-8d0312c60de8) | ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/d52853d7-bef1-45a5-9776-02e27f7e9257) | 
Implementation by hjpa.
Tested with `/dev` on the CS wiki by me.

Inherit tournament vars from parent matches to games

---

components/statistics/portal_statistics.lua

Updated the default value for earnings charts legends, when no value is specified. 
Added a new function for querying LPDB data for player/team earnings, so that they can be sorted by yearly breakdown and displayed as such
https://liquipedia.net/valorant/User:Dark_meluca/PortalStatisticsTest
https://liquipedia.net/valorant/User:Dark_meluca/PortalStatisticsTest/Top10

Statistics: Extra Earnings Chart functionality

---

components/match2/commons/match_summary_base_temp.lua
components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua
components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua

if you want less anno warnings during review: wait for #3322 and rebase the branch then^^
Update starcraft(2) MatchSummary
- cleanup & use commons
- Add annos to `Module:MatchGroup/Util/Starcraft` so that annos in `MatchSummary/Starcraft` can be more precise & anno warnings vanish
dev (for functional changes) / VSCode (for annos)
top: new - bottom: old

Update starcraft(2) MatchSummary

---

components/match2/wikis/leagueoflegends/big_match_template.lua
components/match2/wikis/leagueoflegends/match_links.lua

From #3334, I think file names started requiring `File:` but that was missing here and caused issues:
https://discord.com/channels/93055209017729024/276340346831765504/1159157532674248867
(Also vod icon not needed anymore)
Straight to live fix.

Fix LoL match icons missing `File:`

---

components/match2/wikis/rocketleague/match_summary.lua
components/match2/wikis/sideswipe/match_summary.lua
components/match2/wikis/trackmania/match_summary.lua

Update RL, Sideswipe and Trackmania MatchSummary to use `Module:MatchSummary/Base/temp`
dev

Update RL, Sideswipe and Trackmania MatchSummary

---

components/opponent/commons/opponent_display.lua
components/opponent/commons/player_display.lua
components/opponent/commons/starcraft_starcraft2/opponent_display_starcraft.lua
components/opponent/commons/starcraft_starcraft2/player_display_starcraft.lua
components/opponent/wikis/fortnite/opponent_display_custom.lua
components/opponent/wikis/warcraft/opponent_display_custom.lua
components/opponent/wikis/warcraft/player_display_custom.lua

Add note support to (party) block opponents
And add missing anno for `dq` in BlockOpponentProps
dev

Add note support to (party) block opponents

---

components/prize_pool/commons/prize_pool_base.lua
components/prize_pool/commons/prize_pool_placement_base.lua

Add percentage support in prize pools
dev
to showcase that manual overwrite works (i.e. if usdprize or localprize are set manually it does not use % calculation):

Add percentage support in prize pools

---

standard/game.lua

Currently if a link is omitted from a Game icon creation, then nothing is shown on hover. This is both bad for less knowledgeable users as well as users who rely on alt text for things like screen readers.
Added caption to the icon string and then create it from either game name or game link (as fallback). Mediawiki does the rest by setting it as hover text and alt text.

Add alt/caption text to Game icons

---

components/matches_schedule_display/commons/matches_schedule_display.lua

Fixes cases for `|sdate` is in the middle of a round
Before
After
dev

feat: use inheritedheader in match schedule

---

components/infobox/wikis/warcraft/infobox_unit_custom.lua

Old template code was `{{#ifexpr:{{{passive|0}}}>0|Neutral Special Units|Creep Special Units}}`, the module port inverted the logic and also dropped the `Special` inside Neutral Special Units.
via /dev, then live

Fix unit category in WC infobox unit

---

components/infobox/wikis/ageofempires/infobox_person_player_custom.lua
components/infobox/wikis/valorant/infobox_person_player_custom.lua

Similarly to CS, val and aoe wikis want to use `Module:Region/CountryData` without it adding region to player pages automatically. Disable that like on CS. Also switch from template expansion for data definition of region to using region module (val only).
tested on dev module.

Disable region cell on VAL, AoE player infobox

---

standard/json.lua
standard/test/json_test.lua

Add `Json.stringifySubTables`, a function that stringifies all subtables of a given table.
Useful for e.g. a table with subtables to be stored into lpdb
test cases

Add `Json.stringifySubTables`

---

components/match2/wikis/heroes/match_summary.lua

**Match2 for Heroes of the Storm**
Game Summary: Its just a MOBA with multiple maps
Key Info
- Base is Mobile Legends
- (This Module) removed **length** and replaced with **map names**
- (This Module) adds display for the **Map Veto** 
- The rest is untouched from the port
https://liquipedia.net/heroes/User:Hesketh2
(the hero icon and map names in Veto are placeholder name and icons from other wikis to test only)

Add MatchSummary for Heroes

---

components/match2/wikis/tetris/match_summary.lua

**Part of Match2 Implementation**
PRs starts with non-team stuff. When merged, a 2nd PR which contain team stuff is then up
(This also applies to **MatchGroup**)
For Part 1 (non-team stuff) = LIVE
(e.g. https://liquipedia.net/tetris/CTWC/2022)

MatchSummary for Tetris

---

components/match2/wikis/criticalops/match_group_input_custom.lua

**Part of Critical Ops (very bottom of Pre-Alpha) Match2**
The entire game is a Counter-Strike clone on Mobile, I guess it doesnt required much explanation of match structure. 
The match2 starts with pure paste of CS:GO Match2 because it works instantly
LIVE
https://liquipedia.net/criticalops/Critical_Ops_Circuit/Season_5/Asia/Finals
C-OPS has been on a WIP R6 Match2 for like 6-9months (before CS Match2 exist), but because the game barely has event until this year. I decide to re-visit this and paste the CSGO Match2 because it works out of the gate.

MatchGroup/Input/Custom for Critical Ops

---

components/match2/wikis/tetris/match_group_input_custom.lua

**Part of Match2 Implementation**
PRs starts with non-team stuff. When merged, a 2nd PR which contain team stuff is then up
(This also applies to **MatchSummary**)
For Part 1 (non-team stuff) = LIVE
(e.g. https://liquipedia.net/tetris/CTWC/2022)

MatchGroup/Input/Custom for Tetris

---

components/match2/wikis/warcraft/match_group_input_custom.lua

Fix warcraft match team input reading
- better error in case of missing team template
- set opponent name for blank case
- pass along opponent instead of just name
dev to live

Fix warcraft match team input reading

---

components/faction/wikis/warcraft/faction_data.lua

Adjust warcraft faction data as per request by contributors
- change order: move undead before night elf
- change night elf display from `Nightelf` to `Night Elf`
N/A

Adjust warcraft faction data

---

components/participant_table/commons/participant_table_base.lua

Fix participantTable excess row
Currently participant table displays an additional (unwanted) row if number of displayed entries is devisable by colSpan.
This PR fixes that
dev to live

Fix participantTable excess row

---

components/participant_table/commons/participant_table_base.lua

Allow to disable `sortOpponents` in participants table as per request by taner
dev

Allow to disable `sortOpponents` in participants table

---

components/prize_pool/wikis/warcraft/prize_pool_custom.lua

Default enable ppt import on warcraft starting 2023-10-16, since match2 has been rolled out on warcraft wiki.
dev

Enable ppt import on warcraft starting 2023-10-16

---

components/statistics/portal_statistics.lua

Annotation states there's a paramter that doesn't exist
VSCode

Fix annotation in portal stats

---

components/match2/wikis/tetris/match_group_input_custom.lua

Sync players during opponent resolve in tetris match input processing.
Apparently it was set in the version used but never added to the PR ...
Hence the merge of the PR broke flag inheritance functionality.
This PR adds it back.
live

Sync players during opponent resolve in tetris match input processing

---

components/opponent/commons/opponent.lua
components/opponent/commons/starcraft_starcraft2/opponent_starcraft.lua
components/opponent/wikis/warcraft/opponent_custom.lua

not sure if it should be labeled as a bug or not
on one hand i think it was not intended to not set the wiki var but can not rule it out
Save manually input player team to page var if `syncPlayer` is enabled
`PlayerExt.syncTeam` uses (and returns) the manual input if no team is specified manually.
So we do not need to do the `if not player.team then` check and can just pass the manual input along (instead of nil) instead.
This change results in the team data getting stored in page vars though.
dev

Save manually input player team to page var if `syncPlayer` is enabled

---

components/infobox/extensions/commons/role_of.lua

The current role of has two issues. Firstly it requires a perfect match on the role, so a `Head Coach` would not be matched for role `Coach`. Secondly it will only display one arbitrary match, instead of all matches 
Dev on dota2

feat: non-exact role names in role of

---

components/match2/wikis/warcraft/match_legacy.lua

Fix `matchid` in `lpdb_game` warcraft legacy storage.
Apparently the external api consumers want them for some reason.
dev to live

Fix `matchid` in `lpdb_game` warcraft legacy storage

---

components/match2/wikis/criticalops/match_summary.lua

**Part of Critical Ops (very bottom of Pre-Alpha) Match2**
The entire game is a Counter-Strike clone on Mobile, I guess it doesnt required much explanation of match structure. 
The match2 starts with pure paste of CS:GO Match2 because it works instantly
LIVE
https://liquipedia.net/criticalops/Critical_Ops_Circuit/Season_5/Asia/Finals

Match Summary for Critical Ops

---

components/match2/wikis/criticalops/match_legacy.lua

**Part of Critical Ops (very bottom of Pre-Alpha) Match2**
The entire game is a Counter-Strike clone on Mobile, I guess it doesnt required much explanation of match structure. 
The match2 starts with pure paste of CS:GO Match2 because it works instantly
LIVE
https://liquipedia.net/criticalops/Critical_Ops_Circuit/Season_5/Asia/Finals
The wiki will have usage of GTL (seeing this were raised for Tetris Legacy)

Match Legacy for Critical Ops

---

components/match2/wikis/fifa/match_summary.lua

depends on #2618 (if we change data there)
Add match2 matchSummary for fifa wiki
They have 2 different match2 forms one for when no submatches are present and one for when submatches are present
This module has one row function for each of those 2 cases (`_createGame` and `_createSubMatch`)
test page: https://liquipedia.net/fifa/User:Hesketh2

Add MatchSummary for fifa

---

components/participant_table/wikis/warcraft/participant_table_custom.lua

depends on #3389
Add warcraft participant table
- mostly follows sc2 but has adjustments in nearly every function based on some things being different on warcraft.
"live" since new

Add warcraft participant table

---

components/match2/wikis/fifa/match_group_input_custom.lua

Add Match2 input processing for fifa wiki.
They have 2 different match2 forms one for when no submatches are present and one for when submatches are present
Input processing wise they differ only slightly
- in the score calculation (sum up map/game scores (or in case of penalty shoot-out use that games scores) for the default case and sum up map/game wins in the submatch case)
- checking which player played in which map/game (`CustomMatchGroupInput._processTeamPlayerMapData` together with `CustomMatchGroupInput._fetchMatch2PlayerIndexOfPlayer`)
test page: https://liquipedia.net/fifa/User:Hesketh2

Add Match2 input processing for fifa

---

components/infobox/wikis/callofduty/infobox_person_player_custom.lua

add PlayerTeamAuto to call of duty player infobox so that **|team=** input is Automated 
Tested with dev=1

Add PlayerTeamAuto to COD InfoPlayer

---

components/match2/wikis/trackmania/match_summary.lua

Reported on discord https://discord.com/channels/93055209017729024/372075546231832576/1163510231410679978
inspector->live

Fix display issue of bestof in TM matchsummary

---

components/match2/commons/match_group_display_helper.lua
components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua
components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua

Add option for map display names in sc2/sc match2 as per request by a reviewer (that converted ~800 old match1 team stuff on sc2)
Also refactor veto input reading
- remove restriction to it only being 6 (sc2 now has a map pool of 9 instead of 7 and to be future proof leave it open end)
- cleaner code
dev

Add option for map display names

---

components/match_ticker/commons/match_ticker.lua
components/match_ticker/commons/match_ticker_custom.lua
components/match_ticker/commons/match_ticker_display_components.lua

Made some changes to matchticker to default to a standard component not embedded in an infobox, unless called via the participant entry point which is assumed to be inside an existing infobox wrapper (can be overwritten via `false`).
The `args.infoboxWrapperClass` is now used to create a standalone "infobox" which contains only a match ticker (header can be added too), and it forces on the inner infobox class too as it's needed.
The motivation for this change was initially because mainpage entry was adding the infobox class by default, but it also just made sense to me that the ticker shouldn't be tried to infobox classes by default anyway.
The dropped classes are unneeded (as far as I can see from testing) since their CSS is either overwritten by other CSS, ignored, or inherently added …

Uncouple matchlists from infobox classes by default

---

components/infobox/wikis/callofduty/infobox_team_custom.lua

The features I want are few things
- Embeds the Commons MatchTicker/custom into the Team Infobox
- Add extradata **competesin** which is the one uses for Overwatch, to define teams in the franchised league (OWL/CDL) this is to help with the Portal Teams able to show only CDL teams through an extradata condition call
dev=1 on https://liquipedia.net/callofduty/Seattle_Surge

feat: add match ticker and league information to CoD Team Infobox

---

scripts/deploy.sh

The CoD dev wiki is currently unmaintained and doesn't work

Remove CoD wiki from dev deploy

---

standard/tier/wikis/brawlstars/tier_data.lua
standard/tier/wikis/fifa/tier_data.lua

Brawlstars and Fifa now have proper Tier(Type) setups, hence update their Tier Data to reflect that.
Just data

feat: brawlstar and fifa now uses proper tier setup

---

components/match2/commons/match_group_input.lua
components/match2/wikis/leagueoflegends/match_group_input_custom.lua
components/match2/wikis/leagueoflegends/match_legacy.lua

Store the link to the big match page for matches with a big match.
Also adds it to League of Legends match2 and match1.
Tested with dev
lol m2 (bracketData):
lol m1 (extraData):

Store big match links for matches with a big match

---

components/infobox/wikis/fifa/infobox_team_custom.lua

Add MatchTicker to FIFA Team Infobox, this is like the #3407 pull request 
Tested with Dev=1 on some pages

Add MatchTicker to FIFA Team Infobox

---

components/participant_table/commons/starcraft_starcraft2/participant_table_starcraft.lua

Add option to force non raceTable display.
Needed for some events where custom invented races are used.
dev

Add option to force non raceTable display

---

components/infobox/wikis/mobilelegends/infobox_hero_custom.lua

The Mobile Legends Hero Infobox currently has a ``releasedate`` parameter that is saved into extra data. This changes this from being saved in extradata to being saved into the ``Date`` field in LPDB. 
Tested with Dev module on a live page.

Saving release date into the date field

---

components/match2/commons/match_summary_base.lua
components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
components/match2/wikis/arenaofvalor/match_summary.lua
components/match2/wikis/dota2/match_summary.lua
components/match2/wikis/leagueoflegends/match_summary.lua
components/match2/wikis/mobilelegends/match_summary.lua
components/match2/wikis/pokemon/match_summary.lua
components/match2/wikis/rocketleague/match_summary.lua
components/match2/wikis/sideswipe/match_summary.lua
components/match2/wikis/splatoon/match_summary.lua
components/match2/wikis/trackmania/match_summary.lua
components/match2/wikis/valorant/match_summary.lua
components/match2/wikis/warcraft/match_summary.lua

Allow teamStyle option for default MS headers
- also adjust wikis according to what they used before the MS rework.
dev

Allow teamStyle option for default MS headers

---

standard/links/commons/links.lua

Files : 
https://liquipedia.net/commons/File:InfoboxIcon_Apple_Podcasts.png
https://liquipedia.net/commons/File:InfoboxIcon_Spotify.png 
This is mainly for the F1 wiki as there's a portal to cover podcasts, however we're missing icons for Spotify and Apple Podcasts.

Add Spotify and Apple Podcasts links & icons

---

components/match2/wikis/warcraft/legacy/match_group_legacy_convert_map_data.lua
components/match2/wikis/warcraft/legacy/match_group_legacy_default.lua
components/match2/wikis/warcraft/match_group_input_custom.lua

Add warcraft match1 to macth2 legacy wrapper for brackets.
Due to warcraft having several different MatchSummary templates with different input structure for map data also need something to catch that.
As of now does NOT support 2v2 legacy matches.
new modules "live", the `Module:MatchGroup/Input/Custom` via dev
https://liquipedia.net/warcraft/User:Hjpalpha/Legacy

Add warcraft match1 to macth2 legacy wrapper for brackets

---

components/match2/wikis/rainbowsix/get_match_group_copy_paste_wiki.lua

Change parameter to showScore for each map once enabled instead of only when mapDetails are turned off
When the parameter "showScore" has been set to true in the BracketGen then it will show "|score1= |score2=" in the map section every time, instead of only showing that part when mapDetails has been turned off. 
(Saves me to do a few find+replace moves for tournaments where only mapScores are known)
Did a live update on the module and tested it with any bracket (bracketID: 2 for example) and it shows the wanted result.
Module: https://liquipedia.net/rainbowsix/Module:GetMatchGroupCopyPaste/wiki
Bracket Gen: [Example Bracket](https://liquipedia.net/rainbowsix/Special:RunQuery/BracketCopyPaste?title=Special%3ARunQuery%2FBracketCopyPaste&pfRunQueryFormName=BracketCopyPaste&GetBracketCopyPaste …

Parameter update for `|score1=|score2=`

---

components/infobox/wikis/arenaofvalor/infobox_person_player_custom.lua

Add the PlayerTeamAuto feature to Arena of Valor wiki, which apparently were left unadded compared to other games in the similar branches 
Tested on https://liquipedia.net/arenaofvalor/FirstOne with |dev=1 
dont mind the first revision name, I thought of putting both on same PR but I had issues with the PUBG one so this is for just AoV

Add PlayerTeamAuto to AOV Infobox player

---

components/infobox/wikis/rainbowsix/infobox_person_player_custom.lua

Adding specialRoles function to TeamHistoryAuto so it will show roles like "Retired" and "Banned" in th infobox of players.
A poll was held and people wanted to see this change
Dev module: https://liquipedia.net/rainbowsix/Module:Infobox/Person/Player/Custom/dev
Live page using |dev=1 (I will remove dev once merged): https://liquipedia.net/rainbowsix/AceeZ
Addtional test page: https://liquipedia.net/rainbowsix/User:Okidokie98/Test2

Added "specialRoles = true" for TeamHistoryAuto

---

scripts/deploy.sh

Currently if a deploy fails due to some error (protected page or whatever else), it will halt there and not continue with any other modules. This change logs that something failed but lets the deployment attempt to continue. At the end, if something failed, it will then error the script, rather than mid-way through.
Also cleaned up the if/for code styling.
Tested on my fork of the repo using dev wiki.

Don't fail deploys catastrophically

---

components/match2/wikis/warcraft/legacy/match_group_legacy_default.lua

Fix typos in warcraft `MatchGroup/Legacy/Default`
live (not in use yet except on test page)

Fix typos in warcraft `MatchGroup/Legacy/Default`

---

components/infobox/wikis/formula1/infobox_unit_engine.lua

Adds a custom infobox for engines using a custom unit infobox similar to the car implementation previously merged. It allows for the engine specifications to be shown on their pages seen in the link below. Chronology is also implemented to highlight previous engines developed.
Tested via a dev module in a userspace page:
Module - https://liquipedia.net/formula1/Module:Infobox/Unit/Engine/dev
Page - https://liquipedia.net/formula1/User:Kitbinary/Mercedes_V6_Hybrid_engine

Add custom Infobox Unit for engines on Formula 1 wiki

---

components/match2/wikis/warcraft/match_group_input_custom.lua

Warcraft sets starttime of the event in infobox (if known). Inherit that to the first match.
dev

Inherit starttime from infobox to first match

---

components/infobox/wikis/starcraft/infobox_map_custom.lua

Catch nil in broodwar infobox map

Catch nil in broodwar infobox map

---

components/infobox/wikis/callofduty/infobox_team_custom.lua

This is one part I wasnt aware of back when adding this line at first, that is the Mobile and non-Mobile (that isnt CDL teams) clunked in same portal teams. My thought is to also use that **competesin** for Mobile teams to separate
The problem is, I can separate Mobile teams, but can't exclude them (see pics below)
Now I need the **competesin** to store empty or `''` as well for teams without that input 
(which is all teams except CDL and Mobile teams), Tested on |dev=1
This would allow me to use `!MOBILE` to exclude through using **|condition=**
End goal of this PR is to do this:
https://liquipedia.net/callofduty/Portal:Teams/Europe

CoD Info Team: Make competesin always store

---

components/match2/wikis/callofduty/match_group_input_custom.lua

Auto flag retrieval on Brackets when {{Solo}} or {{DuoOpponents}} used
(Which turns out, quite a good amount over in Call of Duty)
|dev=1 at (flags now all retrieved from the first appearance and no need to add flag onward for later matches)
https://liquipedia.net/callofduty/WorldGaming/Canadian_Championship/2016#Results

Add sync player to CoD Match2 Processing

---

components/infobox/wikis/wildrift/infobox_unit_champion.lua

Introduced in #3240, where the last table.insert wasn't cleanly adjusted but had a leftover `widgets` in there
live

WR: Fix recursive appendWith

---

components/prize_pool/commons/starcraft_starcraft2/prize_pool_starcraft.lua

Fix sc/sc2 ppt var passalong
introduced with #3459
`args.storelpdb` is now nil usually, hence use the (imo better) `prizePool.options.storeLpdb`

Fix sc/sc2 ppt var passalong

---

components/external_media_links/external_media_link.lua

Previously, `extradata_event_link` would only be stored when specifically entered but not when only event was entered.
This leads to EMLs not being displayed when querying for an event, since conditioning would only be on link, not on event:
https://github.com/Liquipedia/Lua-Modules/blob/main/components/external_media_links/external_media_list.lua#L118
This will always store said extradata point, either with the specific link input, or with the event, or with an empty string (previously, the field was nil)
I guess eventually we'd want to `gsub(' ', '_')` there as well, but that would require a change in the query part as well
via /dev

EML: Fill event-link from resolved event

---

components/infobox/wikis/fortnite/infobox_person_player_custom.lua

- PlayerTeamAuto is self explanatory (starting to few like if this would be a good commons feature in the future)
- 
- the **addlpdbdata** is to do few things
1. make the Auto History in the module able to stored datapoints of transfers
2. to allow both {{OpponentList}} and Prize Pool to be able to retrieve player's team icon automatically that depends on stored transfer and the dates stored in that tournament page, which is a huge efficiency increase for wikis like Fortnite
https://liquipedia.net/fortnite/User:Hesketh2 (Opponent List)
https://liquipedia.net/fortnite/Bugha (Player Infobox dev=1)

Fortnite Player: Add PlayerTeamAuto and lpdbdata for History

---

standard/table.lua
standard/test/table_test.lua

As an optional third param, `Table.includes` can now match for patterns in the table/array. If a user wants to match specifically full strings to pattern, they can use `^` and `$` in their pattern as they should be aware of pattern matching from `string.find()`.
Tested using `/dev` and testcases.

Add pattern matching to `Table.includes`

---

standard/error_ext.lua
standard/result_or_error.lua

Previously, `Module:ResultOrError` would just throw a list of stack traces whenever it errors and it was just a nightmare to read. Now, using some client javascript, these errors will be parsed into identical errors as from default Scribunto. Since this has to go through the `error()` call (unless each module using `ResultOrError` wants to catch the errors themselves), it had to be done this way.
Otherwise it'll just look like this:
```js
liquipedia.customLuaErrors = {
init: function() {
var $dialog = $('<div>').dialog({
title: mw.msg('scribunto-parser-dialog-title'),
autoOpen: false
});
$('.scribunto-error').each(function() {
try {
var parsedError = JSON.parse(this.innerHTML.toString().slice(11, -1));
var $backtraceList = $('<ol>', {class: 'scribunto-trace'}); …
```

Produce clean ResultOrError errors by default

---

components/infobox/wikis/ageofempires/infobox_person_player_custom.lua

Adds a (match1) matchticker to player pages on AoE
via /dev

AoE: Add matchticker to player infoboxes

---

components/match2/commons/match.lua
components/match2/commons/match_group_legacy.lua
components/match2/wikis/starcraft/legacy/match_group_legacy.lua
components/match2/wikis/starcraft2/legacy/match_group_legacy.lua
components/standings/commons/standings_storage.lua
definitions/mw.lua
standard/json.lua
standard/test/json_test.lua

Adjust `Json.stringify` to use `mw.ext.LiquipediaDB.lpdb_create_json` over `mw.text.jsonEncode` for performance reasons.
- adjust testcases
- use options table over simple `pretty` boolean var
- add option to still encade as array (if it is an array)
- adjust `match2game.score` to use `mw.ext.LiquipediaDB.lpdb_create_array` to keep lpdb data as is
- adjust `standingstable.macthes` to use `mw.ext.LiquipediaDB.lpdb_create_array` to keep lpdb data as is
- adjust git consumers that use pretty
dev & testcases & storage tests on sc2

Adjust `Json.stringify`

---

components/match_ticker/commons/match_ticker.lua

Table.includes now support an addition parameter, and with string.gsub returning two, that value is always truthy, and as such would activate pattern mode.
Live

fix: match ticket bug introduced with #3448

---

components/match2/wikis/fifa/match_group_input_custom.lua

The called function only has two parameters, while caller supplier three. Remove the 3rd, redundant, one.
Not at all

fix: minor typo in fifa match2

---

components/match2/commons/match.lua

`lowerEdges` & `lowerMatchIds` of `match2bracketdata` should be arrays, not objects. Use the old mixed serialization instead of the object forced one, for this key.
Tested with dev

fix: incorrect match2bracketdata json serialization

---

.luarc.json

Add default project settings for LuaLS (former sumneko-lua). 
These settings get higher prioty than manually set settings in VSCode when conflicting, but can still be overwritten by advance users with `--config-path`. 
https://luals.github.io/wiki/configuration/#luarcjson-file
VSCode

feat: add default LuaLS lua settings

---

components/infobox/wikis/ageofempires/infobox_league_custom.lua

Adds a (match1) MatchTicker to infobox league if the tournament is upcoming or ongoing.
Since matchtickers are currently added manually using [a template](https://liquipedia.net/ageofempires/Template:Upcoming_matches_tournament), please either blank this template temporarily when merging or ping me so i can remove then duplicated usages.
via /dev

AoE: Add matchticker to infobox league

---

components/infobox/wikis/ageofempires/infobox_league_custom.lua

Since the matchticker is added to bottomContent, it already is in an infobox wrapper.
Disable the additional class when being called from the infobox to prevent an offset.
/dev to live

AoE matchticker: disable infobox-wrapper

---

components/match2/wikis/rocketleague/match_group_input_custom.lua

Check for empty parties in `hasopponent`, for example ` / ` was being stored as having an opponent whereas it is an empty duo-party
/dev module

RL: Check for empty parties

---

components/infobox/wikis/overwatch/infobox_map_custom.lua

Overwatch maps now have different lighting options (dawn, morning, evening, night, overcast), this new parameter would allow a list of those.
See [here](https://liquipedia.net/overwatch/User:Moonshot/sandbox).

Add lighting variants to `overwatch` Infobox/Map

---

components/match2/wikis/counterstrike/match_group_input_custom.lua

Apply `syncPlayer` for `Module:MatchGroup/Input/Custom` on CS wiki so that party (solo) opponents can pull data from ParticipantsTable.
`/dev`.

Sync party opponents' data in CS match2

---

components/match2/wikis/worldoftanks/match_group_input_custom.lua
components/match2/wikis/worldoftanks/match_summary.lua

New Wiki - 2 teams controlling Tanks trying to win the game.
**The match2 is basically carbon copy (1:1) to osu! match2** because both were developed stuff together. Only osu specific stuff like protects in bans and mplink are not carried over the rest is exactly the same with nothing changed. 
Tanks and osu actually very identical in the way match works 
(has map names, has scores, has vetoes, only that Tanks is more on Teams and less on Solos)

Add Match2 for World of Tanks

---

components/opponent/commons/opponent.lua

Since our plugin doesn't handle two imports on the same line, split it into two

fix: anno warning in opponent

---

standard/info/wikis/counterstrike/info.lua

Because ESL decided to move already ongoing tournaments from CS:GO to CS2 (😠), we now have to deal with this. I thought about adding multiple game support to the infobox but that would require changing the base infobox too and not just CS custom. Also, what would we even do for the `tournament_game` var?? Would have to have like a switch date or something and maybe multiple vars, and then have to add display support for that in other modules too... so yeah, nope.
Instead just making this not really real game for the purpose. Then will override game per-match or using vardefine somewhere on the pages.
/dev and then pushed to live also as needed ASAP.

Add pseudo game "CS:GO/CS2" to cs wiki

---

components/match2/wikis/warcraft/legacy/legacy_match_maps.lua
components/match2/wikis/warcraft/legacy/match_group_legacy_convert_map_data.lua
components/match2/wikis/warcraft/legacy/match_group_legacy_default.lua
components/match2/wikis/warcraft/match_summary.lua

Add support for an edge case in warcraft match2.
Sometimes they have map info and submatch total scores but not map winner/scores.
This adds the option to add a `|mapX={{Map|map=Submatch Score Fix|score1=2|score2=7}}` input to fix the submatch score (and match score).
This fix map is then not displayed.
This PR also adds support to legacy wrappers for this edge case.
if someone has a good and easy to implement idea to solve it better you are more than welcome ...
dev

Add support for an edge case in warcraft match2 submatches

---

components/match2/wikis/warcraft/legacy/match_group_legacy_convert_map_data.lua

In the old `BracketTeamMatchMulti` they allowed missing maps, but only had max maps 1-9.
This PR adjusts the code so it can allows missing maps accordingly.
After this is merged all old team matches can be wrapper converted on warcraft, only leaving <250 pages with 2v2 stuff still to be converted (2v2 stuff never stored into match1 at all anyways).
dev

Catch another edge case in warcraft match legacy wrapper

---

standard/info/wikis/fighters/info.lua

MK1 uses allmode icons, not lightmode/darkmode as currently specified.
Applied by editor
https://liquipedia.net/fighters/index.php?title=Module%3AInfo&type=revision&diff=197383&oldid=189950

Update MK1 icons for Fighters

---

standard/info/wikis/callofduty/info.lua

To be more consistent, the older names were redirected into the names seen in this change 
also that this could now work again (which previously, isnt the case) 
Tested on live environment

Adjust COD info filenames

---

components/match2/wikis/warcraft/match_group_input_custom.lua

Fix warcraft map walkover handling in case of additional manual score input.
- walkover input wins now over score input for determining the winner
- minor cleanup to reduce need for indents
dev

Fix warcraft map walkover handling in case of additional manual score input

---

components/match2/wikis/counterstrike/match_external_links.lua
components/match2/wikis/rainbowsix/match_group_input_custom.lua
standard/links/commons/links.lua

They moved all the old stuff we have links for to `https://old.letsplay.live/`. So just moving that across. Also, added correct team and event link format.
Just data :p

Update LPL links to legacy domain

---

components/match2/wikis/warcraft/match_group_input_custom.lua

Fix warcraft match2 team player input handling. Namely suppress duplicate entries from manual + wiki var inheritance
dev

Fix team player input handling

---

components/infobox/commons/infobox_person.lua
components/infobox/commons/infobox_team.lua

Save earnings by year into the new `earningsbyyear` field
tested in dev

feat: save earnings by year in `earningsbyyear`

---

components/prize_pool/commons/prize_pool_base.lua

As discussed in discord:
The change to `Json.stringifySubTables` introduced in #3497 changed the values of `nil` fields when stored in LPDB.
This sets json fields to empty tables by default, so they are of type table when being read from LPDB again.
In TeamCard/Storage this is similar, but at least players/opponentplayers are already set as empty table there.
via /dev (see [here](https://liquipedia.net/commons/Special:LiquipediaDB/MainspaceTest#placement) - these testcases don't entirely prove how the issue is fixed, but they show it does not break anything)

PPT: Set empty tables for lpdb json fields

---

standard/error_ext.lua

Fix this broken due to the default to non-array json stringify.
Live fixed.

fix: print `erorStackTrace` as array in ErrorExt

---

components/infobox/wikis/warcraft/infobox_item_custom.lua

note: needs a bot run `python pwb.py replace -lang:warcraft -transcludes:"List With Categories" -regex "\{\{[lL]ist[_ ]With[_ ]Categories" "{{Json" -summary:"remove template:List With Categories"` after merge
The old template cann be removed afterwards
Store sold from in warcraft infobox item. Data is needed for on wiki usage.
Also get rid of a stupid template that set additional categories and build display for the sold from input.
dev

Store sold from in warcraft infobox item

---

components/infobox/commons/infobox_person.lua
components/infobox/extensions/commons/player_introduction.lua
components/infobox/wikis/ageofempires/infobox_person_player_custom.lua
components/infobox/wikis/apexlegends/infobox_person_player_custom.lua
components/infobox/wikis/arenaofvalor/infobox_person_player_custom.lua
components/infobox/wikis/callofduty/infobox_person_player_custom.lua
components/infobox/wikis/fortnite/infobox_person_player_custom.lua
components/infobox/wikis/halo/infobox_person_player_custom.lua
components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua
components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua
components/infobox/wikis/naraka/infobox_person_player_custom.lua
components/infobox/wikis/pubgmobile/infobox_person_player_custom.lua
components/infobox/wikis/rainbowsix/infobox_person_player_custom.lua
components/infobox/wikis/tft/infobox_person_player_custom.lua
components/infobox/wikis/valorant/infobox_person_player_custom.lua
components/infobox/wikis/wildrift/infobox_person_player_custom.lua
components/infobox/wikis/zula/infobox_person_player_custom.lua

note: merge should happen coordinated so that https://liquipedia.net/commons/Template:PlayerTeamAuto can be adjusted right after the merge
- Merge PlayerTeamAuto module (non git) into `Module:PlayerIntroduction` (git)
- Add PlayerTeamAuto (locked behind option param) to Infobox/Person commons base
dev

Add PlayerTeamAuto

---

standard/error_ext.lua
standard/result_or_error.lua

Four (one minor) fixes in this PR:
- `error.error` sometimes didn't match the expected pattern of `string.format`, so it was causing errors.
- `mw.ext...` stack lines wouldn't be processed correctly.
- filtering of unneeded error lines wasn't working.
- sometimes certain lines needed whitespace trimming (minor).
Also, moved from `Module:Error/Ext` to `Module:ResultOrError` as this is working on class `Error` which is sub-class of `ResultOrError` and not the class `error` or `Error` from `Module:Error`.
`/dev`.
| Borked | Fixed |
| ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/ab287a3b-2e2d-4030-8b81-50d8584f9ae5) | ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/553c4aad-a953-47e2-ad1e-5e38bfbbf8ed) |

fix: `Error/Ext` filtering and `mw.ext` errors

---

components/match2/wikis/tetris/match_summary.lua

We want to record the [TWC final bracket](https://worlds.tetr.io/brackets/#ZX), where matches are bo3 sets, ft11 rounds. We were thinking of using Map to represent these sets, but the default Map display doesn't include the game scores of each round:
Example:
So, tried copying some ideas over from https://liquipedia.net/callofduty/Module:MatchSummary, which is pretty similar to what we want.
Sample bracket
https://liquipedia.net/tetris/Module:MatchSummary/dev
https://liquipedia.net/tetris/index.php?title=User:Mitsu_at/Sandbox&oldid=15229

Tetris: Add ability to display map game scores in MatchSummary

---

components/match2/commons/display_util.lua
standard/error_ext.lua
standard/result_or_error.lua

Instead of printing out a hard-to-read stack trace, use the new result or error printing functionality here too.

feat: use `ResultOrError` in `DisplayUtil`

---

components/match2/wikis/warcraft/match_group_input_custom.lua
components/match2/wikis/warcraft/match_group_util_custom.lua

As per request by warcraft contributors adjust some race processing in warcraft submatches
- allow random for submatches via a map having `tXpYrandom = true` 
- if mixed races (player with different races in different maps of the submatch) and not random set race to `m` (Multi)
- else fall back to what is currently used
Additional minor cleanup in `MatchGroup/Util/Custom`: `Ix` --> `Index` (as 2nd commit)
dev

Adjust some race processing in warcraft submatches

---

components/match2/wikis/warcraft/match_group_input_custom.lua

Fix warcraft team player input in match2.
If reading player data from different sources (wiki var, manual input) it intermingles them in a way that can cause issues.
Namely it sometimes adds flags/displaynames/factions to the wrong players if several input methods are mixed.
dev

Fix warcraft team player input in match2

---

components/match2/commons/match.lua

Parse json strings in `Match._moveRecordsFromMatchToList`.
This PR fixes Valorant bigMatch
dev

Parse json strings in `Match._moveRecordsFromMatchToList`

---

standard/links/commons/links_priority_groups.lua

Module:Links/PriorityGroups was apparently maintained via git, but had no deploy header to wasn't pushed live automatically.
N/A

Add missing deploy header

---

components/earnings/wikis/worldoftanks/earnings.lua

Unlike other wikis, World of Tanks has a significant coverage of **15vs15** which includes a **18-21 player teamcards** on the wiki. This Custom Earnings is to set the upper limit to **21** the most number seen in a teamcard from what I told
Previously without these the earnings just stops after 10th player
LIVE

Add Custom Earnings for World of Tanks

---

standard/info/wikis/worldoftanks/info.lua

There were three missing games in this info modules
these related to the WoT Infobox changes which introduces |game= input as well
Currently Live

Add missing games to WoT Info

---

.stylelintrc.json
stylesheets/commons/Bracket.css
stylesheets/commons/Brackets.css
stylesheets/commons/Crosstable.css
stylesheets/commons/DivTable.css
stylesheets/commons/Grid.css
stylesheets/commons/Icons.css
stylesheets/commons/Infobox.css
stylesheets/commons/Mainpage.css
stylesheets/commons/Miscellaneous.css
stylesheets/commons/Navbox.css
stylesheets/commons/OpponentList.css
stylesheets/commons/Prizepooltable.css
stylesheets/commons/Statisticstable.css
stylesheets/commons/TeamTemplates.css
stylesheets/commons/Teamcard.css
stylesheets/commons/Techtree.css

Change the quote-style to `double` instead of default `single`. This is because single quotes ends up being problematic when there's a combination of `var` and `calc` together (such as here https://github.com/Liquipedia/Lua-Modules/pull/3551/files#diff-2fad38bd1d381f4a4e899cceb22da429ce989db910ffad93c03c27632d2b1ec1R78), breaking the parsing all together

fix: change single-quotes to double-quotes to fix

---

stylesheets/commons/GroupTableLeague.css
stylesheets/commons/OpponentList.css
stylesheets/commons/Prizepooltable.css
stylesheets/commons/Teamcard.css

`less` complies `grid-column: 5 / -1` into `grid-column: -5` by default (it does math). This has been fixed in [newer versions of less](https://lesscss.org/usage/#less-options-math), but we're still running [2.X](https://github.com/less/less.js/issues/1880).
For now apply the escaping work around, where `~""` will be treated as pure-css by the less complier and not ass less

fix: escape division signs

---

standard/result_or_error.lua

When reading and error message, if the error text or assertion error text contains `:`, then whatever follows get eaten by the text splitting and then not printed out by the string formatting since it doesn't expect it.
Added some code to handle splits that are larger than the expected four.
`/dev`

fix: ResultOrError `errorShort` formatting with extra colons

---

stylesheets/commons/Brackets.css

The bracket designer buttons design is broken on dark mode and the new skin (see picture below). This is due to the `button` CSS rules adding a radius and minimum height. I fixed it by putting the default value to 0.
Tested on my dev environment [here](http://killian.wiki.tldev.eu/rocketleague/Special:BracketDesigner)
[Gitlab ticket](https://gitlab.com/teamliquid-dev/liquipedia/web/skins/lakesideview/-/issues/51)

Fixing style bracket designer buttons

---

stylesheets/commons/Mainpage.css

We are experimenting with a new portal style for the home page of an incoming new game. It's a very game focused page with bigger portal pills (thus the name big-portal)
Here is a screenshot of the final design:
Implemented on my dev environment (the screenshot actually comes from it).
Regarding the implementation, as we are still testing, we would need to add the following lines in the Main Page:
```
<div class="big-portal">
</div>
```
If we want to make it more generic, we would update the `grid` module with variants.

Adding new big portal style

---

components/prize_pool/commons/prize_pool_import.lua
components/prize_pool/commons/starcraft_starcraft2/prize_pool_starcraft.lua

Makes `importLimit` a hard limit on importing, rather than allow overriding by adding extra placements. Disabled on BW & SC2 due to them using opposite functionality.
Tested on `/dev` and new functionality works correct.
@hjpalpha could you test SC2 or BW dev please on a page that uses the old functionality?

feat: add `placementsExtendImportLimit` toggle to PPT import

---

stylesheets/commons/Miscellaneous.css

Add dark reader support to these classes, and also remove an unused gradient that hjpa said isn't needed.
| Dark Reader | Native Dark Theme |
| ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/ce80bc88-974d-4c84-991f-0501bfeaab2d) | ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/1fbc0272-4cfd-44b8-8879-35f55f4c6c13) | 
I didn't :(

Support darkreader on SC/WC darkmode classes

---

components/match2/wikis/brawlstars/match_group_input_custom.lua

The line wasnt there
The wiki is also replacing its matchticker with the standard one on commons, but highlighted tiers was absent due to this line was missing
|dev=1 and then LIVE

Make Brawl Stars stored publishertier in matches

---

stylesheets/commons/Mainpage.css

We are experimenting with a new portal style for the home page of an incoming new game. It's a very game-focused page with bigger portal pills (thus the name big-portal).
It was also asked to justify the content to the center, which is what this PR is doing.
I have implemented and tested it in my dev environment.

Justifying panels for big portal

---

components/results_table/commons/results_table_award.lua

Some award titles can be very short compared to others (and compared to the minimum column width), so I thought it looked a little better to centre them.
Before and after: 
/dev

Centre award in table

---

components/match2/wikis/warcraft/match_legacy.lua

Pass along map in wc match legacy

Pass along map in wc match legacy

---

components/match2/wikis/leagueoflegends/legacy/match_maps_legacy.lua

Add wrapper for league of legends match lists.
[Sandbox](https://liquipedia.net/leagueoflegends/User:LuckeLucky/sandbox)
Create 2 new templates: One to replace [Template:MatchList](https://liquipedia.net/leagueoflegends/Template:MatchList) and another one to replace [Template:MatchListStart](https://liquipedia.net/leagueoflegends/Template:MatchListStart).Also need to add a condition to [BracketMatchSummary](https://liquipedia.net/leagueoflegends/Template:BracketMatchSummary) and [MatchLua](https://liquipedia.net/leagueoflegends/Template:Match/old) to create a Json if they are wrapped by a LegacyMatchList.

Add lol wrapper for legacy match lists

---

scripts/deploy_res.sh

Fix a typo in the deploy script. 
Tested locally that it doesn't error.

fix: bash typo

---

components/match2/wikis/leagueoflegends/legacy/match_maps_legacy.lua

In a walkover the oposing opponent should have score set to 'FF' instead of 'L'. Also walkover was deleted after processing the first opponent.
Live

Fix walkover in Legacy Wrapper

---

.github/workflows/scheduled.yml
scripts/deploy_res.sh

In #3548, forgot to update the schedule/full deploy for JS support
Tested a bit in local bash env

fix: support full deploy for js

---

components/prize_pool/wikis/ageofempires/prize_pool_custom.lua

Sets the notabilitymod to 0 to not have qualified opponents get inflated score in notabilitychecker (as in, score from qualifier and main event).
It would be an alternative to adjust the extra dropoff function to have drops for first placement as well.
via /dev

Set notabilitymod for qualified placements

---

stylesheets/commons/Miscellaneous.css

Temporary fix until we can find a dynamic solution for the page height issue in portals using these hexagons.
Temporary fix until we can find a dynamic solution for the page height issue in portals using these hexagons.
Tested it with the help of Laura and Killian last Wednesday (November 29) using Chrome's devtools.

Temporary small fix to hexagons.

---

components/results_table/commons/results_table_base.lua

Due to team templates being stored in LPDB for opponents, when creating a historical template, the tournament pages need to all be purged to store the correct sub-template then. This causes issues on results table where the team template data is assumed to be accurate when it might not be.
See: https://discord.com/channels/93055209017729024/372075546231832576/1180160034236289145
Fixed by parsing the team template with result date before passing off to opponent display to ensure that if the parent historical team template is still in LPDB data of opponent, then we still display the correct sub-template on results.
`/dev`

fix: results table using wrong TT after creating historical

---

standard/links/commons/links.lua
standard/links/commons/links_priority_groups.lua

Added linkedin to the links luas, so that on the Formula 1 wiki we can link to engineers LinkedIn pages, as many don't have other social media (and a good way to find/learn about engineers outside of LP).
n/a

feat: add LinkedIn links 

---

stylesheets/commons/Miscellaneous.css

Fix the background color in hotkey class to be viable for darkmode
browser inspect
before:
after:

Fix hotkey class for darkmode

---

stylesheets/commons/Prizepooltable.css

There exists usage of the classes used in ppt directly in wikitables in the td elements.
Currently in this case it uses the `background-color: var( --clr-semantic-gold-80, #ffe982 );` definition from Colours.css.
This is not darkmode compliant.
This PR adjusts it for td elements so that if those classes are used directly in the td it shows the darkmode compliant color.
before:
after:
inspect, see screenshots above

Fix ppt color usage directly in td elements

---

components/infobox/commons/infobox_manufacturer.lua

Removes the '.extradata' from the storage call.
Live :/ (module page needs to be locked too)

fix: storage call in infobox manufacturer

---

components/match2/wikis/leagueoflegends/legacy/match_maps_legacy.lua

Handle param `location` in BracketMatchSummary (should've been like that from the start).

Handle param Location in BracketMatchSummary

---

components/match2/wikis/warcraft/legacy/match_group_legacy_default.lua

THis 1-line change allows reset match details in warcraft legacy bracket wrapper to work (after a bot run).
dev (together with #3613 to be able to use dev)
This change doesn't work without an accompanied bot job that changes `"\}\}\s*\{\{[bB]racketMatchSummary"` to `"}}|resetDetails={{BracketMatchSummary"`.
The bot job can be run after or before merge (my bot is busy with other stuff today) though.
Currently Details for finals with rests are not shown at all due to the `{{BracketMatchSummary...}}{{BracketMatchSummary...}}` giving an invalid json.

Allow reset match details in warcraft legacy bracket wrapper

---

stylesheets/commons/Teamcard.css

Making the button a bit more reactive to screen width and also take up less vertical space on wider displays. Also, better support adding an adjacent note text.
https://liquipedia.net/commons/index.php?title=Template:TeamCardToggleButton&diff=537571&oldid=458113
Tested using browser devs tools and then pushed live as needed it for CS wiki.

Some `TeamCardToggleButton` css changes

---

components/opponent/commons/starcraft_starcraft2/opponent_display_starcraft.lua

In #3624 a commit was lost from vscode to git apparently. This PR does it now.
It fixes SC(2) Opponent display in brackets (namely add the missing `BracketOpponentEntry` class) and cleans up the SC(2) OpponentDisplay module a tiny bit
live (was in dev on the weekend already)

fix: SC(2) Opponent display in brackets

---

components/infobox/extensions/commons/infobox_extension_achievements.lua

For use in #3632 since dota2 has their icons spaced out.
| default | spaced |
| ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/693471fd-e4fa-4f98-a05e-9f66e0291666) | ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/fcaaac93-5336-47d1-8638-6fcd05a91b49) | 
Tested on `/dev`

feat: Space icons in Infobox Achievements

---

standard/date_ext.lua

Converts strings like `+2:00` into second values for offsetting unix timestamps.
Needed this functionality for a future PR and thought it's useful to have here rather than it being hidden inside the code of the upcoming PR there it's not really clear why or what it's doing.
Debug console and `/dev` for future PR.

feat: Method to convert TZ offset to seconds

---

components/match2/wikis/stormgate/brkts_wiki_specific.lua
components/match2/wikis/stormgate/get_match_group_copy_paste_wiki.lua

depends on #3624
Add stormgate match support via using sc/sc2 via commons
As per our current (not official) information there is no hero stuff in stormgate 1v1 esports, hence can just use sc/sc2 match system for now, which mostly is located on commons anyways
N/A, copy from sc/sc2
using sc(2) match2 for now due to not having the time to get a match2 setup for stormgate
we will have to give it its own match2 setup when 3v3 with heroes is added to the game.
Then we will also rename race params to faction params to fit the naming used by the game devs better.

Add stormgate match support via using sc/sc2 via commons

---

components/match2/wikis/dota2/match_group_input_custom.lua

Store the featured as a string in the extradata. So that it can be filtered on in the an LPDB query.
Live

fix: make featured queryable in dota2 match2

---

package.json

`stylelint-less` just released v3, which uses `stylelint` v16. 
`grunt-stylelint` does however not yet support `stylelint` v16, causing a conflict, and breaking our pipeline atm.
Force `stylelint-less` back to v2.

fix: do not use `stylelint-less` v3

---

stylesheets/commons/Miscellaneous.css

Was missed due to originally thinking the faction is called human
N/A

Add color inversion to vanguard icon

---

stylesheets/commons/Brackets.css

not urgent, the issue only affects a hand full of pages
- fix some border colors to use vars
- fix (sc2) ffa match2 display (see screenshots below for context)
- that ffa display will get overhauled in 2024 after the BR match2 display is ready but until then imo we should not let it look in darkmode like it currently does
before:
after:

Fix some darkmode issues with match2

---

components/match2/commons/match.lua
components/match2/wikis/brawlstars/match_summary.lua
components/match2/wikis/counterstrike/match_group_input_custom.lua
components/match2/wikis/halo/match_group_input_custom.lua
components/match2/wikis/halo/match_summary.lua
components/match2/wikis/overwatch/match_group_input_custom.lua
components/match2/wikis/overwatch/match_summary.lua
components/match2/wikis/rainbowsix/match_group_input_custom.lua
components/match2/wikis/rainbowsix/match_summary.lua
components/match2/wikis/splitgate/match_group_input_custom.lua
components/match2/wikis/splitgate/match_summary.lua
components/match2/wikis/starcraft/match_legacy.lua
components/match2/wikis/warcraft/match_group_input_custom.lua
components/match2/wikis/warcraft/match_summary.lua

Remove LRThreads field storage. Removed it entirely on wikis that didn't have any usages of it. Took out a few cases of unused `preview` too while at it

feat: remove lrthread

---

components/statistics/portal_statistics.lua

Use the match2 flag in Module:Info, from #3643 to determine when to use Match2 querying, instead of an args parameter.

feat(pstats): use m2 info instead of args

---

components/infobox/wikis/osu/infobox_league_custom.lua
components/infobox/wikis/osu/infobox_person_player_custom.lua
components/infobox/wikis/osu/infobox_team_custom.lua

Has all three in this PR
Based on the merged one for World of Tanks
This includes three Infoboxes
- **Team** (no changes from Tanks)
- **Player** (same as Tanks, only few role changes)
- **League** (removed Maps and add Game Modes param instead)
Currently on LIVE

Add Infoboxes to osu

---

components/infobox/commons/infobox_widget_customizable.lua

Prepare for killing `addCustomCells` and moving it into parse.
These changes technically allow for `addCustomCells` usage while also having `custom` in `:parse`.
The intention is to be able to progress away from `:addCustomCells` entirely and move them all into `:parse`.
AFTER all customs have been adjusted we can remove the entire if
/dev, together with #3663

Prepare for killing `addCustomCells`

---

components/match2/wikis/callofduty/match_group_input_custom.lua
components/match2/wikis/callofduty/match_summary.lua

Adds the Breaking Point icon to the Call of Duty Match2. 
Tested live here: [Userpage](https://liquipedia.net/callofduty/User:Fenrir.SPAZ/BPTestl)
LPDB Data:

Adding Breaking Point Icon and link to Call of Duty Match2

---

standard/json.lua
standard/test/json_test.lua

As part of #3524, allow a single method to parse a whole nested sequence of `{{Json}}` template calls. Also works without any nested escaped JSONs.
`/dev` and testcases.

feat: Add `Json.parseStringified()` for parsing escaped JSON strings

---

definitions/liquipedia_db.lua

resolves #3675 
Add more lpdb tables to annos definitions
- Company
- ExternalMediaLink
- match2 (+ subtables)
- Series
- StandingsEntry
- StandingsTable
- Transfer
- Settings
- Gear
Additionally move `extradata` to `LpdbBaseData` since it is present in all lpdb tables
VSCode

Add more lpdb tables to annos definitions

---

components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua

This little 1 line change forces `TBD` maps in starcraft/starcraft2/stormgate matches to not link the TBD.
dev

Force TBD maps in matches to not link

---

stylesheets/commons/Mainpage.css

The new match ticker takes up more vertical space than the old one. A small css change to make it like the old one and vertically center the score/versus text.
| Old Ticker | New Ticker | Compact Ticker |
|--------|--------|--------|
| ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/6404107d-5a0a-4454-a80f-c65693b1200e) | ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/c7d38c4e-2d3b-4bbd-8a2b-78990b5eaa90) | ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/3e5d3704-a2c6-406d-89df-9e7adc69be2d) | 
Using browser dev tools.

css: Make matchticker versus score more compact

---

components/match_ticker/commons/match_ticker_display_components.lua

As discussed on discord for matches missing scores when first going live...
https://discord.com/channels/93055209017729024/874304000718172200/1186991934724648970
tested on /dev

fix(matchticker): live matches missing opponent scores

---

stylesheets/commons/Teamcard.css

Something weird going on with teamcards that causes sometimes `<dl>` to be present or not. If anyone can work out why, please go ahead.
See discord for more details: https://discord.com/channels/93055209017729024/268719633366777856/1187077920318042134
Anyway, this changes the CSS styling to avoid this issue. It's cleaner this way too, no margin created, instead of creating one and then negating it later on in a parent div.

fix(teamcard): inconsistent inotes height

---

components/opponent/commons/player_ext_custom.lua
components/opponent/wikis/starcraft/player_ext_custom.lua
components/opponent/wikis/starcraft2/player_ext_custom.lua

Redirect player ext custom on commons and sc2/sc
Reason: need it to be directly callable instead of having to check which one to use in e.g. GTL (match2 version) so i can bring it up to be usable for stormgate
N/A

Redirect player ext custom

---

components/infobox/commons/infobox.lua
components/infobox/commons/infobox_basic.lua
components/infobox/commons/infobox_widget_injector.lua
components/infobox/wikis/starcraft2/infobox_league_custom.lua

is thiss generally a good idea?
- Make parent Class available in WidgetInjector if passed along
- with that we also have access to args etc.
- as an example usage updates sc2 infobox league accordingly
- this infobox still needs a proper cleanup afterwards (incl. adding annos), it is just here as poc
dev
tested without the updates to the /Custom also and it doesn't break anything there too
- clean up all infoboxes to get rid of `_args` and `_league` (and similar)
- might clean up the infoboxes a bit here and there while doing that (and also add remaining annos)

feat: Make parent Class available in WidgetInjector if passed along

---

standard/tier/wikis/formula1/tier_data.lua

Add awards tier type to Tier_data for use on awards pages
Tested a while back using the main module

Add awards as a tier type for Formula1

---

stylesheets/commons/Teamcard.css

`td` is an element not a class 🤦 
browser dev tools 200% this time 🫠
Also pushed it live for now.

fix: CSS mistake in changes of #3688

---

components/results_table/commons/results_table_base.lua

Bug reported on discord: https://discord.com/channels/93055209017729024/268719633366777856/1188884214775545866
When a  historical team template is first created over the top of an existing non-historical, it breaks the query logic of the results table as it instantly expects all results to now be using a sub-template team template, but that takes time to actually spread across all the pages' data.
The query before is like this:
```
([[opponentplayers_p1template::anonymo esports 2021]] OR [[opponentplayers_p2template::anonymo esports 2021]] OR [[opponentplayers_p3template::anonymo esports 2021]] OR [[opponentplayers_p4template::anonymo esports 2021]] OR [[opponentplayers_p5template::anonymo esports 2021]] OR [[opponentplayers_p1template::anonymo esports orig]] OR …
```

fix(results-tbl): Newly historical TTs break player team querying

---

stylesheets/commons/Miscellaneous.css

To rollout Mobile Legends dark mode, we are fixing some spots where colors are still hardcoded. This solves the stream page as bellow:

Moving hard coded stat row color to var

---

stylesheets/commons/Colours.css

This is a hard fix for the _toccolours_ Mediawiki class that uses hard colors (which clashes with dark mode). Example here:
https://liquipedia.net/mobilelegends/M5_World_Championship
Note: Not sure if this is the correct place for the fix
In my test environment: http://killian.wiki.tldev.eu/rocketleague/Test_Background

Removing toccolours hardcoded colors

---

components/infobox/wikis/worldoftanks/infobox_league_custom.lua

Since World of Tanks wiki has 4 games (or 4 possible games) it covers on the wiki, this adds a category for events played on each of these games. 
This is just Category tracking and no LPDB changes or saving.
This is currently being tested live via dev here: [Test page](https://liquipedia.net/worldoftanks/Legendary_Seven_Autumn/2023/Offline)

Adding Game Categories to WoT Infobox League

---

components/infobox/wikis/pubgmobile/infobox_league_custom.lua

As the wiki now uses |game= instead of |platform= to differentiate between game versions, the latter is now deprecated and should be removed
dev module

removing unused |platform= parameter in infobox league

---

components/infobox/commons/infobox_patch.lua
components/infobox/wikis/dota2/infobox_patch_custom.lua
components/infobox/wikis/fortnite/infobox_patch_custom.lua
components/infobox/wikis/halo/infobox_patch_custom.lua
components/infobox/wikis/rainbowsix/infobox_patch_custom.lua
components/infobox/wikis/valorant/infobox_patch_custom.lua

Rewrites the Infobox Patch modules for wikis not being handled by hjp
This PR also requires a refactor to the Base Infobox/Patch in order to correct the custom versions of LPDB saving (they were previously overriding the LPDB). 
dev with patch pages using ``|dev=1`` to confirm LPDB data saving and display

Refactor Patch Infoboxes

---

components/prize_pool/wikis/ageofempires/prize_pool_custom.lua

Stores json-stringified extradata in wikivariable to be able to reset/extend in TeamCard.
Will make most other variables set in this module obsolete once applied.
/dev

AoE PPT: store extradata in variable

---

components/hidden_data_box/wikis/ageofempires/hidden_data_box_custom.lua

AoE match expects names, not identifiers.
Issue introduced with #3655 
live

AoE: Fix wrong game info in HDB

---

standard/info/wikis/callofduty/info.lua

Some games needed cleaner name entries so it doesnt cause 2-row on Infoboxes.

COD Info name adjustments

---

standard/links/commons/links.lua

Fix links in infobox series
Due to changing the order in processing the `Links.makeFullLinksForTableItems` now happens before the display and hence changes the links table.
To avoid that make `Links.makeFullLinksForTableItems` not mutate anymore
dev

Fix links in infobox series

---

components/match2/wikis/omegastrikers/match_group_input_custom.lua
components/match2/wikis/omegastrikers/match_summary.lua

Fix missing map name and incorrect map parsing since #3394 for Omega Strikers.
Live

fix: omega strikers match2 regression

---

components/participant_table/commons/participant_table_base.lua
components/participant_table/commons/starcraft_starcraft2/participant_table_starcraft.lua

Fix "RandomEvent" stuff in sc2 participant table
- set race as random always in this case (both in lpdb data as well as wiki var)
Also:
- fix an anno (`any` --> `ParticipantTableConfig`)
- move class definition annos in base up
- fix a `ParticipantTable:` --> `self:` "typo"
dev to live (since bug fix)

Fix "RandomEvent" stuff in sc2 participant table

---

components/match_ticker/commons/match_ticker.lua

If a team argument is passed by the team doesn't have a team template, the behaviour switches to being a ticker for all teams and isn't filtered anymore. This isn't really intended behaviour imo.
`/dev`
and still works fine on teams with TTs:

fix(matchticker): Unexpected behaviour when TT doesn't exist

---

components/participant_table/commons/starcraft_starcraft2/participant_table_starcraft.lua

if the prize pool )or something else) before the ParticipantTable already sets the faction/race vars as random the players are not displayed in ParticipantTable anymore.
To fix that ParticipantTable unsets the wiki vars before syncing players in this edge case.
dev

Fix an edge case in sc(2) participants table

---

components/infobox/wikis/callofduty/infobox_person_player_custom.lua

Store LPDB data for Players' Team History on CoD. This is so automatically retrieval of player's team can be enabled on other pages via Opponent.sync()
dev=1 https://liquipedia.net/callofduty/Special:LiquipediaDB/Drazah

Store LPDB data for player's history on CoD

---

components/participant_table/wikis/stormgate/participant_table_custom.lua

merges into #3692
Add Stormgate participant table custom instead of using sc2 via commons
THis is a copy of the sc2 version on commons but renaming race to faction everywhere
dev where applicable or "live" if the modules do not get triggered automatically
(PRs #3693, #3694 and #3695 tested together)

Add Stormgate participant table custom

---

javascript/commons/FilterButtons.js

Added functionality to javascript of filter buttons to have certain filters that are not disabled by the "All" toggle. This is useful for tiertypes because of the default "empty" tiertype. If used for something that isn't the empty tier type and a button is still rendered, then you can still toggle it manually.
https://liquipedia.net/commons/index.php?title=Module%3ATournamentsList%2Fdev&type=revision&diff=542325&oldid=542323
https://github.com/Liquipedia/Lua-Modules/assets/5881994/667e3b4b-551d-4893-a5dd-3852bd533cdb
(Monthly is also set as always active for demo purposes only)
Tested on dev wiki.
http://darkrai.wiki.tldev.eu/rocketleague/Main_Page

feat(filterButtons): Exclude disabling some filters with "All" button

---

components/match2/commons/match_group_input.lua
components/match2/commons/match_summary_base.lua
components/match2/wikis/counterstrike/match_group_input_custom.lua
components/match2/wikis/counterstrike/match_summary.lua

Adding the functionality of replacing players within a team opponent for a specific match2 match. Often teams have a sub for a single match and that player doesn't get a record anywhere (in data) that they played, except maybe a manual comment on the match.
Now, the with the following input, players can be replaced in-data for specific matches, and an automatic comment will be added to the match.
A player can either replace another player entirely in a match, or for a specific game only. If they replace them entirely, then the subbed-out player will be removed from the player list, otherwise they will still remain and the sub will be added as an extra player. Players can also stand-in for no-one if a team only had four players at the time but the game needs five, or whatever.
The …

feat: add `substitutes` input for `TeamOpponenent` in match2

---

components/match_ticker/commons/match_ticker_display_components.lua

Fix gradient issue on ios for matchtickers by moving the gradient class from the row to the table element.
The 2nd row has a set BG via css and hence the gradient gets ignored there anyways.
dev + dev page: https://liquipedia.net/starcraft2/Liquipedia:Upcoming_and_ongoing_matches_on_mainpage/dev
viewed on iPhone, samsung galaxy 22 enterprise (android; chrome), desktop (both on chrome, firefox)

Fix gradient issue on ios for matchtickers

---

components/infobox/commons/infobox_person.lua
components/infobox/extensions/commons/age_calculation.lua
components/infobox/wikis/ageofempires/infobox_person_player_custom.lua
components/infobox/wikis/arenaofvalor/infobox_person_player_custom.lua
components/infobox/wikis/brawlstars/infobox_person_player_custom.lua
components/infobox/wikis/fortnite/infobox_person_player_custom.lua
components/infobox/wikis/halo/infobox_person_player_custom.lua
components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua
components/infobox/wikis/pokemon/infobox_person_player_custom.lua
components/infobox/wikis/splatoon/infobox_person_player_custom.lua

Refactor infobox person base module
- refactor agecalculation to not have to rely on wiki variables and be able to handle categories better
- return html instead of string
- kick "global" vars
- codestyle cleanups
- ...
The changes to the customs are only so that we do not break them.
The customs will get refactored in other PRs later on

Refactor infobox person base module

---

.luacheckrc
spec/orm_spec.lua
standard/lpdb.lua

Create an ORM for LPDB. Initial version only has support for saving and only the match2 (and not match2XXX).
Tested with automated busted tests

feat: create an lightweight ORM for saving

---

components/infobox/wikis/warcraft/infobox_character_custom.lua

Correct swapped cell names in warcraft `Module:Infobox/Character/Custom`
live

fix: Correct swapped cell names

---

standard/game.lua
standard/info/wikis/counterstrike/info.lua

Due to there being fake CS2/CS:GO game on the cs wiki, it gets returned by this function but it really shouldn't. Add a param to demote fake games and then use it as a filter.
Untested yet. Will test a bit later, but it should work. Feel free to give feedback on the name `fake`.

feat(games): Don't return fake games from `Game.listGames()`

---

components/match2/commons/match.lua

Use the new ORM to save the LPDB Data. This will automatically strip html tags for everything except extradata.
Tested with /dev

fix: html strip lpdb fields (resolves LPA-11107)

---

standard/lua.lua

Every single occurance of Lua.import (that I could find) has `requireDevIfEnabled=true`. Since this is clearly the default way of using Lua.import, we can skip some verbosity by skipping this flag.
Setup a simple test module to ensure correct dev and non-dev are imported

refactor: default `requireDevIfEnabled` to true in Lua.import

---

components/hidden_data_box/wikis/rainbowsix/hidden_data_box_custom.lua
components/infobox/wikis/rainbowsix/infobox_league_custom.lua
components/infobox/wikis/rainbowsix/infobox_patch_custom.lua
components/infobox/wikis/rainbowsix/infobox_team_custom.lua
components/infobox/wikis/rainbowsix/infobox_weapon_custom.lua
components/match2/wikis/rainbowsix/match_group_input_custom.lua
components/match2/wikis/rainbowsix/match_legacy.lua
components/match2/wikis/rainbowsix/match_summary.lua
components/prize_pool/wikis/rainbowsix/prize_pool_custom.lua
components/squad/wikis/rainbowsix/squad_custom.lua

Remove redundant `requireDevIfEnabled` from r6 git modules
N/A

Remove redundant `requireDevIfEnabled` from r6 git modules

---

components/earnings/wikis/ageofempires/earnings.lua
components/faction/wikis/ageofempires/faction_data.lua
components/faction/wikis/ageofempires/faction_icon_data.lua
components/hidden_data_box/wikis/ageofempires/hidden_data_box_custom.lua
components/infobox/wikis/ageofempires/infobox_league_custom.lua
components/infobox/wikis/ageofempires/infobox_map_custom.lua
components/infobox/wikis/ageofempires/infobox_series_custom.lua
components/infobox/wikis/ageofempires/infobox_team_custom.lua
components/prize_pool/wikis/ageofempires/prize_pool_award_custom.lua
components/prize_pool/wikis/ageofempires/prize_pool_custom.lua
standard/tier/wikis/ageofempires/tier_custom.lua

Remove redundant `requireDevIfEnabled` from aoe git modules
Also fix some indents in faction data modules
N/A

Remove redundant `requireDevIfEnabled` from aoe git modules

---

components/match2/wikis/valorant/legacy/match_maps_legacy.lua

`walkover` is sometimes set as `true` on MatchMaps.
Sometimes, only the agent is input, so we should not stop parsing if player is empty.
Live.

Fix wrapper valorant

---

components/infobox/wikis/rainbowsix/infobox_league_custom.lua

Adds a space between the Game name and Competition in the Infobox League for Rainbow Six

R6 Category adjustment

---

components/match2/wikis/warcraft/legacy/legacy_match_maps.lua

`String.startsWith(key, prefix)` caught keys starting with `map10`, `map11`, ... in the `filterByKey` condition when only looking for `map1`.
This PR adjusts the condition to only filter for the wanted keys
dev to live

Fix: warcraft legacy match maps filterByKey condition

---

components/infobox/commons/infobox_league.lua

Catch non strings for string match checks in infobox league
reason is to avoid errors like on:
https://liquipedia.net/valorant/DreamHack_Community_Clash/Season_1.5/Qualifier_1
dev

Catch non strings for string match

---

.gitignore
.luacov

Setup getting test coverage stats locally
How to run locally (assuming both `busted` and `luacov` are install)
`busted -c && luacov`
```
==============================================================================
Summary
==============================================================================
File                                                                            Hits Missed Coverage
----------------------------------------------------------------------------------------------------
standard/abbreviation.lua                                                       8    0      100.00%
standard/array.lua                                                              123  70     63.73%
standard/class.lua                                                              54   19 …
```

chore: test coverage for local running

---

standard/info/wikis/valorant/info.lua

All old matches now uses legacy wrapper

Update valorant's match2 status

---

components/infobox/wikis/formula1/infobox_team_custom.lua

Add cell to infobox_team_custom.lua
added cell to display a team's last grand prix win on Formula 1
Via dev

Add new statistic Cell to Formula 1 Team Infobox

---

components/infobox/wikis/starcraft2/infobox_person_player_custom.lua

In SC2 infobox person player custom we compare `placement.individualprizemoney` to 50.
To avoid an error cast `placement.individualprizemoney` to be numeric (with 0 as fallback).

Fix: Cast string to number

---

components/match2/wikis/arenafps/match_group_input_custom.lua

https://liquipedia.net/arenafps/Quake_World_Championship/2023#Group_Stage
Trying to call a function that doesn't exist
Live

Fix match2 for afps

---

components/match2/wikis/crossfire/match_group_input_custom.lua

Same issue as #3539 where matches with `**bestof**` set to 2 will accidentally treated as finished immediately after the first game is done (which should not be happening), this fix is to solve this situation from occuring
The fixed code is also brought over from #3539 as the root cause of issue is on the same set of codes
|Dev=1 and LIVE

Fix even bestof issue for CrossFire Match processing

---

standard/info/wikis/ageofempires/info.lua

Given the usage of Module:Game in Infoboxes etc. will map input to Identifiers, which are later on stored, would this be an option to make the commons processing usable (without breaking existing stuff and lpdb data) on AoE?
Input by the old identifiers would still be functional via the (lowercased) abbreviations.
via /dev

AoE: Change game identifiers to be full names

---

components/infobox/wikis/counterstrike/infobox_league_custom.lua

`Game.raw()` always returns empty table if it can't find the game. Annotation was wrong and so was code assumption following anno down the road.
Instead, check if table is empty in this instance so that assumption is correct after.
pushed live to fix broken pages.

fix(infobox): cs league breaks when no game input

---

components/infobox/wikis/worldofwarcraft/infobox_person_player_custom.lua

Currently if dps is entered as a role on wow wiki it (and subsequent roles) are not shown.
This is caused due to the key in the roles table not being lowercased.
This PR fixes that and also removes the `['...']` around the keys in that table.
dev

Fix: lowercase key where it is expected to be lowercase

---

.eslintrc.json
javascript/commons/FilterButtons.js

This reverts commit 1e388179223ae2eb3ae35911cfefd34403bcb985 (#3592)
ES6 is now supported by ResourceLoaderArticles

revert: change from es2017 to es5

---

stylesheets/commons/Teamcard.css

After we fixed the indendation of `<dd>` elements as intended by wikicode and MediaWiki core CSS there is now a left margin on inotes in team cards. This change removes that margin again specifically for this use case
I tested this in the dev tools of my browser

Remove left margin of inotes dd elements after dd fix in skin

---

components/infobox/wikis/counterstrike/infobox_person_player_custom.lua

Fix role display in cs infobox player.
Reported by NiKoholic: https://discord.com/channels/93055209017729024/372075546231832576/1197732608482742432
dev

Fix role display in cs infobox player

---

components/infobox/commons/infobox_person.lua
components/infobox/wikis/dota2/infobox_person_player_custom.lua
components/infobox/wikis/rocketleague/infobox_person_player_custom.lua

After all the customs are now adjusted we can do a cleanup of the commons base.
- move build to after storage
- refactor locations stuff
- move category setting from inside display to categories function
- use `Table.iter.parisByPrefix`
previews with dev on sc2 (using commons), dota2 and rl (both having custom location stuff)

Cleanup `Module:Infobox/Person`

---

components/squad/commons/squad.lua

Adding back Former Squad as an auto generated title for the Squad table. Partial revert of #3349 
Reverting some of the previous changes to allow for there to be discussion about the previous changes to figure out the best course forward. 
dev on left, current on right

Re-Add `Former Squad` header

---

components/infobox/wikis/leagueoflegends/infobox_team_custom.lua
components/infobox/wikis/valorant/infobox_team_custom.lua

Corrects a bug from #3830 where when affiliate was set, it would throw an error "attempt to call field 'team' (a nil value)"
tested in dev

Fixing Team Affiliate always throwing errors

---

scripts/deploy_res.sh

After #3851 the weekly syncing for resources should deploy `.less` files in addition to `.css` and `.js`.
`find stylesheets javascript -type f -name '*.less' -o -name '*.css' -o -name '*.js'`
```
stylesheets/commons/Achievement.less
stylesheets/commons/Ambox.less
stylesheets/commons/AutomaticPointsTable.less
stylesheets/commons/Bracket.less
stylesheets/commons/Brackets.less
stylesheets/commons/Colours.less
stylesheets/commons/Columns.less
stylesheets/commons/Crosstable.less
stylesheets/commons/DivTable.less
stylesheets/commons/FilterButtons.less
stylesheets/commons/Grid.less
stylesheets/commons/GroupTableLeague.less
stylesheets/commons/Icons.less
stylesheets/commons/Infobox.less
stylesheets/commons/Mainpage.less
stylesheets/commons/Matchseries.less
stylesheets/commons/Miscellaneous.less …
```

ci: add support for `.less` files in sync for resources

---

components/infobox/wikis/starcraft/infobox_unit_custom.lua

Use correct class in bw infobox unit so that infobox unit doesn't error and displays correctly again on broodwar.
Bug introduced with #3798

Fix: Use correct class in bw infobox unit

---

components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
components/match2/wikis/warcraft/match_summary.lua

This icon 
1) Doesn't exist as a file
2) Is never used in the code

refactor: remove unused icon

---

components/match2/wikis/apexlegends/match_group_input_custom.lua

Entering a non-numeric placement/kills for a team in a finished match, breaks everything. This fixes it.
Also fix a potential nil error due to typo.
Live

fix(m2, apex): non-numeric score breaks stuff

---

components/match2/wikis/apexlegends/match_summary.lua
stylesheets/commons/BattleRoyale/Panel.less
stylesheets/commons/BattleRoyale/PanelTable.less

To better align the game schedule on overall standings.
Currently it looks like:
With the changes it looks like:
and on mobile:
Also separated the match-countdown-block to have different styling in the panel schedule and panel table.
The table countdown now looks more according the design:
Tested the css on commons

Make game schedule align better

---

components/match2/wikis/apexlegends/match_group_input_custom.lua
components/match2/wikis/apexlegends/match_legacy.lua

Mapping to match1 for Apex, primarily during the transition period, only used by front page match ticker
Live

feat(m2, apex): create mapping to match1

---

components/match2/wikis/apexlegends/match_legacy.lua

HOTFIX: Fix header in apex match legacy, it shredded R6 legacy storage
N/A, reverted the bot deployed stuff on r6 manually, but this needs to be merged before next sync else legacy storage on R6 breaks again

HOTFIX: Fix header in apex match legacy

---

components/infobox/wikis/rainbowsix/infobox_league_custom.lua

Only a visual text change so it will link to the correct page .../Major instead of .../Six Major
Changing the name in Ubisoft-tier for the Major events to represent the correct format and to link to the correct page.
Going from Six Major (Only under ESL this name was used) to just "Major" since BLAST has taken over the production.
Dev module, the result can be seen on the picture: 
Before image:

Changed "Six Major" to "Major" in Ubisoft Tiers

---

components/infobox/wikis/brawlstars/infobox_person_player_custom.lua

Function was defined as class function, but called without self.
dev to live

fix: BS infobox player role processing call

---

components/infobox/wikis/omegastrikers/infobox_league_custom.lua
components/infobox/wikis/omegastrikers/infobox_person_player_custom.lua

I've come to realize these two were lost in the radar and was never added to GitHub, so I did. Player and League Infobox for Omega Strikers 
This include a refactoring of these module to be based on the recently merged SMITE ones 
- League Infobox have the Game function removed (OS dont need one here)
- The old Player Infobox had similar Role/Data situation like SMITE, so we're porting that one here with the fixes. The old one also have signature characters but also similar to SMITE it is better to move away from it
The infoboxes are Live since the wiki is up last year, the new version in this PR are just being tested both dev=1 and live just today
Has both infobox in this module

Add Omega Strikers player and league infobox

---

stylesheets/commons/BattleRoyale/PanelTable.less

Sometimes the team name is longer than the reserved cell space in the table, which causes the cell to expand. I talked with Jasper how to solve this and we decided to add an overflow to the cell and to encourage using shorter bracket display names. 
I tested the css in the browser console.

BR - Team name overflow in table

---

components/prize_pool/commons/prize_pool_import.lua

Essentially adding functionality like importLimit but in the reverse direction when importing a stage in PPT. Could do this before in a different way for group stages using elim colors, but doesn't work for brackets obv.
Example here where need to import first bottom two teams from each group, then the play-in bracket, and then finally winners of the groups from the first part.
https://liquipedia.net/counterstrike/BLAST/Premier/2024/Spring/Groups
`/dev` running live on that example page.

feat(prizepool): add skipping placements from start when importing

---

components/match2/wikis/apexlegends/match_legacy.lua

Each `m2game` is a `match1`, but the logic to set `m1.finished` currently comes from `m2.finished`. This updated so it comes from `m2game.winner` instead.
Live

fix(m2, apex): fix logic for finished games

---

standard/region/commons/region_data.lua

There already exists a latam region in the data, so we shouldn't remap it to south america.
https://discord.com/channels/93055209017729024/268719633366777856/1201624845784453280
Due to wiki custom remapping SA to LATAM, and then region module remapping it back, it ended up in a endless loop fighting over itself until it overflows the stack.
live to fix broken pages.

fix(region): don't remap latam to south america

---

standard/region/commons/region_data.lua

Adds LAN (LATAM North) and LAS (LATAM South) as aliases for Latin America.
Neither of these are currently used by ISO Alpha-3 (see below)

Adding LAN and LAS as Latin America Region aliases

---

components/match2/wikis/apexlegends/match_legacy.lua

Set match1.header for matchlists also. It was meant to do it from the start, but forgot to fix the condition.
Live

fix(m2, apex): also inherit header to m1 for matchlists

---

components/match2/wikis/apexlegends/match_group_input_custom.lua

Don't use the index of the opponent, use their placement instead
Live

fix(m2, apex): use correct number to apply bg from

---

.github/workflows/luacheck.yml

[Github is retiring Node16 in a couple of months](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) and action-junit-report@v3 is using node16. Upgrading to v4 which is using node20.

ci: upgrade `action-junit-report` to `v4`

---

.github/workflows/deploy.yml
.github/workflows/luacheck.yml
.github/workflows/resources.yml
.github/workflows/scheduled.yml

[Github is retiring Node16 in a couple of months](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) and actions/checkout@v3 is using node16. Upgrading to v4 which is using node20.

ci: upgrade checkout action to v4

---

standard/date_ext.lua

Prep date switch by adding additional consts to `Module:Date/Ext` and using them in git modules.
We can also adjust other modules on commons (and on the wikis) to use them instead of hardcoded 1970 dates.
A swift merge would allow me to adjust non git modules (~400) in the next days for the default date switch.
N/A

Add vars to DateExt for date switch

---

components/infobox/wikis/rocketleague/infobox_map_custom
components/infobox/wikis/rocketleague/infobox_map_custom.lua

Creates a new Rocket League Infobox for Map pages 
While some of these fields should (in theory) be broken down and dispalyed nicer, the wiki doesnt seem to care. So the format was copied exactly

Create Rocket League map infobox

---

javascript/commons/BattleRoyale.js

On for example https://liquipedia.net/apexlegends/FFL/REBOOT_2#Results there was a bug that the side scroll arrows wouldn't show on load because the parent was hidden behind the 'weeks' tab and therefor returned a width of 0. 
By adding the observer it checks if the size of the target element changes and then executes the function 'recheckSideScrollButtonStates'.
Tested my changing the JS on commons.

BR - Add observer for side scroll buttons

---

components/infobox/commons/infobox_team.lua

Fixes 3 related issues:
1) Unexpected input errors 
- Caused by not having ReferenceCleaner.clean in the inital parse date
- Added start and end of the regex to check for valid string as additional security
2) Basic input with just date not storing into LPDB
- Caused by the same as above
3) Team having STD images not showing `[[File:]]`
- Fixed with the String.isNotEmpty() check
The two first were caused during a refactor to clean up the code before release, and that case wasn't retested.
Live

fix(infobox team): created sometimes not working as intended

---

components/infobox/wikis/mobilelegends/infobox_item_custom.lua

With #3856 an icon module was added to commons that gets called inside match2.
ML had a custom module in its place. Hence Match2 MatchSummary errored.
I moved the Module. Due to the old module being used in Infobox item we now have to adjust the import accordingly.
Live

Fix: Mobile Legends match2 and hence adjust Infobox/Item

---

components/opponent/wikis/stormgate/player_ext_custom.lua

It is called from inside the match2 GTL.
Currently it gets copied from the commons base, but that only calls the commons `syncPlayer` function that does not sync faction.
dev to live

Add `populatePlayer` to stormgate `Module:Player/Ext/Custom`

---

components/infobox/extensions/wikis/stormgate/infobox_extension_cost_display.lua

Add stormgate CostDisplay infobox extension.
It will be used in infoboxes unit/building/hero (probably will create them later this week) and probably some other non git cases too.
It follows closely the sc2 version but with different keys.
Since the game is still in beta we do not have proper icons as of now, hence for now using place holders instead.
N/A

Add stormgate CostDisplay infobox extension

---

components/match2/wikis/apexlegends/match_summary.lua

Fix unintended changes to Apex's match summary in #3856 icon that broke the completed icon
Live

fix(m2, apex): broken completed icon

---

standard/date_ext.lua

Switch the default date from `1970-01-01` to `0000-01-01`
- Adjust the templates:
- https://liquipedia.net/commons/Template:DefaultYear
- https://liquipedia.net/commons/Template:DefaultDate
- https://liquipedia.net/commons/Template:DefaultDateTime
- change the default date in lpdb --> @FO-nTTaX / devs
- adjust the lpdb data (via sql access) --> @FO-nTTaX /devs
N/A

switch default date

---

components/match2/wikis/dota2/match_group_input_custom.lua

Apply `syncPlayer` for `Module:MatchGroup/Input/Custom` on Dota2 wiki so that party (solo) opponents can pull data from ParticipantsTable.
Copied from CS wiki.

feat(match2): sync party opponents' data for dota2

---

components/infobox/extensions/wikis/stormgate/infobox_extension_attack.lua

Add attack infobox extension for stormgate.
It will be used in infoboxes unit/building/hero (to be created later this week).
It stores the attack data so we can retrieve it for automated overview pages.
intended usage in the infoboxes:
```lua
for _, attackArgs, attackIndex in Table.iter.pairsByPrefix(args, 'attack') do
Array.extendWith(widgets, Attack.run(attackArgs, attackIndex, self.faction)
end
```
N/A (consumers do not exist yet)

Add attack infobox extension for stormgate

---

components/match2/wikis/arenafps/match_group_input_custom.lua
components/match2/wikis/arenaofvalor/match_group_input_custom.lua
components/match2/wikis/callofduty/match_group_input_custom.lua
components/match2/wikis/counterstrike/match_group_input_custom.lua
components/match2/wikis/criticalops/match_group_input_custom.lua
components/match2/wikis/crossfire/match_group_input_custom.lua
components/match2/wikis/dota2/match_group_input_custom.lua
components/match2/wikis/halo/match_group_input_custom.lua
components/match2/wikis/heroes/match_group_input_custom.lua
components/match2/wikis/mobilelegends/match_group_input_custom.lua
components/match2/wikis/osu/match_group_input_custom.lua
components/match2/wikis/overwatch/match_group_input_custom.lua
components/match2/wikis/pokemon/match_group_input_custom.lua
components/match2/wikis/splatoon/match_group_input_custom.lua
components/match2/wikis/splitgate/match_group_input_custom.lua
components/match2/wikis/valorant/match_group_input_custom.lua
components/match2/wikis/wildrift/match_group_input_custom.lua
components/match2/wikis/worldoftanks/match_group_input_custom.lua
components/match2/wikis/zula/match_group_input_custom.lua

As a follow-up to #3921, drop the need for `hasDate` and use timestamps instead. Second step of #1889
Tested on counterstrike

refactor: remove `hasDate`

---

components/match2/wikis/arenaofvalor/match_summary.lua
components/match2/wikis/brawlstars/match_summary.lua
components/match2/wikis/callofduty/match_summary.lua
components/match2/wikis/clashofclans/match_summary.lua
components/match2/wikis/counterstrike/match_summary.lua
components/match2/wikis/criticalops/match_summary.lua
components/match2/wikis/crossfire/match_summary.lua
components/match2/wikis/dota2/match_summary.lua
components/match2/wikis/halo/match_summary.lua
components/match2/wikis/heroes/match_summary.lua
components/match2/wikis/mobilelegends/match_summary.lua
components/match2/wikis/omegastrikers/match_summary.lua
components/match2/wikis/overwatch/match_summary.lua
components/match2/wikis/pokemon/match_summary.lua
components/match2/wikis/splitgate/match_summary.lua
components/match2/wikis/valorant/match_summary.lua
components/match2/wikis/wildrift/match_summary.lua
components/match2/wikis/zula/match_summary.lua

Since #3921 good timestamps are always available. Use those instead of the double string check.
Final part of #1889 cleanup
Changes to what other wikis already use

refactor: use timestamps conditions in match summary

---

components/match2/wikis/arenaofvalor/match_summary.lua
components/match2/wikis/brawlstars/match_summary.lua
components/match2/wikis/clashroyale/match_summary.lua
components/match2/wikis/dota2/match_summary.lua
components/match2/wikis/heroes/match_summary.lua
components/match2/wikis/leagueoflegends/big_match.lua
components/match2/wikis/leagueoflegends/match_summary.lua
components/match2/wikis/mobilelegends/match_summary.lua
components/match2/wikis/omegastrikers/match_summary.lua
components/match2/wikis/pokemon/match_summary.lua
components/match2/wikis/valorant/big_match.lua
components/match2/wikis/valorant/match_summary.lua
components/match2/wikis/wildrift/match_summary.lua

Use CharacterIcon intead of AgentIcon/ ChampionIcon.
`Module:CharacterIcon/Data` was created for all the wikis listed bellow.
All tested on /dev.
*transparent?

Update match summary to use CharacterIcon

---

standard/region/commons/region_data.lua

Missed during initial PRs and is used on LoL wiki and probably other Riot wikis too.
Just data but pushed live to fix pages and working fine.

data(region): add missing china alias

---

components/match2/wikis/wildrift/match_group_input_custom.lua

Introduced in #3942
Live by Martin

fix: typo in wild rift m2 causes error

---

components/match2/commons/match_group_util.lua

As found on discord: 
https://discord.com/channels/93055209017729024/874304000718172200/1204127039293100033
This was still defaulting to `0` timestamp instead of `-62167219200`, causing issues in some display stuff.
Reading match records was still relying on `timestamp` entry in extradata that isn't set in a lot of wiki customs when the date is empty. Instead, just convert from date to timestamp on the fly like this to make sure it doesn't happen again. No need for default fallback either.
Maybe there is a performance impact from this though, so can also do it like this if we still want to rely on timestamp in extradata:
https://liquipedia.net/commons/index.php?title=Module:MatchGroup/Util/dev&diff=549569&oldid=549574
`/dev`.

fix(match2): timestamp default `0` missed in #3897

---

components/infobox/extensions/wikis/stormgate/infobox_extension_attack.lua
components/infobox/wikis/stormgate/infobox_building_custom.lua
components/infobox/wikis/stormgate/infobox_unit_custom.lua

At request by contributors:
- unify buildtime key between the infoboxes
- Move Attack display to bottom of the infoboxes so it looks better (due to the attacks having headers)
- change effect in attacks to csv and linking display
- make passive link in buildings
- make built comma sep list in infobox unit
- add a missing space in unit categories
live since not yet really in use

Adjust stormgate unit and building infoboxes

---

javascript/commons/Miscellaneous.js

We want to understand what percentage of page views use the dark theme if available.
I did not test this
* https://gitlab.com/teamliquid-dev/liquipedia/web/extensions/teamliquidintegration/-/issues/27

Add dark theme usage tracking

---

components/match2/commons/get_match_group_copy_paste.lua
components/match2/commons/get_match_group_copy_paste_wiki.lua
components/match2/commons/starcraft_starcraft2/get_match_group_copy_paste_starcraft.lua
components/match2/wikis/apexlegends/get_match_group_copy_paste_wiki.lua
components/match2/wikis/arenafps/get_match_group_copy_paste_wiki.lua
components/match2/wikis/brawlstars/get_match_group_copy_paste_wiki.lua
components/match2/wikis/counterstrike/get_match_group_copy_paste_wiki.lua
components/match2/wikis/dota2/get_match_group_copy_paste_wiki.lua
components/match2/wikis/halo/get_match_group_copy_paste_wiki.lua
components/match2/wikis/leagueoflegends/get_match_group_copy_paste_wiki.lua
components/match2/wikis/rainbowsix/get_match_group_copy_paste_wiki.lua
components/match2/wikis/rocketleague/get_match_group_copy_paste_wiki.lua
components/match2/wikis/splitgate/get_match_group_copy_paste_wiki.lua
components/match2/wikis/starcraft/get_match_group_copy_paste_wiki.lua
components/match2/wikis/starcraft2/get_match_group_copy_paste_wiki.lua
components/match2/wikis/stormgate/get_match_group_copy_paste_wiki.lua
components/match2/wikis/valorant/get_match_group_copy_paste_wiki.lua
components/match2/wikis/warcraft/get_match_group_copy_paste_wiki.lua
components/match2/wikis/wildrift/get_match_group_copy_paste_wiki.lua

Clean up the Copy Pastas a bit, fixes annotations warnings etc 
No functional changes
Tested commons + r6

refactor(match2): clean up match copy pastes

---

components/prize_pool/commons/prize_pool_placement.lua

Some modules (e.g. NotabilityChecker) still use the `players` field, which wasn't saved for e.g. DuoOpponents.
via dev

PPT: Fill placement.players from opponentplayers

---

stylesheets/commons/BattleRoyale/PanelTable.less

This PR improves the alignment of the header row text for the games. See attached image.
Closes: https://gitlab.com/teamliquid-dev/liquipedia/web/issue-bucket/-/issues/34
I tested the CSS on the live commons wiki

fix(match2): Bad alignment in BR overview header

---

spec/prize_pool_spec.lua

The ppt arguments didn't have a date set and defaulted to the day of execution.
CI

fix(ppt test): Add a date to arguments

---

components/match2/wikis/counterstrike/match_external_links.lua

Some platforms have updated their platforms with new slugs and/or migrated their old stuff to a legacy sub-domain. Will run bots after merge to update all the old links to their legacy variants.
Just some data :p

data(match2): update cs2 platform links

---

components/infobox/wikis/stormgate/infobox_map_custom.lua

Fix function calls (missing `_`).
introduced with #3728

fix: add missing `_` in function names

---

components/match2/wikis/leagueoflegends/big_match.lua

Leftover from the Big Default Date Rework
Live

fix(match2): lol bigmatch not showing up for matches without date

---

components/infobox/extensions/wikis/stormgate/infobox_extension_cost_display.lua
standard/icon_data.lua

Use font icon for stormgate buildTime in CostDisplay
Looks way cleaner and we do not need to use the sc2 icon anymore
N/A

Use font icon for stormgate buildTime in CostDisplay

---

components/infobox/commons/infobox_person.lua
components/infobox/extensions/commons/age_calculation.lua
components/infobox/wikis/formula1/infobox_person_player_custom.lua

Added death_location and abbreviations as params. Discussion regarding abbreviations [here](https://discord.com/channels/93055209017729024/1077895919200112722/1203059062216982550)
Also minor wording change for custom player infobox
via dev for abbreviations parameter

feat(infobox person): add death location support

---

components/match2/wikis/dota2/match_group_input_custom.lua
components/statistics/portal_statistics.lua
standard/date_ext.lua

Fix typo in defaultYear
Typo was found by spazer and reported [here](https://discord.com/channels/93055209017729024/372075546231832576/1207526671587082350)
This typo seems to be exclusive to defaultYear. I insource searched for the typo using deaultYear, Date, Month, Day. Most modules using the typos aren't on the git so I will open an issue to track them and subsequently change them following this pr.
https://github.com/Liquipedia/Lua-Modules/issues/3993
N/A

Fix typo in defaultYear

---

components/faction/commons/faction.lua

As most factions don't have a pagename that differs from name, default to that for links unless pageName exists
via /dev

feat(faction) Icon: default link to name if no pageName is set

---

standard/date_ext.lua

Remove typo since all usage has been removed https://github.com/Liquipedia/Lua-Modules/issues/3993
N/A

refactor: remove unneeded key

---

components/prize_pool/commons/prize_pool_base.lua
components/prize_pool/commons/prize_pool_legacy.lua
components/prize_pool/wikis/dota2/prize_pool_custom.lua
components/prize_pool/wikis/halo/prize_pool_custom.lua
components/prize_pool/wikis/leagueoflegends/prize_pool_custom.lua
components/team_card/team_card_storage.lua

Will need bot run when going live to replace `smw_prefix` with `lpdb_prefix`

refactor: drop usage of legacy `smw_prefix`

---

components/statistics/portal_statistics.lua

Fix bug on stats portal where the age display subtracted age from defaultYear
Tested live https://liquipedia.net/fortnite/Portal:Statistics

Fix stats portal bug

---

stylesheets/commons/Teamcard.less

With lakeside view skin, button css styling is being applied to buttons that shouldn't have it due to specific application.
Browser dev tools
----
cc @liquidely can we please add `justify-content: center;` to `.main-content-column button` in the skin so that the buttons' text is also centered correctly?

fix(lakeside): CS wiki teamcard toggle buttons

---

javascript/commons/Countdown.js

Adding JS support for https://liquipedia.net/commons/Template:Abbr/AQTT .
Just data.

data(countdown): add AQTT timezone

---

components/opponent/commons/player_display_custom.lua
components/opponent/wikis/starcraft/player_display_custom.lua
components/opponent/wikis/starcraft2/player_display_custom.lua

Add "redirects" for `Player/Display/Custom` to `Player/Display` on commons.
Add "redirects" for `Player/Display/Custom` to `Player/Display/Starcraft` on sc2 and broodwar.
So i can call `Player/Display/Custom` in modules shared between sc(2) and other wikis.
live

Add "redirects" for `Player/Display/Custom`.

---

components/infobox/commons/infobox_person.lua

Fix an annotation warning in infobox person by casting `nil` away after an `isEmpty` check.
VSCode

fix(infobox person): anno warning

---

.eslintrc.json
.stylelintrc.json
javascript/commons/BattleRoyale.js
javascript/commons/Bracket.js

Also, we've got a weird mix of ES6 and ES2020 settings in the ESLint config rn. The wikimedia extends are setting es-x rules to es6, parser is set to 2020, and then env is set to es6 again. It doesn't make much sense to me. I made a commit here to standardize it all to ES2020 and also added jquery to the env as it was missing.
Tested in VS Code.

ci(eslint): properly support ES2020

---

components/infobox/wikis/zula/infobox_league_custom.lua

Apparently this was also a lost module that left unadded, this is based on SMITE's recently merged Infobox league.
As ZULA specificly wants just the highlights and the ability to show the different game versions
I would originally ported cod but realize there might be some significant changes needed due to COD is merged for a long time
**On LIVE**

Setup Infobox League for Zula

---

standard/info/wikis/zula/info.lua

This is part of #4026, Zula has 3 different game versions (in a CS-like manner)
Is the line that says **match2 = 2** needs to be removed? I cant remember what it does now

Add other game versions to Zula

---

components/infobox/commons/infobox_team.lua

depends on #3996
Make org icon in infobox teams created darkmode compatible
dev

feat(infobox team): support darkmode in created field for team logo

---

components/hidden_data_box/commons/hidden_data_box.lua

Due to `Game.toIdentifier()` having `useDefault` fall back to true, it meant that if game wasn't supplied to HDB, it would always use the default game for that wiki and never the query result from the parent.
tested on /dev.

fix(hdb): game was always default if no input

---

components/match2/wikis/clashroyale/match_summary.lua

As requested on discord by Vishu. Closes #4028.
`/dev` on CR wiki.

feat(matchsummary): add tower cards to clash royale

---

javascript/commons/FilterButtons.js

Adding the functionality to use a new optional "curated" button to instantly swap to a list of tournaments defined by the wiki editors.
* Clicking the button at any point will automatically disable all other filters for that filter group and apply a pre-defined curated list of tournaments. Other filter groups will still apply, so you can further filter the list as you wish.
* Clicking the all button when curated is active will just do the normal all-button functionality.
* Clicking another button when curated is active will enable that button and restore all other buttons to their state before curated was activated.
* All states are remembered even on page reload.
Also re-added missing default filters functionality that I unintentionally overwrote in the previous PR due to it not being …

feat(filterbuttons): implement optional curated button

---

javascript/commons/FilterButtons.js

In order to maintain compatibility with filters applied directly onto elements with other classes, re-worked how the filter classes are applied to not delete existing classes. Not really a bug as it didn't break anything existing, but want to be able to use them like this for an upcoming project.
Tested on the dev wiki as before.

fix(filterbuttons): keep compatibility with existing classes

---

standard/links/commons/links.lua

Update `strikr` link as per mention on discord by benjastrike
https://discord.com/channels/93055209017729024/268719633366777856/1212824886796488745
> Hi, there is a |strikr= website for playersinfobox, but the domain of the page change to https://strikr.pro/, how can i change that?
N/A

Update `strikr` link

---

components/infobox/wikis/mobilelegends/infobox_item_custom.lua

pass back `nil` instead of nothing so the `table.insert` in `Array.map` doesn't throw

fix: error when attribute content is empty on MLBB infobox item

---

components/infobox/wikis/warcraft/infobox_league_custom.lua

Use prefixvar that gets passed to function instead of hardcoded `'map'` so we actually get different maps for the different map lists

fix: use prefix instead of hardcoded `'map'`

---

definitions/mw.lua
standard/page_variable_namespace.lua
standard/variables.lua

`wikiVaribleKey` --> `wikiVariableKey`
N/A

fix: typo in annotation class

---

components/match2/wikis/stormgate/get_match_group_copy_paste_wiki.lua

fix: add missing `}}` in sg match copy paste

fix: add missing `}}` in sg match copy paste

---

javascript/commons/BattleRoyale.js

A sideways scroll button should appear when the Battle Royale Match 2 table is too wide for a screen. However, the sideways scroll button disappears when toggling to an alternative match/group.
This triggers checks on the panel and game change.
Fix for: https://gitlab.com/teamliquid-dev/liquipedia/web/issue-bucket/-/issues/37
Tested by changing [the script on commons](https://liquipedia.net/commons/index.php?title=MediaWiki:Common.js/BattleRoyale.js), updating Resource Loader Message and manual testing [here](https://liquipedia.net/apexlegends/Apex_Legends_Global_Series/2024/Split_1/Challenger_Circuit_1/APAC_South/Semifinals)

fix: BR sideways scroll buttons dissapears when toggling between matches

---

stylesheets/commons/BattleRoyale/PanelTable.less

As requested, the padding in the BR tables for placements and kills is reduced to 0.5rem.
Chrome dev tools

BR - Change padding for placements and kills

---

stylesheets/commons/Miscellaneous.less

Add styles for `sfrac` template so we can get rid of the hardcoded color (border top/bottom).
secret commons

Add styles for `sfrac` template

---

components/hidden_data_box/wikis/rocketleague/hidden_data_box_custom.lua

Fix an annotation warning in rl hdb by telling it which custom infobox league it uses
VSCode

fix(RL HDB): remove anno warning

---

standard/date_ext.lua

Allow osdate/osdateparam as valid input in some dateExt functions
dev

feat(DateExt): Allow osdate/osdateparam as valid input in some functions

---

components/match2/wikis/warcraft/get_match_group_copy_paste_wiki.lua

fix(wc match2 copy paste): add missing `}}` for literal opponents map details
live

fix(wc match2 copy paste): add missing `}}` for literal opponents map details

---

components/match2/wikis/ageofempires/match_legacy.lua

Add matchsection to match1 extradata to make match2 compatible with `SwissTableLeagueTeam`.
[discord](https://discord.com/channels/93055209017729024/268719633366777856/1215956299791994932)
live

fix: Add matchsection to match1 extradata

---

components/match2/wikis/arenaofvalor/match_group_input_custom.lua

Make use of [Module:HeroNames](https://liquipedia.net/arenaofvalor/Module:HeroNames) to map a possible hero alias to its real "name".
Only commit 076c553aaec581c5dbe799e9397f8a629a15ed2f represents the change.
dev

fix: Use hero name alias in arenaofvalor

---

components/match2/wikis/clashofclans/match_group_input_custom.lua

This is for events that using Duo or Solo opponents, to have flags automatically tracked on brackets or matchlists. As Clash of Clans start having more non-team events

Enable syncPlayer for CoC Processing

---

components/infobox/extensions/commons/infobox_extension_patch_auto.lua
components/infobox/extensions/wikis/stormgate/infobox_extension_patch_auto.lua
components/infobox/wikis/stormgate/infobox_league_custom.lua

Automate patches in infobox league on stormgate.
- if no patch is entered retrive the correct patch (based on dates)
- if patch is entered but patch display is not retrieve the patch name for diplay
extension "live" as new and not in use, infobox league via dev

feat(stormgate infobox league): automate patches

---

stylesheets/commons/Miscellaneous.less

Some matchtickers (e.g. valorant) apply highlighting to publishertier matches.
This makes the already defined classes darkmode compatible, using the same variables as the non-publishertier versions combined with the usual highlighting color.
inspector:
Before:
After:

fix(css) recent-matches-publishertier darkmode compatibility

---

components/match2/wikis/ageofempires/match_group_input_custom.lua
components/match2/wikis/ageofempires/match_summary.lua

- Contributors requested initialized score if match has started and a map has details entered.
- Width change necessary due do long names otherwise overflowing.
- Font and margin changes to be more similar to match1 popups.
via dev
Visual changes, before:
After:

fix(match2) Various match2 improvements on AoE

---

standard/tabs.lua

Adds the tabs module to the git.
Changes compared to live:
- code changes to meet git standards better
- add option `removeEmptyTabs` (removes empty tabs in tabs dynamic) and `returnIfEmpty` (returns instead of erroring if no tab name/link/content args are specified)
- behaviour with misisng content (in case of content being set for at least 1 tab)
- currently: if you have a missing content inbetween it will display the contents "attached" to the wrong tabs
- new: if `removeEmptyTabs` is set to `true` the correct tabs get removed
- new: if `removeEmptyTabs` is false or unset it will error instead
dev

feat: Add tabs component

---

components/match2/wikis/leagueoflegends/big_match.lua
standard/tabs.lua

- git consumers now accept html returns instead of only strings
- `this` edge case (if first tab is empty in tabs dynamic)
- misisng new line in `_single`
- option to suppress header in `_single`
dev

fix(tabs): edge cases failing

---

components/match2/wikis/ageofempires/match_group_input_custom.lua
components/match2/wikis/ageofempires/match_summary.lua

Some tournaments have multiple map- or civdrafts for a single match (especially AoE4 ones), this adds support for adding them.
Also ensures mapdrafts are listed before civdrafts.
dev

feat(match2) Allow multiple drafts for AoE

---

standard/tabs.lua

fix `hide-showall` in tabs
live

Fix(tabs): `hide-showall`

---

stylesheets/commons/Teamcard.less

Reverts Liquipedia/Lua-Modules#4110
Unintended effects on non-valorant wikis

Revert "Add light/dark theme css for btn-theme in teamcard"

---

components/infobox/wikis/apexlegends/infobox_person_player_custom.lua
components/infobox/wikis/arenaofvalor/infobox_person_player_custom.lua
components/infobox/wikis/dota2/infobox_person_player_custom.lua
components/infobox/wikis/dota2/infobox_person_user_custom.lua
components/infobox/wikis/heroes/infobox_person_player_custom.lua
components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua
components/infobox/wikis/naraka/infobox_person_player_custom.lua
components/infobox/wikis/overwatch/infobox_person_player_custom.lua
components/infobox/wikis/overwatch/infobox_person_user_custom.lua
components/infobox/wikis/rainbowsix/infobox_person_player_custom.lua
components/infobox/wikis/rainbowsix/infobox_weapon_custom.lua
components/infobox/wikis/wildrift/infobox_person_player_custom.lua

Update some infoboxes to use CharacterIcon instead of wiki-specific `Module:XIcon`.
On some wikis [Module:CharacterNames](https://liquipedia.net/rainbowsix/Module:CharacterNames) was created, this module contains aliases for the characters, and maybe in the future, we could move all HeroNames, ChampionNames, etc... to this name.
Rainbowsix match2 modules can be updated in the future to use CharacterIcon and CharacterNames.
/dev on certain wikis

feat: Update some infoboxes to use CharacterIcon

---

components/infobox/wikis/ageofempires/infobox_team_custom.lua

Removes the region cell from the infobox, as AoE esports is not divided into regions and the information therefore only duplicates the info from location cells.
/dev

feat(infobox) AoE: Disable region cell in Infobox team

---

components/infobox/wikis/stormgate/infobox_skill_custom.lua

Adds storage for impact.
Impact does not need dispaly it is "just" for conditioning in queries.
Also make the effect display a bit more pretty
dev

feat(infobox): Add impact storage on Stormgate's Skill Infobox

---

components/infobox/wikis/osu/infobox_person_player_custom.lua

Removes status cell overwrite so `Banned` can be displayed in infobox as a valid status. https://github.com/Liquipedia/Lua-Modules/pull/4107 meets the rest of the requested changes
Brought up here: https://discord.com/channels/93055209017729024/1164213669324927096/1218721711768207440
Discussion with hjp: https://discord.com/channels/93055209017729024/874304000718172200/1219815338632417343
dev https://liquipedia.net/osu/Natsuko

feat(infobox person custom osu!): remove status cell overwrite

---

components/match2/commons/match.lua
components/match2/commons/match_group_base.lua
components/match2/commons/match_group_input.lua
components/match2/commons/match_subobjects.lua
components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua

Add annos for input processing parts of match2 on commons and sc(2).
Ignores the FFA stuff for sc(2) due to it to be replaced eventually anyways
/dev (#4098, #4100 and #4102 together)

docs(match2): Input processings commons + sc(2)

---

components/match2/commons/match.lua

fix(doc): Allow boolean for `storeMatch1` in match storage options
VSCode

fix(doc): Allow boolean for `storeMatch1` in match storage options

---

components/automatic_points_table/commons/automatic_points_table.lua
components/automatic_points_table/commons/automatic_points_table_display.lua
components/mvp_table/commons/mvp_table.lua
components/tournaments_summary_table/commons/tournaments_summary_table.lua
standard/hotkey.lua
standard/league_icon.lua

Remove leading underscores of const vars outside of match2 folder to be in line with code style.
(For match2 folder it will happen step by step when annotating it in the next weeks.)
N/A

refactor: code style improvements

---

components/match2/wikis/crossfire/match_group_input_custom.lua
components/match2/wikis/crossfire/match_summary.lua

To allow Casters to be input and display in match summary ( `|casterX=Y` ) like this:
Requested by an editor from the CrossFire wiki (the request actually includes MVP, but that one already exists): 
tested on dev=1

feat(match2): add casters display to CrossFire

---

components/infobox/wikis/valorant/infobox_person_player_custom.lua

- New roles:
1. Content Creator
2. Stats Producer
3. Translator
4. Interpreter
- 'Streamers' role category changed from 'Streamers' to 'Content Creators'
- Added abbreviation for `Years Active (Org)` - not sure if that's the best way to do it though
- `years_active_manage` param renamed to `years_active_org` - there are only a handful of usages, so it can be changed manually on the wiki once merged

feat: add additonal roles to valorant person infobox

---

standard/gallery.lua
standard/team_logo_gallery.lua

- `Module:Gallery` builds a gallery display without using the extension.
- `Module:TeamLogoGallery` builds a gallery of the teams team logos
- uses (historical) team templates and `Module:Gallery`
"live" as new modules

feat: create automated team gallery

---

components/infobox/wikis/overwatch/infobox_person_player_custom.lua

Currently the Player Infobox for Overwatch allows users to list a players signature heroes. However, the Overwatch wiki gets spammed with edits on these signature heroes, so a while ago, we limited the saving of these signature heroes into LPDB to 3. There are currently players on the wiki with more than 6 signautre heroes listed. This limits the display of the signature heroes to 3 to bring it in line with LPDB saving. 
Player example with many Signature Heroes being displayed
Same player LPDB data
[Player ](https://liquipedia.net/overwatch/Stellar) (shown above) page using dev modules

feat: limit SignatureHeroes on OW Player Infobox

---

components/match2/commons/match_group_display_bracket.lua
components/match2/commons/match_group_input.lua

Fixes the storage and display of qual headers
- currently only `R1M1qualifiedHeader` input gets stored, this PR makes it so that it falls back to `qualifiedHeader` if no cell specific qual header is entered
- currently only `qualifiedHeader` input gets evaluated for displayed (but not stored), this PR makes it so that the stored header is taken and only if that is not present it falls back to the `qualifiedHeader` input
As a side effect this now also allows different qual headers for upper and lower brackets via the `RxMy` prefix to `qualifiedHeader`
dev

fix(match2): qualified headers

---

standard/tabs.lua

Static Tabs without a link displays completely bonkers. They should be hidden
Live

fix(tabs): static tabs without links display are wonky

---

components/match2/wikis/rainbowsix/legacy/match_maps_legacy_store.lua
components/match2/wikis/rocketleague/legacy/legacy_match_list.lua

suppress anno warnings in match2 legacy input processings
Note: With this plus already drafted/open PRs we should get down to <10 anno warnings in VSCode :)
VSCode

docs(match2): suppress anno warnings in legacy input processings

---

standard/tabs.lua

revert #4135 as it broke several things (across lots of wikis)
- https://discord.com/channels/93055209017729024/268719633366777856/1224813148541030590
- https://discord.com/channels/93055209017729024/268719633366777856/1224941155460972598
spazer reverted it live

revert:"fix(tabs): static tabs without links display are wonky (#4135)"

---

standard/info/commons/info.lua
standard/info/wikis/ageofempires/info.lua
standard/info/wikis/apexlegends/info.lua
standard/info/wikis/arenafps/info.lua
standard/info/wikis/arenaofvalor/info.lua
standard/info/wikis/artifact/info.lua
standard/info/wikis/autochess/info.lua
standard/info/wikis/battalion/info.lua
standard/info/wikis/battlerite/info.lua
standard/info/wikis/brawlhalla/info.lua
standard/info/wikis/brawlstars/info.lua
standard/info/wikis/callofduty/info.lua
standard/info/wikis/clashofclans/info.lua
standard/info/wikis/clashroyale/info.lua
standard/info/wikis/criticalops/info.lua
standard/info/wikis/crossfire/info.lua
standard/info/wikis/dota2/info.lua
standard/info/wikis/fifa/info.lua
standard/info/wikis/fighters/info.lua
standard/info/wikis/formula1/info.lua
standard/info/wikis/fortnite/info.lua
standard/info/wikis/freefire/info.lua

Remove deprected fields from info modules - part 1
(removed remaining usage i coud find via https://tools.liquipedia.space/?view=search)
N/A

refactor(info): remove deprected fields - part 1

---

standard/info/wikis/smash/info.lua
standard/info/wikis/smite/info.lua
standard/info/wikis/splatoon/info.lua
standard/info/wikis/splitgate/info.lua
standard/info/wikis/squadrons/info.lua
standard/info/wikis/starcraft/info.lua
standard/info/wikis/starcraft2/info.lua
standard/info/wikis/stormgate/info.lua
standard/info/wikis/teamfortress/info.lua
standard/info/wikis/tetris/info.lua
standard/info/wikis/tft/info.lua
standard/info/wikis/trackmania/info.lua
standard/info/wikis/underlords/info.lua
standard/info/wikis/valorant/info.lua
standard/info/wikis/warcraft/info.lua
standard/info/wikis/wildrift/info.lua
standard/info/wikis/worldoftanks/info.lua
standard/info/wikis/worldofwarcraft/info.lua
standard/info/wikis/zula/info.lua

Remove deprected fields from info modules - part 3
(removed remaining usage i coud find via https://tools.liquipedia.space/?view=search)
N/A

refactor(info): remove deprected fields - part 3

---

components/match2/wikis/mobilelegends/match_group_input_custom.lua

We had several 1v1 tournaments for the ML Wiki, but this module doesn't support SoloOpponent. I replaced `typeIsParty(opponent)` with `typeIsParty(opponent.type)` to make it work.
dev https://liquipedia.net/mobilelegends/User:MatryoshX/Sandbox

fix(match2): fix broken 1v1 matches

---

components/infobox/wikis/warcraft/infobox_patch_custom.lua

use commons `setLpdbData` function instead of the faulty local one (causes bad lpdb data)
forgot to remove it in #3711
dev into live

fix(infobox): patch on warcraft is not storing properly

---

standard/links/commons/links.lua
standard/links/commons/links_priority_groups.lua
stylesheets/commons/Icons.less

These are two separate requests that happens on same time 
- Rooter is a streaming platform
- CFS is the official site for CrossFire events, editors requested this to be a separate icon as sometime it needs a usage over a 2nd website parameter
- while the full site is named `crossfirestars` the param was decided to be just `cfs` the site's official shortname
this PR adds the icons and links for both
File needs to be added to CSS by someone else because I cannot edit the .css
https://liquipedia.net/commons/File:InfoboxIcon_Rooter.png
https://liquipedia.net/commons/File:InfoboxIcon_CFS.png

Add Infobox Icons & Links for `Rooter` and `CFS`

---

components/squad/wikis/leagueoflegends/squad_custom.lua

When refactoring the objectnames, league of legends apparently ended up with two row:create(), instead of one. 
IDE would have caught this if it wasn't for ExtendedSquad() being in use.
Live

fix(squad): error on league of legends

---

components/infobox/wikis/formula1/infobox_person_player_custom.lua

Rename the header to clarify which stats are being displayed. Since there are multiple series other than F1
fwiw I do plan on eventually moving stats out of the infoboxes and into a subpage where we can track all series
dev

feat(infobox): rename header on F1 person infobox

---

standard/currency_data.lua

Fixing details of the IDR currency. The name of the currency is Indonesian rupiah, and there is no space after the currency symbol.
https://en.wikipedia.org/wiki/Indonesian_rupiah
via /dev

fix details of the IDR currency

---

components/opponent/commons/starcraft_starcraft2/opponent_starcraft.lua
components/opponent/wikis/warcraft/opponent_custom.lua

Allow `faction` as an alternative input to `race` on warcraft, starcraft and stracraft2. First steps in a possible standardization, but allows for easier usage on commons.
With /dev

feat(opponent): make faction alias to race on craft wikis

---

package.json

grunt-eslint just upgrade to eslint 9 (released a couple of days ago) in v25. Several of our dependencies do not yet support eslint 9, so stopping at v24.
Pipeline is no longer breaking

ci: use grunt-eslint 24.x for now

---

components/squad/commons/squad_custom.lua
components/squad/commons/squad_row.lua
components/squad/commons/squad_utils.lua
components/squad/wikis/apexlegends/squad_custom.lua
components/squad/wikis/arenaofvalor/squad_custom.lua
components/squad/wikis/counterstrike/squad_custom.lua
components/squad/wikis/dota2/squad_custom.lua
components/squad/wikis/halo/squad_custom.lua
components/squad/wikis/leagueoflegends/squad_custom.lua
components/squad/wikis/mobilelegends/squad_custom.lua
components/squad/wikis/overwatch/squad_custom.lua
components/squad/wikis/rainbowsix/squad_custom.lua
components/squad/wikis/rocketleague/squad_custom.lua
components/squad/wikis/smash/squad_custom.lua
components/squad/wikis/smite/squad_custom.lua
components/squad/wikis/starcraft/squad_custom.lua
components/squad/wikis/starcraft2/squad_custom.lua
components/squad/wikis/stormgate/squad_custom.lua
components/squad/wikis/valorant/squad_custom.lua
components/squad/wikis/warcraft/squad_custom.lua
components/squad/wikis/wildrift/squad_custom.lua
spec/squad_spec.lua
standard/lpdb.lua

Use ORM instead of direct function. Gives some validation on key fields and automatic filling on some other fields
dev
Two minor changes to LPDB storage,
extradata will always exist (as empty)
teamname dropped from objectname (unneeded)
LPDB Before:
LPDB After:

feat(squad): use model for storing

---

components/match2/wikis/apexlegends/match_summary.lua
javascript/commons/BattleRoyale.js
stylesheets/commons/BattleRoyale/PanelTable.less

Mobile optimizations:
- Remove icons from Rank, Team and Total points
- Abbreviate Total points to Pts.
Closes [ticket](https://gitlab.com/teamliquid-dev/liquipedia/web/issue-bucket/-/issues/54)
Tested it on the live site.

feat(match2): shorter header titles in mobile view to save width

---

stylesheets/commons/BattleRoyale/PanelTable.less

Increase the border width between games to separate them.
Closes [ticket](https://gitlab.com/teamliquid-dev/liquipedia/web/issue-bucket/-/issues/55)
devtools

feat(match2): extra border width to the game columns on battle royale

---

standard/team_logo_gallery.lua

Currently if images are removed due to being the same as the one before the index used for building the caption is increasedc nonetheless, resulting in jumping "numbering" in captions.
This PR resolves that by first filtering the imageDatas and only after that building the captions (via mapping them).
dev

fix(team logo gallery): incorrect text when skipping an image

---

components/match2/wikis/crossfire/match_group_input_custom.lua

currently crossfire match2 does not store any player data whatsoever from the looks of it
to fix that fetch player data from TeamCards as done on most wikis using the commons function
dev

fix(match2): crossfire is not storing players

---

stylesheets/commons/Colours.less

Black classes getting variables to make anything using them work in dark-mode too.
Chrome dev tool.
Although the issue is more compatibility testing across the whole wiki which I did not test nor do I think I could have, since the colours may have been used on non-dark-theme compliant backgrounds, so it may very well break stuff I am unaware off.

feat: darkmode support for `black` css class

---

components/match2/wikis/ageofempires/match_group_input_custom.lua
components/match2/wikis/ageofempires/match_legacy.lua

resulttype was missing in legacy storage, causing consumers to show 0:0 instead of W:FF
live, bugfix

fix(match2): AoE walkover handling

---

components/infobox/wikis/callofduty/infobox_person_player_custom.lua
components/infobox/wikis/crossfire/infobox_person_player_custom.lua
components/infobox/wikis/formula1/infobox_person_player_custom.lua
components/infobox/wikis/fortnite/infobox_person_player_custom.lua
components/infobox/wikis/freefire/infobox_person_player_custom.lua
components/infobox/wikis/halo/infobox_person_player_custom.lua
components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua
components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua
components/infobox/wikis/naraka/infobox_person_player_custom.lua
components/infobox/wikis/omegastrikers/infobox_person_player_custom.lua
components/infobox/wikis/osu/infobox_person_player_custom.lua
components/infobox/wikis/pokemon/infobox_person_player_custom.lua
components/infobox/wikis/pubgmobile/infobox_person_player_custom.lua
components/infobox/wikis/rainbowsix/infobox_person_player_custom.lua
components/infobox/wikis/smite/infobox_person_player_custom.lua
components/infobox/wikis/splatoon/infobox_person_player_custom.lua
components/infobox/wikis/valorant/infobox_person_player_custom.lua
components/infobox/wikis/wildrift/infobox_person_player_custom.lua
components/infobox/wikis/worldoftanks/infobox_person_player_custom.lua
components/infobox/wikis/zula/infobox_person_player_custom.lua

- fix a bug on lol where if manual TH input was present the THA was stored anyways.
- use `.result` instead of `._result` (was adjusted in the `TeamHistoryAuto` module some time ago to be able to call `.result` from lua)
- use `true` over `'true'` due to `Module:TeamHistoryAuto` using `Logic.readBool` nowadays
dev to live for lol
N/A for the rest

fix(infobox): league of legends storing incorrect data for player history

---

components/team_card/team_card_storage.lua
spec/team_card_storage_spec.lua

Merge `Module:TeamCard/Qualifier` into `Module:TeamCard/Storage` as initially intended (but wasn't possible at the time).
Also migrate the testcases to busted automated testing
Automated testing

refactor(teamcard): move qualifier text parsing from external module

---

components/portal_players/commons/portal_players.lua
stylesheets/commons/Colours.less

Changes first made for https://github.com/Liquipedia/Lua-Modules/pull/4016 but that PR isn't ready for merge as per reviews. 
These changes add a background color to players who have passed away, similar to retired or inactive players, etc.
via dev

feat(portal players): add color for deceased status

---

.luacheckrc
spec/game_spec.lua
spec/test_helper.lua
standard/game.lua

There were a number of issues with this method:
- The casting was wrong
- The filtered array wasn't being used
- The filtering didn't work anyway due to misleading casting.
- Ordered lists didn't even reach filtering code
PR address them all, and I think it should work properly now.
Tested with dev on CS wiki.
| Before Fix | After Fix |
| ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/4e7068dd-8f03-42ec-93f0-6b5665e031bd) | ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/9ea81656-6b97-40fe-809a-de4a480c20cc) |

fix: `listGames` doesn't filter unlisted items

---

standard/medals_data.lua

Due to using `Module:Image` the `File:` prefix is not needed and causes red links instead of images

fix(medals): remove file prefix in data

---

stylesheets/commons/Colours.less
stylesheets/commons/Infobox.less

These are all defined using vars in [`Colours.less`](https://github.com/Liquipedia/Lua-Modules/blob/main/stylesheets/commons/Colours.less) so there should be no issue in removing them for either theme.
They're causing darkmode issues too currently.
When removed:

fix(infobox): drop non-themed infobox header colors

---

stylesheets/commons/Brackets.less

Support for Bruinen skin regressed in #4190 as we overlooked that the old skin is still in use.
Browser dev tools
| Bruinen | Lakesideview |
| ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/0707adbd-409b-4cf3-9902-c43441804a2d) | ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/c76ad3a2-533d-4340-a530-ffa7943c5fd0) |

fix(match2): regression in counterstrike bruinen support

---

stylesheets/commons/Miscellaneous.less

The icons are still in their original color on dark theme. 
Since they are png's the CSS filter invert changes them to white when dark theme is activated.
Devtools

fix(bigmatch): make icons white monochrome on dark theme

---

components/infobox/wikis/overwatch/infobox_league_custom.lua

as per request by ow contributors
- add storage for publishertier (it was already highlighted in infobox league, but not stored)
- add owwc as supported blizz tier
dev

feat(infobox): store overwatch publishertier

---

components/infobox/extensions/commons/infobox_extension_game_appearances.lua

This is part of #4177, as the module that's appeared locally are suggested to be made as proper Extension module instead
This is a port from `Module:GetGameAppearances` that appears in couple wikis, I renamed it to `GameAppearances` 
this module's intention is to be used on Infobox Player, where a list of Games the player had compete in that wiki can be displayed
https://liquipedia.net/simracing/Jarno_Opmeer
Since this is a local module turned into commons module, Help on Annotation and cleanup is surely needed because I can't get through one myself

feat(infobox_extensions): create automated game appearances for players

---

components/infobox/extensions/commons/metadata_generator.lua
spec/metadata_generator_spec.lua
spec/test_helper.lua

Module:Games is an old data module, being a subset of what's available in Module:Info (with help of Module:Game).
This is now this only non-AoE module using it.
After merge, remove https://liquipedia.net/commons/Module:Games (AoE has its own local version)
Only with busted

refactor: remove usage of deprecated `Module:Games`

---

components/match2/wikis/ageofempires/match_group_input_custom.lua

Fixes two issues with aoe match2:
- Faulty walkover handling for `walkover=2` (was W-FF for input 1, but L-W for input 2)
- Missing playerData in preview/without TC due to typo
via dev

fix(match2) AoE: walkover status, playerData

---

components/opponent/commons/opponent_display.lua
components/opponent/wikis/smash/opponent_custom.lua
components/opponent/wikis/smash/player_display_custom.lua
standard/info/wikis/smash/info.lua

Opponent Display for Smash, to support Participant Tables.
Dev

feat(opponent): support smash participant tables

---

components/participant_table/wikis/ageofempires/participant_table_custom.lua
stylesheets/commons/OpponentList.less

Adds a custom that supports toggeable display of seeding tables.
via dev, css classes via inspector/direct attribute setting
Before:
After:

feat(participantTable): Add AoE custom with support for seedings

---

components/participant_table/commons/participant_table_base.lua

Store dq indicator in participant table to be able to differentiate between participants that actually played in the event and e.g. participants who forfeited after being invited.
dev

feat(participantTable): store dq indicator

---

components/match2/commons/match_group_display_matchlist.lua
stylesheets/commons/Brackets.less

For draws, the `brkts-matchlist-slot-winner` was applied, but lead to weird display cause only parts were overridden by the `bg-draw` class.
via dev:
Before:
After:

fix(match2): prevent applying winner class for draws in MatchList

---

standard/info/wikis/rainbowsix/info.lua

Added darkmode version for the game icon: https://liquipedia.net/commons/File:Rainbow_Six_Siege_gameicon_darkmode.png
+in addition updated the name of the lightmode icon: https://liquipedia.net/commons/File:Rainbow_Six_Siege_gameicon_lightmode.png

added darkmode icon for R6+updated lightmode icon name

---

components/match_table/commons/match_table.lua

Range [0,1] to [0, 100] and remove the extra `1`
`102W : 147L (0.411) in matches and 225W : 287L (0.441) in games` to `102W : 147L (41%) in matches and 225W : 287L (44%) in games`
tested live, before weekly resync

fix(matchtable): Display stats scores

---

components/match2/wikis/apexlegends/match_summary.lua

If there are no status to ever show, we should always hide the column to save soem space
/dev

feat(match2): don't show status column for matches without statues

---

components/match2/wikis/apexlegends/match_group_input_custom.lua

Add support to manually tweak (setting fully manual was already possible) the point. This is for instance if a team reiceves bonus points (eg. starts with +10 points because of seed) or have a penety and as such starts with negative points.
/dev

feat(match2): manual bonus/subtract points on apex

---

components/opponent/wikis/smash/player_display_custom.lua

Large icons are 25x25px, which is too big for most use cases (including ParticipantTable). These are intended to be 18x18px, which is the default.
Change is live

Use small character icons for Smash

---

components/opponent/wikis/fighters/player_display_custom.lua

Large icons are 25x25px, which is too big for most use cases (including ParticipantTable). These are intended to be 18x18px, which is the default.
Change is live

Use small character icons for Fighters

---

stylesheets/commons/Colours.less

https://github.com/Liquipedia/Lua-Modules/pull/4180 Added a color for deceased players in the player portal and it doesn't seem to work very well. 
I just changed it to a darker hex code, not sure about the best way to do this tho
If anyone is able to test this for me it would be appreciated
https://liquipedia.net/rainbowsix/Portal:Players/Asia_Pacific#_Australia
N/A

fix(colours): add dark-theme appropriate gray background color

---

components/squad/wikis/overwatch/squad_custom.lua

`Number` inserted in the wrong place
This PR fixed it

fix(squad): header order on overwatch

---

components/squad/wikis/starcraft/squad_custom.lua

Currently squads on broodwar wiki error due to trying to insert into `self.children` which does not exist.
This PR fixes the key from `children` to `rows` so that squads work again on broodwar.

fix(squad): tlpd not working on broodwar

---

javascript/commons/FilterButtons.js

Due to a regression in #4040, filter buttons written to expect the previous javascript code (i.e., non-commons tournamentlists) would no longer have their default states respected.
Added intermediary const value which respects both old and new ways of setting default state. (Technically, if `buttonElement.dataset.filterDefault` is `false` but `filter-button--active` is present, then the false is ignored - not ideal, but that would only happen if someone incorrectly applied either the false value or the class.)
Pushed live on commons.

fix(filterButtons): default by class unintentionally ignored

---

components/infobox/extensions/wikis/warcraft/infobox_extension_building_unit_shared.lua

As requested on discord https://discord.com/channels/93055209017729024/268719633366777856/1234540830648172595
dev

fix(infobox): max damage calculation on warcraft's unit infobox is incorrect

---

javascript/commons/BattleRoyale.js

BR Match 2: (Desktop) sideways scrolling, when reaching the ends of the table (Both left/right) resuming to the vertical scroll
In this MR:
- Split function 'implementScrollWheelEvent' for readability. 
- Enable vertical scroll when horizontal scrolling within the table container is at the end (or start).
Closes [ticket](https://gitlab.com/teamliquid-dev/liquipedia/web/issue-bucket/-/issues/53)
Tested it first on my userspace, after that worked I added it to commons for everyone to use.

feat(match2): improve battle royale sideways scrolling on desktop 

---

standard/table.lua

Add `Table.deepMerge` function which is using `Table.deepMergeInto` but does not mutate first table
dev

feat(standard): Add `Table.deepMerge` function

---

components/hidden_data_box/wikis/brawlhalla/hidden_data_box_custom.lua

Simplify the phase logic (1 phase = 2h offset), by increasing the `num_missing_dates` counter directly. Each `num_missing_dates` is 1s offset.
https://github.com/Liquipedia/Lua-Modules/blob/7b611e80e3ff2c7d04e1c91ea5ac02dea59411dd/components/match2/commons/match_group_input.lua#L370-L372
Live

feat(hdb): simplify phase logic on brawlhalla

---

spec/game_spec.lua
standard/game.lua

Currently the default span is applied in the span wrapper in Module:Game and hence making manual size inputs bnasically invalid.
This PR changes it so that if size is applied default class is not applied.
As per discussion in Module Sync meeting.
testcases

feat(game): only apply default class to span if size is not supplied

---

components/match2/wikis/wildrift/match_group_input_custom.lua

So that the match2 works on SoloOpponent, previously it doesnt 
Which is a pretty urgent fix, as a tournament is ongoing by the time the PR exist (https://liquipedia.net/wildrift/Ionia_Cup/2024/1v1)

feat(match2): support solos on wild rift

---

components/prize_pool/commons/prize_pool_import.lua
components/prize_pool/commons/prize_pool_placement.lua
components/prize_pool/wikis/brawlhalla/prize_pool_custom.lua

Smash-likes need the last match id to have the option to fetch more detail about the lastvs match. 
This PR implements the auto retrieval of last matchId in Import, and handle both manual and auto imports in PPT.
/dev

feat(ppt): fetch and store id of last match on brawlhalla

---

components/match2/commons/match_group_input.lua

Add functions that are often repeated in match2 custom input processing to commons `Module:MatchGroup/Input`.
The idea is to extend #4118 and #4120 to also remove those duplicate code snipets and use the in this PR added commons functions instead if they are identical.
N/A, copied from R6 and not used anywhere as of now

refactor(match2): Add often used functions to commons

---

package.json

`grunt-stylelint@0.20.0` requires `stylelint@16.x`, but `stylelint-less@2.x.x` requires `stylelint@15.x`. This is causing a conflicting peer dependency.
(I did attempt to push us to `stylelint-less@3.x.x`, however, that causes stylelint plugin warnings that I don't know enough about to debug.)
Also added `jquery@3.6.1` (what we current have on the wikis) to add static analysis/IDE support for it in JS modules.
Tested locally:

ci: resolve `stylelint-less` version dependency mismatch

---

components/match2/wikis/ageofempires/get_match_group_copy_paste_wiki.lua
components/match2/wikis/ageofempires/match_group_input_custom.lua
components/match2/wikis/ageofempires/match_summary.lua

- Swapped order of parameters in generator (contributor request)
- Fix enabling of headtohead link from variable/infobox
- "Fix" display of team matches (still need to get player name overflow to work)
via dev
before:
after:

fix(match2): Various adjustments on AoE

---

components/match2/wikis/brawlhalla/match_summary.lua

Map name is not fully aligned, but rather depends on who won. This is because the checkmark is 16px while the filler is 14px. Increasing the filler to 16px.
Live

fix(match2): map names on brawlhalla are not centered

---

components/match2/wikis/brawlhalla/match_legacy.lua

In the match1 conversion, the character / heads list was not being made properly, as the source is game for this match level field.
Live

fix(match2): brawlhalla's char list in match1 is not working

---

components/match2/commons/match_group_input.lua
components/match2/wikis/clashofclans/match_group_input_custom.lua
components/match2/wikis/dota2/match_group_input_custom.lua
components/match2/wikis/smite/match_group_input_custom.lua

The old `placementCheckDraw` did return `true` in case of an empty Array of scores getting passed to it.
With #4120 & #4118 it started to return false in that case, resulting in errors on R6 wiki.
This PR changes the behaviour of `isDraw` to match that of the old `placementCheckDraw` again.
Longterm we probably should think about if we actually want it to return true in that edge case.
If not we also would have to adjust the `getResultTypeAndWinner` accordingly.
Additionally this PR adjusts 3 more wikis to use the `isDraw` function from commons.
dev into live

fix(match2): restore behaviour of `isDraw`

---

components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua

Makes the ticker darkmode compliant
via dev

feat(infobox): Use standard MatchTicker on LoL player pages

---

components/match2/wikis/apexlegends/brkts_wiki_specific.lua
components/match2/wikis/brawlhalla/brkts_wiki_specific.lua

Smash-likes don't want the match summary to show when it's only triggered by the existence of an approximate datetime
Live

feat(match2): don't show match summary for inexact datetime on brawlhalla

---

components/match2/commons/bracket_template.lua

`brkts-template-container` doesn't work for quite some time now.
This PR replaces its usage by just referencing to `Special:RunQuery/BracketCopyPaste` instead.
The Form has more options anyways and hence is **imo** preferable.
dev + [test page](https://liquipedia.net/starcraft2/User:Hjpalpha/wip31)

feat(match2): replace non working `brkts-template-container`

---

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua

* Fix Lua errors that appeared on https://liquipedia.net/starcraft2/World_Team_League/2024/Summer/Code_A#Results (discussed here: https://discord.com/channels/93055209017729024/213614988647071744/1237518343930515538)
* The fix is simply changing a lowercase 'o' to an uppercase 'O' three times.
I edited the module on Commons and tested that the Lua errors disappeared on the SC2 wiki page.

fix(match2): some faction issues on sc1&sc2

---

javascript/commons/FilterButtons.js

Adds the functionality for template expansion upon filter button change.
Usage:
`<div data-filter-expansion-template="TemplateName" data-filter-groups="group1,group2">Default content</div>`
will lead to wikitext of `{{TemplateName|group1=options|group2=options}}` where `options` is a comma-separated list of all active filters for that group. 
http://darkrai.wiki.tldev.eu/rocketleague/User:SyntacticSalt/Test (http://darkrai.wiki.tldev.eu/commons/MediaWiki:Common.js/FilterButtons.js)

feat(filterButtons): support template expansions

---

components/broadcast_talent_table/commons/broadcast_talent_table.lua

Currently cancelled or postponed tournaments show up in talent's achievements tables. Not ideal imo as cancelled tournaments were usually cancelled due to being scams or something else like that.
Tested on `/dev`
(notice `HCG Masters Season 1` missing now)

feat(broadcastsTable): skip cancelled tournaments in achievements

---

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
components/match2/wikis/warcraft/match_group_input_custom.lua
components/opponent/commons/starcraft_starcraft2/player_ext_starcraft.lua
components/opponent/wikis/warcraft/player_ext_custom.lua
components/participant_table/commons/starcraft_starcraft2/participant_table_starcraft.lua
components/standings/commons/standings_storage.lua
components/standings/commons/starcraft_starcraft2/standings_storage_starcraft_legacy.lua

- switch to using `faction` wiki vars instead of `race` wiki vars
- additionally it fixes a compatibility bug with HDB
- currently HDB only sets `faction` wiki vars while most modules still expect the `race` ones
- this PR switches all git components to use the `faction` ones instead and hence fixes the above mentioned issue
- clean up some (lua) variable names
(Non git modules & templates should by now be able to work with both vars, after this PR i will remove the support for the race one)
dev

refactor: switch to using `faction` wiki var instead of `race` wiki var

---

components/participant_table/commons/participant_table_base.lua
components/participant_table/commons/starcraft_starcraft2/participant_table_starcraft.lua

Currently ParticipantTable skips storage for entries that already have a placement on the page.
This PR changes this behaviour into merging the data from ParticipantTable into the one of the Placement it finds.
This PR is needed for another follow up PR for RLs Player/Ext/Custom
dev

feat(participantTable): merge instead of skip for `duplicate` placements

---

components/opponent/wikis/rocketleague/player_ext_custom.lua

it working #depends on #4247 but there is no harm in already merging it
Use placement data instead of obsolete datapoint in Rocketleagues `PlayerExtCustom.fetchTeamHistoryEntry` fucntion so it actually can fetch teams again.
Note: this means that RLs `PlayerExtCustom.fetchTeamHistoryEntry` is still only usable directly on pages with PrizePool/ParticipantTable and still only works for solo opponents and not for duo etc.
dev

fix: on rocketleague, automatically fetch team of players from participant table 

---

components/participant_table/commons/participant_table_base.lua

Fixes the objectName building for participant Table
Issue was introduced with #4247

fix(participantTable): objectName building

---

components/match2/wikis/callofduty/legacy/legacy_bracket_match_summary.lua
components/match2/wikis/callofduty/legacy/match_group_legacy_default.lua
components/match2/wikis/callofduty/legacy/match_maps_legacy.lua

Add Legacy Wrappers for Bracket and Matchlist to be able to bot convert match1 templates into storing match2 data
"live" + [test page](https://liquipedia.net/callofduty/User:Hesketh2/Legacy), not in use as of now

feat(match2): Legacy Wrappers for Call of Duty

---

stylesheets/commons/Bracket.less

Since Fortnite will have a chunk of Match1-brackets to be covered on wiki (for EWC), bracket width in the CSS are needed

feat: set match1 bracket width for Fortnite

---

stylesheets/commons/GroupTableLeague.less

Fix the button (and dropdown) padding in the match2 based GTL.
Due to a somewhat recent change to button styles (probably [this](https://discord.com/channels/321003439431745537/321641676579930112/1242837025430704152)) the padding applied by the `dropdown-box-button` / `dropdown-box` class gets overwritten.
This PR changes specificity on those classes so that they get applied properly again.
broswer dev tools

fix(GTL button): button padding in match2 based GTL

---

stylesheets/commons/OpponentList.less

Use equal padding for `.participantTable-entry`
Before and after example:
Inspect element

feat(participantTable): Use equal padding for `.participantTable-entry`

---

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua

Fix a key in SC(2) faction processing for duo oppnents in match2

fix(match2): SC(2) faction processing for duo oppnents

---

components/infobox/wikis/valorant/infobox_team_custom.lua

Putting Martin's fix into PR as suggested https://discord.com/channels/93055209017729024/268719633366777856/1246923785173467146
I did a quick check via Insource and didn't see any other usage
Martin did a fix live

fix(infobox): fix upcoming tournaments sometimes not working on Valorant

---

components/match2/wikis/leagueoflegends/big_match.lua

Currently in LoL BigMatch champion names from the ApiMap are not cleaned.
This results in errors for champions that were renamed.
This PR adds functionality to clean those champion names up to avoid the beforementioned errors.
reported by trev on discord: https://discord.com/channels/93055209017729024/372075546231832576/1246731149477417042
dev to live

fix(match2): on league of legends champion names from the Api are not normalized

---

components/infobox/wikis/dota2game/infobox_cosmetic_custom.lua

Media wiki's external links requires no spaces in the name. So was causing fault links.
Live

fix(infobox): dota2game's cosmetic infobox market link does not work for items without defindex while having space in the name

---

components/infobox/wikis/dota2game/infobox_cosmetic_custom.lua

When adding LPDB Data storage fothe cosmetic item, `setitems` were adding as an array. The template based version stored as CSV. 
Live

fix(infobox): dota2game's cosmetic automatic `setitems`

---

javascript/commons/BattleRoyale.js
javascript/commons/Bracket.js
javascript/commons/Collapse.js
javascript/commons/Commons_mainpage.js
javascript/commons/Commons_tools.js
javascript/commons/CopyToClipboard.js
javascript/commons/Countdown.js
javascript/commons/Crosstable.js
javascript/commons/FilterButtons.js
javascript/commons/Mainpage.js
javascript/commons/Miscellaneous.js
javascript/commons/Prizepooltable.js
javascript/commons/Selectall.js
javascript/commons/Tabs.js
package.json

Upstream eslint config `eslint-config-wikimedia` changed their configs in their 0.28 last night. https://github.com/wikimedia/eslint-config-wikimedia/releases/tag/v0.28.0
Arrow functions are now mandated after their release and I see no reason not to follow 
Also `stylelint-config-wikimedia` updated their configs in their release to [0.17](https://github.com/wikimedia/stylelint-config-wikimedia/releases/tag/v0.17.0) last night. That requires stylelint 16. I think all our dependencies now support stylelint 16, leaving that for later to upgrade.
Locally and pipeline

refactor: use arrow functions in js

---

.stylelintrc.json
package.json
stylesheets/commons/Brackets.less

All upstream dependencies now support stylelint v16, so no longer need to lock us to v15.
Locally and pipeline

ci: use stylelint 16

---

components/prize_pool/commons/prize_pool_import.lua

As per [discussion on discord](https://discord.com/channels/93055209017729024/874304000718172200/1246521662036250624) store the dateTime in placement data if importing from match2/standings tables.
Additionally this solves an inconsistency where atm on wikis that use lastvs oppnent data for group finishes where it already stoired the full untruncated date.
dev on sc2

feat(prizePool): Store dateTime from import

---

components/portal_players/wikis/fifa/portal_players_custom.lua
components/portal_players/wikis/smash/portal_players_custom.lua

Adds the gigas background to deceased persons, in line with https://github.com/Liquipedia/Lua-Modules/pull/4016
I'm leaving Formula 1 out of this PR since it only needs 3 colors
As a side note, I have added gigas to the description on each wikis player portal, similar to the other colors https://liquipedia.net/rainbowsix/Portal:Players/Europe
N/A

feat(portalPlayers): Add color for deceased on fifa and smash

---

stylesheets/commons/PanelBox/Heroes.less

Add the styling for the heroes section. The filters are left out for now as mentioned in the [ticket](https://gitlab.com/teamliquid-dev/liquipedia/web/extensions/teamliquidintegration/-/issues/134).
The hero rows are scaling based on the viewport width and they have a subtle hover effect.
On the live wiki: 
https://liquipedia.net/dota2game/User:Elysienna/Main_Page
Some autocompleting

feat: implement heroes section

---

components/hidden_data_box/commons/hidden_data_box.lua

Currently, match2 code looks for participants (teams) with capitalized first letters due to resolving redirects. HDB was not setting these properly and instead using direct passed data from LPDB (which comes from TT database).
`/dev`

fix(HDB): write capitalized participant variables

---

standard/links/commons/links.lua
standard/links/commons/links_priority_groups.lua
stylesheets/commons/Icons.less

Adds support for soop as infobox link.
Soop is the successor of afreecatv, but for some time they will run in parallel
N/A

feat(links): add soop support

---

components/series_medal_stats/series_medal_stats.lua

Due to the recent change in prize pool date storage from import (#4306) the end date condition in `Module:SeriesMedalStats` doesn't include the day of the end date anymore.
This PR adjusts the condition so that it includes the day of the end date again.
dev

fix(seriesMedalTables): fix endDate condition

---

components/infobox/wikis/mobilelegends/infobox_item_custom.lua

Removing duplicate 'cooldown reduction' parameter
via /dev

fix(infobox): remove duplicate `cooldown reduction` cell on mlbb

---

components/faction/wikis/stormgate/faction_data.lua
components/faction/wikis/stormgate/faction_icon_data.lua
stylesheets/commons/Faction.less

Add `Celestial` and `Neutral` as factions for Stormgate wiki.
(Celestial was announced officially and hence can be added now, also since we now know that c is taken for the faction we named neutral/creep as Neutral.)
live for data, browser dev tools for styles

feat(faction): add `Celestial` and `Neutral` as factions on stormgate

---

spec/locale_spec.lua
standard/locale.lua

Closes #4323 
Previously, input of `country=cn` or similar would lead to removed country from the output as it would get parsed as region.
via dev:

feat(locale): Allow single country regions

---

components/infobox/wikis/mobilelegends/infobox_item_custom.lua

- Adjust several parameters used in the infobox.
- Remove:
- Armor
- Evasion
- Magic Resistance
- Status Resistance
- Attack Damage
- Add:
- Hybrid Lifesteal
- Healing Effect
- Spell Vamp
- Physical Defense
- Magic Defense
- Adaptive Attack
- Critical Damage
- Slow Reduction
- Remove unused categories in `possibleCategories`
- Remove unused function: `function CustomItem._movementSpeedDisplay(caller, base)`
via /dev
https://liquipedia.net/mobilelegends/User:MatryoshX/Test_Page

feat(infobox): Adjust Infobox item for relevance to MLBB wiki

---

components/infobox/wikis/brawlstars/infobox_person_player_custom.lua

In addition, the plain category was added in both the custom as well as the base, removed that.
via dev:

fix(infobox): incorrect category naming on Brawl Stars's player infobox

---

components/infobox/wikis/rocketleague/infobox_league_custom.lua

In #4320 i forgot to parse the tier to a number which leads to currently no events having set publ tier as true.
This PR adds the `tonumber` to fix that.
dev to live

fix(infobox): publishertier not working

---

components/participant_table/commons/participant_table_base.lua
components/participant_table/commons/starcraft_starcraft2/participant_table_starcraft.lua
components/participant_table/wikis/stormgate/participant_table_custom.lua
components/prize_pool/commons/prize_pool_base.lua
components/prize_pool/commons/starcraft_starcraft2/prize_pool_award_starcraft.lua
components/prize_pool/commons/starcraft_starcraft2/prize_pool_starcraft.lua

Due to participant table now merging queried placement with the data inputted in the participant table we sometimes get stuck in lpdb loops.
PartTbl reads from lpdb and writes the exact same suff back to lpdb and hence overwrites changes the prize pool made to lpdb in the same page save again.
This PR changes the behaviour from reading from lpdb to instead passing along wiki variables from prize pool to participant table.
As per yesterdays Modules Sync Meeting this is the prefered solutionm over #4299 where the issue was just minimized while still reading from lpdb_placement instead of inheriting the wiki variable.
dev

fix(partTable): resolve LPDB loops

---

components/prize_pool/commons/prize_pool_base.lua

#4319 introduced an issue where the stringification failed due to "circular references".
Instead of copying existing tables, create new ones for every placement.
via dev, another fix is currently active on live

fix(prizepool): Do not reuse tables in placement data

---

components/prize_pool/wikis/ageofempires/prize_pool_custom.lua

Previously, tiertype was ignored in weight calculation.
While this is fine for most types, it leads to weird behavior with qualifiers:
The placement from a qualified team (place=1) gets a heigher weight than the actual result in the tournament.
dev

fix(prizepool): Honor tiertype on AoE in weight calculation

---

components/match2/wikis/worldoftanks/match_summary.lua
components/matches_schedule_display/commons/matches_schedule_display.lua
components/results_table/wikis/fortnite/results_table_custom.lua
standard/abbreviation.lua

Workaround found in https://github.com/LuaLS/lua-language-server/issues/2707#issuecomment-2163368205
It the empty string matching doesn't seem to be perfect, but it's quite good now and will only give false positives and no false negatives as far as I could tell (ie error slightly more than intended, but always on the safe side)
IDE Intellisense

docs(standard): improve abbrevation annotation

---

components/prize_pool/commons/prize_pool_placement.lua
components/prize_pool/wikis/fortnite/prize_pool_custom.lua
components/prize_pool/wikis/warcraft/prize_pool_custom.lua

Sometimes `lpdbData.players = lpdbData.opponentplayers` is used.
This PR changes it so that it now used Table.copy to create the (deprecated) players table isntead of referencing to the opponentpayers table.
This is so that the `Json.stringify` for the wiki variable that gest set does not break.

fix(prizePool): Do not reuse tables in placement data - part 2

---

javascript/commons/Countdown.js
javascript/commons/FilterButtons.js

When filter buttons are triggering DOM updates, some scripts need to be rerun to consider the new HTML content (for example: countdowns).
This sets a basic setup to rerun some JS scripts after a DOM update, with the countdown implementation.
Dev environment: http://killian.wiki.tldev.eu/rocketleague/MainPageTest

feat(FilterButtons): refresh countdowns after expansion

---

components/match2/wikis/rainbowsix/get_match_group_copy_paste_wiki.lua

Adds a bunch of new things to the Rainbow Six Copy/Paste generator
- Ability to add casters based off Bool (currently only supports 2 casters)
- Ability to add Match Pages based off a selection list (supports R6Esports, LPL, OPL, Challengermode, ESL, FACEIT)
- Separates the score parameters to either the match, or the maps themselves
- Adds MVP parameter based off Bool
Dev modules/templates/forms

feat(match2): add new options for Rainbow 6's Match2 Copy/Paste

---

components/match2/wikis/clashofclans/match_group_input_custom.lua

matches in Clash of Clans can ended it a tied score, but won through other factors (being the Total score count per map, or percentage if the former is also tied)
Previously an issue caused the `|winner=` to not be able to override the tied scores, effectively causing double winners, This is to fix that issue, need some code cleanup help here
(Note: CoC also used scores manually to displayed the total star count, but its unlikely I planned to rework the match2 to force the map1 scores to display over 1/0 due to i have no clue + editors dont want 1/0 on a BO1 either)
LIVE
World of Tanks also have the same issue, but it will be a separate PR

feat(match2): make winner override draws for CoC

---

standard/info/wikis/pokemon/info.lua

Decided to convert via bot, because most of the brackets had "r1m1p1" params.

feat: Update pokemon match2 status

---

components/infobox/wikis/brawlstars/infobox_person_player_custom.lua

Issue introduced in #4334, I've overlooked that `self.role2` is in fact an empty table by default instead of nil.
live

fix(infobox): brawlstars role check

---

components/match2/wikis/rainbowsix/match_group_input_custom.lua
components/match2/wikis/rainbowsix/match_summary.lua

Trying to get rid of [https://liquipedia.net/rainbowsix/Module:OperatorIcon](Module:OperatorIcon) in r6.
/dev

feat(match2): Use CharacterIcon in rainbow six

---

components/match_ticker/commons/match_ticker.lua

To filter matches by tournament tier and tier type, this module needs to be able to filter by tournaments. This adds both tier and tier type as possible parameters.
Dev environment: http://killian.wiki.tldev.eu/rocketleague/MainPageTest

feat(MatchTicker): add tier and tiertype filters

---

components/match2/wikis/warcraft/match_group_input_custom.lua

Fix the faction reading for players in Warcaft team matches

fix(match2): Warcraft factions in team matches

---

components/infobox/commons/infobox_map.lua

Adds display support for `creator3` in infobox map as per request from discord.
https://discord.com/channels/93055209017729024/268719633366777856/1246078773896544360
dev

feat(infobox): add support for more creators in infobox map

---

stylesheets/commons/FilterButtons.less

We want to implement a new design for the filter buttons, which will be tested with the new Dota2 Main page. This gives the new rules for the filter buttons which give the following outcome:
On my dev env: http://killian.wiki.tldev.eu/rocketleague/MainPageTest

feat(FilterButtons): Adding new filter styles

---

stylesheets/commons/FilterButtons.less

Somehow, `@media(hover...)` is not supported in less when embedded in other CSS rules. I should have caught it before but somehow I didn't see it. It broke my style on the dev env so quite a serious fix.
On my dev env: http://killian.wiki.tldev.eu/rocketleague/MainPageTest

fix(FilterButtons): Fixing hover CSS rules

---

stylesheets/commons/Banner.less

Add the styling for the dota2 mainpage banner.
https://liquipedia.net/dota2game/User:Elysienna/Main_Page
On the live wiki
https://gitlab.com/teamliquid-dev/liquipedia/web/extensions/teamliquidintegration/-/issues/131
https://gitlab.com/teamliquid-dev/liquipedia/web/extensions/teamliquidintegration/-/issues/130

feat: implement dota 2 banner header

---

stylesheets/commons/Banner.less

The current class name conflicts with a class name of the same name that already exists. 
This MR changes the banner class name to a more specific. It uses the modifier class `wiki-dota2game` from the body to add the specific background-image.
After merge the class names needs to be edited here: https://liquipedia.net/dota2game/User:Elysienna/Main_Page
[dev wiki ](http://laura.wiki.tldev.eu/rocketleague/User:Elysienna/Main_Page)

Change class name for banner

---

components/participant_table/commons/starcraft_starcraft2/participant_table_starcraft.lua

Inherit `isRandomEvent` from parent to section so it is enough to set it in the parent instead of in every child/section
live

feat(participantTable): Inherit `isRandomEvent` from parent on sc & sc2

---

components/infobox/wikis/ageofempires/infobox_person_player_custom.lua

Fetching new ratings is not possible for quite a while now due to API changes that need to be implemented in the extension.
Leaving the config commented out for easier enabling once https://gitlab.com/teamliquid-dev/liquipedia/web/issue-bucket/-/issues/64 is done.
dev

feat(Infobox): Remove outdated player ratings on AoE

---

components/infobox/wikis/stormgate/infobox_skill_custom.lua
components/infobox/wikis/stormgate/infobox_unit_custom.lua

Added storage and display of the introduction and deprecating patch/version for infobox unit and skill:
This allows auto removing these units from stats pages (e.g. https://liquipedia.net/stormgate/The_Human_Vanguard_Unit_Statistics).
For upgrades/abilities that are no longer present in game can be excluded from being displaying on e.g. unit pages (like https://liquipedia.net/stormgate/Vulcan) using Module:SkillCard via `{{CardList|dev=1}}`)
_Obviously that module needs to be updated after the pr is merged_
Added storage for unit veterancy in the infobox unit:
This allows  an automated overview on unit pages for the bonuses granted for each veterancy level:
Added storage for subfaction flags in the infobox unit:
Units might be part of 1v1, coop, 3v3 and or hero subfaction(s). Storing this …

feat(infobox): Update stormgate infoboxes unit and skill

---

javascript/commons/FilterButtons.js
stylesheets/commons/FilterButtons.less

Add ability to define groups that can hide themselves if all their filterable-item children are hidden. Also refactored some of the code to clean up jsdoc warnings and formatted the module documentation.
Currently we can get this scenario where you can empty out an entire section of filterable items and then you are left with an empty heading:
Tested on the dev wiki (http://darkrai.wiki.tldev.eu/rocketleague/Main_Page):
| With Ongoing Tournament(s) | Without Ongoing Tournament(s) |
| ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/eebfaa01-4614-4c9d-8932-97a698da4393) | ![image](https://github.com/Liquipedia/Lua-Modules/assets/5881994/23b81f44-68c1-432e-9dd1-b09e960e38b8) |

feat(filterButtons): add self-hiding groups

---

components/prize_pool/commons/prize_pool_import.lua

Adds the option to shift the imported placements by a given number of slots.
This can be used to add manual entries above the imported ones.
dev

feat(prizepool): Add option to shift imported placements

---

standard/links/commons/links.lua
standard/links/commons/links_priority_groups.lua

Adds support for `douyin_page`.
It is supposed to link to douyin user page. It needs to be available in addition to the douyin links that link to streams as both will get used on player/team pages.
requested by zeropochan on discord
dev

feat(links): add `douyin_page` support

---

components/squad/commons/squad_row.lua
components/squad/commons/squad_utils.lua

As the date is put into extradata during parsing, but wasn't read from there:
https://github.com/Liquipedia/Lua-Modules/blob/e5d02d4fac624a979586cbba1136ae0e61b8e82e/components/squad/commons/squad_utils.lua#L149
dev

fix(squad): newteamdate is not working

---

standard/countdown.lua

Countdown errored if the passed arguments had key value pairs where the key wasn't a string.
This PR accounts for such cases and filters the key value pairs with non string key away.
dev

fix(countdown): error on integer keys

---

components/match2/wikis/fighters/match_summary.lua

feat(match2): improve fighters match summary alignment

---

standard/links_stream.lua

When a table with non string keys was passed to `StreamLinks.processStreams` it errored due to a missing type check.
This PR adds the type check and adjusts the annotations accordingly.
dev

fix(countdown): error on non string keys

---

components/match2/wikis/fighters/match_summary.lua

Create a different display style for 2+ for a side
/dev

feat(match2): create multicharacter styleing

---

components/match2/wikis/fighters/match_legacy.lua

Smash-likes uses some core fields different in their match1 implementation. Adjust those in the legacy as well.
They also do the same for PPT, but there we add consumer side handling instead, as that should be standardized (while there is no official standard for match1).
Live

feat(match2): adjust fighter's match1 fields

---

components/match2/wikis/fighters/match_group_input_custom.lua

Generally on fighters, when grabbing data from non-streams, the map that was played is not know. The data is also not shown.
This PR makes it optional to enter the map name
Live

feat(match2): allow for empty map names on fighters

---

components/infobox/wikis/fighters/infobox_league_custom.lua
components/prize_pool/commons/prize_pool_base.lua
components/prize_pool/wikis/fighters/prize_pool_custom.lua

Store tournament level extradata from prizepool on fighters, similar to CS. Here we are storing winner and runner up data
Live

feat(prizepool): store tournament data on fighters

---

components/opponent/wikis/fighters/player_display_custom.lua

Extra div causes no padding to be added after the characters, which was unintended
Devtools -> Live

fix(opponent): missing padding between name and characters on fighters

---

components/match2/wikis/heroes/match_summary.lua

Iterate bans using match.games, this allows to display bans even if game 1 has no bans.
Add game length display.
/dev

fix(match2): Handle display of games with no bans and length on heroes

---

standard/links_stream.lua

Before the stream changes away from JavaScript doing more of the work, we had twitch and youtube ordered first as the most common platforms. Now we are back to alphabetical order:
Moved twitch, youtube, and kick to be first as the current "go-to" english platforms and moved TL stream to the end as basically legacy item.

feat(streams): re-order streams based on previous priority

---

components/infobox/commons/infobox_league.lua
components/infobox/wikis/fighters/infobox_league_custom.lua
components/infobox/wikis/smash/infobox_league_custom.lua
components/infobox/wikis/starcraft2/infobox_league_custom.lua
components/infobox/wikis/worldoftanks/infobox_league_custom.lua

Refactored infobox league's prizepool setup to make it static instead, allowing it to be used for double prize pools as well.
Smash is based on what's [currently live](https://liquipedia.net/smash/index.php?title=Module:Infobox/League/Custom&action=edit) but untracked, changed to bring it up to date with the infobox refactor that happened earlier this year
/dev by me and spazer

feat(infobox): infobox league for smash

---

components/infobox/commons/infobox_league.lua
components/infobox/wikis/fighters/infobox_league_custom.lua
components/infobox/wikis/smash/infobox_league_custom.lua
components/infobox/wikis/starcraft2/infobox_league_custom.lua

Introduced in #4425, USD-only prizepools broke on fighters and SC2. Caused by insufficient testing
Live

fix(infobox): usd broken on fighters and sc2

---

components/match2/wikis/leagueoflegends/match_group_input_custom.lua

Currently on LOL match processes resulttype etc wrongly if it isn't a standalone match.
This PR changes the order of processing so that the merge happens before the opponent processing and hence before the resulttype processing
dev

fix(match2): wrong processing if not standalone

---

components/match2/wikis/leagueoflegends/match_group_input_custom.lua

due to only testing in userspace and hence having to provide matchId and BracketId anyways it wasn't noticed in #4390 that those could be nil on bigmatch pages when trying to concat them.
This PR adds the necessary nil checks so that the concat nil error doesn't occour.
dev + testing it on a page in main space

fix(match2): error sometimes on bigmatch on lol

---

components/ratings/ratings_display.lua
components/ratings/ratings_display_graph.lua
components/ratings/ratings_display_list.lua
components/ratings/ratings_storage_lpdb.lua

Refactoring Ratings Display to make future things easier to implement.
dev
Before:
After:

refactor(ratings): decouple ratings display

---

components/match2/wikis/apexlegends/match_group_input_custom.lua
components/match2/wikis/apexlegends/match_summary.lua

Currently the bg and icon of the "status" column will only show up once the match is finished. 
This PR changes it so the icon will always show up, while the bg will only be there when it's finished.
/dev

feat(match2): remove finished check on apex for bg

---

stylesheets/commons/Mainpage.less

Less wrongly compiled the calc values, applied a fix as per https://stackoverflow.com/questions/11972084/how-to-prevent-less-from-trying-to-compile-css-calc-properties
live

fix(matchticker): less compilation doing badly with calc

---

components/match2/wikis/apexlegends/match_group_input_custom.lua
components/match2/wikis/apexlegends/match_summary.lua

Entering `-` as placement will mark the team with no placement, and display it as such as well 
Match Tab:
Game Tab:
dev

feat(match2): support "DNP" style placements on apex

---

components/opponent/wikis/stormgate/opponent_custom.lua

`Opponent.resolve` should retrieve the faction and only not apply it if it isn't default faction AND not set already.
The current condition makes it so that if either of the above conditions is fulfilled it is not applied.
This PR fixes that behaviour by switching the `and` to an `or`.
dev into live

fix(opponent): stormgate's faction sync

---

stylesheets/commons/Mainpage.less

Same issue as on #4435 but this time it's just nuking the left calc and only using 185px hardcoded 🫠
live

fix(matchticker): less compilation doing badly with min

---

components/match2/wikis/smite/match_group_input_custom.lua
components/match2/wikis/smite/match_summary.lua

Adds match pages to Smite's Match2 setup. Specifically adding the SmiteEsports (Publisher) pages. 
Tested live with dev modules

feat(match2): Add Links to Smite

---

stylesheets/commons/Fountain.less

feat(fountain.less): Adding grayscale filter to Portal:Heroes to display update status
- Previously Rathoz had to make a Google Sheet to keep track of Hero pages that are up to date.
- Someone on Discord suggested a VersionControl message to be displayed on each hero's page for clarity.
- Why not utilize /dota2/Portal:Heroes to reflect the VersionControl message stored in LPDB?
Additionally:
- Updating/cleaning up some notes within the stylesheet, and grouping up certain styles.
- Removing certain lines unused.
Applying a `filter: grayscale (x%)` with Stylus on Firefox.

feat: On dota2game, add color indicator for out of date

---

javascript/commons/Countdown.js
javascript/commons/FilterButtons.js
javascript/commons/SwitchButtons.js

This MR has 2 purposes:
- Fix the value parsing for the countdown refresh on the toggle (data was wrongly passed)
- Extend the JS refresh on dynamic template expansion to re-init switch buttons
To note: I wanted to add the refresh of _data-toggle-area_ as well but couldn't figure out where the js logic is.
In console in [this page](https://liquipedia.net/dota2/User:Nadox/Dota2MainPage2)

fix(Countdown): toggle data parsing & extended filter button refresh

---

stylesheets/commons/Fountain.less

FacetCard desc1/desc2 needs padding-top for readability.
Stylus plugin on Firefox.
- Regrouping other styles accordingly.
- Removed the unnecessary `box-sizing: border-box;` as suggested.
- Added black `.vercheck_` for the grayscale filter to work temporarily, since hero pages are still under construction.

 feat(fountain.less): Adding padding to FacetCard for better readability

---

components/match2/wikis/dota2/big_match_template.lua
stylesheets/commons/BigMatch.less

As discussed:
- prevent media wiki from creating additional p tags
- change flex basis

fix(match2): improve style on dota2's matchpage footer 

---

components/match2/commons/match_group_util.lua

Patch information is not being kept when parsing a record. This PR makes it so it's kept if set.
/dev

fix(match2): missing patch information on lol match pages

---

components/match2/wikis/leagueoflegends/match_group_input_custom_match_page.lua

When using manual input on a match page page, `championVeto` would be nil and error in the iterator. 
Live

fix(match2): error when mixing input modes on lol match pages

---

stylesheets/commons/Fountain.less

- The `Template:$craft` will be used more often moving forward. Moving the styles from that template into the stylesheet would be a better practice.
- Certain design elements are not moved yet because I'm unsure if it is necessary to have them.
- Portal:Heroes grayscale is set to 90%. Lower levels of grayscale are inconvenient for colorblind users.
Thank you!
Stylus on Firefox.
Still getting the linter plugin to work on my computer. Apologies in advance for any linter issues.

 feat: styles for template:$craft 

---

components/infobox/wikis/starcraft/infobox_map_custom.lua

All tileset categories are empty on the StarCraft: Brood War wiki: https://liquipedia.net/starcraft/Category:Tilesets
For example, https://liquipedia.net/starcraft/Category:Jungle_World_Tileset should include https://liquipedia.net/starcraft/Python
I edited https://liquipedia.net/starcraft/Module:Infobox/Map/Custom/dev and previewed the page https://liquipedia.net/starcraft/Python with `|dev=1` to check that the category "Jungle World Tileset" was added.

feat: Add the tileset category to infobox map for starcraft

---

components/match2/wikis/leagueoflegends/match_group_input_custom.lua

Due to typo, the normalization of characters was not done
/dev

fix(match2): league of legend's vetophase character name normalization

---

components/match2/wikis/leagueoflegends/match_group_input_custom_match_page.lua

Heroes should always be in role order, so let's sort them from the start instead
/dev

fix(match2): league of legends hero pick order

---

stylesheets/commons/Banner.less

This aligns the border-radius of the main page header with the border radius of the nav pills
https://gitlab.com/teamliquid-dev/liquipedia/web/issue-bucket/-/issues/86
Dev tools

fix: border radius for the new dota2 wikis main page header

---

components/match2/wikis/valorant/match_group_input_custom.lua

It's impossible to query for player/agent inside match2games.participants so we need to move the data we want to query to extradata.
In the future we expect to have the possibilty to query match2games.participants.
/dev and [sandbox](https://liquipedia.net/valorant/User:LuckeLucky/sandbox/2)

feat(match2): store player and agent info on valorant

---

standard/links_stream.lua

To match the names of the special pages we have to normalize the platform before passing it to building the special page or resolving the stream.
Reported on discord: https://discord.com/channels/93055209017729024/372075546231832576/1269537138504892477
dev

fix(countdown): resolve platforms to special pages

---

standard/links_stream.lua

This fixes a typo. The function was only just created in https://github.com/Liquipedia/Lua-Modules/commit/0164a5a046d446dd1cbb2eb3f92844be7e740192 so I don't think there's any external users as of right now
I did not

feat(countdown): Fix a typo in a function name in Module:Links/Stream

---

components/notability/wikis/trackmania/notability_checker_config.lua

New notability checker:
- Weekly tournaments won't count any point
- New point system for tier-4 tournaments as I showed on the screenshot above
- Multiplied everything by 4 so there would be no fractional numbers
Discussion and voting can be found in #trackmania
Tested by me and V3n0M on https://liquipedia.net/trackmania/Special:RunQuery/SobakaPirat/Notability_Checker

feat: update trackmania notabilty calculations for 2024

---

components/match2/commons/match_group_util.lua

Only impacts Apex of things that are live. The <, > was mixed up for time
/dev

fix(match2): ongoing and upcoming swapped in certain cases

---

components/match2/wikis/osu/get_match_group_copy_paste_wiki.lua

If Protect field is set to true, on a bracket that contains one more match, every subsequent match adds a duped `protect` type and extra `tXmap` which stacks the longer the bracket goes
this PR is fixing that, so protect should always just appear only once, as first type and only a single extra set of tXmap is added
LIVE

fix(match2): Dupe types in Osu match copypaste

---

stylesheets/commons/NavigationCard.less

The specificity of the navigation card link colors is not high enough, so I made it `!important`
dev tools

fix: color of navigation card links

---

components/infobox/wikis/hearthstone/infobox_league_custom.lua

We already have Standard, Wild and Battlegrounds, these are 2 additional - Arena and Duels. 
There are tournaments played in Arena (last was a couple of days ago), were Duels events.
If this pull request will be merged, we can have pages about this modes with dynamic event list.
Tested in userspace - https://liquipedia.net/hearthstone/User:Nikita_r28/Solary_Lich 
This pull request will not break anything

feat(infobox): add 2 game modes for Hearthstone

---

components/match2/commons/get_match_group_copy_paste.lua
components/match2/commons/match_group_display_helper.lua
components/match_ticker/commons/match_ticker_display_components.lua
standard/i18n_data.lua

As LH wants us not use to `mw.messages`, moving the i18n to lua from the extension.
/dev

feat(match2): use i18n over mw.messages for bracket headers

---

stylesheets/commons/Panels.less

The original class wasn't always available, so I added a new class for this purpose.
dev tools

fix: use different class to target collapsible panel body content

---

components/match2/wikis/ageofempires/match_group_input_custom.lua

Matches were marked as finished if a certain time has passed since their dates.
This lead to all matches without a known date yet to be marked as finished.
dev

fix(match2) Prevent matches with default date to be automatically marked as finished

---

standard/info/wikis/geoguessr/info.lua

GeoGuessr is a newly installed wiki
LIVE
Infobox and Match2 will come shortly soon after, to set some expectation 
- Match2 will be using Team Fortress's setup aka #4333 with TF2's local links gone, which is currently in-PR, as everything matches what GeoGuessr need. 
- Infobox league will had some customization, player is always needed but there won't be one for team [team will be fine with base]
Labels are also created

feat(info): add GeoGuessr

---

components/tournaments_list/filter_buttons.lua
stylesheets/commons/FilterButtons.less

We want to have the filter buttons being left aligned on [this page](https://liquipedia.net/dota2/User:FO-nTTaX/Sandbox/23). To do so, this adds a field that is configurable from the config to use additional CSS rules in the filter buttons.
On my dev env: http://killian.wiki.tldev.eu/rocketleague/Dota2MainPageSandbox

feat(FilterButtons): filter buttons alignment

---

components/match2/commons/get_match_group_copy_paste_wiki_base.lua

Adds support for duo, trio and quad opponents to match2 copy-paste
dev

feat(match2): add support for duo, trio, quad in copy paste

---

components/match_ticker/commons/match_ticker_display_components_new.lua
stylesheets/commons/MatchTicker.less

Due to the new style, all info does not fit in the match ticker. As a result, we decided to put the date/countdown into a new row to make the information more visible.
Results:
On my [dev env](http://killian.wiki.tldev.eu/rocketleague/Dota2MainPageSandbox)

feat(MatchTicker): move date and countdown to a new row in new style

---

components/match2/commons/display_util.lua

Looks like since #3530, this function is unused

refactor(match2): remove unused function

---

components/match2/wikis/dota2/match_page_template.lua
stylesheets/commons/BigMatch.less

This PR is for updating the player stats section for various screen resolutions:
On the live wiki: https://liquipedia.net/dota2/Liquipedia:ID_XLA7bhOs3l_R01-M001

feat(match2): styling and structure dota2 match page player stats

---

components/match_ticker/commons/match_ticker_display_components_new.lua
javascript/commons/Countdown.js
standard/countdown.lua

We want to show a COMPLETED pill for the new style of the match ticker. To do so without affecting all countdowns, this adds a flag to indicate to add this pill.
Results:
On my [dev env](http://killian.wiki.tldev.eu/rocketleague/Dota2MainPageSandbox)

feat(countdown): display `completed` for completed matches in new style

---

standard/links/commons/links.lua
standard/links/wikis/stormgate/links_custom_data.lua
stylesheets/commons/Icons.less

- sgworld is basically dead, hence remove it
- add untapped support for stormgate
- untapped technically has support for several games (from what i see we do not have them as wikis though), they have game specific subdomains, hence push it into the sg custom
- alphab sorting in `Icons.less`
the newly added module live (can't use dev due to the module not existing yet), moved it to dev afterwards

feat(links): Add Untapped for stormgate and remove sgworld

---

javascript/commons/FilterButtons.js

The `refreshScriptsAfterContentUpdate` method was called only in some scenarios while it should be triggered after every update (even on init). It caused issues on the [new main page](https://liquipedia.net/dota2/User:FO-nTTaX/Sandbox/23) when the filters were the default ones.
This moves the call of the `refreshScriptsAfterContentUpdate` method on performUpdate.
Directly on the console.

fix(FilterButton): issues with default filters

---

components/infobox/extensions/wikis/stormgate/infobox_extension_cost_display.lua
components/infobox/wikis/stormgate/infobox_building_custom.lua
components/infobox/wikis/stormgate/infobox_skill_custom.lua
components/infobox/wikis/stormgate/infobox_unit_custom.lua

Changes due to Stormgate EA release (Griffin patch)
- Replace `|veterancybonusattackspeed=` with `|veterancyspecialbonus=` in `infobox_unit_custom`
- Add `|power=` to `infobox_building_custom` and `infobox_skill_custom`
- Add `|charge_time=` to `infobox_skill_custom`
- Add `|deprecated=` to `infobox_building_custom`
...and some follow-up changes in the appearance of the infoboxes. 
dev tools

feat(infobox): Update Unit, Building and Skill Infoboxes for Stormgate (Griffin patch)

---

components/match2/wikis/arenaofvalor/match_summary.lua

As reported on discord: https://discord.com/channels/93055209017729024/268719633366777856/1271440466214129746
When a game has no ban information entered, subsequent games would not have their bans shown.
dev on https://liquipedia.net/arenaofvalor/User:Lolliftw/Sandbox/3
before:
after:

fix(match2): on AoV bans are not shown unless previous game(s) have a bans

---

components/match2/commons/display_util.lua
components/match2/commons/match_group_input.lua
components/opponent/commons/player_ext_custom.lua
standard/error.lua
standard/error_display.lua
standard/error_ext.lua
standard/feature_flag.lua
standard/logic.lua
standard/result_or_error.lua

Re-imagining of  #623 (https://github.com/Liquipedia/Lua-Modules/pull/623/commits/125aa9121e501d34c892c204570cc04a2dd5a8e6)
Renames: 
* Class `Result` was renamed `RoEResult`
* Class `Error` was renamed `RoEError`
* Class `error` was renamed `Error`
Changes:
* `ResultOrError.try` should always be called from `Logic.try` or other `Logic` functions
* `RoEError` is now a container for `Error`, instead of string container (RoEError.error changed from string to Error type)
* `Error` now takes care of the stack, instead of `RoEError`
* For `:catch(f(x))` , `x` will now be of type `Error` instead of string
dev with forced error

refactor(standard): error handling

---

components/infobox/wikis/overwatch/infobox_person_player_custom.lua

Team.page would error if the team was nil, as reported on discord https://discord.com/channels/93055209017729024/268719633366777856/1272900297647456297
Issue introduced in #4484 
live

fix(infobox): do not error when player has team1 but not team2

---

components/match_ticker/commons/match_ticker.lua

When the page would be rendered in the exact minute a game starts, it would disappear from the matchticker as all conditions would be LT or GT NOW, but not EQ.
Noticed on valorant, where the bot conversion runs on :00 and therefore often triggered this: https://discord.com/channels/93055209017729024/372075546231832576/1273192019497451561
dev

fix(matchticker): matches starting same minute as render are not shown

---

components/infobox/wikis/overwatch/infobox_league_custom.lua

Overwatch does not have different map pages for OW1 and OW2, this removes the [[Map/game]] format; copied from apex
dev

fix(infobox): remove overwatch game-specific map links

---

javascript/commons/FilterButtons.js

Quick fix to avoid having broken countdown on pages with filter buttons. This only recalls the countdown when the content from the filter buttons is repopulated. It doesn't solve the core issue but it is a fix that works for divs that have their DOM updated, as tested on: 
- https://liquipedia.net/dota2/Main_Page
- https://liquipedia.net/dota2/User:FO-nTTaX/Sandbox/23
By testing it on prod on:
- https://liquipedia.net/dota2/Main_Page
- https://liquipedia.net/dota2/User:FO-nTTaX/Sandbox/23

fix(countdown): Remove countdown init call on all update

---

javascript/commons/FilterButtons.js

For the new [main page design](https://liquipedia.net/dota2/User:FO-nTTaX/Sandbox/23) we want to display tournaments and matches that don't have their respective category in the filter groups. The reason is that right now, for tournaments without tier types an empty and hidden button is required (like currently done in https://liquipedia.net/dota2/Main_Page).
This is checking if there is a filter state, if not then it just shows the element by default.
On the console with @FO-nTTaX for [this page](https://liquipedia.net/dota2/User:FO-nTTaX/Sandbox/23)

feat(FilterButtons): show filter elements if filter state doesn't exist

---

components/match2/wikis/dota2/match_page_template.lua
stylesheets/commons/BigMatch.less

This sets the picks and bans section for the Dota2 match page with the following result:
Desktop:
Mobile:
On [this page](https://liquipedia.net/dota2/Liquipedia:ID_XLA7bhOs3l_R01-M001)

feat(match2): dota2 match page picks and bans

---

components/match2/wikis/dota2/match_page_template.lua
stylesheets/commons/BigMatch.less

Add the team stats section. Only missing is the team name that should work with `{{winnerName}}`
[Here](https://liquipedia.net/dota2/Liquipedia:ID_XLA7bhOs3l_R01-M001)

feat(match2): dota2 match page team stats section

---

components/match2/wikis/dota2/match_page_template.lua

Add SAP logo to the header
https://liquipedia.net/dota2/Liquipedia:ID_XLA7bhOs3l_R01-M001

feat(match2): add SAP logo to template Dota2 match page

---

stylesheets/commons/BigMatch.less

Make the avatar images look a bit better with the correct aspect ratio.
https://liquipedia.net/dota2/Liquipedia:ID_XLA7bhOs3l_R01-M001

feat(match2): fix aspect ratio of hero avatars on dota2 matchpages

---

components/match2/commons/display_util.lua
components/match2/commons/match.lua
standard/error_display.lua
standard/lua.lua

With this change, an error Match/Legacy will not have a cascading effect to affect all of match2, rest of the match is still stored and displayed
dev

feat(match2): handle match/legacy errors

---

components/match2/commons/match_group_util.lua
components/match2/wikis/dota2/match_group_input_custom_match_page.lua
components/match2/wikis/dota2/match_page.lua

Add winnerName proper to the VM.
Also fix a typo in the parsing
Some refactoring
dev

feat(match2): on dota2 match pages add winnerName prop

---

components/match2/commons/starcraft_starcraft2/get_match_group_copy_paste_starcraft.lua
components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua

Currently sc/sc2 has its own casters input processing and display.
This PR normalizes it to use the commons funcctions instead.
Due to bot conversion runs being needed i pushed an intermediate version live that currently supports both input variants.
A bot run is under way to change the old inputs to the new pattern.
Once that bot run is finished this PR can be merged.

feat(match2): normalize caster input and display on sc/sc2

---

components/match2/commons/match.lua
components/match2/commons/match_group_input.lua

Introduced in #4511, opponent extradata was always set to an empty table if not otherwise created, which leads to bad serialization in LPDB (json array instead of object).
Reported on discord: https://discord.com/channels/93055209017729024/443856413052239882/1273905924775346198
tbd

fix(match2): opponent extradata is empty array instead of null

---

components/infobox/commons/infobox_company.lua

Allows to query the awarded prizepool for an organizer by `Title::baseText` instead of pagename.
Since on AoE most organizers are individuals and infobox player is preferred for the main page, the module is solely used on subpages `<Name>/Tournaments` (e.g. https://liquipedia.net/ageofempires/MembTV/Tournaments), which means the querying fails.
Adding a parameter to query by the baseText instead.
dev

feat(infobox) Allow querying organizer prizepool by Title::baseText

---

components/match2/wikis/arenaofvalor/match_summary.lua

resolves #4558 
On aov (game) comments in a match overflow/are cut off.
This PR gives the comment div a width of 100% top fix this issue
current:
dev:

fix(match2): aov comments cut off

---

components/match2/wikis/ageofempires/match_group_input_custom.lua

The change from #4263 would lead to a hard error, preventing display of the entire bracket in case of a missing team template.
This prevents the immediate error and instead will result in the usual "Missing team template for ..." error inside the specific match.
live

fix(match2): AoE: Prevent hard error on missing team template

---

components/match2/commons/match_group.lua
components/match2/commons/match_group_base.lua

These functions have been deprecated from a long time. They seem to have no usage
They are unused based on the fact that the categories are never set
https://tools.liquipedia.space/?view=pagesfordeletion&category=Pages_using_deprecated_Match_Group_functions

refactor(match2): remove unused deprecated functions

---

components/match2/wikis/ageofempires/match_group_input_custom.lua

Per title: Matches with no time entered (yet) would resolve team templates with the default date, using wrong logos and names for historical TTs.
bugfix, live

fix(match2): AoE: Do not use default timestamp to resolve team templates

---

components/match2/wikis/dota2/match_page_template.lua
stylesheets/commons/BigMatch.less

This PR updates the facets and changes the icon size of the items (thanks to SyntacticSalt)
Live site

feat(match2): add facets and increase item render size on dota2 match pags

---

components/match2/commons/match_group_input.lua

`hasSpecialStatus` currently returns true if any of the opponnents has an unset status.
This (among other things) causes the finiuched checks in the refactors to always return true if no manual input is given.
This PR adds a nil check on the status check in `hasSpecialStatus`.
dev

fix(match2): unset status causing `hasSpecialStatus` to be true

---

components/match2/commons/match_group_display_helper.lua
components/match2/commons/match_group_util.lua
components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
components/match2/wikis/ageofempires/match_legacy.lua
components/match2/wikis/brawlhalla/match_legacy.lua
components/match2/wikis/fighters/match_legacy.lua

Currently several wikis store walkovers uppercased, while they should be lower cased.
This PR adjusts the consumers on the repo in a way that they can handle both upper and lower case so we can fix the storage with the refactors.
dev

fix(match2): prep walkover consumers for walkover value fix

---

components/match2/wikis/rainbowsix/match_group_input_custom.lua

A missing `not` made the condition incorrect
Tested with /dev on valorant

fix(match2): mapscore started auto calcing too early on R6

---

standard/lua.lua

A new and different category for caught lua errors in userspace
/dev

feat(standard): set a different category for userspace errors

---

components/infobox/commons/infobox_building.lua
components/infobox/wikis/stormgate/infobox_building_custom.lua
components/infobox/wikis/stormgate/infobox_unit_custom.lua

- Add support for Creep Camps to `Module:Infobox:Building/Custom`
- Add bounties for luminite and therium to `Module:Infobox:Unit/Custom` storage (for creep units)
Example:
dev tools

feat(infobox): add creep camp support in stormgate infobox building

---

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua

fix(match2): pass wrong var to `canUseAutoScore`

---

components/match2/wikis/rocketleague/match_group_input_custom.lua

Rocket League maps are assumed to be completed once scores are entered, unless finished is explicitly set to false.
Preview in dev

feat(match2): entering map-score on rocketleague should finish the map, unless `|finished=false`

---

components/match2/commons/match_group_display_helper.lua
components/match2/wikis/overwatch/match_summary.lua
components/match2/wikis/rainbowsix/match_summary.lua

Currently on R6 and OW, default resultTypes are displaying the score as `-1`. This will change it to show `W` and walkoverType (often `L`)
/dev

feat(match2): improve map score display on R6 and OW

---

stylesheets/commons/BigMatch.less

This PR removes the specific width and heights on the team logo's.
devtools

fix(match2): dota2 matchpage team logo stretching 

---

components/match2/wikis/valorant/match_group_input_custom.lua

Fixes typo
Reported by GodOfPog https://discord.com/channels/93055209017729024/372075546231832576/1276022319734849609
did live patch

fix(match2): `acs` misspelled as `asc`

---

components/match2/wikis/starcraft/legacy/match_group_legacy_default.lua
components/match2/wikis/starcraft2/legacy/match_group_legacy_default.lua

improves the pattern matching used for that winners bracket advantage stuff in legacy mapping on sc(2)
live

feat(match2): on sc&sc2, improve the pattern matching for winners bracket advantage

---

components/match2/wikis/callofduty/match_group_input_custom.lua

This two was replaced by GOL and Factor (which is for the LoL wiki) following the refactor changes, This is to brought back the accidentally replaced ones
(Pic is pre-refactoring)
LIVE

fix(match2): missing links for COD

---

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua

Remove the temp. workarounds form sc(2) MatchInput processing after the need for them has been resolved by bot jobs.
N/A

feat(match2): remove temp workarounds on sc(2) MGI

---

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua

if participants was empty it did not calculate any numbers leading to en empty map mode which then got overwritten by `MatchGroupInput._applyTournamentVarsToMaps` with the mode of the match, leading to a display bug
This PR adjusts it so that we assume we have 2 oppoennts if no participants data is found and sets the mode accordingly to `literalvliteral` as it was intended.
dev to live

fix(match2): uncalculated mode for games with missing opponents
