- match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Changes to `Module:MatchGroup/Input/StarCraft` on Commons:
* Add Icon retrieval so it can be stored in match2opponent
* Improve retrieval of Team link/page for storage in the `name` field in match2opponent
> Add icon retrieval for storage during match processing

- match2/wikis/starcraft/match_legacy.lua
- match2/wikis/starcraft2/match_legacy.lua
opponent1/2 in match record is not always populated, for instance if they were marked as TBD
> Add TBD checks in starcraft/starcraft2 save to smw

- match2/commons/match_group_display_bracket.lua
- match2/commons/match_group_display_matchlist.lua
- match2/commons/starcraft_starcraft2/player_display_starcraft.lua
- match2/commons/starcraft_starcraft2/player_util_starcraft.lua
- Changed `StarcraftPlayerUtil.syncPlayer` to modify the player struct in place
- Make use of recently added `StarcraftTournamentUtil.getContextualDate` and `StarcraftTournamentUtil.getContextualDateOrNow` for retrieving the end date set by infobox tournament.
> Minor improvements to StarcraftPlayerUtil

- match2/commons/display_util.lua
Disables the runtime type checking outside of /dev. Reduces the Lua runtime on large pages by about 3%. Added an additional dev flag `DevFlags.forceTypeCheck` that can be used to turn on type checking.
> Disable type checking in non-/dev

- match2/commons/player_display.lua
- match2/commons/starcraft_starcraft2/player_display_starcraft.lua
- match2/commons/starcraft_starcraft2/player_util_starcraft.lua
- Remove white-space pre from InlinePlayer. It's not needed because InlinePlayer already sets `&nbsp;` between race and flag and player name. If the player name has a space, then it's long enough to deserve line breaks anyway.
- For `TemplatePlayer` in `starcraft/starcraft2`: Read the frame object from args instead of `mw.getCurrentFrame()` so it can be used as a drop in replacement for `require('Module:Player').player`. Example: https://liquipedia.net/starcraft2/index.php?title=Module:Portal_tournaments&action=edit
> Minor improvements to PlayerDisplay

- match2/commons/match_group_base.lua
Following the discussion in the bracket-update channel these changes would make iMarbot and Rathoz happy.
--> https://discord.com/channels/93055209017729024/756217678493909143/862030161729290267
In Matchlists it enables that matches are entered into unnamed params.
Plus adding aliases for the Match headers in Matchlists to be better in line (naming wise) if the unnamed params are used.
I think this might get used by quite some wikis, so it seems to be better to enable it directly in the base version instead of letting most wikis overwrite it.
(Just a suggestion, no problem if not wanted^^)
Example:
The following code snippets will do the same after this change
```
{{MatchList|id=...
|{{Match|...}}
|{{Match|...}}
|{{Match|...}}
}}
---------------
{{MatchList|id=...
|M1={{Match|...}} …
```
> Add Option to use unnamed params for matches in matchlists

- match2/commons/get_match_group_copy_paste.lua
* Improve randomness of ID generator due to seeding the Random Number Generator by time and throwing the first 3 random values away.
* Enable `args` to be passed to matchlist and bracket functions.
> Improve randomness of ID generator + enable `args` passing

- match2/wikis/starcraft2/match_group_legacy.lua
Sometimes that key is a number so using String functions on it throws errors. Converting it to a string first solves that.
> Fix Legacy Conversion error (stacked 1st)

- match2/commons/match_group_base.lua
Add option to disable ID duplicate check if storage is also disabled
Use-Case:
Legacy Bracket that gets transcluded, for which storage is disabled (only on the page that gets transcluded) the double ID check will still add the double ID category to the page that gets transcluded.
> Add option to disable ID duplicate check (stacked)

- match2/wikis/starcraft2/match_group_legacy.lua
* Disable storage by default in UserSpace
* Allow blank entries in Brackets in UserSpace IF storage is not enabled manually
Reason:
Brackets in UserSpace often are incomplete and wrongly used.
Due to that the Conversion on UserSpace throws several errors.
> Add UserSpace workarounds (stacked)

- match2/wikis/starcraft2/match_legacy.lua
Change "L" walkovers to be "unk" resulttype in the match(1) storage.
Reason:
some "old" Modules want this value instead of the "L" one.
e.g. https://liquipedia.net/commons/Module:Player_matches_table
> Adjust Legacy resulttype storage

- match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
Fix h2h link for players that have spaces in their name
__Before:__
__After:__
> Fix h2h link

- match2/wikis/starcraft2/match_group_legacy.lua
Add an edit-warning when editing pages with Legacy Brackets
> Add Legacy edit warning (stacked)

- match2/wikis/starcraft2/match_group_legacy.lua
Fix DE reset conversion
this enforces that the Finals macth only displays score2 if there actually is a score set for one of the opponents
__Before:__
__After:__
> Fix DE reset conversion (stacked)

- match2/commons/display_util.lua
Add `DisplayUtil.try` which is a variant of `DisplayUtil.TryPureComponent` that works for a general function. Given a function, it either returns its result, or on error returns a rendered error message that can be outputted. 
Also improves the output of `DisplayUtil.LuaError` slightly.
> Add DisplayUtil.try

- match2/commons/match_group_display_bracket.lua
Uses the third place header specified via `RxMTPheader=` if it's set
> Customize third place header

- match2/wikis/starcraft2/match_group_legacy.lua
Allow advantage input the old way in legacy conversion.
> Allow advantage input the old way in legacy conversion.

- match2/wikis/starcraft2/match_group_legacy_default.lua
With this change for a match that has to be set in a custom way we only need to call
```
customMapping.R3M1 = DefaultMapping.matchMappingFromCustom({
opp1 = 'R3W9',
opp2 = 'R3W10',
details = 'R3G5details',
match = 'R3M1',
header = 'L3',
})
```
instead of setting
```
customMapping.R3M1 = {
['$flatten$'] = { 'R3G5details' },
['finished'] = 'R3W9win|R3W10win',
['opponent1'] = {
['$notEmpty$'] = 'R3W9',
['1'] = 'R3W9',
['flag'] = 'R3W9flag',
['race'] = 'R3W9race',
['score'] = 'R3W9score',
['type'] = 'type',
['win'] = 'R3W9win',
},
['opponent2'] = {
['$notEmpty$'] = 'R3W10',
['1'] = 'R3W10',
['flag'] = 'R3W10flag',
['race'] = 'R3W10race',
['score'] = 'R3W10score',
['type'] = 'type',
['win'] = 'R3W10win',
},
['R3M1header'] = 'L3'
}
customMapping.R3M1= DefaultMapping.addMaps(customMapping.R3M1) …
```
> Add functions `matchMappingFromCustom` and `matchResetMappingFromCustom`

- match2/wikis/rocketleague/brkts_wiki_specific.lua
* Adjust RL Input processing (via `Module:Brkts/WikiSpecific`) to allow score2 & score3
* Allow Headers for maps (also needed for the 3set match stuff)
Display adjustments will follow in later PRs
Example where it will be used: https://liquipedia.net/rocketleague/Rocket_League_Championship_Series/Season_X/Championships/Europe#Results
functionality in combination with #106
> Adjust processing to allow score2 & score3

- match2/wikis/rocketleague/opponent_display.lua
Add Option for score2 & score3
* for all matches
* from extradata of opponents
* bracket-reset functionality remains untouched
takes #105 as basis to show what changes compared to the default on commons
functionality in combination with #103
> Add Option for score2 & score3 (stacked)

- match2/commons/match_group_base.lua
Allow manual overwrite for mobile match width in brackets.
The Display Modules already have the functionality, the param just needs to be passed to them.
> Allow manual overwrite for mobile match width

- match2/commons/match_group_util.lua
Reason: when retrieving stuff from the TBD team template it returns `{{Abbr|TBD|To Be Decided}}` which will just be displayed like that.
Changing the team template would cause other issues (like the the displays linking to the `TBD` page everywhere it is used).
This change solves the bad display without creating the (red) links everywhere else.
__Before:__
__After:__
> Change TBD from template to hardcoded stuff

- match2/wikis/rocketleague/brkts_wiki_specific.lua
change icon and name retrieval to use `mw.ext.TeamTemplate.raw`
but keep the old functions, so that in case the team template exists the old way, but not in the extension it will still be recognized
> change icon and name retrieval

- match2/commons/match_group_util.lua
- match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua
When populating match2 structural types from extradata, remove those values in extradata. Makes things easier to read when dumping match2 objects to logs.
> Starcraft: Clear values when extracting from extradata

- match2/commons/match_group_display_bracket.lua
- match2/commons/match_group_util.lua
- match2/commons/starcraft_starcraft2/match_group_display_bracket_starcraft.lua
- match2/commons/starcraft_starcraft2/match_group_input_starcraft_ffa.lua
- Move `upperMatchIds`, `headMatchIds` computation out of `BracketDisplay` because the FFA display module will also make use of it. Ideally this would also be stored in lpdb (and fetched instead of computed). I'm leaving that for the future.
- Added a `MatchGroup` structural type to hold the new fields.
- Added field `match.bracketData.advanceSpots`: an array that maps placements to advancement colors (`up`, `stayup`, etc). It is roughly the match2 equivalent of the `pbg=` params used in standings tables, as it encodes which placements advance, and is populated before the match starts. It encompasses info stored under `qualWin, qualLose, upperMatchIds, winnerto, loserto`, and generalizes them to multiple opponents.
> [ffa 1/5] Add more fields for match to match relations (`bracketData.advanceSpots`, `MatchGroup` struct)

- match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua
- match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
Rework offrace computation code path to make parts of it visible to FFA modules.
- Previously a player's race specified in a match was stored in the `mainRace` field. For non team matches, if the played race differs, then it is shown as an offrace. I removed `mainRace` because it's not actually the main race of the player, only of the match. I changed it to explicitly compare the played race with the race specified in the match.
> [ffa 2/5] Rework offrace computatation (Scarlett race switch param)

- match2/commons/match_group_util.lua
- match2/commons/opponent_display.lua
- match2/commons/starcraft_starcraft2/match_group_display_bracket_starcraft.lua
- match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua
- match2/commons/starcraft_starcraft2/opponent_display_starcraft.lua
- Added fields to structural types: `Match.noScore`, `Opponent.advances`, `GameOpponent.placement` `GameOpponent.score` 
- See https://liquipedia.net/starcraft2/Liquipedia:Brackets/FFA for a description of what they do
- Added `showplacement` to `match.extradata`, which overrides whether the match-level placement column (to the left of the opponent column) appears in the FFA match summary.
- Added `advancecount` to `match.extradata`, which overrides the number of opponents that advance from a match. See https://liquipedia.net/starcraft/Liquipedia:BracketUpdate/Tests/Artosis for an example.
- The fields are added to the starcraft namespace. Will move them to general namespace once we have more experience with ffa related things.
> [ffa 3/5] Add FFA fields to various structs

- match2/wikis/rocketleague/brkts_wiki_specific.lua
Convert Team Opponents with Template "bye" to Literal Opponents
Avoids the "No team template exists for name bye" stuff
__Before__
__After__
> Add Catch for "bye"

- match2/commons/match_group_legacy.lua
Allows empty matches in UserSpace for Legacy Brackets
Empty Opponents will be replaced with `TBD`
This will suppress lots of errors in UserSpace for missing matches
Also fixed a small problem where a key could be a number and not a string and hence throwing errors
Comparable to #84
> Allow empty matches in userspace

- match2/wikis/rocketleague/brkts_wiki_specific.lua
Resolve the historical part of team templates before storage
--> enables the proper display of them
VS
> Store team template resolved

- match2/commons/match_group_legacy.lua
Disable storage in user space as default for Legacy
Overwrite via `|store=true` would still be possible.
> Disable storage in user space as default for Legacy (stacked)

- match2/commons/match_group_display_bracket.lua
Add Option to "not" display a header that by default is set via entering `&nbsp;` manually into it.
The header is still there but the background color is inherited and it has no border.
new css class for this:
```
.brkts-header-nodisplay {
border: none;
background-color: inherit;
}
```
Result:
> Add option to not display a default header

- match2/commons/match_group_base.lua
* Kick `bracketreset` & `thirdplace` from bracketdata if the matches do not exist
> Kick `bracketreset` & `thirdplace` if they do not exist

- match2/wikis/rocketleague/brkts_wiki_specific.lua
Add option for unfinished maps (OPTION 2)
* Maps can be set as not yet finished via `|finished=false` or `|unfinished=true` in the map template call
PR #131 has an alternative way how we can achieve it
__Advantages to #131 __
* Better performance
* all map functions directly used in map processing and not having to move some to match processing
> Add option for unfinished maps (OPTION 2)

- match2/wikis/rocketleague/brkts_wiki_specific.lua
- match2/wikis/rocketleague/match_group_legacy_default.lua
Adjust
* `Module:Brkts/WikiSpecific`
* `Module:MatchGroup/Legacy/Default`
to enable legacy STORAGE of `mapXtYgoals`
Display to be done later (if we want it)
> Support `mapXtYgoals` STORAGE for Legacy reasons

- match2/wikis/rocketleague/match_summary.lua
Add Support for Legacy usage of `|pXteam=` in https://liquipedia.net/rocketleague/Template:SwissMatchMaps
> Add Support for Legacy usage of `|pXteam=`

- match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- match2/wikis/rocketleague/brkts_wiki_specific.lua
thanks to the change to `mw.ext.TeamTemplate.raw` some functions now are redundant and hence can be removed/shortened
> Switch TeamTemplate Processing

- match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
moved the check into the wikicode of https://liquipedia.net/starcraft2/Template:Map
* fixes the issue that maps were still processed if empty (except for the first empty one they were still processed)
> moved check to wiki code

- match2/commons/match.lua
LP Tier Type isn't saved to LPDB, fixed that
> Save LP Tier Type to LPDB if set

- match2/wikis/rainbow_six/brkts_wiki_specific.lua
- match2/wikis/rainbow_six/match_legacy.lua
* Empty {{TeamOpponent|}} is display as Literal empty string, instead of Team Template TBD
* Literals are stored as TBD when converting match2 to match1
> R6 improved literals

- match2/wikis/rainbow_six/match_legacy.lua
Ops Bans in match1 has a space after the comma.
> Fixed Match1 Operator Bans

- match2/wikis/rainbow_six/brkts_wiki_specific.lua
* When only one team recieved points, the other would get -1 instead of 0, causing winner calculations not to work.
* Draws
> Fixed two cases when automatic match score calculations could fail

- components/infobox/commons/infobox_series.lua
add optional function to define tournament vars for infobox series
(needed for e.g. external cup lists)
**alternate option:** call this from `addCustomCells` in the Custom module
> add optional function to define vars (stacked)

- components/infobox/commons/infobox.lua
Fixes a bug where we tried to add a node to `self.chronology`, as opposed to `self.chronologyContent`. We don't even need that class var set though, so simplify the code while we're at it.
> Simplify and fix chronology code

- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/match_group_display_matchlist.lua
- components/match2/wikis/rainbow_six/brkts_wiki_specific.lua
Added support for a function in brkts/wikispecific to overrule the default matchHasDetails.
This is instead of requiring the overrule to be in a custom MatchGroup/Display/Bracket AND MatchGroup/Display/Matchlist which most wikis likely won't need. 
matchHasDetails determine's if the popout with match details is available or not.
Brkts/wikispecific was choosen after discussion with hjp, due to other similiar functions already exists in brkts/wikispecific, such as getMatchGroupModule
> Better customization options for matchHasDetails

- components/match2/wikis/rainbow_six/match_legacy.lua
- components/match2/wikis/rainbow_six/match_summary.lua
* Match2 to Match1 -> usage of extradata.bestofx is expected a string and not a number (it's template based and not module so it matter). Convert to bestof to a string before saving
* Match2 to Match1 -> Order of map halves in Match1 is always atk,def,otatk,otdef. Fixed it
* MatchSummary could display wrong for OT, it took some of the data from RT instead of OT.
> 3 minor bugfixes for R6

- components/infobox/commons/infobox.lua
Fixes an issue where chronology was being set to the root HTML, as opposed to the infobox specific HTML. See the screenshot for visual example.
> Attach chronology cell to content, not root

- components/infobox/commons/infobox.lua
`centeredCell` accepts just one input param, which makes its usage inconsistent with fcell when supplying multiple arguments. This PR changes the function to accept varargs.
> Make centeredCell accept varags as input

- components/infobox/commons/infobox.lua
Matcherino is used on tournament pages.
Sadly it has 2 different link formats, but we use the same icon for it, hence we need this exception here.
> add exception for matcherino

- standard/localisation.lua
old calls of this module passed args as a table (and sometimes the frame), so not to break stuff we need this for now
> add temp workaround

- components/infobox/commons/infobox.lua
* adjust link key cleanup so that we can drop lots of stuff from the links module's `_PREFIXES` table
see #196
> adjust link key cleanup

- components/infobox/commons/infobox_league.lua
- components/infobox/wikis/rocketleague/infobox_league_custom.lua
Stacks on #206 
Creates Rocket League's prize pool calculation. Would be better to use the automated conversion for this but the current one doesn't use it, so this PR simply converts the current template code to lua
> Create prizepool calculation for tournaments

- components/match2/commons/match_group_display_bracket_template.lua
- components/match2/commons/match_group_display_helper.lua
Used by bracket template pages on commons to show a blank bracket. This was previously rendered in php. 
Example https://liquipedia.net/commons/Template:Bracket/8-1Q-2L1D-1Q
> Add BracketTemplateDisplay

- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/match_group_display_matchlist.lua
Changes that come after the current round of stylesheet cleanup.
Changes include:
- Delegated overflow handling to match summary popup implementations. This enables more advanced overflow handling, such as that used by ffa match summary.
- The wrapper element around match summary has been merged with the match summary element. Should be easier to style them now.
> [css2] Post-css cleanup

- components/match2/commons/match_group_display_matchlist.lua
- components/match2/commons/starcraft_starcraft2/match_group_display_matchlist_starcraft.lua
This rewrites matchlist to use css grid instead of table. It fixes a bunch of issues that are a result of wiki not supporting `table-layout: fixed`.
Fixes mouseover z-index interaction with green backgrounds on adjacent cells
Before:
After:
Fixes mobile width calculation
Before
After
Fixes simultaneous popup active and opponent hover effects
Before
After
> Rewrite matchlist using css grid

- components/infobox/commons/infobox_basic.lua
fix `BasicInfobox:createBottomContent` so we can use self on the call
> fix `BasicInfobox:createBottomContent`

- components/infobox/commons/infobox_basic.lua
we need this function in several infoboxes, so we could just call them from here
* function `getAllArgsForBase` allows it to retrieve a set of customizable Links or args for a certain baseArg from args
intended usage is for use in unpack inside fcell
example code:
```
infobox:fcell(Cell:new('Caster(s)'):options({}):content(
unpack(self:getAllArgsForBase(args, 'caster', {makeLink = true}))):make())
```
result:
needs updating the /doc too
> Add function `getAllArgsForBase` to `Module:Infobox/Basic`

- components/infobox/commons/infobox.lua
needed for some infoboxes on sc2 (e.g. ability, spell)
needs updating the /doc too
> add option to change the size of infoboxImage

- components/match2/wikis/rainbow_six/brkts_wiki_specific.lua
- components/match2/wikis/rainbow_six/match_legacy.lua
- components/match2/wikis/rainbow_six/match_summary.lua
- Changed MatchSummary comment to use block display. It fixes issues in the previous iterations, `<span>comment</span> `didn't linebreak correctly & none-block-display solution looks really bad if there's a link or reference in the comment.
- Forgot to add the date parameter to the formatDate call, fixed
- Changed the Match2->Match1 mapping when it comes to how the R6 match1 handles walkovers
- Added the match1.header field in the Match2->Match1 mapping
- Fixed case where if only defense and not attack (live updating) score has been entered, it would ignore the entered defense score
- Modules calling Match1 expects atk/def to have 0's instead of blank
- Fixed issue where games without a date, would be automatically marked as finished, because more then one day has passed since 1970.
> Various R6 fixes

- components/infobox/commons/infobox_league.lua
If we are given the following param:
```
|organizer=[https://www.dell.com/en-us/gaming/alienware Alienware]
```
We would error since `mw.title.new` will return `nil`. Handle those cases.
> Handle links being given to `_exists`

- components/infobox/commons/infobox_league.lua
If a tournament is single date, i.e. happens on a single day, we have no startdate. In that case default to the enddate for LPDB
> Default to enddate when no startdate is given

- components/infobox/commons/infobox_league.lua
On many wikis, when a tournament's location is online, the region is put as location, like so:
```
|country=Oceania
```
This breaks our location display:
This PR makes sure those locations are handled
> Handle valid locations which are not countries

- components/infobox/wikis/rocketleague/infobox_league_custom.lua
Rocket League still uses a legacy implementation of `liquipediatiertype`, so we need to support that for now.
> Use legacy liquipediatiertype for RL

- components/match2/wikis/rainbow_six/brkts_wiki_specific.lua
R6/Brkts/WikiSpecific was missing the github action header. Added
> Added action header to R6's Brkts/WikiSpecific

- components/match2/commons/match_group_display_helper.lua
- components/match2/commons/opponent_display.lua
- components/match2/commons/player_display.lua
- components/match2/commons/starcraft_starcraft2/player_display_starcraft.lua
- components/match2/wikis/starcraft2/match_legacy.lua
copy modules from live that have some minor bug fixes/changes
--> so the automated copy from git to wiki doesn't cause issues with those modules
*  components/match2/commons/match_group_display_helper.lua
* * `&nbsp;` handling & needed bracket
* components/match2/commons/opponent_display.lua
* * add `&nbsp;` fallback for literals
* * import `Module:Logic`
* components/match2/commons/player_display.lua
* * add css whitespace pre
* components/match2/commons/starcraft_starcraft2/player_display_starcraft.lua
* * add `&nbsp;` fallback for players
* components/match2/wikis/starcraft2/match_legacy.lua
* * change formatting a bit & add additional conditions for games/maps to be stored as legacy match
> copy from live

- components/infobox/wikis/rocketleague/infobox_league_custom.lua
Fix for Rocket League 1v1 tournaments not having a `participantsnumber`
> Use `player_number` for `participantsnumber`

- components/infobox/commons/infobox_league.lua
Allow some more customization of `Infobox/League`
* Server display
* * SC2 has a "cleaning" function for server input.
* * * we only allow certain servers
* * * we standardize the output
* function to determine if we should store data (we have some pages in main space that should not)
* chronology data (we allow `previous3` & `next3` and have some of it automated on sc2)
> Allow more customization of `Infobox/League`

- components/infobox/commons/infobox_league.lua
Move `_definePageVariables` to the start of `run` so that the vars are available in functions like `createPrizepool`
stacked on #278
> Move `_definePageVariables` to the start of run

- components/infobox/commons/infobox_cell.lua
For certain cells we would like to have the ability to add a CSS class to the root. An example of this is `liquipediatier`
> Allow adding class to Cell

- components/infobox/commons/dev_infobox.lua
- components/infobox/commons/infobox_widget_customizable.lua
- components/infobox/commons/infobox_widget_injector.lua
Stacks on #305, see #304 for overview.
Creates the `Customizable` widget, accepting an ID and a list of widgets, and which using the `Injector`, can be used to specify wiki-specific widgets in groupings that make sense. For example:
```lua
Customizable(
'tier',
{
Cell('Liquipedia tier', args.liquipediatier),
Cell('Liquipedia tier type', args.liquipediatiertype)
}
),
```
A wiki could now add cells to this grouping of tier, thereby keeping all tier-related properties together.
> Create Customizable widget

- components/infobox/commons/infobox_widget_chronology.lua
See #304 for overview.
Creates the Chronology widget, which links to the next/previous tournaments in a series
> Create Chronology widget

- components/infobox/commons/infobox_widget_customizable.lua
- components/infobox/commons/infobox_widget_injector.lua
Add the function `addCustomCells` to `Injector` so we avoid having custom modules always having to check `id == 'custom'`.
> Add `addCustomCells` to `Injector`

- components/infobox/commons/infobox_widget_center.lua
- components/infobox/commons/infobox_widget_chronology.lua
- components/infobox/commons/infobox_widget_customizable.lua
- components/infobox/commons/infobox_widget_links.lua
- components/infobox/commons/infobox_widget_title.lua
Always use named arguments for widgets
For all widgets:
- `name` will be used for display values
- `id` will be used for ... identifiers
- `content` will be used for content of that widget
- `child`/`children` denote inner widgets, e.g. in Customizable
- return values are always **lists** of widgets.
> Switch to named arguments for widgets

- components/infobox/commons/infobox_widget_builder.lua
Creates the Builder widget. While its functionality is very simple, it enables clearer code.
Before
=======
```lua
local widgets = ({
Cell{name = 'Founded', content = {args.foundeddate},},
Cell{name = 'Defunct', content = {args.defunctdate},},
})
if not String.isEmpty(args.companytype) and args.companytype == _COMPANY_TYPE_ORGANIZER then
infobox:cell('Total prize money', self:_getOrganizerPrizepools())
table.insert(widgets, Cell{
name = 'Total prize money',
content = {self:_getOrganizerPrizepools()}
})
infobox:categories('Tournament organizers')
end
```
After
=====
```lua
local widgets = ({
Cell{name = 'Founded', content = {args.foundeddate},},
Cell{name = 'Defunct', content = {args.defunctdate},},
Builder{
builder = function()
if not String.isEmpty(args.companytype) and args.companytype …
```
> Create builder widget

- components/infobox/commons/infobox_scene.lua
Migrates Infobox/Scene over to table based layout, see #304 . Merges into #321 
* has no custom versions on any wikis
* only used on sc2
> Migrate infobox scene

- components/match2/commons/match_group_display_helper.lua
Fixes an issue where opponents in a blank bracket (or matchlist) are hoverable
> Don't make blank opponents hoverable in matchlist and bracket

- components/infobox/commons/dev_infobox.lua
- components/infobox/commons/infobox_widget_factory.lua
Extracts conversion from Widget to HTML to its own module, in case it's ever needed outside of Module:Infobox. Also adds logic to make `Builder` work
> Create widget factory

- components/infobox/commons/infobox_basic.lua
- components/infobox/commons/infobox_map.lua
- components/infobox/commons/infobox_patch.lua
- components/infobox/commons/infobox_patch_custom.lua
- components/infobox/commons/infobox_widget_highlights.lua
- components/infobox/wikis/starcraft2/infobox_patch_custom.lua
Migrates Infobox/Patch over to table based layout, see #304. Merges into #321 
* adjust function `getAllArgsForBase` in `Module:Infobox/Basic` a bit
* add `Module:Infobox/Widget/Highlights`
* migrate `Module:Infobox/Patch`
* migrate `Module:Infobox/Patch/Custom` base version on commons
* migrate `Module:Infobox/Patch/Custom` SC2
> Migrate Infobox patch

- components/infobox/commons/infobox_widget_factory.lua
Children of Customizable do not currently receive context. This PR fixes that.
> Pass context to Customizable children

- components/infobox/commons/infobox_team.lua
Adds a Title widget to achievements in Infobox/Team
> Add Title to team achievements

- components/infobox/commons/infobox_team.lua
#321 removed support for "default" team logos for when a team does not have a logo.
> Support default team logo

- components/infobox/commons/infobox_basic.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Remove default `:addCustomContent` function as it is no longer needed due to the rewrite (i think)
> Remove default `:addCustomContent` function (stacked on #361)

- components/infobox/commons/infobox_widget_links.lua
- standard/links.lua
Sort and group the links in the Infobox in preferred order.
This is a specific request from Counter-Strike, but I've seen it pondered by other wikis too.
Before
======
After
======
> Sort Links in Infobox

- components/infobox/commons/infobox_widget_links.lua
#363 sorted the infobox links, and set links that were iterated past to nil. This is fine, except that this mutates the original links array in Module:Infobox_X. This PR copies the memory instead, so that it is not mutated.
> Preserve original Links array

- components/infobox/commons/infobox_widget_center.lua
Allow css styling for centered cells
wanted for `Module:Infobox/UnofficialWorldChampion`
> Allow classes for centered cells

- components/infobox/commons/infobox_league.lua
- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Addresses the remaining two Counter-Strike issues:
- location should imo not link to Category:<country tournaments>
- like NiKoholic mentioned: valvetier should be <Valve logo> Tier (currently just the Valve logo)
> Address Counter-Strike Infobox/League complaints

- components/infobox/commons/infobox_widget_header.lua
#380 breaks images when `subHeader` is not supplied. Disable `subHeader`, for now.
> Fix Header images

- components/match2/wikis/rainbow_six/brkts_wiki_specific.lua
match._storePlayers will throw away all players that occur after a gap in the opponentX list by breaking at the first empty entry.
An empty entry could occur for DNPs (did not play).
Tweaked the wikispect function so it won't create gaps in the index.
> Make sure there are no gaps in opponentX_pY (R6)

- components/match2/commons/match_summary_ffa.lua
Adds display component for the popup match summary of a free-for-all match. The data is presented as a table, with opponents as rows and games of the match as columns.
- The component is intended to be general purpose, applicable to all wikis. However because match2 isn't enabled on a lot of wikis I can't validate that assertion as of now.
- The display is visually similar to the Match standings team template used on battle royale wikis. https://liquipedia.net/pubg/Template:Match_standings_team However it is functionally restricted to showing the ffa standings of a match, and not general team standings.
- Most of the cells in the table can be customized by passing in wiki specific cell components in `props.config`
- Most FFA matches in RTS games only care about placement, and will forgo …
> [ffa 4/5] Add FFA match summary display component

- components/match2/commons/starcraft_starcraft2/match_summary_ffa_starcraft.lua
Match summary with starcraft specific customizations
- Support `duo trio quad` opponent types
- Support offrace icons
- Starcraft specific footer icons
> [ffa 5/5] Starcraft specific FFA match summary

- components/match2/commons/opponent_display.lua
- components/match2/commons/player_display.lua
- components/match2/commons/starcraft_starcraft2/player_display_starcraft.lua
Applies to block-style components for players, teams, and literals. 
Before
After
> Show `&zwsp;` for empty block-style opponents

- components/match2/commons/brkts_wiki_specific_base.lua
- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/match_group_display_bracket_template.lua
- components/match2/commons/match_group_display_helper.lua
- components/match2/commons/match_group_display_matchlist.lua
- components/match2/commons/match_summary_ffa.lua
- components/match2/commons/opponent_display.lua
- components/match2/commons/starcraft_starcraft2/match_group_display_bracket_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_group_display_matchlist_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft_ffa.lua
- components/match2/commons/starcraft_starcraft2/match_summary_ffa_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
- components/match2/commons/starcraft_starcraft2/opponent_display_starcraft.lua
- components/match2/commons/starcraft_starcraft2/player_display_starcraft.lua
- components/match2/wikis/rainbow_six/match_summary.lua
- components/match2/wikis/rocketleague/match_summary.lua
- components/match2/wikis/rocketleague/opponent_display.lua
- components/match2/wikis/starcraft/brkts_wiki_specific.lua
- components/match2/wikis/starcraft2/brkts_wiki_specific.lua
- components/match2/wikis/valorant/match_summary.lua
Makes it easier to copy changes between dev and non-dev versions of a module. Can now do a file copy without having to add or remove '/dev' in requires. Also in preparation of a rework of Module:DevFlags
> Use Lua.requireDev for modules with dev and non-dev versions

- components/match2/commons/match_group_display_bracket.lua
Fixes an issue with skipRound not being applied to child matches. Previously this wasn't a problem because match nodes were right aligned in the bracket.
Before ![image](https://user-images.githubusercontent.com/85348434/134084855-5c515c7b-afcc-4c5d-a4be-fc7937f7e3f2.png)
After ![image](https://user-images.githubusercontent.com/85348434/134084840-3d216c2a-53c4-47f2-b6bd-c1b24ca1b3a2.png)
> Bracket alignment fixes

- components/match2/commons/match_group_base.lua
Store Section Headers for matches
input option 1:
input option 2:
lpdb data:
> Store Section Headers for matches

- components/match2/commons/match_group_base.lua
Move Legacy matchlist Warning so it is displayed after the matchlist instead of before it
> Move Legacy matchlist Warning

- components/infobox/extensions/commons/age.lua
Create an age module, allowing calculation of ages. This PR improves over both the current legacy implementation, as well as #400, by providing a class-based structure for calculating the age, improving readability.
In contrast to previous implementations, this module uses `os.time()` extensively to guarantee correctness (and again improve readability).
The module is not yet complete compared to previous implementations, it does not yet set categories, variables, etc. This is to prompt discussion on how exactly we would like to structure the interaction between templates, modules, etc when it comes to these features.
> Create age module

- standard/league_icon.lua
Add LeagueIcon Module
Use Cases:
* function `display`: Display Icons in LeagueIconSmall fashion from modules (e.g. if the icon and iconDark were queried)
* * supports retrieval of the icon from existing LeagueIconSmall templates if not disabled via option flag
* * supports no link versions via option flag
* function `getIconFromTemplate`: retrieve Icon from existing LeagueIconSmall templates if not disabled via option flag
* function `generate`: Generate Copy-Paste Code for creating a new LeagueIconSmall template
* function `generateHistorical`: Generate Copy-Paste Code for creating a new historical LeagueIconSmall template
Examples:
> Add LeagueIcon Module

- standard/feature_flag.lua
`Module:FeatureFlag` is a replacement of the old `Module:DevFlags`
Changes are:
- Flag state is stored in mediawiki variables, so that flags can be enabled from wikicode (e.g. `{{#vardefine:feature_dev|1}}`).
- Flag state is shared between nested templates. In `{{Foo|a={{Bar}}}}`, flags set in `Template:Foo` will be available in `Template:Bar`.
- Default flag state is now configured in `Module:FeatureFlag/Config`. The default must be specified as a literal, and can't depend on runtime state.
> Add Module:FeatureFlag

- components/match2/commons/display_util.lua
- components/match2/commons/match_group_base.lua
- components/match2/commons/match_group_display.lua
- components/match2/wikis/valorant/match_group.lua
- standard/feature_flag.lua
- standard/lua.lua
Changes code that previously used `Module:DevFlags` to use `Module:FeatureFlag`
To `#invoke` a dev module from wikicode, one must enable the dev flag *and* invoke the `/dev`-suffixed module. Enabling the dev flag will not automatically select the dev module. If the dev module is invoked without setting the dev flag, then it won't use the `/dev` suffixed dependency modules.
`Template:Invoke` eliminates this source of error by selecting the module (dev or non-dev) depending on the dev flag, and providing an easy way to set the dev flag.
Usage:
`{{Invoke|Magpie|theive}}` will invoke `Module:Magpie` or `Module:Magpie/dev` depending on whether the `dev` feature flag is enabled.
`{{Invoke|Magpie|theive|dev=1}}` enables the dev flag and invokes `Module:Magpie/dev` …
> Make use of feature flags

- standard/league_icon.lua
* Adjust LeagueIcon Module for Infobox/League
* Fix bug (`leagueIconSmallTemplate` not being split if we have an `icon` but no `iconDark`)
> Adjust LeagueIcon Module for Infobox/League

- components/infobox/commons/infobox_league.lua
Now that we have a standard for iconDark in the LeagueIconSmall templates we can try to retrieve it from them too
wait for #437
> Add iconDark retrieval from LIS

- components/infobox/commons/infobox_person.lua
* Use `Module:Region` instead of `Template:Region` and hence allow determining the region from the country if `Module:Region/CountryData` exists on the wiki
* make role field customizable
> Switch to use Region Module

- components/match2/commons/display_util.lua
`Module:DisplayUtil|assertPropTypes` when enabled on /dev takes up a significant fraction of runtime, which makes it hard to compare timings of dev and non-dev. Plus I don't remember the last time I saw a runtime type check error
This disables runtime type check unless enabled via `feature_force_type_check`.
> Disable runtime type check unless enabled via feature

- components/infobox/wikis/halo/infobox_league_custom.lua
Add legacy var `tournament_edate` to halo `Module:Infobox/League/Custom`
> Add legacy var `tournament_edate`

- components/match2/commons/match_group.lua
- components/match2/commons/match_group_base.lua
- components/match2/commons/match_group_display.lua
Makes use of the performance instrumentation in https://liquipedia.net/commons/Module:Performance/Util
Usage:
Use `{{#vardefine:feature_match_group_instrumentation|1}}` on a page to enable
Configure which functions are tracked in https://liquipedia.net/commons/Module:MatchGroup/Config (or on wikis)
`{{#invoke:Performance/Util|ReportContainer}}` to bring up the results table
`{{#invoke:Performance/Util|ClearData}}` for when a page has more more than one table
Notes:
- Timings are tracked and aggregated across template boundaries. The exception is exclusive duration which isn't propagated upward across a template boundary
Example:
https://liquipedia.net/starcraft2/Liquipedia:BracketUpdate/Tests/Wide_Load
> [mg3] Enable performance instrumentation for match group

- components/match2/commons/match_group.lua
- components/match2/commons/match_group_base.lua
- components/match2/commons/match_group_display.lua
- components/match2/commons/match_group_input.lua
- components/match2/wikis/valorant/match_group.lua
This consolidates all entry points that display matchlist/brackets to just 3 from templates and 3 in lua.
Templates:
- Template:Matchlist -> MatchGroupDisplay.TemplateMatchlist
- Template:Bracket -> MatchGroupDisplay.TemplateBracket
- Template:ShowBracket -> MatchGroupDisplay.TemplateShowBracket
In lua:
- MatchGroupDisplay.MatchlistBySpec
- MatchGroupDisplay.BracketBySpec
- MatchGroupDisplay.MatchGroupById
All other entry points have been marked deprecated and will be soon removed
The functionality in customMatchlist/customBracket, which allows overriding headers when displaying match groups by id, has been merged into MatchGroupDisplay.MatchGroupById.
> [mg7] Consolidate match group entry points

- components/infobox/commons/infobox_team.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
__Region__
* use region module instead of template
* store region standardized instead of as raw input
* make region cell customizable
__Location__
* use standardized country names for display and storage
* use the standardized country name for the region module usage
__SC2__
* Kick region display
> Adjust region & location handling for teams

- components/infobox/commons/infobox_person.lua
* `unknown birth date` was inverted (added when date was set and not added other wise)
> Fix bug in infobox person

- components/infobox/wikis/rocketleague/infobox_team_custom.lua
Rocket league ratings require Region abbreviations in data storage, not the full names which the default Infobox inserts.
> Fix for disappearing ratings on Rocket League 

- components/infobox/commons/infobox_team.lua
- components/infobox/wikis/rocketleague/infobox_team_custom.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Reverts Liquipedia/Lua-Modules#467
This module does not replicate the functionality of Template:Region and thus should be reverted.
The module does not:
- Set SMW
- Set variables
- Properly set LPDB on all wikis
#479 was a temp fix for the last issue, which thus can also be reverted.
> Revert "Adjust region & location handling for teams"

- components/infobox/commons/infobox_team.lua
Make `region` customizable in infobox team so we can kick it (e.g. sc2) or override it (e.g. halo)
Doesn't change the behavior of the module unless override is used in a custom part.
> Make region customizable

- components/infobox/wikis/starcraft2/infobox_team_custom.lua
* Kick Region in sc2 as it is not needed nor wanted
* store locations in a cleaned way (so that e.g. `usa`, `us` and `United States` are stored as the same value)
I just kick some stuff
The module isn't used (yet) so it can not really break something, the currently used module doesn't set region (nor displays it) too...
The currently used module stores locations in a clean way too ...
> Kick Region in sc2

- components/match2/commons/match_group_legacy.lua
- components/match2/wikis/starcraft/match_group_legacy.lua
- components/match2/wikis/starcraft2/match_group_legacy.lua
Legacy brackets aren't passing the right param for template ID. changed it to use args[1] instead of args['1'].
Apply changes and inspect a page with legacy brackets https://liquipedia.net/starcraft2/2019_WCS_Summer/Playoffs
> Fix legacy bracket template id passing

- components/infobox/wikis/starcraft2/infobox_building_custom.lua
Use `String.convertWikiListToHtmlList` instead of `CustomBuilding:_convertToList`
Via sandbox module and user page
> Use `String.convertWikiListToHtmlList` in sc2 building infobox

- components/match2/wikis/starcraft/match_legacy.lua
Player matches table will show the score as "W : " if resulttype isn't empty
Player matches table shows "W :   " as the score instead of "1 : 0" for submatches of team matches using the new brackets, i looked at the differences between the lpdb entrys for team matches using the old matchgroups and the new matchgroups and noticed that the new one has an entry for resulttype and the old one doesn't.
In the Module:Player matches table on commons, the function updateScores checks if resulttype is not empty and changes the score to "W : ".
```lua
local updateScores = function(winner, resulttype, PlayerNo, homeScore, awayScore, result)
local scores = {}
if resulttype ~= '' then
if winner == tostring(PlayerNo) then
scores = {'W', RESULTTYPES[resulttype]}
result = 'win'
elseif winner == …
```
> Removed resulttype 'submatch' for legacy matches (on the starcraft 1 wiki)

- components/match2/commons/match_group.lua
- components/match2/commons/match_group_base.lua
- components/match2/commons/match_group_display.lua
Makes it easier to know when to remove one of the deprecated functions
> [mg12] Add deprecation warnings to match group entry points

- components/match2/wikis/starcraft/match_legacy.lua
Clean up SC `Module:Match/Legacy`
* prefix internal functions with `_`
* switch `"` to `'` (before it was a mix)
* rename `p` to `Legacy`
* remove expand template function and replace its usage with the `safeExpand` function from the template module
tested it on live for a few minutes (only used on a hand full of pages)
> Clean up SC `Module:Match/Legacy`

- components/infobox/commons/infobox_widget_links.lua
* `self:_removeAppendedNumber` is not needed there due to the key coming from the `_PRIORITY_GROUPS` and hence not having the appended number
* display links with the same base as key (i.e. if they only have an appended number) one after another behind the one without appended number
Tested on halo wiki by creating the module (with the changes) there (hence not using the commons module), see if it throws and if it does what it is supposed to do, delete the halo module again
Before image:
After Image:
> Fix Link order in infoboxes

- standard/table.lua
stacked on #503
`Table.iter.prefix` Iterates over table entries whose keys are prefixed numbers. The entries are
visited in order, starting from 1. The iteration stops upon a skipped number.
Example:
```
local args = {
p1 = {},
p2 = {},
p3 = {},
foo = {},
p10 = {},
}
for key, player in Table.iter.prefix(args, 'p') do
mw.log(key)
end
```
will print out 'p1 p2 p3'
```
local args = {
p1 = {},
p2 = {},
p3 = {},
foo = {},
p10 = {},
}
for key, player in Table.iter.prefix(args, 'p') do
mw.log(key)
end
```
> Add Table.iter.pairsByPrefix

- components/match2/commons/brkts_wiki_specific_base.lua
- components/match2/commons/match_group_display.lua
- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/match_group_display_matchlist.lua
- components/match2/commons/starcraft_starcraft2/match_group_display_bracket_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_group_display_matchlist_starcraft.lua
- components/match2/wikis/rocketleague/brkts_wiki_specific.lua
- components/match2/wikis/rocketleague/match_group_display_bracket_custom.lua
- components/match2/wikis/starcraft/brkts_wiki_specific.lua
- components/match2/wikis/starcraft2/brkts_wiki_specific.lua
- Remove luaGet on Matchlist and Bracket display modules, and instead call the container directly.
- Change Brkts/WikiSpecific getMatchGroupModule to getMatchGroupContainer
- configFromArgs isn't wiki customizable right now. Could add when needed.
> [mg13] Simplify matchlist/bracket container interface

- standard/logic.lua
- standard/string_utils.lua
- standard/table.lua
There are 450 `Logic/Table/StringUtils.isEmpty` calls in this repo, and the majority (260) of them occur as `not Logic/Table/StringUtils.isEmpty(x)`. 
I added `Logic/Table/StringUtils.isNotEmpty` to tailor to this usage. So instead of writing `not Logic.isEmpty(x)` one can instead write `Logic.isNotEmpty(x)`.
Tested as a part of #534
> Add Logic.isNotEmpty, Table.isNotEmpty, StringUtils.isNotEmpty

- components/infobox/commons/infobox_person_user.lua
Add Gender field to default `Infobox user`
RL, CS and some others have that field.
After this imo RL, CS and several others can directly use the commons based `Module:Infobox/Person/User` for their invoke in `infobox user`
just adding a simple field, not tested
> Add Gender field to default `Infobox user`

- components/infobox/commons/infobox_league.lua
Certain wikis want more than just two locations. This PR allows for infinite locations. Furthermore, the existing code was essentially duplicated twice, so by putting the code in a loop we make it cleaner too.
The code is already running on a dev wiki, and works well there. The code is largely unchanged, aside from being put into a loop.
> Allow infinite league locations

- components/infobox/wikis/starcraft2/infobox_unit_custom.lua
Avoid nil concat
pushed to live to fix the bug
> Avoid nil concat

- components/match2/commons/match_group_base.lua
- components/match2/commons/match_group_display.lua
- components/match2/commons/match_group_input.lua
Allows the use of
```
{{Bracket|Bracket/4H2L1DH2LLH4H2H2L1DLLL|id=DWAkb4zHaJ|warnMissing=false}}
```
to show an empty bracket without specifying `R1M1=...` etc. Useful for testing and debugging. If `warnMissing=true` (default) it would show the same empty bracket but with a warning for the missing matches.
Use https://liquipedia.net/starcraft2/Liquipedia:BracketUpdate/Tests/Bracket_Layout
> Allow disabling missing match warning in brackets

- components/match2/commons/match_group_util.lua
- components/match2/commons/match_group_workaround.lua
stacked on #476
This is a lua workaround to the lpdb bug where players are sometimes assigned to a different opponent. See hjpa's description below for more details.
The workaround is to recompute the player-opponent assignment when the match group is fetched in `MatchGroupUtil.fetchMatchRecords`.
Before
After
Turn on `feature_issue528_workaround`
Inspect
https://liquipedia.net/starcraft2/Liquipedia:BracketUpdate/Tests/WTL_0
https://liquipedia.net/starcraft2/Liquipedia:BracketUpdate/Tests/Wide_Load
> Add workaround for player indexing bug

- components/infobox/commons/infobox_league.lua
The current version from #640 introduces a bug where nothing will be written to LPDB for previous/next if those parameters do not contain a `|` (because, e.g. the pagename can be used as a displayname already).
Removing the shortcut altogether fixes this, because `mw.text.split(string, '|', true)[1]` will contain the whole string when no `|` is found.
Tested behavior of mw.text.split within a sandbox/luaconsole
> Fix bug where missing displayname would result in empty string for previous/next in LPDB

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
Adjust chronology storgae for sc2
Since SC2 determines next/previous semi automatically we need some small adjustments to store them properly.
sandbox
> Adjust chronology storgae for sc2

- components/infobox/commons/infobox_league.lua
Allow more organizers and sponsors to be stored in LPDB for `Infobox league`
e.g. apex currently stores >5 sponsors
Created the module locally (temporarily) on sc2 and used it on a test page (in main space that i deleted afterwards again)
> Allow more organizers and sponsors for LPDB

- components/infobox/commons/infobox_league.lua
In the case of one day tournaments, only date is filled in the infobox. Therefore, sdate = edate = date, and all date variables have to be fed from args.date
Tested in a sandbox on ageofempires:
- that tournament_enddate is set correctly already
- that this change will achieve the same with tournament_startdate
Tested on RL:
- that prize pool and other downstream templates will use `tournament_startdate` if present, otherwise fallback to `tournament_enddate`
- Checked that setting the var in the infobox/directly after won't change LPDB data
> Fix variable tournament_startdate to be filled from args.sdate or date

- components/match2/wikis/rocketleague/match_legacy.lua
Rocket League's legacy module is saving player info (opponent1players, opponent2players) in a datastucture that modules retrieving the information don't expect, causing lua error and missing data. 
The RL modules that use the information are Module:Rating/Run (and Module:Rating/Display via a data object that /Run saves in smw) and Module:TeamsMatchup/versus (which is used on the stream page).
Did a quick live test. 
https://liquipedia.net/rocketleague/index.php?title=Module:Match/Legacy&diff=989058&oldid=969501
Purged the page of a tournament and checked the stream page.
Where previously the stream page would give out a lua error, it now successfully rendered the additional information.
For the Rating's Module, the roster display is commented out (because it hasn't been working), hence it …
> Change match1 player saving

- components/infobox/commons/infobox_person.lua
* support display of team2 in `nameDisplay`
* support several additional params used for team entry for `nameDisplay`
* add option for (custom) page vars
* team cells: no testing, due to it just being copy paste
* icons in name display via sandbox on sc2
* custom vars: none due to it being a function that does nothing (overridable)
> prepare for infobox player implementation on RL and CS

- components/infobox/commons/infobox_person.lua
Fix Team Display in infobox person implementations
pushed to live
before:
after:
> Fix Team Display in infobox person

- standard/table.lua
Add Table.deepMergeInto
Recursively merges entries from the second table into the first table,
overriding existing entries. The first table is mutated in the process.
Can be called with more than two tables. The additional tables are merged into
the first table in succession.
Usage
```
Table.deepMergeInto({a = {x = 3, y = 4}}, {a = {y = 5}})
-- Returns {a = {x = 3, y = 5}}
```
```
Table.deepMergeInto({a = {x = 3, y = 4}}, {a = {y = 5}})
-- Returns {a = {x = 3, y = 5}}
```
> Add Table.deepMergeInto

- components/infobox/wikis/rocketleague/infobox_team_custom.lua
Add school tier LPDB storage to RL infobox team (as requested by Basincc)
not tested as it only adds additional storage to LPDB that is not yet used anywhere
1. Apply it to the module (since bots are a bit broken)
2. Adjust the template to also store it in SMW (the team portal still uses SMW)
3. Purge all team pages to update their LPDB and SMW data
4. adjust query condition on the team portal page(s) so that school teams do not show up there
5. Create a new team portal sub page for the school teams & start creating team pages for it
> Add school tier LPDB storage to RL infobox team

- components/infobox/commons/infobox_person.lua
* For persons use id instead of name for `objectname`
* add missing underline in objectname
pushed to live
> Use id instead of name for `objectname`

- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Remove useless line
the elseif is never triggered due to the elseif above having the same condition
pushed to live
> Remove useless line

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/wikis/starcraft/match_legacy.lua
- components/match2/wikis/starcraft2/match_legacy.lua
Rename race to faction in lpdb match2game.extradata storage
Adjust legacy modules accordingly
goal is to standardize race/... to the term faction
pushed to live, compared lpdb data entries (legacy ones are still the same, match2game is changed as intended)
checked the current and the match2 query version of the module that uses this data and it works as intended
> Rename race to faction (SC, SC2)

- components/infobox/commons/infobox_item.lua
- components/infobox/wikis/wildrift/infobox_item_custom.lua
* base implementation for infobox item
* * sadly infobox item is very very very very very different across wikis so that the base module will have to be entirely overwritten for most usages
* infobox item implementation for wildrift
created the modules and a test template on wildrift
hesketh will test in the upcoming days
lpdb implementation is not done in the custom module as the current (wiki code) template only has smw at this point. The wiki would need to decide what to store into lpdb first (storing everything into a datapoint seems rather bad it would be several A4 pages of json in extradata)
> Add infobox item implementation

- components/infobox/wikis/starcraft2/infobox_person_player.lua
Add missing `{}` (the automated achievements return a string so the brackets are needed)
pushed to live to kill the error
> Add missing `{}`

- components/infobox/commons/infobox_league.lua
Counterstrike has requested that instead of showing "Organizer(s)", we show either "Organizer" or "Organizers" depending on the number of organizers. This PR implements that.
Pushed to https://liquipedia.net/commons/Module:Infobox/League/dev
And then tested on counterstrike. This is not overridable by wikis, so behaviour is the same everywhere.
> Selectively show `organizers` plural

- components/infobox/wikis/starcraft2/infobox_person_player.lua
stacked on #676 
* Do not show Achievements header if no achievements are set
* do not display allkills if the query return `'0'`
pushed to live to fix the bug
> Fix Achievements display

- components/infobox/commons/infobox.lua
- components/infobox/commons/infobox_basic.lua
enable `darkmodeforced` in infoboxes
`/dev` modules for the modules that get changed + for infobox person and infobox person/player (on sc2)
> enable `darkmodeforced` in infoboxes

- components/infobox/commons/infobox_unit.lua
Make header in infobox unit/champion/... customizable (wildrift needs an additional line between image and hence i need to be able to set the subheader there)
doesn't change the behavior if not overwritten
> Make header customizable

- components/match2/wikis/rainbow_six/match_legacy.lua
An `or 0` in an incorrect place, causing lua errors if opponent.score were to be a string. 
While opponent.score should never be a string (see guidelines), throwing a lua error is not the way to go if it were to happen.
Tested it live.
https://liquipedia.net/rainbowsix/index.php?title=Module%3AMatch%2FLegacy&type=revision&diff=384314&oldid=373959
> Fixed lua error in Match2 -> Match1 mapping

- components/match2/wikis/rainbow_six/match_group_input_custom.lua
Convert numeric strings to numbers before comparing them, avoiding lua error if one is a number and one is a string.
Tested it live.
https://liquipedia.net/rainbowsix/index.php?title=Module%3AMatchGroup%2FInput%2FCustom&type=revision&diff=384320&oldid=374459
> Ensure numbers are of number type and not strings

- components/match2/commons/starcraft_starcraft2/match_external_links_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_group_display_bracket_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_group_display_matchlist_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_summary_ffa_starcraft.lua
- components/match2/commons/starcraft_starcraft2/opponent_display_starcraft.lua
- components/match2/commons/starcraft_starcraft2/player_display_starcraft.lua
The argument rewriting doesn't work with the only entry point (StarcraftPlayerDisplay.InlinePlayer). None of the other modules have entry points so Class.export isn't needed.
changes for StarcraftPlayerDisplay are live
> Remove Class.export from starcraft display components

- components/match2/wikis/rainbow_six/match_summary.lua
Made the MatchSummary look more aesthetic, especially when few details are available about a map (such as lacking side scores and/or lacking operator bans).
Additionally, after merging, change the padding of `brkts-popup-body-match-sidewins` and `brkts-popup-body-match-sidewins-overtime` from `0 0 3px 3px` to `0`. This is not required, but improves the aesthetics further.
Put the changes in Module:MatchSummary/dev and ran these two brackets in Dev mode to inspect the changes.
```
{{#invoke:MatchGroup/Display|DisplayDev|id=rwtAOLMhqn}}
{{#invoke:MatchGroup/Display|DisplayDev|id=y3u6kH6rhA}}
```
The _new_ pictures in this section does not include the above mentioned padding change.
Old (minimum map information):
New (minimum map information):
Old (full map information):
New (full map …
> Improved the style of the Match Summary popout

- components/infobox/commons/infobox_team.lua
* only display achievements header if there are achievements
temporarily created the module locally on R6 (they are implementing the /Custom atm) and tested it there
> Adjust achievements display

- components/infobox/commons/infobox_team.lua
Allow to set custom variables for teams
does nothing until overwritten in the `/Custom` version
> Allow to set custom variables for teams

- components/match2/wikis/rocketleague/match_group_input_custom.lua
Properly set placements in case of double walkovers
via /dev version of the module
> Adjust placement calculation

- components/match2/wikis/rocketleague/match_group_input_custom.lua
Allow matches to be manually set as not finished via `|finished=false`
temporarily pushed to live
> [SUGGESTION] Allow matches to be manually set as not finished

- components/infobox/wikis/apexlegends/infobox_league_custom.lua
- components/infobox/wikis/starcraft2/infobox_league_custom.lua
Alternative to #699 
overwrites the liquipediatiertype wiki var on apex and sc2 so that the alias can be used
pushed to live on sc2 (module not in use yet)
Apex change is the same
> Adjust tier and tiertype vars

- components/infobox/extensions/commons/metadata_generator.lua
- components/infobox/extensions/test/metadata_generator_test.lua
- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Builds on #673 and generalizes the module to create one version for all wikis. Stacks on top of #681. Wikis only need to set `publisherdescription` in their infobox template/module. 
Note: I recommend reviewing by looking at every commit except the first. The first is just a copy, then after that I applied changes.
Also see the added test.
> Generalize metadata generation for tournaments

- components/match2/wikis/rocketleague/match_group_input_custom.lua
If `winner` is not set to `draw` (or `0`) try to calculate if we still have a draw
Calculates draw status automatically if
* the match is set as finished,
* we have exactly 2 opponents in the match,
* status of both opponents is `S` (i.e. they both have proper scores) and
* the scores of the opponents are the same
Additionally sets `winner = 0` if
* the match is set as finished,
* we have exactly 2 opponents in the match,
* status of both opponents is not `S`
* the statuses of the opponents are the same
This is only a suggestion, if you want it take it if not just close the PR^^
via /dev version of the module
> Calculate match draw

- components/infobox/wikis/apexlegends/infobox_league_custom.lua
Apex contributors want to change the link for the Pc platform and want an additional platform "console".
They also say that platform "mobile" is not needed.
see https://discord.com/channels/93055209017729024/545651077710872576/908296147007864833 (discord conversation)
Doesn't change any vars nor categories nor lpdb only the display.
Krola temporarily pushed the additional "console" platform live already.
> Adjust platforms

- components/match2/commons/match_group_util.lua
`length` is a string not a number (containing a `:`) hence the `tonumber` will always return nil, this PR fixes that
dev modules
> Fix length being parsed as number instead of string

- components/infobox/wikis/starcraft2/infobox_league_hidden.lua
Add sc2 `Template:Infobox league/hidden` implementation.
It is not really an infobox, it has no display and hence doesn't use the infobox classes.
It "only" stores into LPDB and sets wiki vars and categories.
created the module + a test template and compared data on several pages compared to the data set by the old implementation
> Add sc2 `Infobox league/hidden`

- components/match2/wikis/rainbow_six/brkts_wiki_specific.lua
Use the dev module of Brkts/WikiSpecific/Base if dev mode is available. 
Put it live
> Use dev of Brkts/WikiSpecific/Base if dev-mode is enabled

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
* Adjust sc(2) input processing order of players in teams so that the manually input is taken if entered and the variables from teamCards are only used if no manual input was given
* Rename functions to fit the new order better
/dev module and tested it via preview on a few pages (plus saving it on one page)
- lpdb data looks good
- display looks good
> Adjust sc(2) input processing order of players in teams

- components/match2/wikis/wildrift/match_group_input_custom.lua
Adjust wildrift walkover handling
* allow additional input options
* set match as finished if walkover happens
* make opponent scores always numeric (instead of sometimes having numbers as strings)
pushed live (system not live on that wiki) and tested on test page
> Adjust wildrift walkover handling

- components/match2/commons/brkts_wiki_specific_base.lua
- components/match2/commons/match_group_display.lua
- components/match2/commons/match_group_display_singlematch.lua
- components/match2/commons/match_group_input.lua
- components/match2/commons/match_group_util.lua
New display type to replace the {{ShowMatch}} template of the old bracket system. {{ShowMatch}} of old displays the custom header, together with the standard MatchSummary. Example of the old {{ShowMatch}} can be found at https://liquipedia.net/rainbowsix/Six_Major/2020/Stage_2/Latin_America/Mexico#Results 
The new display type added in this PR, called *SingleMatch*, displays the match2 MatchSummary as is. Hence it's recommended, but not required, that before using the new display type to add support for displaying the Match Score in the Match Summary (PR #704 adds that for R6 and VAL, #718 for SC and SC2).
SingleMatch is **not** a parse, storage & display like that of Matchlist and Bracket. It is only a Display Type. 
Entry point is MatchGroupDisplay.TemplateShowSingleMatch. There are two …
> Add Display Type SingleMatch

- components/infobox/wikis/halo/infobox_league_custom.lua
Adjust participantNumber display in halo infobox league as wished by halo contributors
* do not display list of teams
* move teamNumber/playerNumber up above the tier and do not display headers for them
will be done by halo contributors
EDIT: done and tested here: https://liquipedia.net/halo/Halo_Championship_Series/2021/Kickoff_Major
> Adjust participantNumber display in halo infobox league

- components/infobox/wikis/mobilelegends/infobox_item_custom.lua
Item Infoboxes for the new Mobile Legends wiki https://liquipedia.net/mobilelegends/Main_Page
The infobox is heavily based on the Custom one made for Wild Rift recently ( https://liquipedia.net/wildrift/index.php?title=Module:Infobox/Item/Custom&action=edit )
Only difference here includes few parameters (which is item stats) being replaced/added/removed and a rework on the list of categories
other than that were unchanged from the Wild Rift version.
Page tested : https://liquipedia.net/mobilelegends/Sea_Halberd
Template Infobox Item: https://liquipedia.net/mobilelegends/Template:Infobox_item
Params are appeared as tested, including the new wording on category has properly reflected the needed ones for Mobile Legends
> Create Infobox/Item for Mobile Legends

- components/match2/commons/match_group_display.lua
- standard/warning_box.lua
* Add `Module:WarningBox`
* Adjust modules that display such a warningBox, but do not use the module yet
This change will make it possible for the warningBox to be easily used in other modules
pushed the new module to live and tested the changed module via via /dev version
> Add `Module:WarningBox`

- components/match2/commons/match_summary_ffa.lua
Lua Diagnostic was throw warning here that the statement was ambiguous. Got annoyed at the constant warning in my VSCode, so decided to fix it.
Checked with warnull where the bracket was supposed to be.
> Fix lua ambiguity

- components/match2/commons/starcraft_starcraft2/match_external_links_starcraft.lua
Changes the interface of `{{MatchExternalLink}}` from
```
{{MatchExternalLink|type=vod|number=9|url=https://www.youtube.com/watch?v=ziz3dryrT0g}}
```
to
```
{{MatchExternalLink|vod9=https://www.youtube.com/watch?v=ziz3dryrT0g}}
```
It also supports multiple links now, 
```
{{MatchExternalLink
|lrthread=https://tl.net/forum/sc2-tournaments/558748-gsl-2020-code-s-ro24-group-b
|review=https://tl.net/forum/starcraft-2/558779-code-s-ro24-soo-bunny-inno-scarlett-advance
}}
```
The old interface was pretty awful... don't know what I was thinking.
https://liquipedia.net/starcraft2/Template:MatchExternalLink
> Change interface of starcraft's Template:MatchExternalLink

- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/match_group_util.lua
Depends on #533 
`bracketData.lowerEdges` is a replacement for `bracketData.lowerMatches`. The main difference is that `bracketData.lowerEdges` is a many to many mapping between a match and its lower matches. It directly encodes the connector lines that appear in the bracket. 
`lowerEdges` is an array of
```
{
opponentIx,
lowerMatchIx,
}
```
The new `lowerEdges` structure enables many configurations that were not possible previously:
- lower match without connector
- single lower match advancing into two opponents
- two lower matches advancing into one opponent
- crossing of wires: first lower match advancing into second opponent, and second lower match advancing into first opponent
Use https://liquipedia.net/starcraft2/Liquipedia:BracketUpdate/Tests/Bracket_Layout
> [coords1] Add bracketData.lowerEdges

- standard/error.lua
- standard/error_display.lua
- standard/error_ext.lua
```
Error is a minimal error class, whose purpose is to allow additional fields to be
attached to an error message string. It has only one method, the __tostring
metamethod, and one required field, error.message.
The class is intended to be open, meaning that its fields are all public and
can be used for any purpose. By convention, the following fields have specific
meanings:
error.message: A short error message describing the error. (Required)
error.stacks: The stack traces of the error. The first stack trace is the one
last thrown. Subsequent stack traces are from when the error was rethrown by an
error handler handling the same error. error.stacks can be set to nil if it is
not needed, or for performance.
error.originalErrors: When an error handler throws (not a rethrow), the original …
```
> [try1] Add Module:Error, Module:Error/Ext, Module:Error/Display

- components/infobox/commons/infobox_team.lua
- components/infobox/wikis/halo/infobox_team_custom.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Normalize the input values of location and location2. 
Two of the three wikis using standardised team infobox does this already in custom's (sc2 & halo), while the 3rd (rl) has no queries looking at lpdb_team.location. 
The implementation uses Module:Flags function CountryName(). That function converts a country name, flag code, or alias to a standardized country name.
Examples on how the normalization/standardization work:
- uk -> United Kingdom
- eu -> Europe
- fRanCe -> France
- Holland -> Netherlands
Starcraft2 & Halo wikis already do this. It would be an addition for Rocket League, but as previously said, Rocket League have no identified dependencies on the field. 
SC2: Tested by hjp (sandboxes)
Halo: Tested by me on Liquid using sandboxes
RL: Tested by me on G2 & FaZe using …
> Normalize location and location2 before saving to lpdb (Infobox Team)

- standard/date_ext.lua
Functions for working with dates strings and instants.
An instant is a datetime represented as a number of seconds since UNIX epoch.
Usage
```
DateExt.readInstant('2021-10-17 17:40 <abbr data-tz="-4:00">EDT</abbr>')
-- Returns 1634506800
DateExt.formatInstant('c', 1634506800)
-- Returns 2021-10-17T21:40:00+00:00
```
```
DateExt.readInstant('2021-10-17 17:40 <abbr data-tz="-4:00">EDT</abbr>')
-- Returns 1634506800
DateExt.formatInstant('c', 1634506800)
-- Returns 2021-10-17T21:40:00+00:00
```
> Add Module:Date/Ext

- components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
- components/match2/commons/starcraft_starcraft2/opponent_display_starcraft.lua
Display scores in SC/SC2 MatchSummary headers if enabled (e.g. the `SingleMatch` display (added with #719 for sc2) will have it enabled)
dev modules
> Add option to display scores in SC/SC2 MatchSummary headers

- components/infobox/commons/infobox_team.lua
stacked on #708 
Set location category for teams. The old infoboxes set those categories, the new ones do currently not set it
via sandbox on sc2
> Set location category for teams

- components/infobox/commons/infobox_person.lua
stacked on #728 
Standardize the lpdb values of nationality, nationality2 and nationality3.
Display a Warning Box if the entry is not supported.
The implementation uses function `CountryName()` of `Module:Flags`. It converts a country name, flag code, or alias to a standardized country name.
temporarily created the module on sc2
> Standardize nationality storage

- components/hidden_data_box/commons/hidden_data_box.lua
* catch args == nil
* make basepagename a string (it is treated as a table by gsub otherwise)
pushed live (module not in use yet) and used it on a page on sc2
> Fix HiddenDataBox bugs

- components/match2/commons/get_match_group_copy_paste.lua
- components/match2/commons/get_match_group_copy_paste_wiki_base.lua
- components/match2/commons/starcraft_starcraft2/get_match_group_copy_paste_starcraft.lua
Add CopyPaste Generator support for SingleMatch
Usage mostly via https://liquipedia.net/starcraft2/Special:RunQuery/SingleMatchCopyPaste (Form to be added on other wikis too)
per sandbox and then pushed live
> Add CopyPaste Generator support for SingleMatch

- components/match2/wikis/wildrift/match_summary.lua
Center Game.length display vertically via css class
```css
.brkts-popup-body-element-vertical-centered {
display: flex;
align-items: center;
}
```
pushed live (match2 system not in use on that wiki)
> Center Game.length display vertically

- components/earnings/commons/earnings_base.lua
Sadly atm we have a bunch of different TeamCards on the wikis.
Some of the teamCards store the players pages with undersocres replacing spaces, some use spaces instead of underscores.
> `PlayerA_(unique_identifier)` vs `PlayerA (unique identifier)`
To resolve this issue this PR adjusts the query conditions so that they fetch data for both cases.
via Sandbox
> Adjust earnings to allow differently stored player pagenames

- components/squad/squad_row.lua
Builds on #636 and implements support for "special" teams, like "retired" which if enabled by the wiki will call the template `{{Team/retired}}`, etc
Tested in sandbox
> Add support for special teams

- components/match2/commons/match_group_display_helper.lua
Adjust default criteria for MatchSummary popup
used like that (modulo a check against default date) on most wikis
> Adjust default criteria for MatchSummary popup

- components/match2/commons/match_group_coordinates.lua
Depends on #555 and #556
Adds `Module:MatchGroup/Coordinates` which computes a bunch of fields that describe where a match is relative to the rest of the bracket. Specifically:
```
coords.matchIndexInRound: Index of the match within the round containing it.
coords.rootIndex: Index of the root whose tree contains the match.
coords.roundCount: Number of rounds in the bracket.
coords.roundIndex: Index of the round containing the match.
coords.sectionCount: Number of sections in the bracket.
coords.sectionIndex: Index of the section containing the match. (0=upper, 1=lower for double elim)
coords.semanticDepth: 1 for Finals, 2 for Semi-finals, 3 for Quarterfinals, etc. 0 for Grand Finals.
coords.semanticRoundIndex: Index of the round, skipping rounds that have no matches in the section.
``` …
> [coords4] Add Module:MatchGroup/Coordinates

- standard/stream_links.lua
Streaming specific subset of Module:Links
StreamExt.readCountdownStreams can be used to extract the streaming platform args from an argument table for use in
Module:Countdown.
used by starcraft's GroupTableLeague
https://liquipedia.net/starcraft2/Liquipedia:BracketUpdate/Tests/DH_NA
> [pl6] Add Module:Stream/Ext

- components/match2/commons/match_group_display_helper.lua
- components/match2/commons/opponent.lua
```
Structural type representation of an opponent.
Examples:
{type = 'solo', players = {displayName = 'Neeb'}}
{type = 'team', template = 'alpha x 2020'}
{type = 'literal', name = 'B2'}
See Opponent.isOpponent for the exact encoding scheme and required fields.
- For opponent display components, see Module:OpponentDisplay.
- For input from wikicode, use {{1Opponent|...}}, {{TeamOpponent|...}} etc.
- Used by: PrizePool, GroupTableLeague, match2 Matchlist/Bracket,
StarcraftMatchSummary
- Wikis may add additional wiki-specific fields to the opponent representation.
```
For reference: StarcraftOpponent adds support for isArchon to party types.
https://liquipedia.net/commons/Module:Opponent/Starcraft
Used by dev versions of starcraft's PrizePool and GroupTableLeague
> [pl4] Add Module:Opponent

- components/infobox/wikis/rocketleague/infobox_league_custom.lua
- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/valorant/match_group_input_custom.lua
Removing the legacy handling of tiers in Rocket League. This means dropping extradata.tier2 and not writing the tiertype into tournament.tier.
https://liquipedia.net/rocketleague/index.php?search=insource%3A%22liquipediatier%3DMonthly%22&title=Special%3ASearch&profile=default&fulltext=1
https://liquipedia.net/rocketleague/index.php?search=insource%3A%22liquipediatier%3DWeekly%22&title=Special%3ASearch&profile=default&fulltext=1
https://liquipedia.net/rocketleague/index.php?search=insource%3A%22liquipediatier%3DQualifier%22&title=Special%3ASearch&profile=default&fulltext=1
Bot should change these 175 tournaments from `|liquipediatier=Qualifier|liquipediatier2=...`  to `|liquipediatier=...|liquipediatiertype=Qualifier`. The format with tiertype in the wikicode is widely used outside these …
> Remove special tier handling in RL Infobox League

- components/match2/wikis/valorant/big_match.lua
- components/match2/wikis/valorant/match_summary.lua
Changes:
* Fixed parsing of data (previously causing lua errors)
* Fixed field with wrong name (previously causing lua errors)
* Added Stats and Economy into tabs of their own
* Fixed the two countdowns
* Automatically fetch patch and tournament name from tournament link
* MatchSummary null pointers fixed
https://liquipedia.net/valorant/VoganRL/Matches
https://liquipedia.net/valorant/Match:ID_c0gBtlJP3i_R01-M001
https://liquipedia.net/valorant/Match:ID_c0gBtlJP3i_R01-M002
> Valorant - Improve BigMatch

- components/match2/commons/match_group_display_helper.lua
`DisplayHelper.makeOpponentHighlightKey` and `Opponent.toName` serve a similar purpose: to convert a opponent to a string key. Only one is needed.
sc2 tournament test pages
> Use Opponent.toName for highlight key

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
- components/infobox/wikis/starcraft2/infobox_league_hidden.lua
Remove Legacy Date Vars for SC2 in
* `Module:Infobox/League/Custom`
* `Module:Infobox/League/Hidden`
The usage of those vars has been removed on all sc2 modules.
For commons Modules that are used on SC2 they were changed so that they use the new ones (if they exist) and use the legacy vars as a fallback.
pushed to the modules (these Modules are not yet used on live) and checked display and storage data on a few pages when using is on them (temporarily)
> Remove Legacy Date Vars for SC2

- standard/vod_link.lua
Add `Module:VodLink` as a module version of `TemplateVodlink` which exists on quite a few wikis:
> Add `Module:VodLink`

- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/match_group_util.lua
If `match2bracketdata.upperMatchId` is present in lpdb, then use that instead of computing it in MatchGroupUtil.
Tested as a part of #753
> [coords5c] Read upperMatchIds from lpdb

- components/match2/commons/player_display.lua
- components/match2/commons/starcraft_starcraft2/player_display_starcraft.lua
Add dq options to `PlayerDisplay.BlockPlayer` and `StarcraftPlayerDisplay.BlockPlayer`, for parity with `InlinePlayer`
https://liquipedia.net/starcraft2/Liquipedia:Gallery/ParticipantTable
> Add dq options to BlockPlayer

- components/match2/wikis/valorant/big_match.lua
Automatically retrieve Tournament Link for Big Match via the Tournament Match, so that less fields needs to be filled in manually by editors.
Live as Big Match is not gone gold yet.
https://liquipedia.net/valorant/index.php?title=Match%3AID_c0gBtlJP3i_R02-M001&type=revision&diff=373764&oldid=373457
> Automate Tournament Link for Big Match

- components/infobox/wikis/mobilelegends/brkts_wikispecific.lua
Module:Brkts/WikiSpecific for Mobile Legends
This is basically the #746 but that was for Wildrift, this one is for ML.
the only thing that was changed here is the .png image file.
pushed to live (already in use)
> Add Brkts/WikiSpecific for Mobile Legends

- components/infobox/commons/infobox_person.lua
- components/infobox/wikis/starcraft2/infobox_person_commentator.lua
- components/infobox/wikis/starcraft2/infobox_person_player.lua
Fix a bug with LPDB storage of earnings if a CUSTOM earnings functions is used
sandbox + pushed to live afterwards
only affects sc2 (all other wikis either do not yet use the module or do not have a custom earnings function)
> Fix custom earnings bug for infobox player

- components/infobox/wikis/ageofempires/infobox_league_custom.lua
* Remove tournament_tier2, tournament_tiertype2 vars (not used on AoE)
* correct wrong setting of tournament_tier (was set in RL style)
* Searched for occurrences where tier2, tiertype2 are set on AoE (none)
* Usage of `tournament_tier` was already replaced by `tournament_liquipediatier` in all Modules/Templates on AoE, fixing wrong content only for consistency.
> Fix variables in `Module:Infobox/League/Custom`

- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Add option to store a list of sub/accademy teams to extradata
We want to use that list in some placement queries so that the placements of accademy/sub teams are also counted for the current team.
via sandbox and after that temp pushed to live
> Add option to store a list of sub/accademy teams to extradata

- components/infobox/wikis/ageofempires/infobox_league_custom.lua
* Create error when unknown game is set (cannot be allowed since most lookups will be broken).
* Add tracking category for unknown game mode.
* Rename cell "Game version" to "Game & Version"
Tested in a [sandbox on AoE](https://liquipedia.net/ageofempires/Module:SyntacticSalt/sandbox2)
> Add tracking category and error in `Module:Infobox/League/Custom` on AoE

- components/match2/wikis/valorant/big_match.lua
Split the Eco Charts into first half, second half and OT, as the chart is only intended to be used with at most 12 rows.
Also mapped the input 'detonate' to 'explosion' as the two extensions don't agree on what it should be called (yet).
Live
> Improve Economy Tab of BigMatch

- components/match2/commons/match_group_coordinates.lua
- components/match2/commons/match_group_display_bracket.lua
- components/match2/commons/match_group_util.lua
Read match coordinates from lpdb if it is present. Otherwise compute it in MatchGroupUtil. The bracket.sections and bracket.rounds arrays aren't directly stored in lpdb so they need to be rebuilt from the coordinates data.
> [coords5d] Read coordinates from lpdb

- components/match2/wikis/valorant/big_match.lua
* Removed workaround that was in place due to Chart and API Ext not agreeing on name (they now agree on name)
* Fixed typo (had `Table` instead of `table`)
* Removed unused parameter in function call
Live https://liquipedia.net/valorant/Match:ID_c0gBtlJP3i_R02-M001
> [BigMatch] Code Cleanup

- components/infobox/wikis/starcraft2/infobox_league_hidden.lua
Avoid using string.lower with nil
pushed live (module not YET in use, go live planned today)
> Avoid `string.lower(nil)`

- components/match2/commons/match_group_util.lua
`match2bracketdata.bracketsection` is replaced with `match2bracketdata.coordinates.sectionIndex`.
`match2bracketdata.rootindex` is replaced with `match2bracketdata.coordinates.rootIndex`.
> [coords5g] Remove deprecated fields

- components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
FFAMatchSummary has its own showScore default, so the showScore default handling should be moved to a code path specific to non-FFA MatchSummary.
live modules
> Fix config.showScore handling in starcraft MatchSummary

- components/infobox/commons/infobox_league.lua
Make type a customizable cell in infobox league, so that it can be overwritten on sc2 (we have an additional type "Online/Offline")
doesn't change anything, except that it will be overwritable
sandboxes on sc2
> Make type a customizable cell in infobox league

- components/match2/wikis/rainbow_six/match_legacy.lua
Incorrect statement would always use opponent.score instead of using fallback (0) when it should have.
Put it live
> Match2->Match1: Fix incorrect score handling

- components/infobox/commons/infobox_league.lua
From #839.
This category is used on serveral (most?) wikis using the legacy templates.
Also changed the upper first, to use a built in function, instead of using substrings.
> Add Online/Offline Tournament Category

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
Adjust function `_cleanPrizeValue`.
Due to several bot runs over the last days (which cleaned up `prizepool` and `prizepoolusd` entries in `infobox league`) some of the cleanup regex replacements are not necessary anymore, hence this PR removes them.
pushed live (module not in use), tested it on a few pages (preview + save, check lpdb and revert again)
> Adjust function `_cleanPrizeValue`

- components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
stacked on #840 
Currently the SC2 MatchSummary has
- the same striped background for the veto header and the first veto
- the same striped background for the last veto and the casters information
This PR changes that and gives each of them its own row and hence changing striped backgrounds
before:
after:
`/dev` module + previews
> Adjust sc2 MatchSummary veto & Caster Display

- components/infobox/wikis/wildrift/infobox_item_custom.lua
Wild Rift recently changed Upgraded items to Top-Tier items, so this change does that. For the maps, "Summoner's Rift" simply was the wrong name for the map. I changed the link and the parameter `sr` to `wr`.
- Does this break LPDB on any of the wikis?
- No.
- Are all needed page variables still set?
- Yes.
- Does this break SMW on any of the wikis?
- No.
> Added "top-tier" category and changed maps.

- components/infobox/commons/infobox_league.lua
Use `Module:ReferenceCleaner` instead of `gsubs` in a custom function in `Infobox league`
temporarily created the module on sc2 and edited it there (sc2 does not yet use the standardized infobox league modules)
tested it with full, and partial (`-??` or `-XX`) dates
> use `Module:ReferenceCleaner` in function `League:_cleanDate`

- components/infobox/wikis/starcraft2/infobox_map_custom.lua
Store creators redirect-resolveded for maps
Pushed to live temporarily.
LPDB Data is changed as intended.
> Resolve redirects for creators in maps

- components/infobox/extensions/commons/age.lua
Remove `earliestPossibleBirthDate >= os.time(_EPOCH_DATE) condition due to there existing people on the wikis that are born before 1970.
e,g,: https://liquipedia.net/starcraft2/SirScoots
sandbox on sc2
> Remove `birthdate >= _EPOCH_DATE` condition

- components/match2/commons/match_group_input.lua
- components/match2/commons/match_group_util.lua
This change fetches the new `bracketData` fields (`lowerMatchIds` `lowerEdges` `upperMatchId` and `coordinates`) in the match input processing pipeline so they can be stored in lpdb along with the reset of the match. 
- `lowerMatchIds` and `upperMatchId` are stored in lpdb. They fetched from the bracket template if available (i.e. recently purged). Otherwise they are computed.
- `lowerEdges` is stored in lpdb. It is computed unless it is specified during input spec processing.
- `coordinates` is fetched from the bracket template. It is not computed if the bracket has not been purged to include coordinates data. It is then stored in lpdb.
- `advanceSpots` is more complicated so I have left it out for now. I'll leave lpdb storage of `advanceSpots` some other time. 
Starcraft 2 tournament …
> [coords6] Save new bracketdata fields to lpdb

- components/match2/commons/match_group_util.lua
Add `MatchGroupUtil.indexTableToRecord`
`MatchGroupUtil.indexTableToRecord` was accidently left out of #559. It wasn't caught previously because coords6-coords8 were intended to be merged as a whole, and so coords6 wasn't tested independently.
live modules
> Add MatchGroupUtil.indexTableToRecord

- components/infobox/commons/infobox_team.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Unify earnings display between team and person infoboxes
N/A (only chnages displayed text, no actual changes to functionality)
> Unify earnings display between team and person infoboxes

- components/earnings/commons/earnings_base.lua
Round earnings to integer instead of 2 decimals
sandbox on sc2, works as intended
> Round earnings to integer instead of 2 decimals

- components/match2/wikis/rainbow_six/match_legacy.lua
This is a pull request to add more available data to the API, so links to VoDs, SiegeGG pages and r6esports pages can be retrieved automatically by people that want to use those. It also changes streams handling to use `parseIfString` from the json module.
I tested this change by looking at the SMW data of EUL 2021 Stage 3 matches, like [this one](https://liquipedia.net/rainbowsix/Special:Browse/:European-20League-2F2021-2FStage-203-23legacymatch-5FuUYjvppIot-5F0001).  Since this doesn't edit existing data there should be no issues (besides the process for dealing with `match.stream`, but was done by Rathoz so I assume it doesn't generate issues).
> Add links to VOD, SiegeGG and r6esports.br to SMW match

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Switch SC(2) Match Input Processing to use the new standard date vars.
As a preparation both infoboxes on SC (old template version) and SC2 (new standardized version) now additionally store the new (standard) date variables `tournament_startdate` and `tournament_enddate`.
/dev module
> Switch SC(2) Match Input Processing to use the new standard date vars

- components/infobox/wikis/starcraft2/infobox_person_commentator.lua
- components/infobox/wikis/starcraft2/infobox_person_player.lua
Adjust SC2 `adjustLPDB` functions in `Infobox/Person/Player` and `Infobox/Person/Commentator` so that they add to extradata instead of overwriting it.
This ensures that the earnings by year that are set via the commons module are still present when storing to LPDB.
pushed to live, works as intended now
> Adjust SC2 `adjustLPDB` functions in `Infobox/Person/...`

- components/infobox/wikis/ageofempires/infobox_league_custom.lua
* Add missing information regarding voobly and gameversion to LPDB (Was not added in the old infobox, but is now needed to correctly determine the Game and Version.)
* Also set variables to be able to re-add information in case of overriden extradata.
Tested by manually calling the parser function to set these values.
> Add game version to LPDB in `Module:Infobox/League/Custom` on AoE

- components/infobox/wikis/starcraft2/infobox_person_commentator.lua
- components/infobox/wikis/starcraft2/infobox_person_player.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
* round values to integers instead of with 2 decimals
* switch round function in infobox team to use the Math module instead of having the same function in the module
temp pushed live
> Adjust SC2 Earnings Display for teams and persons

- components/infobox/wikis/wildrift/infobox_item_custom.lua
Fixing a bad argument error as reported in Discord (solution from HJP) 
Change was implemented by HJP on the Wiki module: https://liquipedia.net/wildrift/index.php?title=Module%3AInfobox%2FItem%2FCustom&type=revision&diff=83504&oldid=82663
> Fixing Wild Rift Infobox Item bad argument error 

- components/infobox/wikis/rocketleague/infobox_unit_car.lua
RL infobox car implementation was missing the Injector:parse function, hence so e stuff got lost when calling the injector. This PR adds the Injector:parse function (which does nothing).
pushed live
> Fix RL Infobox car

- components/earnings/wikis/halo/earnings.lua
- components/earnings/wikis/valorant/earnings.lua
Update default players per team sizes for Valorant and Halo to match reality.
> Earnings - Update default players per team

- components/match2/commons/get_match_group_copy_paste_wiki_base.lua
wikiCopyPaste._getOpponent already uses literal. Adding it in allowed modes so that doesn't need to get overwritten by wiki-customs.
N/A
> Add Literal as allowed mode in CopyPasta/Base

- components/infobox/commons/infobox_league.lua
Add the option to display warnings in Infobox/League. For example for incorrect values.
Tested together with #707 in sandbox on R6
> Add option to display Warnings in Infobox/League

- components/match2/commons/bracket_template.lua
- components/match2/commons/match_group_util.lua
Bracket templates (e.g. Template:Bracket/8) now compute bracket coordinates (see #557) and stores them to lpdb. Brackets using the bracket templates can then avoid computing the bracket coordinates themselves.
**Additional changes**
- A few additional fields are stored: `bracketData.lowerMatchIds`, `bracketData.upperMatchId`, and `bracketData.lowerEdges`
-  `bracketData.rootIndex` is deprecated and no longer stored
- bracketData fields in lpdb now use the right type: numbers are encoded as JSON numbers instead of strings, and unspecified values are left out instead of using the empty string.
- For ease of merging the new code is in a new module `Module:MatchGroup/Template`. The old `Module:TemplateMatch` will be removed after the templates using them have been switched over.
**LPDB …
> [coords7] Store bracketData.coordinates in lpdb for bracket templates

- components/infobox/wikis/rainbowsix/infobox_league_custom.lua
After going live with #707, two issues have been spotted.
* Publisher tier not checked for nil before doing lower and not checked for being a valid tier
* Platform lookup in category creation was incorrectly calling game lookup.
Live
> Fix two issues with #707

- components/infobox/wikis/rainbowsix/infobox_league_custom.lua
* Set the tiertype to 'General' if omitted. R6 modules expects this. \(See also https://discord.com/channels/93055209017729024/874304000718172200/888079423771910194\)
* Make the platform link to the Category based on editor feedback
Tested live
> Improve R6 Infobox League

- components/notability/commons/notability_checker.lua
It's fairer if the notability points drop off occurs when it's been a year instead of occuring every Calender New Year. 
R6 is already using this methods. Asked RL, and they liked it too. As far as I know those are the only two wikis using dropoff today.
> Change notability dropoff to placement date instead of on new years

- components/infobox/commons/infobox_person_user_custom.lua
- components/infobox/wikis/dota2/infobox_person_user_custom.lua
- components/infobox/wikis/halo/infobox_person_player_custom.lua
- components/infobox/wikis/overwatch/infobox_person_user_custom.lua
- components/infobox/wikis/rocketleague/infobox_person_player_custom.lua
Move/Rename `Infobox/Person/...` modules to `Infobox/Person/.../Custom`
N/A
please move the according modules before merging, so that we do not duplicate them
feel free to ping me and let me do the chore, but it has to be coordinated
also adjust the invokes in the according templates so it will not error
> Move/Rename Infobox Person modules to `.../Custom`

- components/match2/wikis/wildrift/match_group_input_custom.lua
Adjusting Module MatchGroup Input (Custom) Module for Wild Rift **match2** implementation
These are basically #754 which has been already merged, both Wild Rift and Mobile Legends shared the same basis that is interchangeable
Necessary small changes were made including 
- wiki labelling
- HeroNames changed to ChampionNames
- Trovo and Huya was added into the stream section, as these two platform has never been used in Mobile Legends, but does use actively in Wild Rift
Pushed Live, all parts are intact including Wild Rift-specific stuff such as Recent Matches, Recent Champion Matches and matchticker (stuff that still currently relies on a set of legacy info)
> Adjusting MatchGroup/Input/Custom for Wild Rift

- components/match2/commons/match_group_input.lua
Populates `match2.match2bracketdata.groupRoundIndex`. 
`groupRoundIndex` is the round containing the match, inside the group table league that the match belongs to. It is automatically parsed out of `{{MatchSection|Round 5}}` or `{{MatchSection|Day 5}}`. It can also be set on individual matchlists and matches with `{{Matchlist|round=5}}` or `{{Match|round=5}}`.
`groupRoundIndex` is intended to provide an alternative method of specifying rounds in a GroupTableLeague that does not involve sdate/roundNedate. `groupRoundIndex` can be also used to override the round number of individual matches for a sdate/edate based GroupTableLeague.
**Push instructions:** Please notify @warnull before push so a quick final test can be performed.
https://liquipedia.net/starcraft2/Liquipedia:BracketUpdate/Test …
> [coords11] Store match2bracketdata.groupRoundIndex

- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Add "Disbanded Teams" category for sc2 infobox team.
Using the /Custom version for this, because atm most wikis do not have the category:
pushed live
> Add "Disbanded Teams" category

- components/match2/wikis/rainbow_six/legacy/match_group_legacy_default.lua
* Add `team` as default bracketType.
* Add `details` suffix to the details automatically.
Also changed quotes to be single quotes in order to me more consistent with other modules (separate commit).
This handling was put live over Christmas, is expected to be used by some legacy brackets. Because the module at the time wasn't on the repo (just in a chore PR #831 ), updating the PR was forgotten.
Live
> Improvement to Legacy/Default

- standard/links/wikis/rocketleague/links_custom_data.lua
Adjust `steam` link for rocketleague as requested by tino
pushed live
> Adjust `steam` link for rocketleague

- components/infobox/wikis/halo/infobox_map_custom.lua
Correcting the file path for the module in the comment header. Also removing one of the two `function CustomMap:createWidgetInjector()
return CustomInjector()
end`
Untested. However the module at the desired file location already exists. Will archive the Module Infobox/Map once merged
> Fix Header for Halo Map Infobox

- components/match2/wikis/mobilelegends/match_summary.lua
The previous matchsummary that was merged (#752) didnt include the feature to support historical icon switches for heroes who had icon changes in the past, so this one just simply add that into it
https://liquipedia.net/mobilelegends/User:Hesketh2/sandbox
> Adding Icon switches in MatchSummary for Mobile Legends

- components/match2/commons/matches_schedule_table.lua
- components/match2/commons/matches_table.lua
- components/match2/commons/starcraft_starcraft2/matches_table_starcraft.lua
Add match2 implementation for `Module:Bracket matches table`
via sandboxes
SC2:
(data from: https://liquipedia.net/starcraft2/ESL_Pro_Tour/2021/22/Masters/Last_Chance)
RL:
(data from: https://liquipedia.net/rocketleague/Crimson_Wings/Womens_Car_Ball_Championship/Season_4)
> Add match2 implementation for `Module:Bracket matches table`

- components/match2/commons/brkts_wiki_specific_base.lua
- components/match2/commons/match.lua
- components/match2/commons/match_group_input.lua
- components/match2/commons/match_group_legacy.lua
- components/match2/commons/match_subobjects.lua
- components/match2/wikis/brawlstars/match_group_input_custom.lua
- components/match2/wikis/halo/match_group_input_custom.lua
- components/match2/wikis/rainbow_six/match_group_input_custom.lua
- components/match2/wikis/rocketleague/legacy/legacy_match_list.lua
- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/splitgate/match_group_input_custom.lua
- components/match2/wikis/starcraft/brkts_wiki_specific.lua
- components/match2/wikis/starcraft2/brkts_wiki_specific.lua
- components/match2/wikis/valorant/match_group_input_custom.lua
- components/match2/wikis/wildrift/match_group_input_custom.lua
This changes opponent processing to be done at the same time as match processing, instead of in a previous stage. The approach is the one taken by starcraft/starcraft2. This PR changes all wikis to use that approach.
The advantage of the starcraft approach is that:
- Opponent processing is all in lua instead of half template half lua.
- The match2 opponent notation is no longer tied to `{{Match}}` contexts. This makes match2 opponent notation available in other components like GroupTableLeague, PrizePool and OpponentList.
- By making use of Opponent.readOpponentArgs, the input of duo/trio/quad opponent types are automatically enabled in match2 wikis.
- The code flow is much simpler, by using a single entry point and avoiding indirections like `WikiSpecific.processOpponent`.
- The new code …
> [pl8] Combine opponent and match input processing

- components/automatic-points-table/commons/automatic-points-table.lua
- Automatic Points Table is a table that automatically fills in its points from tournaments' prize pool templates.
- This is the first of many pull requests that will build up to the fully functional module.
- This was deployed in Module Sandbox here: https://liquipedia.net/rocketleague/Module:Sandbox/AutoPointsTable/Rewrite/GH/1
- **mw.logObject()** is used to view the constructed dictionaries that represent the extracted position background and tournaments data
In the following image, the **pbg** dictionary is surrounded by a **red** square, while the **tournaments** dictionary is surrounded by a **blue** square
> Extracting position bg and tournaments data

- components/notability/commons/notability_checker.lua
- components/notability/wikis/rocketleague/notability_checker_config.lua
The current NotabilityChecker only queries the database with the prefix `p` in lpdb_placement.players. However many wikis insert both the prefixes `p` and `c`, the latter being used coaches. 
For example:
R6: https://liquipedia.net/rainbowsix/Special:LiquipediaDB/Six_Invitational/2022/Asia_Pacific#placement
Dota2: https://liquipedia.net/dota2/Special:LiquipediaDB/I-League/2021/2#placement (check the second entry, not the first)
CS: https://liquipedia.net/counterstrike/Special:LiquipediaDB/PGL/2021/Stockholm#placement
Apex: https://liquipedia.net/apexlegends/Special:LiquipediaDB/Apex_Legends_Global_Series/Championship/North_America/2021#placement (second entry)
League: https://liquipedia.net/leagueoflegends/Special:LiquipediaDB/VCS/2021/Winter#placement
This PR would add support to the …
> Add support for fetch results as coach

- components/notability/commons/notability_checker.lua
* As Rocket League no longer uses tier2, the entire special handling for tier2 is removed.
* Removed unused private function
Put it on /dev. 
* On R6 made the Template invoke the /dev module. 
* On RL compared the output of `require('Module:NotabilityChecker').run{player1='Talon'}` and `require('Module:NotabilityChecker/dev').run{player1='Talon'}` which were identical.
> Remove unused code

- components/match2/wikis/arenaofvalor/brkts_wikispecific.lua
I have decide to work on implementing Match2 for **Arena of Valor**, another Mobile MOBA to have all Mobile MOBA had match2 installed (the others are **Mobile Legends** and **Wildrift**)
AOV will inherit the necessary match2 modules that is from **Mobile Legends** which is almost near-perfect identical in terms of setups 
Pushed Live, with https://liquipedia.net/arenaofvalor/Arena_of_Valor_Bangladesh_Championship/2021/Qualifiers/Khulna as the first live page to use match2 brackets
**I have notice that there isn't **arenaofvalor** folders in the match2 section yet, I dont know how to create one so I'll will pause other module PRs (MatchGroup, MatchSummary, Legacy) so that the folder can be created, then I can put the rest up later**
> Add Brkts/WikiSpecific for Arena of Valor

- components/match2/wikis/rainbow_six/match_legacy.lua
R6's match1 saves unredirected teamtemplate pages in Match1 opponents. 
#763 added resolve redirect on the match2 `name` (pagename) field. 
This PR adds an extra step in the Match1 handling to save the unresolved pagename.
Tested live
> Fix Match1 issue on R6 after #763

- components/match2/commons/match_summary_base.lua
- components/match2/wikis/mobilelegends/match_summary.lua
- components/match2/wikis/rainbow_six/match_summary.lua
- components/match2/wikis/splitgate/match_summary.lua
- components/match2/wikis/valorant/match_summary.lua
- components/match2/wikis/wildrift/match_summary.lua
Wikis keep duplicating these two functions. Move them to /Base. A wiki can still use their own function if they have a need for it.
Tested successfully with /dev
> Extract createOpponent and createScore to MatchSummary/Base

- components/match2/wikis/mobilelegends/match_legacy.lua
Add legacy storage for Mobile Legends, while ML is a wiki that made post-Match2 was formed, Legacy is still needed for some storage stuff
These are a direct copypaste from Wild Rift's newest version, which incorporate changes from #763 (the original revision, #724 is already merged as well)
Using the similar test method on #724  - https://liquipedia.net/mobilelegends/User:Hesketh2/sandbox
(as of 2:14AM UTC+8 on January 8 if things look weird that is because Mobile Legends has to wait until #927 was merged)
> Add Legacy storage modules for Mobile Legends

- components/match2/wikis/overwatch/brkts_wiki_specific.lua
Adding the Match Summary module for the Overwatch wiki using match2. Display is incredibly similar to Halo 
All changes tested here: https://liquipedia.net/overwatch/User:Fenrir.SPAZ/Sandbox
> Create Wiki Specific Brkts for OW

- components/notability/wikis/rainbowsix/notability_checker_config.lua
Remake of #893 due to bad rebase (I did `git rebase main notability-add-r6` - what should I've done instead?).
Create Notability Config for R6, so that the legacy module can be retired and the Standardized Notability Checker be used instead.
New module, tested live
> Add Notability Config for R6

- components/match2/wikis/mobilelegends/match_legacy.lua
Porting Changes from the Arena of Valor version, also known as  #935
ML has the same issue that the hero statistics module cannot registered heroes, they does recognize a match however
difference here is ML does not have old bracket system to begin with, so I try to cross-porting the AoV one and the module does worked.
So I'm consider cross-port this to ML, and when both are merged than I can try backport this to WR to see if things are good
Pushed Live
Would be better to get this merged first, because legacy was already on the git so to prevent rollback (while AoV is not on the git yet)
> Adjusting Legacy Module for Mobile Legends

- components/hidden_data_box/wikis/ageofempires/hidden_data_box_custom.lua
Migrate the HiddenDataBox to be commons- and LPDB-based.
Tested by calling the Module/Sandbox instead of the old template on pages where it is used, e.g.
https://liquipedia.net/ageofempires/Visible_Cup/4/Swiss_Stage/Round_1-2 or https://liquipedia.net/ageofempires/AOElympics/2020/1v1/Hideout
> Add HiddenDataBox for AoE

- components/infobox/commons/infobox_person.lua
This change is used for players/people who have an official ID in non-roman characters.
Link towards discord messages on the topic.
https://discord.com/channels/93055209017729024/268719633366777856/928038413452599328
dev modules (commons + sc2)
> Update Infobox to allow "local/native" ID in Subheader

- standard/flags.lua
- standard/flags_master_data.lua
Adjust `Module:Flags` and `Module:Flags/MasterData` so that they enables the usage of language flags.
* Language flags can now be displayed via function `LanguageIcon`
* * It first converts language values to keys that then can be used by the `Icon` function
* Enable iso key retrieval for language flags
* Add necessary table entries to `Module:Flags/MasterData` for that
This also removes the `Pages with unknown flags` Category for the added language flags if this module is used.
sandboxes on sc2
Via function `CountryCode` we could easily store all flags as alpha2 isos (or language isos) as long as they have an iso
(else it returns `''`)
(also has support for alpha3 iso for country flags via the format variable/param)
> Enable language flags

- components/match2/commons/match_group_legacy.lua
- components/match2/wikis/starcraft/legacy/match_group_legacy.lua
- components/match2/wikis/starcraft2/legacy/match_group_legacy.lua
Adjust Legacy Bracket MatchGroup calls to use the intended calls instead of the deprecated functions
dev modules
> Adjust Legacy Bracket MatchGroup calls

- components/match2/wikis/starcraft2/legacy/match_maps_legacy_store.lua
Adds the SC2 (1v1) implementation that is called from `Template:Legacy Match list start` and `Template:Match list end`.
The later also stores the matches into match2.
is live (for several months)
> SC2 Legacy Match list - Part 2

- components/match2/wikis/rocketleague/legacy/legacy_match_list.lua
- components/match2/wikis/starcraft2/legacy/legacy_player_cross_table.lua
Adjust Legacy Matchlist MatchGroup calls to use the intended calls instead of the deprecated functions
dev modules (on sc2 pushed live)
> Adjust Legacy Matchlist MatchGroup calls

- components/infobox/commons/infobox_map.lua
Adding Release date and Game as default parameters
Adds 2 new default parameters for the Map Infobox, that being the maps release date, and the game the map is used for. 
**EDIT:** Game/Game Version removed from this PR. Further conversations are needed
Tested on Commons. Page was created in Userspace and moved to Mainspace. LPDB output shown below on the Mainspace version. Following the test, the page was moved back to https://liquipedia.net/commons/User:Fenrir.SPAZ/Sandbox
> Adding default parameters for Infobox Map

- components/infobox/commons/infobox_league.lua
Currently for the Display we use the `LeagueIconSmall` (LIS) templates (ignoring manually input icons), while for the LPDB/wiki-var storage we use the manually set icons and only use the LIS templates as fallback.
This PR switches the display so that it will consider the manually input icons too.
Namely it now uses the `LeagueIcon` module instead of directly expanding the LIS templates.
This makes the behavior of storage and display consistent for the icons
/dev sandbox
> Make LeagueIcon handling consistent

- components/automatic-points-table/commons/automatic-points-table.lua
Added parseTeam() which parses the teams provided in the arguments of the module
The module is deployed in Sandbox and is working as intended after making this change:
https://liquipedia.net/rocketleague/Module:Sandbox/AutoPointsTable/Rewrite/GH/2
here's a screenshot showing a portion of the teams table
> Added parseTeams

- components/match2/wikis/arenaofvalor/match_legacy.lua
Legacy Module for AoV, based on the Mobile Legends version that has been merged but with 1 specific change
Previously AoV has an issue where the hero statistics module cannot picked up any hero at all but does acknowledge that theres a match, while Wild Rift has no issue (using same M2 modules) so I asked hjp and he proceed with the extradata converter to help solve it (basically pick/ban was gone from extradata for unknown reason)
After the converter is added heroes are now appeared normally, the rest has also functional fine with no spotted issues so far.
Pushed Live
test page: https://liquipedia.net/arenaofvalor/User:Hesketh2/sandbox
* has a test match and tables that compare the lpdb data
* is atm a bit buggy due to lpdb bug (the display in the table doesn't always match what is …
> Add Match Legacy for Arena of Valor

- components/infobox/commons/infobox_league.lua
Resolves redirects of organizers before entering them into LPDB.
Organizers are often entered with names/pages that are redirects, and that is making it hard to query for tournaments of a specific organizer, e.g. to list them on the organizer's page.
Resolving redirects before saving organizers allows to have them saved consistently under a single name.
Tested correct behavior of the introduced function in a [sandbox](https://liquipedia.net/ageofempires/Module:SyntacticSalt/sandbox4)
Tested correct LPDB entry with a /dev Infobox on commons/AoE
> Resolve organizer pages before writing them to LPDB

- components/group_table_league/commons/group_table_league_starcraft_next.lua
Add the SC(2) custom part of the match2 GroupTableLeague implementation (#952)
* adds Archon handling
* sets some tie breaker aliases
* adjusts the (DATAPOINT!!!) storage to also include race/faction data
used on ~600 pages on sc2 wiki already
Although i opened this PR the module was (so far) build by warnull
> Add match2 version of GroupTableLeague - SC(2) Custom

- components/infobox/wikis/halo/infobox_person_player_custom.lua
lpdpData.extradata is no longer overwritten, but added to. It will now contain data for the Statistics Portal to use for player earnings, which was currently being deleted in the overwrite.
Was tested here [https://liquipedia.net/halo/index.php?title=Module:Infobox/Person/Player/Custom/Dev&action=edit] and directly invoked on a player page in preview mode to check the lpdbdata using "mw.logObject"
> Stop overwriting Commons extradata

- components/automatic-points-table/commons/automatic-points-table.lua
**This is a different implementation for the same function in https://github.com/Liquipedia/Lua-Modules/pull/948 - this solves the issue mentioned in https://github.com/Liquipedia/Lua-Modules/pull/948#issuecomment-1011575312**
In this PR, I added the a function to perform the required LPDB queries to query for all the results in the provided tournaments to the template
The Module after this change is deployed in user-space and is working as intended
https://liquipedia.net/rocketleague/index.php?title=Module:Sandbox/AutoPointsTable/Rewrite/GH/3/2
This part might require tweaks to some wikis' prizepool table later, as it depends on lpdb objects stored in the prizepools to get the amount of points for every placement.
The following image is an example output for some of the placements:
> Added queryPlacements

- components/match2/commons/get_match_group_copy_paste.lua
Avoid nil concats in `Module:GetMatchGroupCopyPaste`
live to fix the bug
> Avoid nil concats in `Module:GetMatchGroupCopyPaste`

- components/notability/wikis/rocketleague/notability_checker_config.lua
Added a custom modifier for 1v1 tournaments within the RL wiki to be a quarter of the usual notability distribution.
> 1v1 notability modifier for Rocket League

- components/automatic-points-table/commons/automatic-points-table.lua
In this PR, I added getPointsData function which calculates the total points for every team and parses the points from manual points, queried points, secured points and deductions.
This is in preparation for rendering the table.
The module after this change is [deployed in sandbox](https://liquipedia.net/rocketleague/Module:Sandbox/AutoPointsTable/Rewrite/GH/4), here's a screenshot showing the points data for a single team:
> The table at index 1, is the team points gained in the tournament at index 1.
> The three tables; _table#46, table#47 and table#48_ are empty because this team hasn't participated in the corresponding tournaments.
> Added getPointsData

- components/match2/commons/match_group_display_matchlist.lua
- components/match2/commons/starcraft_starcraft2/match_group_display_matchlist_starcraft.lua
Allow table of matches (retrieved via lpdb queries, but the list does not belong to the same matchGroup) as input for MatchlistContainer, so that other modules can easily call the display for those.
/dev modules together with a module i am building which needs this option.
(the module i am building is not yet ready, but it already has the display functionality that uses the matchlist display)
--> https://liquipedia.net/starcraft2/Module:HeadToHeadMatchHistory
> Allow table of matches as input for MatchlistContainer

- components/automatic-points-table/commons/automatic-points-table.lua
Sorts the pointsData in order from highest to lower total points, this will be the same order in which the teams will be displayed in the table, top-to-bottom.
Attaches the position of every team, so that it can be displayed in the position column in the table.
Deployed in sandbox and works as intended
https://liquipedia.net/rocketleague/Module:Sandbox/AutoPointsTable/Rewrite/GH/5
> Add sortData and addPositionData

- components/match2/wikis/mobilelegends/matchgroup_input_custom.lua
Direct Backport of #933 (AOV, the newest version across all three [AOV, ML, WR])
> Adjustments for ML MatchGroup Input

- components/match2/wikis/rainbow_six/match_legacy.lua
Some PR is a the last few months have changed how match2bracketdata fields work. Previously the header would be set to empty string if not present on a match, now it's missing instead (nil).
Tweaked the code to deal with this (moved one part of the if statement into its own if statement inside the scope).
Also cleaned up the header code to be of higher code standard.
Tested live
> Fix issue with R6's match1.header

- components/automatic-points-table/commons/automatic-points-table.lua
Initial commit for generatePointsTable which creates the divTable which will contain the points
This commit only creates the headers and containers, the cells will be added in another commit
[Deployed in Sandbox](https://liquipedia.net/rocketleague/Module:Sandbox/AutoPointsTable/Rewrite/GH/6)
Example output screenshot:
> Add generatePointsTable (Headers only in this commit)

- components/notability/commons/notability_checker.lua
Extracted the inner loop of _calculateWeight() function and made the extracted function public. 
This is preparation for a commons version of https://liquipedia.net/rainbowsix/Module:Notable_teams_and_players_without_page, which is in used on 10ish wikis. This module calculates the points for every person or team on a wiki and lists the ones without a page whom are notable. In order to not duplicate calculation code, using the calculations of the Notability Checker is better.
For performance reasons, make the logging optional.
Put it on /dev
> Extract the inner loop of _calculateWeight()

- standard/abbreviation.lua
Abbreviations are used quite often in Modules.
To avoid recreating the function for it over and over again (or even worse expanding the abbr template) we could add this module and require its function `.make` instead.
new module so just pushed live
tested direct invoke display in my userspace:
also works when called via a different (sandbox) module
> Create abbreviation module

- components/infobox/wikis/arenaofvalor/infobox_league.lua
Infobox League for Arena of Valor
Based on #961 (ML's recently merged Infobox League) with a change.
Since AoV never had tracking of patches at all (not even used in other tour pages from what I see) coupled with AoV has multiple game version that needs to be labelled.
I decide to replace section that would show patches with Game Versions instead and that's the only thing different, the rest are same as #961
Since its already going live so I put some of the pages on mainspace to check things
- https://liquipedia.net/arenaofvalor/Arena_of_Valor_Bangladesh_Championship/2021
- https://liquipedia.net/arenaofvalor/Arena_of_Valor_International_Championship/2021
This will later be used as a basis for the Infobox League on the PUBG Mobile Wiki Split
exclude the two wiki-specific ( |perspective= …
> Add Infobox League for AOV

- components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua
My next plan is to look at the Infobox Modules for Mobile Legends, League has already added, Player is up next. 
*I'll rely on improving the ML ones to be able to port for Wild Rift and AOV later on.*
Similar to League, Player is a **pasteover** from Halo, **no changes has been made since Dec6 2021** so there maybe a lot of catch up/clean up.
Already going live, here's few of the live pages:
- https://liquipedia.net/mobilelegends/Wise
- https://liquipedia.net/mobilelegends/Baloyskie
Totally unrelated?, but in ML I did not make /Custom in ML wiki and calls off from the /Custom in Commons directly ( https://liquipedia.net/commons/index.php?title=Module:Infobox/Team/Custom&action=edit ) totally fine with no issue so far since the wiki's installation, do we still need to make one for the wiki …
> Add Infobox Player for ML

- components/infobox/wikis/dota2/infobox_person_player_custom.lua
Correctly sets role categories on Dota, instead of just linking them.
live
> Fix role categories not set on Dota

- components/infobox/wikis/wildrift/infobox_unit_champion.lua
Blue Essence is Blue Motes in Wild Rift and has a different icon. The same goes for RP and Wild Cores.
Parameters `species`, `birth`, and `factions` are also irrelevant to this certain infobox.
Changing the icons to match what is in-game seems like a good change to me. I also considered changing the parameter name from `cost_be` and `cost_rp` to `cost_bm` and `cost_wc`, but that's a change for another day.
Does this break LPDB on any of the wikis? Nope.
Are all needed page variables still set? Yes.
Does this break SMW on any of the wikis? No.
> Correct Wild Rift's icons and remove irrelevant parameters

- components/infobox/commons/infobox_unit.lua
This change is similar to #910 but for Unit, also for Hero/Champion infoboxes in MOBA games where they would have a title name in tandem with the actual character name
Tested from https://liquipedia.net/mobilelegends/User:Hesketh2/unit 
the setup in that page uses a /dev module for both Base Unit and for adjusting Infobox Hero for ML ( #714 ) which is the original cause for this commons PR
> Add subheader support to Infobox Unit

- components/infobox/wikis/dota2/infobox_person_player_custom.lua
Dota2's Portal:Player stopped working due SMW fields not being properly set. Third bug fix is unrelated to the Portal:Player and can be moved out of the PR if requested.
* SMW field `isplayer` is not being properly set. The SMW storage code expects wikivar `isplayer`. New implemenation sets this wikivar. Added the static data into the roles data.
* SMW field `nationality` is not being properly set. The SMW storage code expects wikivar `country`. New implemenation sets this wikivar.
* LPDB extradata field uses raw input instead of normalized input. New implemenation will now save using the normalized input instead (derived from `variable` in the roles data).
Live as the Portal was broken.
> Fix three bugs on dota's Infobox Player

- components/match2/wikis/starcraft2/legacy/match_maps_legacy.lua
Disable duplicate check for non storage legacy match lists.
If the matches do not store the matchlist does not need to check if the id already exists or not as it only displays.
This is often the case on older transcluded pages.
pushed live
> Disable duplicate check for non storage legacy match lists

- components/match2/wikis/halo/match_group_input_custom.lua
It was suggested to allow separation by different halo titles when searching headtohead history between teams. To allow for the headtohead module to use "game" as a condition variable, it needed to be stored in match2 lpdb data.
The module additionally references "Module:GameVersion" to take the raw input for the game version, and format it to a uniform standard so as to be easily identifiable as belonging to the same game when specified with a lpdb query. The field can then be changed to a "token" input on the head to head form, eliminating the need for users to format the game correctly when they input it
An existing tournament was copied to a test page here [https://liquipedia.net/halo/Dark_meluca/TournamentTest] for which a /dev version of the module was created with the added …
> Allow for tournament_game storage in match2 in halo wiki

- components/infobox/wikis/pubg/infobox_weapon_custom.lua
Adjusting the infobox to have support for throwable weapons.
The current Infobox Weapon does not support the parameters for throw speed and throw cooldown. Under the consideration that throw speed *could* replace reload speed, throw cooldown is needed as a new cell regardless. This will be unused for all infobox uses that are not throwable weapons
Tested live and on user page: https://liquipedia.net/pubg/User:Fenrir.SPAZ/Sandbox
> Adding throwable cells PUBG Weapon Infobox

- components/infobox/commons/infobox_map.lua
Adds location as a default value. There are 28 wikis that are (or will) use Infobox/Map, with 23 of those wikis already having the template (1 wiki has no usage of this template). There are 9 wikis that currently use location as a parameter, which seems like a lot to force that field to be in custom versions. Most of those use just plain wiki text for the location, a few use a flag. 
Code was tested via this module: https://liquipedia.net/commons/Module:Sandbox/Fenrir
and was tested on various wikis via ``{{#invoke:Infobox/Map|run|``
An actual testing page was set up here: https://liquipedia.net/overwatch/User:Fenrir.SPAZ/Sandbox
> Add location to Infobox/Map

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/wikis/arenaofvalor/matchgroup_input_custom.lua
- components/match2/wikis/brawlstars/match_group_input_custom.lua
- components/match2/wikis/halo/match_group_input_custom.lua
- components/match2/wikis/mobilelegends/matchgroup_input_custom.lua
- components/match2/wikis/rainbow_six/match_group_input_custom.lua
- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/splitgate/match_group_input_custom.lua
- components/match2/wikis/valorant/match_group_input_custom.lua
- components/match2/wikis/wildrift/match_group_input_custom.lua
- standard/stream_links.lua
Fix Stream Storage in match2 as mentioned in #1029 
* add functions to `Module:Links/Stream` that can be used by the /Custom modules
* adjust the /Custom modules to use that functionality provided via commons
/dev modules, tested for sc2, sc and RL
> Adjust Stream handling in match2 input processing

- components/match2/wikis/dota2/matchgroup_input_custom.lua
Adding `MatchGroup/Input/Custom` module for Dota 2. Most of the module is copied from Mobile Legends. Added `isFeatured` check and saving Dota 2 match ID in `Match2game`.
Tested here: https://liquipedia.net/dota2/User:Lenya_01/15
> Add MatchGroup Input for Dota 2

- standard/table.lua
Add `.mapInterleavedPrefix` function to `Module:Table`
Extracts prefixed keys interleaved with numeric indexes from an arguments table, and applies a transform to each key or index.
Intended use is for template calls that support both prefixed and indexed params.
(want to try to build a solution for #1047 with this)
Orig function from warnull in a utils module that is not yet on the git. Think it fits here best though.
Cleaned up the variable names a bit.
sandbox
only adds a new function, does not touch existing ones.
> Add `.mapInterleavedPrefix` function to `Module:Table`

- standard/flags_master_data.lua
`Bosnia and Herzegovina` is too long for storage in match2 lpdb, so it gets cut of there.
This PR adds an alias in the flags data so that the cut version gets found by the flags module too.
pushed live
> Fix `bosniaandherzegovina` flags data

- components/infobox/wikis/mobilelegends/infobox_hero_custom.lua
Infobox Hero for the Mobile Legends Wiki
Module: https://liquipedia.net/mobilelegends/Module:Infobox/Unit/Hero
Template: https://liquipedia.net/mobilelegends/index.php?title=Template:Infobox_hero&action=edit
Both is derived from Wild Rift version which got both these added just a week ago, few parameters have been changed adjusted including
- costbe and costrp has been replaced by **costbp** and **costdia** to reflect the actual currency for those games (icon files already provided)
- everything that says Champion in it has been changed to be Hero, as Mobile Legends dont called their character Champion
- Rest of Base Stats are unchanged, as they are all present in both games
- **Region** as in LoL werent existed nor being properly mentioned in the game, however, Mobile Legends replaced …
> Create Infobox/Hero for Mobile Legends

- standard/lpdb.lua
- standard/lua.lua
Add a wrapper function for mass LPDB queries.
Since we use that functionality in several modules it seems waranted to add the wrapper function to the Lua module so we can access it whenever we do mass queries.
sandbox
> Add a wrapper function for mass LPDB queries

- components/infobox/extensions/commons/years_active.lua
- components/infobox/extensions/commons/years_active_base.lua
- components/infobox/extensions/wikis/rocketleague/years_active.lua
Add an implementation of `YearsActive` via commons.
Wikis can set custom values (startYear, additionalConditions, defaultNumberOfStoredPlayersPerMatch) and legacy entry points via a wikispecific module
* created the commons modules, tested them on sc2 and some other wikis via preview
* temp created a /test module on RL (due to them already having a module with that name (should be replaced with the new one)) and tested it via that
* * alias function works too (so that no replacement runs should be necessary)
> Add `YearsActive` commons implementation

- components/infobox/wikis/pubg/infobox_league_custom.lua
**Part of the PUBG Split Project**
Infobox League (New Modulized version) for PUBG, theres a lot of new part that is unique to PUBG - both being the game mode and game perspective. Also **Game Version** are renamed as **Platform** here, Hjp has help added these stuff  to the new infobox.
**_This will work for both wikis post-split on a slightly different meaning, the main wiki is still having the Console Version with them while Mobile will be for various game version releases instead._**
As of now, I have replaced the main infobox league so its already live, The other variable/LPDB/SMW calls that existed in the old box are being kept. So far the earnings/achievements and also Tournament Portals/Ticker are still intact
Just in case, this is my sandbox: …
> Add Infobox League for PUBG

- components/infobox/extensions/commons/age.lua
Currently age calculation is off by up to almost 1 day:
(atm: seconds / 60 / 60 / 24 / 365.25 = 12.999826032398)
after the change:
(atm: seconds / 60 / 60 / 24 / 365.2425 = 13.000092974759)
sandbox
> Fix age calculation

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
Outsource EPT Season value so it can be changed without PRs.
live
> Outsource EPT Season value

- components/match2/wikis/brawlstars/match_group_input_custom.lua
Added support for:
- read brawler picks and bans per map
- remove bans from match as they are not used according to @jojimenezt 
- read map type
- read match mvp
live (system so far only used on test pages)
> Update custom input processing

- components/infobox/commons/infobox_person.lua
For wikis not overriding `_createLocation` in their Player implemenation, the default handling in Common's Infobox Person is to set the country category in all spaces. This currently affects the wikis Starcraft2, (Mobile Legends) and Halo.
It was determined on discord that the category shouldn't be set in userspace. https://discord.com/channels/93055209017729024/874304000718172200/943890994921889852
Tested in preview mode on SC2 userspace & mainspace page. 
Works as expected.
> Do not add category in userspace (Person)

- components/infobox/commons/infobox_unofficial_world_champion.lua
Adjust "days" —> "times" in the "most times held" section
live
> Fix typo in unofficial world champ infobox

- components/infobox/wikis/starcraft2/infobox_patch_custom.lua
Add option to disable storage in LPDB for SC2 infobox patch.
Since SC2 has cases where the Patch pages get transcluded we need an option to disable the storage so the LPDB entries are not doubled in those cases.
Live
> Add option to disable storage in LPDB

- components/match2/commons/match_group_input.lua
Fix for #983 (Legacy Brackets don't use historical team templates). Apply the template fallback in correct order. 
`opponent` has the more up to date template information, being retrieved from `Module:Opponent.resolve`, while `record` is contains the arguments (from wikicode/legacy).
Tested with `dev` feature toggle on R6, RL, SC2, ML & halo. 
No unintended side effects on any wiki.
Issue successfully seen solved on R6 & RL (ML, Halo doesn't use legacy, couldn't find a SC2 tournament to test with dev toggle on)
> Fix Historical TT's in Legacy Brackets

- standard/table.lua
Add the index as a third value in pairsByPrefix, in addition to the key and value. 
https://liquipedia.net/rainbowsix/Module:Sandbox/Rathoz
Returned the expected output
```
p1	table
p2	table
p3	table
p1	table	1
p2	table	2
p3	table	3
```
> Add index to pairsByPrefix

- components/match2/wikis/brawlstars/match_group_input_custom.lua
Update brawlstars match2 input processing
- fix a bug where score and status were not set correctly
- adjust pick input as wisched by the wiki
- add input for players per map
live (system not yet in use)
> Update brawlstars match2 input processing

- components/match2/wikis/rainbow_six/match_group_input_custom.lua
- components/match2/wikis/rainbow_six/match_legacy.lua
- components/match2/wikis/rainbow_six/match_summary.lua
I use the new API through an object-oriented language that doesn't like when a field can either be an array or an object. This change makes it so `t1firstside` is always an object. I named the new field `rt` for "regular time", which is in line with the other field name which is called `ot` for "overtime".
I made these exact changes to the modules on the rainbowsix wiki. Then I both purged and null edited the [Six Invitational 2022 page](https://liquipedia.net/rainbowsix/Six_Invitational/2022). All matches and match summaries looked the same after the purge. The API response does now include the field even if a game doesn't go to overtime (not the exact same matches, just showing the changes):
```
"{\"t1firstside\": {\"rt\": \"atk\"}, \"t2halfs\": {\"atk\": \"3\", \"def\": \"4\"}, …
```
> Update t1firstside to always be an object

- components/match2/wikis/rocketleague/match_summary.lua
Width of the Goaltime is wrong. 15% will break after every single timestamp, while it should fill out the row to the middle. Increased max-width from 15% to 50%.
Live
> Fix width of Goaltimes

- components/infobox/commons/infobox_league.lua
- components/infobox/wikis/starcraft2/infobox_league_hidden.lua
As discussed multiple times on the discord, such as 
https://discord.com/channels/93055209017729024/802175956286177311/927935117622661170
https://discord.com/channels/93055209017729024/874304000718172200/935522534147899462
https://discord.com/channels/93055209017729024/874304000718172200/935854580531613796
Reasoning is improved querying of tournament data when a tournament is split across multiple pages.
Setting the wiki-variable `tournament_parent` always in Infobox League. By default, the current logic will apply (`|parent=...`) and if missing will use the Pagename of the page (including userspace prefix) and `|name=` respectively.
Applying this wiki-variable will then cause downstream Modules, such as match2, to set their LPDB-property `parent`.
Some Template/Modules may need to be …
> Default parent if not set

- components/standings/standings_storage.lua
If the wiki variable for parent (`tournament_parent`) is set, save the values to the lpdb property (`parent`) in the standing table.
Tested on R6
> Save parent to standings if set

- components/match2/commons/match.lua
If the match2's parent value is set, set it also for match2game. This will save the value to the lpdb property (`parent`) in the match2game lpdb.
Tested with /dev
> Save parent to match2game if set

- components/match2/wikis/dota2/matchgroup_input_custom.lua
Removing the specific player input + some code cleanup. 
Specific player input can be readded at a later stage, currently just porting over the match2. Since this would likely require additional extension changes it can wait.
Live on userspace only
> Remove player input, extract publisherid parsing from vod function

- components/match2/wikis/dota2/match_summary.lua
Move the overflow hidden from each "row" in the popup to instead cover the entire popup. This allows a single row to overflow into another row. Needed during hoovering
https://liquipedia.net/dota2/User:Lenya_01/15
Before:
After:
Still in userspace, put it live
> Tweak overflow:hidden handling

- components/match2/wikis/dota2/matchgroup_input_custom.lua
The current implementation for automatically finishing a match only handles odd numbered bestofs. 
This PR updates the logic to not totally break on even numbered bestof. 
In the new implementation a tied bo2 will require a manual `|finished=true` and will work fully for 2-0's. But most importantly it it won't prematurely finish the match once a single map is completed, which the current implementation does..
The last case currently not working as expected (tie) will be fixed in a followup PR.
This PR (and the followup) will also need to be applied to: AoV, Halo, ML, Splitgate & Wildrift.
Live
> Fix dota2 finished calculation on even numbered bestOf's

- components/match2/wikis/dota2/match_summary.lua
If a map has no hero bans, all subsequent maps' hero bans would not be displayed. 
This has been fixed in this PR by iterating on the maps instead of hero bans per map.
Before:
After:
Live
> Fix missing Hero Bans

- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Adjust SC2 infobox team to fit the prize pool changes applied yesterday.
- adjust conditions as well as placement data handling according to the prize pool changes
- use condition module for building the conditions for the placement query
tested via sandboxes for several days, pushed live yesterday (atm the infobox team template is calling the /dev module until after the PR is merged)
> Adjust SC2 infobox team

- components/match2/wikis/dota2/matchgroup_input_custom.lua
The previous version would call `getInexactDate` which adds a second to each match missing a date. This caused a chunk of matches to the times 1970-01-01 00:00:01, 1970-01-01 00:00:02, 1970-01-01 00:00:03 etc. While the logic in BrktWikiSpec and MatchSummary expects `1970-01-01 00:00:00` to determine missing date. This would display Jan 1st, 1970 on any match missing a date.
Before:
After:
(Separate issue can be seen in the after image, the popup shouldn't be available for this match, RCA is known, PR pending)
Live
> Change missing date to use EPOCH

- components/match2/wikis/dota2/match_legacy.lua
Missing in #1105 as didn't find any page setting it. But seems like there were a bunch and my sampling was bad. 
The match2 bestof value should be set in the `gamecount` extradata field of match1.
Before (note match 1 & 3):
After:
Live
> Convert match2 bestof to match1 object

- components/match2/commons/match.lua
- components/standings/standings_storage.lua
Fix #992 (last_heading issue)
Dev module
group A without activated dev
group B with activated dev
> Fix #992 (last_heading issue)

- components/match2/commons/match.lua
Standings and Match2 currently uses two different fallback values if last heading is missing when inserting into LPDB. Standing is using `<blank>` and match2 is using `none`. 
Per conversation on the discord (https://discord.com/channels/93055209017729024/372075546231832576/954366452905938974) and PR #1120, the value should be `<blank>` as fallback.
Not tested
> Empty the LPDB fallback value for section

- components/notability/wikis/rainbowsix/notability_checker_config.lua
Adjusts the minimum requirement for notability on R6. 
Change was tested live. Additional tests where done via sandbox (note the sandbox values differ slightly from the PRs)
https://liquipedia.net/rainbowsix/User:Okidokie98/Notability/Players
https://liquipedia.net/rainbowsix/Module:Notable_teams_and_players_without_page/Sandbox
https://liquipedia.net/rainbowsix/Module:NotabilityChecker/config/sandbox
> Adjusting Rainbow Six notability points

- components/match2/wikis/dota2/match_summary.lua
Replacing #1125 based on feedback and as such is the new followup PR to #1118.
Use-case: End users can easily see what Best of X upcoming (or ongoing) matches are
Before:
After:
Live
> Show upcoming games in Match Summary

- components/automatic-points-table/commons/automatic-points-table.lua
- components/automatic-points-table/commons/display.lua
This is an attempt to separate the Display Code from the Logic of querying and calculating the points
This PR is a different approach to https://github.com/Liquipedia/Lua-Modules/pull/1017 
Deployed in [Sandbox ](https://liquipedia.net/rocketleague/Module:Sandbox/AutoPointsTable/Rewrite/GH/8) and works just like https://github.com/Liquipedia/Lua-Modules/pull/1017
> Refactor display into a separate module

- components/infobox/commons/infobox_person.lua
- components/infobox/wikis/rocketleague/infobox_person_player_custom.lua
Store `teamtemplate` (child-TT if historical) into lpdb_player. 
Field `team` is now automatically retrieved from the teamtemplate, if it can be resolved, otherwise fallback on previous method.
Add tracking category to commons + Rocket League for invalid values in `|team=`/`|teamlink=`.
Tested on a couple of players with /dev.
> Store teamtemplate in lpdb_player

- components/match2/wikis/rainbowsix/match_group_input_custom.lua
If a match is missing a date, we want to store it as Epoch 0.
However, this would cause the original team template to always be used in historicals if a match had to date. To improve this, this PR will use the tournament date when resolving opponents if the date is missing.
Once this PR gets merged, will create followup PRs for other games using epoch as default date.
Before (Note G2 Icon):
After:
Dev modules on R6
> Use better date for resolving opponents when date is missing

- components/squad/squad_row.lua
Store `newteamtemplate` (child-TT if historical) into lpdb_player.
Initially considered storing `teamtemplate` as well, but leaving it out for now as 1) Not sure which date for child TT to use 2) Unsure if required.
Tested on a couple of teams on RL
> Store newteamtemplate in lpdb_squadplayer

- .github/workflows/luacheck.yml
This would add a second check result to pull request that looks like this:
If the details link is clicked, a page would open that looks something like this, detailing the errors without having to look through the entire list in the CLI output.
If you don't think this is valuable, feel free to just close it.
I tested this on a private repository.
> Change luacheck reporting display on GitHub

- components/standings/standings_storage.lua
If the title of a GroupTableLeague (GTL) contains a flag or icon, this is entered as HTML into LPDB_standings's title field.
This PR will remove all HTML tags and their inner content from the GTL's title before storing into LPDB. 
Example:
`<span foo="bar">Lorum Ipsum</span> Cool Title` will become `Cool Title`.
Before:
After:
Tested using dev modules
> Remove HTML from Title field

- components/infobox/wikis/mobilelegends/infobox_league.lua
The change were made so that the tournament portal modules use in Portal:Tournaments can display yellow highlighted tiers (for events that has publishertier added), originally it can't recognize yellow tiers. 
A test module (which is same as the main one with the addition of this PR) on the https://liquipedia.net/mobilelegends/M3_World_Championship page
It now appears in yellow at: https://liquipedia.net/mobilelegends/M_World_Championship (the tournament lists)
other wikis that I do PR infoboxes all had this missing (Halo, both PUBG, AOV) but i'll get this first and then do the same later on since Each wiki has its own different publishertier input (hcs-sponsored, pubgpremier, etc etc)
> Add publishertier LPDB in Infobox League ML

- components/match2/wikis/rocketleague/match_group_input_custom.lua
Fix `extradata.isfeatured` in RL matches.
Infobox sets `"1"/"0"` while matches until now expected `something/empty`.
/dev module
> Fix `extradata.isfeatured` in RL matches

- components/infobox/wikis/pubgmobile/infobox_league_custom.lua
**Part of the PUBG Split Project**
Since PUBG MOBILE wiki is a clone of the current PUBG Desktop wiki, this module has no difference from #1041 and functional with no changes so I did just to do regular PR stuff and to have **pubgmobile** folder created for storing files as well
I actually had created a pubgmobile label months ago, so I can get to use it now.
Already live, as part of cloning
> Add Infobox League for PUBG MOBILE

- components/match2/wikis/starcraft2/legacy/match_maps_team_legacy.lua
For Archon, 2v2 and 3v3 opponents in team legacy matchlists the displayName of some players was set wrong, this PR fixes this bug.
dev module and after testing with it pushed live
> Fix team legacy matchlist for non 1v1 submatches

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
This is a (minor) Quality of Life change for editors when inputting maps in team matches.
Currently players have to be inputted as link values into the maps.
Since TeamCard was slightly changed to now also set the same wiki variables that participant lists set we now can use the display name and grab the full link from the wiki vars instead.
Only constraint for this is if 2+ players with the same displayName participate in the same event, then the link values still have to be set accordingly.
dev modules
> Allow easier player input in maps for sc/sc2

- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/rocketleague/match_summary.lua
Adds support for
- timeout storage and display
- caster storage and display
within matches on the RL wiki as requested by contributors of the wiki.
/dev modules
> Add timeout and caster support to RL matches

- components/squad/wikis/rainbowsix/squad_custom.lua
R6 exclusively uses automatic Squad/Org Tables. The display & storage has been extracted into a Custom Squad implementation for the Squad tables, while the Org Tables still use the SquadAuto's implementation.
This module is called from: https://liquipedia.net/commons/index.php?title=Module:SquadAuto&action=edit#mw-ce-l602
Live
> Create Squad for R6

- components/match2/commons/match_group_input.lua
Add `inheritedHeader` to `match2bracketdata` per the discussion in the discord.
https://discord.com/channels/93055209017729024/756217678493909143/961630621229277213
Decision of final name of the property still pending.
/dev module
roundheader (renamed to inheritedHeader) present without header being present (R1M2):
> Add `inheritedHeader` to `match2bracketdata`

- components/notability/wikis/ageofempires/notability_checker_config.lua
wiki should correspond with server url path
> fix capitalisation of aoe wiki name in aoe notability checker config

- components/infobox/commons/infobox_person.lua
- a person can only be teamless if they are not dead and not retired (technically they are, but they are not looking for a team then)
- a dead person can not be active
dev module
> Adjust Person category handling

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
Adjust active person category handling to not put players/casters into the active category if they had a match in the last 3 years.
Use commons determination for the active category instead.
dev module
> Adjust active person category handling

- components/infobox/commons/infobox_widget_header.lua
Requested by dota2 for Infobox Teams, is in use on a handful of pages today with the legacy infoboxes, such as https://liquipedia.net/dota2/PSG.LGD 
Input for the new infobox here would be `|imagesize=65%` while the old dota2 infobox uses `|image_sizedefault=frameless|image_upright=0.65`. So once dota2 goes live with Infobox Team, this would need to be updated on those team pages.
You can read more about `frameless` and `upright` (used on line 93): https://www.mediawiki.org/wiki/Help:Images#Rendering_a_single_image 
Dev modules & preview.
> Add scaling support to Infobox Header

- components/infobox/commons/infobox_widget_header.lua
Missed to perform a test case in #1168, where by if no size was supplied to the header, there would be a null pointer on line 89.
As part of the lessons learned, an upcoming PR will mitigate the effect on the wiki if a similar thing occur in the future.
Live
> Fix null pointer in Widget Header caused by #1168

- components/infobox/commons/infobox_building.lua
- components/infobox/commons/infobox_campaign.lua
- components/infobox/commons/infobox_campaign_mission.lua
- components/infobox/commons/infobox_company.lua
- components/infobox/commons/infobox_game.lua
- components/infobox/commons/infobox_item.lua
- components/infobox/commons/infobox_league.lua
- components/infobox/commons/infobox_map.lua
- components/infobox/commons/infobox_patch.lua
- components/infobox/commons/infobox_person.lua
- components/infobox/commons/infobox_scene.lua
- components/infobox/commons/infobox_series.lua
- components/infobox/commons/infobox_show.lua
- components/infobox/commons/infobox_skill.lua
- components/infobox/commons/infobox_strategy.lua
- components/infobox/commons/infobox_team.lua
- components/infobox/commons/infobox_unit.lua
- components/infobox/commons/infobox_unofficial_world_champion.lua
- components/infobox/commons/infobox_weapon.lua
- components/infobox/commons/infobox_website.lua
Passthrough from `|imagesize=` to Header Image's size. 
Change Infobox Skill from `|imageSize=` to `|imagesize=`.
Change Infobox Item from `|size` to `|imagesize=`.
The latter two changes needs updated pages on the wiki. Infobox Skill is only used Starcraft2, Infobox Item is used by Wild Rift and Mobile Legends.
Tested on Infobox Teams combined with #1168 & #1147.
> Add imagesize passthrough on all infobox headers

- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Use `individualprizemoney` to fix a minor earnings bug on sc2 team pages (basically it was counting non team/solo placements wrongly)
pushed live
> Fix earnings bug for sc2 teams

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
Improve runtime of SC2 player pages significantly.
Since the SC2 infobox already queries all achievement worthy placement records and runs trough them to determine earnings and medal statistics data we decided to now also sort the achievements via that.
The so found achievements then get json-stringified and stored into a wiki var.
Achievements table module then just reads that wikivar, parses it and uses the so retrieved data instead of doing its own queries.
(Due to SC2 having team events with up to 30 players on a team the earnings and achievements/results queries are way more inefficient compared to other wikis so we try to actively reduce them and any redundancy.)
/dev modules with preview tests on > a dozen player pages
Achievements (incl. awards) display as well as infobox display …
> Improve runtime of SC2 player pages significantly

- components/match2/commons/match_summary_base.lua
If the Opponent is a TBD (based on the logic in Module:Opponent.isTbd()), don't insert a link.
Before:
After:
Dev Module
> Hide Opponent Link if it's TBD

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
- Support submatch with only aggregate map info
- allow subgroup headers for > 9 subgroups
/dev modules
> Support submatch with only aggregate map info

- components/match2/wikis/rocketleague/match_summary.lua
* Rewrite RL MatchSummary to use MatchSummary/Base Classes
* Additionally adds Bestof display (as requested by RL contributors)
* Additionally has a comment that only has to be unboxed in case score display in matchsummary headers is wanted (also supported in combination with the bestof display)
* --> e.g. for usage of `Template:SingleMatch`
/dev module
(also tested the stuff that was only added as comment)
both score and bestof display enabled
with enabled score display and not entered bestof
with bestof display and disabled score display
fixed the double score display on the right for maps (in the above screenshots it is still wrong)
* probably needs rebase once #1137 is merged
(contains the additions that get added in #1337 (just with different code due to now using the /Base classes)) …
> Rewrite RL MatchSummary to use MatchSummary/Base Classes

- components/match2/wikis/rocketleague/match_summary.lua
Currently the Score in the MatchSummary displays the result of the first match in this popout header. Improve this based on discussions in RL channel.
For Match Sets, it should displays Sets won/lost.
For Bracket Reset, it should display W/L.
Before:
After:
Dev feature toggle with dev modules
> Improve Score Display for Bracket Reset and Match Sets

- components/infobox/wikis/rocketleague/infobox_league_custom.lua
> Kick extra colon in the "Misc Mode" cell name

- standard/stream_links.lua
In order to get away from improvised historic solutions like `twitch2`, a new format will be used from streams when saving into LPDB. This format would 
1) Allow for infinite usages of a single platform 
2) Allow setting language code for the streams
The format that was decided on is `platform_languageCode_counter`, so for example `twitch_en_1` and `twitch_en_2` instead of `twitch` and `twitch2`.
The initial scope of support will be only saving into LPDB from match2, reading from LPDB for match2 display and conversion from match2 to match1 (match1 will use the old formats). No change to the wikicode or the page setup.
In a future we should look at getting all streams we have information about into the DB. But that's **___currently out of scope___**
This PR adds functionality to store …
> Store new Stream Key Format

- components/infobox/wikis/dota2/infobox_person_player_custom.lua
Fix countryDisplay for dota2 infobox player when not in main space.
/dev module
> Fix countryDisplay when not in main space

- components/infobox/wikis/dota2/infobox_person_player_custom.lua
Fix country display in dota infobox player (switch 2 lines)
Bug introduced in #1201.
> Fix country display in dota infobox player

- components/standings/standings_storage.lua
Save `type` and `buchholz` fields if present.
* The LPDB field `type` doesn't yet exist, but it is in the process of being created. `type` should initially be either `league` or `swiss`
* `buchholz` goes into the scoreboard. This PR can be merged before the field is made available, it will start automatically populating once it is available.
Dev module
> Add support for Swiss tables

- components/match2/commons/match.lua
Swiss tournaments on the wiki often split their rounds into High & Low (and Mid when applicable). This can for instance be seen on https://liquipedia.net/counterstrike/PGL/2022/Antwerp/Europe_A#Swiss_Results .
Since these are headings, wiki variable `last_heading` will be set to eg `High`, which is then stored in match2's `section` field. Having what should be 3 different section all being named `High` in the database is unwanted. Rather we'd want them to be named Round X or similar.
Since automatic swiss standings require the wiki variable `matchsection` to be set to function properly, and it must always be set to `Round X` to function, which is the parent heading.
So to solve the issue, with this PR, if the wiki variable `last_heading` has one of a few predetermined values (`high`, …
> Use matchsection as section for some last_heading

- components/standings/standings_storage.lua
Save dark mode icon in Standings, if supplied.
Tested using /dev
> Save Dark Mode Icon in Standings

- components/standings/standings_storage.lua
Saw a typo in the extradata code, it currently adds an additional table around the extradata.
Tested using /dev module
> Fix typo in Standings extradata

- components/squad/wikis/rocketleague/squad_custom.lua
Activate useTemplatesForSpecialTeams option on Rocket League's SquadTable, by request.
Dev Module
> Activate "TemplatesForSpecialTeams" on Rocket League

- components/standings/standings_storage.lua
In order to add Standings LPDB for the old-school manual Group Tables (and Swiss), we require an separate entry point function to Standings Store.
The biggest reasoning is that some parsing is required around the Team. The manual tables _most often_ use {{TeamIcon|name}}, however since it's basically a freetext display field in the old template, variants exists. On line 55 the code parses out the Team Link from the long html string that `{{TeamIcon|}}` creates. It also formats the match/games w/d/l to match the format that the normal storage function expects. It then invokes the normal standings storage.
It has a failsafe, if any of the super critical parameters are missing, it will not attempt to store anything. 
If it cannot parse the team name, it will store the team as `TBD`.
Before …
> Add template entry point to Standings Store

- components/earnings/commons/earnings_base.lua
Support `individualprizemoney` lpdb field in earnings module
- leave the old stuff in until all wikis switched to use `individualprizemoney` in `lpdb_placement`
- add option to query via the `individualprizemoney` if there is no divisionfactor set (i.e. if a wiki has `individualprizemoney` populated they can just nil the `Earnings.divisionFactorPlayer` function via the custom part)
tested on freefire, rl and sc2 via dev modules and previews
if the indiv prize money fields are populated the values differ slightly from the old ones in singular cases due to the old one not being exact if teams had not the default number of players (e.g. the case on freefire)
(not on sc2 as our custom earnings stuff already uses the indiv prize stuff)
if the indiv prize money fields are not populated then the …
> Support `individualprizemoney` lpdb field in earnings module

- components/match2/commons/match_group_display_helper.lua
- components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
* Display `Submatch X` (without link) instead of blank
* Display submatch-scores properly (instead of `-1`) if the submatch has a result type
/dev modules
> Adjust display for aggregated submatches

- components/standings/standings_storage.lua
varDefaultMulti's behaviour is strange. It both tries to look up the final parameter, and return it in raw if it doesn't exist. While the `nil` was added there to have a `nil` return if the first two failed to look up, however since it tries to do a variable lookup on `nil`, that errored.
Using two nested varDefault instead to get the expected behaviour.
Live
> Fix date usage in Standings fromTemplate

- components/match2/wikis/valorant/big_match.lua
- components/match2/wikis/valorant/match_summary.lua
Update Module:BigMatch and Module:MatchSummary on VALORANT to use Module:AgentIcon instead of multiple Template:AgentIcon/* and Template:AgentBracket/*, so when a new agent is out, we only need to update a single module instead of creating templates.
/dev module
> Change AgentIcon templates to module version for VAL match2

- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/rocketleague/match_summary.lua
Continuation of this [pull-request](https://github.com/Liquipedia/Lua-Modules/pull/1146) which was automatically closed.
This change is to return the format of the casting on the match summary back to how it was [originally showcased](https://twitter.com/LiquipediaRL/status/1508509085842522117).
The reason it was changed away from this was because it was stored in a comment.
This edit changes the presentation of the parameters to look how it was in the comment-era.
/dev module
> Recreate original caster match summary for RL

- components/team_card/team_card_storage.lua
Intended to be jacked into the current Common's TeamCard, where it moves the LPDB Storage from exclusively on /Custom (see https://liquipedia.net/dota2/Module:TeamCard/Custom) to just the overriding the parts required by the wiki. This allows us a to have a standardized TeamCard Storage.
The new custom would look like https://liquipedia.net/rainbowsix/Module:TeamCard/Custom/sandbox
/sandbox module (https://liquipedia.net/commons/index.php?title=Module%3ATeamCard%2Fsandbox&type=revision&diff=423372&oldid=422360) on R6.
> Create TeamCard Storage

- components/infobox/commons/infobox_league.lua
Add storage of the newly created `seriespage` to LPDB Tournaments table. 
Tested using /dev module
> Infobox League: Add seriespage DB storage

- components/squad/squad_row.lua
Add support to set the new lpdb fields `type` in the SquadPlayer table. Default value is `player`. Only accepted values are `player` & `staff` at the moment, but more are to be added in the future depending on discussion outcomes on the discord.
Tested on Rocket League using /dev modules.
> Initial support for LPDB field type

- components/infobox/commons/infobox_league.lua
- components/infobox/wikis/ageofempires/infobox_league_custom.lua
- components/infobox/wikis/apexlegends/infobox_league_custom.lua
- components/infobox/wikis/arenaofvalor/infobox_league_custom.lua
- components/infobox/wikis/brawlhalla/infobox_league_custom.lua
- components/infobox/wikis/brawlstars/infobox_league_custom.lua
- components/infobox/wikis/halo/infobox_league_custom.lua
- components/infobox/wikis/mobilelegends/infobox_league_custom.lua
- components/infobox/wikis/overwatch/infobox_league_custom.lua
- components/infobox/wikis/pubg/infobox_league_custom.lua
- components/infobox/wikis/pubgmobile/infobox_league_custom.lua
- components/infobox/wikis/rainbowsix/infobox_league_custom.lua
Add default prizePool function to commons infobox league.
Since atm in most /Custom modules the prizepool function is (basically) the same we imo should provide a default version via commmons.
/dev modules (mostly on R6 so far)
----> no issues detected with adding the wiki var --> no changes via this PR
> Add default prizePool function to commons infobox league

- components/infobox/wikis/wildrift/infobox_league_custom.lua
Looking to migrate the infobox on Wild Rift (under old version) to a new version
_**The Infobox is a direct clone of Mobile Legends which was already merged**_
Test Page: https://liquipedia.net/wildrift/User:Hesketh2/dev
I also have put the /dev version on a test for one of the tournaments here : <https://liquipedia.net/wildrift/TapTap_Cup/Season_2> for checks on LPDB usage
Other stuff such as 
- the team's earnings and achievements (both infobox and achievements table still in Old Verison)
- the player's earnings and achievements  (both infobox and achievements table still in Old Verison)
both does function normally as of now
Right now it has a conflicting issue with the tournaments list module on the mainpage ( <https://liquipedia.net/wildrift/Module:TournamentsList> ) that It misses a …
> Infobox League for Wild Rift

- components/match2/wikis/brawlstars/match_legacy.lua
Adjust resulttype in match1 legacy storage so it fits the pattern used by the matchTicker
/dev module and after that live
> Adjust resulttype in match1 legacy storage

- standard/stream_links.lua
Fix afreecatv issue with stream links by changing the find condition.
Currently Pages using this module will error due to `afreeca` being a substring of `afreecatv`.
With this change is will not check if the platform name is simply found in the input but will also ensure that the input either ends after that substring or digits follow after the substring (and the input ends after those digits).
/dev module
> Fix afreecatv issue with stream links

- components/infobox/wikis/rainbowsix/infobox_person_player_custom.lua
* Empty role would cause a person to be counted as staff instead of player
* Let `PlayerTeamAuto` and `TeamHistoryAuto` get the player via pagename instead of supplying it
Live
> Fix two bugs

- components/squad/wikis/pubg/squad_custom.lua
The new squad modules, the custom module hasnt been implemented for PUBG yet so I take this opportunity to do it, so PUBG (and the mobile wiki later on) can use new Squad if they dont wish to do AutoSquad (or if its not viable transfer-wise)
**This one is directly pasted from the version on Rocket League because I want to scrap roles column out of it, and RL one dont have role column (comparing to Mobile Legends) so that fits my need**
https://liquipedia.net/pubg/Valdus_Esports
After this is merged I'll use the same one for PUBG MOBILE later.
> Add Squad to PUBG (Desktop Wiki)

- components/infobox/commons/infobox_person.lua
- components/infobox/wikis/rocketleague/infobox_person_player_custom.lua
Adjust Person infobox module for non-representing players
- do a check if the first entered country is the non-representing one
--> if so set a variable in self so that it is available for later usage and in the /Custom modules
- adjust the Dual Citizenship check to account for non-representing value
- adjust RL /Custom accordingly as that is the only wiki that overwrites that function
/dev module(s)
> Adjust Person infobox module for non-representing players

- components/squad/squad.lua
- components/squad/squad_row.lua
- components/squad/wikis/arenaofvalor/squad_custom.lua
- components/squad/wikis/mobilelegends/squad_custom.lua
Add support for `|teamrole=`.
This PR splits the "team icon" to its own column, and adds the "team role" below, if supplied.
Old dota2 table:
Standardized Squads table With teamrole support
Tested on dota2 and SC2
> Squads: Add support for TeamRole parameter

- components/infobox/commons/infobox_league.lua
Add option for series cell to only display LIS icons instead of manually entered icons
(as requested by martin in the `Templates/Modules Sync` on tuesday)
still to be tested
> Add option for series cell to only display LIS icons

- components/infobox/commons/infobox_league.lua
Add default lp tier display function to commons infobox league.
Since atm in several /Custom modules the tier display is the same and several more can just use it too.
Changes compared to current R6/... version:
* actually checks if the tier is valid (instead of also allowing types in the tiers entries)
* uses new structure (as discussed on discord) for module tier, but has fallback for old structure
* Sets tracking categories to find pages with wrong tier/tiertype entries
/dev modules on several wikis both with overwrite and with adjuting /devs to not overwrite anymore
> Add default lp tier display function to commons infobox league

- components/infobox/wikis/ageofempires/infobox_league_custom.lua
Adjust AoE infobox league module to overwrite the tioer function directly, so that their conversion from text to number is doesn't trigger the warnings.
/dev
> Infobox tier update aoe

- components/squad/squad_row.lua
This is the second variant of displaying Inactive/Retired etc, by setting `|newteamrole=Retired` while leaving `|newteam=` blank. The first method is `|newteam=Retired`, which is currently turned on by using `options.useTemplatesForSpecialTeams = true`.
This PR will add support for the second variant
Dev modules
> Display newTeamRole without newTeam

- components/squad/squad_row.lua
Don't clean the Player input parameters. It causes issues with displaynames with special characters.
Before:
After:
Tested live on dota2 with a dev module of Squads.
> Squads: Don't clean player input

- components/infobox/wikis/dota2/infobox_league_custom.lua
Add missing space between tier and valve logo
/dev module
upper one the old (wikicode) infobox, lower one the one with the current /Custom
with the proposed change it looks like the old version again
> Add missing space

- components/infobox/commons/infobox_widget.lua
- components/infobox/commons/infobox_widget_error.lua
- components/infobox/commons/infobox_widgets.lua
Make error message a widget so that errors in children are displayed properly.
Atm if the childs cause the error we just get the following error message with a really unhelpful trace:
After this change it looks like this:
(in the above example 2 errors were forced intentionally)
Additionally it logs the widget that causes the error as well as a traceback:
/dev modules (a bunch of them)
If you want to test it yourself. On SC2 I added a version of infobox league using the /dev stuff that has no intentional error and a version of infobox league that causes an intentional error:
* https://liquipedia.net/starcraft2/Template:Infobox_league/dev (no error)
* https://liquipedia.net/starcraft2/Template:Infobox_league/error (intentional error)
> Make error message a widget

- components/infobox/wikis/dota2/infobox_league_custom.lua
Two wikivariables that were not set and defaulting the LPDB game field to dota2.
Remove Auto Chess. There's only one tournament on the wiki and its supposed to be moved to the Auto chess wiki instead (https://discord.com/channels/93055209017729024/213718409567928331/976450350598979634)
Not yet live, tested on sandbox
> Dota2 League Infobox Improvements

- components/infobox/wikis/valorant/infobox_team_custom.lua
Revised version based on the older one built a while back. Leaves functionality for the wiki rating.
Page was tested [here](https://liquipedia.net/valorant/User:Fenrir.SPAZ/Sandbox_2)
Currently, this infobox does not correctly display team earnings in LPDB
The other major change is the saving of the region name in LPDB from ``na`` --> ``North America``
> Create Valorant Infobox Team

- components/squad/squad.lua
- components/squad/wikis/dota2/squad_custom.lua
Add support for former & inactive status to Squad
/dev modules
https://liquipedia.net/dota2/User:Lenya_01/16
> Squads: Add support for former & inactive status

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Adjust CS Tier handling in infobox League.
Also fixes a bug with `valvemajor`
Atm we can not use the commons tier function directly, the overwrite is needed.
After the tier switch plus possibly some additions to CS' Module:Tier (as a replacement for `Template:TierDisplay/link`) it can probably be made to use the commons function
/dev module (even though the modules are not yet in use)
> Adjust CS Tier handling

- components/infobox/wikis/valorant/infobox_team_custom.lua
Adds Upcoming and Ongoing team tournaments to the bottom of the Valorant Infobox (by contributor request) 
Tested via [dev module ](https://liquipedia.net/valorant/Module:Infobox/Team/Custom/dev) on a [sandbox page](https://liquipedia.net/valorant/User:Fenrir.SPAZ/Sandbox_2)
> Adding Tournaments to Valorant Infobox

- components/infobox/wikis/dota2/infobox_league_custom.lua
Couple of wiki variables that were behind the template {{TVar}} was missed in the initial migration. 
Added the ones with usage back.
Live
> Add missing dota2 wiki-variables

- components/hidden_data_box/wikis/ageofempires/hidden_data_box_custom.lua
Sets wiki variable `tournament_mode` in HDB, which is needed by some match modules for LPDB storage.
/dev
> Set `tournament_mode` in HiddenDataBox

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
We cleaned some very old pages and marked players that did not play in them but were listed in the teamCards as DNP. Hence they are not stored into the player field in the placement anymore.
Due to that we now have no pages left with >20 players in a placement. Hence we can finally lower the number and reduce runtime on pages conditioning on that data significantly.
N/A
> Adjust number of maximum players in a placement

- components/match2/commons/player_ext.lua
Fix some gsub issues
`gsub` has a second return value that then gets evaluated by the `mw.text.trim` function.
To avoid that adjust the use cases so that the gsub results is stored into the variable before calling `mw.text.trim` onto that variable.
live
> Fix a gsub + trim combination issue in Player/Ext

- components/match2/wikis/wildrift/match_legacy.lua
Title. It wasnt added originally. This is to help publishertier being registered for matches (including ability to show yellow highlights on upcoming matches, both the current and the upcoming match2 ticker)
I've temporarily tested it out by adding this line in the module on wiki, but its still empty. Maybe there is something I have to set inside the https://liquipedia.net/wildrift/index.php?title=Template:HiddenDataBox&action=edit to make it work (like in LoL PC wiki the publishertier lpdb would appear as **1** in the LPDB datas)
( <https://liquipedia.net/wildrift/Special:LiquipediaDB/Icons_Global_Championship/2022/Play-ins> )
> Store `publishertier` into smw for WR match2

- components/match2/wikis/leagueoflegends/match_legacy.lua
League's match1 doesn't convert `matchsection`, making swisstables unusable.
Live
> Add missing matchsection in league

- components/match2/wikis/valorant/match_summary.lua
Not looking at adding BigMatch for the initial rollout, hence removing the link.
> Remove BigMatch link for Valorant

- components/infobox/wikis/starcraft2/infobox_person_custom_shared.lua
Change empty race display in SC2 infoboxes commentator and player to not show the cell instread of `[[]]`
live
> Change empty race display

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Just some key-name changes to fix some of the extradata in maps not getting set anymore.
During the cleanUp this seems to have slipped through.
/dev module
> Fix SC/SC2 map extradata bug

- components/infobox/commons/infobox_widget_injector.lua
Allow not setting `Injector:parse` in /Custom infoboxes by returning `widgets` instead of `{}`
/dev modules
> Allow not setting `Injector:parse` in /Custom infoboxes

- components/match2/wikis/valorant/match_group_input_custom.lua
- components/match2/wikis/valorant/match_summary.lua
Add mapVeto support. Match1 backwards compatibility already has support for it.
> Add MapVeto support for Valorant

- components/match2/wikis/valorant/match_group_input_custom.lua
Short-hand which fits better in standard mode, as `opponent1_p1` is quite long. The new additional input would be `t1p1`, matching the current match1. This would have added benefit of improved contributor familiarity.
> Add support for a less verbose input of player data

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
* wrongly calculated map modes for team opponents
* rename `numberOfPlayers` to `numberOfParticipants` to be more fitting
* add a missing `.faction`
live
> Fix some sc/sc2 bugs with match2

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
Adjust Sc2 `player_number` handling to suppress the `[[Category:Individual Tournaments]]` if it is 0 (i.e. not set or 0 set and can not be calculated from race numbers)
/dev module
> Adjust Sc2 player_number handling

- components/infobox/commons/infobox_person.lua
Allow adding wiki-specific categories without overwriting the commons `getCategories` function that already sets several categories in person infoboxes
/dev modules
> Allow wiki categories without overwriting commons categories

- components/earnings/commons/earnings_base.lua
- components/infobox/commons/infobox_team.lua
* Allow historical earnings queries for teams via `module:Earnings`
* Allow query for several teams at the same time (combined values, not values per team)
* Support `participantlink`
* pass along param in infobox team
/dev modules
tested on:
* valorant (want the historical query)
* sc2, rl, r6 as references that it doesn't break the current usages
> Allow historical earnings queries for teams

- components/infobox/commons/infobox_series.lua
Allows for adding wiki specific content after the Links. VAL and CS has Chronology at this spot, which is the immediate use case. 
Dev module
> Add custom content cell to series

- components/infobox/wikis/valorant/infobox_series_custom.lua
Old:
New:
Needs #1321 for full support
Sample testing, both content and LPDB.
> Create Series for Valorant

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Fix a small bug where race/flag for literals was not shown if both were set
first /dev, then live
> Fix small sc/sc2 bug with literals in matches

- components/hidden_data_box/wikis/wildrift/hidden_data_box_custom.lua
- components/infobox/wikis/wildrift/infobox_league_custom.lua
Add wildrift HiddenDataBox/Custom
+ add legacy wiki-var `tournament_riot_premier` to infobox league as it is used by some templates/modules
/dev module for infobox league
live for the HDB change
> Add wildrift HiddenDataBox/Custom

- components/match2/wikis/valorant/match_group_input_custom.lua
- components/match2/wikis/valorant/match_legacy.lua
Use the explicitly given info in the PlayerStats input. This is important due to substitutes. In the currently (commented) method, they can't be seen as the player who played a match. 
Live
> Player handling use explicit information

- components/match2/wikis/valorant/match_legacy.lua
The extradata fields `hidden`, `cancelled`, `opponent1rounds` and `opponent2rounds` were not being set in match1 backwards compatibility. They has been added.
Live
> Add 4 extradata fields in match1

- components/infobox/wikis/rainbowsix/infobox_person_player_custom.lua
The resolve of the team2 was missing the first parameter (frame) in it's function call, which would throw a lua error.
Changed the resolve to use the raw functionality, to match what commons does with team1. 
Live
> Fix team2 page resolve

- components/match2/wikis/valorant/match_group_input_custom.lua
Default to EPOCH instead of using fallback dates.
Requested by the wiki
Live
> Default EPOCH instead of using fallback dates

- components/match2/wikis/valorant/match_summary.lua
Valorant wiki for some reason isn't creating a new instance of the MatchSummary(Base). This effectively means they're reusing the same object for every match. That has weird knock-on effects, such as sub-elements from previous matches showing up on successive matches.
Live
> Fix lack of instance initialization in MatchSummary

- components/infobox/commons/infobox_series.lua
Fix links in series infobox by building the infobox before storing into lpdb (and hence prefixing the links)
/dev modules
reported by spazer: https://discord.com/channels/93055209017729024/372075546231832576/981407248079265802
> Fix links in series infobox

- components/match2/wikis/valorant/match_legacy.lua
* Resolved redirected names are expected for the match1game extradata field by querying modules.
* Ensuring numeric scores before trying to add them. Fix issue with W/L/FF etc would crash here.
Live
> Fix 2 bugs in Match1 for VAL

- components/earnings/commons/earnings_base.lua
QueryHistoricalNames will return nil if the input is not a valid team template.
Check that before attempting to loop over the output.
/dev module in preview
> Check for valid output from queryHistoricalNames

- components/infobox/commons/infobox_series.lua
- components/infobox/wikis/starcraft2/infobox_series_custom.lua
Adjust series default tier handling
* allow overwriting of the function directly
* use tier module instead of expanding templates
* allow non cased entries
* add warnings for invalid tiers/tiertypes
* store liquipediatiertype (was apparently forgotten before)
tldr: use what we have for the league infobox already
/dev module + /Custom/dev module on sc2 and rl
> Adjust series default tier handling

- components/match2/wikis/valorant/match_group_input_custom.lua
- components/match2/wikis/valorant/match_summary.lua
Add MVP Support for Valorant. Based on R6. 
Valorant do not store anything in match1 into LPDB or SMW, so not adding any match1 or SMW compatibility.
Dev module with preview
> Add MVP support for Valorant

- components/infobox/commons/infobox_widget_links.lua
Fix bug with tlpd icon
temp created the module on broodwar wiki and adjusted it, works as intended
> Fix bug with tlpd icon

- components/infobox/wikis/starcraft/infobox_person_player_custom.lua
Add BW infobox player
under way
The stuff commented out is to be re-added once the 1v1 match data is converted to match2
(left old, right new; icons missing since the links modues have to be adjusted; clan missing intentionally until decided upon; birth date will be shown properly after bot run to switch to iso instead of the template)
R1CH will love this (left new, right old):
> Add BW infobox player

- components/infobox/wikis/starcraft/infobox_series_custom.lua
Add broodwar infobox series
new module/template
sc currently does not have an infobox series, they currently use infobox league for them ...
so comparing lpdb data etc. is not possible (well comparing to nil ...)
tested the new template on a few pages, no errors detected
> Add broodwar infobox series

- components/match2/wikis/rainbowsix/match_legacy.lua
Resolve redirect all player links (mvp & opponentPlayers) before storing in LPDB Match1 on the Rainbow6 wiki.
Tested live
> Resolve Redirect player links before storing into match1

- components/match2/wikis/valorant/match_summary.lua
* Change everything to use a mod 4 numbers
* Increased the width of side scores to account for 2 digit numbers
* Align scores to center in order to match match1
Before:
After:
Dev Module & preview
UAT by editors
> Improve CSS on Valorant MatchSummary

- components/infobox/wikis/halo/infobox_team_custom.lua
- components/infobox/wikis/rainbowsix/infobox_team_custom.lua
- components/infobox/wikis/rocketleague/infobox_team_custom.lua
- components/infobox/wikis/valorant/infobox_team_custom.lua
Remove the `File:` prefix on logo storage in lpdb_team on Halo, R6, Rl and Valorant.
`File:` prefix breaks the LPDB guidelines. 
Surrounding Template and Modules have been updated to support this change. 
Tested on R6
> Remove `File:` prefix on LPDB Team image field

- components/automatic-points-table/commons/automatic-points-table.lua
- components/automatic-points-table/commons/display.lua
- components/automatic-points-table/commons/minified-display.lua
This change is made to add a limit arg to the module to limit the number of teams displayed by the table.
Deployed in Sandbox [here](https://liquipedia.net/rocketleague/Module:Sandbox/AutoPointsTable/Rewrite/GH/9)
Example images:
- Normal table limited to 8 teams
- Minified table limited to 4 teams
> Add limit argument to limit the number of teams displayed in the table

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
- components/infobox/wikis/starcraft2/infobox_team_custom.lua
Switch MatchTicker module in 2 sc2 infoboxes player/commentator and team
The old match ticker has several issues that the new one fixes.
tested some months ago + again today
> Switch MatchTicker module in 2 sc2 infoboxes

- components/standings/standings_storage.lua
Cast numeric fields, primilary in the scoreboard, into numbers. 
/dev module
> Standings: Cast numeric fields to numbers

- components/match2/wikis/rocketleague/match_summary.lua
link was leading to insecure website
Checked if octane.gg supports https -> yes it does
> Octane.gg link should be https (RL)

- components/widget/widget_table.lua
- components/widget/widget_table_cell.lua
- components/widget/widget_table_row.lua
Create Widgets for CSS Tables based on Grids.
The TableWidget contains an Array of TableRowWidgets, which in turns has an Array of TableCellWidgets.
The inherited children from TableCells that was part of the RFC has been dropped for now.
There are various outstanding features, most specifically rowspan and colspan and also some of the CSS should be moved into Classes. To be implemented in future PRs.
> Add Widgets for CSS-Grid based tables

- components/automatic-points-table/commons/automatic-points-table.lua
This commit is made to store the rankings in lpdb objects for use in other different pages, specifically team pages
Deployed in [Sandbox](https://liquipedia.net/rocketleague/Module:Sandbox/AutoPointsTable/Rewrite/GH/10)
Here's an example of the datapoints stored:
> Add lpdb store and resolve team name redirects

- components/prize_pool/commons/prize_pool.lua
Now properly fetches the information for local currencies, and also can support multiple local currencies.
```
table#89 {
["data"] = table#90 {
["currency"] = "EUR",
["currencyText"] = "€&nbsp;<abbr title=\"Euro\">EUR</abbr>",
["symbol"] = "€",
["symbolFirst"] = true,
},
["id"] = "LOCAL_CURRENCY1",
["index"] = 1,
["type"] = "LOCAL_CURRENCY",
},
```
> Add proper support for parsing local currencies

- components/prize_pool/commons/prize_pool.lua
Uses the Widgets and prize type functions created in #1400 and #1403 respectively to display the full Prize Pool Table.
There are still some outstanding functionality, such as merging rows ("rowspan") and having proper support for Party (Solo, Duo etc) type opponents.
> Create the prizepool table

- components/prize_pool/commons/prize_pool.lua
#1374 did not have correct parsing of opponent level type (if provided). It expected a `type` key containing a json table, while in reality it should just be a `type` key containing a string.
"dev module"
> PrizePool - Fix opponent level type parsing

- components/automatic-points-table/commons/minified-display.lua
Fixes some css in order to correctly display the minified table.
[Deplayed in Sandbox](https://liquipedia.net/rocketleague/Module:Sandbox/AutoPointsTable/Rewrite/GH/11)
Here's a screenshot for the resulting table:
> Fix css for displaying minified tables

- components/infobox/wikis/starcraft/infobox_league_custom.lua
Do not resolve redirect on series value in bw infobox league.
BW wiki has several series that are displayed on the same page, hence they need to not RR them.
(I dislike it but it is what it is ...)
/dev module and pushed live afterwards
> Do not resolve redirect on series value in bw infobox league

- components/standings/standings_storage.lua
LPDB consumers are seeing issues with the scoreboard types. For example, if overtime is empty, it will be turned into an array. This PR ensures we will always save an object to LDPB.
Visual example:
Live
> Enforce scoreboard tables to be in the proper format

- components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua
depends on #1431
* order required modules alphabetically
* during heroIcon display if an invalid hero is entered add a warning (incl. a tracking category)
* store signatureHero data with standardized names instead of the entered ones
/dev module
> Store heroes standardized and add warning for invalid entries

- components/infobox/commons/infobox_person.lua
Make warnings in person infobox accessible in /Custom
/dev modules
example usage:
(adding a warning when invalid heroes are entered, since that part is in the /Custom we need to be able to access (and adjust) the warnings in the /Custom)
> Make warnings in person infobox accessible in /Custom

- components/hidden_data_box/commons/hidden_data_box.lua
- components/hidden_data_box/wikis/ageofempires/hidden_data_box_custom.lua
Add Tier validation to HiddenDataBox
- enforce valid inputs
- standardize the variable value that gets set and hence what is stored in lpdb via e.g. matches etc.
- display warnings if invalid tier/tiertype values are entered + set category
/dev modules
> Add Tier validation to HiddenDataBox

- components/infobox/wikis/mobilelegends/infobox_person_player_custom.lua
depends on #1431 
Add |heroX= input for the Signature Heroes for the ML Infobox Player 
(not really sure why It wasnt there in first place I probably forgot)
https://liquipedia.net/mobilelegends/User:Hesketh2/Test
My actual goal of this change is to allow this {{Notable Players}} template to work with a wiki that dont use SMW (such as ML), but afaik the template still dont have any LPDB version at all so I decide to update the infobox first
> Add Signature Hero input for ML Infobox Player

- components/infobox/commons/infobox_league.lua
- components/infobox/wikis/starcraft2/infobox_league_hidden.lua
Standardise parent storage
--> always use underscore instead of space
/dev module
> Standardise Infobox/League parent storage

- components/match2/commons/match_ticker/match_ticker_query.lua
Add query componnet classes for the match2 match ticker implementation.
Sandboxes
This PR together with several other PRs will set up the match2 match ticker.
See also #1066 and #1068 and #1069
> Add match ticker query components

- components/prize_pool/commons/prize_pool.lua
If there is a cash reward in a local currency and that automatic conversion of local to usd has not been turned off. Then convert the money to USD prizepool unless USD has been explicitly given.
Dependency on #1404
> Automatically convert local cash to usd

- components/match2/commons/opponent_display.lua
OpponentDisplay.PlayerInlineOpponent doesn't exist. Change to use PlayerDisplay.InlinePlayer instead for solo players.
dev module
> Don't call function that doesn't exist

- components/infobox/wikis/pubgmobile/infobox_league_custom.lua
Same implementation as #1444 , Related code are a direct paste of the mentioned PR
Briefly updated on the live module (before bot reverted) and functional well
There will be two more wikis getting the same implementation (AoV & ML) after this, Brawl is a good one to have but im not familiar with their standard infoboxes yet.
> Add Official Device for PUBGM Infobox League

- components/infobox/wikis/mobilelegends/infobox_item_custom.lua
in the old one, **critchance** became parameter for **cooldown reduction**
and **critreduction** became **critical chance**
this PR is to reflect this correctly
Going Live
> Fix params in ML Infobox Item

- components/match2/commons/opponent.lua
Add `fromLpdbStruct` and `toLpdbStruct` in `Module:Opponent` for conversion between opponent structs and lpsb storage structs for prizePool/standingEntry
/dev module
only simulated tests with made up data porting from one format to the other and back
can not really be tested as standings first would need switching to new system or lpdb_placement getting adjusted
works as intended from what i can see in the tests
with the plans for lpdb keys matching in standing entries and placements we can also import from standings to prize pools easier
> Add `fromLpdbStruct` and `toLpdbStruct` in `Module:Opponent`

- components/prize_pool/commons/prize_pool.lua
Store the prizepool data into LPDB.
Limitation in the PR: Only the standard 3 opponent types are supported (Solo, Team & Literal). No support added for other Duos etc (wouldn't be supported by the current lpdb fields anyway)
> Store data into LPDB

- components/infobox/wikis/naraka/infobox_league_custom.lua
Create Infobox League for the Naraka wiki. 
Currently tested on:
https://liquipedia.net/naraka/Module:Infobox/League/Custom/Dev
https://liquipedia.net/naraka/Europe_Scrim/June/Week_2/Solo
https://liquipedia.net/naraka/Ryomen/Results (To test if results aren't affected)
> Create infobox league for Naraka

- components/infobox/wikis/infobox_league_custom.lua
Planned to do a major cleaning of Pokemon which saw  a lot of template is over a year untouched. I decide to begin with Infobox League then later will be Match2 that was like sitting there half a year
**Based on the PUBGMOBILE Box, removed platforms with Modes and Games kept as the wiki contains multiple games, multiple modes and both teams/indivs**
The test pages <https://liquipedia.net/pokemon/User:Hesketh2/Test>
Did some quick /dev test on the main pages looks to work fine, and results reflect correctly for achievements
**I need to solve this matter before it goes trhough**
OLD INFOBOX: <https://liquipedia.net/pokemon/Template:Infobox_league>
GAME FORMAT MODULE: <https://liquipedia.net/pokemon/index.php?search=Module%3AGameFormats>
Different from other games, The old infobox in Pokemon …
> Creating Infobox League for Pokemon

- components/prize_pool/commons/prize_pool.lua
- components/widget/widget_table_cell.lua
This PR changes the stucture of `content` in a Widget Table Cell from a flat array of strings into a mixed one with support for both strings and tables with strings.
String will be handed in the same way as before, however a lua-table will be automatically wrapped in a div. This is good practice when working with flexboxes.
The changes in the Prize Pool is to adjust to this behavior & fixes the issue with overly wide columns when line breaks occur.
Using dev modules.
Old:
New:
> Add support for Wrapping content in Table Cells

- components/infobox/wikis/overwatch/infobox_person_player_custom.lua
As requested by the contributors of the wiki, this will cap the number of displayed and stored Signatures Heroes from the current number supported to three (3). 
Via Dev module and tested live
> OW hard limit for signature hero

- components/prize_pool/commons/prize_pool.lua
Add simple points storage, mirroring the method used on majority of main wikis, that being `points1` is saved into lpdb extradata field `prizepoints`.
Dev module
> Add points storage into extradata

- components/prize_pool/commons/prize_pool_legacy.lua
Old prize pools had support for `w`, `d` and `l` as valid places. The new prize pools don't (yet at least). When doing legacy conversion, map the letter places into numeric places.
Live test on https://liquipedia.net/rainbowsix/Six_Invitational/2017/PC#Prize_Pool_2 and https://liquipedia.net/rainbowsix/Six_Invitational/2020#Prize_Pool_2
> Map special letter places (w, d, l) in Legacy

- components/standings/standings_storage.lua
The LPDB Table `Standings` was recently deprecated in favor of two new DB Tables, `StandingsTable` and `StandingsEntry`. 
The PR aims to add data to the new db tables, and in the intermediate term, to the deprecated table as well. Removal storage into the deprecated table will be removed once there are no longer any consumers.
> Support new lpdb tables `standingstable` and `standingsentry`

- components/standings/standings_storage.lua
Fixed bug introduced by #1482 where sometimes the key to the slot index sometime has a capitalized `i` and sometimes not.
Live
> Fix mixed usage `.slotIndex` and `.slotindex`

- components/standings/standings_storage.lua
Scribunto has a lazy method to check for circular refences. If the same table reference is passed twice it will (incorrectly) error
This PR introduces a Table.copy to get a new reference.
Live
> Copy fallback tables before returning

- standard/class.lua
Allows some intellisense (EmmyLua and sumneko-lua) to understand the Class.export function, making intellisense useful on Modules that return via Class.export.
> Add annotations to `Class.export`

- standard/currency/currency_data.lua
Fix `isAfter` in Currency/Data.
It was incorrectly set on every single currency except USD. It is not only set where it should be.
live
> Fix `isAfter` in Currency/Date

- standard/locale.lua
- standard/region/commons/region.lua
Convert an arbitrary table input to a table intended to be stored by LPDB into the `locations` json field.
Make the current `location` parameter more granular. We are requesting the following property scheme for locations:
`venue` ➝ `city` ➝ `country` ➝ `region`
These would be added to a LPDB JSON property `locations`. It would replace the current `location` & `location2` in Teams and Tournaments. It would also make `venue` (Tournaments) and `region` (Teams) redundant. For compatibility reasons, don't remove any of the legacy properties yet.
The keys that would be part of the JSON would be as follows:
`venue` : string
`city` : string
`country` : alpha2 code, so string, but always very short. If community doesn't want alpha2, LPDB is allowed to store as full name string.
`region` : string …
> Convert data to flatten locations table (LPDB Json)

- components/infobox/commons/infobox_building.lua
- components/infobox/commons/infobox_skill.lua
- components/infobox/commons/infobox_unit.lua
- components/infobox/wikis/starcraft2/infobox_skill_ability.lua
- components/infobox/wikis/starcraft2/infobox_skill_spell.lua
Fix issue where various infoboxes calls the wrong hotkey function when there are two hotkeys.
N/A
> Infobox's calling the wrong Hotkey function

- components/match2/wikis/pokemon/matchgroup_input_custom.lua
Originally the Match2 for Pokemon was in WIP since March but I have forgot to PR it up. So its three months old there could be parts that might need retouch due to this gap
**Some pre-context to Pokemon is the wiki is a multi-game and multi-type, but by majority comes down to**
- The Mainline games (VGC) and Card Games (TCG) are just a basic 1v1 SoloOpponent bracket
- The other are Pokemon UNITE which is in general, a MOBA genre and is what this Match2 is relied on as they are loosely based on the Mobile Legends Match2 modules
As of now only Pokemon UNITE events have used these 
Example: <https://liquipedia.net/pokemon/Pokemon_UNITE_Championship_Series/2022/India>
**Differences to the MOBA Match2 are**
- Side colors in UNITE is Purple and Orange
- The length section becomes a total score …
> Create MatchGroup/Input/Custom for Pokemon

- components/match2/commons/match_group.lua
- components/match2/commons/match_group_base.lua
- components/match2/commons/match_group_display_helper.lua
- components/match2/commons/starcraft_starcraft2/player_ext_starcraft.lua
For functions where their function comment mentioning that they're deprecated, replace with a proper annotation for deprecation. Gives slight intellisense advantages.
As a result of this, 4 calls to deprecated functions have been indentified and can be resolved in future PRs.
N/A just a change in comments
> Annotate deprecated instead of just having a comment

- components/match2/wikis/brawlstars/match_legacy.lua
- components/match2/wikis/overwatch/match_legacy.lua
- components/match2/wikis/rainbowsix/match_legacy.lua
- components/match2/wikis/rocketleague/match_legacy.lua
- components/match2/wikis/starcraft/match_legacy.lua
- components/match2/wikis/starcraft2/match_legacy.lua
- components/match2/wikis/valorant/match_legacy.lua
Half of the wiki custom for `Match/Legacy` (match2 to match1) is using `p` as the module table. Update these to a better name. 
Also changed BW from `Legacy` to `MatchLegacy` to have it more uniform across the board.
> Dropped `p` as internal name in match2 to match1

- components/prize_pool/commons/prize_pool_legacy.lua
Fix typo Legacy mapping causing solo not to be detected
Live
> Fix typo Legacy mapping

- components/match2/wikis/arenaofvalor/match_legacy.lua
- components/match2/wikis/brawlstars/match_legacy.lua
- components/match2/wikis/dota2/match_legacy.lua
- components/match2/wikis/leagueoflegends/match_legacy.lua
- components/match2/wikis/mobilelegends/match_legacy.lua
- components/match2/wikis/overwatch/match_legacy.lua
- components/match2/wikis/rainbowsix/match_legacy.lua
- components/match2/wikis/rocketleague/match_legacy.lua
- components/match2/wikis/starcraft/match_legacy.lua
- components/match2/wikis/starcraft2/match_legacy.lua
- components/match2/wikis/valorant/match_legacy.lua
- components/match2/wikis/wildrift/match_legacy.lua
**Not added for SC1 and SC2** - they were doing a bunch of extra stuff and I think it's better if @hjpalpha does it instead just so the business logic gets correct.
Module:Match sends a second parameter in its call to Module:Match/Legacy, `options`, with info if it should be converted to match1 and/or smw. None of the current implementations respect those. Updated so they do.
Tested on R6 with dev modules
> Have match2-to-match1 respect store flags.

- components/prize_pool/commons/prize_pool_legacy.lua
Currently, `|points=seed` will work, but not `|points=Seed` when detecting a qualifier. Fix this by lowercasing the input before checking.
Before:
After:
> Fix case sensitivity of seed in Prize Pool Legacy

- components/match2/wikis/halo/match_summary.lua
- components/match2/wikis/rocketleague/legacy/match_group_legacy_default.lua
- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/sideswipe/match_group_input_custom.lua
- components/match2/wikis/starcraft/legacy/match_group_legacy_default.lua
- components/match2/wikis/starcraft2/legacy/match_group_legacy_default.lua
Remove remaining usages of `p` as internal module names in the code base.
Tested the RL Input change with dev modules, as there's technically logic change there. Rest are just renames
> Remove uses of `p` in favor of better names

- components/prize_pool/commons/prize_pool.lua
To match old width behavior
After:
Before:
Tested using dev modules
> Add min-width to place, team & player columns

- components/match2/commons/opponent_display.lua
Unless explicitly showLink is given, TBD's links will be hidden by default.
SC2 already has the same behavior implemented
dev module
> Make the default behavior of TBD is to hide the link

- components/prize_pool/commons/prize_pool.lua
Supply OpponentType information when it comes to TBDs. 
This has the intended side effect of adding (filler) icons to team TBDs.
/dev module
> Correct OpponentType on TBDs

- components/match2/commons/opponent_display.lua
This css-class stops the ability for mouse pointer to change while hoovering over items. The biggest issue with this is that abbr's don't work while this is set. It brings no real advantage, and starcraft2 has already remove its usage from their implementations.  Hence suggesting we remove it from the common library as well.
CSS Preview mode, removing the class there and made sure nothing breaks.
> Remove css class that causes issues

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Allow `u` as valid race entry in maps for players in team matches
/dev module
> Allow `u` as valid race entry in maps for players in team matches

- components/infobox/commons/infobox_league.lua
- components/infobox/commons/infobox_widget_header.lua
- components/infobox/extensions/commons/metadata_generator.lua
- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Set the metaImage and metaDescl tags allowing for embeds.
The image is set to the primary image of the league. 
Dev modules initially then live on R6 to get a good sample size.
> SEO Tags for Infobox League

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Do not default to `u` for manual race input per map
/dev & live (can't test for singlematch in /dev atm due to prep for #1154)
> Do not default to `u` for manual race input per map

- components/prize_pool/commons/prize_pool.lua
Tournament Pags can be moved, and then the `|qualifies=` link can become invalid, even though there's a redirect in place.
This PR solves this by doing a resolve redirect on the tournament links.
Dev module
Before:
After:
> Resolve Redirect Tournament Links

- components/prize_pool/wikis/valorant/prize_pool_legacy_custom.lua
Valorant Legacy has a slightly different naming scheme to enable the prize summary. 
Made a short custom to handle their way.
Without Custom:
With Custom:
> Create Legacy Custom for Valorant PPT

- components/prize_pool/wikis/valorant/prize_pool_legacy_custom.lua
Valorant can run thier local currency directly from the infobox into their prize pool table. 
This PR add support for this in their legacy handling.
In a future PR, should look at either adding support for this in Commons PPT alternatively in Valorant custom PPT.
Live
> Fix localcurrency in Valorant Legacy

- components/prize_pool/wikis/valorant/prize_pool_legacy_custom.lua
Valorant inserts tournament logos as points on occasion. 
In the current handling, it gives the following effect (the PPT tries it's best to find a number in there)
After a discussion on the Valorant Discord channel, it was decided to at least temporary hide it until a final decision has been made once more Editors are online
Live
> Remove images in points in Valorant's legacy PPT

- components/prize_pool/commons/prize_pool_legacy.lua
The fields `lastscore` and `lastvscore` were merged in the new PPT. Update the legacy mapping to correctly reflect this
Live
> Fix lastscore not working in Legacy Mapping

- components/prize_pool/commons/prize_pool_legacy.lua
Automatically retrieve the display part of a link and sets it as the display name for a tournament in legacy.
This stops red links where there previously weren't any before new PPT.
Before:
After:
Tested on dota2
> Automatically get the Tournament Name in PPT Legacy

- components/prize_pool/wikis/dota2/prize_pool_legacy_custom.lua
Dota2 has some of same variations that Valorant has, specifically the wiki variable to set local currency and that the prizesummary is called prizenote.
Gives -> (PrizeNote is correctly mapped to Prizesummary and the currency is set from the Infobox)
> Create Legacy Custom for dota2

- components/match2/commons/opponent_display.lua
Taken from OpponentDisplay/downstreams.
Remove the link from the icon in addition to the actual link, if links should not be given.
Slight known issue: the alignment change done around the same time this PR was opened assumes the <a> is in place. After this PR is merged, the alignment change will be tweaked to reflect the new situation.
/dev module
> Remove Icon Link if links should be removed in Team Display

- components/infobox/commons/infobox_team.lua
Many wikis, such as Valorant and Counter strike have additional staff roles added to the infobox.
This PR makes the entire section with staff roles a customizable, allowing for wikis to add new roles in the same section as the current roles.
> In Infobox Team, make Staff a customizable.

- components/infobox/wikis/counterstrike/infobox_team_custom.lua
Create the Customizable for Team Infobox on Counter Strike.
Template based:
New Module:
LPDB Before:
LPDB After:
Tested using dev module on Navi's page
> Create Team Infobox for CS

- components/infobox/wikis/counterstrike/infobox_team_custom.lua
Missed to overwrite the standard function, making the custom not called.
Live
> Fix missing override in Team infobox

- components/prize_pool/commons/prize_pool.lua
`Opponent.readOpponentArgs` only returns nil for missing team templates. This PR adds support to detect other types of TBDs and set them to the TBD Opponent.
Before:
After:
> Fix TBD handling for Party Opponents

- components/infobox/commons/infobox_widget_header.lua
The old template infobox's linked directly to the template (which shows the documentation as well), not to the doc page.
Let's change the behavior the match that of old. The current behavior wasn't something that was actively decided on based on this discsussion.
Tested using dev module.
> Remove the /doc part of the link when linking to template

- components/match2/commons/opponent_display.lua
Since PR #1514, the default behavior of Team TBDs is to hide the link unless forced active. This PR brings the same functionality to Party TBDs.
Dev Module
> Party TBDs - hide link by default

- components/infobox/extensions/commons/metadata_generator.lua
`mw.title.getCurrentTitle()` gets the title object. Need to have a string. Let's use `.text` (https://www.mediawiki.org/wiki/Extension:Scribunto/Lua_reference_manual#Title_objects) 
Live
> Metadata Generator - Fix typo in name fallback

- components/prize_pool/commons/prize_pool.lua
Incorrect lua regex (`-` needs to be `%` escaped in lua...). 
```lua
mw.log(string.match('2022-05-20', '%d%d%d%d-%d%d-%d%d'))
-- nil
mw.log(string.match('2022-05-20', '%d%d%d%d%-%d%d%-%d%d'))
-- 2022-05-20
mw.log(string.match('not a date', '%d%d%d%d%-%d%d%-%d%d'))
-- nil
```
> Fix Date Validation in Prize Pool

- components/infobox/commons/infobox_widget_links.lua
- standard/links/commons/links.lua
Add link to Esportal.
Update link for ESEA-D (esea-division) to use esea-league icon instead of esea icon.
N/A
> Add Esportal link, update icon for ESEA-D

- standard/region/extensions/ept_data.lua
Add `Non-representing` support to EPT Regions stuff
live
before it did not display the `1` in the "Others" region, it displayed `NYD` instead:
https://cdn.discordapp.com/attachments/213614988647071744/1000907907178713239/unknown.png
before it did not display the non-rep. flag in the "Others" region, it displayed it without region (transparent BG)
> Add `Non-representing` support to EPT Regions stuff

- plugins/sumneko_plugin.lua
Sumenko is the biggest lua extension for VSCode and Neovim. However much of the intellisense for the modules is unusable as the extension cannot map between our requires and the files in our repo (both the Module prefix and the different naming schemes causes the failure).
This PR implements a plugin that helps the intellisense to locate the correct file.
How it works it by automatically, under the hood, annotates all imports with `---module '...'` where `...` is a findable name for the intellisense engine. The annotation is not set in the lua code, but is set in the code read and consumed by the extension.
> Create a plugin for the sumenko extension

- standard/flags.lua
On the wiki flag templates are always written with lowercase names.
Have the fallback scenario lowercase the flag name before calling the template.
Tested on CS
> In flags template fallback, lowercase the flag name

- components/infobox/commons/infobox_league.lua
- components/infobox/commons/infobox_team.lua
Currently the categories why `Country Tournaments` and `Country Teams` are set in Userspace. No other category, except for warning/error categories, are set in mainspace by default. This PR solves this issue.
Tested with dev modules
> Change so all categories are only set in mainspace

- components/infobox/commons/infobox_league.lua
Missed two categories that were set in a different way that are being displayed in userspace still. Can be considered a followup on #1576.
> Two more categories not to display in userspace

- standard/links/commons/links.lua
- standard/links/wikis/counterstrike/links_custom_data.lua
- standard/links/wikis/rainbowsix/links_custom_data.lua
Faceit links require the language code now days.
Add `/en`
https://www.faceit.com/players/Bennermaster
https://www.faceit.com/en/players/Bennermaster
Live on CS
> Fix faceit player & team links

- components/match2/commons/match.lua
- components/match2/commons/match_group_input.lua
Store tournament in match2games (using the value from the match)
/dev module (via logging before the table gets passed to lpdb, since lpdb_match2game.tournament did not yet exist as a key)
> Store `tournament` in `match2games`

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
Limit queried keys to lower the used lua memory significantly (on https://liquipedia.net/starcraft2/Bly from ~46 MB down to ~25MB; the page didn't load before the change)
mainly match2games takes up a significant chunk but is neither needed inside the infobox nor inside the matchticker to which the first 5 matches are passed
live
> Limit queried keys to lower the used lua memory significantly

- components/infobox/commons/infobox_company.lua
- components/infobox/commons/infobox_game.lua
- components/infobox/commons/infobox_league.lua
- components/infobox/commons/infobox_person_user_custom.lua
- components/infobox/commons/infobox_scene.lua
- components/infobox/commons/infobox_series.lua
- components/infobox/commons/infobox_unit.lua
- components/infobox/commons/infobox_unofficial_world_champion.lua
- components/infobox/commons/infobox_website.lua
Most of the stuff I changed was just text fields addressing #1323. The only code change made was adding dynamic organizer row singular/plural support. Was copied from infobox_league.lua so it should work. But tested anyway here: https://liquipedia.net/counterstrike/User:IMarbot/test_series_infobox (working as intended).
> Adressing lack of consistent capitalization (fix #1323)

- components/infobox/wikis/starcraft2/infobox_person_player_custom.lua
Pass along 10 instead of 5 matches from infobox to matchticker
This is so that in case matchticker finds matches to exclude it still has enough matches available
N/A just a number change
> Pass along 10 instead of 5 matches

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Currently the `tournament_prizepoolusd` is being set by the default handling of PrizePool in Infobox Leauge on CS wiki. Whilst mostly fine, for tournaments without a prize pool set in usd, `tournament_prizepoolusd` will not be updated by the CS custom. This has the side effect of storing an auto converted prize pool from local to usd into LPDB (but not displaying it anywhere on the page). This causes consumers of this LPDB data (Tournament Lists) to get the auto converted USD prize. 
Live on CS.
> Infobox League CS: Always set USD Prize Pool wiki-var

- components/infobox/commons/infobox_league.lua
Currently we always use "TierDisplay Tournament" for the portal link. This PR allows wikis to have a Link table defined in Module:Tier (see CS for example) with specifically defined links for tiers.
Dev Module, tested on CS (has link table) & R6 (does not have link table)
> Add support for using (Module:Tier).link to get set tier link

- components/infobox/commons/infobox_league.lua
#1265 added the field `mode` to LPDB Tournament.
Have Infobox League store it by default, by using the standard (wiki-custom) wiki-variable `tournament_mode`.
Dev module
> Store Mode into LPDB from Infobox League

- components/infobox/commons/infobox_character.lua
- components/infobox/commons/infobox_hero.lua
Creates a new Infobox called Character, that is meant to serve as the base for the Infoboxes: Hero, Agent, Operator, Legend, Character and Champion. 
Having spent some time looking at the infoboxes across various wikis, it would be a nightmare to combine them all into 1 infobox. My suggestion is to have a ``Infobox/Character/MOBBA`` (or something to that effect) that would account for the base parameters for wikis like League of Legends, Wild Rift, Dota 2, Mobile Legends and other very similar wikis. Otherwise you would have massive ``/Custom`` modules for those wikis that repeat a lot of the same functionality
Tested via test [page](https://liquipedia.net/commons/User:Fenrir.SPAZ/Infobox_Hero)
> Create Infobox Character

- components/match2/commons/starcraft_starcraft2/opponent_starcraft.lua
Add to and from LpdbStruct sc/sc2 specifics (race/faction and archon stuff)
stacked on #1387
also needs #1388 
/dev module
only simulated tests with made up data porting from one format to the other and back
can not really be tested as standings first would need switching to new system or lpdb_placement getting adjusted
works as intended from what i can see in the tests
with the plans for lpdb keys matching in standing entries and placements we can also import from standings to prize pools easier
> Add to and from LpdbStruct sc/sc2 specifics

- components/match2/commons/match_group_util.lua
Adjust `fetchMatchForBracketDisplay `
->  add option to not combine match and bracketResetMatch but instead return them seperately
usecase see: #1566
/dev module
> Adjust `fetchMatchForBracketDisplay `

- components/infobox/commons/infobox_person.lua
Used for handling names for players with multiple names / combined last names. To then correctly give the short version for the player-intro and the Automated squad tables
https://liquipedia.net/apexlegends/Hardecki
Currently in use on Hardecki
<!--
Demonstrate the code is solid. Example: The exact pages you used to test this change, screenshots / videos if the pull request changes the user interface.
How exactly did you verify that your PR solves the issue you wanted to solve?
If you leave this empty, your PR will very likely be closed.
Things to be particularly aware of:
For the future, certain countries would have the order flipped (For player intro and squadtables) E.g South Korea, China etc. Still need to fully find editor consencus but that would need to be added most likely
> Adding support for given/family names.

- components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
Depends on #1569
Rework SC/SC2 matchSummary display for bracketResets.
before:
after:
/dev modules
> Rework SC/SC2 matchSummary display for bracketResets

- components/match2/commons/match_group_display_helper.lua
Due to insufficient testing in #1393, a bug slipped through in one of the cases. Fix was immediately put on the live server but no PR was opened (due to none-working hours). nbsp isn't read by the countdown JS as a space, and hence it cannot parse the date. Switch it intoa normal space.
Live since Friday.
> Fix bug in match2 Countdown

- components/infobox/commons/infobox_weapon.lua
Adds default support for LPDB storage for the Weapon Infobox. Also adjusts a few fields to be customizable to help support custom module saving. 
Tested via dev module and testing pages
> Store Weapons into LPDB + Update Game appearances cell name

- components/prize_pool/commons/prize_pool.lua
Store the new LPDB field `prizepoolindex` into lpdb placements.
> Store Prize Pool Index in Prize Pool Tables

- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Adjust cancelled_tournament handling in sc/sc2 match2
Namely still set scores and resulttypes based on score/map entered data, only if that is not available fall back to setting
resulttype as `'np'` and scores as `-1`
/dev module
> Adjust cancelled_tournament handling in sc/sc2 match2

- components/prize_pool/wikis/apexlegends/prize_pool_custom.lua
Added the prizepoints. (Alongside a changed TeamCard)
Added support for prizepoints so ALGS ranking pages can be automated
Affected tournament page and ranking page:
https://liquipedia.net/apexlegends/Apex_Legends_Global_Series/2022/Split_2/Playoffs
https://liquipedia.net/apexlegends/Apex_Legends_Global_Series/2021-22/Rankings/EMEA
Results still working:
https://liquipedia.net/apexlegends/K4shera/Results
https://liquipedia.net/apexlegends/Acend/Results
Tested on the following pages.
> Added support for prizepoints.

- components/match2/commons/match_group_input.lua
Add default header support for GSL style matchlists
suggested by CS, but imo a net gain for all wikis, as that format is quite common across wikis
/dev module
> Add default header support for GSL style matchlists

- components/infobox/wikis/leagueoflegends/infobox_person_player_custom.lua
Forces any input that is has an alphabetical character as its first character to be capitalized for the status input. 
This reduces the need of a bot run to correct instances of ``|status=active`` to ``|status=Active``. Most of the input was already capitalized, this standardizes it
Tested live via a /dev module
> Player Infobox - Uppercase first letter in status

- components/hidden_data_box/commons/hidden_data_box.lua
- components/hidden_data_box/commons/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/ageofempires/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/starcraft2/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/wildrift/hidden_data_box_custom.lua
Cleanup of HDB:
* Move from `:` to `.`, as no instance is ever being created
* Simplify `cleanDate` function
* Add support for legacy tier formatting in `validateTier`
* Change some `== 'true'` to `Logic.readBool()`
* Added warning for invalid parent
Participant Fetching:
* Add participant (player/staff of teams) fetcher. 
* * This information is retrieved from Placements LPDB, which is being set by the Team Cards.
* * The variables set can be overwritten by the wiki custom
Tested on R6 so far with dev module. TCFetch seems to work. 
Testing needs to be done on existing user of it. Some fields are not being set on R6, most likely because of lack of Custom var setting.
> Add Participant Fetching & Cleaning the code

- components/infobox/wikis/apexlegends/infobox_league_custom.lua
> Add "individual" to tournament_extradata

- components/infobox/wikis/counterstrike/infobox_person_player_custom.lua
CS uses `|steam=` input for what would be `link.steamalternative`. Map the input accordingly.
Live
> Map CS Steam to SteamAlternative

- components/match2/wikis/brawlstars/match_summary.lua
- components/match2/wikis/dota2/match_summary.lua
- components/match2/wikis/leagueoflegends/match_summary.lua
- components/match2/wikis/overwatch/match_summary.lua
- components/match2/wikis/rainbowsix/match_summary.lua
- components/match2/wikis/splitgate/match_summary.lua
Adjust some icons to use darkmode friendly versions
`LiveReport.png` --> `LiveReport32.png`
`Preview Icon.png` --> `Preview Icon32.png`
`Writers Icon.png` --> `Reviews32.png`
n/a, just switching file targets
> Adjust some icons to use darkmode friendly versions

- components/match2/commons/get_match_group_copy_paste.lua
- components/match2/commons/get_match_group_copy_paste_wiki_base.lua
- components/match2/commons/starcraft_starcraft2/get_match_group_copy_paste_starcraft.lua
* let `.getStart` function adjust args if necessary (so that wikis can adjust args based on other values in args; see)
for that also move the `getStart` calls before args is read for further params
example use case: <https://liquipedia.net/counterstrike/Module:GetMatchGroupCopyPaste/wiki/dev>
* cleanup (tonumber casts, using Logic.readBool, sorting requires in alphab order, `"` --> `'`)
/dev modules + /dev template + /dev form
> Adjust match2 copy paste to be a bit more customizable + cleanup

- components/squad/wikis/leagueoflegends/squad_custom.lua
Create Custom Squad implementation for League of Legends. It's a based of a mix of R6 (since League partially uses AutoSquadTables) and dota2 (since both League and dota2 has positions).
Test scenarios:
**Squad Auto Active:**
Old: 
New:
**Squad Auto Former:**
Old:
New:
**Manual Active:**
Old:
New:
**Manual Former:**
Old:
New:
> Create Squad Custom for League

- components/squad/wikis/leagueoflegends/squad_custom.lua
The current link code expects `|page=`, due to the property is called `page` in the automatic squad table. The manual table should still accept `|link=`. This PR changes the fields the row looks for from `page` to `link`, and maps the auto tables `page` to `link`.
Live since last night
> Fix `|link=` in manual squad tables on League

- standard/links/commons/links.lua
CyberGamer was acquired by LPL and is already setup as an alias of LPL, it shouldn't be here.
Live
> Remove cybergamer from Links

- components/match2/commons/match.lua
- components/match2/commons/match_group_input.lua
- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
- components/match2/commons/starcraft_starcraft2/match_group_input_starcraft_ffa.lua
- components/match2/wikis/arenaofvalor/matchgroup_input_custom.lua
- components/match2/wikis/brawlstars/match_group_input_custom.lua
- components/match2/wikis/dota2/matchgroup_input_custom.lua
- components/match2/wikis/halo/match_group_input_custom.lua
- components/match2/wikis/leagueoflegends/matchgroup_input_custom.lua
- components/match2/wikis/mobilelegends/matchgroup_input_custom.lua
- components/match2/wikis/overwatch/match_group_input_custom.lua
- components/match2/wikis/pokemon/matchgroup_input_custom.lua
- components/match2/wikis/rainbowsix/match_group_input_custom.lua
- components/match2/wikis/rocketleague/match_group_input_custom.lua
- components/match2/wikis/sideswipe/match_group_input_custom.lua
- components/match2/wikis/splitgate/match_group_input_custom.lua
- components/match2/wikis/valorant/match_group_input_custom.lua
- components/match2/wikis/wildrift/match_group_input_custom.lua
Add timeZone storage to match2 & move common extradata to commons
/dev modules
> Add basic (common) match2 extradata lpdb storage

- components/hidden_data_box/wikis/rocketleague/hidden_data_box_custom.lua
Create HDB custom for RL, setting the custom wiki vars that RL are setting in their current template based HDB.
Dev template and compared the data in LPDB on a test page. Dark Icon & Players are actually stored now on matches on subpages (which they weren't before).
> Create HDB for Rocket League

- components/hidden_data_box/wikis/valorant/hidden_data_box_custom.lua
Create HDB custom for Valorant, setting the custom wiki vars that Valorant are setting in their current template based HDB.
Also fixed match1 players being broken, opted to not include flags atm (since they were broken before anyway and it would complicate stuff).
Dev template and compared the data in LPDB on a test page.
> Create HDB for Valorant

- components/infobox/wikis/wildrift/infobox_person_player_custom.lua
Since the League of Legends player infobox was standardized, the Wild Rift module can easily be moved over as well as the wikis are set up in the same way.
Tested on the following page:
https://liquipedia.net/wildrift/Guyler
PlayerIntroduction has been updated along to fix the one issue with PlayerTeamAuto initially not working.
> Set up Custom Player Module for Wild Rift

- components/match2/wikis/dota2/match_summary.lua
Fix typo in dota2 matchsummary
requested by trev: https://discord.com/channels/93055209017729024/372075546231832576/1006057649852391445
N/A
> Fix typo in dota2 matchsummary

- components/match2/commons/opponent.lua
- components/prize_pool/commons/prize_pool.lua
This modifies `Module:Opponent`, function `resolve` to optionally load flags and teams for players.
The data is fetched via `Module:Player/Ext`, so either comes from wikivars, match2 or lpdb.
According options are added to `Module:PrizePool`. The feature is disabled by default.
Tested with [Opponent/dev](https://liquipedia.net/commons/Module:Opponent/dev), [PrizePool/dev](https://liquipedia.net/commons/Module:PrizePool/dev), and different configurations of [AoE:PrizePool/Custom](https://liquipedia.net/ageofempires/Module:PrizePool/Custom).
> Allow PrizePool to fetch flags for party opponents

- components/hidden_data_box/wikis/dota2/hidden_data_box_custom.lua
Create HDB for dota2 wiki. Hope I got everything right, since they fetched info with SMW previously (only wiki I know to do that)
Tested on a page with match1
Waiting for Arlington Group Stages to finish (tonight) before testing on one with match2. Arlington is the only match2 page with HDB
> Create HDB for dota2

- components/match2/commons/match_group_util.lua
- components/match2/commons/opponent_display.lua
- components/match2/commons/player_display.lua
- components/match2/commons/starcraft_starcraft2/opponent_display_starcraft.lua
- components/match2/commons/starcraft_starcraft2/player_display_starcraft.lua
- components/prize_pool/commons/prize_pool.lua
Update non team opponent display in prize pools
* support duo, trio, ... opponent types
* display playerTeam for non team opponents as an icon besides the players instead of in an extra column
this matches the display in participant tables (for solo opponents)
* adjust storage for non-solo non-team opponents a bit (participantflag)
/dev modules
This needed some slight css additions, so either needs a cache flush or waiting until cache expires^^
https://liquipedia.net/commons/index.php?title=MediaWiki%3ACommon.css%2FBrackets.css&type=revision&diff=442043&oldid=441187
> Update non team opponent display in prize pools

- components/match2/wikis/counterstrike/match_legacy.lua
The icondark in `match.extradata` was being set using the wrong variable. After fixing that error, a new revision to extradata fields was made, to ensure they match exactly the fields set by match1, both in name and type.
Compared the extradata fields from match, and match set via match2 input.
[ESEA Season 41: Advanced Division - Europe](https://liquipedia.net/counterstrike/Special:LiquipediaDB/ESEA/Season_41/Advanced/Europe)
`{"opponent1rounds":"33","maps":"Ancient,Mirage,Overpass","timezoneID":"CEST","featured":"0","hidden":"0","timezone":"+2:00","matchsection":"","overturned":"","bestofx":"3","opponent2rounds":"45","team1icon":"CSGO default lightmode.png","cancelled":"","icondark":"","team2icon":"Apeks 2021 lightmode.png"}`
[FiReLEAGUE 2022: Argentinian …
> Fix match legacy extradata values

- components/hidden_data_box/wikis/leagueoflegends/hidden_data_box_custom.lua
Create Hidden Data Box for League of Legends. 
Tested on two tournaments with dev template. One using match1 and one using match2. Only difference was slightly improvement (short name and darkicon were mapped unlike the old one).
> Create HDB for League of Legends

- components/hidden_data_box/wikis/counterstrike/hidden_data_box_custom.lua
Have removed the usage on CS where they, in match1, uses wiki-arrays (changed into wiki-vars). This simplifies TC and HDB, especially the latter.
Tested with dev module on Antwerp Major
> Create HDB for CounterStrike

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
- components/infobox/wikis/starcraft2/infobox_league_hidden.lua
depends on #1638
Adjust sc2 infobox league (+hidden) to use `Module:Currency`
/dev modules
> Adjust sc2 infobox league (+hidden) to use `Module:Currency`

- components/infobox/commons/infobox_widget_links.lua
- components/match2/wikis/leagueoflegends/match_group_input_custom.lua
- components/match2/wikis/leagueoflegends/match_summary.lua
- standard/links/commons/links.lua
Add FactorGG (https://www.factor.gg/) support to:
* Match2 on League
* Player & Team Links (inc sorting).
> Add FactorGG support (League match2, Links, Widget Sorting)

- components/infobox/wikis/leagueoflegends/infobox_league_custom.lua
Creates a new League Infobox for League of Legends
[testing page](https://liquipedia.net/leagueoflegends/User:Fenrir.SPAZ/newleagues)
Tested using dev template on LCS 2022 Summar. Both Preview and LPDB looked fine, barring one thing. 
LPDB Organizers and Sponsors aren't saved properly, due to wikicode not matching (full links, all in one param). This needs to be botted or manually fixed on tournament after live)
> LoL League Infobox

- components/infobox/wikis/leagueoflegends/infobox_league_custom.lua
Fallback tickername to shortname on LoL's Infobox League.
Requested by Admins.
Live
> LoL League: Fallback tickername to shortname

- components/hidden_data_box/wikis/ageofempires/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/dota2/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/leagueoflegends/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/starcraft2/hidden_data_box_custom.lua
- components/hidden_data_box/wikis/valorant/hidden_data_box_custom.lua
If the parent doesn't exist, `queryResult`will be an empty table when given to `addCustomVariables`. In wikis going into the `extradata`, ensure that it exists.
Live on league of legends since last night.
> Default extradata before usage in HDB Customs

- components/match2/wikis/counterstrike/match_group_input_custom.lua
Sometimes an external link for a map stats page can be set while the name of the map still empty. Usually, it happens in ESEA events where we know the map stats page before the map veto happens.
Using `/dev` module.
> Change the call order of match.getLinks

- components/prize_pool/commons/prize_pool_legacy.lua
Handle the special case most wikis had in their Template based PPTs, which was `|points=q` to create a checkbox, with an optional `|link=`
> PPT Legacy: Map `q` to checkmark

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_legacy.lua
Resolves #1544
* Allow for special scores to be inputted in Last Score
* In legacy commons, have a default handler for `walkovertoX`, `wotoX`, `walkoverfromX` & `wofromX`.
Dev module (both normal & legacy)
> Add support for special score in PPT (W,FF,DQ,L,D)

- components/match2/commons/opponent.lua
- components/match2/commons/starcraft_starcraft2/opponent_starcraft.lua
- components/prize_pool/commons/prize_pool.lua
Adjust handling of missing TTs in opponents
Display the warning instead of using tbd as fallbacks
/dev modules
> Adjust handling of missing TTs in opponents

- components/match2/wikis/leagueoflegends/match_legacy.lua
League needs parent in game1. This PR sets the value into extradata.
Live
> Set parent into extradata in game1

- components/prize_pool/commons/prize_pool.lua
- components/prize_pool/commons/prize_pool_legacy.lua
Currently `Placement:_parseOpponentArgs` will discard any Literals as `Opponent.isTbd` will return true for any and all literals.
This PR adds allows literals not to be automatically discarded and used as is instead. The PR also adds handling of `|literalX=` in legacy PPTs.
Dev module
> Support Literals in PPT

- components/match2/commons/starcraft_starcraft2/opponent_starcraft.lua
- rename stuff according to renames in `Module:Opponent`
- add a missing key during indexing
/dev modules in combination with testing for adding standardized storage of standings via sc/sc2 group table league
> Fix Module:Opponent/Starcraft

- components/prize_pool/commons/prize_pool.lua
Changes the word `teams` to `participants` in the prizenote, matching the column header and fitting all wikis.
N/A
> Change 'teams' to 'participants' in the prizepool prizenote

- components/match2/commons/opponent.lua
Call Opponent.toName only if player.team is not nil in function toLpdbStruct
/dev module
> Call Opponent.toName only if player.team is not nil

- components/match2/wikis/counterstrike/get_match_group_copy_paste_wiki.lua
Some tabs and newlines were removed from match copy/paste, to make the output tidier.
Also, a new function was created to handle the creation of a set.
Using [MatchListCopyPaste/dev](https://liquipedia.net/counterstrike/Special:RunQuery/MatchListCopyPaste/dev).
> Tidy up counterstrike match copy paste

- components/prize_pool/commons/prize_pool_legacy.lua
If the `|seed=` is just a wiki-link without a displaytext (`[[Link]]`), but it could not be parsed by the `parseWikiLink` function. This PR resolves that issue
Tested with /dev module
> Make links without displaytext parsable by PP Legacy 

- components/prize_pool/commons/prize_pool.lua
- standard/currency/currency.lua
Allow wikis to decide on the rounding precision in prize pool currency values
- adjust PP
- adjust Currency.formatMoney
/dev
> Allow wikis to decide on the rounding precision in prize pool currency values

- components/infobox/wikis/valorant/infobox_league_custom.lua
Add category for Female Tournaments in Valorant's `Infobox league`.
/dev Module
> VAL: Add category for Female Tournaments

- components/prize_pool/wikis/counterstrike/prize_pool_custom.lua
CounterStrike is using the `placement.qualified` flag in their tournament lists. Have the new PPT set it.
Dev module
> Save Qualified LPDB field on CS

- components/prize_pool/commons/prize_pool.lua
The PPT currently sorts columns based on prize types. However for two prizes that change that same type the order is arbitrary. This PR will add a secondary sort based on the index (ie POINTS1 will be sorted to be before POINTS2).
dev module
> Improve column sorting of Prizes

- components/infobox/wikis/valorant/infobox_person_player_custom.lua
Added more roles to Valorant's `Infobox player` to support common roles for broadcast talents in order to switch from `Infobox commentator`
/dev Module
> Add more roles to VAL Infobox Player

- components/match2/wikis/counterstrike/match_legacy.lua
Always set `match.extradata.bestofx`. Doing this previously was messing the `SwissTableLeague` that only relied on the field being set to display either map or score in swiss cell.
Tested on Live pages using both `SwissTableLeague` and match2.
> Always set bestofx in match legacy

- components/infobox/wikis/counterstrike/infobox_league_custom.lua
Respect the disable lpdb/smw storage wiki-variables that indicate that LPDB data and categories shouldn't be set.
Live
> Respect disable LPDB/SMW storage on CS League Infobox

- components/match2/commons/get_match_group_copy_paste.lua
- components/match2/wikis/counterstrike/get_match_group_copy_paste_wiki.lua
Allow unnamed matchParams for matchlists in copy paste (requested by cs)
/dev
> Allow unnamed matchParams for matchlists in copy paste

- components/prize_pool/commons/prize_pool.lua
Add option to add a manual (override) link to a points prize type similiar how data can be overriden in the Qualifier prize type.
Dev module
> Add option to override a point's link

- components/match2/wikis/counterstrike/match_summary.lua
If match has `faceit`and `cstats`link there should be a dot in the middle.
Using `/dev` module.
> Only reset iconsInserted if dot is inserted

- components/notability/wikis/apexlegends/notability_checker_config.lua
Summary:
Created NotabilityChecker.config to work with commons notability checker
Shows the side by side comparison of the old local version and the new commons version. The old version separately displays coach/player notability, but accounting for that, the values are the same
Page here for testing (change to /dev template call for the commons version)
https://liquipedia.net/apexlegends/User:Dark_meluca/NotabilityTest
> NotabilityChecker config file for apexlegends wiki

- components/infobox/wikis/starcraft2/infobox_league_custom.lua
Catch case of `prizepoolusd` without `prizepool`
live
> Catch case of `prizepoolusd` without `prizepool`

- components/standings/standings_storage.lua
Currently the standingstable.matches  value is 
```
"matches": {
"1": "2Uem5SbOHQ_0001",
"2": "2Uem5SbOHQ_0002",
"3": "2Uem5SbOHQ_0003" 
},
```
AND when empty it is 
```"matches": [],```
Change this to be 1 type:
Array of string 
```"matches":["2Uem5SbOHQ_0001","2Uem5SbOHQ_0002","2Uem5SbOHQ_0003"]```
when empty
```"matches":[]```
Live
> Use Json.Stringify for standings matches

- components/match2/commons/match_summary_base.lua
Prepare match footer icons for darkmode
analogous to #1611
to be done
> Prepare match footer icons for darkmode

- components/infobox/wikis/mobilelegends/infobox_hero_custom.lua
The MLBB Editors were requesting **Region and City** text labels, since this is bit different from LoL that Region/City do not  contain its own icon so they need only just Text Label. The rest were untouched, just two more text labels
/Dev
from: <https://liquipedia.net/mobilelegends/Tigreal>
<https://liquipedia.net/mobilelegends/Module:Infobox/Unit/Hero/dev>
- I remember that Rathoz is on Vacation, so I have add both Rath and Jasper (Vogan) for this case.
- I'm looking to push ML to Full Wiki this week or so (as I want to timed it with a competitive scene-related announcement this week) so If I can get this merged before we reach Saturday would be a great timing
> Add additional text label for ML Hero Infobox

- components/match2/commons/match_summary_base.lua
Add `Footer:addLinks` function to matchSummary/Base
the function supports darkmode icons
examples & usecase see #
/dev together with #
> Add `Footer:addLinks` function to matchSummary/Base

- components/match2/wikis/dota2/match_summary.lua
- components/match2/wikis/leagueoflegends/match_summary.lua
- Added a class to the div that groups the thumbs. 
- Added 
`.brkts-popup-body-element-thumbs {
flex: 1;
}`
to the [brackets.css](https://liquipedia.net/commons/MediaWiki:Common.css/Brackets.css). This allows the group thumbs to go to the next line if needed:
> LPA-5872 match2 on web: Gameline breaks on < 450px on Dota2 and LoL(LPA-5875)

- components/match2/wikis/rainbowsix/match_summary.lua
depending on #1702 
Use `footer:addLinks` in R6 MatchSummary to enable darkmode support in match2 footers (together with #1702 & #1612)
/dev
current:
proposed:
> Use `footer:addLinks` in R6 MatchSummary

- components/match2/wikis/overwatch/match_group_input_custom.lua
- components/match2/wikis/overwatch/match_summary.lua
depending on #1702 
* Use `footer:addLinks` in OW MatchSummary to enable darkmode support in match2 footers (together with #1702 & #1612)
* Kick `pllg` as per request by OW contributors (Laus) --> also solves last missing icon
/dev
Get DarkMode Icon for:
--> got kicked instead
> Use `footer:addLinks` in OW MatchSummary

- components/match2/wikis/starcraft/legacy/match_group_legacy.lua
Catch cases where in BW the old brackets had no opponents filled in but maps were filled in.
(Idk why they have it but it is the case on some pages ...)
/dev, now live
> Catch some empty cases in broodwar legacy handling

- components/match2/wikis/dota2/match_summary.lua
depends on ##1722
enable darkmode support in match2 footers (together with #1702 & #1612)
* Use `footer:addLinks` in OW MatchSummary
* add support for the icons using `_AUTO_LINKS`
/dev
> Prepare dota2 matchSummary footer for darkmode

- components/match2/wikis/counterstrike/match_external_links.lua
- components/match2/wikis/counterstrike/match_summary.lua
depends on #1722
enable darkmode support in match2 footers (together with https://github.com/Liquipedia/Lua-Modules/pull/1702 & https://github.com/Liquipedia/Lua-Modules/pull/1612)
/dev
Get DarkMode Icon for:
> Prepare CS matchSummary footer for darkmode

- components/prize_pool/commons/prize_pool.lua
This information is needed by SMW Storage  to the set `has firstX page` when there are multiple participants sharing the same placement.
See https://github.com/Liquipedia/Lua-Modules/pull/1727#issuecomment-1222469115
> Set OpponentIndex in Data Storage
