standard/info/wikis/fifa/info.lua

Skipped the legacy wrapper and directly converted templates via bot

feat: Update fifa match2 status

---

components/match2/wikis/arenaofvalor/match_legacy.lua
components/match2/wikis/brawlstars/match_legacy.lua
components/match2/wikis/callofduty/match_legacy.lua
components/match2/wikis/counterstrike/match_legacy.lua
components/match2/wikis/criticalops/match_legacy.lua
components/match2/wikis/crossfire/match_legacy.lua
components/match2/wikis/dota2/match_legacy.lua
components/match2/wikis/fifa/match_legacy.lua
components/match2/wikis/heroes/match_legacy.lua
components/match2/wikis/leagueoflegends/match_legacy.lua
components/match2/wikis/mobilelegends/match_legacy.lua
components/match2/wikis/overwatch/match_legacy.lua
components/match2/wikis/pokemon/match_legacy.lua
components/match2/wikis/rainbowsix/match_legacy.lua
components/match2/wikis/splatoon/match_legacy.lua
components/match2/wikis/valorant/match_legacy.lua
components/match2/wikis/wildrift/match_legacy.lua
components/match2/wikis/zula/match_legacy.lua

fix annotation warnings in match2 legacy storage
VSCode

refactor(match2): improve match1 storage

---

components/infobox/wikis/valorant/infobox_person_player_custom.lua

Updates the name of the Signature section from Heroes to Agents, as Valorant does not have Heroes
data

fix: valorant `signature hero` to `signature agent`

---

components/hidden_data_box/wikis/starcraft/hidden_data_box_custom.lua
components/hidden_data_box/wikis/starcraft2/hidden_data_box_custom.lua

fix sc/sc2 game value set by hdb

fix(HDB): do not use game fallback on sc & sc2

---

components/infobox/wikis/trackmania/infobox_league_custom.lua

Add circuit parameters to trackmania infobox league for new TMWT circuit
dev

feat: add circuit info on trackmania infobox league

---

standard/links/commons/links.lua
standard/links/commons/links_priority_groups.lua
standard/links/wikis/counterstrike/links_custom_data.lua
standard/links/wikis/overwatch/links_custom_data.lua

Pretty self explanatory, and yes the `//` are intended; FACEIT website structure is a mess.
Just data ^^

Add FACEIT League link

---

javascript/commons/BattleRoyale.js
stylesheets/commons/BattleRoyale/PanelTable.less

Closes [ticket](https://gitlab.com/teamliquid-dev/liquipedia/web/issue-bucket/-/issues/48)
- Add a check to see on init if the user is on a screen smaller than 768px.
- Add media queries in the css.
Tested it on the live site

BR match 2 mobile sideways scrolling behaviour

---

standard/info/wikis/goals/info.lua

GOALS is the new wiki that was installed just recently
This is the usual Info module for every wiki. Since the game still in development I put 2024 as start year

Create Info module for GOALS

---

components/squad/commons/squad_custom.lua
components/squad/commons/squad_utils.lua
components/squad/wikis/apexlegends/squad_custom.lua
components/squad/wikis/arenaofvalor/squad_custom.lua
components/squad/wikis/counterstrike/squad_custom.lua
components/squad/wikis/dota2/squad_custom.lua
components/squad/wikis/leagueoflegends/squad_custom.lua
components/squad/wikis/mobilelegends/squad_custom.lua
components/squad/wikis/overwatch/squad_custom.lua
components/squad/wikis/rocketleague/squad_custom.lua
components/squad/wikis/smash/squad_custom.lua
components/squad/wikis/starcraft/squad_custom.lua
components/squad/wikis/starcraft2/squad_custom.lua
components/squad/wikis/stormgate/squad_custom.lua
components/squad/wikis/valorant/squad_custom.lua
components/squad/wikis/warcraft/squad_custom.lua
components/squad/wikis/wildrift/squad_custom.lua

Extract common functionality from the customs into a util
Tested on CS and OW, covering the different usecases

refactor(squad): extract commonly used functionality

---

components/match2/wikis/overwatch/match_group_input_custom.lua
components/match2/wikis/overwatch/match_summary.lua

Removed permanent dead links, added archive links for dead links (not sure if this is how it's usually done), added new links

feat(match2): update links for overwatch

---

standard/info/wikis/fighters/info.lua

Adding Koihime Enbu to Module:Info for Fighters

feat: add Koihime Enbu to Fighters

---

components/squad/commons/squad_row.lua
components/squad/wikis/arenaofvalor/squad_custom.lua
components/squad/wikis/dota2/squad_custom.lua
components/squad/wikis/leagueoflegends/squad_custom.lua
components/squad/wikis/mobilelegends/squad_custom.lua
components/squad/wikis/overwatch/squad_custom.lua
components/squad/wikis/smite/squad_custom.lua
components/squad/wikis/wildrift/squad_custom.lua

Move position field to commons
Tested on dota2

refactor(squad): standardise position

---

components/squad/commons/squad_row.lua
standard/icon.lua
standard/icon_data.lua

Swap the low res uploaded icons for Font Awesome Icons. The captain one is basically the same, and the rarely used substitute is different but similar enough.
dev

feat(squad): use FA for icons

---

components/squad/commons/squad.lua
components/squad/commons/squad_custom.lua
components/squad/commons/squad_row.lua
components/squad/commons/squad_utils.lua
components/squad/wikis/apexlegends/squad_custom.lua
components/squad/wikis/arenaofvalor/squad_custom.lua
components/squad/wikis/counterstrike/squad_custom.lua
components/squad/wikis/dota2/squad_custom.lua
components/squad/wikis/halo/squad_custom.lua
components/squad/wikis/leagueoflegends/squad_custom.lua
components/squad/wikis/mobilelegends/squad_custom.lua
components/squad/wikis/overwatch/squad_custom.lua
components/squad/wikis/rainbowsix/squad_custom.lua
components/squad/wikis/rocketleague/squad_custom.lua
components/squad/wikis/smash/squad_custom.lua
components/squad/wikis/smite/squad_custom.lua
components/squad/wikis/starcraft/squad_custom.lua
components/squad/wikis/starcraft2/squad_custom.lua
components/squad/wikis/stormgate/squad_custom.lua
components/squad/wikis/valorant/squad_custom.lua
components/squad/wikis/warcraft/squad_custom.lua
components/squad/wikis/wildrift/squad_custom.lua

Standardise most functionality, only a couple of wikis have significant directors on their own. Most customs are now down to 20 LOC.
Tested with dev on the following wikis (covering all types of changes)
* AoE (Commons/Custom)
* Apex
* AoV
* Counterstrike
* dota2
* overwatch
* r6
* sc1
* sc2
* wc3

refactor(squad): standardise most

---

spec/icon_spec.lua

Not valid input to the function per specs

test(icon): fix anno warning

---

components/squad/commons/squad.lua

It shouldn't be needed but seems to be. This is a quick fix for the error
Live

fix: error on squad table

---

standard/tabs.lua

As per the vote in discord change behaviour of singular tabs.
vote: https://discord.com/channels/93055209017729024/878766918880874536/1225506962524082296
dev

feat(tabs): option to show singular tab as a tab

---

standard/timezone_data.lua

add `Armenian Time` as per request on discord by NiKoholic
https://discord.com/channels/93055209017729024/765984788107624468/1229430730636132352
N/A

feat(standard): add `Armenian Time`

---

components/external_media_links/external_media_list.lua

Querying without any additional conditions fails, this PR fixes it
Live

fix(externalMedia): fails when no additional conditions

---

components/squad/commons/squad_row.lua

Pulling this change out of #4162, as it's not related to the overall change there, just code simplification/readability/
Tested Rocket League and R6

refactor(squad): simplify newteam

---

standard/info/wikis/mobilelegends/info.lua

MLBB had a new logo of the game, this is to reflect the default file to be the current logo version

feat: update mlbb logo

---

components/infobox/commons/infobox_person.lua
components/portal_players/commons/portal_players.lua

Add banned storage for infobox person.
conversation on discord about it: https://discord.com/channels/93055209017729024/874304000718172200/1219815338632417343
dev

feat: add banned storage on infobox person

---

stylesheets/commons/Miscellaneous.less

Halfbox background is not compatible with darkmode
dev tools

feat: darkmode support for `halfbox`

---

stylesheets/commons/Miscellaneous.less

Match pages didn't have dark theme colors yet
Closes [ticket](https://gitlab.com/teamliquid-dev/liquipedia/web/skins/lakesideview/-/issues/113)
Devtools

feat(bigmatch): add dark-theme colors

---

stylesheets/commons/Miscellaneous.less

I forgot a couple of ampersands when copy and pasting code around. This solves why some parts still had LT colors. Also made a change to one color to make it more consistent.
Tested it on the live site in Miscellaneous.less

feat(bigmatch): missing ampersands

---

components/squad/commons/squad_row.lua
components/squad/commons/squad_utils.lua
components/squad/wikis/starcraft2/squad_custom.lua
components/squad/wikis/stormgate/squad_custom.lua

Special team mapping broke because the parsing discarded all non-valid teams. 
Setup a better way to handle it
with /dev on CS

fix(squads): special team input

---

components/participant_table/commons/participant_table_base.lua

allow to disable title in ParticipantTable
dev

feat(ParticipantTable): allow to disable title

---

components/infobox/extensions/commons/infobox_extension_game_appearances.lua

I accidentally left out a Typo in that module. This is just the typo fix

fix(infobox_extensions): fix breaking typo

---

standard/highlight_conditions/wikis/overwatch/highlight_conditions.lua

Add OW HighlightConditions as per request on discord
dev

feat(HighlightConditions): customize for OW

---

standard/highlight_conditions/wikis/overwatch/highlight_conditions.lua

fix(ow highlightCond): parse to number
not tested, am on phone, opening the pr was painful enough ;)

fix(highlightCond): overwatch not working

---

components/participant_table/commons/participant_table_base.lua

- fix the filling up with TBD opponents via `|count=` parameter
- allow >1 TBD opponent
dev

fix(ParticipantTable): filling up with TBD via count

---

components/infobox/extensions/commons/infobox_extension_game_appearances.lua

docs: fix game appearances annotation

---

components/participant_table/wikis/ageofempires/participant_table_custom.lua

docs: Fix annotations in AoE tarticipants table

---

spec/test_helper.lua

Shuts up some IDE warnings. If anyone got a better suggestion I'm all ears

docs: meta define the global test function exposed by custom `busted.export`

---

components/match2/wikis/apexlegends/match_group_input_custom.lua
components/match2/wikis/apexlegends/match_summary.lua

Simple "match point" support on Apex. 
A team reaches "match point" when they gotten a certain amount of points. After they have reached it, next time they finish first, they win the match.
/dev

feat(match2): basic support for matchpoint on apex

---

standard/logic.lua

Improve `Logic.nilIfEmpty` annotations by using generic
VSCode

doc(Logic): Improve `Logic.nilIfEmpty` annotations

---

components/match_table/commons/match_table.lua

Due to a report f a potential bug by @LuckeLucky i noticed that default date was displayed. This PR makes it so that the default date is not shown.
dev

fix(matchTable): do not display default date

---

components/hidden_data_box/wikis/brawlhalla/hidden_data_box_custom.lua
standard/date_ext.lua

feat(hdb): setup brawlhalla

---

components/prize_pool/commons/prize_pool_base.lua

As per suggestion on discord and agreed in Modules Sync move percantage column to directly after local currency column
to be done

feat(ppt): move percentage column next to money columns

---

components/prize_pool/wikis/brawlhalla/prize_pool_custom.lua

Setup ppt for brawlhalla
https://liquipedia.net/brawlhalla/User:Rathoz/WC/2023

feat(prizepool): brawlhalla setup

---

standard/info/wikis/dota2/info.lua

Changes the default logo for Dota 2 to match the File Standards Guide
N/A

feat: update dota2 logo 

---

components/match2/wikis/clashofclans/match_group_input_custom.lua

Caused the processing to error out so no games being displayed.
Not sure what caused this to fail now since the function was removed a year ago.
live

fix(match2): error on Clash of Clans

---

components/squad/commons/squad_utils.lua

fix(squad): inactive references not working with SquadAuto

---

components/match2/wikis/overwatch/get_match_group_copy_paste_wiki.lua

Adds the copy/paste generator for match2 from the Overwatch wiki
Still needs fixing:
/dev

feat(match2): custom overwatch Copy/Paste generator

---

stylesheets/commons/Miscellaneous.less

Add darkmode support to several timeline css classes.

feat(timeline): Add darkmode support

---

components/match2/wikis/callofduty/get_match_group_copy_paste_wiki.lua

Adds the copy paste generator for Call of Duty
dev module

feat(match2): Add Match2 Copy/paste for Call of Duty

---

stylesheets/commons/NavigationCard.less

Discussed this yesterday with Kevin. This MR adds a hover zoom effect to the image of the card.
Live website.
https://liquipedia.net/dota2game/User:Elysienna/Main_Page

feat: add hover effect to navigation card

---

standard/info/wikis/callofduty/info.lua

The new game coming this year, fortunately logos were available pretty quick

feat: add Black Ops 6 on CoD

---

components/match2/wikis/callofduty/match_summary.lua

Updates the current lightmode icon for the CDL along with adding a new icon for darkmode support. 
tested live

feat(match2): Add darkmode support for CDL icons

---

components/participant_table/wikis/stormgate/participant_table_custom.lua

When converting partTable to merge instead of skip apparently i forgot to convert the stormgate custom.
This PR fixes that.
dev to live

fix(participantTable): stormgate not working as intended

---

standard/links/commons/links.lua

Adds Player and Team link options for Challengermode in the Infobox

feat(links): add player and team links for ChallengerMode

---

standard/info/wikis/callofduty/info.lua

feat: Update callofduty match2 status

---

components/infobox/wikis/criticalops/infobox_person_player_custom.lua

This was left unnoticed and never got added to git, that one is very old in code so this is a complete re-paste from World of Tanks setup
Live

feat(infobox): infobox player for Critical Ops

---

components/infobox/wikis/mobilelegends/infobox_patch_custom.lua

Implements new infobox patch for MLBB
https://liquipedia.net/mobilelegends/User:MatryoshX/Test_Page

feat(infobox): infobox patch for MLBB

---

components/game_table/commons/game_table.lua
components/game_table/commons/game_table_custom.lua
standard/info/wikis/callofduty/info.lua

Use match table to display games instead.
[sandbox](https://liquipedia.net/leagueoflegends/User:LuckeLucky/sandbox/2)

feat(gameTable): create game table

---

components/infobox/wikis/mobilelegends/infobox_unit_hero_custom.lua

- Remove unused cell content
- Change the display order of the cells
- Switch from the local `HeroWL` module to the `CharacterWinLoss` module
https://liquipedia.net/mobilelegends/User:MatryoshX/Test_Page

feat(infobox): adjust mlbb infobox hero content

---

components/character_icon/commons/character_icon.lua

Adds the option to append the link in textual form to the character icon.
First usecase is Module:ChampionStats
dev

feat(CharacterIcon): Add option to include name with the Icon

---

components/infobox/wikis/valorant/infobox_person_player_custom.lua

Adding bottom content to the Valorant Player Infobox 
/dev

feat(infobox): add tickers to valorant's player infobox

---

standard/info/wikis/magic/info.lua

feat(info): Update magic match2 status

---

components/infobox/wikis/warcraft/infobox_item_custom.lua

Change requested by Stowka https://discord.com/channels/93055209017729024/161454541009715200/1253787318066614342 
Meant to fix broken extradata
Stowka tested via dev

fix(infobox): requirements storage on warcraft item infobox

---

components/infobox/wikis/easportsfc/infobox_company_custom.lua
components/infobox/wikis/easportsfc/infobox_league_custom.lua
components/infobox/wikis/easportsfc/infobox_person_player_custom.lua
components/match2/wikis/easportsfc/match_group_input_custom.lua
components/match2/wikis/easportsfc/match_legacy.lua
components/match2/wikis/easportsfc/match_summary.lua
components/portal_players/wikis/easportsfc/portal_players_custom.lua
standard/info/wikis/easportsfc/info.lua
standard/tier/wikis/fifa/tier_data.lua

(This is me using vscode, pardon any thing that looks weird because I don't use it often)
Renaming FIFA folder on github to match the wiki that's already renamed to **easportsfc** including header changes

feat: rename fifa to easportsfc

---

components/prize_pool/commons/prize_pool_import.lua

Fix the args key used for `stageGroupElimStatuses`
live

fix(prizepool): `stageGroupElimStatuses`option in import

---

components/squad/commons/squad_custom.lua
components/squad/commons/squad_utils.lua
components/squad/wikis/overwatch/squad_custom.lua
components/squad/wikis/starcraft2/squad_custom.lua
components/squad/wikis/stormgate/squad_custom.lua

Allow title overwrite in AutoSquads
dev
FYI: After testing already pushed squadAuto dev to live to already pass the title along there

feat(squad): Allow title overwrite in AutoSquads

---

components/match2/wikis/overwatch/get_match_group_copy_paste_wiki.lua

Adds faceit parameter to the match copy paste module. 
dev

feat(match2): add Faceit to Overwatch Match Copy/Paste

---

components/tournaments_listing/commons/tournaments_listing_conditions.lua

Adds the option to query for multiple series at once
dev

feat(TournamentsListing): Allow to query for multiple series

---

javascript/commons/Countdown.js
standard/timezone_data.lua

Used in leagueoflegends [Template:Abbr/ECT](https://liquipedia.net/leagueoflegends/Template:Abbr/ECT).

feat(timezone): Add ECT timezone

---

components/infobox/wikis/worldoftanks/infobox_league_custom.lua

as requested here: https://discord.com/channels/93055209017729024/268719633366777856/1260727178421866496
by thePhilX
in dev
https://liquipedia.net/worldoftanks/User:Kitbinary/Sandbox_1

feat(infobox): add patch to world of tanks's league infobox 

---

components/hidden_data_box/wikis/fighters/hidden_data_box_custom.lua

Create Custom for Fighters for Hidden Data Box
Tested on https://liquipedia.net/fighters/User:Rathoz

feat(hdb): setup for fighters

---

components/match2/commons/match_group_input.lua
components/match2/wikis/apexlegends/match_summary.lua
components/match2/wikis/arenafps/match_summary.lua
components/match2/wikis/clashroyale/match_summary.lua
components/match2/wikis/crossfire/match_summary.lua
components/match2/wikis/heroes/match_summary.lua
components/match2/wikis/osu/match_summary.lua
components/match2/wikis/tetris/match_group_input_custom.lua
components/match2/wikis/worldoftanks/match_summary.lua
components/prize_pool/wikis/ageofempires/prize_pool_custom.lua
components/prize_pool/wikis/rainbowsix/prize_pool_custom.lua
components/prize_pool/wikis/trackmania/prize_pool_custom.lua

suppress some annotation warnings
VSCode

doc: fix some annotation warnings

---

components/match2/commons/match_group_input.lua
components/match2/wikis/arenaofvalor/match_group_input_custom.lua
components/match2/wikis/brawlhalla/match_group_input_custom.lua
components/match2/wikis/brawlstars/match_group_input_custom.lua
components/match2/wikis/dota2/match_group_input_custom.lua
components/match2/wikis/heroes/match_group_input_custom.lua
components/match2/wikis/leagueoflegends/match_group_input_custom.lua
components/match2/wikis/mobilelegends/match_group_input_custom.lua
components/match2/wikis/omegastrikers/match_group_input_custom.lua
components/match2/wikis/pokemon/match_group_input_custom.lua
components/match2/wikis/rainbowsix/match_group_input_custom.lua
components/match2/wikis/smite/match_group_input_custom.lua
components/match2/wikis/wildrift/match_group_input_custom.lua

Make character names go through [Module:ChampionName](https://liquipedia.net/wildrift/Module:ChampionNames)

feat(match2): standardize character names input

---

components/match2/wikis/brawlhalla/brkts_wiki_specific.lua
components/match2/wikis/fighters/brkts_wiki_specific.lua
components/match2/wikis/fighters/get_match_group_copy_paste_wiki.lua
components/match2/wikis/fighters/match_group_input_custom.lua
components/match2/wikis/fighters/match_legacy.lua
components/match2/wikis/fighters/match_summary.lua

Create Custom for Fighters
Tested on https://liquipedia.net/fighters/User:Rathoz

feat(match2): add support for fighters

---

components/infobox/wikis/fighters/infobox_league_custom.lua
components/prize_pool/wikis/brawlhalla/prize_pool_custom.lua
components/prize_pool/wikis/fighters/prize_pool_custom.lua

PPT to work with Fighters. Special datapoint for their circuit handling
https://liquipedia.net/fighters/User:Rathoz

feat(prizepool): setup for fighters

---

components/faction/wikis/ageofempires/faction_data.lua

alias already in module
+Indians  and changed indexes accordingly
Indians  was already added to aliases previously
none

feat(faction): Add AoEO's Indians

---

components/match2/wikis/fighters/match_legacy.lua

Add `game1` storege in Fighter's match2
Live

feat(match2): store legacy games for fighters

---

components/opponent/wikis/fighters/player_display_custom.lua
components/participant_table/wikis/fighters/participant_table_custom.lua

Does not affect Participant's Table
Dev to Live

feat(opponent): sometimes display fighters characters on new line

---

components/game_table/commons/game_table_character.lua
components/match_table/commons/match_table.lua

/dev and [sandbox](https://liquipedia.net/leagueoflegends/User:LuckeLucky/sandbox/2)

feat(gameTable): Add more settings/change display 

---

standard/timezone_data.lua

Adding missing timezone.
Just data :D

data(timezone): add AQTT Aqtobe Time

---

standard/info/wikis/easportsfc/info.lua

The yearly releases (for FC the releases always shifted ahead by a year)
file is already uploaded to commons

feat: add FC25

---

components/match2/wikis/leagueoflegends/match_group_input_custom.lua

Sometimes someone skip champion ban.
/dev

fix(match2): Allow empty bans in leagueoflegends

---

components/infobox/commons/infobox_league.lua
standard/page.lua

New LPDB field to contain the pagenames of all series
/dev

feat(infobox): store list of series

---

components/game_table/commons/game_table_character.lua
components/game_table/dota2/game_table_character_custom.lua

* [NEW](https://liquipedia.net/dota2/User:LuckeLucky/sandbox/2)
* [OLD](https://liquipedia.net/dota2/Bloodseeker/Matches)

feat(gameTableCharacter): Add Custom GameTable Character to dota2

---

stylesheets/commons/Colours.less

Requested by the people sitting around me, I got cornered into adding it 🙈

feat: add a softer version for gray-bg

---

stylesheets/commons/Fountain.less

Adds the fountain.less file to the git, so
- iris can edit it via PRs
- linters etc. run over it
- we have better code style in it
- we have a review process for it
- can easier move stuff from it to resolve it eventually
N/A, copied from live and adjusted only to please the linter.

chore(less): Add fountain.less

---

components/game_table/commons/game_table.lua

fix(gameTable): Respect input limit when displaying games

---

components/match2/wikis/dota2/match_page_template.lua

Some minor updates to the html

feat(match2): minor improvements on dota2 match page

---

components/match2/wikis/osu/get_match_group_copy_paste_wiki.lua

_Admittedly, I forgot to put this one up._ 
Last touched November 2023 so I tried to adjust it to look more like the newer CopyPaste generator, might need some help on the Annotations if I missed any. 
Osu is a bit extensive due to the weirdness of Vetoes and their `protect` type of veto
The updated version here is already edited onto live, the generator was live since then

feat(match2): create Match CopyPaste for osu

---

stylesheets/commons/Grid.less

This is adding better support for nested grids. This is a requirement for the new dota2 main page
I edited it into the live version for a test after testing with dev tools for a while.

feat(grids): add better support of nested grids

---

stylesheets/commons/Faction.less

Add darkmode support for stormgates celestial faction

feat(faction): add darkmode support for stormgate's celestial faction

---

stylesheets/commons/Techtree.less

Senti build a techtree module for stormgate that i cleaned up.
With cleaning it up i also want to move its styles into *.less.
Browser dev tools

feat: add techtree styles for stormgate

---

components/game_table/commons/game_table.lua

#4448 only fixed the display ...
For limit = 100:
* Old
* New
/dev

fix(gameTable): stats do not respect limit

---

components/infobox/extensions/wikis/stormgate/infobox_extension_attack.lua

docs: fix annotation on stormgate

---

spec/hidden_data_box_spec.lua

test: properly stub in HDB test

---

standard/info/wikis/fighters/info.lua

feat: update fighter's match2 status

---

standard/links/commons/links.lua
stylesheets/commons/Icons.less

Adding a paramet for Geoguessr links:
Currently left open to support both users/maps/other subpage types

feat: add Geoguessr links

---

standard/links/commons/links_priority_groups.lua

feat: add group for GeoGuessr link

---

standard/i18n.lua

fix: typo in a comment in new i18n library

---

components/participant_table/wikis/stormgate/participant_table_custom.lua

Currently on stormagte the participant table doesn't work properly in the randomEvent case
- reads random faction if set from the prize pool
- does not set correct faction wiki var (random)
- does not inherit config from parent to sections
1:1 copied from sc/sc2 version, dev

fix(participantTable): random event handling on stormgate

---

standard/info/wikis/heroes/info.lua

feat: Update Heroes match2 status

---

components/opponent/commons/opponent.lua

refactor(opponent): remove redundant code

---

components/match2/wikis/clashroyale/get_match_group_copy_paste_wiki.lua

depends on #4503
Adds the copy paste match2 generator for Clash Royale
dev

feat(match2): Clash Royale Copy/Paste Generator

---

standard/info/wikis/fighters/info.lua

Added the game 2XKO to the Fighting Games Info lua module with help from general-help channel on discord

feat: add 2XKO to Fighters

---

components/match2/commons/display_util.lua
standard/error.lua
standard/error_display.lua
standard/result_or_error.lua

Refactor error handling more, a first step of re-imagining of #625 (https://github.com/Liquipedia/Lua-Modules/pull/625/commits/4765444b649c9ac1d9ecb6df69c51a9dff03bb43)
/dev

refactor(standard): error handling additionally

---

standard/info/wikis/stormgate/info.lua

feat: disallow manual squads on stormgate

---

stylesheets/commons/SwitchButtons.less

Request by Kevin to increase the border radius.
Devtools

feat: Increase border-radius value switchpill

---

components/infobox/wikis/stormgate/infobox_unit_custom.lua

- change csv-function to current version (was an oversight from last pr that's only relevant for subfaction units)
- Always show Health and Armor in Infobox (with "0" if no input)
dev

feat(infobox): Update stormgate infobox building

---

components/infobox/extensions/commons/infobox_extension_patch_auto.lua

Fix the query condition for the patches to be retrieved
dev into live

fix(Infobox): autopatch using non-patch data sometimes

---

components/match2/commons/display_util.lua

Add some aliases in DisplayUtil to allow for easier migration of DisplayUtil Downstreams

feat: remove some need of DisplayUtil/downstreams

---

components/match2/commons/match.lua
components/match2/commons/match_group.lua
components/match2/commons/match_subobjects.lua
standard/lua.lua

feat(standard): automatically setup performance testing if enabled

---

standard/lua.lua

As reported in discord: https://discord.com/channels/93055209017729024/268719633366777856/1273667771070287912
dev

fix(standard): Prevent nil display if called module returns nothing

---

components/match2/wikis/clashroyale/get_match_group_copy_paste_wiki.lua

Adds the map copy paste to the match2 copy paste generator for CR wiki
live

fix(match2): add maps copy pasta for CR

---

components/match2/commons/starcraft_starcraft2/get_match_group_copy_paste_starcraft.lua

fix(match2): missing indent for casters in sc(2) copy pasta

---

components/match2/wikis/ageofempires/get_match_group_copy_paste_wiki.lua
components/match2/wikis/ageofempires/match_group_input_custom.lua
components/match2/wikis/ageofempires/match_summary.lua
components/match2/wikis/overwatch/get_match_group_copy_paste_wiki.lua
components/match2/wikis/overwatch/match_group_input_custom.lua
components/match2/wikis/overwatch/match_summary.lua

Adds the caster row for the Overwatch and AOE wikis
dev

feat(match2): Add caster support for OW & AOE

---

components/match2/wikis/dota2/match_page_template.lua

As mentioned by Elisa in Slack, this part was not being used by the template so I removed it.
Live

feat(match2): remove unused section of dota2 match page

---

components/match2/commons/match_group_display_bracket.lua
components/match2/commons/match_group_display_horizontallist.lua
components/match2/commons/match_group_display_matchlist.lua
components/match2/commons/match_group_display_matchpage.lua
components/match2/commons/match_group_display_single_match.lua
components/match2/commons/starcraft_starcraft2/match_group_display_single_match_starcraft.lua

Remove hardcoded regex's where there a function that already does this
Tested with /dev with Single Match

refactor(match2): remove duplicated regex

---

components/tournaments_listing/commons/tournaments_listing_conditions.lua

- add option to condition on country, city and venue
- extract condition building from csv to function
dev

feat(TournamentsListing): add option to condition on country, city and venue

---

components/match2/commons/brkts_wiki_specific_base.lua

docs(match2): missing annotation

---

components/match2/wikis/rainbowsix/match_group_input_custom.lua

refactors R6 match input processing based on new commons func from #4481

refactor(match2): input parsing on R6

---

components/match2/wikis/dota2/match_group_input_custom.lua

refactor(match2): dota2 input parsing

---

components/match2/wikis/arenaofvalor/match_group_input_custom.lua

refactor(match2): aov input parsing

---

components/match2/wikis/valorant/match_group_input_custom.lua

refactor(match2): input parsing for valorant

---

components/match2/wikis/callofduty/match_group_input_custom.lua

refactor(match2): call of duty input parsing

---

components/match2/wikis/overwatch/match_group_input_custom.lua
components/match2/wikis/overwatch/match_summary.lua

refactor(match2): overwatch input parsing

---

components/match2/commons/match_group_input.lua
components/match2/wikis/heroes/match_group_input_custom.lua
components/match2/wikis/heroes/match_summary.lua

refactor(match2): input parsing on heroes

---

components/match2/wikis/wildrift/match_group_input_custom.lua

refactor(match2): wild rift's input parsing

---

components/match2/commons/match_group_input.lua
components/match2/wikis/brawlstars/match_group_input_custom.lua
components/match2/wikis/brawlstars/match_summary.lua

+ optional bestOf calculation in mapIsFinished  as it's needed by BS

refactor(match2): brawl star's match parsing

---

components/match2/wikis/rocketleague/match_group_input_custom.lua
components/opponent/wikis/rocketleague/opponent_display_custom.lua

refactor(match2): input parsing on rocketleague

---

components/match2/wikis/halo/match_summary.lua

Invalid TT on halo causes baad
Live

fix(match2): invalid team template on halo causes hard error

---

components/opponent/wikis/rocketleague/opponent_display_custom.lua

Some random error, only affect some list/bracket, not sure why or how but conflict on function name
Dev into live

fix(match2): random error on rocketleague

---

components/match2/wikis/starcraft/legacy/match_group_legacy_default.lua

fix(match2): starcraft match group legacy header

---

components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua

wrongly assumed uniform display mode due to change in mode building
dev to live

fix(match2): on sc(2), uniform display triggers when it shouldn't

---

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua

fix(match2): on sc(2), sometimes trying to do math on nil

---

components/match2/commons/match_group_input.lua

Fallback dates would pick the key over the value
Live

fix(match2): issue with fallback dates

---

components/match2/commons/match_group_input.lua

show the invalid walkover/score input in the error message for easier and faster debugging
dev

feat(match2): improve error messages

---

components/match2/wikis/arenaofvalor/match_group_input_custom.lua
components/match2/wikis/brawlstars/match_group_input_custom.lua
components/match2/wikis/callofduty/match_group_input_custom.lua
components/match2/wikis/dota2/match_group_input_custom.lua
components/match2/wikis/heroes/match_group_input_custom.lua
components/match2/wikis/leagueoflegends/match_group_input_custom.lua
components/match2/wikis/overwatch/match_group_input_custom.lua
components/match2/wikis/rainbowsix/match_group_input_custom.lua
components/match2/wikis/valorant/match_group_input_custom.lua
components/match2/wikis/wildrift/match_group_input_custom.lua

#4597 for other wikis
/dev on heroes

fix(match): #4597 for rest of the wikis

---

standard/info/wikis/hearthstone/info.lua

There seems to be Transfers already happening in 2013

feat: change hearthstone startdate to 2013

---

components/match2/wikis/rainbowsix/match_summary.lua

Typo, and then I extracted it to a func
Live

fix(match2): displaying oppo 1 map score for oppo 2 on r6

---

components/match2/wikis/rocketleague/match_summary.lua

feat(match2): #4604 for rocketleague

---

components/match2/wikis/dota2/match_group_input_custom_match_page.lua
components/match2/wikis/dota2/match_page.lua
components/match2/wikis/dota2/match_page_template.lua
components/match2/wikis/leagueoflegends/match_page_template.lua

The API is now available, and adjust the parsing the new reality.
Also remove some leftover LoL in the template tha should be there + fixed a minor typo in the league of legends one
"live"

feat(match2): use real api on dota2

---

components/match2/wikis/dota2/match_page_template.lua

Just realized it has to be the darkmode version, not lightmode

fix(match2): dota2 match page typo facets

---

components/match2/wikis/clashroyale/get_match_group_copy_paste_wiki.lua

Fixing an oopsie where we forgot to add closing brackets for the matches (honeslty, not sure how we didnt notice this last time)
live

fix(match2): Clash Royale Copy & Paste fix

---

components/infobox/wikis/rocketleague/infobox_person_player_custom.lua

Fix RL infobox nationalities not being put in categories.
/dev module

fix(infobox): RL nationality categories

---

components/match2/wikis/brawlstars/match_summary.lua
components/match2/wikis/callofduty/match_summary.lua

Apply #4604 for the remaining wikis

feat(match2): improve walkover display on Brawl Stars and CoD

---

components/match2/wikis/valorant/get_match_group_copy_paste_wiki.lua

Added line to show casters when stream is available
https://discord.com/channels/93055209017729024/268719633366777856/1273772202839506946
Dev

feat(match2): Add casters support to valorant match2 copy pasta

---

components/match2/wikis/valorant/match_summary.lua

fix(match2): typo in #4621

---

components/infobox/wikis/stormgate/infobox_building_custom.lua

Annos specifiy that there should be an array returened

docs(infobox): fix anno issue on stormgate

---

components/match2/wikis/dota2/match_group_input_custom_match_page.lua
components/match2/wikis/dota2/match_page.lua
components/match2/wikis/dota2/match_page_template.lua

dota2db changed their item return to have images, let's use the images from there
"live"

feat(match2): new data struct for items on dota2 api

---

components/infobox/commons/infobox_person.lua

Handle plural & singular cases for the Nicknames cell
Requested here: https://discord.com/channels/93055209017729024/268719633366777856/1276575466756505611
dev

feat(infobox): change cell title from `Nicknames` to `Nickname(s)`

---

components/infobox/wikis/pubg/infobox_map_custom.lua

Creates a custom map infobox for PUBG. It was originally some super ancient template. There a few custom params
https://discord.com/channels/93055209017729024/268719633366777856/1276715574029717577
live

feat(infobox): map infobox for PUBG custom

---

components/prize_pool/commons/starcraft_starcraft2/prize_pool_starcraft.lua

kick unsued function form sc(2) prize pool custom
N/A

chore(prizepool): remove unsued function form sc(2) custom

---

definitions/mw.lua

docs: improve team template annotations

---

components/match2/wikis/rainbowsix/legacy/legacy_bracket_match_summary.lua
components/match2/wikis/rainbowsix/legacy/match_group_legacy_default.lua
components/match2/wikis/rainbowsix/legacy/match_maps_legacy.lua

fix(match2): Don't fill score when empty in legacy maps on r6

---

components/infobox/wikis/deadlock/infobox_character_custom.lua

Initial hero infobox for deadlock

feat(infobox): hero infobox for deadlock

---

standard/info/wikis/deadlock/info.lua

Should match2 value stays 0 then changed it after #4652 is added?

feat(info): Add Deadlock

---

components/infobox/wikis/deadlock/infobox_character_custom.lua

Fixing typo ``meele`` to ``melee``
Didnt

fix(infobox): fix misspelled word

---

components/infobox/commons/infobox_lore.lua
components/infobox/wikis/dota2game/infobox_lore_custom.lua

https://liquipedia.net/dota2game/User:Rathoz/lore

feat(infobox): create lore infobox for dota2game

---

components/opponent/commons/opponent.lua
components/opponent/commons/player_ext.lua
components/opponent/commons/starcraft_starcraft2/opponent_starcraft.lua
components/opponent/commons/starcraft_starcraft2/player_display_starcraft.lua
components/opponent/commons/starcraft_starcraft2/player_ext_starcraft.lua
components/opponent/wikis/stormgate/opponent_custom.lua
components/opponent/wikis/stormgate/player_ext_custom.lua
components/opponent/wikis/warcraft/opponent_custom.lua
components/opponent/wikis/warcraft/player_ext_custom.lua
components/participant_table/commons/participant_table_base.lua
components/prize_pool/commons/prize_pool_placement_base.lua

feat(opponent): by default do not overwrite page vars in sync

---

components/match2/wikis/dota2/match_page_template.lua
stylesheets/commons/BigMatch.less

Kevin came back with some additional requests.
- Font-size changes for player performance elements
- Hide empty image and use background-color instead
Live wiki

fix(match2): dota2 matchpage styling changes

---

components/match2/wikis/dota2/match_page_template.lua

Forgot to add the match timer
Live wiki

feat(match2): add match length dota2 matchpage

---

stylesheets/commons/PanelBox/Heroes.less

- hero title alignment
- hero title visited hover state color
Live wiki

fix: hero title alignment and visited hover color

---

components/infobox/wikis/dota2/infobox_cosmetic_custom.lua
components/infobox/wikis/dota2/infobox_lore_custom.lua
stylesheets/commons/Banner.less

feat: merge dota2game into dota2

---

stylesheets/commons/FilterButtons.less
stylesheets/commons/Panels.less

Add a new name so we can remove the class, as the idea is that is neither test nor dota2 specific

feat: rename css class

---

components/opponent/commons/starcraft_starcraft2/player_ext_starcraft.lua
components/opponent/wikis/stormgate/player_ext_custom.lua
components/opponent/wikis/warcraft/player_ext_custom.lua

fix(opponent): do not write player faction page var for default faction

---

components/match2/wikis/arenafps/match_legacy.lua

docs: remove extra doc param

---

components/infobox/wikis/stormgate/infobox_map_custom.lua

This is just a small fix to update Infobox map, to be able to display the current possible camps. The camp data in this infobox is outdated. 
dev tools.

feat(infobox): update camps on SG Map Infobox

---

components/match2/wikis/tft/match_group_input_custom.lua
components/match2/wikis/tft/match_summary.lua

Especially for the EWC, but also for some other 4v4 tournaments on TFT, we need brackets to cover the tournaments properly.
Examples:
- https://liquipedia.net/tft/Esports_World_Cup/2024/Closed_Qualifier/Americas
- https://liquipedia.net/tft/Esports_World_Cup/2024/Closed_Qualifier/EMEA
- https://liquipedia.net/tft/Esports_World_Cup/2024/Closed_Qualifier/APAC
- https://liquipedia.net/tft/Esports_World_Cup/2024/Closed_Qualifier/China
- https://liquipedia.net/tft/Esports_World_Cup/2024

feat(match2): Add tft support

---

components/match2/wikis/dota2/match_group_input_custom.lua
components/match2/wikis/dota2/match_summary.lua

Add the special caster display to dota2, they are entering it in comments

feat(match2): add casters to dota2

---

components/match2/wikis/dota2/match_group_input_custom_match_page.lua
definitions/mw.lua

docs(match2): annotate dota2 input and dota2 api data

---

components/infobox/wikis/deadlock/infobox_character_custom.lua

Just a small typo fix for infobox character

fix(infobox): spelling on deadlock infobox character

---

components/infobox/commons/infobox.lua
components/prize_pool/commons/prize_pool_base.lua
components/squad/commons/squad.lua
components/widget/widget_builder.lua
components/widget/widget_factory.lua
components/widget/widget_table.lua
components/widget/widget_table_new.lua
components/widget/widget_table_row.lua
components/widget/widget_table_row_new.lua

refactor(widget): move factory widget to `/Widget`

---

components/match2/commons/match_group_input_util.lua
components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
components/match2/wikis/arenaofvalor/match_group_input_custom.lua
components/match2/wikis/brawlstars/match_group_input_custom.lua
components/match2/wikis/callofduty/match_group_input_custom.lua
components/match2/wikis/deadlock/match_group_input_custom.lua
components/match2/wikis/dota2/match_group_input_custom.lua
components/match2/wikis/heroes/match_group_input_custom.lua
components/match2/wikis/leagueoflegends/match_group_input_custom.lua
components/match2/wikis/overwatch/match_group_input_custom.lua
components/match2/wikis/rainbowsix/match_group_input_custom.lua
components/match2/wikis/rocketleague/match_group_input_custom.lua
components/match2/wikis/valorant/match_group_input_custom.lua
components/match2/wikis/wildrift/match_group_input_custom.lua

Switch finished to `true` for not played matches
(cleaned up version of #4600 due to heavy merge conflicts in that PR)
dev
if further refactoring happens all those customs need to be adjusted too (e.g. #4631)

feat(match2): Switch finished to `true` for not played matches

---

components/match2/wikis/valorant/match_group_input_custom.lua

fix(match2): missing nil check on valorant input processing

---

components/match2/commons/match_group_input_util.lua
components/match2/wikis/valorant/match_group_input_custom.lua
standard/page.lua

Annotations to decrease the change of #4726 happening
in IDE

docs(match2): add annotations for MGI opponents and players

---

components/match2/wikis/criticalops/match_group_input_custom.lua

fix(match2): error on c-ops

---

components/match2/wikis/ageofempires/match_group_input_custom.lua
components/match2/wikis/ageofempires/match_summary.lua

Match Group Input parsing refactor for AoE. LuckeLucky requested it done quickly so he could do legacy mapping on it.
Tested by me, mbergen and LuckeLucky

refactor(match2): AoE input parsing

---

components/match2/commons/match_group_display_helper.lua
components/match2/wikis/valorant/match_legacy.lua
components/match2/wikis/valorant/match_summary.lua
standard/table.lua

When there a gap in participants, agents are not shown, and data is not stored in match/legacy. 
Gap can occur due to >5 players on the team, a sub is play or a standin. 
/dev

fix(match2): valorant agents

---

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
components/match2/wikis/warcraft/match_group_input_custom.lua

as per suggestion in #4733
dev

refactor(match2): minor changes to get rid of anno warnings on sc(2) & wc3

---

components/match2/commons/match_group_input_util.lua

as per dms on discord
not tested

fix(match2): non-working fallback

---

components/match2/wikis/rainbowsix/legacy/match_group_legacy_default.lua
components/match2/wikis/rainbowsix/legacy/match_maps_legacy.lua
components/match2/wikis/valorant/legacy/match_group_legacy_default.lua
components/match2/wikis/valorant/legacy/match_maps_legacy.lua

feat(match2): valorant legacy handling for bo1

---

standard/info/wikis/simracing/info.lua

Add couple more games to the wiki, which came out after the last changes

feat: add more games to simracing

---

components/widget/widget_icon.lua
components/widget/widget_icon_image.lua
components/widget/widget_inline_icon_and_text.lua
components/widget/widget_span.lua

Widgets for inline icon with link

feat(widget): widgets for inline icon with link

---

components/match2/wikis/clashroyale/match_group_input_custom.lua
components/match2/wikis/clashroyale/match_summary.lua

- typo in input processing
- team matches being broken in match summary due to it assuming some additional (redundant, submatch) data in extradata
- made MS calculate that data from the existing games data
dev into live

fix(match2): several issues on CR

---

components/widget/widget.lua
components/widget/widget_button.lua
components/widget/widget_link.lua

feat(widget): create button widget

---

components/auto_inline_icon/commons/auto_inline_icon.lua
components/widget/widget_icon_image.lua

Some feedback to decrease the icon height from 24px to 20px.
Part live, part is just a size change

feat: tweaks to auto inline icon

---

components/infobox/wikis/ageofempires/infobox_league_custom.lua

Same field name as a function of base class. Removed the need of the field.
Live

fix(infobox): age of empires infobox league

---

components/match2/wikis/teamfortress/match_summary.lua
components/match2/wikis/warcraft/match_group_input_custom.lua

docs: annotation fixes

---

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
components/match2/wikis/stormgate/match_group_input_custom.lua
components/match2/wikis/warcraft/match_group_input_custom.lua

Remove the with #4783 deprecated wiki var after its usage removal
N/A

chore(match2): remove deprecated wiki var

---

components/match2/wikis/counterstrike/match_external_links.lua

Saw this branch from @ZaykorDE that was never made into a PR
@iMarbot @ZaykorDE still relevant?

feat: update cs faceit link on match2

---

standard/info/wikis/arenafps/info.lua

feat(info): Update match2 status on arenafps

---

components/game_table/commons/game_table.lua
components/game_table/commons/game_table_character.lua
components/game_table/dota2/game_table_character_custom.lua
components/game_table/valorant/game_table_character_custom.lua

/dev
Examples:
* [New character table](https://liquipedia.net/valorant/User:LuckeLucky/sandbox/2)
* [New player table](https://liquipedia.net/valorant/User:LuckeLucky/sandbox/3)
* [Old character table](https://liquipedia.net/valorant/Killjoy/Matches)
* [Old player table](https://liquipedia.net/valorant/MaiShiu/Matches)

feat(gameTable): Add custom gameTable to valorant

---

components/game_table/commons/game_table.lua

fix(gameTable): Check if winner is set

---

components/match2/wikis/rocketleague/match_group_input_custom.lua

fix(match2): tournament enddate not used on rocketleague

---

components/match2/wikis/ageofempires/match_legacy.lua

fix(match2): Use correct field for displayname in AoE Match/Legacy

---

components/character_icon/commons/character_icon.lua

feat(CharacterIcon): Prefer iconinfo display when adding textlink

---

components/match2/commons/match_group_input_util.lua
components/match2/wikis/ageofempires/match_group_input_custom.lua

BYE Opponents do not get the correct structure returned from readOpponents
/dev

fix(match2): issue with bye opponents

---

standard/array.lua

Remake of #4182 but without mapIndex

docs(standard): add `nodiscard` to immutable array functions

---

components/infobox/commons/infobox_patch.lua
components/infobox/wikis/dota2/infobox_cosmetic_custom.lua
components/widget/infobox/widget_infobox_highlights.lua

refactor(widget): migrate highlights widget to use children instead of content

---

components/infobox/commons/infobox_company.lua
components/infobox/commons/infobox_game.lua
components/infobox/commons/infobox_league.lua
components/infobox/commons/infobox_patch.lua
components/infobox/commons/infobox_person.lua
components/infobox/commons/infobox_scene.lua
components/infobox/commons/infobox_series.lua
components/infobox/commons/infobox_show.lua
components/infobox/commons/infobox_team.lua
components/infobox/commons/infobox_website.lua
components/infobox/wikis/fighters/infobox_league_custom.lua
components/infobox/wikis/formula1/infobox_team_custom.lua
components/infobox/wikis/formula1/infobox_unit_car_custom.lua
components/infobox/wikis/formula1/infobox_unit_engine_custom.lua
components/infobox/wikis/smash/infobox_league_custom.lua
components/infobox/wikis/trackmania/infobox_league_custom.lua
components/infobox/wikis/valorant/infobox_series_custom.lua
components/widget/infobox/widget_infobox_chronology.lua
components/widget/infobox/widget_infobox_links.lua

refactor(widgets): rename the input of widget infobox link and chronology to links instead of content

---

components/match2/wikis/geoguessr/match_summary.lua
components/statistics/count.lua

docs: fix anno related stuffs

---

components/match2/wikis/pokemon/match_group_input_custom.lua

refactor(match2): pokemon mgi

---

components/match2/wikis/trackmania/match_group_input_custom.lua
components/match2/wikis/trackmania/match_summary.lua
components/opponent/wikis/trackmania/opponent_display_custom.lua

Refactor the MGI for Trackmania

refactor(match): Trackmania MGI

---

components/match2/wikis/sideswipe/match_group_input_custom.lua

Refactor the MGI for Sideswipe

refactor(match2): sideswipe mgi

---

components/match2/wikis/omegastrikers/match_group_input_custom.lua
components/match2/wikis/omegastrikers/match_summary.lua

MGI Refactor for Omegastrikers

refactor(match2): omegastrikers mgi

---

components/match2/wikis/tetris/match_group_input_custom.lua
components/match2/wikis/tetris/match_summary.lua

refactor(match2): tetris mgi

---

components/match2/wikis/brawlhalla/match_group_input_custom.lua

refactor(match2): Brawlhalla MGI

---

components/match2/wikis/magic/match_group_input_custom.lua

refactor(match2): magic mgi

---

components/match2/wikis/splatoon/match_group_input_custom.lua
components/match2/wikis/splatoon/match_summary.lua

refactor(match2): splatoon mgi

---

components/match2/wikis/easportsfc/match_group_input_custom.lua

refactor(match2): EASportsFC MGI

---

components/match2/wikis/brawlstars/match_group_input_custom.lua
components/match2/wikis/callofduty/match_group_input_custom.lua
components/match2/wikis/counterstrike/match_group_input_custom.lua
components/match2/wikis/counterstrike/match_summary.lua
components/match2/wikis/overwatch/match_group_input_custom.lua
components/match2/wikis/rainbowsix/match_group_input_custom.lua
components/match2/wikis/valorant/match_group_input_custom.lua
standard/info/wikis/counterstrike/info.lua

refactor(match2): counterstrike mgi

---

components/match2/wikis/tetris/match_group_input_custom.lua

fix(match2): tetris error sometimes

---

standard/info/wikis/hearthstone/info.lua

Based on:
https://github.com/Liquipedia/Lua-Modules/pull/4518#issuecomment-2396334507

Update Hearthstone Info M2 status

---

components/match2/wikis/apexlegends/match_group_input_custom.lua

improve code quality for apex mgi
tested by kano

refactor(match2): apex mgi cleanup

---

components/match2/wikis/valorant/match_legacy.lua

Currently in legacy storgae on val only 5 players ares tsored independently of how many are set in the match/teamCard
This PR changes that by switching from hardcoded 1 to 5 to looping through match2players with Array.forEach
dev

fix(match2): valorant legacy storgae does not store enough players sometimes

---

standard/info/wikis/teamfortress/info.lua

Shoulod have been updated before

chore: update teamfortess match2 status

---

components/match2/wikis/clashroyale/match_legacy.lua
standard/info/wikis/clashroyale/info.lua

feat(match2): match legacy for clash royale

---

components/match2/wikis/ageofempires/legacy/legacy_bracket_match_summary.lua
components/match2/wikis/ageofempires/legacy/match_group_legacy_default.lua

Move handling of maps to Legacy BMS, this will avoid code repetition when creating the wrappers to showmatch and matchlistst start ..
/dev

feat(match2): Handle match1 map mapping in bms on aoe

---

components/match2/wikis/ageofempires/legacy/legacy_bracket_match_summary.lua

Somehow when I tested It seemed fine, Guess not.
live

fix(match2): Stringify map in Legacy BMS on aoe

---

components/match2/wikis/deadlock/match_summary.lua

docs(match2): deadlock annos

---

components/infobox/wikis/geoguessr/infobox_league_custom.lua
components/infobox/wikis/geoguessr/infobox_person_player_custom.lua

Importing non-existing modules
Live

fix(infobox): bad imports on geoguessr

---

components/match2/commons/match.lua
components/match2/commons/match_group_util.lua

No longer used since MGI refactors were completed

refactor(match2): some more removal of mapX support

---

components/match2/commons/match_group_display_bracket.lua

fix(match2): wrong qualified displayed for reset matches

---

components/match2/commons/match_summary_base.lua
components/match2/wikis/arenafps/match_summary.lua
components/match2/wikis/brawlstars/match_summary.lua
components/match2/wikis/callofduty/match_summary.lua
components/match2/wikis/clashofclans/match_summary.lua
components/match2/wikis/clashroyale/match_summary.lua
components/match2/wikis/crossfire/match_summary.lua
components/match2/wikis/dota2/match_summary.lua
components/match2/wikis/halo/match_summary.lua
components/match2/wikis/heroes/match_summary.lua
components/match2/wikis/honorofkings/match_summary.lua
components/match2/wikis/leagueoflegends/match_summary.lua
components/match2/wikis/mobilelegends/match_summary.lua
components/match2/wikis/osu/match_summary.lua
components/match2/wikis/overwatch/match_summary.lua
components/match2/wikis/pokemon/match_summary.lua
components/match2/wikis/rainbowsix/match_summary.lua
components/match2/wikis/splatoon/match_summary.lua
components/match2/wikis/tft/match_summary.lua
components/match2/wikis/valorant/match_summary.lua
components/match2/wikis/wildrift/match_summary.lua
components/match2/wikis/worldoftanks/match_summary.lua
components/widget/match/summary/widget_match_summary_all.lua
components/widget/match/summary/widget_match_summary_mvp.lua
definitions/mw.lua

Refactor MVP Row in Match Summary into a Widget instead
Tested on R6

refactor(match2): match summary mvp into a widget

---

components/transfer/commons/transfer_list.lua

Add a `true` as default for shown
dev to live

fix(transfer): missing default true

---

components/widget/infobox/widget_infobox_chronology.lua
components/widget/misc/widget_misc_inline_icon_and_text.lua

fix: order of inline icon and text

---

components/opponent/commons/player_display_custom.lua

Allows the intellisense to better understand

docs: improve player display intellisense 

---

components/widget/misc/widget_misc_inline_icon_and_text.lua

fix: actually fix the inline icon with text

---

definitions/mw.lua

docs: fix typo

---

components/widget/match/summary/widget_match_summary_character_ban_table.lua

fix(match2): do not show empty ban rows

---

components/auto_inline_icon/commons/auto_inline_icon.lua

Add an option to surpress the text and only show the icon
Live

feat: add support to auto inline icon to only show icon

---

components/widget/match/summary/widget_match_summary_mvp.lua

refactor(match2): cleanup mvp widget a bit

---

components/match2/wikis/dota2/match_summary.lua

With the removal of the ban bg-colors and tweaks to the display size, 7+7 characters now fit on a ban row
dev

refactor(match2): standardize ban display of dota2

---

components/match2/commons/match_summary_base.lua
components/match2/wikis/heroes/match_summary.lua
components/match2/wikis/honorofkings/match_summary.lua
components/match2/wikis/leagueoflegends/match_summary.lua
components/match2/wikis/mobilelegends/match_summary.lua
components/match2/wikis/pokemon/match_summary.lua
components/match2/wikis/smite/match_summary.lua
components/match2/wikis/wildrift/match_summary.lua

Looks weird when there's less than max amount of bans. Seems entirely unneeded.
dev on hok

feat(match2): remove defaultIcon for characterBans

---

components/match2/wikis/overwatch/legacy/match_maps_legacy.lua

fix(match2): overwatch legacy mapping forever loop

---

components/squad/commons/squad_row.lua
components/squad/commons/squad_utils.lua
components/squad/wikis/overwatch/squad_custom.lua
components/squad/wikis/starcraft2/squad_custom.lua
components/squad/wikis/stormgate/squad_custom.lua
components/widget/squad/widget_squad_core.lua
components/widget/squad/widget_squad_core_tldb.lua

docs: fix anno warnings after renames

---

components/match2/wikis/brawlstars/match_summary.lua
components/match2/wikis/clashroyale/match_summary.lua
components/match2/wikis/omegastrikers/match_summary.lua

Introduced with #4878, which removed the definition of the class on img tags itself
bugfix, so live

fix(match2): unstandardized pick/ban champion size is max

---

components/match2/commons/match_summary_base.lua
components/match2/wikis/deadlock/match_summary.lua
components/match2/wikis/dota2/match_summary.lua
components/match2/wikis/heroes/match_summary.lua
components/match2/wikis/honorofkings/match_summary.lua
components/match2/wikis/leagueoflegends/match_summary.lua
components/match2/wikis/mobilelegends/match_summary.lua
components/match2/wikis/pokemon/match_summary.lua
components/match2/wikis/smite/match_summary.lua
components/match2/wikis/wildrift/match_summary.lua
components/widget/match/summary/widget_match_summary_character_ban_table.lua

Standardize the character parsing for mobas. In the future we want to use "participants", but waiting until it's moved to opponents.players instead
dev on dota2

refactor(match2): standardize character parsing in moba match summaries

---

standard/tier/wikis/brawlstars/tier_data.lua

Kick unused/unwanted D-tier. https://discord.com/channels/93055209017729024/591393837927366672/1297982203824705546
live

feat(tier): remove unused D-tier from Brawlstars

---

components/match2/wikis/warcraft/match_summary.lua

fix(match2): wc3 hero picks are incorrectly flipped

---

components/match2/wikis/apexlegends/match_group_input_custom.lua

When refactoring the MGI there was a typo in the point modifier handling
dev

fix(match2): apex's point modifier

---

components/match2/wikis/battlerite/match_summary.lua
components/match2/wikis/deadlock/match_summary.lua
components/match2/wikis/magic/match_summary.lua
components/match2/wikis/pokemon/match_summary.lua

Keeping the Match Summary refactors going
Tested on deadlock

refactor(match2): MS on battlerite, deadlock, magic and pokemon

---

components/match2/wikis/ageofempires/match_summary.lua

Linter complains
@mbergen tested

fix(match2): aoe typo

---

components/match2/commons/match_group_input_util.lua
components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua
components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
components/match2/wikis/ageofempires/match_group_input_custom.lua
components/match2/wikis/ageofempires/match_summary.lua
components/match2/wikis/dota2/match_group_input_custom.lua
components/match2/wikis/halo/match_group_input_custom.lua
components/match2/wikis/halo/match_summary.lua
components/match2/wikis/rocketleague/match_group_input_custom.lua
components/match2/wikis/rocketleague/match_summary.lua
components/match2/wikis/warcraft/match_group_input_custom.lua
components/match2/wikis/warcraft/match_summary.lua
standard/links/commons/links.lua

Standardize H2H Links + RL and AoE's custom link implementations. 
After this PR+#4944 only SC2 FFA and Counterstrike uses custom link displaying functionality
dev on all impacted wikis

refactor(match2): move h2h links to MGI

---

components/match2/wikis/ageofempires/match_summary.lua
components/match2/wikis/arenafps/match_summary.lua
components/match2/wikis/brawlhalla/match_summary.lua
components/match2/wikis/brawlstars/match_summary.lua
components/match2/wikis/callofduty/match_summary.lua
components/match2/wikis/clashofclans/match_summary.lua
components/match2/wikis/counterstrike/match_summary.lua
components/match2/wikis/criticalops/match_summary.lua
components/match2/wikis/crossfire/match_summary.lua
components/match2/wikis/easportsfc/match_summary.lua
components/match2/wikis/fighters/match_summary.lua
components/match2/wikis/halo/match_summary.lua
components/match2/wikis/hearthstone/match_summary.lua
components/match2/wikis/heroes/match_summary.lua
components/match2/wikis/omegastrikers/match_summary.lua
components/match2/wikis/osu/match_summary.lua
components/match2/wikis/overwatch/match_summary.lua
components/match2/wikis/rainbowsix/match_summary.lua
components/match2/wikis/rocketleague/match_summary.lua
components/match2/wikis/sideswipe/match_summary.lua
components/match2/wikis/splatoon/match_summary.lua
components/match2/wikis/splitgate/match_summary.lua
components/match2/wikis/tft/match_summary.lua
components/match2/wikis/trackmania/match_summary.lua
components/match2/wikis/valorant/match_summary.lua
components/match2/wikis/worldoftanks/match_summary.lua
components/match2/wikis/zula/match_summary.lua

Minor Cleanup in match summaries, mostly moving logic and display around
/dev preview on top 10 wikis by trafic, and 10 first wikis alphabetically

refactor(match2): minor cleanups in many wiki match summaries

---

components/match2/wikis/halo/match_summary.lua
components/match2/wikis/hearthstone/match_summary.lua
components/match2/wikis/overwatch/match_summary.lua
components/match2/wikis/rocketleague/match_summary.lua
components/match2/wikis/sideswipe/match_summary.lua
components/match2/wikis/splitgate/match_summary.lua
components/match2/wikis/teamfortress/match_summary.lua
components/match2/wikis/tetris/match_summary.lua
components/match2/wikis/tft/match_summary.lua
components/match2/wikis/trackmania/match_summary.lua

Wiki with other stuff not refactored yet, such as craft-wikis, wikis with map veto or wikis with CS's match status thing
Preview tested a few

refactor(match2): match summary createBody H-T

---

components/match2/wikis/clashroyale/match_group_input_custom.lua
components/match2/wikis/clashroyale/match_summary.lua

Also remove bans, as it was only used on ***1*** match on the entire wiki!
/dev

refactor(match2): clashroyale match summary body

---

components/match2/wikis/omegastrikers/match_summary.lua

Essentionally the same as BrawlStars, changing the layout (putting picks in the game row instead of a different table)
dev

refactor(match2): standardize ms-body on omegastrikers

---

components/match2/commons/match_summary_base.lua
components/match2/wikis/arenafps/match_summary.lua
components/match2/wikis/brawlstars/match_summary.lua
components/match2/wikis/callofduty/match_summary.lua
components/match2/wikis/clashofclans/match_summary.lua
components/match2/wikis/clashroyale/match_summary.lua
components/match2/wikis/counterstrike/match_summary.lua
components/match2/wikis/criticalops/match_summary.lua
components/match2/wikis/crossfire/match_summary.lua
components/match2/wikis/easportsfc/match_summary.lua
components/match2/wikis/geoguessr/match_summary.lua
components/match2/wikis/halo/match_summary.lua
components/match2/wikis/heroes/match_summary.lua
components/match2/wikis/omegastrikers/match_summary.lua
components/match2/wikis/osu/match_summary.lua
components/match2/wikis/overwatch/match_summary.lua
components/match2/wikis/rainbowsix/match_summary.lua
components/match2/wikis/rocketleague/match_summary.lua
components/match2/wikis/sideswipe/match_summary.lua
components/match2/wikis/splatoon/match_summary.lua
components/match2/wikis/splitgate/match_summary.lua
components/match2/wikis/teamfortress/match_summary.lua
components/match2/wikis/tetris/match_summary.lua
components/match2/wikis/tft/match_summary.lua
components/match2/wikis/trackmania/match_summary.lua
components/match2/wikis/valorant/match_summary.lua
components/match2/wikis/worldoftanks/match_summary.lua
components/match2/wikis/zula/match_summary.lua

Use the break widget everywhere, instead of the old one
Tested on arenafps

refactor(match2): use break widget

---

components/match2/commons/match_summary_base.lua
components/match2/wikis/counterstrike/match_summary.lua
components/match2/wikis/criticalops/match_summary.lua
components/match2/wikis/heroes/match_summary.lua
components/match2/wikis/osu/match_summary.lua
components/match2/wikis/rainbowsix/match_summary.lua
components/match2/wikis/splatoon/match_summary.lua
components/match2/wikis/valorant/match_summary.lua
components/match2/wikis/worldoftanks/match_group_input_custom.lua
components/match2/wikis/worldoftanks/match_summary.lua
components/match2/wikis/zula/match_summary.lua

Move from Customs (via class overrides) to standard format with some options
/dev on r6

refactor(match2): standarize mapVeto display further

---

components/match2/wikis/counterstrike/match_summary.lua
components/match2/wikis/criticalops/match_summary.lua
components/match2/wikis/heroes/match_summary.lua
components/match2/wikis/osu/match_summary.lua
components/match2/wikis/rainbowsix/match_summary.lua
components/match2/wikis/splatoon/match_summary.lua
components/match2/wikis/valorant/match_summary.lua
components/match2/wikis/worldoftanks/match_summary.lua
components/match2/wikis/zula/match_summary.lua

Continue body refactors
tested on R6

refactor(match2): match summary body to widget on more wikis

---

components/transfer/commons/transfer_list.lua

As per request on discord remove SPECIAL_ROLES exception when merging transfers
dev (some days ago)

feat(transfer): remove SPECIAL_ROLES exception when merging transfers

---

components/match2/wikis/crossfire/match_summary.lua

fix(match2): MVP display missing on crossfire

---

components/match2/commons/match_group_display_helper.lua
components/match2/commons/starcraft_starcraft2/match_summary_ffa_starcraft.lua
components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
components/match2/wikis/starcraft/brkts_wiki_specific.lua
components/match2/wikis/starcraft2/brkts_wiki_specific.lua
components/widget/match/summary/widget_match_summary_game_comment.lua
components/widget/match/summary/widget_match_summary_game_win_loss_indicator.lua
stylesheets/commons/Brackets.less

https://liquipedia.net/starcraft2/User:Hjpalpha/wip18
https://liquipedia.net/starcraft2/User:Hjpalpha/wip17
(mind due to the css changes one needs to adjust that via browser tools)

refactor(match2): starcraft(2) MatchSummary

---

stylesheets/commons/Brackets.less

fix(match2): game row font size unexpceted increase in #4969

---

scripts/generate_changelog_local.sh

Script to generate a changelog from the commits.
Based on https://github.com/smichard/conventional_changelog, core structure is the same, but heavily modified non the less. 
Usage of the script will be internal only initially
Locally on wsl

chore: script to generate changelogs

---

components/match2/wikis/stormgate/match_summary.lua
components/match2/wikis/warcraft/match_summary.lua
components/widget/match/summary/widget_match_summary_game_center.lua

Improve display based on feedback
dev tools

feat(match2): improve display on wc3 and sg

---

components/match2/wikis/rainbowsix/match_summary.lua

feat(match2): partial standardization of match summary on R6 

---

components/match2/wikis/hearthstone/match_summary.lua
components/widget/match/summary/widget_match_summary_character.lua

Use standardized display components for HS
dev

feat(match2): standardize hearthstone display

---

components/match2/wikis/brawlhalla/match_summary.lua

Use standardized display components on bh
dev

feat(match2): standardize display of brawlhalla

---

components/infobox/commons/infobox_league.lua

Due to venues sometimes being called the same thing, also supply the city & country in those cases.
dev

feat(infobox): also supply city and country when venue is known

---

components/match2/commons/starcraft_starcraft2/match_summary_starcraft_ffa.lua

need the opponent instead of just the scores and placements etc present because of a TBD check on the opponent.
live

fix(match2): sc(2) ffa erroring on shown 0 scores

---

components/match2/wikis/pokemon/match_summary.lua

curry adds the date as first not as last param
this pr accounts for that
dev

fix(match2): pokemon game data not shown in MS

---

standard/tier/wikis/mobilelegends/tier_data.lua

feat: add national tiertype on MLBB

---

components/match2/wikis/ageofempires/match_summary.lua
components/match2/wikis/arenafps/match_summary.lua
components/match2/wikis/callofduty/match_summary.lua
components/match2/wikis/clashofclans/match_summary.lua
components/match2/wikis/clashroyale/match_summary.lua
components/match2/wikis/counterstrike/match_summary.lua
components/match2/wikis/criticalops/match_summary.lua
components/match2/wikis/crossfire/match_summary.lua
components/match2/wikis/easportsfc/match_summary.lua
components/match2/wikis/fighters/match_summary.lua
components/match2/wikis/geoguessr/match_summary.lua
components/match2/wikis/halo/match_summary.lua
components/match2/wikis/heroes/match_summary.lua
components/match2/wikis/omegastrikers/match_summary.lua
components/match2/wikis/osu/match_summary.lua
components/match2/wikis/overwatch/match_summary.lua
components/match2/wikis/splatoon/match_summary.lua
components/match2/wikis/splitgate/match_summary.lua
components/match2/wikis/teamfortress/match_summary.lua
components/match2/wikis/tetris/match_summary.lua
components/match2/wikis/tft/match_summary.lua
components/match2/wikis/worldoftanks/match_summary.lua
components/match2/wikis/zula/match_summary.lua

Use the standard icon display where applicable
dev on AoE

feat(match2): standardize icon display in match summaries

---

components/match2/commons/match_group_display_helper.lua
components/match2/wikis/rainbowsix/match_summary.lua
components/widget/match/summary/widget_match_summary_game_center.lua

Largely standard the display of R6 
/dev

feat(match2): standardize R6 display

---

components/match2/wikis/arenafps/match_summary.lua

feat(match2): standardize arenafps display

---

components/match2/commons/match_group_display_helper.lua
components/match2/wikis/callofduty/match_summary.lua
components/match2/wikis/crossfire/match_summary.lua
components/match2/wikis/halo/match_summary.lua
components/match2/wikis/overwatch/match_summary.lua

Standardize Map Mode Icon display, requires external non-standardized module "MapModes" atm
dev on OW

feat(match2): standardize MapMode icon

---

components/match2/wikis/criticalops/match_summary.lua
components/match2/wikis/zula/match_summary.lua

Standardize COps and Zula's displays
/dev

feat(match2): standardize cops and zula's display

---

components/match2/wikis/valorant/match_summary.lua

Standardize display on valorant
/dev

feat(match2): standardize valorant's display

---

components/match2/wikis/osu/match_summary.lua

Fix missing tonumber plus a typo on function name
dev

fix(match2): on osu, match summary errors

---

components/match2/wikis/counterstrike/match_summary.lua

Standardize the display of Counterstike's Match Summary
/dev

feat(match2): standardize counterstrike display

---

components/match2/commons/match_summary_base.lua
components/match2/wikis/ageofempires/match_summary.lua
components/match2/wikis/clashofclans/match_summary.lua
components/match2/wikis/clashroyale/match_group_input_custom.lua
components/match2/wikis/clashroyale/match_summary.lua
components/match2/wikis/easportsfc/match_summary.lua
components/match2/wikis/fighters/match_summary.lua
components/match2/wikis/heroes/match_summary.lua
components/match2/wikis/osu/match_summary.lua
components/match2/wikis/rocketleague/match_group_input_custom.lua
components/match2/wikis/rocketleague/match_summary.lua
components/match2/wikis/sideswipe/match_summary.lua
components/match2/wikis/splatoon/match_group_input_custom.lua
components/match2/wikis/splatoon/match_summary.lua
components/match2/wikis/tft/match_summary.lua
components/match2/wikis/trackmania/match_summary.lua

Standardize remaining game rows, there's a few that could use further standardization in the future, but most are in good state
dev on AoE, FIFA, Fighters and RL (the main wikis of the bunch)

feat(match2): standardize rest of the wiki's game rows

---

components/match2/wikis/brawlhalla/match_summary.lua
components/match2/wikis/brawlstars/match_summary.lua
components/match2/wikis/crossfire/match_summary.lua
components/match2/wikis/geoguessr/match_summary.lua
components/match2/wikis/hearthstone/match_summary.lua
components/match2/wikis/magic/match_summary.lua
components/match2/wikis/osu/match_summary.lua
components/match2/wikis/overwatch/match_summary.lua
components/match2/wikis/rocketleague/match_summary.lua
components/match2/wikis/sideswipe/match_summary.lua
components/match2/wikis/splatoon/match_summary.lua
components/match2/wikis/splitgate/match_summary.lua
components/match2/wikis/teamfortress/match_summary.lua
components/match2/wikis/tetris/match_summary.lua

docs(match2): fix some annotations

---

components/match2/wikis/stormgate/match_summary.lua
components/match2/wikis/warcraft/match_summary.lua
stylesheets/commons/Brackets.less

just some capitalization stuff
live

fix(match2): wc/sg off-faction icons not shown

---

components/match2/commons/match_group_input_util.lua
components/match2/wikis/dota2/match_group_input_custom.lua
components/match2/wikis/leagueoflegends/match_group_input_custom.lua

Standardize more on dota2 and league
dev

feat(match2): standard processMatch on dota2 and lol

---

components/match2/commons/match.lua
components/match2/commons/match_group_input_util.lua
components/match2/commons/match_group_util.lua

First step in solving #4821
Not Played Example
Walkover Example

feat(match2): replace `walkover` and `resulttype` with `status` on match level on standardized wikis

---

definitions/mw.lua
standard/mock/mock_team_template.lua
test_assets/team_template_data.lua

set up a mock for team templates so we can simulate them in some test cases
- on wiki with some mw.logObject tests to check the functions return the same as the normal team template extension
- tested in busted via #5016

feat(team template): set up a mock

---

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
components/match2/commons/starcraft_starcraft2/match_group_input_starcraft_ffa.lua
components/match2/wikis/ageofempires/match_group_input_custom.lua
components/match2/wikis/apexlegends/match_group_input_custom.lua
components/match2/wikis/counterstrike/match_group_input_custom.lua
components/match2/wikis/stormgate/match_group_input_custom.lua
components/match2/wikis/warcraft/match_group_input_custom.lua

Second step in solving #4821, follow up to #5043
Tested on CS

feat(match2): replace `walkover` and `resulttype` with `status` on match level on non-standardized wikis

---

components/match2/commons/match_group_input_util.lua
components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
components/match2/commons/starcraft_starcraft2/match_group_input_starcraft_ffa.lua
components/match2/wikis/dota2/match_group_input_custom.lua
components/match2/wikis/halo/match_group_input_custom.lua
components/match2/wikis/rocketleague/match_group_input_custom.lua
components/match2/wikis/stormgate/match_group_input_custom.lua
components/match2/wikis/warcraft/match_group_input_custom.lua

standardize processMatch on sc(2), sg and wc
dev

feat(match2): standardize processMatch on sc(2), sg and wc

---

components/match2/wikis/dota2/match_group_input_custom.lua

fix(match2): missing passalong of map parser on dota

---

components/match2/commons/match_group_input_util.lua
components/match2/wikis/brawlhalla/match_group_input_custom.lua
components/match2/wikis/clashofclans/match_group_input_custom.lua
components/match2/wikis/deadlock/match_group_input_custom.lua
components/match2/wikis/dota2/match_group_input_custom.lua
components/match2/wikis/hearthstone/match_group_input_custom.lua
components/match2/wikis/honorofkings/match_group_input_custom.lua
components/match2/wikis/magic/match_group_input_custom.lua
components/match2/wikis/magic/match_summary.lua
components/match2/wikis/smite/match_group_input_custom.lua
components/match2/wikis/tetris/match_group_input_custom.lua
components/match2/wikis/tetris/match_summary.lua

Standardize ProcessMap on HoK, prepare for standardization on other wikis
dev on HoK

feat(match2): standardize mapName handling for processMap standardization

---

components/match2/wikis/ageofempires/match_group_input_custom.lua
components/match2/wikis/brawlhalla/match_group_input_custom.lua
components/match2/wikis/fighters/match_group_input_custom.lua
components/match2/wikis/magic/match_group_input_custom.lua
components/match2/wikis/tetris/match_group_input_custom.lua

Extract Map Extradata where it's currently inline to independent function

refactor(match2): extract map extradata to seperate function where it isn't

---

components/match2/commons/match.lua
components/match2/commons/match_group_input_util.lua

Next step in solving #4821
dev on r6

feat(match2): replace `walkover` and `resulttype` with `status` and `opponents` on map level on standardized wikis

---

components/infobox/wikis/dota2/infobox_league_custom.lua
components/match2/commons/match_summary_base.lua

they just annoyed me during modules sync so lets get rid of them :P
vscode

docs(match2): missing parameter documentation

---

components/match2/wikis/valorant/match_summary.lua
components/widget/match/summary/widget_match_summary_characters.lua

Apply the hidden agents to valorant on mobile again
/dev

feat(match2): hide agents on valorant in mobile view

---

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
components/match2/commons/starcraft_starcraft2/match_group_input_starcraft_ffa.lua
components/match2/wikis/ageofempires/match_group_input_custom.lua
components/match2/wikis/apexlegends/match_group_input_custom.lua
components/match2/wikis/brawlstars/match_group_input_custom.lua
components/match2/wikis/clashofclans/match_group_input_custom.lua
components/match2/wikis/clashroyale/match_group_input_custom.lua
components/match2/wikis/dota2/match_group_input_custom.lua
components/match2/wikis/easportsfc/match_group_input_custom.lua
components/match2/wikis/goals/match_group_input_custom.lua
components/match2/wikis/leagueoflegends/match_group_input_custom.lua
components/match2/wikis/magic/match_group_input_custom.lua
components/match2/wikis/omegastrikers/match_group_input_custom.lua
components/match2/wikis/osu/match_group_input_custom.lua
components/match2/wikis/overwatch/match_group_input_custom.lua
components/match2/wikis/rocketleague/match_group_input_custom.lua
components/match2/wikis/smite/match_group_input_custom.lua
components/match2/wikis/stormgate/match_group_input_custom.lua
components/match2/wikis/tetris/match_group_input_custom.lua
components/match2/wikis/valorant/match_group_input_custom.lua
components/match2/wikis/warcraft/match_group_input_custom.lua

Next step in solving #4821
mix testing on various wikis by me and hjp

feat(match2): replace `walkover` and `resulttype` with `status` and `opponents` on map level on non-standardized wikis

---

components/match2/commons/match_group_input_util.lua
components/match2/wikis/magic/match_group_input_custom.lua

feat(match2): standardize magic's map processing

---

components/match2/commons/match_group_input_util.lua
components/match2/wikis/clashroyale/match_summary.lua

Cleanup after previous merged PRs, these functions are no longer used.
check function usage by search

chore(match2): remove now unused code

---

standard/tier/wikis/fighters/tier_data.lua

feat(tier): remove unused tier-4 from Fighters

---

components/match2/commons/match_group_input_util.lua
components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
components/match2/commons/starcraft_starcraft2/match_group_input_starcraft_ffa.lua
components/match2/wikis/stormgate/match_group_input_custom.lua
components/match2/wikis/warcraft/match_group_input_custom.lua

standardize sc2, sg, wc map processing
dev

refactor(match2): standardize sc2, sg, wc map processing

---

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
components/match2/wikis/stormgate/match_group_input_custom.lua
components/match2/wikis/warcraft/match_group_input_custom.lua

fix(match2): calculateMapScore faulty on craft wikis

---

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft_ffa.lua

fix 2 passalongs so it doesn't error anymore
live

fix(match2): sc(2) free-for-all errors

---

components/match2/wikis/rocketleague/match_summary.lua

Re-add recently-missing space
/dev

feat(match2): add space to OT-length on RL

---

components/external_media_links/external_media_link.lua
components/external_media_links/external_media_list.lua

Links should be stored with underscores.
For now, querying happens with either underscores or spaces. Eventually it should also only query for underscores.
dev

feat(eml): Pagify links in ExternalMediaLink storage

---

components/match2/wikis/worldofwarcraft/get_match_group_copy_paste_wiki.lua
components/match2/wikis/worldofwarcraft/match_group_input_custom.lua
components/match2/wikis/worldofwarcraft/match_summary.lua

Create support for WoW in match2
https://liquipedia.net/worldofwarcraft/Guild_Clash

feat(match2): create support for world of warcraft

---

javascript/commons/BattleRoyale.js

Fixes the different errors that appeared on the new version of Battle Royal match fetching.
Dev env + production

fix(match2): battle royale issue with matchids starting with a number and incorrect caching

---

components/match2/wikis/goals/match_summary.lua

Dev and Live https://liquipedia.net/goals/GOALS_Community_Cup/3

feat(match2): enable per-map score display for GOALS

---

components/match2/wikis/battalion/get_match_group_copy_paste_wiki.lua
components/match2/wikis/battalion/match_group_input_custom.lua
components/match2/wikis/battalion/match_legacy.lua
components/match2/wikis/battalion/match_summary.lua
standard/info/wikis/battalion/info.lua

Support Battalion 1944
https://liquipedia.net/battalion/Fragadelphia/Winter_Wartide#Playoffs

feat(match2): create support for battalion

---

components/match2/wikis/squadrons/match_group_input_custom.lua
components/match2/wikis/squadrons/match_legacy.lua
components/match2/wikis/squadrons/match_summary.lua
standard/info/wikis/squadrons/info.lua

Support for Squadrons in Match2
https://liquipedia.net/squadrons/Squadrons_Championship_League/5/Elite/Playoffs

feat(match2): create support for squadrons

---

components/match2/wikis/paladins/get_match_group_copy_paste_wiki.lua
components/match2/wikis/paladins/match_group_input_custom.lua
components/match2/wikis/paladins/match_legacy.lua
components/match2/wikis/paladins/match_summary.lua
standard/info/wikis/paladins/info.lua

Support Paladins for match2
https://liquipedia.net/paladins/Mid-Season_Invitational/2019/Play-In#Results

feat(match2): create support for paladins

---

components/infobox/wikis/apexlegends/infobox_league_custom.lua
components/infobox/wikis/brawlstars/infobox_league_custom.lua
components/infobox/wikis/clashofclans/infobox_league_custom.lua
components/infobox/wikis/tft/infobox_league_custom.lua
components/infobox/wikis/valorant/infobox_league_custom.lua

remove the old input stuff after conversion bot runs
N/A, just kicking now unused params

feat(infobox): finish the publishertier standardization

---

components/match2/wikis/artifact/get_match_group_copy_paste_wiki.lua
components/match2/wikis/artifact/match_group_input_custom.lua
components/match2/wikis/artifact/match_legacy.lua
components/match2/wikis/artifact/match_summary.lua
standard/info/wikis/artifact/info.lua

Support artifact
https://liquipedia.net/artifact/User:Rathoz

feat(match2): create support for artifact

---

components/notability/wikis/clashofclans/notability_checker_config.lua

found it on the wiki while fixing something for them ...
live ...

feat(notability): add clashofclans notability checker config

---

components/match2/wikis/trackmania/brkts_wiki_specific.lua
components/match2/wikis/trackmania/match_group_display_bracket_custom.lua

chore(match2): add untracked trackmania files

---

components/match2/commons/match_group_input_util.lua
components/match2/wikis/apexlegends/match_group_input_custom.lua

Initial standardization of MGI to allow for proper rollout of BR/FFA to more wikis.
dev

feat(match2): standardize FFA/BR input

---

components/match2/wikis/pubg/brkts_wiki_specific.lua
components/match2/wikis/pubg/game_summary.lua
components/match2/wikis/pubg/get_match_group_copy_paste_wiki.lua
components/match2/wikis/pubg/match_group_input_custom.lua
components/match2/wikis/pubg/match_legacy.lua
components/match2/wikis/pubg/match_summary.lua
standard/info/wikis/pubg/info.lua
standard/info/wikis/pubgmobile/info.lua

feat(match2): support for pubg

---

components/match2/wikis/hearthstone/legacy/match_group_legacy_default.lua

Winner and finished was being handled incorrectly.
/dev

fix(match2): finished handling in hearthstone's legacy wrapper

---

components/match2/commons/match_summary_ffa.lua
components/match2/wikis/apexlegends/game_summary.lua
components/match2/wikis/pubg/game_summary.lua
components/match2/wikis/pubg/match_summary.lua
components/match2/wikis/pubgmobile/game_summary.lua
components/match2/wikis/pubgmobile/match_summary.lua

Move common elements to commons
dev on apex

refactor(match2): standardize BR display further

---

components/match2/wikis/freefire/match_group_input_custom.lua
components/match2/wikis/pubg/match_group_input_custom.lua
components/match2/wikis/pubgmobile/match_group_input_custom.lua

Unless I misunderstood **3** here, Both PUBG games and Free Fire played as a team of 4 compared to Apex's Trio of 3

feat(match2): increase max players on some BRs

---

components/match2/wikis/ageofempires/match_summary.lua

**Please ping if merged before/without #5120, as that was applied as hotfix**
Reintroduced in #5023 
Eventually this should be solved with ellipsis, but i can't get it to work properly while generally allowing it to grow/shrink
dev
(last map in screenshot is longest used mapname on the wiki)

fix(match2): Prevent line wrap in bracket popups on AoE

---

components/match2/wikis/hearthstone/match_summary.lua

fix(match2): fix nil in array on hearthstone

---

components/main_page/commons/main_page_layout.lua
components/main_page/wikis/dota2/main_page_layout_data.lua
components/main_page/wikis/rainbowsix/main_page_layout_data.lua
components/match_ticker/commons/match_ticker.lua
components/match_ticker/commons/match_ticker_display_components_new.lua
standard/info/commons/info.lua
standard/info/wikis/dota2/info.lua
standard/info/wikis/leagueoflegends/info.lua
stylesheets/commons/Banner.less
stylesheets/commons/FilterButtons.less
stylesheets/commons/Panels.less

Made a Main Page Layout for easier manage of the Main Page when the dota2 main page was revamped. As there are plans in the pipeline to roll it out to move wikis, 
dota2 is live, r6 in user page

feat(mainpage): standardize main page layouts

---

components/match2/commons/match_group_input_util.lua
components/match2/commons/match_summary_ffa.lua
components/match2/wikis/apexlegends/match_group_input_custom.lua
components/match2/wikis/apexlegends/match_summary.lua
components/match2/wikis/fortnite/match_group_input_custom.lua
components/match2/wikis/fortnite/match_summary.lua
components/match2/wikis/freefire/match_group_input_custom.lua
components/match2/wikis/freefire/match_summary.lua
components/match2/wikis/naraka/match_group_input_custom.lua
components/match2/wikis/naraka/match_summary.lua
components/match2/wikis/pubg/match_group_input_custom.lua
components/match2/wikis/pubg/match_summary.lua
components/match2/wikis/pubgmobile/match_group_input_custom.lua
components/match2/wikis/pubgmobile/match_summary.lua

Fully standardize "Match Point" handling and point parsing. Adds MPe and Manual Points to wikis that currently don't have it.
/dev

feat(match2): further standarize BR

---

standard/info/wikis/fortnite/info.lua
standard/info/wikis/freefire/info.lua
standard/info/wikis/naraka/info.lua

Some wikis that should have m2 status

chore: update match2 status on some BR wikis

---

components/match2/commons/match_group_input_util.lua
components/match2/wikis/apexlegends/match_group_input_custom.lua
components/match2/wikis/fortnite/match_group_input_custom.lua
components/match2/wikis/freefire/match_group_input_custom.lua
components/match2/wikis/naraka/match_group_input_custom.lua
components/match2/wikis/pubg/match_group_input_custom.lua
components/match2/wikis/pubgmobile/match_group_input_custom.lua

All of the BR wikis are using the same parsing logic, which does have some fundamental differences compared to the non-BR one. So extracted this to commons
/dev

feat(match2): make standard BR-map parsing

---

components/match2/commons/match_summary_ffa.lua
components/match2/wikis/apexlegends/game_summary.lua
components/match2/wikis/fortnite/game_summary.lua
components/match2/wikis/freefire/game_summary.lua
components/match2/wikis/naraka/game_summary.lua
components/match2/wikis/pubg/game_summary.lua
components/match2/wikis/pubgmobile/game_summary.lua
components/match2/wikis/underlords/game_summary.lua

Extract some common stuff to commons
dev

feat(match2): standardize br-map opponent enrichment

---

components/match2/wikis/autochess/game_summary.lua
components/match2/wikis/autochess/get_match_group_copy_paste_wiki.lua
components/match2/wikis/autochess/match_group_input_custom.lua
components/match2/wikis/autochess/match_summary.lua

Same as underlords, expect for default points from the generator

feat(match2): support for autochess

---

components/match2/wikis/autochess/get_match_group_copy_paste_wiki.lua
components/match2/wikis/tft/game_summary.lua
components/match2/wikis/tft/get_match_group_copy_paste_wiki.lua
components/match2/wikis/tft/match_group_input_custom.lua
components/match2/wikis/tft/match_summary_ffa.lua
components/match2/wikis/underlords/get_match_group_copy_paste_wiki.lua

Thanks for the refactor in #5195 we can now support both FFA and 2-opponents on the wiki. This implements that for TFT
together with #5195

feat(match2): support TFT FFA

---

components/match2/wikis/arenafps/game_summary.lua
components/match2/wikis/arenafps/get_match_group_copy_paste_wiki.lua
components/match2/wikis/arenafps/match_group_input_custom.lua
components/match2/wikis/arenafps/match_summary_ffa.lua

Same way as TFT, add it to arenafps also

feat(match2): support arenafps FFA

---

components/match2/wikis/halo/game_summary.lua
components/match2/wikis/halo/get_match_group_copy_paste_wiki.lua
components/match2/wikis/halo/match_group_input_custom.lua
components/match2/wikis/halo/match_summary_ffa.lua

Same way as TFT, add it to halo also

feat(match2): support halo FFA

---

components/match2/wikis/callofduty/game_summary.lua
components/match2/wikis/callofduty/get_match_group_copy_paste_wiki.lua
components/match2/wikis/callofduty/match_group_input_custom.lua
components/match2/wikis/callofduty/match_summary_ffa.lua

Same way as TFT, add it to COD also, specifically for WarZone (its BR mode)

feat(match2): support call of duty warzone (BR)

---

standard/info/wikis/paladins/info.lua

chore: update match2 status on paladins

---

standard/info/wikis/goals/info.lua

new wiki so status should be 2

chore: update match2 status on goals

---

components/opponent/commons/starcraft_starcraft2/player_display_starcraft.lua

resolve pagename for sc(2) `TemplatePlayer`
live

fix(opponent): resolve pagename for sc(2) `TemplatePlayer`

---

components/match2/wikis/counterstrike/match_external_links.lua
standard/links/commons/links.lua
standard/links/commons/links_priority_groups.lua
stylesheets/commons/Icons.less

Some new third-party tournament platform for CS2. Added in all the usual places.
Tested via dev deploy :)

feat: Add "Esplay" icon for tournaments and matches

---

standard/links/commons/links.lua
standard/links/commons/links_priority_groups.lua
stylesheets/commons/Icons.less

Link and icons for FIDE rating (chess)

Link and icons for FIDE rating (chess)

---

.github/workflows/deploy test.yml
.github/workflows/deploy.yml
.github/workflows/scheduled.yml
scripts/deploy.sh
scripts/deploy_res.sh

This reverts commit f6b5fb58928e0a9b3c02b0c873d6ebfedc117e52.

revert: "ci(deploy): change deploy to use a bot password (#5209)"

---

components/match2/wikis/autochess/match_group_input_custom.lua
components/match2/wikis/autochess/match_summary.lua
standard/info/wikis/autochess/info.lua

feat(match2): support non-ffa matches on autochess

---

components/match2/wikis/counterstrike/game_summary.lua
components/match2/wikis/counterstrike/match_group_input_custom.lua
components/match2/wikis/counterstrike/match_summary_ffa.lua

Use standardized match processing for CS and add FFA support
By kano

feat(match2): standardize CS match processsing and add FFA support

---

components/match2/wikis/apexlegends/match_group_input_custom.lua
components/match2/wikis/apexlegends/match_summary.lua

Add support for Apex's Arenas (2-opponents matches)
dev by kano

feat(match2): add support for arena in Apex

---

components/match2/wikis/stormgate/match_group_util_custom.lua

do not create loop during imports
live as hot fix

fix(match2): import loop on stormgate

---

standard/info/wikis/simracing/info.lua

chore: fix misspelling of Gran Turismo Sport

---

components/match2/commons/match_group_input_util.lua
components/match2/wikis/apexlegends/match_group_input_custom.lua
components/match2/wikis/trackmania/brkts_wiki_specific.lua
components/match2/wikis/trackmania/match_group_input_custom.lua
components/match2/wikis/trackmania/match_summary_ffa.lua

Support Trackmania's FFA. They will use normal brackets for up to 4 opponents, and for opponent counts higher than that, use FFA.
dev

feat(match2): add support for trackmania FFA

---

components/match2/commons/match_group_input_util.lua
components/match2/wikis/ageofempires/match_group_input_custom.lua

Add a customizable point on commons for readOpponent, which allows AoE to be put into
dev

feat(match2): standardize aoe's match parsing

---

components/match2/wikis/ageofempires/match_group_input_custom.lua
components/match2/wikis/ageofempires/match_summary_ffa.lua

Initial version of FFA for AoE. More features will be needed for full usage
https://liquipedia.net/ageofempires/User:Rathoz

feat(match2): support FFA on AoE

---

components/match2/commons/game_summary.lua
components/match2/commons/match_group_input_util.lua
components/match2/commons/match_summary_base_ffa.lua
components/match2/wikis/ageofempires/match_group_input_custom.lua
components/opponent/wikis/ageofempires/player_display_custom.lua

Add civ display on AoE for their FFA
dev

feat(match2): add civ display on AoE FFA

---

components/match2/commons/match_group_input_util.lua
components/match2/wikis/hearthstone/match_group_input_custom.lua
components/match2/wikis/hearthstone/match_summary_ffa.lua
components/opponent/commons/opponent_display.lua

Add FFA Support for Hearthstone
Adds special support for placement range in games, as in HS BG multiple players frequerntly change the same game placement.  The placement points is the average of the range they were in. We do not display the range (yet?), it's only calculating
https://liquipedia.net/hearthstone/User:Kanoodles/Testing

feat(match2): support hearthstone ffa

---

components/main_page/wikis/deadlock/main_page_layout_data.lua

Updating deadlock mainmage module. Navigation cards

---

standard/info/wikis/geoguessr/info.lua
standard/info/wikis/omegastrikers/info.lua
standard/info/wikis/smash/info.lua

chore: update some out of date m2 statuses

---

components/match2/wikis/warcraft/game_summary.lua
components/match2/wikis/warcraft/match_group_input_custom.lua
components/match2/wikis/warcraft/match_summary_ffa.lua

mostly a copy from sc(2) plus adding heroes support
dev
https://liquipedia.net/warcraft/User:Hjpalpha

feat(match2): support ffa on warcraft

---

components/filter_buttons/wikis/apexlegends/filter_buttons_config.lua
components/main_page/wikis/apexlegends/main_page_layout_data.lua
components/main_page/wikis/dota2/main_page_layout_data.lua
components/main_page/wikis/rainbowsix/main_page_layout_data.lua
components/widget/match/ticker/widget_match_ticker_container.lua
stylesheets/commons/Banner.less

A new shiny mainpage for apex
https://liquipedia.net/apexlegends/User:Kanoodles/MainPageTest

feat: support new mainpage for Apex

---

components/match_ticker/commons/match_ticker.lua

fix: smaller issues with match ticker

---

components/match2/wikis/leagueoflegends/match_summary.lua

Requested by contributors
Tested by ElectricalBoy

feat(match2): do not show skipped games on lol

---

components/filter_buttons/wikis/halo/filter_buttons_config.lua
components/main_page/wikis/halo/main_page_layout_data.lua
stylesheets/commons/Banner.less

Tested on;
https://liquipedia.net/halo/User:Kanoodles/MainPage

feat(mainpage): Standardize Halo main page

---

components/filter_buttons/wikis/leagueoflegends/filter_buttons_config.lua
components/main_page/wikis/leagueoflegends/main_page_layout_data.lua
stylesheets/commons/Banner.less

_Depends on #5293_
This PR standardizes main page layout of League of Legends wiki.
- Sandbox: <https://liquipedia.net/leagueoflegends/User:ElectricalBoy/Sandbox3>

feat(mainpage): Standardize LoL main page

---

components/filter_buttons/filter_buttons.lua
components/filter_buttons/wikis/apexlegends/filter_buttons_config.lua
components/filter_buttons/wikis/dota2/filter_buttons_config.lua
components/filter_buttons/wikis/halo/filter_buttons_config.lua
components/filter_buttons/wikis/leagueoflegends/filter_buttons_config.lua
components/filter_buttons/wikis/pubg/filter_buttons_config.lua
components/filter_buttons/wikis/pubgmobile/filter_buttons_config.lua
components/filter_buttons/wikis/rainbowsix/filter_buttons_config.lua
components/widget/tournaments/widget_tournaments_ticker_sublist.lua

Resolves #5325 
Done some initial tests on [leagueoflegends:User:ElectricalBoy/Sandbox3](https://liquipedia.net/leagueoflegends/User:ElectricalBoy/Sandbox3) and seems to be good. @ElectricalBoy you know the scene better, does it acutally look correct?

fix: incorrect validation/fallback values in tournament filtering in mainpage

---

components/game_table/deadlock/game_table_character_custom.lua

<https://discord.com/channels/93055209017729024/765984788107624468/1329123257588256951>
N/A; copied and pasted content of <https://liquipedia.net/deadlock/Module:GameTable/Character/Custom>

feat(gameTable): deadlock support

---

components/filter_buttons/wikis/hearthstone/filter_buttons_config.lua
components/main_page/wikis/hearthstone/main_page_layout_data.lua
stylesheets/commons/Banner.less

Setting up the new main apge for Hearthstone;
Tested on;
https://liquipedia.net/hearthstone/User:Kanoodles/MainPageTest

feat(mainpage): new Hearthstone main page 

---

standard/info/wikis/arenafps/info.lua

Give Painkiller and Unreal Tournament 4 its proper logo
Add AVP2 as I've spotted a tournament with no displayed game input, turns out a missing entry

feat: update gamedata on arenafps

---

components/match2/wikis/pubg/match_group_input_custom.lua
components/match2/wikis/pubg/match_summary.lua

copy from pubgmobile
/dev & live

feat(match2): Handle 2 opponents in pubg

---

components/filter_buttons/wikis/arenafps/filter_buttons_config.lua
components/main_page/wikis/arenafps/main_page_layout_data.lua
stylesheets/commons/Banner.less

Setting up the new Main Page on the Arena FPS wiki.
tested on;
https://liquipedia.net/arenafps/User:Kanoodles/Test

feat(mainpage): new ArenaFPS main page

---

components/main_page/wikis/halo/main_page_layout_data.lua

Currently used a specific quarter, changed it to use {{Current term}} so it doesn't need to be updates manually.

feat: update link for transfer edits on halo

---

components/filter_buttons/wikis/fortnite/filter_buttons_config.lua
components/main_page/wikis/fortnite/main_page_layout_data.lua
stylesheets/commons/Banner.less

Setting up the new Main Page on the Fortnite wiki.
tested on;
https://liquipedia.net/fortnite/User:Kanoodles/Test

feat(mainpage): new Fortnite main page

---

components/infobox/wikis/dota2/infobox_league_custom.lua

Been requested to store this in lpdb, like in teams and players.
dev

feat: add leagueid to dota2 lpdb storage

---

components/match2/wikis/leagueoflegends/match_page.lua

fix(match2): match vod not showing on lol match pages

---

components/standings/commons/standings_parse_wiki.lua
components/standings/commons/standings_parser.lua
components/standings/wikis/apexlegends/standings_table_legacy_ffa.lua
components/widget/standings/widget_standings_ffa.lua

Legacy wrapper for apex's `Module:League_standings_without_lobby_ranked` & `Module:League_standings_without_lobby`.
dev with preview

feat: legacy support for ffa standings on apex

---

components/mvp_table/commons/mvp_table.lua

just gsub underscores to spaces and also lower it
dev

fix(mvpTable): `Category:Pages with underscore team templates` gets set in some cases

---

standard/info/wikis/crossfire/info.lua

Apparently I had it incorrect since the beginning, it supposed to be an upper F.

fix: CrossFire text capitalization

---

components/infobox/wikis/chess/infobox_league_custom.lua
standard/info/wikis/chess/info.lua

Separate variants and time controls
/dev

feat: separate variants and time controls on chess infobox league

---

components/standings/commons/standings_parse_wiki.lua

Was missing one param in the anno
N/A

docs(standings): missing anno

---

components/prize_pool/commons/prize_pool_import.lua
standard/tournament_structure.lua

exclude ffa standings and brackets with ffa matches during ppt import since they currently cause issues
dev

feat: disable ffa prizepool imports

---

components/opponent/wikis/fighters/opponent_custom.lua
components/opponent/wikis/smash/opponent_custom.lua

resolves part of #5206
add char support in `toLpdbStruct` and `fromLpdbStruct`, this also results in chars being stored in placement data
dev on fighters

feat(opponent): add char support in `toLpdbStruct` and `fromLpdbStruct`

---

components/infobox/wikis/valorant/infobox_person_player_custom.lua

To be able to use #5419, enable storage of teamhistory datapoints from THA.
dev

feat(infobox): Enable TeamHistory datapoints on valorant

---

components/widget/ratings/widget_ratings.lua
components/widget/ratings/widget_ratings_list.lua
standard/icon_data.lua

A module on the new Dota 2 main page that shows a partial snippet of the Dota 2 rankings
Laura's dev wiki

feat: Main Page snippet of Dota 2 rankings

---

standard/currency_data.lua

Resolves https://github.com/Liquipedia/Lua-Modules/issues/5441
Adding Armenian dram (AMD) currency to Currency/Data
Tested on Infobox league
https://liquipedia.net/chess/User:SobakaPirat/AMD

feat: add Armenian dram (AMD) currency

---

components/match2/wikis/clashroyale/match_summary.lua

Mistakenly removed in #5229
live

fix(match2): missing tower cards on clash royale

---

components/tournament/tournament.lua

Add the simple nil catch
N/A, just noticed it due to #5451

fix(tournamentTicker): missing nil catch

---

components/main_page/wikis/apexlegends/main_page_layout_data.lua

Adding the Headlines into the Apex Legends main page.
Also re-ordered the mobile layout a little bit

feat: add headlines to Apex Mainpage

---

components/tournament/tournament.lua

Potential adjustment for #5428 
dev

feat(tournament): make phase calculation based on midnight instead of noon

---

components/infobox/wikis/mobilelegends/infobox_item_custom.lua

* Add new parameters, e.g., `category`, `type`, `status`, etc.
* Remove unused parameters.
* Reduce the number of categories in `_getWikiCategories`.
* Set LPDB data.
Currently tested on my test page: [Test Page](https://liquipedia.net/mobilelegends/User:MatryoshX/Test_Page)

feat(infobox): update mobile legends infobox item

---

components/notability/wikis/geoguessr/notability_checker_config.lua

Notability checker config for GeoGuessr. Base code was taken from osu with an addition of points for the first place in qualification.
Tested by me and Steve
https://liquipedia.net/geoguessr/Special:RunQuery/SobakaPirat/Notability_Checker

feat(notability checker): configurations for GeoGuessr

---

components/match2/wikis/fighters/match_legacy.lua

fixes #5465 
dev in <https://liquipedia.net/fighters/User:ElectricalBoy>

fix(match2): missing nil catch in fighters legacy storage

---

components/infobox/wikis/fighters/infobox_game_custom.lua

[`{{Infobox game}}`](https://liquipedia.net/fighters/Template:Infobox_game) in fighters is hardcoded html. This PR adds infobox module for games so that we can kick html portion of the template.
dev: [fighters:User:ElectricalBoy](https://liquipedia.net/fighters/User:ElectricalBoy)

feat(infobox): add custom game infobox to fighters

---

components/filter_buttons/wikis/brawlstars/filter_buttons_config.lua
components/main_page/wikis/brawlstars/main_page_layout_data.lua
stylesheets/commons/Banner.less

Adding the new Main Page to Brawl Stars.
Tested on:
https://liquipedia.net/brawlstars/User:Kanoodles/Test

feat(mainpage): new Brawl Stars main page

---

standard/flags_master_data.lua

Resolves #5469
Add USSR alpha 2/3 codes.

feat: add ussr country codes

---

components/widget/ratings/widget_ratings_list.lua
stylesheets/commons/RankingTable.less

A Beta label on the rankings page and main page snippet that tells the user rankings are subject to tweaking.
dev wiki

feat: add `Beta` label to Dota 2 rankings

---

components/match2/commons/match_group_display_bracket.lua
components/widget/tournaments/widget_tournament_label.lua
components/widget/tournaments/widget_tournament_tier_pill.lua
components/widget/tournaments/widget_tournaments_ticker_sublist.lua

docs: fix some annos

---

components/hidden_data_box/wikis/valorant/hidden_data_box_custom.lua
components/infobox/wikis/valorant/infobox_league_custom.lua

chore(infobox): followup cleanup for 4856

---

components/infobox/wikis/stormgate/infobox_item_custom.lua

docs: fix some stormgate infobox item annos

---

javascript/commons/BattleRoyale.js
javascript/commons/Commons_mainpage.js
javascript/commons/Commons_tools.js
javascript/commons/FilterButtons.js
javascript/commons/Mainpage.js
javascript/commons/RankingTable.js

- Change `.done` to `.then`
- Add extra null check to rankingstable
wikidev
https://gitlab.com/teamliquid-dev/liquipedia/issue-bucket/-/issues/311

ci: js-lint pipeline is failing due to upstreams change

---

components/match2/commons/match_group.lua

feat(match2): support MatchPages in Userspace

---

components/match2/commons/match_summary_base.lua
components/match2/wikis/overwatch/get_match_group_copy_paste_wiki.lua
components/match2/wikis/overwatch/match_group_input_custom.lua
components/match2/wikis/overwatch/match_summary.lua
components/widget/match/summary/widget_match_summary_character_ban_table.lua
standard/icon_data.lua

https://liquipedia.net/overwatch/User:ElectricalBoy#v2

feat(match2): support char bans on overwatch

---

components/match2/wikis/tarkovarena/get_match_group_copy_paste_wiki.lua
components/match2/wikis/tarkovarena/match_group_input_custom.lua
components/match2/wikis/tarkovarena/match_summary.lua

Match2 for New Wiki, Tarkov Arena
This is in fact actually the same #5487 (War Thunder) setup the only change is the name of the game 
because both wikis works with the same setup, technically their match works in same way: Map, Scores, Winner
LIVE

feat(match2): Support for Tarkov Arena

---

components/infobox/wikis/callofduty/infobox_map_custom.lua

No one in COD wiki notice the wiki still use non module version (me as well), I make it close to that as possible
https://liquipedia.net/callofduty/Arklov_Peak/MW

feat(Infobox): custom map for COD

---

components/infobox/wikis/valorant/infobox_character_custom.lua

This PR adds character infobox for Valorant.
dev in userspace + preview in live

feat(infobox): character infobox for Valorant

---

components/infobox/commons/infobox_character.lua
components/infobox/wikis/valorant/infobox_character_custom.lua
components/main_page/wikis/valorant/main_page_layout_data.lua

small oversights from #5510...
hotfix in live

fix(infobox): Valorant character infobox breaking backwards compatibility

---

components/match2/wikis/leagueoflegends/get_match_group_copy_paste_wiki.lua

follow-up for #5473
This PR adds caster params to LoL generator.
dev

feat(match2): add caster params in LoL generator

---

stylesheets/commons/RankingTable.less

fix: beta tag is not wrapping on dota2 rankings

---

components/widget/misc/widget_panel.lua

small oversight from #5519
N/A

docs: fix incorrect return type anno for Panel

---

standard/array.lua

simple typo fixes
spellchecker

docs: fix spelling mistakes in Array documentation

---

components/infobox/wikis/starcraft2/infobox_person_player_custom.lua

solves person infoboxes erroring in userspace on sc2
problem was introduced with #5430 
the problematic code was never reached in userspace before that change
live

fix(infobox): userspace errors on sc2 infobox player

---

components/infobox/wikis/dota2/infobox_cosmetic_custom.lua
components/widget/infobox/widget_infobox_cell.lua

simple spelling fix
spellchecker

chore(infobox): fix spelling in CellWidgetOptions

---

standard/links/commons/links.lua
standard/links/commons/links_priority_groups.lua
stylesheets/commons/Icons.less

Add FIDE tournament and Chess-Results to links

feat: add support for FIDE tournament links and Chess-Results links

---

components/patch/patch.lua

fix: incorrect deploy header

---

components/filter_buttons/commons/filter_buttons.lua
components/main_page/wikis/apexlegends/main_page_layout_data.lua
components/main_page/wikis/arenafps/main_page_layout_data.lua
components/main_page/wikis/brawlstars/main_page_layout_data.lua
components/main_page/wikis/deadlock/main_page_layout_data.lua
components/main_page/wikis/dota2/main_page_layout_data.lua
components/main_page/wikis/fortnite/main_page_layout_data.lua
components/main_page/wikis/halo/main_page_layout_data.lua
components/main_page/wikis/hearthstone/main_page_layout_data.lua
components/main_page/wikis/leagueoflegends/main_page_layout_data.lua
components/main_page/wikis/marvelrivals/main_page_layout_data.lua
components/main_page/wikis/overwatch/main_page_layout_data.lua
components/main_page/wikis/pubg/main_page_layout_data.lua
components/main_page/wikis/pubgmobile/main_page_layout_data.lua
components/main_page/wikis/rainbowsix/main_page_layout_data.lua
components/main_page/wikis/valorant/main_page_layout_data.lua
components/widget/filter_buttons/widget_filter_buttons.lua
components/widget/filter_buttons/widget_filter_buttons_button.lua
components/widget/filter_buttons/widget_filter_buttons_row.lua

This PR converts FilterButtons to return widgets instead of html.
dev in LoL / Overwatch

refactor(mainpage): filter buttons into widgets

---

components/infobox/commons/infobox_weapon.lua

regression from #5541
dev + hotfix in live

fix(infobox): missing nil catch in weapon infobox

---

components/infobox/commons/infobox_team.lua
components/infobox/extensions/commons/role_of.lua
components/infobox/wikis/apexlegends/infobox_team_custom.lua
components/infobox/wikis/counterstrike/infobox_team_custom.lua
components/infobox/wikis/dota2/infobox_team_custom.lua
components/infobox/wikis/freefire/infobox_team_custom.lua
components/infobox/wikis/heroes/infobox_team_custom.lua
components/infobox/wikis/honorofkings/infobox_team_custom.lua
components/infobox/wikis/leagueoflegends/infobox_team_custom.lua
components/infobox/wikis/pubgmobile/infobox_team_custom.lua
components/infobox/wikis/rainbowsix/infobox_team_custom.lua
components/infobox/wikis/teamfortress/infobox_team_custom.lua
components/infobox/wikis/valorant/infobox_team_custom.lua
components/infobox/wikis/wildrift/infobox_team_custom.lua

This reverts commit f9d50fe0c272dfea6b8eda24156d18e1144618f2.
Requested to be reverted pending outcome of the poll

revert: feat(infobox): remove staff sections in infobox team

---

components/filter_buttons/wikis/starcraft2/filter_buttons_config.lua
components/main_page/wikis/starcraft2/main_page_layout_data.lua
standard/date_ext.lua
stylesheets/commons/Banner.less

This PR standardizes main page layout of Starcraft II wiki.
Credit for initial work done for this PR goes to @elisazanatta
<https://liquipedia.net/starcraft2/User:ElectricalBoy/MainPage>

feat(mainpage): new Starcraft II main page

---

components/widget/main_page/widget_main_page_transfers_list.lua

requested on discord: <https://discord.com/channels/93055209017729024/268719633366777856/1347623861855719444>
oversight from #5570
dev in LoL / OW

feat(mainpage): use local version of transfer input form if available

---

components/main_page/wikis/dota2/main_page_layout_data.lua
standard/icon_data.lua

Follow-up for #5570 
This PR cleans up remaining HTML strings in Dota 2 mainpage.
dev

refactor(mainpage): convert html strings to widgets in dota2 mainpage

---

components/infobox/wikis/warthunder/infobox_map_custom.lua

fix(infobox): broken deploy header in warthunder map infobox

---

standard/array.lua

docs: add documentation to Array.flatMap and Array.parseCommaSeparatedString

---

components/filter_buttons/wikis/valorant/filter_buttons_config.lua

Adds two missing regions to the mapping, as reported on discord.
There's another issue with these, see #5587 
dev to live

fix(filter): Add missing entries to region mapping on Valorant

---

components/match_table/wikis/counterstrike/match_table_custom.lua

Sets the CS-custom option to only display "prioritized tiertypes"
Further adjustments necessary:
Bo1 scores (see https://github.com/Liquipedia/Lua-Modules/pull/4487#issuecomment-2707499711)
Round stats
dev, including #5580 and #5581:
Left non-standard, right standard

feat: Add custom match table on CS

---

.github/workflows/deploy test.yml
.github/workflows/deploy.yml

ci: fix files pattern

---

lua/wikis/commons/MatchTable.lua

feat: Allow to filter match table by type

---

lua/wikis/commons/GameSummary/Starcraft.lua
lua/wikis/starcraft/GameSummary.lua
lua/wikis/starcraft2/GameSummary.lua

chore: drop the `/Ffa` from sc(2) gamesummary module name

---

lua/wikis/valorant/FilterButtons/Config.lua

yet another missed region
live

feat: add another region mapping for valorant

---

lua/wikis/commons/Widget/Standings/Ffa.lua
stylesheets/commons/Standings.less

Resolves #5387 
Fixes the Button overflow issue on mobile described here:

fix(StandingsFfa): Mobile overflow issue with round button

---

stylesheets/commons/Standings.less

I made a wrong css selector with an extra >. This fixes that.

fix(StandingsFfa): wrong css selector

---

lua/wikis/valorant/Infobox/Person/Player/Custom.lua

As requested on discord https://discord.com/channels/93055209017729024/268719633366777856/1349782981430083687
dev

feat(infobox): Set specialRoles=true for TeamHistoryAuto on valorant

---

lua/wikis/commons/Widget/Match/Ticker/Container.lua

fix: Fix defaultItems being nil in MatchTickerContainer

---

lua/wikis/trackmania/MatchGroup/Legacy/Default.lua

https://github.com/Liquipedia/Lua-Modules/actions/runs/13894670443
N/A

chore(match2): fix broken deploy header

---

lua/wikis/rainbowsix/MainPageLayout/data.lua

A small follow-up for #5632 
dev

feat(mainpage): use lpdb query for counting operators in r6 mainpage

---

lua/wikis/rainbowsix/Infobox/Character/Custom.lua

fix(infobox): missing nil catch in R6 character infobox

---

lua/wikis/apexlegends/MainPageLayout/data.lua

Adding visibility for App Download on on the mainpage as part of a project on various wikis.
Tested on Live

feat: add App to Apex Mainpage

---

lua/wikis/deadlock/MainPageLayout/data.lua

Adding visibility for App Download on on the mainpage as part of a project on various wikis.
Tested on Live

feat: add app on Deadlock Mainpage

---

lua/wikis/leagueoflegends/MainPageLayout/data.lua

Adding visibility for App Downloadon on the mainpage as part of a project on various wikis.
Tested on Live

feat: add app on LoL Mainpage

---

lua/wikis/commons/ParticipantTable/Base.lua

fix(participantTable): imported opponents are not sorted

---

lua/wikis/commons/Widget/Grid/Container.lua
lua/wikis/commons/Widget/Panel.lua

docs: update type annotations for grid and panel widgets

---

lua/wikis/fighters/MatchSummary.lua

feat: display scores better on fighters' match2

---

stylesheets/commons/Fountain.less

Just larger width to accommodate texts/strings for the ru wiki within Template:Spellcard. Thank you.

feat(spellcard): larger width for the ru wiki

---

lua/wikis/callofduty/MainPageLayout/data.lua

This PR applies changes from #5674 to COD mainpage
dev

refactor(mainpage): use mainpage match ticker widget in COD mainpage

---

lua/wikis/hearthstone/FilterButtons/Config.lua

feat(filterButtons): tier type filter buttons for hearthstone

---

lua/spec/condition_spec.lua
lua/wikis/commons/Condition.lua
lua/wikis/commons/YearsActive/Base.lua

feat: implement Comparator.ge and Comparator.le

---

lua/wikis/heroes/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Setting up the new mainpage for heroes of the storm
https://liquipedia.net/heroes/User:Kanoodles/Test

feat(mainpage): new HotS main page 

---

lua/wikis/freefire/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Setting up the new Free Fire Main Page
https://liquipedia.net/freefire/User:Kanoodles/Test

feat(mainpage): new Free Fire main page

---

stylesheets/commons/Mainpage.less

This reverts commit 98db7eaccfe18a5de58376dcc64b037af5c49b92.

revert: "feat(mainpage): improve tournament list headers on Lakeside (#5584)"

---

lua/wikis/commons/MatchSummary/Base.lua

docs(match2): fix incorrect MatchSummary.createSubstitutesComment documentation

---

lua/wikis/leagueoflegends/MatchGroup/Input/Custom/MatchPage.lua

fix(match2): vod param in LoL MatchPage map is ignored

---

lua/wikis/commons/Format/Table.lua
lua/wikis/commons/Icon/Data.lua
lua/wikis/commons/Patch/Calendar.lua
lua/wikis/commons/Patch/Fetch.lua
lua/wikis/commons/Patch/List.lua
lua/wikis/commons/Widget/Basic/DataTable.lua
lua/wikis/worldoftanks/Tier/Custom.lua

stacked on #5712
has suggestions to bring the code of #5712 closer to standard

refactor #5712

---

lua/wikis/brawlstars/NotabilityChecker/config.lua

Update the points in the Notability Checker for the brawlstars wiki. Request by Editor Kairyu in #admin-requests on Discord. Notability Guidelines were adjusted a few months ago
https://discord.com/channels/93055209017729024/765984788107624468/1355935077258756296
dev

feat(notability checker): Update points for brawlstars

---

lua/wikis/commons/MatchTable.lua

Uses OpponentDisplay.InlineScore to handle float scores
dev

feat(MatchTable): handle decimal score display

---

lua/wikis/dota2/MatchSummary.lua

This PR ports #5310 to dota2
dev

feat(match2): do not show skipped games on dota2

---

lua/wikis/mobilelegends/FilterButtons/Config.lua
lua/wikis/mobilelegends/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Setting up the new Main page on Mobile Legends;
Tested on https://liquipedia.net/mobilelegends/User:Hesketh2/New

feat(mainpage): new Mobile Legends main page

---

lua/wikis/commons/MatchGroup/Input/Util.lua

Removes the score requirement for matches to be set as finished
To not get bad data in case of finished matches without score nor winner input it applies the notplayed status in that case
dev

fix(match2): finished handling for matches without scores

---

lua/wikis/mobilelegends/MainPageLayout/data.lua

The Patches pill was using the same images as items, therefore I've changed the picture used.

feat(mainpage): update image for patches navigation card in mobilelegends mainpage

---

lua/wikis/mobilelegends/MainPageLayout/data.lua

This PR applies changes from #5674 to mobilelegends mainpage (#5757)
dev

refactor(mainpage): use mainpage match ticker widget in mobilelegends mainpage

---

lua/wikis/commons/MatchGroup/Legacy.lua
lua/wikis/hearthstone/MatchGroup/Legacy/Default.lua

As all Brackets with legacy wrappers should only be used on old pages it seems reasonable to assume that all matches in brackets that use legacy wrapper are finished.
dev

feat(match2): Set finished to true for all Matches in Legacy wrapper

---

lua/wikis/commons/Infobox/Patch.lua
lua/wikis/counterstrike/Infobox/Patch/Custom.lua

This PR adds custom patch infobox to counterstrike wiki
dev

feat(infobox): patch infobox for counterstrike

---

lua/wikis/easportsfc/GetMatchGroupCopyPaste/wiki.lua

This PR adds copy-paste generator for easportsfc from wiki, with all the necessary refactors/rewrites put in place.
[easportsfc:Special:RunQuery/BracketCopyPaste/dev](https://liquipedia.net/easportsfc/Special:RunQuery/BracketCopyPaste/dev)

feat(match2): copy-paste generator for easportsfc

---

lua/wikis/ageofempires/Faction/Data.lua
lua/wikis/ageofempires/Faction/IconData.lua

updated god names and updated god icons as discussed on discord.

fea: update faction icons and name for AoM chinese gods

---

lua/wikis/trackmania/ResultsTable/Custom.lua

This PR adds custom results table for trackmania to the repository.
N/A; copied directly from [trackmania:Module:ResultsTable/Custom](https://liquipedia.net/trackmania/Module:ResultsTable/Custom)

feat(resultsTable): custom results table for trackmania

---

lua/wikis/pubgmobile/Infobox/Weapon/Custom.lua

1:1 copy from pubg, was missed during the wiki split
N/A

chore(infobox): add missing pubgm infobox weapon

---

lua/wikis/heroes/GetMatchGroupCopyPaste/wiki.lua

This PR adds copy-paste generator for heroes from wiki, with all the necessary refactors/rewrites put in place.
[heroes:Special:RunQuery/BracketCopyPaste/dev](https://liquipedia.net/heroes/Special:RunQuery/BracketCopyPaste/dev)

feat(match2): copy-paste generator for heroes

---

lua/wikis/marvelrivals/Infobox/Character/Custom.lua

Adds additional storage to LPDB Extradata for Marvel Rivals Character Infobox (Hero). 
Adds the role icon for the role field (light & darkmode)
Testing live [here](https://liquipedia.net/marvelrivals/FenrirTest)

feat(infobox): Marvel Rivals Character Infobox Update

---

lua/wikis/osu/MainPageLayout/data.lua

chore(mainpage): fix broken deploy header

---

lua/wikis/ageofempires/FilterButtons/Config.lua
lua/wikis/ageofempires/Info.lua
lua/wikis/ageofempires/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Adds the new mainpage layout on AoE.
https://liquipedia.net/ageofempires/User:SyntacticSalt/Main_Page + inspect for banner

feat: Add new mainpage on AoE

---

lua/wikis/commons/Timezone/Data.lua

Kazakhstan unified their timezone on march 1st, shifting the ALMT time to UTC+5.
The idea would be to add two versions (i happily take ideas on the name) of ALMT time and bot-convert usages before that date to the version with +6.
Just data

feat: Add new version of Alma-Ata Time

---

lua/wikis/tarkovarena/Infobox/Person/Player/Custom.lua

Only the Auto Team History was needed for the wiki

feat(Infobox): Tarkov Arena player

---

lua/wikis/omegastrikers/GetMatchGroupCopyPaste/wiki.lua
lua/wikis/sideswipe/GetMatchGroupCopyPaste/wiki.lua
lua/wikis/splatoon/GetMatchGroupCopyPaste/wiki.lua
lua/wikis/tetris/GetMatchGroupCopyPaste/wiki.lua

This PR adds copy-paste generator for omegastrikers, sideswipe, splatoon, tetris from wikis, with all the necessary refactors/rewrites put in place.
dev

feat(match2): add "new" match2 generators to repository

---

stylesheets/commons/NavigationCard.less

Improves the display of navigation card images on wider (>1024px)  screens, by increasing the image height depending on the screen width. This reduces the amount of image that is cutoff from top and bottom.
On smaller screens, the behavior is unchanged, as 5rem will be greater than 5vw.
| Previous | New | Screen width
|-----------|------| -------------|
| ![grafik](https://github.com/user-attachments/assets/ea54f75f-ee96-4764-bd93-6e0e6c351e00)  | ![grafik](https://github.com/user-attachments/assets/faf52538-2617-4438-bc96-73f7a595a05f) | 570px | 
| ![grafik](https://github.com/user-attachments/assets/25cafac5-1013-4de1-911d-6356cc224001)  | ![grafik](https://github.com/user-attachments/assets/4e91151d-e899-4687-bdaf-7b29db518439) | 760px |
| …

feat(mainpage): Improve navigation card display on various screen sizes

---

lua/wikis/valorant/MainPageLayout/data.lua

Add "Liquipedia App" panel to main page 
Tested on main page directly

feat(mainpage): add Liquipedia App panel to valorant mainpage

---

lua/wikis/fighters/Info.lua

Adding Fatal Fury: City of the Wolves (commonly abbreviated to CotW in the FGC) to the game list

feat: add CotW to Fighters

---

lua/wikis/commons/Widget/Match/Summary/Ffa/GameDetails.lua

fix(match2): error when there are no caster in FFA mode

---

stylesheets/commons/Fountain.less

This class is repurposed for other things. Increasing the size by 10% for visibility.

feat: increase font-size for certain class

---

lua/wikis/commons/Abbreviation.lua
lua/wikis/commons/AutoInlineIcon.lua
lua/wikis/commons/Hotkey.lua
lua/wikis/commons/Links.lua
lua/wikis/commons/Placement.lua
lua/wikis/commons/ReferenceCleaner.lua
lua/wikis/commons/Timezone.lua

preps git maintained modules in regards to a process to remove Class.export (after everything uses Lua.invoke wrapper)
for more context see #5776
N/A

chore: prepare git usages of Class.export for its removal process

---

templates/templatesToProtect

ci: add matchpage copy-paste template to protected template list

---

lua/wikis/commons/Widget/Match/Page/PlayerDisplay.lua
lua/wikis/dota2/MatchPage.lua
lua/wikis/leagueoflegends/MatchPage.lua

Regression from #5810
- dota2: dev
- leagueoflegends: hotfix in live

fix(match2): missing nil catches in matchpages

---

lua/wikis/ageofempires/MainPageLayout/data.lua
lua/wikis/apexlegends/MainPageLayout/data.lua
lua/wikis/arenafps/MainPageLayout/data.lua
lua/wikis/brawlstars/MainPageLayout/data.lua
lua/wikis/callofduty/MainPageLayout/data.lua
lua/wikis/dota2/MainPageLayout/data.lua
lua/wikis/fortnite/MainPageLayout/data.lua
lua/wikis/freefire/MainPageLayout/data.lua
lua/wikis/halo/MainPageLayout/data.lua
lua/wikis/hearthstone/MainPageLayout/data.lua
lua/wikis/leagueoflegends/MainPageLayout/data.lua
lua/wikis/marvelrivals/MainPageLayout/data.lua
lua/wikis/mobilelegends/MainPageLayout/data.lua
lua/wikis/osu/MainPageLayout/data.lua
lua/wikis/overwatch/MainPageLayout/data.lua
lua/wikis/pubg/MainPageLayout/data.lua
lua/wikis/pubgmobile/MainPageLayout/data.lua
lua/wikis/rainbowsix/MainPageLayout/data.lua
lua/wikis/starcraft2/MainPageLayout/data.lua
lua/wikis/tft/MainPageLayout/data.lua
lua/wikis/valorant/MainPageLayout/data.lua

As per discussion in discord DMs add boxid 1516 for all `specialEvents`
N/A

chore(MainPage): box id 1516 for `specialEvents`

---

lua/wikis/marvelrivals/Infobox/Person/Player/Custom.lua

Add custom infobox to marvelrivals wiki, handling for categories (ingame roles + staff)
dev

feat(Infobox): custom player infobox for marvelrivals

---

lua/wikis/commons/ParticipantTable/Base.lua

as title says^^
resolves #5851
dev

fix(participantTable): merge with ppt placement failing for some underscore constelations

---

lua/wikis/valorant/FilterButtons/Config.lua

fix: Add additional unmapped regions on Valorant

---

lua/wikis/leagueoflegends/MatchPage.lua

maintenance for better readability; no change in functionality
dev

refactor(match2): clean up player loadout code in lol match page

---

lua/spec/flags_spec.lua
lua/wikis/commons/CountryRepresentation.lua
lua/wikis/commons/ExternalMediaLink.lua
lua/wikis/commons/Flags.lua
lua/wikis/commons/Infobox/Character.lua
lua/wikis/commons/Infobox/Company.lua
lua/wikis/commons/Infobox/Person.lua
lua/wikis/commons/Infobox/Scene.lua
lua/wikis/commons/Infobox/Series.lua
lua/wikis/commons/Infobox/Show.lua
lua/wikis/commons/Infobox/Team.lua
lua/wikis/commons/Infobox/Weapon.lua
lua/wikis/commons/MatchGroup/Display/Helper.lua
lua/wikis/commons/Player/Display.lua
lua/wikis/commons/PortalPlayers.lua
lua/wikis/commons/Widget/Ratings/List.lua
lua/wikis/heroes/Infobox/League/Custom.lua
lua/wikis/rocketleague/Infobox/Person/Player/Custom.lua

prereq:
Clean up `Flags.Icon` and `Flags.languageIcon` plus their on git-usages
N/A

chore: Clean up `Flags.Icon` and `Flags.languageIcon`

---

lua/wikis/dota2/MatchGroup/Input/Custom.lua
lua/wikis/dota2/MatchPage.lua

cherry-picked from #5821
hotfix in live

fix(match2): missing nil catch in dota2 match page

---

lua/wikis/ageofempires/Infobox/Faction/Custom.lua
lua/wikis/commons/Infobox/Faction.lua
lua/wikis/commons/Infobox/Faction/Custom.lua

Adds a basic Infobox/Faction, combined with a custom implementation for AoE
dev

feat: create Infobox Faction for AoE

---

lua/wikis/ageofempires/FilterButtons/Config.lua
lua/wikis/ageofempires/MainPageLayout/data.lua
lua/wikis/commons/Widget/FilterButtons.lua

Adjust some last details on AoE mainpage before going live:
- Display game abbreviations in filterbuttons if on desktop
- Make game filters always visible
- Use dynamic faction page count
dev

feat: Improve details on AoE mainpage

---

lua/wikis/ageofempires/GetMatchGroupCopyPaste/wiki.lua

Adds means to generate FFA-code to AoE
live with adjusted form

feat: Add FFA options to AoE CopyPaste generator

---

lua/wikis/commons/MatchPage/Base.lua
lua/wikis/commons/OpponentLibraries.lua
lua/wikis/commons/Widget/Match/Page/MapVeto.lua
lua/wikis/valorant/MatchPage.lua
stylesheets/commons/BigMatch.less

As a VAL fan, I want to see what maps each team picked/banned.

VALMatch: Implement map veto section

---

lua/wikis/commons/Logic.lua

docs: update Module:Logic documentation

---

lua/definitions/mw.lua
lua/wikis/ageofempires/MainPageLayout/data.lua
lua/wikis/apexlegends/MainPageLayout/data.lua
lua/wikis/arenafps/MainPageLayout/data.lua
lua/wikis/brawlstars/MainPageLayout/data.lua
lua/wikis/callofduty/MainPageLayout/data.lua
lua/wikis/commons/Icon/Data.lua
lua/wikis/commons/WantToHelpList.lua
lua/wikis/commons/Widget/MainPage/WantToHelp.lua
lua/wikis/deadlock/MainPageLayout/data.lua
lua/wikis/dota2/MainPageLayout/data.lua
lua/wikis/fortnite/MainPageLayout/data.lua
lua/wikis/freefire/MainPageLayout/data.lua
lua/wikis/geoguessr/MainPageLayout/data.lua
lua/wikis/halo/MainPageLayout/data.lua
lua/wikis/hearthstone/MainPageLayout/data.lua
lua/wikis/heroes/MainPageLayout/data.lua
lua/wikis/leagueoflegends/MainPageLayout/data.lua
lua/wikis/marvelrivals/MainPageLayout/data.lua
lua/wikis/mobilelegends/MainPageLayout/data.lua
lua/wikis/osu/MainPageLayout/data.lua
lua/wikis/overwatch/MainPageLayout/data.lua
lua/wikis/pubg/MainPageLayout/data.lua
lua/wikis/pubgmobile/MainPageLayout/data.lua
lua/wikis/rainbowsix/MainPageLayout/data.lua
lua/wikis/starcraft2/MainPageLayout/data.lua
lua/wikis/tft/MainPageLayout/data.lua
lua/wikis/wildcard/MainPageLayout/data.lua
lua/wikis/worldoftanks/MainPageLayout/data.lua

This PR converts `Liquipedia:Want to help` transclusion to a widget.
dev in LoL / OW

refactor(mainpage): want to help panel to widget

---

lua/wikis/artifact/Info.lua
lua/wikis/battalion/Info.lua
lua/wikis/clashroyale/Info.lua
lua/wikis/runeterra/Info.lua
lua/wikis/squadrons/Info.lua

Wikis have been converted/ or have legacy mapping

chore(Info): Update match2 status on some wikis

---

lua/wikis/commons/MvpTable.lua

report on Discord: https://discord.com/channels/93055209017729024/276340346831765504/1370835531633787041
preview with dev

fix(mvpTable): team displays ignore htts

---

lua/wikis/valorant/MatchGroup/Input/Custom.lua

Follow up on #5930, it was requested to have this added also

feat(match2): add publisher-region to valorant lpdb

---

lua/wikis/valorant/MatchGroup/Input/Custom.lua
lua/wikis/valorant/MatchGroup/Input/Custom/MatchPage.lua
lua/wikis/valorant/MatchGroup/Input/Custom/Normal.lua

This PR adds `getPatch()` implementation for Valorant MatchPage map parser.
dev

feat(match2): read patch information from Valorant API

---

lua/wikis/commons/Widget/GeneralCollapsible/Default.lua
lua/wikis/commons/Widget/GeneralCollapsible/Toggle.lua
lua/wikis/commons/Widget/NavBox.lua
lua/wikis/commons/Widget/NavBox/Child.lua
lua/wikis/commons/Widget/NavBox/EditButton.lua
lua/wikis/commons/Widget/NavBox/List.lua

- are we okay with kicking the edit/view button at the top left?
- are we okay with the changed collapse behaviour for now? --> ask in editor-announcements if we like it
- i know we said we wanted to do it by cookie, just thinking of this as a temp solution until then (don't have the passion to write that atm)
search string for finding navbox usages: `insource:/[{:]navbox[\s\|]/i` (~2k), `module: insource:"Navbox"` (~70)
Implements Navbox as Widget
The Html result is similar to the result of the old novbox.
Removing some reduncancies (e.g. hlist div applied twice, atc pp)
Has changed collapse behaviour:
- removed collapse option at lower levels
- top level is always collapsible
- top level is auto collapsed if at the top of a page and uncollapsed at the bottom (via some heuristic) …

feat: Implement Navbox

---

lua/wikis/rocketleague/MatchSummary.lua
lua/wikis/sideswipe/MatchSummary.lua

fix(match2): team names in rocketleague match summary

---

lua/wikis/geoguessr/MainPageLayout/data.lua

https://discord.com/channels/93055209017729024/1270721461988102246/1375106723462909992

feat(mainpage): update navigation card images for geoguessr

---

lua/wikis/ageofempires/Infobox/Map/Custom.lua
lua/wikis/apexlegends/Infobox/Map/Custom.lua
lua/wikis/brawlstars/Infobox/Map/Custom.lua
lua/wikis/callofduty/Infobox/Map/Custom.lua
lua/wikis/commons/Infobox/Map.lua
lua/wikis/commons/Map.lua
lua/wikis/formula1/Infobox/Map/Custom.lua
lua/wikis/halo/Infobox/Map/Custom.lua
lua/wikis/overwatch/Infobox/Map/Custom.lua
lua/wikis/pubg/Infobox/Map/Custom.lua
lua/wikis/pubgmobile/Infobox/Map/Custom.lua
lua/wikis/rocketleague/Infobox/Map/Custom.lua
lua/wikis/starcraft/Infobox/Map/Custom.lua
lua/wikis/starcraft2/Infobox/Map/Custom.lua
lua/wikis/stormgate/Infobox/Map/Custom.lua
lua/wikis/valorant/Infobox/Map/Custom.lua
lua/wikis/warcraft/Infobox/Map/Custom.lua
lua/wikis/warthunder/Infobox/Map/Custom.lua
lua/wikis/worldoftanks/Infobox/Map/Custom.lua

This PR adds `StandardMap` and methods to fetch it from LPDB.
Context: https://github.com/Liquipedia/Lua-Modules/pull/5937#discussion_r2092538811
dev

feat: setup map model and data fetching

---

lua/wikis/commons/MatchPage/Base.lua
lua/wikis/commons/Widget/Match/Page/MapVeto.lua

see https://github.com/Liquipedia/Lua-Modules/pull/5898#discussion_r2072287100 for previous discussion
dev

feat(match2): use map information from LPDB for match page mapveto

---

lua/wikis/commons/Widget/MainPage/WantToHelp.lua

remove the check for the existence of the page that gets linked (as it exists on all wikis)
dev

chore: simplify WantToHelp widget a bit

---

lua/wikis/valorant/GetMatchGroupCopyPaste/wiki.lua

This PR adds match page copy-paste generator for Valorant.
- <https://liquipedia.net/valorant/Special:RunQuery/BracketCopyPaste/dev>
- <https://liquipedia.net/valorant/Special:RunQuery/MatchListCopyPaste/dev>
- <https://liquipedia.net/valorant/Special:RunQuery/MatchPageCopyPaste/dev>

feat(match2): match page copy-paste generator for valorant

---

lua/wikis/commons/Widget/Standings/Ffa.lua

resolves #5983 
dev
https://liquipedia.net/callofduty/User:Hesketh2/TestStandings

feat: do not show placement change column if there is only 1 round

---

lua/wikis/rainbowsix/GetMatchGroupCopyPaste/wiki.lua

fix: typo in R6 copy paste generator

---

lua/wikis/commons/MatchGroup/ShortenBracket.lua

chore(match2): fix spelling in ShortenBracket._processMatches

---

lua/wikis/tetris/Info.lua

Add new Tetris game TGM4 to Module:Info. 
Game reference: https://tetris.wiki/Tetris_The_Grand_Master_4_Absolute_Eye
Logo image sourced from: https://thectwc.com/2025/05/02/tetris-the-grand-master-4-absolute-eye-world-tournament/
There was a tournament for this new game at CTWC: https://liquipedia.net/tetris/CTWC/2025/TGM4_Tournament
Infobox and team cards (to show game logo): https://liquipedia.net/tetris/User:Mitsu_at/Sandbox/TGM4

feat: Add TGM4 game to Tetris wiki

---

README.md

docs: update readme regarding magic comment

---

lua/wikis/commons/MatchPage/Base.lua
lua/wikis/commons/Opponent.lua
lua/wikis/commons/Opponent/Starcraft.lua
lua/wikis/commons/Player/Ext.lua
lua/wikis/commons/TeamTemplate.lua
lua/wikis/commons/Widget/Match/Page/TeamDisplay.lua
lua/wikis/commons/Widget/TeamDisplay/Inline.lua
lua/wikis/rocketleague/Player/Ext/Custom.lua
lua/wikis/stormgate/Opponent/Custom.lua
lua/wikis/warcraft/Opponent/Custom.lua

likely regression of #5998
reported on discord: https://discord.com/channels/93055209017729024/268719633366777856/1382718415218806864
dev

fix: team templates with underscores causing lots of errors

---

lua/wikis/marvelrivals/NotabilityChecker/config.lua

as title states
requested on discord: https://discord.com/channels/93055209017729024/268719633366777856/1383929081485201438
N/A, just number change

feat(notability): adjust borders on marvelrivals

---

lua/wikis/freefire/Infobox/Character/Custom.lua

Standardize the freefire character infobox
dev

feat(infobox): standardize freefire character infobox

---

lua/wikis/commons/MatchGroup/Input/Util.lua
lua/wikis/commons/MatchGroup/Util.lua
lua/wikis/valorant/MatchGroup/Input/Custom.lua
lua/wikis/valorant/MatchPage.lua

feat(match2): automated patch display for Valorant match page

---

lua/wikis/commons/Widget/NavBox/Transfer.lua

as title says, regression of #6036
dev into live

fix(NavBox): missing nil catch in transfer navbox

---

lua/wikis/commons/Widget/Infobox/All.lua
lua/wikis/commons/Widget/Infobox/Cell.lua
lua/wikis/commons/Widget/Infobox/Table.lua
lua/wikis/underlords/Infobox/Character/Custom.lua

Migrate the character infobox on underlords. Created a new infobox widget, table, seen it a few times and might be used or could be used frequently in the future.
Tested visual and also did database E2E test with a consumer of the data

feat(infobox): character infobox for Underlords

---

lua/wikis/teamfortress/Infobox/Character/Custom.lua

feat(infobox): character infobox for tf2

---

stylesheets/commons/HexagonPortraits.less

Update the css style of ther heroes selector on hots. In the future this needs to be refactoed to js instead, as this very heavy coupled between multiple places and not flexiable at all

feat: update roles on hots

---

lua/wikis/commons/Links.lua
lua/wikis/commons/Links/PriorityGroups.lua
stylesheets/commons/Icons.less

Adding commons link for blast.tv links primarily for match pages for RL, DOTA and CS2
RLCS major page

feat: add BLAST.tv to links

---

lua/wikis/smite/MainPageLayout/data.lua
stylesheets/commons/Banner.less

This PR adds new mainpage config for SMITE.
https://liquipedia.net/smite/User:Kanoodles/test

feat(mainpage): new smite main page

---

lua/wikis/commons/Lua.lua

chore: fix an anno in Module:Lua

---

lua/wikis/honorofkings/MainPageLayout/data.lua

Title, old link of Heroes was outdated link

feat(mainPage): Update link to Heroes Portal

---

lua/wikis/battlerite/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Setup a basic new main page for Battlerite
https://liquipedia.net/battlerite/User:Kanoodles

feat(mainpage): new Battlerite main page

---

lua/wikis/commons/Icon/Data.lua
lua/wikis/commons/Widget/Match/PageButton.lua

Initital tweak to match page button based on new designs
dev

feat: update the "go to match page" button

---

lua/wikis/commons/GameTable.lua
lua/wikis/commons/GameTable/Character.lua
lua/wikis/commons/MatchTable.lua
lua/wikis/valorant/GameTable/Character/Custom.lua

Add the match page button on recent match/games per product request. There will be tweaks to the design of the buttons in the future, they don't look optimal yet
dev

feat: add match page button to recent match/game tables

---

lua/wikis/dota2/MainPageLayout/data.lua
stylesheets/commons/RankingTable.less

This adds the new dota2 rankings to the main page and the esports hub
Tested in a dev setup

add dota2 rankings to main page

---

.eslintrc.json
javascript/commons/Bracket.js
javascript/commons/Collapse.js
javascript/commons/Commons_mainpage.js
javascript/commons/Commons_tools.js
javascript/commons/Countdown.js
javascript/commons/Crosstable.js
javascript/commons/Mainpage.js
javascript/commons/Miscellaneous.js
javascript/commons/Prizepooltable.js

This shortens various line lengths to avoid warnings in the CI, also removes some old code in the tracker
-

Shorten line lengths

---

lua/wikis/lab/Info.lua

Setting up the Info module for the Lab wiki:
Starting year is set to 1800 since the scope of the wiki coverage isn't tied to any game release and could feature sports.
Default logo is a generic shield
https://liquipedia.net/lab/Module:Info

feat: add Lab info

---

lua/wikis/rematch/MainPageLayout/data.lua
stylesheets/commons/Banner.less

New Mainpage design for new wiki **Rematch** I thought of just skip the hassle of setting up old main page and just do the new one right away
LIVE
https://liquipedia.net/rematch/Main_Page

feat(mainpage): rematch mainpage

---

lua/wikis/leagueoflegends/FilterButtons/Config.lua
lua/wikis/leagueoflegends/GetMatchGroupCopyPaste/wiki.lua
lua/wikis/leagueoflegends/HiddenDataBox/Custom.lua
lua/wikis/leagueoflegends/Infobox/Character/Custom.lua
lua/wikis/leagueoflegends/Infobox/League/Custom.lua
lua/wikis/leagueoflegends/Infobox/Patch/Custom.lua
lua/wikis/leagueoflegends/Infobox/Person/Player/Custom.lua
lua/wikis/leagueoflegends/Infobox/Team/Custom.lua
lua/wikis/leagueoflegends/Match/Legacy.lua
lua/wikis/leagueoflegends/MatchGroup/Input/Custom/MatchPage.lua
lua/wikis/leagueoflegends/MatchGroup/Legacy/Default.lua
lua/wikis/leagueoflegends/MatchMaps/Legacy.lua
lua/wikis/leagueoflegends/MatchPage.lua
lua/wikis/leagueoflegends/MatchSummary.lua
lua/wikis/leagueoflegends/PrizePool/Custom.lua
lua/wikis/leagueoflegends/PrizePool/Legacy/Custom.lua
lua/wikis/leagueoflegends/Widget/CharacterTable/Entry/Custom.lua

chore: use Lua.import in leagueoflegends

---

javascript/commons/Collapse.js
javascript/commons/Commons_tools.js
javascript/commons/Miscellaneous.js
javascript/commons/Selectall.js

Add some proper styling to some buttons

feat: improve some js buttons

---

javascript/commons/Collapse.js

"Navframe" collapse was targeting the wrong parent
live

fix: navframe collapse

---

lua/wikis/commons/Widget/NavBox/SeriesChildFromLpdb.lua

requested by nick on discord
dev

feat(navbox): allow to condition on default tiertype

---

lua/wikis/commons/MatchTable.lua

per title, SORT was used for display, and DISPLAY was used for sort
I did not

fix(MatchTable): Swap INVALID_TIER_SORT and _DISPLAY

---

lua/wikis/commons/Icon/Data.lua

To be used in https://liquipedia.net/commons/Template:Toggle_bracket_start

feat: add schedule & bracket icons

---

lua/wikis/pubg/FilterButtons/Config.lua
lua/wikis/pubg/GetMatchGroupCopyPaste/wiki.lua
lua/wikis/pubg/HiddenDataBox/Custom.lua
lua/wikis/pubg/Infobox/Company/Custom.lua
lua/wikis/pubg/Infobox/League/Custom.lua
lua/wikis/pubg/Infobox/Person/Player/Custom.lua
lua/wikis/pubg/Infobox/Weapon/Custom.lua
lua/wikis/pubg/Match/Legacy.lua
lua/wikis/pubg/MatchGroup/Input/Custom.lua
lua/wikis/pubg/PrizePool/Award/Custom.lua
lua/wikis/pubg/PrizePool/Custom.lua

chore: use Lua.import in pubg

---

lua/wikis/overwatch/GetMatchGroupCopyPaste/wiki.lua
lua/wikis/overwatch/HiddenDataBox/Custom.lua
lua/wikis/overwatch/HighlightConditions.lua
lua/wikis/overwatch/Infobox/Character/Custom.lua
lua/wikis/overwatch/Infobox/League/Custom.lua
lua/wikis/overwatch/Infobox/Team/Custom.lua
lua/wikis/overwatch/Match/Legacy.lua
lua/wikis/overwatch/MatchGroup/Input/Custom.lua
lua/wikis/overwatch/MatchGroup/Legacy/Default.lua
lua/wikis/overwatch/MatchSummary.lua
lua/wikis/overwatch/NotabilityChecker/config.lua
lua/wikis/overwatch/PrizePool/Custom.lua
lua/wikis/overwatch/Squad/Custom.lua

chore: use Lua.import in overwatch

---

lua/wikis/commons/MatchPage/Base.lua
lua/wikis/commons/Widget/Match/Page/MapVeto.lua
lua/wikis/commons/Widget/Match/Page/TeamDisplay.lua

This PR applies #5900 to match pages.
dev in LoL & Valorant

refactor(match2): use TeamIcon widget in match pages

---

lua/wikis/leagueoflegends/GetMatchGroupCopyPaste/wiki.lua

This PR (re-)adds `|vod=` param to LoL matchpage generator, along with some formatting changes.
dev

feat(match2): add vod param to leagueoflegends matchpage generator

---

lua/wikis/commons/Widget/Match/Page/TeamDisplay.lua

fix(match2): TBD opponent points to a link on match pages

---

lua/wikis/freefire/NotabilityChecker/config.lua

Part of my Main Wiki Cleanup 
The wiki has never moved on from the old non-git module from like couple years back, I decide to rework this by porting over PUBG MOBILE's setup first

feat(notability checker): Add Free Fire

---

lua/wikis/commons/Widget/Match/Summary/MapVeto.lua

fix(match2): quick fix for map veto styling

---

stylesheets/commons/Brackets.less

feat(match2): make vod icons smaller

---

lua/wikis/ageofempires/ParticipantTable/Custom.lua

fix(ParticipantTable): Reduce button size on AoE seeding table

---

stylesheets/commons/Brackets.less

unused since a few refactors ago (of sc(2) ffa stuff)
N/A

chore: remove unused css class

---

stylesheets/commons/Brackets.less

(temporary) decreasing the width to try it out. We'll adjust next week more likely
devtools

feat(match2): decrease gap between body elements

---

lua/wikis/paladins/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Setting up the Paladins matchpage.
https://liquipedia.net/paladins/User:Kanoodles/Test

feat(mainpage): new Paladins main page

---

lua/wikis/chess/MainPageLayout/data.lua

Applying #5911 to Chess main page
https://liquipedia.net/chess/User:Nikita_r28/mainpagetest

refactor(mainpage) use WantToHelp widget on chess

---

lua/wikis/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Adding Battalion mainpage
https://liquipedia.net/battalion/User:Kanoodles

feat(mainpage): Add Battalion Main Page

---

stylesheets/commons/Match.less

Make the stream button grow when there's a CTA Text. Also fixes some edge cases in scenarios
devtools

feat: grow stream buttons when there's text in them

---

lua/spec/vod_link_spec.lua
lua/wikis/commons/VodLink.lua
stylesheets/commons/Miscellaneous.less

Fresh crisp vod icon off the factory floor
devtools + unit tests

feat: new vod icons

---

lua/wikis/clashroyale/MainPageLayout/data.lua
stylesheets/commons/Banner.less

New Main Page for Clash Royale
https://liquipedia.net/clashroyale/User:Hesketh2/Test
I really wish there's the .svg version of the Clash Royale logo with text, but there isnt any so I'm settled with a large PNG instead.

feat(Mainpage): Add Clash Royale

---

lua/wikis/sideswipe/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Creating sideswipe main page
https://liquipedia.net/sideswipe/User:Kanoodles

feat(mainpage): Add Sideswipe Main Page

---

lua/wikis/autochess/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Adding Auto Chess Mainpage
https://liquipedia.net/autochess/User:Kanoodles

feat(mainpage): Add Auto Chess Main Page

---

lua/wikis/underlords/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Many Main page such wow
https://liquipedia.net/underlords/User:Kanoodles

feat(mainpage): Add Underlords Main Page

---

lua/wikis/ageofempires/NotabilityChecker/config.lua
lua/wikis/apexlegends/NotabilityChecker/config.lua
lua/wikis/brawlstars/NotabilityChecker/config.lua
lua/wikis/callofduty/NotabilityChecker/config.lua
lua/wikis/clashofclans/NotabilityChecker/config.lua
lua/wikis/commons/NotabilityChecker.lua
lua/wikis/freefire/NotabilityChecker/config.lua
lua/wikis/geoguessr/NotabilityChecker/config.lua
lua/wikis/halo/NotabilityChecker/config.lua
lua/wikis/marvelrivals/NotabilityChecker/config.lua
lua/wikis/osu/NotabilityChecker/config.lua
lua/wikis/overwatch/NotabilityChecker/config.lua
lua/wikis/pubgmobile/NotabilityChecker/config.lua
lua/wikis/rainbowsix/NotabilityChecker/config.lua
lua/wikis/rocketleague/NotabilityChecker/config.lua
lua/wikis/trackmania/NotabilityChecker/config.lua

docs(notability): function type annotations

---

lua/wikis/splitgate/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Setting up splitgate mainpage
https://liquipedia.net/splitgate/User:Kanoodles

feat(mainpage): Add Splitgate Main Page

---

lua/wikis/warcraft/MainPageLayout/data.lua
stylesheets/commons/Banner.less

more mainpages, the end of the tunnel is approaching.
(Also they wanted the wider tournaments/matches list hence why those are adjusted)
https://liquipedia.net/warcraft/User:Kanoodles

feat(mainpage): Add Warcraft Main Page

---

lua/wikis/valorant/MainPageLayout/data.lua

see previous discussion [here](https://discord.com/channels/93055209017729024/684060921898860569/1397910218100314203)
dev

feat(mainpage): add thisday to valorant

---

lua/wikis/warcraft/MainPageLayout/data.lua

Communtiy request to relocate the first day to the left/above transfers

feat: re-order ThisDay in Warcraft mainpage

---

lua/wikis/stormgate/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Bit of a lack of pictures, so based most of SC2
https://liquipedia.net/stormgate/User:Kanoodles

feat(mainpage): Add Stormgate Main Page

---

lua/wikis/warthunder/MainPageLayout/data.lua
stylesheets/commons/Banner.less

No imagery in war thunder so just yoinking from WoT
https://liquipedia.net/warthunder/User:Kanoodles

feat(mainpage): Add War Thunder Main Page

---

lua/wikis/omegastrikers/MainPageLayout/data.lua
stylesheets/commons/Banner.less

MOAR mainpages
https://liquipedia.net/omegastrikers/User:Kanoodles/test

feat(mainpage): Add Omega Strikers Main Page

---

lua/wikis/commons/MatchTicker.lua

Apparently i failed to correctly copy from dev into the PR in #6197
live

fix(MatchTicker): Merge extradata into correct table

---

javascript/commons/FilterButtons.js
lua/wikis/commons/Icon/Data.lua
lua/wikis/commons/Widget/Match/ButtonBar.lua
lua/wikis/commons/Widget/Match/VodsDropdown.lua
stylesheets/commons/Match.less
stylesheets/commons/Miscellaneous.less

New handling for (game) VODs on the match ticker
dev

feat: redesign vod handling on the match ticker

---

lua/wikis/commons/Widget/Match/VodsDropdown.lua

2 functions are missing annos for their second param
VSC

fix: partially missing annos

---

javascript/commons/Slider.js
lua/wikis/commons/Widget/Basic/Slider.lua
stylesheets/commons/Slider.less

Add plus minus buttons also for easier navigation
dev wiki

feat: add +/- buttons to sliders

---

.github/workflows/delete dev env.yml
scripts/remove_dev.sh

Adds a github action that removes dev env (modules with /dev/something).
fork

ci: add action to remove a dev "env"

---

lua/wikis/fighters/Info.lua

Adding HUNTER×HUNTER NEN×IMPACT (HxHNI) to the fighters wiki. The game launched 2 weeks ago and will be featured in several upcoming majors, including EVO France.

Add HUNTER×HUNTER NEN×IMPACT to Fighters

---

lua/wikis/underlords/Infobox/Faction/Custom.lua

feat(infobox): standardize underlords' Alliance Infobox

---

lua/wikis/magic/Infobox/Unit/Custom.lua
lua/wikis/runeterra/Infobox/Unit/Custom.lua

feat(infobox): add magic and runeterra card infoboxes

---

lua/wikis/wildrift/Infobox/Item/Custom.lua
lua/wikis/wildrift/Infobox/Item/Rune/Custom.lua

feat(infobox): standardize wildrift's rune infobox

---

lua/wikis/commons/TournamentStructure.lua

fix: broken Opponent module import in TournamentStructure

---

lua/wikis/commons/Widget/Infobox/Venue.lua

happened due to a mistake in #6208
hotfix, live

fix(infobox): venue description causing error

---

lua/wikis/commons/TransferList.lua

Brain is in full vacation mode apparently.
Checking the transfer table we should now have every field that needs to be grouped on in here, except for potentially roleXsec; however these were also not checked on in the old version.
live

fix(TransferList): Add date to group conditions

---

lua/wikis/arenafps/InGameRoles.lua
lua/wikis/commons/Roles/ContractRoles.lua
lua/wikis/commons/Roles/StaffRoles.lua
lua/wikis/counterstrike/InGameRoles.lua
lua/wikis/dota2/InGameRoles.lua
lua/wikis/freefire/InGameRoles.lua
lua/wikis/honorofkings/InGameRoles.lua
lua/wikis/leagueoflegends/InGameRoles.lua
lua/wikis/marvelrivals/InGameRoles.lua
lua/wikis/mobilelegends/InGameRoles.lua
lua/wikis/omegastrikers/InGameRoles.lua
lua/wikis/osu/InGameRoles.lua
lua/wikis/overwatch/InGameRoles.lua
lua/wikis/pubg/InGameRoles.lua
lua/wikis/rainbowsix/InGameRoles.lua
lua/wikis/smite/InGameRoles.lua
lua/wikis/splatoon/InGameRoles.lua
lua/wikis/valorant/InGameRoles.lua
lua/wikis/wildrift/InGameRoles.lua
lua/wikis/worldoftanks/InGameRoles.lua
lua/wikis/worldofwarcraft/InGameRoles.lua
lua/wikis/zula/InGameRoles.lua

docs: fix type

---

lua/wikis/naraka/MainPageLayout/data.lua
stylesheets/commons/Banner.less

naraka mainpage addition
https://liquipedia.net/naraka/User:Kanoodles/test

feat(mainpage): Add Naraka Main Page

---

lua/wikis/commons/Widget/Infobox/Venue.lua

fix(infobox): venue desc using span instead of small

---

lua/wikis/illuvium/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Its existence pains me.
https://liquipedia.net/illuvium/User:Kanoodles

feat(mainpage): Add Illuvium Main Page

---

lua/wikis/commons/Standings/Parse/Wiki.lua
lua/wikis/commons/Standings/Table.lua

Add placement mappings to the new swiss standings, logic changed based on discussion (it's non-mandatory now, but expecting it to be frequently used)
dev

feat(standings): support swiss placement mappings

---

lua/wikis/criticalops/MainPageLayout/data.lua
stylesheets/commons/Banner.less

More mainpage
https://liquipedia.net/criticalops/User:Kanoodles

feat(mainpage): Add Critical Ops Main Page 

---

lua/wikis/starcraft/MainPageLayout/data.lua
stylesheets/commons/Banner.less

Another main page addition
https://liquipedia.net/starcraft/User:Kanoodles

feat(mainpage): Add StarCraft (1) Main Page

---

lua/wikis/splatoon/MainPageLayout/data.lua
stylesheets/commons/Banner.less

New mainpage for splatoon
https://liquipedia.net/splatoon/User:Kanoodles

feat(mainpage): Add Splatoon Main Page

---

lua/wikis/zula/MainPageLayout/data.lua

fix: Zula metadesc

---

lua/wikis/counterstrike/ResultsTable/Custom.lua

requested on discord: https://discord.com/channels/93055209017729024/372075546231832576/1404589770692366428
dev

feat(resultstable): enable type display in counterstrike

---

stylesheets/commons/Brackets.less

This PR adds round corners to MVP display in match summaries, making its style consistent with other match summary components.

feat(match2): add round corners to mvp display in match summaries

---

lua/wikis/trackmania/MainPageLayout/data.lua
stylesheets/commons/Banner.less

https://liquipedia.net/trackmania/User:SobakaPirat/Main_Page/new

feat(mainpage): Add Trackmania Main Page

---

lua/wikis/esports/MainPageLayout/data.lua
stylesheets/commons/Banner.less

https://liquipedia.net/esports/User:Kanoodles/test

feat(mainpage): Add Esports Main Page

---

lua/wikis/leagueoflegends/MatchPage.lua

The order that the players are listed in LoL conveys a meaning (which in-game role/position they play). This PR forces players to be sorted by their roles in match pages.
dev

feat(match2): always sort players by role in LoL match page

---

lua/wikis/geoguessr/GameSummary.lua
lua/wikis/geoguessr/MatchGroup/Input/Custom.lua
lua/wikis/geoguessr/MatchSummary/Ffa.lua

as per request on discord:
https://discord.com/channels/93055209017729024/268719633366777856/1404102955459940352
https://discord.com/channels/93055209017729024/268719633366777856/1404127936247762955
via dev by contributors

feat(match2): Ffa support

---

lua/wikis/ageofempires/MatchSummary.lua

fix: Catch nil in mapDisplayName on AoE

---

lua/wikis/commons/Timezone/Data.lua

Template:Abbr/WAT exists since july 2024 and is being used, add the timezone to the DB to not have it fail when using in countdown
live

chore: Add West Africa Time (WAT)

---

lua/wikis/clashroyale/MatchSummary.lua

fix: Remove colors in CR matchsummary

---

lua/wikis/commons/Opponent.lua

docs(opponent): fix spelling in documentation

---

lua/wikis/lab/Widget/ProjectOverview.lua

refactor: replace style attribute with css in project overview

---

lua/wikis/ageofempires/GetMatchGroupCopyPaste/wiki.lua

Requested by editors
i did not

chore: Add youtube param to AoE CopyPaste

---

lua/wikis/commons/Links.lua
lua/wikis/commons/Links/PriorityGroups.lua
stylesheets/commons/Icons.scss

Adds tetr.io icon to infobox.
Sample page:
- https://liquipedia.net/tetris/index.php?title=User:Mitsu_at/Sandbox/Infobox
Dev modules:
- https://liquipedia.net/commons/Module:Links/dev/mitsu_at
- https://liquipedia.net/commons/Module:Links/PriorityGroups/dev/mitsu_at
Uploaded icons (created using psd template from https://discord.com/channels/93055209017729024/235015279711748096/936641806538530878 https://drive.google.com/file/d/1-UiojLdekArpA_vZt6YPxnesKpbwB6mH/edit):
- https://liquipedia.net/commons/File:InfoboxIcon_TETRIO.png
I am unable to test if the icon works correctly because I think that requires CSS changes.

feat: add links data for tetr.io

---

lua/wikis/warcraft/Infobox/League/Custom.lua

requested on discord: https://discord.com/channels/93055209017729024/268719633366777856/1410909553104523365
dev

feat(infobox): return empty game for misisng date on wc3

---

lua/wikis/commons/Widget/Standings/Swiss.lua

point 3 of https://discord.com/channels/93055209017729024/1407714004767473685/1407719773843755138
dev

feat(standings): only display title if it is not empty

---

lua/wikis/ageofempires/Infobox/Team/Custom.lua
lua/wikis/brawlstars/Infobox/Person/Player/Custom.lua
lua/wikis/commons/Count.lua
lua/wikis/commons/Earnings/Base.lua
lua/wikis/commons/InfoboxPlacementStats.lua
lua/wikis/commons/MatchGroup/Display/Helper.lua
lua/wikis/commons/MatchTable.lua
lua/wikis/commons/MatchTicker.lua
lua/wikis/commons/ResultsTable/Base.lua
lua/wikis/commons/TeamLogoGallery.lua
lua/wikis/commons/Transfer/Model.lua
lua/wikis/commons/TransferList.lua
lua/wikis/leagueoflegends/Infobox/Person/Player/Custom.lua
lua/wikis/marvelrivals/Infobox/Person/Player/Custom.lua
lua/wikis/naraka/Infobox/Person/Player/Custom.lua
lua/wikis/overwatch/Infobox/Person/Player/Custom.lua
lua/wikis/rainbowsix/Infobox/Person/Player/Custom.lua
lua/wikis/smash/PortalPlayers/Custom.lua
lua/wikis/valorant/Infobox/Person/Player/Custom.lua
lua/wikis/wildrift/Infobox/Person/Player/Custom.lua

resolves #5639
partially on dev

refactor: replace uses of Module:Team

---

lua/wikis/commons/MatchPage/Base.lua

This PR replaces uses of `Module:VodLink` with the newly added `VodButton` widgets.
dev in LoL

feat(match2): use new VodButton in match pages

---

lua/wikis/commons/TransferList.lua

report on discord: https://discord.com/channels/93055209017729024/268719633366777856/1413536820020515008
regression from #6502
dev

fix(transfer): transfer list not reading wiki config properly

---

lua/wikis/starcraft2/Infobox/Person/MapMaker/Custom.lua
lua/wikis/starcraft2/Infobox/Person/Player/Custom.lua

as per feedback on discord (via some asocial media stuff)
dev

feat(infobox) Suppress unknown faction display in person infoboxes

---

lua/wikis/apexlegends/Infobox/Team/Custom.lua
lua/wikis/brawlstars/Infobox/Person/Player/Custom.lua
lua/wikis/commons/Infobox/Extension/UpcomingTournaments.lua
lua/wikis/commons/Widget/Infobox/UpcomingTournaments.lua
lua/wikis/counterstrike/Infobox/Team/Custom.lua
lua/wikis/dota2/Infobox/Person/Player/Custom.lua
lua/wikis/dota2/Infobox/Team/Custom.lua
lua/wikis/freefire/Infobox/Team/Custom.lua
lua/wikis/honorofkings/Infobox/Team/Custom.lua
lua/wikis/leagueoflegends/Infobox/Person/Player/Custom.lua
lua/wikis/leagueoflegends/Infobox/Team/Custom.lua
lua/wikis/marvelrivals/Infobox/Person/Player/Custom.lua
lua/wikis/naraka/Infobox/Person/Player/Custom.lua
lua/wikis/overwatch/Infobox/Person/Player/Custom.lua
lua/wikis/overwatch/Infobox/Team/Custom.lua
lua/wikis/pubg/Infobox/Person/Player/Custom.lua
lua/wikis/pubgmobile/Infobox/Person/Player/Custom.lua
lua/wikis/pubgmobile/Infobox/Team/Custom.lua
lua/wikis/rainbowsix/Infobox/Person/Player/Custom.lua
lua/wikis/valorant/Infobox/Person/Player/Custom.lua
lua/wikis/valorant/Infobox/Team/Custom.lua
lua/wikis/wildrift/Infobox/Person/Player/Custom.lua
lua/wikis/wildrift/Infobox/Team/Custom.lua

This PR applies #5901 to all remaining wikis
dev in LoL

feat(infobox): use upcoming and ongoing tournaments widget in all wikis

---

lua/wikis/marvelrivals/Infobox/Person/Player/Custom.lua

regression of #6511
live as hot fix

fix(infobox): wrong import for html widgets on marvelrivals

---

lua/wikis/commons/Widget/Match/Summary/MapVetoRound.lua
stylesheets/commons/Brackets.scss

There's issues with new map veto table.
dev

fix(match2): map veto styling fixes

---

lua/wikis/mobilelegends/MainPageLayout/data.lua

Editor request: MLBB switched to monthly transfers from quarterly: https://discord.com/channels/93055209017729024/1209065403955806270/1414981047149658154
https://liquipedia.net/mobilelegends/Module:MainPageLayout/data/dev/centaur
https://liquipedia.net/mobilelegends/User:Centaur98/test

feat(mainPage): Switch to monthly transfers for MLBB

---

lua/wikis/commons/MvpTable.lua

Regression from #6474
Original report: https://discord.com/channels/93055209017729024/268719633366777856/1415022364156231813
dev

fix(mvpTable): parsed args not used for display

---

lua/wikis/commons/PortalStatistics.lua

Since some entrypoints do need a limit that is respected, pass it to executeMassQuery
live

fix: Missing limit parameter for executeMassQuery

---

lua/wikis/dota2/Infobox/Cosmetic/Custom.lua

chore: use https in dota2 cosmetics infobox

---

lua/wikis/commons/Infobox/Extension/TeamHistory/Auto.lua

basically a side effect of #5854
dev
after merge needs purge run on transfers and after that on player pages on sc2

fix: THA not finding data for player with underscores on sc2

---

lua/wikis/commons/MatchPage/Base.lua

Previous discussion: https://discord.com/channels/93055209017729024/1356577556567953550/1417035583326261359
This PR ports #6503 to match pages.
dev

feat(match2): update vod button behavior in match pages

---

lua/wikis/fighters/MainPageLayout/data.lua
stylesheets/commons/Banner.scss

Adding the new mainpage to fighters;
They'll still use thier current tournament list setup which is manual. (THis is due to their overarching events pages per game)
https://liquipedia.net/fighters/User:Kanoodles

feat(mainpage): Add Fighters Main Page

---

lua/wikis/commons/Widget/Infobox/TeamHistory/Display.lua

requersted on discord:
https://discord.com/channels/93055209017729024/268719633366777856/1421776591788183644
dev

feat(infobox): do not display POS icon on special roles

---

lua/wikis/leagueoflegends/MainPageLayout/data.lua

feat(mainpage): update photos for champions and patches navigation cards

---

lua/wikis/commons/Widget/Standings.lua
lua/wikis/commons/Widget/Standings/Ffa.lua
lua/wikis/commons/Widget/Standings/MatchOverview.lua
lua/wikis/commons/Widget/Standings/PlacementChange.lua
lua/wikis/commons/Widget/Standings/RoundSelector.lua
lua/wikis/commons/Widget/Standings/Swiss.lua

docs(standings): fix standings widget type annotations not being picked up

---

lua/wikis/commons/MatchPage/Base.lua
lua/wikis/leagueoflegends/MatchPage.lua
lua/wikis/valorant/MatchPage.lua

refactor(match2): add tournament icon getter to base matchpage

---

.gitattributes

as per today's module sync meeting...
N/A

chore: force LF line endings for Lua files

---

lua/wikis/commons/Widget/Infobox/TeamHistory/Display.lua

i think we fixed that before and it got re added in a bad rebase
dev

fix: loans erroring for TH/THA

---

lua/wikis/esports/MatchGroup/Input/Custom.lua
lua/wikis/esports/MatchSummary.lua

These files were added to the esports wiki back in March for [LULS 2025](https://liquipedia.net/esports/Liquipedia_Ultimate_Logo_Series/2025) but not to this repository...
"live"

feat(match2): esports wiki implementation
