components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
Currently in submatches the score 0 is always show even if no player nor winner data in the maps of the submatch was entered.
This PR changes that behaviour and only displays the submatch scores if
- resultType is not `default`
- at least one of the scores is non 0
- at least one of the submatch opponents has player data entered
dev
before:
with pr:
=> feat(match2): improve score display on sc(2) submatches

components/match2/commons/match_group_input.lua
- some wikis use `pX` as displayName with `pXlink` being the link overwrite
- some wikis use `pX` as the link with `pXdn` being the displayName overwrite
This PR makes it so that
- the displayName is actually read
- the above mentioned cases are both covered
dev to live
=> feat(match2): improve name and displayName processing

components/match2/commons/match_group_input.lua
Edge case (reported on sc2):
- one opponent has known score and the score (numeric) is entered
- one opponent has unknown score and `L` is entered as the score
Currently in this edge case the winner is determined as -1, even if manual winner input is entered.
This PR adjusts it so that if (numeric) manual winner input is evaluated before trying to determine a winner based on scores (be it as draw, via `getDefaultWinner` or `getHighestScoringOpponent`).
dev
=> fix(match2): manual winner for partial unknown score overwritten with `-1`

components/match2/commons/match_group_input.lua
Temporary fix needed for Match1 Legacy input, as sometimes we get empty-string-scores from it, which are causing havoc.
Live for a couple of days
=> feat(match2): ignore empty string scores

components/match2/wikis/valorant/match_summary.lua
Currently in case of a walkover game/map in the matchsummary `-1` is displayed.
This PR make sit so that the walkover information is displayed instead.
dev
=> feat(match2): map score display for walkovers on VAL

components/participant_table/wikis/warcraft/participant_table_custom.lua
requested by stowka
in case in a faction column that is not shown by default only dq'd players are listed it currently does not display that column
this pr makes it so that it shows in that case too
dev
=> feat(participantsTable): display columns if only dq opponents are in them

components/opponent/commons/opponent.lua, spec/opponent_spec.lua
Currently `toName` just concats the player page names in the same order as they are supplied.
To be able to easier find matches, ... for duo/trio/quad opponents this PR adjusts `toName` so that the player pagenames are sorted before concating them.
Due to that the order of input is not relevant anymore and `{{DuoOpponent|p1=Player B|p2=Player A}}` will get the same opponent name as `{{DuoOpponent|p1=Player A|p2=Player B}}`
dev
=> feat(opponent): sort playerNames in `toName`

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
in team matches
when faction is not specified in the map data for a player it should fall back the data of that player available in match2players
currently that doesn't happen
this pr fixes that
not tested but a simple change
=> fix(match2): on sc(2), faction fallback in participants data is missing

components/match2/commons/match_group_input.lua, components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua, components/match2/wikis/arenaofvalor/match_group_input_custom.lua, components/match2/wikis/brawlstars/match_group_input_custom.lua, components/match2/wikis/callofduty/match_group_input_custom.lua, components/match2/wikis/dota2/match_group_input_custom.lua, components/match2/wikis/heroes/match_group_input_custom.lua, components/match2/wikis/leagueoflegends/match_group_input_custom.lua, components/match2/wikis/overwatch/match_group_input_custom.lua, components/match2/wikis/rainbowsix/match_group_input_custom.lua, components/match2/wikis/rocketleague/match_group_input_custom.lua, components/match2/wikis/valorant/match_group_input_custom.lua, components/match2/wikis/wildrift/match_group_input_custom.lua
Step 2 is #4600
current behaviour:
- if `finished=np/skip/...` --> match is not assumed as finished and resulttype is not set properly
- if `winner=np/skip/...` --> match is assumed finished but errors on `setPlacement` because it expects a valid winner input
this PR makes it so that on `np/skip/...` input in either winner or finished **the match is assumed to _not_ be finished**
this results in the error not being able to occour
due to `np/skip` now setting the match as not finished the `resulttype` processing for these cases has to be caught too
additionally this PR fixes a few missing annos
dev
=> fix(match2): not played input handling - step 1

standard/error_display.lua, standard/lua.lua
Align it better with other error displays
=> refactor(standard): Have ClassicError return html instead of string

components/match2/wikis/valorant/legacy/match_group_legacy_default.lua, components/match2/wikis/valorant/legacy/match_maps_legacy.lua
=> fix(match2): Don't fill score when empty in legacy maps on valorant

components/opponent/commons/starcraft_starcraft2/player_ext_starcraft.lua
resolves #1160 (except for gtl/stl which imo is out of scope for this issue/PR)
Add `StarcraftPlayerExt.TemplateStorePlayerLink` function to be able to adjust
- https://liquipedia.net/starcraft/Template:StorePlayerLink
- https://liquipedia.net/starcraft2/Template:StorePlayerLink
and hence be able to kick
- https://liquipedia.net/commons/Module:Player/Ext/downstream
- https://liquipedia.net/commons/Module:Player/Display/downstream
- https://liquipedia.net/commons/Module:Player/Ext/Starcraft/downstream
- https://liquipedia.net/commons/Module:Player/Display/Starcraft/downstream
- https://liquipedia.net/commons/Module:TeamTemplate/Named
dev
=> feat(opponnet): add `StarcraftPlayerExt.TemplateStorePlayerLink`

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft_deprecated.lua
forgot to remove the last usage of `Module:TeamTemplate/Named` in the deprecated match2 input processing for sc(2)
(only used for the ffa shit)
live
=> fix(match2): forgot to remove last usage of `Module:TeamTemplate/Named`

components/opponent/commons/player_display.lua, stylesheets/commons/Brackets.less
=> fix(opponent): long player names with notes do not ellipsis

components/infobox/wikis/deadlock/infobox_character_custom.lua
Some heroes (i.e. `mo & krill`, `abrams`, `pocket`, `shiv`, `yamato`) using shotguns, so their in-game dps dosen't apply foluma.
*mo & krill have 76dps, but calculation result are ~20 dps*
So we decided to allowed contributer manually input `|dps=` parm, if they haven't input anything ,then still using calculation result.
[Discord discussion context](https://discord.com/channels/93055209017729024/1278051336889438218/1278276460980736083)
-->
We adding an dev version of influenced module , [links](https://liquipedia.net/deadlock/Module:Infobox/Character/Custom/dev)
Then test this module in a hero page , [changes](https://liquipedia.net/deadlock/index.php?title=Mo_%26_Krill&type=revision&diff=630&oldid=628)
=> feat(infobox): allowed manually input `dps` param on `deadlock` wiki

components/match2/wikis/dota2/match_page_template.lua, stylesheets/commons/BigMatch.less
In this PR:
- item images are wrapped in a div to fix the ratio
- add opacity to backpack items.
- fix layout shift of the two player performance columns
- fix loadout display on specific screen sizes
- fix hero image ratio
- update to new SAP logo
Live wiki https://liquipedia.net/dota2/Match:ID_PDc51bykFj_R04-M002
=> fix(match2): dota2 matchpage various minor styling fixes

components/match2/wikis/deadlock/get_match_group_copy_paste_wiki.lua, components/match2/wikis/deadlock/match_group_input_custom.lua, components/match2/wikis/deadlock/match_summary.lua, standard/info/wikis/deadlock/info.lua
=> feat(match2): deadlock setup

stylesheets/commons/PanelBox/Heroes.less
This PR fixes the visited link color.
Live wiki
=> fix: dota heroes panel visited color text

stylesheets/commons/Fountain.less
Colors the attribute section according to the hero's primary attribute using predefined colors.
=> feat: applying bg color for Primary Attribute (Hero infobox)

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua, components/match2/wikis/arenaofvalor/match_group_input_custom.lua, components/match2/wikis/brawlstars/match_group_input_custom.lua, components/match2/wikis/callofduty/match_group_input_custom.lua, components/match2/wikis/deadlock/match_group_input_custom.lua, components/match2/wikis/dota2/match_group_input_custom.lua, components/match2/wikis/heroes/match_group_input_custom.lua, components/match2/wikis/leagueoflegends/match_group_input_custom.lua, components/match2/wikis/overwatch/match_group_input_custom.lua, components/match2/wikis/rainbowsix/match_group_input_custom.lua, components/match2/wikis/rocketleague/match_group_input_custom.lua, components/match2/wikis/valorant/match_group_input_custom.lua, components/match2/wikis/wildrift/match_group_input_custom.lua
Currently in the customs `MatchFunctions.getExtraData` is called before opponents are available in the match table.
This leads to `MatchGroupInputUtil.readMvp` (called from `getExtraData` on quite a few wikis) not being able to access the opponents (notably not match2players inside the opponents) and hence mvp data not being filled in correctly.
This PR moves the `getExtraData` to after attaching the opponents to the match table to solve that issue.
dev on lol, rst untested
=> fix(match2): extradata processing has no access to opponents

stylesheets/commons/Brackets.less
i think it resolves /skins/lakesideview#121
add darkmode support for classes used in r6 matchsummary
before:
after:
=> feat(match2): add darkmode support for r6 matchsummary

components/match2/commons/match_summary_ffa.lua
a missing `#` from ~3 years ago ...
live
personally i consider the module deprecated
=> fix(match2): missing `#`

components/match_ticker/commons/match_ticker.lua
Nick flagged this bug:
"(I added CCT tiertype Monthly) the tiertype 'overwrites' the non-tiertype, not sure if this is intended, just that previously it shows non-tiertype and tiertype (the filter for tournaments);  when all kinds of tier is checked except tier 4, it seems normal, when tier 4 is checked, it just shows tiertype"
This is due to tiertype filter not taking into account matches without tiertypes. To solve this, we added the condition that empty tiertypes are added into the list when triggering any filter
With a [dev page](https://liquipedia.net/dota2/Template:NewDota2MainPage_matches/dev)
=> fix(MatchTicker): empty tiertype match alway disappears when using tiertype filters

stylesheets/commons/Fountain.less
- I missed `--` for #4671 the `var(--color)`.
- Adding secondary attributes img properties as well, this will help the icons pop-up better with the colored bg.
Apologies for the second merge request. Thank you!
=> feat(fountain): Missing the two hyphens for the predefined colors.

components/broadcaster_card/commons/broadcaster_card.lua, components/faction/wikis/ageofempires/faction_data.lua, components/faction/wikis/ageofempires/faction_icon_data.lua, components/infobox/extensions/commons/infobox_placement_stats.lua, components/infobox/wikis/stormgate/infobox_building_custom.lua, components/infobox/wikis/stormgate/infobox_map_custom.lua, components/infobox/wikis/stormgate/infobox_unit_custom.lua, components/infobox/wikis/warcraft/infobox_league_custom.lua, components/match2/commons/match_group.lua, components/match2/commons/match_group_display_helper.lua, components/match2/commons/match_group_input_util.lua, components/match2/commons/match_group_legacy.lua, components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua, components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua, components/match2/wikis/dota2/match_page_template.lua, components/match2/wikis/easportsfc/match_group_input_custom.lua, components/match2/wikis/heroes/match_summary.lua, components/match2/wikis/rainbowsix/get_match_group_copy_paste_wiki.lua, components/match2/wikis/stormgate/match_group_util_custom.lua, components/match2/wikis/warcraft/match_group_util_custom.lua, components/participant_table/commons/participant_table_import.lua, components/ratings/ratings_display_graph.lua, components/squad/commons/squad_utils.lua, components/statistics/portal_statistics.lua, definitions/mw.lua, plugins/sumneko_plugin.lua, standard/error_display.lua
searched for double space in vscode (`  `) and replaced most of them with single space or tabs
N/A
=> chore: space cleanup

components/infobox/wikis/counterstrike/infobox_league_custom.lua
New valve tiers going forward for 2025 (and onward).
Just data, pushed live already as need to be used.
=> feat(infobox): add new CS 2025 valve tiers

components/opponent/commons/opponent.lua, components/opponent/commons/starcraft_starcraft2/opponent_starcraft.lua, components/opponent/wikis/stormgate/opponent_custom.lua, components/opponent/wikis/warcraft/opponent_custom.lua
In `Module:Opponent` the option key is `overwriteVars` while in Player/ext it is `overwritePageVars`.
And on WC/SG the option param was passed to the wrong function
live
=> fix(opponent): wrong var name & passed to wrong function

components/opponent/commons/starcraft_starcraft2/player_display_starcraft.lua
the old version did not parse `|link=false` properly, this PR fixes that
additionally it does a nil catch for missing `args[1]`
live
=> fix(opponent): fix `TemplatePlayer`

components/infobox/wikis/osu/infobox_person_player_custom.lua
Some notable players are both players, talents and staffs, so we adding "players" as optional choose in `|role=`.
we also add support for `|role3=` in rare case people both have achievement in players, talents or staffs. 
the above solution was [discussed](https://discord.com/channels/93055209017729024/1164213669324927096/1277272216131735664) in dc with other majorly contributer: 
By Made an dev version of this [module](https://liquipedia.net/osu/Module:Infobox/Person/Player/Custom/dev) then test in a page using preview in both [sandbox page](https://liquipedia.net/osu/User:RushFTK/Module_Sandbox) and [real page](https://liquipedia.net/osu/ChillierPear)
After future discussed, we decided not implement `|role=3` unless we really need add player who really notable at all three ascpect. …
=> feat(infobox): allow `player` as role on osu

stylesheets/commons/Fountain.less
Add darkmode support for `.gvt-el-significant` in fountain.less
=> feat(styles): darkmode support for `.gvt-el-significant`

definitions/mw.lua
`mw.text.split` allows numeric input, state so in the annotation
N/A
=> docs: mw.text.split allows numeric input

stylesheets/commons/SwitchButtons.less
Based on design feedback, the background color of the slider has been changed to a darker state to not look like it is disabled.
How it will look like:
Console on this page](https://liquipedia.net/dota2/Main_Page)
=> feat(matchticker): update toggle slider disabled background color

components/infobox/commons/infobox_widget_all.lua, components/infobox/commons/infobox_widget_factory.lua, components/infobox/wikis/brawlhalla/infobox_person_player_custom.lua, components/widget/widget.lua, components/widget/widget_breakdown.lua, components/widget/widget_builder.lua, components/widget/widget_cell.lua, components/widget/widget_center.lua, components/widget/widget_chronology.lua, components/widget/widget_customizable.lua, components/widget/widget_header.lua, components/widget/widget_highlights.lua, components/widget/widget_links.lua, components/widget/widget_table.lua, components/widget/widget_table_cell.lua, components/widget/widget_table_cell_new.lua, components/widget/widget_table_new.lua, components/widget/widget_table_row.lua, components/widget/widget_table_row_new.lua, components/widget/widget_title.lua
Move all Widgets except `/All`, `/Factory` and `/Injector` from Infobox/Widget to Widget. Those 3 will be done in other PRs due to being directly imported instead of going via /All.
=> refactor(widget): move most widgets from `Infobox/Widget` to `Widget`

.github/workflows/deploy test.yml
Currently the CI  will only take the last commit of the branch. Now it should take all diffs compared to main. However it's important to rebase/merge with main before deploying! (otherwise extra files will be deployed)
Tested in #4633 (https://github.com/Liquipedia/Lua-Modules/actions/runs/10735333412), with some minor tweaks afterwards
=> ci: deploy the entire branch instead of just last commit

components/match2/commons/match_group_display_helper.lua
Currently `opponentIsHighlightable` fails on sc2 for empty party opponents due to the filled in default faction.
After thinking about removing defaultFaction in empty player cases it was noticed that for an party opponent with filled in flag/faction it would still cause the same issue again.
Hence adjust the commons check a bit so it also checks on the displayName not being empty instead.
Additionally move away from checking against not being empty string and use `Logic.isNotEmpty` instead.
dev
=> fix(match2): `opponentIsHighlightable` sometimes being wrong on sc(2)/wc/sg

components/match2/wikis/valorant/get_match_group_copy_paste_wiki.lua
As per request by GodOfPog add `|matchsection` param to first match (if enabled) via a 1 line chnage in the wiki specific part of the copy paste generator modules
dev
the below linked change should be done to all the copy paste forms on the wiki
https://liquipedia.net/valorant/index.php?title=Form%3ABracketCopyPaste%2Fdev&type=revision&diff=987520&oldid=987517
- https://liquipedia.net/valorant/Form:BracketCopyPaste
- https://liquipedia.net/valorant/Form:MatchListCopyPaste
- (they apparently do not have a form for single match)
=> feat(match2): add matchsection param on valorant copy paste

components/match2/wikis/dota2/match_group_input_custom_match_page.lua, components/match2/wikis/dota2/match_page.lua, components/match2/wikis/dota2/match_page_template.lua
Player Names from the API are sometimes a bit garbage.
Use the player.id to lookup the actual player data and fetch the link/name from that.
Use the old names as fallback incase that of no return from lpdb.
/dev/rath
=> feat(match2): fetch name and link from LPDB on dota2 matchpages

components/match2/wikis/dota2/match_legacy.lua
In certain situations, game2.extradata can be nil
Live
=> fix(match2): error on missing game.extradata on dota2

components/match2/wikis/dota2/match_group_input_custom.lua
Currently a matchpage dota2 game will have publisherid as type `number` while a non-matchpage one will have it as a `string`.
Since the dota2 pubid will always be a number, we now want to force it to a number always.
=> fix(match2): type of dota2 publisherid

components/match2/wikis/dota2/match_group_input_custom_match_page.lua
Feature request that for match page matches, heroes on the match summary should be in hero pick order. This will be done if they are provided from the dep injection in getHeroes in that order. So let's pick them from the veto instead of player list.
dev
=> feat(match2): sort dota2 extradata hero picks in pick order

components/prize_pool/commons/prize_pool_import.lua
Due to the changed header in #4618 of `opponentFromRecord` function, and the miss that PPT Import also uses this function. 
Live
=> fix(prizepool): error in import due to `opponentFromRecord` param change

definitions/mw.lua
Fix prop name, `bracket` should be `bracketname`.
Fix ret value, non-existing TTs will return nil.
=> docs: return value of `tt.raw`

components/match_ticker/commons/match_ticker_display_components_new.lua, stylesheets/commons/MatchTicker.less
This PR implements the design for the match detail button
- Add match detail button to the overview when the `match.match2bracketdata.matchpage` exists
- Add a button to add match detail page when you're logged in and there is no `match.match2bracketdata.matchpage`
On https://liquipedia.net/dota2/User:Elysienna
Closes https://gitlab.com/teamliquid-dev/liquipedia/web/issue-bucket/-/issues/121
=> feat(matchticker): add match detail button for matchpages

standard/info/wikis/criticalops/info.lua, standard/info/wikis/crossfire/info.lua, standard/info/wikis/zula/info.lua
Zula and COps had it before. Crossfire puts it in manually in bo1 as match score..
=> feat(match2): show bo1  score on zula cops and crossfire

components/match2/wikis/rainbowsix/legacy/match_group_legacy_default.lua, components/match2/wikis/rainbowsix/legacy/match_maps_legacy.lua
Handle this kind of Bo1 input in legacy
```
{{MatchMaps
|team1=vitality|team2=supremacy |winner=1
|games1=6 |games2=2
|details={{BracketMatchSummary
|date=July 5, 2018 - 20:00 {{Abbr/CEST}}|finished=true
|twitch=rainbow six
|youtube=rainbow six pro league
|map1t1ban1=Ying|map1t1ban2=Mute|map1t2ban1=Hibana|map1t2ban2=Mira
|map1t1firstside=def|map1t1atk=2|map1t1def=4|map1t2atk=1|map1t2def=1
|map1=Oregon |map1score= |map1win=1
|siegegg=129
|esl=35999855
|vod=https://youtu.be/UjHXesurcbU
}}
```
Where the bo1 score is also the match score. 
This PR handles it by removing the match level score from legacy (as to let match2 calculate match level score automatically). Additionally, if map1 is missing, it adds in a dummy map1 with the previous match score.
Dev ->  live
=> feat(match2): handle legacy R6 bo1 input

components/match2/wikis/clashroyale/match_summary.lua
Fixes the card display for games with more than one player.
via dev.
Before:
After:
=> fix(match2): Clash Royale card display for duo opponents

components/infobox/commons/infobox.lua, components/prize_pool/commons/prize_pool_base.lua, components/squad/commons/squad.lua, components/squad/commons/squad_utils.lua, components/squad/wikis/dota2/squad_custom.lua, components/squad/wikis/overwatch/squad_custom.lua, components/squad/wikis/smash/squad_custom.lua, components/squad/wikis/starcraft/squad_custom.lua, components/squad/wikis/starcraft2/squad_custom.lua, components/squad/wikis/stormgate/squad_custom.lua, components/widget/widget.lua, components/widget/widget_breakdown.lua, components/widget/widget_builder.lua, components/widget/widget_cell.lua, components/widget/widget_center.lua, components/widget/widget_chronology.lua, components/widget/widget_factory.lua, components/widget/widget_header.lua, components/widget/widget_highlights.lua, components/widget/widget_links.lua, components/widget/widget_table.lua, components/widget/widget_table_cell.lua, components/widget/widget_table_cell_new.lua, components/widget/widget_table_new.lua, components/widget/widget_table_row.lua, components/widget/widget_table_row_new.lua, components/widget/widget_title.lua
Currently `make()` has effectively 3 different return values.
* 1-`Html` obj wrapped in an array (most common)
* `Html`-array (just in two)
* `Widget`-array
The end goal is to have just one return value.
Other PRs will remove the `Widget`-array return value, by doing that logic as preprocessing instead. 
So this PR is focused on the two `Html` cases. After some POC-ing, I found that `string` was the best return value.
So this PR changes the 2 cases of `Html`-array into single `Html`, and then does `tostring` on basically all return values from all Widgets.
This PR in independent of Parts 1, 2 & 3. Part 3 and Part 4 together are both required to make 5.
Tested on some tournament and team pages on dota2
=> refactor(widget): improve building part 4 - `Html[]` into `string`

standard/tier/wikis/worldoftanks/tier_data.lua
Adding the Points tier for World of Tanks since there is an increase in points tables used for tournament qualification. The idea is to be able to show these in the players or teams detailed results.
=> feat(tier): add points tier for WoT

components/match2/commons/match_group_util.lua, components/opponent/commons/opponent_display.lua
reported on discord:
https://discord.com/channels/93055209017729024/372075546231832576/1284885694224797708
dev
=> fix(opponent): in bo1 handling we sometimes show `nil` as score

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua
Adds a misisng faction normalization in sc(2) match2 input processing.
While at it allso adds a tracking category so i can get rid of one of the unwanted aliases in the next weeks.
live
=> fix(match2): missing faction normalization

components/match2/commons/match_group_util.lua
Improve the bo1 special handling further, by account for status as well. 
/dev
=> feat(match2): improve bo1 status handling

components/match2/commons/match_group_display_helper.lua, components/match2/commons/match_group_util.lua, components/match2/wikis/leagueoflegends/match_page.lua, components/match2/wikis/valorant/match_legacy.lua, components/match2/wikis/valorant/match_summary.lua
When retrieving a game record, automatically parse `participants` into a easy usage solution of two arrays calleds `opponents`. 
Tested on lol and val
=> feat(match2): parse participant into arrays

components/match2/commons/match_group_input_util.lua, components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua, components/match2/wikis/ageofempires/match_group_input_custom.lua, components/match2/wikis/arenaofvalor/match_group_input_custom.lua, components/match2/wikis/battlerite/match_group_input_custom.lua, components/match2/wikis/clashofclans/match_group_input_custom.lua, components/match2/wikis/crossfire/match_group_input_custom.lua, components/match2/wikis/deadlock/match_group_input_custom.lua, components/match2/wikis/dota2/match_group_input_custom.lua, components/match2/wikis/leagueoflegends/match_group_input_custom.lua, components/match2/wikis/rocketleague/match_group_input_custom.lua, components/match2/wikis/smite/match_group_input_custom.lua, components/match2/wikis/warcraft/match_group_input_custom.lua, components/match2/wikis/wildrift/match_group_input_custom.lua
TeamCards always outputs players with `_`, so `_` is always need to match match2players.
Tested on valorant
=> feat(match2): remove support for `pagifyPlayerNames=false`

components/game_table/commons/game_table.lua
MGI standardizes the value, so only checking for `np` is needed when querying data
=> refactor(gametable): simplify not played

components/widget/widget.lua, components/widget/widget_breakdown.lua, components/widget/widget_builder.lua, components/widget/widget_cell.lua, components/widget/widget_center.lua, components/widget/widget_chronology.lua, components/widget/widget_customizable.lua, components/widget/widget_div.lua, components/widget/widget_header.lua, components/widget/widget_highlights.lua, components/widget/widget_links.lua, components/widget/widget_table.lua, components/widget/widget_table_cell.lua, components/widget/widget_table_cell_new.lua, components/widget/widget_table_new.lua, components/widget/widget_table_row.lua, components/widget/widget_table_row_new.lua, components/widget/widget_title.lua
Requires Part 3. No widget's `make()` function uses injector anymore, so we can remove it entirely. All injector logic is now in tryChildren().
=> refactor(widget): improve building part 6 - remove injector from make()

components/match2/commons/match.lua, components/match2/wikis/valorant/match_group_input_custom.lua
Bug in #4754, Match/SubObjects is setting an empty participants table.... screwing up the flow...
dev
=> fix(match2): new valorant game opponent handling

javascript/commons/Countdown.js
Twice now we've had issues with this not being idempotent, so it's just easier to make it so instead of adding workarounds every time it happens. Not even sure when/where the last breakage was.
=> fix(countdown): Make `init()` js method idempotent

components/infobox/commons/infobox_person.lua
Adding in Macau and Singapore to follow the eastern naming order. Macau seemed to be missed and should commonly use eastern order. Singapore is often a mix, but since we don't allow for a swap from western to eastern with nonameflip=true, might be handier to default singapore to eastern as well
=> feat(infobox): Update Eastern Naming Country Order List

components/opponent/wikis/warcraft/opponent_custom.lua
Due to it being used widely in match2 and some other places re-add the `p1race` alias for faction in solo opponnets.
live
=> fix(opponent): Missing alias for faction in solo opponents on wc3

javascript/commons/Mainpage.js
The API call used to get the this day sections sometimes will contain an ad slot. This will be a duplicate of the ad slots we already have. Remove these to avoid having duplicate slots.
I tested this in production.
=> fix(mainpage.js): Fix duplicate ad slots on main page this day section

components/match2/wikis/teamfortress/get_match_group_copy_paste_wiki.lua, components/match2/wikis/teamfortress/match_group_input_custom.lua, components/match2/wikis/teamfortress/match_legacy.lua, components/match2/wikis/teamfortress/match_summary.lua
**Match2 for Team Fortress wiki**, they are one of wikis that hasnt got one but also pretty similar to existing setups we have.
**Base**
- The first revision is a paste from World of Tanks (which Tanks itself is then a cleaner/updated version based on COD)
- a Match of TF behaves similar to those, Have Maps and Scores
**Custom**
- Due to Team Fortress has quite a lot of custom links that needs to be added back, there are more than usual here
- **logstf and logstfgold** are suggested to be added as Per Map instead of a single link. Similar to **stats** in CS Match2, because of this both logstf does get stored in Extradatas.
- **_Vetos/MVP may be removed later, I'm still waiting response from the editors if they want it_** 
LIVE on Several pages : …
=> feat(match2): create team fortress support

components/infobox/commons/infobox_campaign_mission.lua, components/infobox/commons/infobox_unofficial_world_champion.lua, components/infobox/extensions/wikis/warcraft/infobox_extension_building_unit_shared.lua, components/infobox/wikis/leagueoflegends/infobox_unit_champion_custom.lua, components/infobox/wikis/mobilelegends/infobox_item_custom.lua, components/infobox/wikis/mobilelegends/infobox_unit_hero_custom.lua, components/infobox/wikis/overwatch/infobox_unofficial_world_champion_custom.lua, components/infobox/wikis/smite/infobox_unit_god_custom.lua, components/infobox/wikis/starcraft/infobox_league_custom.lua, components/infobox/wikis/starcraft/infobox_team_custom.lua, components/infobox/wikis/starcraft2/infobox_league_custom.lua, components/infobox/wikis/starcraft2/infobox_team_custom.lua, components/infobox/wikis/starcraft2/infobox_unofficial_world_champion_custom.lua, components/infobox/wikis/stormgate/infobox_league_custom.lua, components/infobox/wikis/stormgate/infobox_team_custom.lua, components/infobox/wikis/warcraft/infobox_character_custom.lua, components/infobox/wikis/warcraft/infobox_league_custom.lua, components/infobox/wikis/wildrift/infobox_item_custom.lua, components/infobox/wikis/wildrift/infobox_unit_champion_custom.lua, components/widget/widget_breakdown.lua
Migrate legacy inputs for children to children. 
This PR is for the Breakdown Widget.
=> refactor(widget): children rework - part 7&8 for breakdown widget

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua, components/match2/wikis/stormgate/match_group_input_custom.lua, components/match2/wikis/warcraft/match_group_input_custom.lua
enable reading from current and intended wiki var
- adjust other templates & modules on warcraft, stormgate broodwar and sc2 accordingly
- adjust usage of the wiki var on content pages
- open a pr to remove the currently used one
N/A
=> chore(match2): prep for requested wiki var name change

components/match2/wikis/geoguessr/get_match_group_copy_paste_wiki.lua, components/match2/wikis/geoguessr/match_group_input_custom.lua, components/match2/wikis/geoguessr/match_summary.lua
For New wiki: **GeoGuessr**
the setup is simple, this is #4333 (Team Fortress) Match2 as both version were developed at the same time,
(its also why Geo didnt had M2 pr up until now, I was waiting for TF to be merged)
Match structure for Geo is similar to TF just more Solo/Indivs than Teams and theres event with the other three types of Duos, Trios and Quads (I think theres even some FFA-style event before but eventually decide to exclude coverage for now)
- The custom per map links from TF are also being removed because it's not needed here
- Stats from the Generator is removed
- Geo do had usage of all opponent type: **Team, Solo, Duo, Trio, Quad** but with both the setup and the generator all 5 works with no issue already.
-  everything else should be outright same as 4333
LIVE
=> feat(match2): Create GeoGuessr support

components/external_media_links/external_media_link.lua
feat(ExternalMediaLinks): Add `trans_title` support to wrapper as per request on discord
https://discord.com/channels/93055209017729024/268719633366777856/1288674347845812296
mind this will only adjust the module the form has to be adjusted afterwards too (on each wiki)
not tested, just a super easy 1:1 map
=> feat(ExternalMediaLinks): Add `trans_title` support to wrapper

components/infobox/commons/infobox_building.lua, components/infobox/wikis/stormgate/infobox_building_custom.lua, components/infobox/wikis/stormgate/infobox_unit_custom.lua
With the latest 0.1.0 patch the first hero/subfaction-specific buildings appeared (Arkhos Arcship, Arkhos Arcstation and Arkhos Arcsfortress for hero Kastiel). Changes are identical to how Infobox/Unit is build. 
- Allow customizable header in Infobox/Building
- Add `|subfaction=` and subHeader to Infobox/Building/Custom
dev-tools
- https://liquipedia.net/stormgate/Arkhos_Arcship
- https://liquipedia.net/commons/Module:Infobox/Building/dev/senti
- https://liquipedia.net/stormgate/Module:Infobox/Building/Custom/dev/senti
=> feat(infobox): on stormgate, add support subfactions on buildings

components/match2/commons/match_group_legacy.lua
Third place match headers are ignored :(
This pr fixes that.
/dev
=> feat(match2): in legacy mode, handle third place headers

components/external_media_links/external_media_list.lua
Removes the unintended (second) `[]` around translated title display.
reported on discord by ElectricalBoy
https://discord.com/channels/93055209017729024/268719633366777856/1291372169829421118
live
=> fix(externalMediaList): unintended `[]` in `translatedtitle` display

components/match2/wikis/brawlstars/match_group_input_custom.lua
due to the `table.remove` during looping through the array the array shrinks and the later indexes are never reached
dev into live
=> fix(match2): unattached participant attaching faulty

components/infobox/wikis/warcraft/infobox_league_custom.lua
- fix: set `useDefault = false` when processing the manual input
- feat: set RoC as default for events that started before  TFT was released (as per discord request)
dev
=> feat(infobox): tweak game handling on warcraft

stylesheets/commons/Miscellaneous.less
Made a thing for deadlock abilities to show the scaling factor of it similarly to the in game graphic.
Built it on this page: https://liquipedia.net/deadlock/User:Kanoodles
Template that uses it is here: https://liquipedia.net/deadlock/Template:DeadlockSpiritScalingBox
=> feat: Deadlock Abilities Scaling Ratio Box Template CSS

components/widget/widget.lua
With this little one tweak, adding a Widget to a mw.html's node will no longer kill everything. Rather it should work quite smoothly
Without _build
With _build
=> feat: support widgets as nodes in mw.html

components/match2/wikis/rocketleague/match_group_input_custom.lua, components/opponent/commons/opponent.lua
Check for alternative storage names of "display name" since they are not always the same
/dev
=> fix(match2): rocketleague's non-empty-participant check does not work on party opponents

components/infobox/wikis/apexlegends/infobox_map_custom.lua, components/prize_pool/commons/prize_pool.lua, components/prize_pool/commons/prize_pool_award.lua, components/prize_pool/commons/prize_pool_base.lua, components/widget/widget_table.lua, components/widget/widget_table_cell.lua, components/widget/widget_table_row.lua
For row and full-table, there were no cases of instantiated at creation, only using the `addCell` and `addRow` functions.
=> refactor(widget): migrate Widget Table(Old) to use children instead of content

components/match2/wikis/mobilelegends/match_group_input_custom.lua
=> refactor(match2): MLBB MGI

components/match2/commons/match_group_input_util.lua, components/match2/wikis/ageofempires/match_group_input_custom.lua
All usages of `readPlayersOfTeam` (old) is now removed, change `readPlayersOfTeamNew` to just `readPlayersOfTeam`.
/dev
=> refactor(match2): cleanup player processing functions

components/match2/wikis/hearthstone/get_match_group_copy_paste_wiki.lua, components/match2/wikis/hearthstone/match_group_input_custom.lua, components/match2/wikis/hearthstone/match_legacy.lua, components/match2/wikis/hearthstone/match_summary.lua, standard/info/wikis/hearthstone/info.lua
depends on #4645
Adding a basic match summary for 1 vs 1 tournaments in hearthstone.
(This is excluding the rare team events where individual players would need to be listed e.g aoe style.)
https://liquipedia.net/hearthstone/User:Kanoodles/Bracket
=> feat(match2): support hearthstone

components/match2/wikis/pokemon/match_group_input_custom.lua
During refactor the prefix of the pick/ban input was mixed up.
This PR fixes the prefix.
dev into live
=> fix(match2): wrong prefix for pick/ban input on pokemon

components/match2/wikis/pokemon/match_legacy.lua
For legacy reasons switch opponent names in legacy match1 storage to have spaces instead of underscores
dev into live
=> fix(match2): pkmn legacy macth storage has underscores in opponent names

components/participant_table/commons/starcraft_starcraft2/participant_table_starcraft.lua
Pass along the input index for sorting purposes (in case alphab sorting gets disabled)
dev
=> fix(participant table): missing index passalong in readEntry

components/match2/wikis/deadlock/match_summary.lua, standard/icon_data.lua, stylesheets/commons/Colours.less
Adding support for a side display in deadlock, adding icons on the outer sides of the hero select.
Tested on /dev and matchsummary previews
=> feat(match2): add side information on deadlock

components/match2/wikis/hearthstone/get_match_group_copy_paste_wiki.lua
Map copy paste was missing some parts for the party opponent case
live
=> fix(match2): heartstone's map copy paste for party opponents is faulty

components/match2/wikis/ageofempires/legacy/match_maps_legacy.lua
Module to add the wrappers to MatchListStart and Showmatch match1 templates.
[MatchMapsTeam](https://liquipedia.net/ageofempires/Return_of_the_Clans#Group_Stage)
[MatchMaps](https://liquipedia.net/ageofempires/T90_Titans_League/1/Platinum_League#Group_Stage)
[ShowmatchTeam](https://liquipedia.net/ageofempires/TyRanT_War/2/Show_Match#Results)
[Showmatch](https://liquipedia.net/ageofempires/Bonjwa_Fight_Night_Club#Finals)
After this I think the only templates left to wrap are ffa ... We don't have support for them yet
=> feat(match2): Add match maps legacy to aoe

components/widget/infobox/widget_infobox_chronology.lua
Typo in the class wrapper (string, not table)
Live
=> fix(infobox): typo in chronology fallback

components/widget/infobox/widget_infobox_links.lua
Typo on two of the table.insert + missing table to child to the div (got plans to do something about it)
Live
=> fix(infobox): error in infobox links widget

.github/workflows/deploy test.yml
The previous action (nx-set-shas) would try to find a workflow run of deploy-personal on the main branch, not find one, and thus default to the latest commit on main:
> WARNING: Unable to find a successful workflow run on 'origin/main', or the latest successful workflow was connected to a commit which no longer exists on that branch (e.g. if that branch was rebased)
We are therefore defaulting to use HEAD~1 on 'origin/main'
When then additional changes exist on main, the changed-files action would diff the current main and the branch commits, which would list the files changed on main as changed files, thus overdeploying files. (fwiw, nx-set-shas could have been completely replaced by just setting `base_sha: main` in the changed-files config)
The new action extracts the fork point of the …
=> ci: improve "forkpoint" to determine branch changes

components/match2/commons/match.lua
We skip in the custom loop eg. map3, but since only 2 maps are added to match.games, the 3rd one is still read by _moveRecordsFromMatchToList(). 
This PR changes away from `_moveRecordsFromMatchToList` and reading of mapX, opponentX as inputs, as no wiki no longer uses it for parsed input.
/dev on wc3
=> fix(match2): maps that should be ignored are not

components/transfer/commons/transfer_row.lua
Add a missing icon fallback for icon2 from icon1 in transfer row processing
dev into live
=> fix(transfer): missing icon fallback for icon2 from icon1

components/transfer/commons/transfer_references.lua
Adds a missing `not` in the makeUnique logic for transfer refs display
dev to live
=> fix(transfer): logic inverted

components/infobox/wikis/deadlock/infobox_league_custom.lua
Adding custom infobox league to display the amount of teams/players.
https://liquipedia.net/deadlock/Proving_Grounds/Cup_2
https://liquipedia.net/deadlock/Module:Infobox/League/Custom/dev/kano
=> feat(infobox): custom infobox league for deadlock

components/widget/infobox/widget_infobox_title.lua, components/widget/widget.lua
To allow for each inputs, the `children` special prop no longer needs to be an array on input. It will be automatically converted into an array if not. A non-array children is automatically wrapped into an array of length 1.
dev
=> feat(widget): allow for non-arrays as children

components/transfer/commons/transfer_row.lua, spec/transfer_spec.lua
Currently we process (and store) uksc etc as alpha2, which converts them to uk. (which would be totally fine for me...)
Due to complaints on discord this PR proposes to switch it to alpha 3 to support the uk sub flag stuff.
dev (on mobile)
=> fix(transfer): uk sub flags not showing

components/match2/wikis/easportsfc/match_group_input_custom.lua
Currently bestof gets not parsed at all on fifa.
This will lead to it being a string if there is input for it and hence causing errors in some edge cases.
reported on discord by omarion:
https://discord.com/channels/93055209017729024/1209065403955806270/1296184431358509067
investigated by enuaj and found a solution that ignored annos but pointed me to the fact that bestof was not parsed:
https://discord.com/channels/93055209017729024/1209065403955806270/1296200399354724373
dev
=> feat(match2): parse bestof on easportsfc

components/match2/wikis/heroes/match_summary.lua, components/match2/wikis/honorofkings/match_summary.lua, components/match2/wikis/leagueoflegends/match_summary.lua, components/match2/wikis/mobilelegends/match_summary.lua, components/match2/wikis/pokemon/match_summary.lua, components/match2/wikis/smite/match_summary.lua, components/match2/wikis/wildrift/match_summary.lua, components/widget/match/summary/widget_match_summary_character_ban_table.lua, components/widget/match/summary/widget_match_summary_characters.lua, stylesheets/commons/Brackets.less
* Add some empty checking into the Widgets (remove checks on match summaries)
* Tweak the CSS to get a better display on dota2 (for other wikis this is no change in their display)
CSS in devtools, empty checking is partially live
=> feat(match2): improve character pick and ban display

components/widget/basic/widget_basic_link.lua, components/widget/misc/widget_misc_inline_icon_and_text.lua
Migration of Widget/Chronology to this broke occasions that did not include a pipe character and both link and text.
Let me know if you prefer to have this fallback in the Chronology widget instead.
dev
=> feat(widget): let Link Widget fallback to using link as display text

components/match2/wikis/apexlegends/match_summary.lua
When using {{ShowMatch}} the score is currently shown as `-1`. 
Change the raw usage of opponent.score to using `OpponentDisplay.InlineScore` to display it
/dev
=> fix(match2): incorrect scores shown when using showmatch on apex

components/match2/wikis/deadlock/get_match_group_copy_paste_wiki.lua, components/match2/wikis/deadlock/match_group_input_custom.lua, components/match2/wikis/deadlock/match_summary.lua
Adding support for Hero Bans in Deadlock
The number of bans/ban format is currently community driven, so the current display supporting up to 6 bans should be future proof
Dev modules:
https://liquipedia.net/deadlock/Module:MatchGroup/Input/Custom/dev/kano
https://liquipedia.net/deadlock/Module:MatchSummary/dev/kano
Test page:
https://liquipedia.net/deadlock/User:Kanoodles/test
=> feat(match2): support for hero bans on deadlock

components/transfer/commons/transfer_row.lua, components/transfer/commons/transfer_row_display.lua, spec/transfer_spec.lua
- shut up an anno warning in transfer display
- switch from countrycode to countryname for storage/processing
- can't use alpha2 country code due to it not supporting the shitty uk sub flag stuff
- can't use alpha3 country code due to it not supporting:
```lua
--   ISO 3166-1 alpha-2 User-assigned Code Elements
['xk'] = 'kosovo',
['xx'] = 'nonrepresenting',
```
alternative solution would be to add user assigned alpha3 country codes for those 2 cases... ([xkx for Kosovo](https://en.wikipedia.org/wiki/XK_(user_assigned_code)) and xxx for non rep)
lmk if that is prefered
untested on wki, don't have the time atm
golden/smoke tests should be enough
=> fix(transfer): flag processing not perfect

components/match2/commons/bracket_template.lua
=> fix(match2): display on bracket templates broken

components/match2/wikis/clashroyale/match_summary.lua, components/match2/wikis/splatoon/match_summary.lua, components/widget/match/summary/widget_match_summary_characters.lua, stylesheets/commons/Brackets.less
Remove the order reversal of picks and bans for the right side team.
Dev tools
=> feat(match2): remove flipping of character order in match sumamry

stylesheets/commons/Brackets.less
`.brkts-popup-body-element > *` took higher prio in the CSS `.brkts-popup-body-element-thumbs`
add change the locator to `div.brkts-popup-body-element-thumbs` to bump up the specificity
devtools
=> fix(match2): pick/ban specificity

components/match2/wikis/ageofempires/match_group_input_custom.lua
match2 requires to set the maplink/name in the infobox, but sometimes a map is overlooked. This adds a tracking category to find and clean up these, as well as displaying the map input instead of `Unknown`.
dev
=> fix(match2): Display input for unknown maps, log missing map on AoE

components/infobox/commons/infobox_league.lua, spec/prize_pool_spec.lua, spec/team_card_storage_spec.lua
suggestion as per discussion on discord and in #4911
additionally we should set the topic publishertier for the next modules sync meeting
goldens
=> fix(publishertier): store empty instead of stringified false

components/match2/wikis/ageofempires/legacy/legacy_bracket_match_summary.lua
When either Default win or Default is entered, we should set `|walkover=W` and disregard the map name. This will align with the current input format used for a default win in match2.
/dev and [sandbox](https://liquipedia.net/ageofempires/User:LuckeLucky/sandbox)
=> fix(match2): Handle default map win in legacy wrapper on AoE

components/match2/wikis/ageofempires/match_summary.lua
There are occasions on AoE where there are "maps" entered as skipped (=no winner, resulttype np), but the actual map is unknown and thus left empty.
This fix catches these to still display a row in the popup.
dev
=> fix(match2) Display games with resulttype but no winner on AoE

components/match2/wikis/ageofempires/legacy/match_maps_legacy.lua
matchsection was a param used in MatchListStart that was not mapped by the wrapper.
/dev
=> fix(match2): Handle matchsection in legacy wrapper AoE

standard/links/commons/links.lua
Remove the factror links that were added with #4880 (after being removed with #3462)
As per [discord discussion](https://discord.com/channels/93055209017729024/268719633366777856/1297878614582362142) factor is dead.
4880 probably added them because they were still stored on lol in matches, but not displayed anymore
untested
=> chore(standard): remove factor link

components/infobox/wikis/brawlstars/infobox_league_custom.lua, components/infobox/wikis/callofduty/infobox_league_custom.lua, components/infobox/wikis/clashofclans/infobox_league_custom.lua, components/infobox/wikis/crossfire/infobox_league_custom.lua, components/infobox/wikis/fortnite/infobox_league_custom.lua, components/infobox/wikis/halo/infobox_league_custom.lua, components/infobox/wikis/mobilelegends/infobox_league_custom.lua, components/infobox/wikis/pokemon/infobox_league_custom.lua, components/infobox/wikis/pubg/infobox_league_custom.lua, components/infobox/wikis/pubgmobile/infobox_league_custom.lua, components/infobox/wikis/rocketleague/infobox_league_custom.lua, components/infobox/wikis/starcraft2/infobox_league_custom.lua, components/infobox/wikis/stormgate/infobox_league_custom.lua, components/infobox/wikis/wildrift/infobox_league_custom.lua
Trim away redundant stuff (due to the publishertier changes on commons)
done
=> refactor(infobox): clean up some publisher tier stuff in customs

components/transfer/commons/transfer_row_display.lua
If role(2) is nil but role(2)_2 is not nil table.concat errors.
To avoid that filter away the empty roles for display
dev into live
=> fix(transfer): nil role2 causes error in edgge case

components/match2/wikis/leagueoflegends/legacy/match_maps_legacy.lua
currently it fails to process the details correctly if map name is unset
this pr changes it to not check on set map name but if the input for the map is non empty
dev
=> fix(match2): lol matchMaps legacy not accoutning for empty maps

components/infobox/wikis/warcraft/infobox_item_custom.lua
Use Array.append instead of a plain table so that nil elements get removed inbetween
dev into live
=> fix(infobox): wc item infobox showing `table` at teh bottom

components/match2/wikis/dota2/match_summary.lua, components/match2/wikis/honorofkings/match_summary.lua, components/match2/wikis/leagueoflegends/match_summary.lua, components/match2/wikis/mobilelegends/match_summary.lua, components/match2/wikis/smite/match_summary.lua, components/match2/wikis/wildrift/match_summary.lua, components/widget/match/summary/widget_match_summary_game_winloss_indicator.lua
Use what was made standardized components in #4914 and apply it to more wikis
dev on lol
=> refactor(match2): MS on HoK, LoL, MLBB, Smite & WildRift

components/match2/wikis/arenafps/match_summary.lua, components/match2/wikis/battlerite/match_summary.lua, components/match2/wikis/brawlhalla/match_summary.lua, components/match2/wikis/clashofclans/match_summary.lua, components/match2/wikis/fighters/match_summary.lua, components/match2/wikis/geoguessr/match_summary.lua, components/match2/wikis/hearthstone/match_summary.lua, components/match2/wikis/heroes/match_summary.lua, components/match2/wikis/honorofkings/match_summary.lua, components/match2/wikis/mobilelegends/match_summary.lua, components/match2/wikis/omegastrikers/match_summary.lua, components/match2/wikis/pokemon/match_summary.lua, components/match2/wikis/trackmania/match_summary.lua, components/match2/wikis/wildrift/match_summary.lua
Removed unused addFooters (commons already does this).
Non of the moba's had anything in their ExternalLinks other than stuff like reddit and preview, which is on commons' link support already
=> refactor(match2): remove unused wiki-customs functions

components/match2/commons/match_group_input_util.lua, components/match2/wikis/counterstrike/match_group_input_custom.lua
Fix the status/finished processing on cs by applying fallbacks a bit differently and moving status processing further up.
~~Also allow `'postponed'` as valid not played input~~
dev
=> fix(match2): `tournament_status` is not working

components/match2/wikis/clashroyale/match_legacy.lua
Legacy storage would not find proper opponent data for solo
live
=> fix(match2): Wrong index on match2players in CR Legacy

components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua
As per request on discord (sc2 channel): do not show the popup if h2h is the only link
dev
=> feat(match2): do not show popup if only h2h link is present on sc(2)

components/match2/wikis/brawlstars/match_group_input_custom.lua, components/match2/wikis/brawlstars/match_summary.lua
Waiting for community confirmation that it's OK change to do, initial response seems positive
Old:
New:
/dev
=> refactor(match2): standardize brawlstars' pick and bans display

components/prize_pool/commons/prize_pool_import.lua
Currently if ppt import tries to process a literal without name it errors.
This PR adds a nil check for that
dev
=> fix(prize pool): error on literals with empty name

components/infobox/wikis/hearthstone/infobox_league_custom.lua
Issue reported in discord.
As per https://github.com/Liquipedia/Lua-Modules/blob/baed407c7c5912c954c7ccd4ad59fb5d788faec4/components/infobox/extensions/commons/infobox_extensions_prize_pool.lua#L44
dev
=> fix(infobox) Typo in hearthstone infobox league

spec/array_spec.lua, standard/array.lua
Currently Array.map errors if we have an undefined return (`return end`). It needs explicit `nil` as return value.
This PR changes the behaviour of Array.map so that it doesn't need the nil return but also eats the undefined return.
dev + busted
=> feat: Array.map should handle no return same as nil return

components/infobox/wikis/dota2/infobox_cosmetic_custom.lua, components/widget/infobox/widget_infobox_header.lua
Two small issues affecting the dota2 cosmetic infobox. 
Incorrect setup class for ImageText on the Header, causing error
Incorrect usage of the Center widget, causing those elements not to be displayed
Lvie
=> fix(infobox): issues on dota2 cosmetic infobox

components/widget/match/summary/widget_match_summary_character.lua, components/widget/match/summary/widget_match_summary_characters.lua
Don't need to render at fullsize, use a thumbnail version that's the size of the hoover.
dev
=> feat(match2): render match summmary characters at an appropriate size

components/match2/commons/bracket_template.lua
need to insert the opponents before making the records a match group so that coordinates for the lines between matches get drawn properly
can not use plain opponnet.blank due to:
- match2players has to be a table or else `MatchGroupUtil.makeMatchGroup` errors
- additionally at that point it isn't an opponent but a `match2opponent:LpdbBaseData` object
dev to live
=> fix(match2): display on bracket template pages still off

components/infobox/wikis/counterstrike/infobox_league_custom.lua
Add new restriction type (`national`) for CS league infobox.
Tested using branch deploy.
=> feat(infobox): add national restriction for CS league infobox

components/match2/wikis/leagueoflegends/get_match_group_copy_paste_wiki.lua
leagueoflegends wiki previously used [Template:Match](https://liquipedia.net/leagueoflegends/index.php?title=TemplateArchive:Match/1&redirect=no) as a local redirect for a match1 component. The uses of the legacy redirect were all cleaned up and the redirect itself was archived few days ago.
As `Template:Match` now links to the Commons version, the use of [Template:Match2](https://liquipedia.net/leagueoflegends/Template:Match2) is no longer necessary. Thus, this PR updates MatchGroup generator for LoL to start using `Template:Match`.
dev
=> feat(match2): standardize template usage on league of legends

components/match2/commons/match_summary_base.lua, components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua, components/match2/wikis/ageofempires/match_group_input_custom.lua, components/match2/wikis/halo/match_summary.lua, components/match2/wikis/rainbowsix/legacy/match_maps_legacy.lua, components/match2/wikis/valorant/match_legacy.lua, components/match2/wikis/warcraft/legacy/match_group_legacy_convert_map_data.lua, components/match2/wikis/warcraft/match_summary.lua, components/widget/match/summary/widget_match_summary_map_veto_start.lua
Clean up some double space occourances (found via search in vscode) to either single space or tabs (in case of indents).
N/A
=> refactor(match2): cleanup space usage

stylesheets/commons/Brackets.less
Typo missing the `1`
dev tools
=> fix(match2): missing 1% on margin-left for win/loss icons

standard/tier/wikis/tetris/tier_data.lua
D tier isn't used on Tetris so kicking to remove the filter option on the mainpage
live
=> feat(tier): remove unused D-tier from Tetris

components/infobox/commons/infobox_league.lua, components/widget/basic/widget_basic_link.lua, standard/date_ext.lua, standard/icon_data.lua
Add accommodation button for offline tournaments with ONE known venue. If there are ZERO venues, fallback to use the CITY if there's exactly ONE city.
Look on CS (and highlighted)
Look on Dota2
/dev
=> feat(infobox): accommodation button in infobox league

components/match2/wikis/brawlhalla/match_legacy.lua
add a nil catch needed for empty opponent case
live
=> fix(match2): brawlstars legacy storage erroring on empty opponents

components/infobox/wikis/ageofempires/infobox_person_player_custom.lua
Most history entries from recent years are automated by now, so editors suggested to switch this around to only show that to logged-out users.
Manual history still exists on some 200 pages, so show that for logged-in users to help migrating them.
dev
=> feat(infobox): Show automated team history for logged out users on AoE

components/match2/wikis/dota2/match_page.lua, components/match2/wikis/leagueoflegends/match_page.lua
Currently on (big) match pages the vod is not displayed. This PR adds that.
dev on dota2
=> feat(match2): add match vods on match pages

components/match2/commons/match_summary_base.lua, components/match2/wikis/arenafps/match_summary.lua, components/match2/wikis/battlerite/match_summary.lua, components/match2/wikis/callofduty/match_summary.lua, components/match2/wikis/clashofclans/match_summary.lua, components/match2/wikis/criticalops/match_summary.lua, components/match2/wikis/crossfire/match_summary.lua, components/match2/wikis/geoguessr/match_summary.lua, components/match2/wikis/halo/match_summary.lua, components/match2/wikis/magic/match_summary.lua, components/match2/wikis/overwatch/match_summary.lua, components/match2/wikis/rainbowsix/match_summary.lua, components/match2/wikis/rocketleague/match_summary.lua, components/match2/wikis/sideswipe/match_summary.lua, components/match2/wikis/splatoon/match_summary.lua, components/match2/wikis/splitgate/match_summary.lua, components/match2/wikis/teamfortress/match_summary.lua, components/match2/wikis/tetris/match_summary.lua, components/match2/wikis/tft/match_summary.lua, components/match2/wikis/trackmania/match_summary.lua, components/match2/wikis/valorant/match_summary.lua, components/match2/wikis/zula/match_summary.lua
Create a standardized createBody, and use it where it can be used.
Want to expand it to add character bans, but currently that's depends on a max num of bans, which varies by game.
/dev on R6
=> feat(match2): standardize core body display logic

components/match2/wikis/stormgate/match_summary.lua, components/match2/wikis/warcraft/match_summary.lua
Game comment is located before 2nd team heroes, causing the display to be incorrect.
This PR fixes this
devtools
=> fix(match2): game comment location on wc3 and sg

components/match2/wikis/callofduty/match_summary.lua, components/match2/wikis/crossfire/match_group_input_custom.lua, components/match2/wikis/crossfire/match_summary.lua
Standardize displays and remove unused header on crossfire.
MapMode icon is temporarily removed, will make a return in a later PR.
dev
=> feat(match2): standardize cod and crossfire display

components/match2/wikis/geoguessr/match_summary.lua, components/match2/wikis/halo/match_summary.lua, components/match2/wikis/omegastrikers/match_summary.lua, components/match2/wikis/osu/match_group_input_custom.lua, components/match2/wikis/osu/match_summary.lua, components/match2/wikis/overwatch/match_summary.lua, components/match2/wikis/splitgate/match_summary.lua, components/match2/wikis/teamfortress/match_summary.lua, components/match2/wikis/tetris/match_summary.lua, components/match2/wikis/worldoftanks/match_group_input_custom.lua, components/match2/wikis/worldoftanks/match_summary.lua
Standardize display and remove unused paths (`game.header`).
MapMode icons are temporarily removed.
/dev on OW
=> feat(match2): standardize display on geo, halo, os, ow, splitg, tf, tetris & wot

components/match2/wikis/rainbowsix/match_summary.lua, components/widget/match/summary/widget_match_summary_detailed_score.lua, stylesheets/commons/Brackets.less
Due to width limitation when using icon, the icon and text row breaks. Increase the width when using icon.
Also remove the `brkts-popup-body-match-sidewins-overtime` style as it's no longer needed.
devtools
=> fix(match2): line break on R6 match summary

standard/tier/wikis/arenafps/tier_data.lua
D tier isn't used on Arenafps so kicking to remove the filter option on the mainpage
live
=> feat(tier): remove unused D-tier from Arenafps

components/infobox/wikis/pokemon/infobox_person_player_custom.lua
Allow player's stored transfer data to be stored as datapoints which can then allow automatic team icon on Individual tournaments. We've run into a situation where player didnt have the corresponding team icon applied on their 1v1 events, when they should have it. 
Given Pokemon has very very little amount of Team Transfers that is for the 1v1 scene. This should be very helpful to avoid manual addition of those (incl. Minuscule amount of transfer cleanup needed)
https://liquipedia.net/pokemon/index.php?title=User:Hesketh2/Test&action=edit (Sejun has T1 icon in the imported prize pool by auto)
=> feat(infobox): on pokemon, store in LPDB for player history

components/infobox/wikis/starcraft/infobox_strategy_custom.lua
The page https://liquipedia.net/starcraft/1_Factory_Tanks_(vs._Zerg) has category "Tv**z** Builds" instead of "Tv**Z** Builds". This fixes the capitalization to use the historical categories (e.g. https://liquipedia.net/starcraft/index.php?title=Category:TvZ_Builds&action=history)
dev
=> fix(infobox): matchup category lowercased in StarCraft's strategy infobox

components/match2/wikis/goals/get_match_group_copy_paste_wiki.lua, components/match2/wikis/goals/match_group_input_custom.lua, components/match2/wikis/goals/match_summary.lua, standard/info/wikis/goals/info.lua
**I port it over last year and forgot to revisit it**
GOALS is a soccer game
so I decide to update the paste by using the current version of EA SPORTS FC Setup (recently updated October 17) without touching any edits yet, given its same game genre
LIVE https://liquipedia.net/goals/GOALS_Community_Cup/2
DEV https://liquipedia.net/goals/User:Hesketh2
=> feat(match2): Add GOALS support

components/infobox/wikis/counterstrike/infobox_league_custom.lua, standard/highlight_conditions/wikis/counterstrike/highlight_conditions.lua
Enforce default highlight values for publisher tier for CS wiki as we only want sponsored events to be highlighted now whereas Valve have introduced some other tiers too now that aren't sponsored.
Tested in combination with #4976 via dev deploy.
=> feat(highlight_condtions): add CS custom logic

components/match2/wikis/easportsfc/match_group_input_custom.lua
=> feat(match2): standardize processMatch on fifa

components/match2/commons/match_group_input_util.lua
For trackmania and rocketleague
dev on rl
=> feat(match2): make autoScore optional

stylesheets/commons/Fountain.less
min-width to ensure the width on mobile devices are not too narrow. This change is needed at the moment. 
space between is just to make the columns look a tiny bit nicer. This is just my preference, so this is not needed.
In google chrome dev tools on the main page and game hub on dota 2 only across a variety of window sizes to test the . I am not aware that this code is used on any other wiki at the moment.
=> feat: improve useful articles on dota2 main page

stylesheets/commons/Brackets.less
The flex-grow on the character display causes display issues at times. The center piece should be the growing one.
Tested in devtools on Heroes, Valorant, dota2 and Warcraft. Which should cover all cases
=> feat(match2): remove flex-grow on characters display

components/match2/wikis/fighters/match_group_input_custom.lua, components/match2/wikis/fighters/match_summary.lua
With new and improved looks:
Team Game (also applies to non-solo parties):
Solo Game (minor tweaks):
dev
=> feat(match2): improve display for non-solo matches on fighters

components/match2/wikis/heroes/match_group_input_custom.lua, components/match2/wikis/pokemon/match_group_input_custom.lua, components/match2/wikis/tft/match_group_input_custom.lua, components/match2/wikis/wildrift/match_group_input_custom.lua
Nothing major as the scores are not used for display. (doesn't error). But it's not working as intended without this
=> fix(match2): mapScore calc on heroes, pokemon and wildrift

components/match2/wikis/rocketleague/match_group_input_custom.lua
A series' best-of length cannot be calculated by the number of maps, so this logic is removed.
/dev
=> feat(match2): remove autocalculating bestof on rocketleague

components/match2/wikis/pokemon/get_match_group_copy_paste_wiki.lua
I've come to realize that several MOBA wikis I never actually put the generator on git (HoK, MLBB, SMITE, This) some dated as far as 2022
so i'm taking time to updating those to matched the newest version possible
This and the other mentions will be based on the current LoL's match copypaste setup, but since Pokemon is a bit different I'm getting this one in first, the rest will follow in a different PR
LIVE
=> feat(match2): Add copypaste for Pokemon

components/infobox/commons/infobox_league.lua
once the event has finished (assumed once the end date has been exceeded by 24h) do not display th ebutton anymore
reason: the button seems useless for finished events
dev
=> feat(infobox): show accomodation button only on non finished events

components/match2/commons/match_group_input_util.lua, components/match2/wikis/battlerite/match_group_input_custom.lua, components/match2/wikis/brawlstars/match_group_input_custom.lua, components/match2/wikis/callofduty/match_group_input_custom.lua, components/match2/wikis/clashofclans/match_group_input_custom.lua, components/match2/wikis/clashroyale/match_group_input_custom.lua, components/match2/wikis/crossfire/match_group_input_custom.lua, components/match2/wikis/dota2/match_group_input_custom.lua, components/match2/wikis/halo/match_group_input_custom.lua, components/match2/wikis/heroes/match_group_input_custom.lua, components/match2/wikis/honorofkings/match_group_input_custom.lua, components/match2/wikis/leagueoflegends/match_group_input_custom.lua, components/match2/wikis/mobilelegends/match_group_input_custom.lua, components/match2/wikis/osu/match_group_input_custom.lua, components/match2/wikis/overwatch/match_group_input_custom.lua, components/match2/wikis/pokemon/match_group_input_custom.lua, components/match2/wikis/rainbowsix/match_group_input_custom.lua, components/match2/wikis/splatoon/match_group_input_custom.lua, components/match2/wikis/splitgate/match_group_input_custom.lua, components/match2/wikis/tft/match_group_input_custom.lua, components/match2/wikis/valorant/match_group_input_custom.lua, components/match2/wikis/wildrift/match_group_input_custom.lua, components/match2/wikis/worldoftanks/match_group_input_custom.lua
as per report on discord the mvp data is missing flags and teams on purged/edited pages
this seems to come from a lack of access to opponents data during the processing due to the changes with the recent refactors
this pr passes along the opponents data to the `readMvp` function so that it processes mvps properly again
dev on hok
=> fix(match2): mvp processing does not have access to opponents

components/infobox/wikis/dota2/infobox_league_custom.lua, components/infobox/wikis/leagueoflegends/infobox_league_custom.lua, standard/highlight_conditions/wikis/counterstrike/highlight_conditions.lua
Misc fixes to #4976 and #5035.
Biggest issue is LoL where extradata is set wrong:
Via dev deploy
=> fix(infobox): misc publisher tier and highlight fixes

components/match2/commons/match_group_shorten_bracket.lua
If a Bracket with a set (and filled in) thiord place match is shown with `Template:ShowBracket` in combination with shortening the bracket an error was caused.
This is due to the `match2bracketdata.coordinates` of the third place match not being adjusted.
This PR fixes that by adjusting the coordinates data of the third place match.
=> fix(match2): shortened brackets with 3rd place match erroring

components/match2/wikis/valorant/match_group_input_custom.lua
Function was put in the wrong container
Live
=> fix(match2): typo in MGI on Val

components/widget/match/summary/widget_match_summary_game_team_wrapper.lua
Improves alignment on 18 wikis (arenafps, bs, cod, coc, cf, geo, halo, os, osu, ow, rl, ss, splitgate, tf, tetris, tft, val, wot). The current non-alignment comes when the size of the content on left/right are not the same.
devtools and /dev on geo and val
=> feat(match2): improve centering on match2

components/widget/match/summary/widget_match_summary_game_team_wrapper.lua
Followup to #5068 to improve the styling more.
From:
To:
dev
=> feat(match2): improve match summaries additionally

standard/tier/wikis/brawlhalla/tier_data.lua
D tier isn't used on Brawlhalla so kicking to remove the filter option on the mainpage
live
=> feat(tier): remove unused D-tier from Brawlhalla

components/match2/wikis/apexlegends/match_group_input_custom.lua
Json.stringify in Module:Match fails for apex matches due to a circular reference in the data.
This is caused by setting map.extradata.opponents as just opponents which lua makes just a reference to the original opponents table.
To solve this we need to deepCopy here instead.
Longterm storing opponents additionally in extradata can be skipped once we rely on map.opponents!
live
=> fix(match2): apex with rcircular reference when trying to Json.stringify

components/match2/commons/match_group_display_helper.lua
Remove the strikethrough on "defaults". Only keep it on notplayed.
Feedback from https://discord.com/channels/93055209017729024/1209065403955806270/1303520062531047516 which I resonate with
Before the match summary refactors I believe the only wikis that used the display helper functions were the Craft wikis. So only there there's a negative impact. But they will still display the status text when there was a "default".
=> feat(match2): remove strikethrough on resulttype=default

components/infobox/commons/infobox_team.lua, components/infobox/wikis/ageofempires/infobox_team_custom.lua, components/infobox/wikis/counterstrike/infobox_team_custom.lua
The old implementation was broken at some point and I wasn't sure how to fix it. Instead just made commons set the title correctly whether the player earnings arg was set to true or not.
Removed it from AoE too because again it wasn't working, but also it seems the template on AoE didn't even set the arg to true, idk.
Tested via dev deploy.
=> fix(infobox): correctly abbreviate Approx. Total Winnings or not

components/infobox/commons/infobox_person.lua
Adds param to be called on `Template:Infobox player` to use a default dark mode image alongside a light mode version for the placeholder image on player profiles.
Example: https://liquipedia.net/rainbowsix/index.php?title=Template:Infobox_player&diff=734681&oldid=734675
**Old**
**New**
I can update the template on all wikis that use image placeholders for player photos
live on R6 https://liquipedia.net/rainbowsix/Aziz
=> feat(infobox): add imageDefaultDark on infobox person

components/transfer/commons/transfer_list.lua
as reported on discord transfer list should split transfers if they have different team1_2/team2_2 too
dev
=> feat(transfer): split transfers in transferlist based on team1_2 and team2_2 too

scripts/generate_changelog_local.sh
If a Commit message mentioned another PR than itself, the changelog script would fail. This fixes it by only matching the correct number PR (final) instead of both
=> chore: fix issue with changelog script when there's two PR numbers in the commit

components/squad/commons/squad_custom.lua, components/squad/commons/squad_utils.lua, components/squad/wikis/dota2/squad_custom.lua, components/squad/wikis/overwatch/squad_custom.lua, components/squad/wikis/smash/squad_custom.lua, components/squad/wikis/starcraft/squad_custom.lua, components/squad/wikis/starcraft2/squad_custom.lua, components/squad/wikis/stormgate/squad_custom.lua, components/widget/squad/widget_squad_core.lua, components/widget/squad/widget_squad_core_tldb.lua
It should be called `status`, the input is `status`, the field it stores into is `status`, no idea why it ended up being called `type` in the code. Now that I'm looking at using the `type` field (#5094), it's hightime change the name so it makes sence
2 small changes in SquadAuto is needed `SquadUtils.SquadType.ACTIVE` to `SquadUtils.SquadStatus.ACTIVE`
dev on r6 (auto) and cs (manual)
=> refactor(squad): rename variables from `type` to `status`

components/squad/commons/squad_custom.lua, components/squad/commons/squad_utils.lua, components/squad/wikis/dota2/squad_custom.lua, components/squad/wikis/overwatch/squad_custom.lua, components/squad/wikis/smash/squad_custom.lua, components/squad/wikis/starcraft/squad_custom.lua, components/squad/wikis/starcraft2/squad_custom.lua, components/squad/wikis/stormgate/squad_custom.lua, components/widget/squad/widget_squad_core.lua, components/widget/squad/widget_squad_core_tldb.lua
Add support in Squad Tables to be used for Organizations. This allows for the standardization of org tables. Doing this will allow a significant code simplification of SquadAuto (which currently uses standardized Squad for display of players, while custom table for display of staff). 
This Squad Auto change needs to be put live when this PR is merged.
https://liquipedia.net/commons/index.php?title=Module%3ASquadAuto%2Fdev%2Frath&type=revision&diff=789940&oldid=789920
When this PR is merged, and the SquadAuto change is live, all Auto Org tables will be swapped over to the new. However there's still a significant usage of ManualOrg tables across the wikis, almost all wikis have and use them to some capacity. Apex is also a special case where they got some strange setup. So Manual tables …
=> feat(squad): add support for organization tables

components/squad/commons/squad_row.lua, components/squad/commons/squad_utils.lua
We do not always know the `id` (gamer tag) of org staff. So let's drop that as a requirement, and use either `id` or `name` (realname). 
dev
=> feat(squad): drop the requirement of `id`

components/match2/wikis/clashofclans/get_match_group_copy_paste_wiki.lua, components/match2/wikis/criticalops/get_match_group_copy_paste_wiki.lua, components/match2/wikis/crossfire/get_match_group_copy_paste_wiki.lua, components/match2/wikis/honorofkings/get_match_group_copy_paste_wiki.lua, components/match2/wikis/mobilelegends/get_match_group_copy_paste_wiki.lua, components/match2/wikis/smite/get_match_group_copy_paste_wiki.lua, components/match2/wikis/zula/get_match_group_copy_paste_wiki.lua
Some of the MOBA and other wikis never had one on git, so I'm updating these to match the newest version possible
some might have differences due to its unique per wiki usage, but will try to result in the generated bracket/matchlist remains no different from the old one
- **HOK**: LoL Base, Requires a setup for dynamic ban numbers + |vod= within a map which is the common input pattern on wiki _(note: the vod thing wasnt my addition, another editor adds it yesterday)_
- **MLBB**: use HoK but keep the static 5 bans over dynamic bans
- **SMITE**: already exist, Decrease to only 1 ban input, reflects SMITE 2's 1 ban instead of 5
- **CrossFire and Clash of Clans**: COD Port _(both wikis match2 originally derived from COD base)_
- **Zula**: GOALS Port _(to reflect the standardized setup …
=> feat(match2): Add missing Match Copypaste

components/match2/commons/match_group_legacy.lua, components/match2/wikis/hearthstone/legacy/match_group_legacy_default.lua
Added a new function to legacy to map old rXmY..
Legacy default will only be used to convert solo brackets, team brackets or brackets using RX(DW)Y inputs will be handled on a case-by-case basis.
[8DEBracket](https://liquipedia.net/hearthstone/Stone_League_2015/Season_1/Code_S#Playoffs)
[4SEBracket](https://liquipedia.net/hearthstone/ONOG_Summer_Circuit_Finals#Results)
=> feat(match2): Create hearthstone bracket match1->match2 support

components/match2/wikis/ageofempires/legacy/match_maps_legacy.lua
A lot of LegacySingleMatches have width set, as the default width is too narrow for teams leading to display issues.
live
=> fix(match2): on age of empires, manual width is ignored in Legacy mode

components/notability/commons/notability_checker.lua, components/notability/wikis/ageofempires/notability_checker_config.lua, components/notability/wikis/apexlegends/notability_checker_config.lua, components/notability/wikis/brawlstars/notability_checker_config.lua, components/notability/wikis/halo/notability_checker_config.lua, components/notability/wikis/pubgmobile/notability_checker_config.lua, components/notability/wikis/rainbowsix/notability_checker_config.lua, components/notability/wikis/rocketleague/notability_checker_config.lua, components/notability/wikis/trackmania/notability_checker_config.lua
- use `opponentplayers` over `players` in condition building
- kick `players` in the query due to it not being used anywhere
untested
=> refactor(notability): use standardized fields over deprecated fields

components/match2/commons/brkts_wiki_specific_base.lua, components/match2/wikis/rocketleague/brkts_wiki_specific.lua
There's no usage of this field
=> chore(match2): remove unused defaultIcon

spec/date_ext_spec.lua, standard/date_ext.lua
On Overwatch they have a form that uses date picker with time (in addition to the date).
Form passes the dateTime as `YYYY-MM-DDTHH:mm:ss.ssssZ` (e.g. `2024-11-24T15:38:01.999Z`) to the template/module.
Hence it results in DateExt.readTimestamp erroring.
This PR adds support to also parse such dateTime strings so we can support date picker with dateTime in forms properly with standardized modules.
dev
=> feat: support more date inputs

components/infobox/wikis/rocketleague/infobox_league_custom.lua
Originally only supported the `team_number` arg for team tournaments, extend to the `player_number` arg for individual tournaments
/dev
=> feat(infobox): Show participant count in individual tournament infoboxes on RL

javascript/commons/BattleRoyale.js
There was a bug causing the game panels to be append to the wrong container when there were more battle royales on one page. The query is adjusted to grabbing the br instance instead of the global document.
Live and on dev wiki
https://liquipedia.net/apexlegends/FFL/REBOOT_6
http://laura.wiki.tldev.eu/rocketleague/Apex
=> fix(match2): BattleRoyale loading panels in wrong container when there's multiple

components/infobox/commons/infobox_league.lua
Currently the accommodation button is set to only display in events with one single venue. We propose to also display it for events with multiple venues in the same city, adjusting the URL to only account for city + country input, disregarding the venue input.
/dev
=> feat(infobox): show the stay22 accommodation button on events with multiple venues in same city

components/match2/wikis/honorofkings/get_match_group_copy_paste_wiki.lua
(the bracketdata error is unrelated)
LIVE, Form now adjusted to have MVP fields which is missing in Bracket Paste but is exist in Matchlist Paste
=> feat(match2): Add MVP to copypaste for HoK

components/match2/wikis/starcraft/legacy/match_group_legacy_default.lua, components/match2/wikis/starcraft/legacy/match_maps_legacy.lua, components/match2/wikis/starcraft2/legacy/match_group_legacy_default.lua, components/match2/wikis/starcraft2/legacy/match_maps_legacy.lua, components/match2/wikis/starcraft2/legacy/match_maps_team_legacy.lua
Was lost due to the refactors.
Mind as currently enuaj is converting all the pages that use legacy wrapper to use the new input we will probably be able to kick these modules completely in some months (hence not bothering with annos)
dev
=> feat(match2): add vodgameX support in sc(2) legacy wrappers

components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua, components/match2/wikis/starcraft2/legacy/match_maps_team_legacy.lua, components/match2/wikis/warcraft/match_group_util_custom.lua
- Add a nil catch in sc(2) & stoirmgate matchGroupUtil customs
- pass along game index in an edge case on sc2 team match maps legacy wrapper
live
=> fix(match2): missing nil catch, missing passalong on sc and sg

components/match2/wikis/dota2/match_page_template.lua, components/match2/wikis/leagueoflegends/match_page_template.lua
Business asks us to add it to all existing LOL pages as they are all powered by SAP.
dev
=> feat(match2): add SAP logo to LoL's match pages

components/match2/wikis/hearthstone/get_match_group_copy_paste_wiki.lua, components/match2/wikis/hearthstone/legacy/match_group_legacy_default.lua, components/match2/wikis/hearthstone/match_group_input_custom.lua, components/match2/wikis/hearthstone/match_summary.lua
Add support for team players in hearthstone.
The input for class was changed from `oXpY` to `oXcY` this will require a bot run to fix match2 inputs. `oXpY`will be used for player input in team games.
/dev and [sandbox](https://liquipedia.net/hearthstone/User:LuckeLucky/sandbox)
=> feat(match2): Support team players in hearthstone

components/match2/wikis/hearthstone/legacy/match_maps_legacy.lua
Added the MatchMaps legacy wrapper.
/live on some pages:
* [MatchList](https://liquipedia.net/hearthstone/2014_Hearthstone_World_Championship#Group_Stage)
* [MatchListStart](https://liquipedia.net/hearthstone/DreamHack/2017/Atlanta/Round_8_to_9)
=> feat(match2): Add MatchMaps m1 -> m2 support for hearthstone

components/match2/wikis/hearthstone/match_summary.lua
If player class is empty don't build the class icon.
/dev
=> fix(match2): Don't try to build class icon if is empty on hearthstone

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua, components/match2/wikis/stormgate/match_group_input_custom.lua, components/match2/wikis/warcraft/match_group_input_custom.lua
in team matches not always the first player is set
hence throw an array.filter on the players array to get the set player
dev to live
=> fix(match2): extradata for 1v1 maps in team matches incomplete on craft wikis

components/match2/wikis/ageofempires/match_group_input_custom.lua, components/match2/wikis/ageofempires/match_legacy.lua, components/match2/wikis/ageofempires/match_summary.lua
Makes #5120 obsolete after a purge run
dev
opponent data now filled with empty tables:
Normal game with not every player from TC playing:
not played game:
=> feat(match2): Use parseMapPlayers on AoE

components/match2/commons/match_group_input_util.lua
Always use AutoScore if available. Mainly so that bonus/penelties are shown before the first game starts.
/dev
=> feat(match2): always set score on BR/FFA matches, even on upcoming matches

standard/info/wikis/ageofempires/info.lua, standard/info/wikis/hearthstone/info.lua, standard/info/wikis/smite/info.lua
All of this wikis have match2 or match2 and wrappers in m1 brackets/matchlists (this doesn't include ffa stuff)
=> chore: Update match2 status on some wikis

stylesheets/commons/BattleRoyale/PanelTable.less
When the components were standardized between game overview and match/game summary, one css ended up incorrectly. This meant that everything was center-aligned, instead of the correct alignement.
dev tools
=> fix(match2): alignement of column content on BR

stylesheets/commons/BattleRoyale/PanelTable.less
For some weird reason it works in chrome by removing `-x` from overflow...
Live and dev wiki
https://liquipedia.net/apexlegends/Octane_Collegiate/Season_2/Stage_2/Playoffs
Closes https://gitlab.com/teamliquid-dev/liquipedia/issue-bucket/-/issues/142
=> feat(match2): BR/FFA Sidescrolling behavior not working properly on chrome

javascript/commons/BattleRoyale.js
Since the new BR changes, we insert game-related data only on click. However, countdowns are not being shown on game-specific tabs since they need to be initialized.
This triggers the init flow for countdowns to take into account the new ones. This is what it looks like in a future game:
Double checked with Kano, the result is as expected.
Ran `liquipedia.countdown.init()` in the console on [this page](https://liquipedia.net/apexlegends/Apex_Legends_Global_Series/2024/Championship/Bracket_Stage).
Then updated the script and tested it in the console as well on the same page.
=> fix(match2): Game Tab countdowns are not working

components/match2/commons/match_group_input.lua
If the match comes from ShowBracket then it's opponents, otherwise it's match2opponents
Which is stupid, and needs to be same in the future.
Add a comment sayign the same.
live
=> fix(match2): error when using ShowBracket

javascript/commons/BattleRoyale.js
Since we load game tabs using transclusion, we need to retrigger the sorting arrow hydration so they can work.
In the console for [this page](https://liquipedia.net/apexlegends/BLGS/2024/Qualifier_3/APAC_North/Bracket) + by updating the commons file & mediawiki message article
=> fix(match2): sorting on (ffa) game tabs

stylesheets/commons/BattleRoyale/NavigationTabs.less, stylesheets/commons/BattleRoyale/Panel.less, stylesheets/commons/BattleRoyale/PanelTable.less
This MR updates the colors for Battle Royale on Lakesideview wikis. Way back when we created BR there was never a dark theme design so that's why we need to update it now.
On the live site, for example https://liquipedia.net/apexlegends/BLGS/2024/Qualifier_3/APAC_North/Bracket
https://gitlab.com/teamliquid-dev/liquipedia/issue-bucket/-/issues/159
=> feat(match2): support light/dark theme for BR display

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft_ffa.lua
remove the temp workaround after fixing all usages
N/A
=> chore(match2): remove temp workaround after cleanup

components/hidden_data_box/wikis/dota2/hidden_data_box_custom.lua, components/infobox/wikis/dota2/infobox_league_custom.lua
currently dota2 sets the wiki variable manually but still has the input in the infobox (currently doing nothing)
this also leads to it not working on subpages and match pages
this pr adds the storage in lpdb and wiki variable of headtohead in infobox league and support in hiddenDataBox
basically the initial report: https://discord.com/channels/93055209017729024/372075546231832576/1317925849491570800
dev
=> feat: enable headtohead storage and wiki variable on dota2

javascript/commons/Miscellaneous.js
This makes sure the WC3 wiki does not load in bruinen scripts when the lakesideview beta is enabled
dev tools
=> fix: Load scripts from current skin for WC3 creep spots

components/opponent/wikis/stormgate/player_display_custom.lua, components/opponent/wikis/warcraft/player_display_custom.lua
set the title in the faction image so that css grabs them and makes them white for darkmode
dev tools
=> feat(opponent): support faction darkmode icons on SG and WC

components/match2/wikis/ageofempires/match_legacy.lua
Misread that the player handling code isn't in its own function, so upon empty player the entire team handling would be stopped.
Live
=> fix(match2): Prevent premature return in match legacy on AoE

components/match2/wikis/warcraft/legacy/match_group_legacy_convert_map_data.lua
the removed line is not needed anyways ...
reported on discord by kover: https://discord.com/channels/93055209017729024/372075546231832576/1317177083117699083
dev to live
=> fix(match2): warcraft legacyBrackets erroring on map walkovers

components/statistics/count.lua, components/statistics/portal_statistics.lua
The query variant that fetches match2.match2games would run out of memory on AoE: https://liquipedia.net/ageofempires/Portal:Statistics, so instead directly count match2games instead. Not sure why this wasn't done immediately.
Issue surfaced due to change of match2 status.
dev
=> feat(statistics): improve game stats performance

components/widget/match/summary/widget_match_summary_game_comment.lua
reported on discord: https://discord.com/channels/93055209017729024/372075546231832576/1317037207072149535
- long came comments overflow the MS box
- adjust the max-width of game comments to 100% so that they do not overflow anymore
dev
=> fix(match2): GameComment overflowing matchsummary box

.github/workflows/deploy test.yml, .github/workflows/deploy.yml, .github/workflows/scheduled.yml, scripts/deploy.sh, scripts/deploy_res.sh
This changes the deploy scripts to use a bot password.
Closes https://github.com/Liquipedia/Lua-Modules/issues/5169
I tested locally if I can log in with a bot password in this way.
:warning: **CAUTION**: The variables for the dev deploys have not been set up yet, Nadox and Darkrai should set these up. Values for live deploy exist already.
=> ci(deploy): change deploy to use a bot password

stylesheets/commons/BattleRoyale/PanelTable.less
Add dark theme bg color to arrow navigation in table.
Live, for example https://liquipedia.net/apexlegends/BLGS/2024/Regional_Finals/APAC_South
=> feat(match2): Add dark theme support for BR table navigation

components/match2/wikis/marvelrivals/get_match_group_copy_paste_wiki.lua, components/match2/wikis/marvelrivals/match_group_input_custom.lua, components/match2/wikis/marvelrivals/match_summary.lua, standard/info/wikis/marvelrivals/info.lua
New Wiki: Marvel Rivals
the game is basically Overwatch but Marvel, however the Match2 port here starts with clean COD wiki port with no changes outside removing Mode icon calls for now, because the game has multiple modes, but doesnt have mode icons in the game. (Fortunately no one map is played on two modes)
**Includes Info module as well**
https://liquipedia.net/marvelrivals/User:Hesketh2/Match2_Test
=> feat(match2): Support for Marvel Rivals

stylesheets/commons/BattleRoyale/PanelTable.less
In this MR:
- remove the background-color for kills column (removing it didn't change anything afaik) 
- change the variable for the placement column
Dark theme
Light theme
Bruinen
Devtools
=> feat(match2): Adjust background color for placement and kills

components/match2/commons/match_group_util.lua, components/match2/wikis/ageofempires/match_summary.lua
waiting for purge run to finish (to make sure gameOpponent.status is populated)
Adjust the condition on which the map is not shown to check for non empty opponents data.
That way for set players but unset winner and unset map it would still display the row.
While at it also converted resulttype check to status check (the default win is auto checked via opponents data not being empty/winner being set)
Requested/reported in the aoe discord channel: https://discord.com/channels/93055209017729024/717412628330446929/1319422214306529352
dev on https://liquipedia.net/ageofempires/User:SyntacticSalt/Sandbox/2
=> feat(match2): show mapRow for set players but missing winner/map on aoe

standard/links/wikis/counterstrike/links_custom_data.lua, standard/links/wikis/overwatch/links_custom_data.lua
Due to them changing their web app navigator, the empty URL bits were breaking links. Hyphens work as before now.
Pushed live for CS wiki as just data.
=> feat(infobox): update FACEIT League links to match new format

components/match_ticker/commons/match_ticker_display_components_new.lua
Currently the new match ticker shows streams on finished matches.
That seems pretty useless.
This PR adjusts the matchticker so that it now shows vods for finished matches instead
reported on discord: https://discord.com/channels/93055209017729024/372075546231832576/1320177660638531594
dev
before:
after:
=> feat(matchticker): show vods on finished matches

components/infobox/extensions/wikis/stormgate/infobox_extension_attack.lua
Allow attacks to have multiple bonus damage instances with different bonus damage values. 
Examples for units with multiple bonus damage instances (dev-mode):
- https://liquipedia.net/stormgate/Lancer
- https://liquipedia.net/stormgate/SCOUT
Example for unit with just one bonus damage instance (dev-mode):
- https://liquipedia.net/stormgate/Saber 
dev tools
=> feat(Infobox): on stormgate, allow attacks to have multiple bonus damage instances

standard/info/wikis/smite/info.lua
(set to 180)
for whatever reason SMITE team name is pretty longer than usual and default width often eclipsed through the names which isnt good looking, 180 will help with the majority of the wiki
=> feat: increase match card widths for SMITE

components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua, components/match2/commons/starcraft_starcraft2/match_summary_starcraft.lua
- store the isarchon on mapOpponent level
- standardize the stored value on (match-) opponent level (i.e. use readBool)
- pass the isArchon bool to the opponent display
live
=> fix(match2): Archon submatches in team matches not displaying properly

components/main_page/commons/main_page_layout.lua, components/main_page/wikis/dota2/main_page_layout_data.lua, components/main_page/wikis/rainbowsix/main_page_layout_data.lua, definitions/mw.lua
Move the full mainpage into the module, instead of just the content
This adds the follow func, in addition to the full stucture.
* Display Title
* Metadesc
* Header Banner (still calls external template)
* Navigation Cards (changed from template & varies queries for counting into Lua)
/dev on R6
=> feat(mainpage): standardize handling of navigation cards

components/match2/wikis/fortnite/match_group_input_custom.lua, components/match2/wikis/fortnite/match_summary.lua
I want it like how TFT is able to display both Brackets and Battle Royale together. So like #5196 in reverse
I'm starting with using TFT's setup as basis, because I never edit BR-related match2 yet
things like `OPPONENT_CONFIG` on matchFunctions is carried from FN's current setup
FN doesnt really have a strict default mode **(FOR BR),** they changed pretty regularly `(e.g. Duos in 2024, but Trios in 2025)` after talking to hjp I've come to a decision to left it unset for BR
DEV https://liquipedia.net/fortnite/User:Hesketh2/Test
**Test includes putting both BR and Bracket on same page with same dev on both**
=> feat(match2): Add non-BR support for Fortnite

stylesheets/commons/Prizepooltable.less
currently:
- for win/lose the ppt in the new skin displays the entire row with complete bg
- for lose it only does so every 2nd row
with this PR:
- the display mirrors the way normal place colors (gold, silver, bronze, copper) are applied in ppt
- for lose it is irrelevant if it is an even or odd row
=> feat(prizepool): make ppt display behavour of win and lose similar to other placements

components/match2/commons/match_group_input_util.lua, components/match2/commons/starcraft_starcraft2/match_group_input_starcraft.lua, components/match2/wikis/ageofempires/match_group_input_custom.lua, components/match2/wikis/artifact/match_group_input_custom.lua, components/match2/wikis/brawlhalla/match_group_input_custom.lua, components/match2/wikis/brawlstars/match_group_input_custom.lua, components/match2/wikis/clashroyale/match_group_input_custom.lua, components/match2/wikis/deadlock/match_group_input_custom.lua, components/match2/wikis/fighters/match_group_input_custom.lua, components/match2/wikis/hearthstone/match_group_input_custom.lua, components/match2/wikis/heroes/match_group_input_custom.lua, components/match2/wikis/honorofkings/get_match_group_copy_paste_wiki.lua, components/match2/wikis/honorofkings/match_group_input_custom.lua, components/match2/wikis/magic/match_group_input_custom.lua, components/match2/wikis/omegastrikers/match_group_input_custom.lua, components/match2/wikis/paladins/match_group_input_custom.lua, components/match2/wikis/pokemon/match_group_input_custom.lua, components/match2/wikis/smash/match_group_input_custom.lua, components/match2/wikis/smite/match_group_input_custom.lua, components/match2/wikis/splatoon/match_group_input_custom.lua, components/match2/wikis/stormgate/match_group_input_custom.lua, components/match2/wikis/tetris/match_group_input_custom.lua, components/match2/wikis/tft/match_group_input_custom.lua, components/match2/wikis/warcraft/match_group_input_custom.lua, components/match2/wikis/wildrift/match_group_input_custom.lua, components/match2/wikis/worldofwarcraft/match_group_input_custom.lua
- suppress an anno warning that annoyed me while checking on these issues
- account for party types while processing map player data on fighters (basically copied from smash)
- fix finished handling on brawlstars and omegastrikers which needs to come after the opponent processing and needs the opponents passed
- mind other wikis rely on finished processing being done before the opponent processing, hence introduced the option to recalculate finished after the opponent processing
- fix nil error on clashroyale
dev
=> fix(match2): several issues from #5210

components/match2/commons/match_group_util.lua, components/widget/match/summary/ffa/widget_match_summary_ffa_game_countdown.lua
Currently in BR/FFA display, we display the datetime regardless of its accuracy. Add support so that it won't display a date that epoch-default. 
Additionally, also make it not show the hour/min for estimated dates.
dev
=> feat(match2): don't show countdowns for empty dates on FFA/BR

components/infobox/wikis/marvelrivals/infobox_character_custom.lua
New Wiki, Character Infobox
Used Deadlock's character infobox as basis with some parameters to fit the details provided inside the game
https://liquipedia.net/marvelrivals/Iron_Man 
Updated
=> feat(Infobox): add Character for Marvel Rivals

components/infobox/wikis/stormgate/infobox_building_custom.lua, components/infobox/wikis/stormgate/infobox_unit_custom.lua
From what we know about the Team Mayhem mode (3v3) and what they said in blog posts, AMAs and interviews it’s pretty safe to assume, that heroes in Co-op and Team Mayhem and possibly their units can significantly different from each other. Currently the unit and building infobox doesn't support this properly. 
This pr updates the input for `|subfaction=` that it supports inputs like `|subfaction=1v1, coop:Blockade;Amara;Ryker, mayhem:Blockade` (example)
The output in the infobox (subheader) will look like this:
dev tools
**Note:** this will need some follow-up changes for hero pages and subfaction units and will even break a few pages there that I need to fix/update once the pr is merged.
=> feat(Infobox): Update unit and building infobox regarding subfaction data

components/match2/commons/match_group_util.lua, definitions/liquipedia_db.lua
`opponnets` vs `opponents`
dev into live
=> fix(match2): typo in record parsing

components/match2/wikis/tft/match_legacy.lua
Match Legacy support so M1 querying stuff works
Live
https://liquipedia.net/tft/Liquipedia:Upcoming_and_ongoing_matches_on_mainpage/dynamic
=> feat(match2): create m2->m1 mapping for tft

components/match2/commons/match_summary_base.lua
When not all maps have a specific link added, the link table is not a real array so needs to be iterated with pairs, not ipairs
dev
=> fix(match2): handle game links with interruptions

components/infobox/wikis/starcraft/infobox_person_player_custom.lua, components/infobox/wikis/starcraft2/infobox_person_player_custom.lua, components/match2/wikis/clashroyale/match_summary.lua
Remove the remaining usage of deprecated match2/match2game fields.
- CR (missed in #5229)
- sc/sc2 query condition in infobox player
dev
=> chore(match2): Remove the remaining usage of deprecated match2/match2game fields

components/match2/wikis/fortnite/get_match_group_copy_paste_wiki.lua
Following #5244 (non BR support) is added, the Match Generator module and forms needs to be revisited in order to make it support both
per rath's suggestion I took the base from Arena FPS and mix with the old one 
I don't know how to do /dev tests on these so I just update it right into the Live version
**>2 OP**
**<= 2 OP**
PUBG Mobile will also get the same treatment, after this gets merged I'll use this as base
=> feat(match2): Bracket support for Fortnite copypaste

components/match2/commons/match_group_util.lua
- bo1 match
- one team gets DQed after the map is played
- in display it displays the map score of the played map instead of the match walkover
- desired behaviour: match walkover gets displayed
reported by @iMarbot 
https://discord.com/channels/93055209017729024/372075546231832576/1325273961428287518
dev
before:
after:
=> feat(match2): do not apply bo1 display if there is a match walkover

standard/tier/wikis/dota2/tier_data.lua
We have been using the custom "national" tier on the Dota 2 wiki Tier Data module for the past year, but it looks like this change was never pushed on GitHub. Liquipediabot has been undoing the changes recently to sync with the main repo. So I thought I'd have a go at fixing it myself. 
I don't use GitHub and this is my first PR so yell at me on #Gravy3776 if I've done something wrong )
The additional tier type was previously used on the Dota 2 wiki and works fine. 
edit: sorry I forgot a curly bracket
=> feat: add national tiertype on dota2

components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua, components/match2/wikis/stormgate/match_group_util_custom.lua, components/match2/wikis/warcraft/match_group_util_custom.lua
On SC(2), WC and SG team matches error on empty map input due to a missing nil catch in the check if the map begins with `'Submatch'`.
This PR adds the missing nil catch on the 3 wikis
=> fix(match2): missing nil catch in submatch check

components/country_representation/commons/country_representation.lua
- Cleaner Code
- kicks `maxPlayers` in fav of using `Table.iter.pairsByPrefix`, hence we can kick 20 custom template overwrites
"live" (module unused so far) preview tests on 5 wikis
- adjust commons template
- adjust wiki custom template overwrites (diff from commons: `noCountry` has a default value set) on
- val 
- lol
- brawlstars
- wildrift
- wot
- geoguessr
- kick wiki custom template overwrites to archive on
- dota2
- rl
- ml
- r6
- ow
- pubg
- crossfire
- osu
- stormgate
- trackmania
- fortnite
- pokemon
- tft
- halo
- clashroyale
- sideswipe
- splatoon
- naraka
- splitgate
- marvelrivals
- kick the old module to archive
- bot jobs across all wikis to clean up `noCountry` and `staff` usage so we can just read them as bools:
```bash
#!/bin/bash
cd /home/hjpalpha
wikis=($(python …
```
=> feat: standardize CountryRepresentation

.github/workflows/deploy test.yml, .github/workflows/deploy.yml, .github/workflows/scheduled.yml, scripts/deploy.sh, scripts/deploy_res.sh
This re-adds the botpassword usage after having previously been undone due to missing support for editing admin protected pages. Admin protected pages can now be edited by bots.
=> ci(deploy): change deploy to use a bot password (#5209)

components/match2/wikis/warcraft/match_group_input_custom.lua
Tried to call `MatchFunctions.placementHasBeenSet` which does not exist as it is a function for the ffa match and hence needs to call `FfaMatchFunctions.placementHasBeenSet` instead
live
=> fix(match2): wrong table used to call function from on wc3

components/infobox/wikis/counterstrike/infobox_league_custom.lua
Only the highlighted tournaments are valve sponsored, so using that to determine category too.
=> feat(infobox): use highlight conditions to determine sponsored category on CS

components/match_ticker/commons/match_ticker_display_components_new.lua
Some games are not PARTICIPANT vs PARTICIPANT, but rather 3 or more. This is most common in Battle Royale and other FFA game styles, but also in the common format with 4-participant Trackmania matches. 
The Match Ticker currently only have a PARTICIPANT vs PARTICIPANT display. A new display variant for 3+ Participants matches needs to be added.
This adds basic DISPLAY support for FFA/BR matches in the new style match ticker
For full (BR) support, game based displays are needed as well, which will be another ticket
https://liquipedia.net/apexlegends/User:Rathoz
=> feat: support FFA/BR events in Match Ticker

stylesheets/commons/Brackets.less, stylesheets/commons/OpponentList.less
Currently in darkmode the opponent hovers are very hard to see.
This PR changes the color used for opponent hover in darkmode from black to white. Opacity etc stays the same
browser dev tools & after that pushed to live
before:
after:
=> feat: Opponent-hover darkmode support

standard/links/commons/links.lua
The previous base url was made for personnal accounts but for companies it is `.com/company/name` and not `.com/in/name`.
=> feat: support LinkedIn team links

stylesheets/commons/Infobox.less
Smash infoboxes are colored depending on which game is entered in the infobox. This PR makes them dark-mode compatible. 
Example of just one of the changes 
**Before**
**After**
Inspect tool
=> feat: make Smash infobox colors dark-mode compatible

components/match2/wikis/fighters/get_match_group_copy_paste_wiki.lua
Fighters' match generators do not include map score parameters (that correspond to round scores of actual game) in the copy-paste output. This PR adds it.
dev
=> feat(match2): Include round scores in fighters generators

components/match2/commons/match_group_input_util.lua, components/match2/wikis/valorant/match_group_input_custom.lua
Seemed like the easiest way to mitigate the issues occuring on valorant, where transfer dates are based on the official announcement and often vary from actual date.
Other option would be to first check all maps of a match, extract player input, and override the date variables to include the matchdate in the custom(s).
Let me know what you'd prefer.
dev
=> feat(match2) Allow to disregard transfer dates for players of team

components/match_table/commons/match_table.lua
currently in some edge cases matchTable doesn't retrieve the wanted matches.
mentioned on discord: https://discord.com/channels/93055209017729024/268719633366777856/1309935673842864129
cause of this:
- matchTable retrieves the page names from (historical) TeamTemplate(s)
- there exists a (page) redirect from (at least) one of the pages set in the team template to a page that is not among the pages listed in the team templates
- the match stores them redirect resolved
- hence the condition will never meet what is stored in matches
This PR makes it so that conditions in matchTable gets adjusted so that it also checks for resolve redirected versions.
dev
=> feat(matchTable): support redirected pages that are not set in the team templates

components/match_ticker/commons/match_ticker.lua, components/tournament/tournament.lua
For the components on the new main page usng filters (Match Ticker & Tournament Ticker), needs to have support for Region filters.
Region filters is used by many big wikis, such as LoL and RL.
https://liquipedia.net/leagueoflegends/User:ElectricalBoy/Sandbox3
=> feat: create "region" filter for new main pages

components/match2/wikis/leagueoflegends/get_match_group_copy_paste_wiki.lua
- Fixed bug where `reddit` (extra parameters) input in form no longer makes a difference as to whether the reddit parameters are generated
- Added such that `|patch` and `|bestof` are included by default in each `{{Match}}`
- Added functionality to allow for matchcode to not be fully generated if BigMatch should be used for this particular matchlist.
/dev
=> feat(match2): add more options on LoL copy-paste generator

components/filter_buttons/wikis/pubg/filter_buttons_config.lua, components/main_page/wikis/pubg/main_page_layout_data.lua, stylesheets/commons/Banner.less
_Depends on #5295, #5296_
This PR standardizes main page layout of PUBG wiki.
- Sandbox: <https://liquipedia.net/pubg/User:ElectricalBoy/MainPage>
=> feat(mainpage): Standardize PUBG main page

standard/date_ext.lua
mw.getContentLanguage():formatDate is a relative expensive call, in the sense it can be called a lot, and it does cost a bit everytime. 
https://liquipedia.net/commons/Module:Perf/Date
100k prev = 1.2-1.6s 
100k mem = 0.007s
=> perf: memoize getCurrentTimestamp

components/match_ticker/commons/match_ticker.lua
Improves memory performance of the match ticker, and also ensures that it will always find results (well, limiting it to 20 queries)
Functionally works.
Is more efficient when it comes to post filters (can actually retrieve all matches up to limit). And does that without breaking the memory bank.
As example, just as efficient on all wikis. With a region filter with which exists 45 matches in the future of on LoL, new version could find them all, while existing version only fetched 35.
=> perf: improve memory performance of match ticker

components/main_page/wikis/leagueoflegends/main_page_layout_data.lua, components/main_page/wikis/pubgmobile/main_page_layout_data.lua
kick space that causes main page to be in the `pages with hard coded colors` cat
N/A
=> chore: fix false positive hard-coded color

components/filter_buttons/filter_buttons.lua, components/match_ticker/commons/match_ticker.lua, components/tournament/tournament.lua, components/widget/tournaments/widget_tournaments_ticker.lua, standard/i18n_data.lua
Adds the curated option for FilterButtons, and for MatchTicker to only show matches from curated tournaments. 
Needed for Counterstrike's new main Page.
While it doesn't have a strict dependecy on any other PR, #5320, #5321 and #5322 should preferably be merged first for performance reasons.
The following templates needs to be updated at merge from their dev/rath version.
https://liquipedia.net/commons/Template:MainPageMatches/Upcoming
https://liquipedia.net/commons/Template:MainPageMatches/Completed
TournamentTicker on [CS](https://liquipedia.net/counterstrike/User:Rathoz)
MatchTicker on [CS](https://liquipedia.net/counterstrike/User:Rathoz), [SC2](https://liquipedia.net/starcraft2/User:Rathoz)
MatchTicker player On [SC2](https://liquipedia.net/starcraft2/HerO_(Kim_Joon_Ho)) (in preview)
=> feat: support for the curated option for the new main pages

components/components/filter_buttons/wikis/deadlock/filter_buttons_config.lua, components/main_page/wikis/deadlock/main_page_layout_data.lua, stylesheets/commons/Banner.less
Setting up the data for the Deadlock Mainpage revamp:
https://liquipedia.net/deadlock/User:Kanoodles/TestTest
=> feat: new mainpage for deadlock

.github/workflows/deploy.yml, .github/workflows/scheduled.yml, scripts/deploy.sh
The dev deploy hasn't been working for >6 months now. Since no steps have been taken to fix it, as there seems to been no need for it. Removing it as it's erroring our deploy pipelines.
=> ci(deploy): remove deploy to dev-wikis

components/standings/commons/standings.lua, components/widget/standings/widget_standings_ffa.lua
Use "started", which currently means that the last previous round has ended, to determine when to update "Current". This matches the old behavior. Will be tweaked in the future as we go further in the project, when a "sdate" is introduced in addition to the "edate" (or maybe replacing entirely). 
dev -> live
=> feat: change standings to look on started rather than finished to determine rounds to show

components/standings/commons/standings.lua, components/standings/commons/standings_storage.lua
Store and load standings into wiki-vars also, so a standing table can be rendered even if LPDB data is turned off.
dev
=> feat: save/load standings via wiki-vars in addition to lpdb

components/match_table/commons/match_table.lua
Somewhat regularly an error with the match is reported (e.g. https://discord.com/channels/93055209017729024/372075546231832576/1330180220174729287)
This is related to an un-/partially supported timezone, so to make the error message more descriptive display the TZ in the error message.
dev
=> feat: throw proper error on unsupported TZ in the match table

components/infobox/wikis/stormgate/infobox_item_custom.lua
This would be the first version of a custom item infobox for stormgate which would feature hero gear for coop so far. When more item types are brought into the game it can be extended. 
Examples of two random infoboxes created this way:
dev tools (https://liquipedia.net/stormgate/Module:Infobox/Item/Custom/dev/senti)
=> feat(infobox): create custom item infobox for stormgate

components/infobox/wikis/stormgate/infobox_building_custom.lua, components/infobox/wikis/stormgate/infobox_unit_custom.lua, standard/icon_data.lua
Small follow-up pr to https://github.com/Liquipedia/Lua-Modules/pull/5263 regarding
* adding font awesome icons to represent Co-op and Team Mayhem on Unit Infobox
* adding font awesome icons to represent Co-op and Team Mayhem on Building Infobox
Small changes to appearance of Unit and Building Infobox, especially:
* adding speed to Buildings Infobox (no storage)
dev-tools
=> feat(Infobox): Update unit and building infobox on stormgate regarding subfaction data (part 2)

components/match2/wikis/dota2/match_page_template.lua, components/match2/wikis/leagueoflegends/match_page_template.lua
resolves #5346
add the vodlink class to the div wrapper that is around the icons so they get inverted in darkmode
alternative solution would be to append both used classes at
https://github.com/Liquipedia/Lua-Modules/blob/710b7b9f133a431bb0c83d9e8d32b86697945ac5/stylesheets/commons/Miscellaneous.less#L2211-L2212
=> feat(match2): add darkmode support to link icons on matchPages

spec/flags_spec.lua, standard/flags.lua
As part of the Flag cleanup, remove the subtemplate fallback in flags handling. Instead display a simple warning.
Removed the special case for "File:Space filler flag.png", instead tweaked the code to have almost the same behaviour (but slightly better - will add a link if there's one).
Auto tests
=> feat(standard): remove template fallback in flags

components/standings/commons/standings.lua, components/standings/commons/standings_parse_wiki.lua, components/standings/commons/standings_parser.lua, components/standings/commons/standings_storage.lua, components/standings/commons/standings_table.lua, components/widget/standings/widget_standings_ffa.lua
Next step in the FFA standings standardization process. With this, it can replace the existing FFA tables on Apex for future tournaments.
The next step after this are automation and legacy input parser.
https://liquipedia.net/apexlegends/User:Kanoodles/RathTest by Kano
=> feat: standardize ffa standings parsing

components/main_page/wikis/leagueoflegends/main_page_layout_data.lua
LoL mainpage had a news navcard and a statistics navcard, both of which were unintentionally omitted in #5302. This PR restores the two.
dev
=> feat(mainpage): Add news and stats navcards to LoL mainpage

components/match2/wikis/easportsfc/match_summary.lua
currently `CustomMatchSummary._extractPlayersFromGame` just maps all game players, including the empty (aka not played) ones
this pr adds a check (1 line) that the according player actually played the map
dev
=> fix(match2): all players shown in each game on fifa team games

standard/flags_master_data.lua
Add [Latin American Flag](https://liquipedia.net/commons/Template:Flag/latin_america) to Module:Flag
=> feat: add Latin America flag

components/match_table/commons/match_table.lua
Some wikis (i.e. AoE) display some recent matches on a player's main page, and then a full list of matches on a subpage.
This adds the option to link to such a subpage, similar to the ResultsTable (when showing achievements).
The name of the subpage itself is hardcoded, as that is also already done in case of the year-range subpages.
dev
=> feat: Add option to link to a subpage in match table

components/match_table/commons/match_table.lua
When compared with the match1 matchtable, this version used drastically more Lua memory.
To be able to still render most pages, limit the batch size in Lpdb::executeMassQuery.
dev
=> fix: Set batch limit when querying in match table

stylesheets/commons/Colours.less
The current var for `bg-first` is unreadable in darkmode so this switches to a more readable version. I'm not sure if this is the intended use case for `achievement-placement-1` but it looks good IMO. The attached images display the PR's changes via the "First" text. You can see what the current version is here: https://liquipedia.net/commons/Template:Bgcolortext
inspect tools
=> feat: change var for bg-first

components/standings/commons/standings_parse_lpdb.lua, components/standings/commons/standings_parse_wiki.lua, components/standings/commons/standings_parser.lua, components/standings/commons/standings_table.lua, standard/lpdb.lua
This is the third step in that journey, in this step we build the first new feature, automatically fetching data from matches, so that contributors no longer need to enter information manually
Matches should be moved into the rounds. Should be able to support one match, multiple matches or one or more matchgroups as input.
Having the old `|matches=` input in the outer layer still needs to be support for manual tables. 
```
{{FfaStandings|title=League Standings
|bg=1-10=stay, 11-20=down
|round1={{Round|title=A vs B|started=true|finished=false|matches=glCe2PeAfD_0001}}
<more rounds>
|{{TeamOpponent|dreamfire}}
<more opponents>
}}
```
- For example, 25points for 1st place, 20 points for 2nd place etc in a match, instead of the score granted.
https://liquipedia.net/apexlegends/User:Rathoz
=> feat: automatically import ffa standings from matches

components/standings/commons/standings.lua, components/standings/commons/standings_parse_lpdb.lua, components/standings/commons/standings_table.lua
Import param being reversed in logic
Add some error handling for when there are 
* No opponents 
* Import is enabled, but no matches are entered for a round
Partially live
=> fix: error handling and typo on ffa standings

components/match2/wikis/trackmania/brkts_wiki_specific.lua
matchlists can not display >2 opponents, hence if there are >2 opponents it doesn't make sense to display it as a matchlist at all
hence for `maxOpponentCount > 2 and matchGroupType == 'matchlist'` use ffa display
not tested but change is super simple ...
=> feat(match2): show ffa display if > 2 opponents and matchlist on trackmania

standard/info/wikis/worldoftanks/info.lua
We plan to focus exclusively on World of Tanks and Mir Tankov in the worldoftanks section. This PR aims to remove unused games (World of Tanks Blitz and Blitz) that were mistakenly added.
I've noticed those unused games appearing when using the `PortalStatistics` functions, such as `coverageStatistics` and `pieChartBreakdown`. These functions aren't working properly either, but that's a separate issue.
=> feat: remove of unused games for worldoftanks

standard/tier/wikis/halo/tier_data.lua
The FFA tiertype shortname was set to `Showm.` instead of just `FFA`
https://discord.com/channels/93055209017729024/268719633366777856/1333469058976186378
pushed live
=> feat(tier): align halo's FFA shortname to tiertype

standard/info/wikis/chess/info.lua
Add as draft until chess wiki got installed, I might just stack PRs so when Chess is installed this can be looked at one go
1834 as start year, as in this is the oldest event that has been covered so far.
=> feat: add chess

components/infobox/wikis/chess/infobox_league_custom.lua
Stacking Chess PRs before wiki install
The chess wiki will have some customization 
- a **Type/Variant** of the chess modes, using `|mode=`
**`Classical` is majority but other exist (e.g. `blitz/rapid`) if unset, it will be default to `Classical`.** 
- a **Category Range** this is basically how VALORANT handles Female tourney, except theres four of it: Junior, Female, Senior and Amateur. Editors want to use `qualifier` tiertypes on these events
**UPDATE: Now replaced with the way CS wiki implements this.**
https://liquipedia.net/callofduty/User:Hesketh2/Chess/FIDE_World_Chess_Championship/2024
Wiki is expected to be installed next week, I wouldnt want to stall it any longer
Time Control is being considered but it's so dynamic that it likely won't be in the scope of this PR
=> feat(Infobox): add Infobox League for Chess

components/standings/commons/standings_parse_wiki.lua, components/standings/commons/standings_parser.lua, components/standings/commons/standings_table.lua, components/standings/wikis/pubgmobile/standings_table_legacy_ffa.lua
Adds support for startingpoints as it's needed for this feature.
Wiki-specific PUBGM legacy wrapper so that we don't need to update all existing instances to new wikicode. 
PUBGM have multiple variants of previous Ffa Standings. 4 have been identified so far, but there may be more showing up.
* Template:League standings without lobby
* Template:League_standings_with_past_results
* Template:league standings slot
* Template:league standings slot2
All 3 setups tested (withoutLobby, pastResults, and slot-family)
=> feat: legacy support for ffa standings on pubgm

components/standings/wikis/pubg/standings_table_legacy_ffa.lua
Wiki-specific PUBG legacy wrapper so that we don't need to update all existing instances to new wikicode. 
PUBG have multiple variants of previous Ffa Standings. There are beleived to be these 5 verison, but there could be additional variants not known at this time. 2 of them will be remove by community team manually (due to only 2 usages each).
* Template:League standings without lobby
* Template:League standings slot
* Template:League standings slot2
preview
=> feat: legacy support for ffa standings on pubg

components/standings/commons/standings_parse_wiki.lua, components/standings/wikis/pubg/standings_table_legacy_ffa.lua, components/standings/wikis/pubgmobile/standings_table_legacy_ffa.lua
currently for party opponents they do not get displayed with flag nor link if they are not specified manually
this pr resolves the opponent (incl syncPlayer being activated) after reading its args so that those values are filled in automatically where possible
additionally added 2 missing return annos in the pubg(m) legacy stuff
dev on https://liquipedia.net/geoguessr/User:Steve23/Testing_Page2
=> feat(standings): improve party opponent support in ffa standings

components/infobox/commons/infobox_skill.lua, components/infobox/wikis/stormgate/infobox_building_custom.lua, components/infobox/wikis/stormgate/infobox_skill_custom.lua, components/infobox/wikis/stormgate/infobox_unit_custom.lua, standard/icon_data.lua
1. Make 'caster' on `Infobox/Skill` customizable
2. Update caster display in `Infobox/Skill/Custom` to properly show subfaction casters (follow up on https://github.com/Liquipedia/Lua-Modules/pull/5263 and https://github.com/Liquipedia/Lua-Modules/pull/5340)
3. Update Icon Data for stormgate. Use game mode name ('coop', 'mayhem') instead of icon name ('dungeon', 'fort') so when we change the icon later we only have to change the relevant icon in `Module:Icon/Data` and not all Modules that use it
dev tools
=> feat(Infobox): Update Skill Infobox for Stormgate to properly display subfaction casters

components/opponent/commons/opponent.lua
`player.team` is stored into `...template`, but `player.team` load from `...team`. 
Keeping `...team` as a fallback
Now:
Before:
=> fix: historic team templates for players not working as expected

.github/workflows/luacheck.yml
Bumps [mikepenz/action-junit-report](https://github.com/mikepenz/action-junit-report) from 4 to 5.
<https://github.com/Liquipedia/Lua-Modules/actions/runs/13104214227>
=> ci: Bump mikepenz/action-junit-report from 4 to 5

components/infobox/wikis/deadlock/infobox_character_custom.lua, components/infobox/wikis/deadlock/infobox_item_custom.lua
Saving args.tier to DB for invoking count on [Portal:Items](https://liquipedia.net/deadlock/Portal:Items)
This gonna be automatically invoked based on "|tier=|type=" in [Template:ItemCostHeader](https://liquipedia.net/deadlock/Template:ItemCostHeader).
Already prepared setup for it inside of the template.
Dev version in [Basic Magazine](https://liquipedia.net/deadlock/Basic_Magazine)
Part of the Invoke in my [Sandbox](https://liquipedia.net/deadlock/User:Sl0thyMan/Sandbox/24)
Saving args.playable and args.removed to DB for invoking count on [Portal:Heroes](https://liquipedia.net/deadlock/Portal:Heroes).
args.removed is more of the preparation as right now there is no heroes which is completely deleted. If we not gonna scratched heroes from the game before Title Deadlock was announced.
Dev …
=> feat(infobox): additional storage in items/charactes infobox

components/standings/commons/standings_parse_lpdb.lua
Don't import TBDs in ffa standings.
This also resolves this ticket:
dev: https://liquipedia.net/pubgmobile/User:Hjpalpha
=> feat(standings): Don't import TBDs in ffa standings

components/components/filter_buttons/wikis/deadlock/filter_buttons_config.lua, components/filter_buttons/filter_buttons.lua, components/filter_buttons/wikis/leagueoflegends/filter_buttons_config.lua, components/widget/tournaments/widget_tournaments_ticker_sublist.lua
Resolves #5329 and https://gitlab.com/teamliquid-dev/liquipedia/issue-bucket/-/issues/224
Code is terrible, because sometimes mappings from SR to R is needed, and sometimes the other way around... Depending on component and usage...
A way for certain wikis to filter Matches and Tournaments based on super-region
For League of Legends, they request the following super-regions:
* Americas (Including everything in North/Central/South america)
* EMEA (Europe, Africa, Middle East)
* Pacific (Basically all of Asia + Oceania excluding CN and KR)
* China
* Korea
dev
https://liquipedia.net/leagueoflegends/User:ElectricalBoy/MainPage
=> feat: allow editors to merge regions into super-regions in the new mainpage filters

components/match2/wikis/fighters/get_match_group_copy_paste_wiki.lua
Fighters match2 uses `tXpY` param for specifying which member of the team played the game. This PR adds these `tXpY` params (specifically, `t1p1` and `t2p1`) to the generator output when used under team mode.
[dev](https://liquipedia.net/fighters/Special:RunQuery/BracketCopyPaste/dev)
=> feat(match2): Add team mode to fighters generator

components/statistics/portal_statistics.lua
`prizepoolBreakdown` overflows the page width on smaller devices and on wikis with lost of years to cover (e.g. chess) even on larger screens
to mitigate this issue make the table(s) sideways scrolable via adding a dive wrapper with `table-responsive` class
=> feat(Statistics): make `prizepoolBreakdown` responsive

standard/tier/wikis/valorant/tier_data.lua
Tier data for valorant was created by @hjpalpha in Mar 2023 but was not added to GitHub. This PR adds it to the repository, with a valorant-specific adjustment (kicking unused D-Tier).
live
=> feat(tier): Add valorant data

components/statistics/count.lua, components/statistics/portal_statistics.lua
reported on discord: https://discord.com/channels/93055209017729024/268719633366777856/1336632125872410685
games (usually) get stored as identifiers not as full names
hence enable the query to look for the identifiers too
due to possible custom input or wikis possibly storing game as name (instead of identifier) i leave the fallback of the plain input there too
dev
=> fix(Statistics): game identifiers not found

components/filter_buttons/wikis/valorant/filter_buttons_config.lua, components/main_page/wikis/valorant/main_page_layout_data.lua, stylesheets/commons/Banner.less
_Depends on #5405_
This PR standardizes main page layout of Valorant wiki.
Credit for initial work done for this PR goes to @elisazanatta
Sandbox: <https://liquipedia.net/valorant/User:ElectricalBoy/MainPage>
=> feat(mainpage): new Valorant main page

components/main_page/wikis/valorant/main_page_layout_data.lua
Transfers and statistics navcards used the same image and this was not caught in #5330, so this PR updates image for statistics navcard.
dev
=> feat(mainpage): update image for statistics navbox in valorant mainpage

components/external_media_links/external_media_list.lua
As requested by some TG-heavy wikis, e.g. valorant:
Automatically display the team icon of the subject at the time of the EML.
Only enabled when there is a single subject to query for, and the flag `showSubjectTeam` is set.
Requires TeamHistory datapoints to be saved on the player's page.
dev
=> feat(ExternalMediaList): Add option to display team icons besides EMLs

components/ratings/ratings_storage_extension.lua, components/ratings/ratings_storage_factory.lua, components/ratings/rocketleague/ratings_display.lua, components/ratings/rocketleague/ratings_display_graph.lua, components/ratings/rocketleague/ratings_display_list.lua, components/ratings/rocketleague/ratings_storage_lpdb.lua, components/widget/ratings/widget_ratings.lua, components/widget/ratings/widget_ratings_list.lua, components/widget/standings/widget_standings_placement_change.lua, definitions/mw.lua, standard/info/wikis/dota2/info.lua, stylesheets/commons/RankingTable.less
A data table, showing the top 20 Dota 2 teams, updated weekly.
Existing RL ratings system is moved to RL specific, to be merged into this flow at a later time.
Laura's dev wiki
=> feat: Dota 2 Rankings table for the main rankings page

components/infobox/wikis/rocketleague/infobox_person_player_custom.lua
Adding FIFAe Word Cup history to player pages
dev: https://liquipedia.net/rocketleague/User:Reidthesloth/Player_Card_Test
=> feat(infobox): Add Update FIFAe Word Cup history to RL Infobox player

components/mvp_table/commons/mvp_table.lua
in #5372 the display was changed to use OpponentDisplay. But while doing so the left-alignment was removed, this PR re-adds the left-alignment.
reported on discord: https://discord.com/channels/93055209017729024/268719633366777856/1338646233283039272
dev to live
=> fix(mvpTable): Player Cell not left aligned

components/infobox/wikis/mobilelegends/infobox_unit_hero_custom.lua
Store `lane`, `primaryrole`, `secondaryrole`, and `region` to LPDB
[Tested in this page](https://liquipedia.net/mobilelegends/Arlott)
=> feat(infobox): additional storage in the infobox hero on MLBB

components/match2/commons/starcraft_starcraft2/match_group_util_starcraft.lua
Add a missing nil catch in sc(2) MatchGroupUtil.
It is only relevant for ffa stuff.
=> fix(match2): missing nil catch sc(2)

components/notability/wikis/callofduty/notability_checker_config.lua
First time tapping into this config so expect it to need fix??, saw it was unadded for a while I just took it over, these are based on PUBGM's setup (due to both running the same points system on each of their guidelines) 
There are some things like there are two showmatch tiertype and an individual tiertype in PUBGM's config being removed here, assuming it should not be here
COD's points system for reference
=> feat: COD Notability Config

components/infobox/wikis/stormgate/infobox_skill_custom.lua
Small bugfix for skill infobox display to show standard factions as casters for top-bar abilities similar as how it is done in SkillCards (this part was somehow missing in the last pr).
dev tools, i.e. 
- https://liquipedia.net/stormgate/Promote
- https://liquipedia.net/stormgate/Power_Surge
=> fix(Infobox): Stormgate Skill Infobox didn't show standard factions as caster of top-bar abilites

components/opponent/wikis/smash/opponent_custom.lua
Smash uses a single module for character naming standardization. It is not broken out by game due to the shared rosters. Referring to game specific submodules for this breaks thousands of pages.
live
=> fix(opponent): smash char standardization errors due to game suffix

components/tournament/tournament.lua, components/widget/tournaments/widget_tournament_label.lua, components/widget/tournaments/widget_tournaments_ticker.lua, components/widget/tournaments/widget_tournaments_ticker_sublist.lua
Allow to display game icons in tournament ticker when enabled via flag `displayGameIcons`.
Required to enable new mainpage on e.g. AoE
dev
=> feat: Display game icons in tournament ticker

standard/info/wikis/honorofkings/info.lua
Changing the game name to Honor of Kings and the default game to hok. Only noticed this because for some recent tournaments where `|game=` setting was forgotten, it defaulted to Arena of Valor (the original main game on the wiki) and was not noticed.
dev, thus far only tested with tournament pages, not sure if any thing else is affected by those 2 parameters
=> fix: Changing honorofkings wiki default game & name to Honor of Kings

.eslintrc.json, components/widget/ratings/widget_ratings.lua, components/widget/ratings/widget_ratings_list.lua, javascript/commons/RankingTable.js, standard/icon_data.lua
An expandable/collapsable section for each team in the rankings, that shows their placement progress over time
Laura's dev wiki
=> feat: team rankings progression graph on rankings table

components/match2/wikis/fighters/match_legacy.lua
resolves #5426
just gsub the underscores to places in legacy storage
N/A
=> fix(match2): underscores in opponent names in figherts legacy storage

components/match2/wikis/fighters/match_legacy.lua
fixes #5426
underscore substitution for winner field of legacy storage was omitted in #5431
N/A
=> fix(match2): underscores in winner field in fighters legacy storage

components/filter_buttons/wikis/overwatch/filter_buttons_config.lua, components/main_page/wikis/overwatch/main_page_layout_data.lua, stylesheets/commons/Banner.less
This PR standardizes main page layout of Overwatch wiki.
Credit for initial work done for this PR goes to @elisazanatta
- Sandbox: <https://liquipedia.net/overwatch/User:ElectricalBoy/MainPage>
=> feat(mainpage): new Overwatch main page

standard/tournament_structure.lua
increase the limit of standingsentries that get imported per standingstable during e.g. PPT import from 100 to 1000
required by chess wiki as reported on discord:
https://discord.com/channels/93055209017729024/268719633366777856/1339215360381026436
N/A
=> feat: increase limit of imported entries per standingsTable

components/infobox/wikis/counterstrike/infobox_league_custom.lua
Should be "event", not "qualifier". Was copied from above row and not spotted in last PR.
Just data fix.
=> fix(metadesc): Fix typo in CS metadesc values

components/match2/wikis/leagueoflegends/match_group_input_custom.lua, components/match2/wikis/leagueoflegends/match_summary.lua
LoL wiki records casters for international events (namely MSIs and Worlds) and they currently rely on using comments.
This PR adds support for caster rows (refs: #4313, #4943) to LoL match2.
dev: [leagueoflegends:User:ElectricalBoy/Sandbox2](https://liquipedia.net/leagueoflegends/User:ElectricalBoy/Sandbox2)
=> feat(match2): add caster row support to LoL

components/main_page/wikis/overwatch/main_page_layout_data.lua
Current mainpage uses Overwatch logo, and OW editors wanted it to be updated
dev
=> feat(mainpage): use Overwatch2 logo in mainpage

standard/info/wikis/rainbowsix/info.lua
Recently a page was made for Rainbow Six Vegas (1) which resulted in not showing the game icon on in the Template:TournamentsLists or the game name in the Infobox on said page (see below).
This edit should add the game icon and name onto the wiki, the Icon for Vegas 1 is the same as for Vegas 2, which already was present in this file.
I have also updated the file links to the Default TeamCard images to their correct new filename.
Did not test, should not break anything but will display the Vegas game name icon on this page: 
- https://liquipedia.net/rainbowsix/A-Tier_Tournaments#2007 (in the Game spot)
- https://liquipedia.net/rainbowsix/Major_League_Gaming/2007/Charlotte (When |game=vegas is being used in the infobox it should show: "Game: Tom Clancy's Rainbow Six Vegas")
=> feat: add R6:Vegas (1) 

components/main_page/wikis/hearthstone/main_page_layout_data.lua, components/main_page/wikis/leagueoflegends/main_page_layout_data.lua, components/widget/tournaments/widget_tournaments_ticker.lua
The legacy offsets previously added were only part of the commons version of the old ticker.
Most wikis (including most of the ones already converted to this) already had different local versions, with less weird offsets.
This allows to add the offsets, if necessary, via arguments.
IMO the default should be no offsets at all, and mainpage data can include them based on the specific old version the wiki used.
Check existing new main pages for old offsets:
"dev" by checking the tables have correct content and timestamps are modified
=> feat: Allow to modify tier-specific thresholds in TournamentsTicker

components/main_page/wikis/valorant/main_page_layout_data.lua
The current mainpage uses an Overwatch(???) photo for players navbox. This PR updates this to a Valorant photo.
Blame GodOfPog for choice of photo 😆
dev
=> feat(mainpage): update image for players navigation in valorant mainpage

components/infobox/wikis/leagueoflegends/infobox_unofficial_world_champion_custom.lua
This PR adds Unofficial World Champion infobox for LoL wiki.
Note: This uses the exact same code as the [Overwatch version](https://github.com/Liquipedia/Lua-Modules/blob/56e2e63845971e55dd13d5bcd09d4a2fe67d8a0a/components/infobox/wikis/overwatch/infobox_unofficial_world_champion_custom.lua), with some trivial name changes.
live
=> feat(infobox): add lol unoff. world champ infobox

components/infobox/wikis/ageofempires/infobox_person_player_custom.lua
AoEDB extension has been fixed thanks to Darkrai:
Re-enable ratings for AoE 2, 3, 4
Add new option to fetch rating for AoMR
dev
=> feat: Re-enable rating fetch from AoEDB extension

components/infobox/commons/infobox_person.lua, components/infobox/commons/infobox_team.lua
Define page variables even when outside of mainspace, since they would not have an effect outside of the page itself, unlike LPDB.
TODO
=> feat(infobox): set wiki vars in all namespaces

standard/flags_master_data.lua
They got merged when template-based flags were removed, but this doesn't make sense, as the image used for `germanspeaking` does not include switzerland (the `CH` in DACH).
dev
=> feat: Separate DACH and germanspeaking flags

components/opponent/commons/opponent.lua, components/standings/commons/standings.lua, components/widget/standings/widget_standings.lua, components/widget/standings/widget_standings_match_overview.lua, components/widget/standings/widget_standings_swiss.lua
There exists **at least 20 versions** out there that are automated (automatically populates with match data), in at least 2 major branches. In addition, there **exists 11 versions** of non-automated table. All version have terrible, unmaintainable code and the data storage shoehorned in, in the only way that was possible, terribly. Tiebreakers can break when large numbers are involved. Doing any maintenance and especially new features is next to impossible.
This is the first step in that journey, in this step we build a sustainable standardized display system for Swiss. 
Use the existing data we store on R6, to build a sustainable display system. It shall only use data in LPDB, for many reasons (such as decreased spaghetti, cleaner code, removal of transclusions, ensures we store all data …
=> feat(standings): swiss display style

.github/workflows/luacheck.yml
Upstream CI dependency finally released their node20 version. Let's update these to node20 so we can get rid of the deprecation warning and the potential of failing pipelines when node16 is dropped from GH.
=> ci: update dependencies to versions running node20

components/standings/commons/standings_parse_lpdb.lua, components/standings/commons/standings_parse_wiki.lua, components/standings/commons/standings_parser.lua, components/standings/commons/standings_storage.lua, components/standings/commons/standings_table.lua
produces
Since tiebreakers aren't implemented yet, the top 8 all share their places (the bottom 8 doesn't)
https://liquipedia.net/rainbowsix/User:Rathoz/Leagues/blabla
=> feat(standings): import swiss

stylesheets/commons/Panels.less
This is part of the ticket https://gitlab.com/teamliquid-dev/liquipedia/web/skins/lakesideview/-/issues/156 to set other colors for themes sun, tuliptree, redviolet, gigas and forestgreen.
This needs to be deployed together with https://gitlab.com/teamliquid-dev/liquipedia/web/skins/lakesideview/-/merge_requests/129
- add specificity
- add new variable for panel border color
- add color
wikidev
=> feat: adjust panel-box colors on certain wiki themes

components/main_page/commons/main_page_layout.lua, components/main_page/wikis/apexlegends/main_page_layout_data.lua, components/main_page/wikis/arenafps/main_page_layout_data.lua, components/main_page/wikis/brawlstars/main_page_layout_data.lua, components/main_page/wikis/deadlock/main_page_layout_data.lua, components/main_page/wikis/dota2/main_page_layout_data.lua, components/main_page/wikis/halo/main_page_layout_data.lua, components/main_page/wikis/hearthstone/main_page_layout_data.lua, components/main_page/wikis/leagueoflegends/main_page_layout_data.lua, components/main_page/wikis/marvelrivals/main_page_layout_data.lua, components/main_page/wikis/overwatch/main_page_layout_data.lua, components/main_page/wikis/pubg/main_page_layout_data.lua, components/main_page/wikis/pubgmobile/main_page_layout_data.lua, components/main_page/wikis/rainbowsix/main_page_layout_data.lua, components/main_page/wikis/valorant/main_page_layout_data.lua, javascript/commons/Countdown.js
Closes https://github.com/Liquipedia/Lua-Modules/issues/5326
I have set up a minimal example on my dev here:
* With containment: http://fonttax.wiki.tldev.eu/rocketleague/Dfuvberwuivbr
* Without containment: http://fonttax.wiki.tldev.eu/rocketleague/Dfuvberwuivbr2
=> feat: allow countdown switch group to be containable so it does not change unrelated countdowns

standard/links/commons/links.lua
They moved all the tournament platform stuff to play subdomain. Just fixing the URLs so they are correct.
Just data fix
=> fix(links): update to new toornament subdomain

components/match2/commons/get_match_group_copy_paste_wiki_base.lua, components/match2/wikis/apexlegends/get_match_group_copy_paste_wiki.lua, components/match2/wikis/arenafps/get_match_group_copy_paste_wiki.lua, components/match2/wikis/autochess/get_match_group_copy_paste_wiki.lua, components/match2/wikis/callofduty/get_match_group_copy_paste_wiki.lua, components/match2/wikis/fortnite/get_match_group_copy_paste_wiki.lua, components/match2/wikis/freefire/get_match_group_copy_paste_wiki.lua, components/match2/wikis/halo/get_match_group_copy_paste_wiki.lua, components/match2/wikis/naraka/get_match_group_copy_paste_wiki.lua, components/match2/wikis/pubg/get_match_group_copy_paste_wiki.lua, components/match2/wikis/pubgmobile/get_match_group_copy_paste_wiki.lua, components/match2/wikis/tft/get_match_group_copy_paste_wiki.lua, components/match2/wikis/underlords/get_match_group_copy_paste_wiki.lua
This PR adds `WikiCopyPaste.getFfaOpponent()` and removes all custom variants of Ffa opponent generator functions.
One noteworthy exception is Fortnite that overrides the base version with support for 2Opponent/3Opponent (no other FFA wiki had it).
dev in PUBG
=> refactor(match2): standardize ffa opponent code generation

components/main_page/commons/main_page_layout.lua
This PR kicks usage of `{{Header banner}}` in the new mainpage layout and replaces it with a widget.
dev in LoL
=> refactor(mainpage): header banner into widget

components/infobox/wikis/warthunder/infobox_league_custom.lua
Customizations are **Battle Type** and **Vehicles**
this is to indicate
- one of the 3 Battle type in the game (Arcade, Realistic, Simulator) which defines the match speed
- one of the Vehicle unit types in the game (Aviation, Naval, Ground, or Multiple for tournaments which runs various) 
Contributors dont want to type the full mode names hence the input is just AB/RB/SB, matching their official ingame naming
=> feat(Infobox): Infobox League for War Thunder

components/main_page/commons/main_page_layout.lua, components/main_page/wikis/leagueoflegends/main_page_layout_data.lua, components/main_page/wikis/pubg/main_page_layout_data.lua, components/main_page/wikis/valorant/main_page_layout_data.lua, components/transfer/commons/transfer_list.lua, components/widget/grid/widget_grid.lua, components/widget/grid/widget_grid_cell.lua, components/widget/grid/widget_grid_container.lua, components/widget/main_page/widget_main_page_center_dot.lua, components/widget/main_page/widget_main_page_transfers_list.lua, components/widget/misc/widget_panel.lua
This PR introduces `Module:Widget/Grid/Container` and `Module:Widget/Grid/Cell`, with the purpose of replacing [Module:Grid](https://liquipedia.net/commons/Module:Grid). This also updates layout data for LoL / Valorant so that widgets are directly passed into the grid widgets (see #5528 for initial work).
- dev in LoL / Valorant / PUBG
- preview in OW with dev: for testing backwards compatibility
=> refactor(mainpage): grid into widget

components/main_page/wikis/leagueoflegends/main_page_layout_data.lua, components/main_page/wikis/pubg/main_page_layout_data.lua, components/widget/main_page/widget_main_page_this_day.lua, components/widget/main_page/widget_main_page_this_day_content.lua, components/widget/main_page/widget_main_page_this_day_title.lua
This PR introduces `Module:Widget/MainPage/ThisDay/Title` and `Module:Widget/MainPage/ThisDay/Content` to (fully/partially) replace Html widgets and `{{Liquipedia:This day}}`, respectively.
Note that rewriting [Module:ThisDay](https://liquipedia.net/commons/Module:ThisDay) is not considered to be within scope of this PR and would likely require a separate PR on its own.
dev in LoL/PUBG
=> refactor(mainpage): rewrite this day components as widgets

components/main_page/wikis/marvelrivals/main_page_layout_data.lua
Changed order of nav card according to discord poll on discord
https://discord.com/channels/93055209017729024/1316071697555914804/1346576596554744021
Test it in my sandbox
https://liquipedia.net/marvelrivals/Module:MainPageLayout/data/dev/slothy
https://liquipedia.net/marvelrivals/User:Sl0thyMan/Sandbox/1
=> feat: update order of nav cards on Marvel Rival's mainpage

components/notability/wikis/osu/notability_checker_config.lua
Handling for cases where game mode isn't provided as all lowercase in the infobox
https://liquipedia.net/osu/index.php?title=Module:NotabilityChecker/config&diff=41182&oldid=41179
tried it on the wiki with this event:
https://liquipedia.net/osu/Newbie_Taiko_Journey/2
This tournament should award 2*1.2=2.4 points for the winner.
Without change if mode is "Taiko" in infobox:
With change if mode is "Taiko" in infobox:
Without change if mode is "taiko" in infobox:
With change if mode is "taiko" in infobox:
=> feat: handle uppercase mode names in osu notability checker

components/infobox/wikis/valorant/infobox_weapon_custom.lua
In Valorant's weapons infobox, some fields are named using legacy param names, some are trying to read from legacy param name, etc...
This PR fixes them all
N/A
=> fix(infobox): lpdb field/data inconsistent with valorant weapons infobox params

components/opponent/commons/player_ext.lua, components/opponent/wikis/rocketleague/player_ext_custom.lua
Noticed when testing #5419:
The team sync would only check the pagevars for leavedate, so when querying multiple dates in descending fashion, only the latest team would be returned.
This allows to query dates in either direction.
In addition, add option to return unresolved template. This is necessary to be able to display correct subtemplates when two different dates during the player's time on the time are queried, and there was a HTT change inbetween.
dev
=> feat(opponent): Advanced filter and return for team history in Player/Ext

.github/workflows/luacheck.yml
For security reasons, GitHub does not allow writing checks from Actions workflow for PRs coming from forks. This PR adjusts workflow settings to let Actions annotate only instead of creating full checks when it is run from forks.
For documentation, see
- <https://github.com/mikepenz/action-junit-report?tab=readme-ov-file#inputs>
- <https://github.com/mikepenz/action-junit-report?tab=readme-ov-file#pr-run-permissions>
https://github.com/Liquipedia/Lua-Modules/actions/runs/13699024313
=> ci: annotate test results for pull requests from forks

components/infobox/commons/infobox_person.lua, spec/name_order_spec.lua, standard/name_order.lua
This PR implements [lpcommons:Liquipedia:Name Standards#Name Order](https://liquipedia.net/commons/Liquipedia:Name_Standards#Name_Order)
included test suite (26c2e46)
=> feat(standard): implement name order logic

components/main_page/wikis/apexlegends/main_page_layout_data.lua, components/main_page/wikis/arenafps/main_page_layout_data.lua, components/main_page/wikis/brawlstars/main_page_layout_data.lua, components/main_page/wikis/deadlock/main_page_layout_data.lua, components/main_page/wikis/dota2/main_page_layout_data.lua, components/main_page/wikis/fortnite/main_page_layout_data.lua, components/main_page/wikis/halo/main_page_layout_data.lua, components/main_page/wikis/hearthstone/main_page_layout_data.lua, components/main_page/wikis/marvelrivals/main_page_layout_data.lua, components/main_page/wikis/overwatch/main_page_layout_data.lua, components/main_page/wikis/pubgmobile/main_page_layout_data.lua, components/main_page/wikis/rainbowsix/main_page_layout_data.lua
~~_Depends on #5451 (`DateExt.quarterOf` part of it)_~~
Follow-up for #5530
This PR replaces most wikicode strings into direct Lua calls.
dev
=> refactor(mainpage): load Lua directly from mainpage layout data

standard/team_template.lua
This PR moves [Module:TeamTemplate](https://liquipedia.net/commons/Module:TeamTemplate) to the repository. Utility functions for historic team templates are also added.
c53f78d is identical to the [Commons version](https://liquipedia.net/commons/Special:PermanentLink/738389)
c53f78d...33ca97d add documentation (no code change)
6e2f941 remains untested
=> feat(standard): add TeamTemplate util functions

components/infobox/extensions/commons/infobox_extension_achievements.lua, components/infobox/wikis/fortnite/infobox_person_player_custom.lua, components/infobox/wikis/fortnite/infobox_team_custom.lua
By default, this change adds the achievements of teams by their players during the period in which they performed under the banner of the team in question automatically.
**How did you test this change?**
I tested this change thoroughly on the Fortnite wiki to ensure it works as intended and does not introduce regressions. Here’s how I verified it:
Test Pages:
Team HavoK: A team known to have a Tier 1 2nd place medal (e.g., Fortnite Champion Series 2025 Major 1 Europe). I updated the infobox on its page and confirmed that the "Achievements" section displays the medal icon correctly without manual addition of |achievements={{Team Medals}}.
BIG: A team with known Tier 1 medals (e.g., 1st place achievements). I checked that the infobox automatically shows the correct medal icons under …
=> feat(infobox): automatically include achievements in player and team infoboxes

components/infobox/commons/infobox_character.lua, components/infobox/wikis/leagueoflegends/infobox_character_custom.lua, components/main_page/wikis/leagueoflegends/main_page_layout_data.lua
Currently, champion infobox in LoL extends unit infobox. This doesn't make much sense as champions are playable characters in LoL.
Thus, this PR adjusts champion infobox to extend character infobox, and rewrites the infobox code accordingly.
first in dev, then in live
=> refactor(infobox): rewrite LoL champion infobox

components/infobox/wikis/chess/infobox_league_custom.lua
Add support for multiple time controls in league infobox.
Stores first time control as `mode` in LPDB, and all of them in `extradata`.
Displays as separate lines in infobox.
/dev
=> feat: add support for multiple time controls on chess

components/infobox/commons/infobox_unofficial_world_champion.lua, components/infobox/wikis/rocketleague/infobox_unofficial_world_champion_custom.lua
This PR:
- refactors Unofficial World Champion infobox to accept match2 opponents  
Right now all the data are passed in using `{{Team}}` (or `{{TeamShort}}`). With fe900f7 and 599604c, infobox now expects `{{Opponent}}` templates to be passed in and rendering for opponents is put on the infobox side.
- Adds optional LPDB data point for RL's unofficial world champion infobox  
This is wanted for their mainpage `¯\_(ツ)_/¯`
- <https://liquipedia.net/leagueoflegends/User:ElectricalBoy/Sandbox4>
- <https://liquipedia.net/rocketleague/User:ElectricalBoy>
=> feat(infobox): LPDB data point for RL unofficial world champion infobox

components/notability/wikis/marvelrivals/notablity_checker_config.lua, components/notability/wikis/overwatch/notability_checker_config.lua
Add the existing notability checker config from overwatch to the repo, module already exists for ages
Add newly created notability checker config from marvelrivals that was created a few days ago
Already works with local module versions, just pushing it to github
=> feat(notability checker): add missing notability checker config for overwatch and add newly created notability checker config for marvelrivals

components/match_table/commons/match_table.lua
To be able to list pages where the number of matches meet the set limit, add a tracking category.
This allows to convert such pages into subpages with year ranges, without breaking them first
Noticed the need for this when trying to roll out on CS.
dev
=> feat: Add tracking category for limited match pages

components/infobox/wikis/starcraft2/infobox_team_custom.lua
Nuke the useless and outdated staff sections on sc2 team infoboxes.
Sadly we do not get to nuke this bullshit from more wikis but at least for wikis that do not want it we should nuke it via the customs.
N/A
=> feat(infobox): remove staff section on sc2 infobox team

components/infobox/commons/infobox_team.lua, components/infobox/extensions/commons/role_of.lua, components/infobox/wikis/dota2/infobox_team_custom.lua, components/infobox/wikis/leagueoflegends/infobox_team_custom.lua
Follow-up for #5555
This PR reapplies LPDB storage portion of #5480. It doesn't touch the display portion, nor is it intended to.
preview with dev in LoL and Valorant
=> feat(infobox): remove lpdb storage of deprecated infobox team fields

README.md
The readme lacks instructions for Unix based systems and Neovim editor.  I added some notes and useful tools for these.
=> docs: add instructions for ubuntu and neovim

lua/wikis/commons/MatchTable.lua
To align with other components (e.g. TournamentsListing), the enddate should be inclusive.
dev
=> fix: Make enddate inclusive on matchtable

lua/wikis/artifact/MatchGroup/Legacy/Default.lua
Legacy wrapper for artifact bracket conversion
live, bot runs starting in a few minutes
MatchList conversion should be done manually (community team?!?!) due to it being used on only 4 pages
=> feat(match2): Artifact Bracket Legacy Wrapper

lua/wikis/commons/MatchSummary/Base.lua, lua/wikis/counterstrike/Info.lua
Per-map substitute comment uses 'map' univerally, without any option to override. This is wrong in some wikis, e.g., leagueoflegends, because they should be called 'games' not 'maps'.
This PR adds an option to optionally override this.
preview with dev
=> feat(match2): change gamenoun used in substitute comment

lua/wikis/runeterra/MatchGroup/Legacy/Default.lua
Legacy wrapper for runeterra brackets
live, bot run under way
- https://liquipedia.net/runeterra/Special:WhatLinksHere/Template:32DEBracket (1 usage, mapping makes no sense)
- https://liquipedia.net/runeterra/Special:WhatLinksHere/Template:4DE4SBracket (2 usages, complete garbage)
- https://liquipedia.net/runeterra/Special:WhatLinksHere/Template:32SEBracket (7 usages, complete garbage)
- matchlist conversion (1 page): https://liquipedia.net/runeterra/index.php?title=LoR_Masters_Europe:_Chronicles_of_Targon&action=edit&section=9
=> feat(match): Legacy wrappers for runeterra

lua/definitions/mw.lua, lua/wikis/commons/MatchGroup/Base.lua, lua/wikis/commons/Namespace.lua
When storage is disabled, having a parent or not seems irrelevant. For example https://liquipedia.net/counterstrike/Liquipedia:Match2 is showing a pointless warning.
Untested as of yet, gathering feedback/opinions.
=> feat(match2): don't add HDB warning on documentation pages

lua/wikis/commons/Widget/Ratings/List.lua, lua/wikis/dota2/MatchPage/Template.lua, lua/wikis/leagueoflegends/MatchPage/Template.lua
Add alt text to "SAP" logo for screen readers.
I tested `[[File:SAP_logo.svg|link=|SAP]]`  on wiki and it correctly adds alt text to the img element in HTML.
=> feat: add "SAP" alt text screen readers

lua/wikis/commons/Widget/Match/Ticker/Container.lua
Filterbuttons (and thus also TournamentsTicker) use the `name` field to build the group name.
MatchTicker used `property` field, which originally was meant to indicate LPDB columns to get the value from.
This means that whenever the two fields don't align, the JS breaks (separate problem)
Closes #5626 
dev
Does not require change to any template, as all existing configs need to have it matching anyways
=> fix(MatchTicker): Use correct FilterButtonCategory field

lua/wikis/battalion/MatchGroup/Legacy/Default.lua, lua/wikis/battalion/MatchGroup/Legacy/MatchList.lua
legacy match2 wrappers for battalion
live, brackets (with the exception listed below) and matchlists converted
- https://liquipedia.net/battalion/Template:8SE4STeamBracket (1 usage, bad mapping)
- https://liquipedia.net/battalion/Template:Showmatch (1 usage)
=> feat(match2): Legacy wrappers for battalion

stylesheets/commons/Brackets.less
This resolves the styling issue reported here by using `display: flow-root;`
Fixes #5307
=> fix: Make BR date section not span over infobox

lua/wikis/commons/MatchTicker/Custom.lua, lua/wikis/commons/Widget/Match/Ticker/Container.lua
Aims to improve the main page match ticker flow by
- moving the filterbuttons argument mapping into the matchticker entrypoint `newMainPage`
- moving limit arguments into the container module
- using Lua.import/Lua.invoke when expanding the matchticker, both using JS and for the default display
- passing the button category defaults when calling the default ticker
dev on https://liquipedia.net/ageofempires/User:SyntacticSalt/Main_Page
=> feat: Drop dependency on MainPageTicker templates

lua/wikis/commons/MatchTicker.lua
Allow to filter the matchticker by list of games (e.g. using filterbuttons)
PR/branch stacked on #5637 
dev: https://liquipedia.net/ageofempires/User:SyntacticSalt/Main_Page
=> feat: Support games filter in match ticker

stylesheets/commons/BattleRoyale/Panel.less
The icons are split into separate lines in the GameSummary on mobile. They should fit on the same row, saving some space and looking better.
Before:
After:
=> fix(GameSummary): Removed flex-basis to fit icon and content on the same row on mobile

lua/wikis/commons/Widget/Match/Ticker/Container.lua
Flattens the props structure to allow overriding the limit from invoke args.
This needs to be handled with care, as it can easily lead to rate limits.
It might be a good idea to allow for a higher, but set ratelimit (e.g. 25 matches) instead of exposing the parameter.
Also fix a bug where the wrong type was set for default display of recent matches
dev
(bugfix already live)
=> feat: Allow custom limit on match ticker container

lua/wikis/counterstrike/MatchGroup/Input/Custom.lua
When we started adding Valve tiers for the new VRS stuff to the publishertier, too much started becoming featured. For example 
Use the same logic as other places for highlighting results/tournaments/matches so that only the intended Valve tiers (majors, etc.) actually mean the match is featured.
Tested via dev deploy.
=> feat(match2): Use Highlight Conditions in `isFeatured` for CS wiki

stylesheets/commons/Mainpage.less
The spacing between the top of the new main page cards and the first h3 element is not standard.
| `#this-day-facts > h3:first-child` | `.useful-articles-layout > div > h3:first-child` |
| ![image](https://github.com/user-attachments/assets/cc2026a3-2199-4838-9a96-19b1294af892) | ![image](https://github.com/user-attachments/assets/8331aa6c-265f-4abf-912c-bbb336f9fd5c) |
Essentially just making them both the same (zero) spacing so that it looks better and takes up less space.
=> fix(mainpage): standardize first h3 padding

lua/wikis/commons/Links.lua
Now `|bluesky=username` leads you to bsky.app/profileusername
Should be bsky.app/profile/username
=> fix: Add trailing slash for bluesky link prefix

lua/wikis/valorant/Infobox/Person/Player/Custom.lua
Misunderstanding what actually was requested in #5646 
They want to enable it case by case:
> We have many players who were retired and then unretired, for them specialroles looks better, but for those who didnt return, basic retired param looks better
dev
=> feat(infobox): Expose THA special roles flag to infobox args on valorant

lua/wikis/clashroyale/MatchGroup/Input/Custom.lua, lua/wikis/clashroyale/MatchGroup/Legacy/BMS.lua, lua/wikis/clashroyale/MatchGroup/Legacy/Default.lua, lua/wikis/clashroyale/MatchGroup/Legacy/MatchList.lua, lua/wikis/clashroyale/MatchSummary.lua, lua/wikis/commons/Array.lua
Legacy wrappers for cr
live for new modules, dev for existing ones
- https://liquipedia.net/clashroyale/Template:4DE2v2Bracket (2v2 ...)
- bad mapping
- https://liquipedia.net/clashroyale/Template:12DEBracket (2)
- https://liquipedia.net/clashroyale/Template:64DEBracket (1)
- https://liquipedia.net/clashroyale/Template:8DE4LTeamBracket (5)
- utter bullshit
- https://liquipedia.net/clashroyale/Template:32SEBracket (28)
- https://liquipedia.net/clashroyale/Template:24SETeamBracket (1 usage with bad inputs)
=> feat(match2): Legacy wrappers for cr

lua/wikis/ageofempires/ParticipantTable/Custom.lua, lua/wikis/commons/ParticipantTable/Base.lua, lua/wikis/commons/ParticipantTable/Starcraft.lua, lua/wikis/stormgate/ParticipantTable/Custom.lua, lua/wikis/warcraft/ParticipantTable/Custom.lua
The value used to set the opponent highlight hover in participants table is not resolved.
for context from discord DMs with Rath:
This PR adjusts the ParticipantTable processing so that entry.name (whichg is used for that highlighting) its value uses the resolved oppoent name.
dev
=> fix(participantTable): highlight key unresolved

lua/wikis/fighters/PrizePool/Custom.lua
regression from #5659
The setup from #5659 assumed that any ppt with points would have a circuit associated with it. This assumption is not true in one specific edge case: EWC.
This PR handles the forementioned edge case
preview with dev
=> fix(prizepool): missing 'no circuit defined' catch

lua/wikis/callofduty/FilterButtons/Config.lua, lua/wikis/callofduty/MainPageLayout/data.lua, stylesheets/commons/Banner.less
Setup based on R6 but making tournaments a bit wider because it has the game icons
This requires a filter buttons that can filter events by games which is recently merged
https://liquipedia.net/callofduty/User:Hesketh2/maintest
COD changes game they compete every year, how can I adjust the Filter module to limits to just some games? 
for reference currently I need these three entries based on info module
`bo6` << these are the ones that changes every year 
`wz`  << doesnt change every year
`codm` << doesnt change every year
The rest are old game versions  that doesnt compete events anymore
=> feat(mainpage): COD new mainpage

stylesheets/commons/BigMatch.less, stylesheets/commons/Brackets.less, stylesheets/commons/Mainpage.less, stylesheets/commons/Miscellaneous.less, stylesheets/commons/Teamcard.less
resolves #5238
Currently break point for 100% width is 415px in some components while it is 435px in others.
This PR adjusts the components with 415px breakpoint to swwitch to also using 435px breakpoint and hence unifying the break points to one value.
Especially notable is that GTL has 435px while matchlists have 415px, so for devices with a width between 416-435 the display looks bad (see #5238)
N/A
=> feat: unify mobile break points to one value

lua/wikis/marvelrivals/MainPageLayout/data.lua
Adds "Liquipedia:Special Event" to the Main Page.
Provides the ability for contributors to add featured events to the Main Page of the Marvel Rivals wiki. This is seen on many other wikis and allows easy access to pages of major current tournaments/leagues. It's placed on the right side above the matches and tournaments panels, similar to the Dota 2 Main Page layout in order to keep Heroes available at the top on the left.
Test "Main Page" - https://liquipedia.net/marvelrivals/User:Schon/MainPage
Test "Liquipedia:MainPageLayout/data" - https://liquipedia.net/marvelrivals/Module:MainPageLayout/data/dev/Schon
=> feat(mainpage): add special events panel to marvelrivals mainpage

lua/wikis/callofduty/Infobox/Map/Custom.lua
Requested by Hesketh to support multiple games in the infobox as usually same map is in multiple versions of the game.
Not sure if we should handle extradata differentely
dev=slothy
|game=name of the game still works same as before 
```
{{Infobox map|dev=slothy
|name     = Azhir Cave
|image    = COD MW map Azhir Cave.png
|creator  = Activision
|location = Tobraka, [[Urzikstan]]
|released = 2019-10-25
|size     = Medium
|type     = 6v6
|game1=mw2019
|game2=mw3
|day/night variant = Both
|playlist = Competitive<br>Multiplayer
}}
```
=> feat(infobox): Support for mutiple Games on Map Infobox

lua/wikis/commons/GetMatchGroupCopyPaste/wiki/Base.lua
=> docs: fix spelling in WikiCopyPaste.getStart documentation

lua/wikis/callofduty/MainPageLayout/data.lua
The old setup takes you to monthly transfer pages
but COD uses quarterly setup
changes based on APEX mainpage setup
=> fix(mainpage): wrong COD Transfer pages

lua/spec/operator_spec.lua, lua/wikis/commons/Operator.lua, lua/wikis/commons/Widget/Tournaments/Ticker.lua
The new tournament ticker sometimes errors when there's bad dates (sort would not return the opposite between (`a, b` and `b, a`).
Sometimes display in non-optimal orders when one date is missing. 
This fixes it all
=> feat: improve sorting the tournament ticker

lua/wikis/commons/PortalStatistics.lua
Removes the condition that a tournament must have an enddate in the past for ongoing years for the "prizepool breakdown table"
While i'm not sure whether it makes sense to have this condition or not, it should either apply to all entrypoints, or none.
This goes the easier route of removing it for the single endpoint (partially!) implementing it.
Reported on discord: https://discord.com/channels/93055209017729024/268719633366777856/1352595320759914576
dev
=> fix(Statistics): Don't limit to past events for ongoing years

lua/wikis/overwatch/NotabilityChecker/config.lua
Change B-Tier points from 600 to 700 as per poll in the Wiki 2025 Feedback thread on discord
https://discord.com/channels/93055209017729024/1323697205080490185/1348702592657522728
none, simple value change
=> feat(Notability): Change B-Tier points to 700 in overwatch

lua/wikis/commons/MatchTicker/DisplayComponents.lua
resolves #5693 
brackets always have an inherited header while ffa matchlists might lack them, hence use matchIndex to generate a generic one for those cases
dev
before:
after:
=> fix(MatchTicker): error on ffa matchlists without inherited header

lua/wikis/commons/Widget/Panel.lua, stylesheets/commons/Panels.less
To improve user experience by making the accordion headers more intuitive and easier to interact with. Expanding the clickable area will reduce frustration and enhance accessibility for both mobile and web. Modify the section header accordions so that the entire header can be tapped to open or close the accordion, rather than just the ^ chevron icon.
dev and devtools
=> feat: Increase Tap Area for Section Header Accordions on new Main Page

stylesheets/commons/Fountain.less
This change appends Facetcard- and Aghscard-related styles to differentiate between lightmode and darkmode visuals.
At the time, Facetcard and Aghcard operate only on darkmode styles (as a lot of our contributors use dark theme).
These settings should help with achieving better visuals on lightmode.
Browser: Microsoft Edge v133.0.3065.92 64-bit
Pages used: "/dota2/Batrider" and "/dota2gameru/Batrider".
Aghcard example:
Facetcard example:
=> Additional light/darkmode styling for Facetcard and Aghcard templates

stylesheets/commons/Fountain.less
Added & operator so the style names would parsed as ".theme--dark X" rather than "X .theme--dark"
Fix on class naming being screwed up because of a forgotten & operator
Browser: Microsoft Edge 133.0.3065.92
Page: "/dota2/Batrider"
=> fix: class naming for Facetcard and Aghcard-related styles

javascript/commons/BattleRoyale.js
On wikis that has decimal numbers as their scores, such as Hearthstone, the BR/FFA sorting doesn't account for decimals.
This was because it was running through parseInt instead of parseFloat.
Using parseFloat for all situations where it's currently parseInt is safe. The only thing that parseFloat doesn't support is non-base-10 systems.
=> fix(match2): in FFA view, sorting ignores decimals

stylesheets/commons/Fountain.less
A fix for the aghupgShadow:hover values.
On light theme:
How it's pre-fix:
How it should be:
Browser: Microsoft Edge 134.0.3124.85
Page: /dota2/Huskar
=> fix: Aghcard's aghupgShadow hover values for light and dark themes

lua/wikis/leagueoflegends/Infobox/Team/Custom.lua
Team infoboxes in LoL relied on manual input for team achievements. This PR automates this input.
dev
=> feat(infobox): automatically include achievements in LoL team infobox

lua/spec/condition_spec.lua, lua/wikis/commons/Condition.lua
Currently if adding a ConditionTree which has no nodes (i.e. is empty) as a node to a ConditionTree the resulting condition strings can't be interpreted by LPDB due to the containing stuff like e.g. ` AND ()`.
This PR adjusts handling of empty ConditionTrees as Nodes so that the resulting coindition strings can be read by LPDB.
dev + busted
From the examples added so spec:
| | Old string | New string |
| ----- | ----- | ----- |
| 1 | `() AND [[game::commons1]] AND ()` | `[[game::commons1]]` |
| 2 | `() AND ([[game::commons1]] OR [[game::commons2]]) AND ()` | `[[game::commons1]] OR [[game::commons2]]` |
| 3  | `() AND ([[game::commons1]] OR [[game::commons2]]) AND ()` | `([[game::commons1]] OR [[game::commons2]])` |
| 4 | `(() AND [[game::commons1]] AND ()) AND ([[game::commons1]] OR …
=> feat: Allow empty ConditionTrees to be added as node to a ConditionTree

stylesheets/commons/Mainpage.less
The current headers are not following wiki colors at all and stand out way too much like they don't belong. This is a quick fix to stealing some CSS from the filter buttons and upcoming/completed toggles to match the style of the headers for the tournaments list to something that actually looks like it belongs there.
(Will apply to all Lakeside wikis, not just dota2 but obviously will use Lakeside colors for each wiki)
| Current | Proposed |
| ![image](https://github.com/user-attachments/assets/0b3b1d79-4eaa-4e1b-9cfd-67b2837231b9) | ![image](https://github.com/user-attachments/assets/11c86430-ade0-43b1-a506-939f13fa9526) |
=> feat(mainpage): improve tournament list headers on Lakeside

stylesheets/commons/Quote.less
Fixed pixel size fonts are bad, found one in the wild, so fixing it to rem.
Chrome dev tools.
=> feat: change font size in blockquotes

stylesheets/commons/Mainpage.less
After #5584 was reverted by #5718 due to LESS compile issues. This is a re-attempt at getting the working CSS with LESS compiler into the repo.
LESS online compiler, dev tools, and Alex also tested on dev wiki.
https://discord.com/channels/93055209017729024/1209065403955806270/1354549202792878191
=> feat(mainpage): re-attempt improve tournament list headers on Lakeside

stylesheets/commons/Mainpage.less
Total brain fart, got the new skin and the new mainpage mixed up in my head for #5723...
Changes the CSS qualifier to using mainpage v2 instead of the new skin.
Dev tools
=> fix(mainpage): apply new tournament list only on mainpage-v2

lua/wikis/commons/Widget/MainPage/NavigationCard.lua
format count number in nav cards on main pages with formatNum
requested on discord: https://discord.com/channels/93055209017729024/213614988647071744/1356017559216066726
dev
before:
after:
=> feat(mainpage): format numbers in nav cards

lua/wikis/commons/MatchGroup/Input/Util.lua, lua/wikis/leagueoflegends/MatchGroup/Input/Custom.lua
This PR updates leagueoflegends match2 to use `MatchGroupInputUtil.standardProcessMaps`
dev
=> refactor(match2): use standardProcessMaps in leagueoflegends

lua/wikis/commons/MatchTicker.lua
As discussed in module sync meeting:
Remove maximumLiveHours in query, should be handled by setting finished in match2 processing already.
TBD
=> feat(matchticker): Remove maximumLiveHours

lua/wikis/dota2/MatchGroup/Input/Custom.lua, lua/wikis/dota2/MatchGroup/Input/Custom/MatchPage.lua
This PR updates dota2 match2 to use `MatchGroupInputUtil.standardProcessMaps`
dev
=> refactor(match2): use standardProcessMaps in dota2

lua/wikis/fighters/GetMatchGroupCopyPaste/wiki.lua
Date, vod and stream are pretty much never used in fighters so being able to just not generating them makes sense. 
A toggle which prevent maps from being generated even if bestof is >0 was added as well. The option to set bestof to an accurate number in a large bracket and not have 100 of lines of maps added also is a pretty convenient on a wiki that uses large bracket very often.
=> feat(match2): add toggle for date, vod, stream, and maps in fighters generator

stylesheets/commons/Brackets.less
Updating color scheme for protect as it doesn't look good in darkmode. 
Text no readable 
Before:
After:
inspect mode
=> feat: update bg-color for map veto "protect"

lua/wikis/dota2/GetMatchGroupCopyPaste/wiki.lua
=> feat(match2): standardize template usage on dota2

lua/definitions/mw.lua, lua/wikis/commons/Namespace.lua, lua/wikis/commons/TournamentStructure.lua
currently if a namespace with undersocre (e.g. `User_talk:`) is used we get a nil return which can cause nil concats in some places
This PR fixes that issue by switching underscores to spaces in `Namespace.idFromName`
Also: fixed some annos for mw.site so an anno warning in `Module:Namespace` vanished
dev
=> fix: standard lib doesn't handle namespaces with underscore correctly

lua/wikis/worldofwarcraft/GetMatchGroupCopyPaste/wiki.lua
- ~~Replace all `{{Match}}` usages with `{{Match/old}}`~~ (No existing use)
N/A
=> feat(match2): standardize template usage on worldofwarcraft

lua/wikis/teamfortress/GetMatchGroupCopyPaste/wiki.lua
=> feat(match2): standardize template usage on teamfortress

lua/wikis/mobilelegends/MainPageLayout/data.lua
[Originally listed to show all tournaments upcoming in 75 days](https://liquipedia.net/mobilelegends/index.php?title=Main_Page&action=edit&oldid=69218), but the new page changed it to 60.
=> fix(mainpage): Restore MLBB's tournament upcoming defaults

lua/wikis/commons/Transfer/References.lua, lua/wikis/leagueoflegends/Info.lua, lua/wikis/valorant/Info.lua
Currently `CONTRACT_TYPE` has hardcoded values in Commons that are specific to League of Legends.
This PR extracts the hardcoded values to `Module:Info`, and makes TRef to read from the stored config instead.
This PR also adds contract database config for Valorant.
dev
=> feat(transfer): allow per-wiki settings for contract database TRef type

lua/wikis/commons/GetMatchGroupCopyPaste.lua, lua/wikis/dota2/GetMatchGroupCopyPaste/wiki.lua, lua/wikis/leagueoflegends/GetMatchGroupCopyPaste/wiki.lua
resolves #5605
~~Note: wouldn't work properly on dota2 until #5749 gets merged~~ mitigation: 25aad18...7121397
- [dota2:Special:RunQuery/MatchPageCopyPaste/dev](<https://liquipedia.net/dota2/Special:RunQuery/MatchPageCopyPaste/dev>)
- [leagueoflegends:Special:RunQuery/MatchPageCopyPaste/dev](<https://liquipedia.net/leagueoflegends/Special:RunQuery/MatchPageCopyPaste/dev>)
=> feat(match2): add matchpage support to copy-paste generator

lua/wikis/osu/FilterButtons/Config.lua, lua/wikis/osu/MainPageLayout/data.lua, lua/wikis/osu/Tier/Data.lua, stylesheets/commons/Banner.less
Setting up the new Main page on Osu!
Also adding Tier.Data. They don't wanna filter it by month and week.
They don't use it. No tournamnet of this usage.
Tested on https://liquipedia.net/osu/User:Sl0thyMan/Sandbox/2
Banner tested via inspect:
Opening as draft as I am still not sure if there are better pictures to use. 
Osu doesn't really have any usable photos for Teams/Transfers and Tournaments.
At least I didn't found any osu related
=> feat(mainpage): new Osu! main page

lua/wikis/commons/Links/Stream.lua
Cache stream links as wiki vars for performance improvements
dev
Perf diff:
https://liquipedia.net/honorofkings/King_Growth_League/2025/Spring/Group_Stage/Week_8-9
https://liquipedia.net/honorofkings/King_Growth_League/2024/Summer/Group_Stage/Second_Leg
Mind using dev makes things a tad slower as it adds the `Pages using dev modules` category for each called component. So in live the Perf diff will be bigger than in tests. (For the second screenshot it is ~180ms for the category adding alone)
=> feat: Cache Stream Links

lua/wikis/commons/Class.lua, lua/wikis/commons/Lua.lua
- reverts #5690 as per a report on discord it caused issues in rare cases
- does not add back the (not working) `frame.args.module = nil; frame.args.fn = nil`
- adjusts `Class.export` handling (in `Class._frameToArgs`) instead so it removes the module and fn args there
- needed because of the stupid way Class.export handles args ...
- bot over all invokes to use `Lua.invoke` wrapper
- plus fixing possible issues that arise during that
- prepare all modules that use `Class.export` to handle normal args table instead of the stuff with seperated unnamed args
- prepare templates regarding frameOnly
- let `Lua.invoke` use `Arguments.getArgs` so we can just use args in all modules instead of frame (if frame is needed outside of parsing args can just use `mw.getCurrentFrame()`)
- plus adding …
=> fix: Lua.invoke args adjust causing issues

lua/wikis/commons/MatchGroup/Display/Helper.lua, lua/wikis/commons/MatchPage/Base.lua, lua/wikis/commons/MatchSummary/Base.lua, lua/wikis/commons/Widget/Match/Page/Comment.lua, lua/wikis/commons/Widget/Match/Page/Footer.lua, lua/wikis/commons/Widget/Match/Summary/Casters.lua, lua/wikis/commons/Widget/Match/Summary/Ffa/GameDetails.lua, lua/wikis/commons/Widget/Match/Summary/Ffa/MatchInformation.lua, lua/wikis/dota2/MatchPage.lua, lua/wikis/leagueoflegends/MatchPage.lua, stylesheets/commons/BigMatch.less
resolves #5711
This PR also includes refactoring of substitute / caster comments as they were both needed for the match page.
dev + browser dev tools
=> feat(match2): comment display for match page

lua/wikis/osu/MainPageLayout/data.lua
osu naming issue. 
an oversight on my part.
https://osu.ppy.sh/wiki/en/Brand_identity_guidelines
none
=> fix(mainpage): osu! name fix

lua/definitions/mw.lua, lua/wikis/commons/Date/Ext.lua, lua/wikis/smash/Infobox/League/Custom.lua
The format string used in `DateExt.toYmdInUtc()` is going to always return a string value and should not be interpreted as a number. Cast the return value this way and changed annotation.
https://discord.com/channels/93055209017729024/874304000718172200/1355919729532862825
Tested in VS Code.
=> docs(date): Always return string type for `DateExt.formatTimestamp`

stylesheets/commons/BigMatch.less
Right now team logo in the updated matchpage layout (#5703) does not get aligned properly because the `display=flex` property set here
https://github.com/Liquipedia/Lua-Modules/blob/d898c7aec0fed7e358fe312cd9fa3d5b9c45b043/stylesheets/commons/BigMatch.less#L70-L74
gets overridden by this:
https://github.com/Liquipedia/Lua-Modules/blob/d898c7aec0fed7e358fe312cd9fa3d5b9c45b043/stylesheets/commons/TeamTemplates.less#L138-L142
This PR fixes this issue by creating a rule with higher specificity.
=> fix(match2): team icon in matchpage header not aligned properly in darkmode

lua/wikis/wildcard/MainPageLayout/data.lua
The layout defines category count to Arenas which is wrong category so main page will throw out **0**, but I have no plans to make a custom map infobox, so it should be **Maps** here.
=> fix(mainpage): Wildcard map categories

lua/wikis/fortnite/MainPageLayout/data.lua
Edit button is not working properly and linking to wrong page.
Fortnite editors switched their data formatting for trasnfers as they were hitting limits 
Player_Transfers/2024/1st_Quarter -> Player_Transfers/2025/April
From quarter to month format
dev
https://liquipedia.net/fortnite/User:Sl0thyMan/Sandbox/1
=> feat(mainpage): Fornite change transfer data formatting

lua/wikis/commons/Class.lua
Part of Option2 in #5818
if we go for this PR we need to do theis change to `Module:Arguments`:
https://liquipedia.net/commons/index.php?title=Module%3AArguments%2Fdev%2Fhjp2&type=revision&diff=860449&oldid=860445
Cleans up `Class.export`/`Class._wrapFunction` so it doesn't split up the args into named and unnamed anymore.
Additionally moves out the removal of the `dev`, `module` and `fn` arguments (which get added due to using the lua invoke wrapper) into `Module:Arguments` so they also get removed if Module:Class is not used. (see above suggested change to MOdule:Arguments)
https://liquipedia.net/commons/index.php?title=Module%3AArguments%2Fdev%2Fhjp2&type=revision&diff=860449&oldid=860445
dev
initial perf test show no diff for normal modules and a tiny improvement for modules using …
=> chore: clean up `Class._wrapFunction`

lua/wikis/deadlock/MainPageLayout/data.lua
Kick "nowiki" in updates. It does nothing.
Not sure why it was there in the first place.
inspect + modified wildcard [module](https://liquipedia.net/wildcard/Module:MainPageLayout/data) as it still in the PR https://github.com/Liquipedia/Lua-Modules/pull/5543
=> refactor(mainpage): remove unneeded <nowiki> on deadlock

lua/wikis/warcraft/Infobox/Building/Custom.lua, lua/wikis/warcraft/Infobox/Unit/Custom.lua
Requested change in discord https://discord.com/channels/93055209017729024/268719633366777856/1362066381595476140
They want function which already exist in building module to have in unit as in the new patch they need it.
+ typo + nill catches
dev
before/after:
=> feat(infobox): add support for armortype2 for Warcraft

lua/wikis/commons/Lua.lua
resolves #5752 
additionally kicks `loadDataIfExists` as per insource search (via [Fo's Tools Page](https://tools.liquipedia.0xff0000.dev/?view=search)) it is not used in any module (except some devs and archived ones)
dev
=> fix: `Lua.requireIfExists` not checking for existence of dev module in dev mode

lua/wikis/fighters/Info.lua
This change is a fix to a game title in fighters. 
Guilty Gear Xrd (ggxrd) is currently named and linked to Guilty Gear Xrd -SIGN- in this module, which is a mistake since SIGN is a version and not part of the game's title (Sign is one of the 3 versions of the game, the other 2 are already included in this module). 
Here's the link to the game page:
https://liquipedia.net/fighters/Guilty_Gear_Xrd
In addition to fixing the name/link for ggxrd, this change also adds SIGN as a separate parameter (ggxrds) because versions are also included in this module despite us not using them at the moment, since fighters combine different versions results into the parent game (which is a lot more user friendly). The logo remains the same for both ggxrd and ggxrds because there is no separate logo for …
=> feat: split ggxrd and ggxrds on Fighters 

lua/wikis/trackmania/Infobox/League/Custom.lua
Resolves https://github.com/Liquipedia/Lua-Modules/issues/5840
Add feature for Infobox League to read `highlighed` argument
Tested via [dev/soba](https://liquipedia.net/trackmania/Module:Infobox/League/Custom/dev/soba)
=> feat(infobox): Publishertier for Trackmania Infobox league 

lua/wikis/commons/Widget/Match/Page/TeamDisplay.lua
see https://github.com/Liquipedia/Lua-Modules/pull/5858#issuecomment-2818959445
dev
=> feat(match2): use display name for teams in match page header

lua/wikis/leagueoflegends/MatchGroup/Input/Custom.lua, lua/wikis/leagueoflegends/MatchPage.lua
Right now player names in LoL matchpages use the full player pagename for display instead of the "display name" (e.g., [Viper (Korean player)](https://liquipedia.net/leagueoflegends/Viper_(Korean_player)) instead of just Viper).
This PR changes this behavior to use display names instead.
dev
=> feat(match2): use display name for players instead of pagename in LoL match page

lua/wikis/fortnite/Infobox/Team/Custom.lua
fortnite still uses deprecated fields to condition on for their custom earnings overwrite in infobox team
this also causes award prizes to not be accounted for
dev
=> fix(infobox): fortnite infobox team using deprecated lpdb fields

lua/wikis/brawlstars/Infobox/Unit/Brawler/Custom.lua
Added support for the "Hypercharge" ability by introducing a new cell in the Brawler infobox and renaming the section title to "Abilities" for clarity.
The game has long featured the "Hypercharge" ability, but the infobox template did not support displaying this information. This change resolves that limitation by adding a dedicated field for Hypercharge, ensuring that all key brawler abilities are properly represented.
Pages with new version of Infobox: 
1. https://liquipedia.net/brawlstars/Shelly
2. https://liquipedia.net/brawlstars/8-Bit
**Before:**
**After:**
Now infobox supports Hypercharge and title renamed right.
=> feat(infobox): update abilities display in brawlstars unit infobox

lua/wikis/commons/Widget/MainPage/TransfersList.lua
Reported on discord: https://discord.com/channels/93055209017729024/372075546231832576/1362757042103914646
dev
=> fix(mainpage): footer links of transfer list widget overflowing in mobile

lua/wikis/commons/Player/Ext.lua, lua/wikis/commons/Player/Ext/Starcraft.lua
as per search with https://tools.liquipedia.0xff0000.dev/?view=search there is no usage of this, hence we can remove it
N/A
=> chore: remove unused `fetchMatch2Player` option

lua/wikis/rainbowsix/Info.lua
Given the game's development has been slowed down quite significantly (it's still on testing), but there has been some Community-ran events during the Beta test, might be worth having R6 Mobile events co-exist in the R6 wiki for the time being until they have expanded competitive enough that warrants its own standalone wiki. If not then at least we have a place to document it
this can be merged right away since Siege X is two months away, R6M as a game is two years old at this point
The co-exist, then potential split later is also the approach internally being considered at for VALORANT Mobile as well (albeit w/o Info.lua changes)
=> feat: Add R6 Mobile to R6 wiki

lua/wikis/commons/MatchesScheduleDisplay.lua
reported on discord: https://discord.com/channels/93055209017729024/372075546231832576/1364333175467409428
additionally fixed a wrong anno in the same line
=> fix(MatchesScheduleDisplay): not accounting for possibility of non-string args keys

stylesheets/commons/BigMatch.less
Right now, if the display name of opponent 1 is too long, the split parts of the name gets aligned on the left.
This PR changes the text to be aligned on the right.
before:
after:
=> feat(match2): make team name alignment consistent in match page header

lua/wikis/ageofempires/Infobox/League/Custom.lua, lua/wikis/ageofempires/Infobox/Person/Player/Custom.lua, lua/wikis/commons/MatchTicker/Custom.lua
Switches Infobox player and league to the standard matchticker on AoE
dev
=> feat: Migrate AoE to standardized matchticker for players and tournaments

lua/wikis/ageofempires/Tier/Data.lua, lua/wikis/brawlhalla/Tier/Data.lua, lua/wikis/brawlstars/Tier/Data.lua, lua/wikis/counterstrike/Tier/Data.lua, lua/wikis/criticalops/Tier/Data.lua, lua/wikis/easportsfc/Tier/Data.lua, lua/wikis/formula1/Tier/Data.lua, lua/wikis/honorofkings/Tier/Data.lua, lua/wikis/mobilelegends/Tier/Data.lua, lua/wikis/osu/Tier/Data.lua, lua/wikis/overwatch/Tier/Data.lua, lua/wikis/pubg/Tier/Data.lua, lua/wikis/rainbowsix/Tier/Data.lua, lua/wikis/rocketleague/Tier/Data.lua, lua/wikis/sideswipe/Tier/Data.lua, lua/wikis/splatoon/Tier/Data.lua, lua/wikis/splitgate/Tier/Data.lua, lua/wikis/starcraft/Tier/Data.lua, lua/wikis/starcraft2/Tier/Data.lua, lua/wikis/stormgate/Tier/Data.lua, lua/wikis/tetris/Tier/Data.lua, lua/wikis/wildrift/Tier/Data.lua, lua/wikis/worldoftanks/Tier/Data.lua, lua/wikis/zula/Tier/Data.lua, stylesheets/commons/TournamentTags.less
Fixes the bad display of misc-tournaments that also have a tiertype set on the mainpage.
dev and inspect
Before:
After:
=> fix: Correctly display tournament tags with Tier Misc and tiertype

lua/wikis/tft/MatchGroup/Input/Custom.lua, lua/wikis/tft/MatchSummary.lua
as per request on discord allow empty/missing map name input on maps in standard matches on tft
as stated on discord they seem to not have map names quite often
dev
=> feat(match2): allow empty map(name) input in maps on tft

lua/wikis/commons/ResultOrError.lua
Closes #5870 
There is a tiny difference between dev/no-dev mode, where the dev error message also includes the line in ResultOrError.lua, as that is where the error is rethrown
dev (on a long chain of manually imported dev modules, as the modules isn't Lua.imported)
Before:
Before, no dev:
After:
=> fix: Correctly display import errors when in dev mode

stylesheets/commons/Mainpage.less
The game icons had a vertical offset when compared to the tournament icons, as well as different spacing between components
inspect
Before:
After:
=> fix: Correct vertical offset of game icons in tournaments ticker

lua/wikis/counterstrike/Infobox/Patch/Custom.lua
initial report: https://discord.com/channels/93055209017729024/372075546231832576/1365962895224995881
something that slipped through in #5766...
hotfix in live
=> fix(infobox): counterstrike patch infobox reading incorrect argument in chronology

lua/wikis/ageofempires/Faction/Data.lua
Adds suffixes used to disambiguate civilization pages where missing.
When civs exist in multiple games, the plain `Civname` page is used as a disambiguation page, and all links should directly go to `Civname/Gamename` pages if possible.
N/A
=> fix: Disambiguate some faction links on AoE

lua/wikis/tft/MatchGroup/Input/Custom.lua
Currently empty maps show on tft wiki
this is mostly due to the match date making the map table not empty when doing the removal check
Due to tft not relying on the number of inputted maps for bestof calculations the solution proposed in this PR is to just kick the removal function and instead enable the break on empty option as done on other wikis that have a similar bestif handling
dev
=> fix(match2): tft bestof processing inconsistent with map removal

lua/wikis/commons/MatchTicker/DisplayComponents.lua
When https://github.com/Liquipedia/Lua-Modules/blob/95994e526aebe6967358828b13f76fcfee5ce435/lua/wikis/commons/MatchTicker.lua#L443 is applied, the DisplayComponent would fail due to the field being nil.
While in the specific case I'm not sure whether this game unpacking is actually intended to happen, that's another thing to investigate.
dev to live
=> fix: Handle removed match2games in matchticker

stylesheets/commons/Bracket.less
The match pop up icon in match result lists on the Head to Head query pages should be centered on the border between the two result cells, at the moment it is not. it looks like roughly a 7px difference between what it is and what it should be, this might also be due to the size of the cells differing which means maybe this should be an equation to figure out the spacing, but I am not sure where else this class is used.
dev tools
=> fix: dota2 h2h icon alignment

lua/wikis/commons/MatchGroup/Input/Starcraft.lua
when retrieving it is expected to be lowercased, resulting in currently the subgroup headers not showing
N/A
=> fix(match2): wrong capitalisation in extradata key

lua/wikis/ageofempires/FilterButtons/Config.lua
Another leftover that isn't supposed to be rolled out; AoE community is quite diverse so we want to give a neutral starting point.
Didn't notice since i had dirty localstorage on the test page.
live
=> fix: Remove default tiers in AoE filterbuttons

lua/wikis/rainbowsix/Tier/Data.lua
1. Currently on the R6 wiki we use "Misc" for events with Point Rankings, it might be easier for viewers to understand when "Point Rankings" is used as text/tierType instead of "Misc". (See attached pictures for the current example)
2. Same will happen for the Award Section, since we currently show quite a few Award Shows on the wiki it may be better to display that instead of Misc.
Current list of all events under "Misc.": https://liquipedia.net/rainbowsix/Miscellaneous_Tournaments
No test, just added "points" and "award" to the /Data.
I know that once merged the "|tierType=" need to be updated on the pages where needed, this is no problem and can be done afterwards.
=> feat: add R6 points and award as TierType

lua/wikis/leagueoflegends/MatchPage.lua, stylesheets/commons/BigMatch.less
regression from #5703
dev
before
after
=> fix(match2): lol matchpage does not display game length for bo1 matches

lua/wikis/valorant/MatchPage.lua
A header listing basic information about the match, like date, tournament, streams, participants, and score
=>  feat: Implement valorant match page header & footer

lua/wikis/valorant/Info.lua, lua/wikis/valorant/MatchSummary.lua
As a user, I want to be able to dive deeper into checking (or adding!) match details, while browsing the main page or the matches portal.
=> feat: add match page buttons to VAL matchticker

lua/wikis/commons/Tier/Utils.lua
as it is still used by several wikis of whom several want to keep it, i think we should un-deprecate `Tier.toNumber`
(also gets rid of some anno warnings)
wikis that currently use it:
- aoe
- brawlhalla
- cs
- fighters
- smash
- val
VSCode
=> docs(Tier): un-deprecate `Tier.toNumber`

lua/wikis/commons/Lpdb.lua
Added `datapoint` as a model to the LPDB module so that it can be used to store arbitrary datapoint items.
Tested on `/dev` and it seems to work as intended (at least for storage).
| Code | LPDB |
| ![image](https://github.com/user-attachments/assets/97ad2b4a-89f4-40a7-90f2-63fe4c1b1276) | ![image](https://github.com/user-attachments/assets/1006a79e-1bf6-4d20-b661-3f75330aecd8) |
=> feat(lpdb): add `datapoint` Model to Lpdb module

lua/wikis/wildcard/MainPageLayout/data.lua
Devs have provided a series of new artworks for both the header and the pills. 
Pills had some different file extension vs the old one so I uploaded these separately hence the filename changes all of them now in PNG (and I couldnt recall why I was randomly putting JPG/WEBP in among the PNG pills at first lol)
Header doesnt it's just the same webp so I uploaded the banner as new version over the same file hence no changes on the css
=> feat(mainpage): Wildcard new pill images

lua/wikis/fighters/PrizePool/Custom.lua
initial report: https://discord.com/channels/93055209017729024/202549269134180352/1368388143836954644
> It looks like match2 made it so disambiguated tags appear in the learderboards as full links. e.g. Yagami (Australian Player) instead of just Yagami
dev into live
=> fix(prizepool): fighters ppt saving incorrect display names for leaderboard

lua/wikis/commons/OpponentLibraries.lua
As a side effect of #5742, type annotations in OpponentLibraries do not correctly pick up `Module:Opponent` and `Module:OpponentDisplay`. This PR updates these annotations for them to work properly again.
vscode
=> chore: fix OpponentLibraries type annotation

lua/spec/condition_spec.lua, lua/wikis/commons/Condition.lua
This PR adds `__tostring` metamethod to condition nodes, allowing the builtin `tostring` function to be used with it.
189c7f2
=> feat: add tostring support to condition nodes

lua/wikis/apexlegends/MainPageLayout/data.lua, lua/wikis/arenafps/MainPageLayout/data.lua, lua/wikis/brawlstars/MainPageLayout/data.lua, lua/wikis/callofduty/MainPageLayout/data.lua, lua/wikis/commons/Widget/MainPage/TransfersList.lua, lua/wikis/deadlock/MainPageLayout/data.lua, lua/wikis/dota2/MainPageLayout/data.lua, lua/wikis/fortnite/MainPageLayout/data.lua, lua/wikis/freefire/MainPageLayout/data.lua, lua/wikis/geoguessr/MainPageLayout/data.lua, lua/wikis/halo/MainPageLayout/data.lua, lua/wikis/hearthstone/MainPageLayout/data.lua, lua/wikis/heroes/MainPageLayout/data.lua, lua/wikis/marvelrivals/MainPageLayout/data.lua, lua/wikis/mobilelegends/MainPageLayout/data.lua, lua/wikis/osu/MainPageLayout/data.lua, lua/wikis/starcraft2/MainPageLayout/data.lua, lua/wikis/worldoftanks/MainPageLayout/data.lua
This PR simplifies `transferPage` prop of mainpage transfer list widget so that it takes `string` instead of `fun(): string`.
dev in LoL / SC2
=> refactor(mainpage): simplify transferPage param for transfer list widget

lua/wikis/wildcard/MainPageLayout/data.lua
It turns out that the **Wildcard** game mechanics header, we actually misspelled it. Devs corrected this to us as **Wild Cards** (not to be confused, this is one of the game's mechanic, not referring to the game's name)
=> fix(mainpage): Wildcard header naming

lua/wikis/rainbowsix/Infobox/Character/Custom.lua
This PR updates the rainbowsix character infobox to use `StandardPatch` for querying patches.
dev
=> refactor(infobox): use StandardPatch in rainbowsix character infobox

lua/wikis/commons/Standings.lua
resolves #5915
the index seems stored as a string which leads to 9 being considered larger than 10 etc.
Hence causing only to show up to 9 rounds
dev
=> fix(Standings): `Template:ShowStandings` only showing up to 9 rounds

lua/wikis/rainbowsix/Tier/Data.lua
Fixed the mismatch in key/value so the TierType will be shown instead of Undefined
Fixed the typo so both the key and the value match exactly which should result in Undefined to show the correct tiertype.
(I am aware that I need to manually update the `|...tiertype` in the infobox on the pages where currently `|...tiertype=Award` is used)
<hr/>
> https://liquipedia.net/rainbowsix/Spoit
No test, found the answer in the discord: 
> https://discord.com/channels/93055209017729024/268719633366777856/1128675422264107129
<hr/>
=> fix: Mismatch in "key" and "value" Tier/Data R6

stylesheets/commons/Miscellaneous.less
This makes it so the "in memory of" banner on mainpages has the right border radius to fit with the new main page panels
https://liquipedia.net/leagueoflegends/Main_Page has this coded in already
=> feat: update sadbox styling to match new mainpages

lua/wikis/valorant/MatchGroup/Input/Custom.lua
We need to store the publisher matchid if available
=> feat(match2): store valorant matchid if available

lua/wikis/dota2/GetMatchGroupCopyPaste/wiki.lua
This PR kicks `bestof` param from Dota2 copy-paste generator.
dev
=> chore(match2): kick bestof param from dota2 copy-paste generator

stylesheets/commons/BigMatch.less
Map image inside mapveto card should zoom in when hovering anywhere over it. However, it is triggered only when the cursor is directly over the image. This PR adjusts the hover trigger so that the original behavior is restored.
Browser dev tools
=> fix(match2): map image zoom not triggered when hovering over mapveto title

lua/definitions/mw.lua, lua/wikis/dota2/MatchGroup/Input/Custom.lua
This PR:
- adds `mw.uri` library specification (adapted from MediaWiki Lua reference manual)
- cleans up head-to-head link generator using `mw.uri`
dev
=> refactor(match2): clean up head-to-head link generator in dota2

lua/wikis/brawlstars/MainPageLayout/data.lua
Shuffling widget positions
**Want To Help?** widget moved to the right.
And some **mobileOrder** changes
https://liquipedia.net/brawlstars/Main_Page/Sandbox
=> feat(mainpage): update content order in brawlstars mainpage

lua/wikis/commons/MatchPage/Base.lua, lua/wikis/commons/Widget/Match/Page/Header.lua
This PR adds highlight (as specified by `Module:HighlightConditions`) to the match page header.
dev: <https://liquipedia.net/leagueoflegends/Match:ID_User_ElectricalBoy_zqx7pe0nDj_R01-M001>
=> feat(match2): add tournament highlight to match pages

lua/wikis/valorant/MatchPage.lua
https://github.com/Liquipedia/Lua-Modules/blob/ea15d3fe5c9b0f6b7736322faff2dc8001b36d83/lua/wikis/valorant/MatchPage.lua#L95
`startOvertime` is always `nil` if no overtime rounds are played. This causes `not startOvertime` to evaluate to `true`, resulting as an empty table being returned, i.e., normal round scores are not returned. As a result of this, round scores are not displayed in game summaries in desktop environments.
This PR adjusts logic in this function so that normal round scores are properly returned.
dev
=> fix(match2): round scores are not displayed in valorant match pages on desktop environments

lua/wikis/commons/OpponentDisplay/Starcraft.lua
the score display with 2 decimal places only happens if advantage/penalty is set
this PR accounts for these edge cases
dev
=> fix: some components show score with 2 decimal places

lua/wikis/commons/MainPageLayout.lua
> Call a [parser function](https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Magic_words#Parser_functions), returning an appropriate string. This is preferable to `frame:preprocess`, but whenever possible, native Lua functions or Scribunto library functions should be preferred to this interface.
> 
> [MW Lua Reference Manual](https://www.mediawiki.org/wiki/Extension:Scribunto/Lua_reference_manual#frame:callParserFunction)
dev: <https://liquipedia.net/leagueoflegends/User:ElectricalBoy/MainPage>
=> refactor(mainpage): replace preprocessing with callParserFunction

lua/wikis/valorant/MatchGroup/Input/Custom/MatchPage.lua
Now that the values are 1-based instead of 0, we got a bunch of off-by-ones. Let's fix it
dev
=> feat(match2): change valorant round numbers to 1-based

lua/wikis/valorant/GetMatchGroupCopyPaste/wiki.lua
`|finished=` param in Valorant match2 is mostly redundant as the system automatically handles it if not specified. Let's remove it.
trivial string change
=> chore(match2): remove finished param from Valorant match2 copy-paste generator

lua/wikis/valorant/MatchGroup/Input/Custom/MatchPage.lua
=> docs(match2): fix incorrect return type annotation in valorant match page map parser

lua/wikis/wildcard/Infobox/Unit/Custom.lua
Game is having a major rework soon, this includes the Unit module requiring some changes in display, most notably is the base stat values which is just the same as Character Infobox. 
Previously these stats is put under a SpellCard but now  each summon would have their own ability, we decide on moving these back to the infobox just like Characters it's more consistent that way. Outside of that is a new stat called Sight Range.
LIVE https://liquipedia.net/wildcard/Beakit
=> feat(infobox): Unit rework for Wildcard

lua/wikis/commons/ExternalMediaList.lua, lua/wikis/commons/OpponentDisplay.lua, lua/wikis/commons/PortalPlayers.lua, lua/wikis/commons/Widget/Image/Icon.lua, lua/wikis/commons/Widget/Image/Icon/TeamIcon.lua, lua/wikis/commons/Widget/TeamDisplay/Component/Name.lua, lua/wikis/commons/Widget/TeamDisplay/Inline.lua, lua/wikis/easportsfc/PortalPlayers/Custom.lua, lua/wikis/formula1/Infobox/Team/Custom.lua, lua/wikis/formula1/PortalPlayers/Custom.lua, lua/wikis/leagueoflegends/Infobox/Team/Custom.lua, lua/wikis/valorant/Infobox/Team/Custom.lua
_Cherry-picked from #5649_
This PR introduces inline display widgets for team templates, removing uses of `Team.team`, `Team.icon`, etc.
dev
=> feat: Inline team display widgets

.github/workflows/luacheck.yml
This PR mitigates #5979.
Full fix would be bumping `leafo/gh-actions-lua` to latest once it gets updated.
https://github.com/Liquipedia/Lua-Modules/actions/runs/15553601405
=> ci: use snapshot version of gh-actions-lua

lua/wikis/commons/Widget/Match/Page/Header.lua
Prevents the matchpage from showing -1 scores on non-score results.
Also makes it future-proof for eventual float scores.
dev
=> fix: Use OpponentDisplay.InlineScore on match pages

lua/wikis/commons/Widget/NavBox/Child.lua
in some edge cases an empty child is intended, hence soften the check for empty children to have an overwrite option that allows an empty child
dev
=> feat(navBox): allow empty child overwrite

lua/wikis/commons/I18n/Data.lua, lua/wikis/commons/Widget/Match/Summary/MapVetoStart.lua
This PR:
- replaces arrow images being used for start indicators with fontawesome icons
The original images were gray in color, making them hard to see under darkmode
- refactors hardcoded html string to separate widget
dev
=> refactor(match2): clean up mapveto start widget

lua/wikis/commons/TournamentStructure.lua
Sometimes groups are spread across several pages due to runtime/memory limitations and making them easier to edit.
If those groups consist of brackets instead of groupTables this currently means we can not import them in prize pool due to the prize pool assuming the brackets belong to different stages.
To be able to fetch data from different pages for the same stage this PR adds the option to input several pagenames into the tournamentX parameters with `||` (in wikicode `{{!}}{{!}}`) as delimiter (this delimiter can not be used in pagenames, and hence is imo preferabel to others that could be used in pagenames).
example code (on sc2):
```wiki
{{SoloPrizePool|qualifies1=Esports_World_Cup/2025|qualifies1name=Esports World Cup 2025|dev=hjp …
```
=> feat(Import): Add support to merge several pages into a stage during import

lua/wikis/commons/TournamentStructure.lua
`args.tournament` was inserted before the loop in which the handling was adjusted.
As a solution just made the `pairsByPrefix` not require index for this loop and kick the extra line above
dev
=> fix: args.tournament not parsed correctly

lua/wikis/ageofempires/Info.lua, lua/wikis/apexlegends/Info.lua, lua/wikis/brawlstars/Info.lua, lua/wikis/commons/Service/Team.lua, lua/wikis/commons/Widget/NavBox/AutoTeam.lua, lua/wikis/commons/Widget/NavBox/AutoTeam/Player.lua, lua/wikis/counterstrike/Info.lua, lua/wikis/fighters/Info.lua, lua/wikis/formula1/Info.lua, lua/wikis/fortnite/Info.lua, lua/wikis/smash/Info.lua, lua/wikis/starcraft2/Info.lua, lua/wikis/starcraft2/Squad/Custom.lua, lua/wikis/tft/Info.lua, lua/wikis/valorant/Info.lua
Based on something Rath send me via DMs.
I just added some stuff to it :P
live (new modules) /dev (existing modules)
https://liquipedia.net/starcraft2/User:Hjpalpha/wip13
=> feat: Team Roster NavBox

lua/wikis/honorofkings/Infobox/Person/Player/Custom.lua, lua/wikis/leagueoflegends/Infobox/Person/Player/Custom.lua, lua/wikis/valorant/Infobox/Person/Player/Custom.lua, lua/wikis/wildrift/Infobox/Person/Player/Custom.lua
Moving remaining wikis that have AutoPI calls in their Infobox Template into the Lua Infobox instead
First part of #6009
At deploy the following templates needs to be updated:
https://liquipedia.net/wildrift/index.php?title=Template:Infobox_player&action=edit
https://liquipedia.net/honorofkings/index.php?title=Template:Infobox_player&action=edit
https://liquipedia.net/leagueoflegends/index.php?title=Template:Infobox_player&action=edit
https://liquipedia.net/valorant/index.php?title=Template:Infobox_player&action=edit
https://liquipedia.net/valorant/index.php?title=Template:Infobox_commentator&action=edit
Tested on HoK
=> feat(infobox): move AutoPI into infobox

lua/wikis/commons/Widget/NavBox/EditButton.lua
Currently edit link in navboxes just links to the page instead of actually opening it in a way so you can start editing directly.
This PR adjust the behaviour accordingly.
dev
=> fix(NavBox): edit link  not opening page to edit

lua/wikis/commons/Widget/NavBox/Transfer.lua
generates an automated navbox for transfer pages
"live" (new module)
example on sc2:
example on val (the bad month order is due to wrong transfer dates on the pages that are shifted, e.g. the may 2025 one has a transfer from 2024 ...):
=> feat(NavBox): add lpdb auto generated transfer navbox

lua/wikis/commons/Widget/NavBox/Transfer.lua
Add more options/cases based on feedback on discord
- some wikis use different patterns for pages with unsourced transfers
- some wikis have transfer pages by year
- some wikis have misc pages that contain a year
dev
=> feat(NavBox): add more cases in transfer navbox

lua/wikis/commons/MatchGroup/Util.lua
https://github.com/Liquipedia/Lua-Modules/blob/1f7c686c1c94d1aa82351d68f47ae79623cf3a90/lua/wikis/commons/MatchGroup/Util.lua#L275
N/A
=> docs(match2): fix incorrect type annotation in MatchGroupUtil

lua/wikis/marvelrivals/NotabilityChecker/config.lua
With the updated Notability Guidelines of 2025-06-02 was a change in how notability points for qualifiers were distributed, see [Marvel Rivals Notability Guidelines](https://liquipedia.net/marvelrivals/Liquipedia:Notability_Guidelines). See also request in [Discord ](https://discord.com/channels/93055209017729024/268719633366777856/1384644881212899428) about this topic
Simple number change and im not smart enough to invoke a config/dev in the Special:RunQuery/Notability_Checker
=> feat(notability): Adjust notability gain from qualifiers for marvelrivals

lua/wikis/commons/Infobox/Person/Player/Custom.lua
Add a default custom for infobox player so that new wikis can use it out of the box.
With #5808 the choice for THA/autoTeam will get moved to Module:Info, hence the need for custom just to decide on that should be eliminated.
untested but trivial
=> feat(infobox): Add default player infobox custom

lua/wikis/ageofempires/MatchGroup/Input/Custom.lua, lua/wikis/commons/MatchGroup/Input/Util.lua
Allows to "inherit" map dates onto subsequent maps when enabled via Parser flag.
Sometimes groups of maps are played at the same date; this allows to enter the date only for the first map, and inherits it to following maps until a different date is put in.
Also enable it on AoE.
dev
=> feat: Allow to inherit map dates

lua/wikis/ageofempires/Infobox/Patch/Custom.lua, lua/wikis/commons/Infobox/Patch.lua, lua/wikis/heroes/Infobox/Patch/Custom.lua, lua/wikis/rocketleague/Infobox/Patch/Custom.lua, lua/wikis/runeterra/Infobox/Patch/Custom.lua, lua/wikis/squadrons/Infobox/Patch/Custom.lua, lua/wikis/underlords/Infobox/Patch/Custom.lua, lua/wikis/wildrift/Infobox/Patch/Custom.lua
Port `Template:Infobox patch` on
this PR drops unused functionality from those infoboxes
dev where reasonable
aoe: version = args.version, -- todo: check usage and eliminate in follow up
- merge (adds additional storage of version int `information` (blank until now)
- purge run
- adjust consumers
- follow up pr to kick the additional storage in extradata
=> feat(Infobox): Port remaining patch infoboxes

lua/wikis/commons/Date/Ext.lua, lua/wikis/commons/Widget/NavBox/Transfer.lua
as per request on discord:
For transfer navbox add the current month/quarter/year (depending which is applicable) if in the same year of the latest query result (or january of the year after to account for year switches).
Also fixes a few issues that were reported on discord
dev
=> feat(NavBox): "always" show current month/quarter/year

lua/wikis/commons/Widget/NavBox.lua
If Navboxes are used outside of main and user space it is likely they are used on pages without infobox nor HDB, hence they would always show collapsed there (unless it having <=3 rows), even if used at the bottom of pages.
Due to that allow for non user/main namespaces to set uncollapse via `|collapsed=false`.
report on discord: https://discord.com/channels/93055209017729024/268719633366777856/1385295529017085953
suggestion for restricting it by namespace: https://discord.com/channels/93055209017729024/268719633366777856/1385337232738750615
(credits go to igeneral)
dev
=> feat(NavBox): Allow uncollapsed overwrite outside of main and user space

lua/wikis/chess/Infobox/League/Custom.lua
Chess contains a series of tournaments for the **computer chess** or **chess platform/engines** - https://en.wikipedia.org/wiki/Top_Chess_Engine_Championship 
I believe it would be ideal to give these events its own restrictions indicator, allowing tournaments portal to contain a filtered section just for these, the updated name will be **computer** for clarity
LIVE https://liquipedia.net/chess/Top_Chess_Engine_Championship/Cup_15
=> feat(Infobox): Add new restriction inputs

lua/wikis/commons/MatchTicker.lua, lua/wikis/commons/MatchTicker/DisplayComponents.lua
closes #5987 
On AoE it is somewhat common that longer series get stretched over multiple days; they thus have different dates set on specific games.
Since the matchticker expands these games into separate entries, they pollute the mainpage massively.
This "merges" games that share the same date together.
Currently, scores shown will be of the first game of that group - not sure if we want more elaborate display there, or even no score at all.
dev
before
after
=> feat: Let matchticker group expanded games that share the same date

lua/wikis/heroes/Infobox/Team/Custom.lua
adjusts heroes infobox team to be able to use it for `Template:Infobox tespateam` too (and hence be able to nuke that template)
dev
=> feat(infobox): adjust heroes infobox team

lua/wikis/commons/Infobox/Weapon.lua, lua/wikis/counterstrike/Infobox/Weapon/Custom.lua, lua/wikis/pubgmobile/Infobox/Weapon/Custom.lua
- old one had no usage, so move `Template:Weapon info` into its place and adjust the module accordingly
not converting fortnite in this PR.
for fortnite it might be good to do weapon infobox together with item infobox as they share lots of stuff
dev
=> feat(infobox): add weapon custom infoboxes

lua/wikis/leagueoflegends/MatchPage.lua
context: https://discord.com/channels/93055209017729024/1123585175729741824/1387328315177566329
blame @PiddyNydra :p
dev
=> feat(match2): reorder stats display in lol matchpage

lua/wikis/leagueoflegends/MatchGroup/Input/Custom/MatchPage.lua, lua/wikis/leagueoflegends/MatchPage.lua
Add Rift Heralds, Atakhan and Void Grubs to the objectives panel
=> feat(match2): add additional objectives to league of legends match pages

lua/wikis/starcraft/Infobox/Person/Player/Custom.lua
In the Broodwar wiki, the player infobox applies a race category, but the category applied are "P Players", "T Players", "Z Players" instead of "Protoss Players", "Terran Players" and "Zerg Players" respectively.
Examples:
* https://liquipedia.net/starcraft/Soma
* https://liquipedia.net/starcraft/Free
`dev=enuaj`
=> fix(infobox): faction category has initial letter instead of full name in StarCraft's player infobox

lua/wikis/chess/MainPageLayout/data.lua
Chess Transfer pages are year-based
the current setup actually missed out this config causing the [edit] button to be month-based by accident
/dev/h2
=> feat(mainpage): change chess transfer links to yearly

lua/wikis/overwatch/Infobox/League/Custom.lua
Add a "marginalized gender" input to the infobox league custom. Use the new input for a tracking category "Marginalized Gender Tournaments".
Im not sure if this should also be stored into LPDB?
dev
=> feat(Infobox): add tracking categorie for marginalized gender tournaments on overwatch

lua/wikis/simracing/MatchGroup/Input/Custom.lua
Add some simple storage for simracing, we need it on the API for `<secret>`
https://liquipedia.net/simracing/User:Rathoz
=> feat(match2): add storage support for simracing

lua/wikis/rematch/Infobox/League/Custom.lua
This displays the number of participants (teams or players) in the infobox.
Here: https://liquipedia.net/rematch/Rematch_Elite_Series/North_America
To test: `|dev=mej`
=> feat(infobox): add participants number to rematch infobox league

lua/wikis/dota2/Links/CustomData.lua
rework of #6072 in a more proper way
dev (`|dev=hjp`)
=> feat(dota): adjust blasttv link for dota

lua/wikis/rematch/GetMatchGroupCopyPaste/wiki.lua, lua/wikis/rematch/MatchGroup/Input/Custom.lua, lua/wikis/rematch/MatchSummary.lua
Match2 setup for new wiki **Rematch**
The starting reivsion will be a paste of **GOALS** wiki with no changes  as that's where contributor have been pre-documenting Rematch events there, so a simple setup we need just only Game X and map scores on each side.
LIVE
https://liquipedia.net/rematch/Early_Access_Tournament/Europe
#Notes
Includes all three file: Input, Summary and CopyPaste
=> feat(Match2): Rematch implementation

lua/wikis/commons/Infobox/Effect.lua, lua/wikis/commons/Infobox/Effect/Custom.lua, lua/wikis/hearthstone/Infobox/Character/Custom.lua, lua/wikis/hearthstone/Infobox/Effect/Custom.lua
- add a base + custom `Infobox/Effect` for `Template:Infobox hero power`
- adjust the existing `Module:Infobox/Character/Custom` to be able to handle `Template:Infobox class` (as it currently already does) and additonally `Template:Infobox hero`
dev
=> feat(infobox): Add HS Infobox hero and hero power

lua/wikis/dota2/MainPageLayout/data.lua
The ranking has been launched, we now want it to settle into a more permanent place a bit further down the page.
Ricci did this on the wiki.
=> feat: Adjust main page and esports portal on dota2 to move rankings down a bit

lua/wikis/rocketleague/FilterButtons/Config.lua, lua/wikis/rocketleague/MainPageLayout/data.lua, stylesheets/commons/Banner.less
This PR adds new mainpage config for Rocket League.
https://liquipedia.net/rocketleague/User:ElectricalBoy/MainPage
=> feat(mainpage): new rocketleague main page

lua/spec/prize_pool_spec.lua, lua/wikis/ageofempires/PrizePool/Award/Custom.lua, lua/wikis/ageofempires/PrizePool/Custom.lua, lua/wikis/apexlegends/PrizePool/Custom.lua, lua/wikis/brawlstars/PrizePool/Custom.lua, lua/wikis/commons/PrizePool/Award/Placement.lua, lua/wikis/commons/PrizePool/Award/Starcraft.lua, lua/wikis/commons/PrizePool/Custom.lua, lua/wikis/commons/PrizePool/Placement.lua, lua/wikis/commons/PrizePool/Starcraft.lua, lua/wikis/counterstrike/PrizePool/Custom.lua, lua/wikis/dota2/PrizePool/Custom.lua, lua/wikis/formula1/PrizePool/Custom.lua, lua/wikis/fortnite/PrizePool/Custom.lua, lua/wikis/halo/PrizePool/Custom.lua, lua/wikis/leagueoflegends/PrizePool/Custom.lua, lua/wikis/mobilelegends/PrizePool/Custom.lua, lua/wikis/overwatch/PrizePool/Custom.lua, lua/wikis/pokemon/PrizePool/Custom.lua, lua/wikis/pubg/PrizePool/Custom.lua, lua/wikis/pubgmobile/PrizePool/Custom.lua, lua/wikis/rainbowsix/PrizePool/Custom.lua, lua/wikis/rocketleague/PrizePool/Custom.lua, lua/wikis/tetris/PrizePool/Custom.lua, lua/wikis/trackmania/PrizePool/Custom.lua, lua/wikis/valorant/PrizePool/Custom.lua, lua/wikis/warcraft/PrizePool/Custom.lua
prereq:
some wikis currently store `points2`
some wikis have the desire to have such storage too
goal is to avoid more customs and instead store `points2` via commons renaming it to `prizepoints2` to be in line with the already via commons stored `prizepoints`
storing `prizepoints2` also allows removing the custom storages of `points` and `points2` (due to already preping all consumer modules)
dev
=> feat(prizePool): store prizepoints2

lua/wikis/paladins/GetMatchGroupCopyPaste/wiki.lua
- ~~Replace all `{{Match}}` usages with `{{Match/old}}`~~ (No existing use)
- ~~Archive local version of `{{Match}}`~~ (does not exist)
N/A
=> feat(match2): standardize template usage on paladins

javascript/commons/Collapse.js
Because of not using an arrow function, `this` became rebound. Fixed this
dev wiki
=> fix: show and hide all buttons

lua/wikis/commons/Widget/Match/Ticker/Container.lua
The "Show Countdown" is only visible when on default tier filters, any API call would override the entire ticker, of which the countdown was now a part of. Moving the part which gets overriden by the API call into a div one step lower (splitting up the html attributes really)
dev
=> fix: match ticker "show countdown" is only visible with default filters

lua/wikis/marvelrivals/MainPageLayout/data.lua
Removes the HeroTable on Main page as requested on discord: https://discord.com/channels/93055209017729024/1316071697555914804/1390401952793497742
[dev](https://liquipedia.net/marvelrivals/Module:MainPageLayout/data/dev/Rocketdog)
=> feat(mainpage): remove marvel rivals heroes table

lua/wikis/commons/TeamTemplate.lua
the removed line is not needed as the function that gets called in the line after it already does the according replacement of its own
N/A
=> chore: remove unneeded string replace

lua/wikis/rematch/Infobox/League/Custom.lua
Platform indication in Infobox League, due to the game doesnt have CrossPlay yet at launch
|dev=h2 - https://liquipedia.net/rematch/index.php?title=Module:Infobox/League/Custom/dev/h2&action=edit
There's an earlier revision that I can't get it to display https://liquipedia.net/rematch/index.php?title=Module:Infobox/League/Custom/dev/h2&oldid=132 no idea why, so I went with what's in this PR instead
=> feat(Infobox): Add Infobox League for Rematch

lua/wikis/ageofempires/Infobox/Unit/Custom.lua, lua/wikis/artifact/Infobox/Unit/Custom.lua, lua/wikis/clashroyale/Infobox/Unit/Custom.lua, lua/wikis/hearthstone/Infobox/Unit/Custom.lua
depends on #6108 (for the aoe icon widgets) and #6109 (chronology)
standardization of
- uses `#getcarddata` extension ...
- extension seems to not work but on one page
- oos, suggest to archive/nurke this one entirely
dev
=> feat(infobox): standardize aoe units and hs/artifact/cr card infoboxes

lua/wikis/rocketleague/OpponentDisplay/Custom.lua
remove some RL customization, after checking with the community that it's okay
=> feat(match2): remove player names being links in RL Brackets

lua/wikis/commons/MatchTicker.lua
Since we going through matchFromRecord now, it doesn't like that we nil'd the field here
live
=> fix(matchticker): nil in ffa mode

lua/wikis/commons/MatchSummary/Base/Ffa.lua, lua/wikis/commons/MvpTable.lua, lua/wikis/commons/Widget/Standings/Ffa.lua, lua/wikis/commons/Widget/Standings/MatchOverview.lua, lua/wikis/commons/Widget/Standings/Swiss.lua
None-tbd's will still have links, as that is the default behavior
Match2 FFA change is Live
=> fix: remove force team linking on commons

lua/wikis/commons/Opponent.lua, lua/wikis/commons/OpponentDisplay.lua
reported on discord that all literals are not displayed in brackets:
https://discord.com/channels/93055209017729024/372075546231832576/1396823389171355748
dev
=> fix(opponent): all literals are assumed tbd in BracketOpponentEntry

lua/wikis/commons/Widget/Match/Header.lua
The customizablity of teamstyle was by mistake lost in the new header. The callers still call it, it just wasn't implemented here.
=> feat(match2): customizable teamStyle on popups

lua/wikis/commons/Widget/Match/Card.lua
=> feat: change the highlight to only be the tournament  bar

lua/wikis/commons/Widget/Match/Summary/Characters.lua, stylesheets/commons/Bracket.less, stylesheets/commons/Brackets.less
Hide on mobile no longer works, but since we have multiple of them, switch to one that works and remove the specific one for match2
dev tools
=> fix(match2): hide on mobile not working

stylesheets/commons/Match.less
the CTA text hider only targeted exactly 3 streams, instead of 3+. This fixes it
devtools
=> fix(matchticker): CTA text is showing when there's 4+ streams

lua/wikis/commons/MatchSummary/Starcraft.lua, lua/wikis/stormgate/MatchSummary.lua, lua/wikis/warcraft/MatchSummary.lua, stylesheets/commons/Brackets.less
due to recent changes the veto header now has a not so nice margin/padding issue
to solve that remove the usage of `.brkts-popup-sc-game-header`
also bold the veto header to amke clear it is a header...
additionally kick some unused classes
dev tools
before:
after:
=> feat(match2): improve map veto header on SC2

lua/wikis/commons/Widget/Match/Summary/GameWinLossIndicator.lua, stylesheets/commons/Brackets.less
We want the size to be 14px (0.875rem), not the 110% of 11px.
devtools
=> feat(match2): increase the winloss icon size

lua/wikis/hearthstone/MainPageLayout/data.lua
Classes count on main page use wrong category (Classes instead of Class), so it shows 0 instead of 11
https://liquipedia.net/hearthstone/User:Nikita_r28/test
=> fix(mainpage): fix classes count g:hearthstone

lua/wikis/wildrift/MainPageLayout/data.lua, stylesheets/commons/Banner.less
New Main Page for Wild Rift 
1.Due to the very low amount of tournaments, this is why days are set to 60 
(at the time of this writing, setting both to 60 shows up only 12 tournaments so it will be fine) 
2.Most of pills images are .jpg due to it's existing photos from 2022
https://liquipedia.net/wildrift/User:Hesketh2/test
More of new main page will come flooding in the coming days and week to keep up with the recent design changes. Most of Mobile games page setup will be on me
=> feat(mainpage): Add Wild Rift

lua/wikis/chess/MainPageLayout/data.lua
Applying changes from #6256 to chess wiki
Was looking into why #6244 hadn't deployed after merging, likely this is the reason?
Not tested - only deploy header changed
=> chore(mainpage): fix deploy header in chess data

stylesheets/commons/Brackets.less
- Add a background-color to the thumbs in cases where the images are transparent (like valorant).
- Moved the hover into a css media feature
devtools
=> feat(match2): add bg color to thumbs

lua/wikis/commons/MatchesScheduleDisplay.lua
Oversight from #6030
Because only the timestamp was passed in for countdown, the actual date was not shown if time zone adjustment was disabled in preferences. This PR adds `date` fallback to fix such behavior.
dev
=> fix: match date not shown in schedules display if time zone adjustment is disabled

lua/wikis/clashroyale/MainPageLayout/data.lua
Image change on the statistics pill as I was pointed having 2 pills from TL players might be a bit too unbalance, so a suggestion were to use another team on it instead
**Edit**: We were also suggested to ramp up the Upcoming days significantly, because the low number of tournaments. So we are bumping both to 60
=> feat(mainpage): Clash Royale tweaks

lua/wikis/commons/Widget/Match/VodsDropdown.lua, stylesheets/commons/Miscellaneous.less
Fixes:
Vod Dropdown Active state was reversed
Missing number of vods when active
the VOD icon selector was wrong
live/devtools
=> fix: reverse active logic on vod dropdown btn & darkmode

lua/wikis/warcraft/MainPageLayout/data.lua, lua/wikis/warcraft/Widget/W3EloRanking.lua, lua/wikis/warcraft/Widget/W3EloStandings.lua, stylesheets/commons/Mainpage.less
[Context](https://discord.com/channels/93055209017729024/161454541009715200/1400501452174004314)
This PR:
- Rewrites [Module:W3InfoElo](https://liquipedia.net/warcraft/Module:W3InfoElo) and adds it to this repository
- Updates Warcraft main page to use the above widget
- Throws away css classes that hide some of the rankings
dev + browser dev tools
=> feat(mainpage): show top 10 players in Warcraft ELO ranking

stylesheets/commons/Brackets.less
reported on discord: https://discord.com/channels/93055209017729024/372075546231832576/1402207585645498389
currently scores are compressed and running into player names/flags/factionIcons in the headers of submatches on craft wikis
this pr applies a temp solution of just applying a padding to those scores
the changed classes are not used ouside of this use case (according to a search in vscode)
hence it should only have impact on thse headers on craft wikis
proper solution would be to completely rework the headers of submatches on craft wikis but i currently do not have the time for that
dev tools
=> fix(match2): scores of submatch headers compressed

lua/wikis/commons/Widget/Ratings/List.lua
The backend streak calculations are often wrong, so we decided to remove it temporarily
dev
=> feat: remove streak from dota2  ratings

stylesheets/commons/BigMatch.less
Thought the current pills were a bit shrink-wrapped and could use with a tiny bit more padding in the pill around the text, static width also means the pills have equal size for both loser and winner pills.
=> feat(match2): make Winner/Loser pills in dota2 match page prettier

lua/wikis/commons/TransferList.lua
Regression from #6286:
When removing the initial query i forgot to add the primary teams to the cache/conditions for grouping.
Apparently the testpage only had transfer where roles were involved, so i didn't see this initially.
dev
=> fix(TransferList): Missing grouping on main teams

lua/wikis/rocketleague/YearsActive.lua
oversight in #6186
RL accessed the `ActiveYears.startYear` which was removed form the base.
This PR makes RL use `Info.startYear` (which was what got pushed into `ActiveYears.startYear` anyways)
additionally use Lua.import while at it
live
=> fix: accessing undefined variable in RL `Module:YearsActive`

lua/wikis/commons/TransferList.lua
When switching from multi-query to single query, i also missed that this influences the application of the limit parameter:
Old version would limit the amount of transfer rows (roughly), new version limits to the exact amount of persons.
dev
=> fix(TransferList): Restore behavior for display limit

lua/wikis/commons/Widget/Infobox/Location.lua
country category should be plural instead of singular
this pr adjusts the postfix to be plural
planned follow up (likely tomorrow):
- rename props params a bit
- remove option to not set category
- set category on series infobox via it too and hence be able to kick a function
- needs decision if we want to change the category postfix for it
live
=> fix(infobox): country category singular

lua/wikis/commons/Infobox/Extension/TeamHistoryAuto.lua
reported on discord
dev into live
=> fix(infobox_extension): Missing team display for THA rows with role

lua/wikis/apexlegends/Infobox/League/Custom.lua
1) Added darkmode icon because lightmode icon is almost invisible in darkmode (code taken from brawlstars module)
2) Fixed typo in company name (electroniRc)
https://liquipedia.net/apexlegends/User:Nikita_r28/test
https://liquipedia.net/apexlegends/Module:Infobox/League/Custom/dev/r28
=> feat(infobox): darkmode EA icon for apex infobox league 

lua/wikis/commons/Links.lua
As per request on discord: https://discord.com/channels/93055209017729024/268719633366777856/1404192898819424467
As per discussion in last weeks modules sync we allow new links for hub wiki as long as they do not overwrite existing ones.
N/A just data
=> feat: add h3gg link support in matches

lua/wikis/warcraft/MatchSummary.lua, stylesheets/commons/Brackets.less
Adjust hero icon sizes on FFA tables        
On WC3 wiki, can remove the colored outline for all use cases, there is no "side" in a game of WarCraft 3
dev & devtools respecitively
=> feat(match2): adjust icon sizes on WarCraft 3 for FFA

lua/wikis/easportsfc/GetMatchGroupCopyPaste/wiki.lua
Can't remember why it was setup that way because nowaday it should be able to to just mark finished in the map 
and it will apply the series score & finished status accordingly witthout having to set it manually at match level anymore.
=> feat(copypaste) move finish param to map for FC

lua/wikis/commons/MatchSummary/Base.lua, lua/wikis/commons/Widget/Match/ButtonBar.lua
Remove the t-2h logic and always show stream links in match summary popups, but keep the t-2h logic on other places
=> feat(match2): always show streams in match popups (when variant is primary)

lua/wikis/chess/Info.lua, lua/wikis/chess/Infobox/Person/Player/Custom.lua
This is a re-created PR  of the closing one, due to Ratings implementation is on indefinite freezer.
**Infobox code was made in February, please account this into any potential spots that may be replaced by newer standardizations**
The only customization in here is the new **Title** section, detailing the exact year a player has recieved a chess title. 
Three are included: Grandmaster, International Master and FIDE Master. 
Additionally for Female players they can have another 3 more being Female only variation of those (maximum of 6, but in all players pages, Four listings are the furthest so far)
In previous PR, hjp suggested titles to be under achievements section, but I'm not sure how to do it as they arent populate by auto through tournaments (and if it displays properly, where …
=> feat(Infobox): Add Infobox player for chess

lua/wikis/commons/Namespace.lua, lua/wikis/commons/Standings/Parse/Lpdb.lua, lua/wikis/commons/Standings/Parse/Wiki.lua
Currently Standings are only abel to query from main space.
As per mentions on discord we likely should allow querying from non main space.
This PR allows querying from any main space when retrieving the match data for standings.
Additional changes:
- use `Module:Condition` to build the conditions in some places in Standings modules
- simplify some code
- slap Array.unique around the matches to make sure we do not have duplicate matches listed
- allow new input `|stages=`
- comma sep list of pagenames with potentially stages (`nameSpace:pagename#stage`)
- intended usage: import all matches from a stage/page into a round
- fetches up to 1k matchIds from a given stage/pagename and extends the matches array with those
**lmk if the stage stuff is not wanted, not maried to it :P**
dev (preview …
=> feat(standings): Improve standings query options

lua/wikis/commons/MatchGroup/Input/Util.lua
see https://github.com/Liquipedia/Lua-Modules/pull/6367#discussion_r2268269756
dev in LoL
=> refactor(match2): remove hardcoded match namespace id

lua/wikis/commons/OpponentDisplay/Starcraft.lua
resolves #6393 
- catch the literal case (identical to default opp display)
- extend the `OpponentDisplay.BracketOpponentEntry` class instead of making a completely new one
- simplify due to that
- drop `hasFactionOrFlag` stuff (it is never set anymore, seems it got removed in some of the match2 refactors)
(sadly still can't just use default opp display due to archon and score stuff)
dev to live
=> fix(match2): resolve #6393

lua/wikis/commons/MatchGroup/Display/Helper.lua
This PR replaces custom date string building logic in `DisplayHelper.MatchCountdownBlock` with `DateExt.toCountdownArg`
dev
=> refactor(match2): use DateExt.toCountdownArg in display helper

lua/wikis/commons/Flags/MasterData.lua
Previously HKTW was linked [as a separate flag](https://liquipedia.net/commons/TemplateArchive:Flag/hktw) from East Asia, however with the use of a Master Data Module, it now uses an East Asia flag instead. Thinking to revert the change.
=> feat(flag): Split HKTW from East Asia flag

lua/wikis/commons/OpponentDisplay/Starcraft.lua
never set (anymore) we removed it in all other places already, but this seems to have been missed
untested, but trivial
=> chore: remove last `hasFactionOrFlag` in sc(2)

lua/wikis/commons/ResultsTable/Base.lua
Closes #6390
Removes the implicit-added 'TBD' opponent and replaces it with a dash instead, similar to the display for no prize.
via dev (will add screenshots later today)
=> fix: Remove "tbd" results display in ResultsTable

lua/wikis/pokemon/Info.lua
- Info had a huge rework by adding icons of all remaining games that didn't added with new main page PR. I finally had time to start exploring on it
- 2 new games added: a New one and one missed on the module
- (Mainpage) the filter buttons now have a new entry for `Champions` as they will be the new game to be played on next year, however as `Scarlet & Violet (SV)` events are still running until the new game transition happened, they will still both appear and SV will disappear at a later point after they completely stopped hosting events under SV version
I don't feel like breaking these into two PR because it feeds over on each other
=> feat: add icons for Pokemon

lua/wikis/commons/TransferList.lua
Another mishap from changing how grouping works:
In some situations it was possible that the last transfer group got duplicated, because the last group would always get added past the loop.
This can be removed, as the loop is stopped when the amount of groups hits the configured limit; which already includes the last group.
dev
Before:
After:
=> fix: Do not duplicate last group in transfer list

lua/wikis/commons/Opponent.lua
when accessing extradata that might be nil we currently get an error
this pr fixes that issue
reported on discord: https://discord.com/channels/93055209017729024/372075546231832576/1410799673333256284
live
=> fix: missing nil catch in opponent module

lua/wikis/commons/Widget/Infobox/UpcomingTournaments/Row.lua, lua/wikis/commons/Widget/Misc/DateRange.lua
This PR removes custom string building logic in the upcoming and ongoing tournaments widget, replacing it with `Module:Widget/Misc/DateRange`.
dev
=> refactor(infobox): use daterange widget in upcoming and ongoing tournaments widget

lua/wikis/pubgmobile/MainPageLayout/data.lua
main page was using the PC version of the map, pr switches to mobile version instead
browser dev tool
=> fix(mainpage): incorrect map in pubgm main page

lua/wikis/splatoon/MatchSummary.lua
Changes for these were done by slothyman
Splatoon match2 has an issue where if map template exist, but at least one of it does not have a map name added , the match summary will throw an error. 
The fix originally is to use the DisplayHelper to do that, however that creates another issue where the score and checkmark is not consistent
slothy rework a lot of it to use html widgets to fix it while also keeping it visually the same
Additionally this also removes the usage for the local version of **Module:MapType** as well, it will now just use **Module:MapModes** properly for the mode icons
https://liquipedia.net/splatoon/Splatoon_2_World_Championship/2018
I'm not sure which is Slothy's github name, otherwise I would added him to the assignees
=> refactor(match2): splatoon map display rework

lua/spec/helpers/test_helper.lua
This makes inability to import behave better in the CI pipeline.
Currently a print would cause the output to not be able to be read, which just made it fail without an error.
This makes the error clear
=> ci: change failure to import from a print to error

lua/wikis/chess/Infobox/Person/Player/Custom.lua, lua/wikis/chess/PlayerIntroduction/Custom.lua
requested on discord.
Start of convo https://discord.com/channels/93055209017729024/1333849898583330947/1406973862096146514
Pretty much chess used their custom stuff in the their infobox and didn't use {{PlayerIntroduction}} template at all.
Now they replaced all text with that template, but they several issue with it.
Duplicate names + They would like instead "player" say "chess + title". 
Also included that for banned users it just say "chess player"
Would love help with coding or maybe better idea how to handle this?
https://liquipedia.net/chess/Hikaru_Nakamura
https://liquipedia.net/chess/Igors_Rausis
dev
=> feat: Add custom PlayerIntroduction to chess

lua/wikis/crossfire/FilterButtons/Config.lua, lua/wikis/crossfire/Info.lua
CrossFire houses coverage of 3 different game versions, however on this one I decide to use the **Abbreviation** from Module:Info instead of icons. This is because even with finding the exact logo of these three, they are actually all using the same logo so icons would not work in this case. 
dev
I am completely not sure on the Game.abbreviation returns if that code line needs adjustment, I just copied over from other filters that uses game icons and I replace it to abbreviation
=> feat(mainpage): Add game filters for Crossfire

stylesheets/commons/BigMatch.scss
This PR applies the new match summary design from #6187 to match page footers.
=> feat(match2): new design for matchpage footers

lua/wikis/brawlstars/Infobox/Person/Player/Custom.lua, lua/wikis/dota2/Infobox/Team/Custom.lua, lua/wikis/rainbowsix/Infobox/Person/Player/Custom.lua, lua/wikis/wildrift/Infobox/Person/Player/Custom.lua
resolves #6495
after merge: `python pwb.py replace -lang:dota2 -regex -transcludes:"Infobox team" "{{[uU]pcoming[_ ]and[_ ]ongoing[_ ]tournaments[_ ]of}}\n?" "" -summary:"cleanup upcoming tournaments template usage"`
dev
=> refactor(infobox): use standardized match ticker / widget for infobox footer

lua/wikis/commons/Widget/Transfer/Row.lua
This PR:
- replaces two helper functions that are specific to rumor display with one function
- memoizes icon getters instead of creating one for every function call
smoke
=> refactor(transfer): clean up transfer row widget implementation

lua/wikis/commons/Countdown.lua, lua/wikis/commons/MatchGroup/Display/Matchlist.lua, lua/wikis/commons/MatchPage/Base.lua, lua/wikis/commons/MatchTable.lua, lua/wikis/commons/MatchTicker/DisplayComponents.lua, lua/wikis/commons/MatchesScheduleDisplay.lua, lua/wikis/commons/Widget/Infobox/UpcomingTournaments/Row.lua, lua/wikis/commons/Widget/Match/Countdown.lua, lua/wikis/commons/Widget/Match/Summary/Ffa/GameCountdown.lua, lua/wikis/lab/Widget/ProjectOverview.lua, lua/wikis/starcraft2/Infobox/League/Custom.lua, lua/wikis/warcraft/Infobox/League/Custom.lua
This PR wraps `Module:Countdown` with `Class.export`, and updates existing uses accordingly.
Non-git uses of `Countdown._create` have to be updated after merge
trivial
=> chore: wrap Countdown with Class.export

lua/wikis/commons/MatchPage/Base.lua
This PR:
- hides matchpage footer if there is no information to display  
currently it displays header regardless of information availability
- wraps external link icons with `Span`  
there were extra gaps being inserted for every non-`allmode` icon, and wrapping light/darkmode icons with extra `Span` mitigates the issue
dev
=> fix(match2): matchpage footer being displayed even if it has no content

lua/wikis/commons/Icon/Data.lua
context: https://discord.com/channels/93055209017729024/1400382174078832670/1414634994659233823
This PR updates arrow icons used in transfer rows. Specifically:
- solid icons are replaced with regular icons
- switches from-team and to-team icons
- Current  
- This PR  
dev
=> feat(transfer): update transfer arrow icons

lua/wikis/fighters/Info.lua
Adding major fighting game releases that are currently missing from this module/Fighters coverage.
Ref on discord: https://discordapp.com/channels/93055209017729024/202549269134180352/1413938982076551178
Full list:
Aquapazza: Aquaplus Dream Match (2011)
Arcana Heart (2007)
Arcana Heart 2 (2008)
Art of Fighting 3 (1996)
Capcom Fighting Jam (2004)
Fate/unlimited codes (2008)
Melty Blood Act Cadenza (2005)
Mortal Kombat 3 (1995)
Neo Geo Battle Coliseum (2005)
Samurai Shodown V (2003)
Samurai Shodown VI (2005)
Sengoku Basara X (2008)
Soulcalibur III (2005)
The King of Fighters 2003 (2003)
The King of Fighters Neowave (2005)
The King of Fighters XI (2005)
The King of Fighters XII (2009)
X-Men vs. Street Fighter (1996)
All games on this list were releases by major fighting game developers like …
=> feat: add missing major fighting games data

stylesheets/commons/Match.scss
The tournament image and text are not vertically aligned.
devtools
Current:
New:
=> fix(matchticker): align tournament name and image

lua/wikis/commons/Widget/Basic/Button.lua, lua/wikis/commons/Widget/Match/ButtonBar.lua, lua/wikis/commons/Widget/Match/VodButton.lua
Currently, the vod buttons in the vod dropdowns don't display as intended.
dev: https://liquipedia.net/dota2/User:Eetwalt
Design for reference:
=> fix: display buttons correctly on the vod dropdown

stylesheets/commons/Brackets.scss
Regression from #6514
Report on discord: https://discord.com/channels/93055209017729024/372075546231832576/1414976233397293086
=> fix(match2): map veto type not readable in light theme

lua/wikis/commons/MvpTable.lua, lua/wikis/commons/ParticipantTable/Base.lua, lua/wikis/commons/PrizePool/Import.lua, lua/wikis/commons/TournamentStructure.lua
This PR adds type alias for `MatchGroupsSpec` in `Module:TournamentStructure` and updates its consumers accordingly.
N/A
=> docs: type annotation for MatchGroupsSpec

lua/wikis/commons/Infobox/Extension/TeamHistory/Manual.lua
stacked on #6536
regression of #6388
missed that the second date coiuld also start with a questionmark instead of a number
live
=> fix: TH erroring if second date starts with `?`

lua/wikis/marvelrivals/MainPageLayout/data.lua
Update the banner images on the marvelrivals mainpage, they are currently still using photos from overwatch
no negative feedback from contributors
dev
=> feat(mainpage): Update images on marvelrivals mainpage

lua/wikis/valorant/MatchPage.lua
small oversight from #6558
dev
=> fix(match2): league icon not read properly in valorant matchpage under light theme

lua/wikis/apexlegends/Infobox/Person/Player/Custom.lua, lua/wikis/apexlegends/Infobox/Team/Custom.lua
Rquested on discord: 
https://discord.com/channels/93055209017729024/545651077710872576/1415959687110852705
They would like to include both S/A tier tournaments.
Example of page with most achievements for both tiers.
Most of the players doesn't have that many achievements. Mostly 3-5 with both tiers
dev
=> feat(infobox): Add automatic achievements for Apex legends

lua/wikis/easportsfc/Infobox/League/Custom.lua
Making the infobox to display Mobile tournaments
EA Sports FC Mobile tournaments have been covered since 2024, yet the Mobile platform is not included in the infobox.
I added "mobile = 'Mobile'," into the original module
=> feat: support mobile tournament on ea fc in the infobox

stylesheets/commons/BigMatch.scss
=> fix(match2): win/loss indicator in matchpage header overflows at certain width

stylesheets/commons/Crosstable.scss
`@extend` has shown to be excruciatingly slow in scssphp:2, removing its usage makes the output CSS a bit bigger but improves performance by literally minutes.
I built a command line profiler around the same library we use on production
Compilation time with scssphp:1
Compilation time with scssphp:2
scssphp:2 with extend ran long enough that I ran out of patience and killed it, I waited for at least 5 minutes though.
=> perf: remove usage of @extend in crosstable.scss

lua/wikis/commons/MainPageLayout.lua, lua/wikis/commons/Widget/Grid/Cell.lua, lua/wikis/dota2/MainPageLayout/data.lua, lua/wikis/hearthstone/MainPageLayout/data.lua, lua/wikis/wildrift/MainPageLayout/data.lua, stylesheets/commons/BattleRoyale/NavigationTabs.scss, stylesheets/commons/BootstrapVisibility.scss, stylesheets/commons/Grid.scss, stylesheets/commons/Miscellaneous.scss, stylesheets/commons/NavigationCard.scss
New viewports, so our pages look good on all types of devices. Currently, especially on smaller viewport sizes, content get's squished and unreadable on certain pages. Also, content on really large screen gets stretched and hard to read. We aim to improve this by tweaking the responsivity on smaller breakpoints, and introducing content centering on larger breakpoints.
Note that these Module changes don't reflect reality in isolation, as there are changes needed to the wiki skin layout together with the module changes.
This PR needs to be merged in sync with skin and extension changes.
New viewports:
Large viewport variants we are looking to A/B test on different wikis:
Large viewport variants are applied to the following wikis:
Option A: See …
=> feat: adjust breakpoints

javascript/commons/Collapse.js
We felt it was a bit too big with medium based on its placement
devtools
=> feat: change toggle btn to show/hide all matchlists to small
